#!/usr/bin/env python3
"""Identities by reflection for the checked computation [L]B = O (lbt.src):
proofs/crypto/ed25519/group/id_lb.bend. See idlib.py.

  python3 tools/generators/ed25519_group/gen_ids_p.py
"""
from idlib import Ctx


def main():
    c = Ctx(['c'])
    v = c.var('c')
    c.ident('dy_one', c.add(c.sub(c.const(1), v), v), c.const(1), (), '(1 - c) + c == 1: the denominator dy = 1 - c')
    c.write('id_lb.bend', '# GENERATED by tools/generators/ed25519_group/gen_ids_p.py\n# Identities for lbt.bend.\n')


if __name__ == '__main__':
    main()
