#!/usr/bin/env python3
"""Certificates for edwards25519, as Bend files (proofs/crypto/ed25519/group/cert_*.bend).

  python3 tools/generators/ed25519_group/gen_cert.py [p] [l] [d] [i]

  p   Pocklington chain: p = 2^255 - 19 is prime                 (cert_p.bend)
  l   Pocklington chain: the group order L is prime             (cert_l.bend)
  d   d^((p - 1) / 2) mod p (== p - 1: d is not a square)       (cert_d.bend)
  i   2^((p - 1) / 4) mod p (a square root of -1)               (cert_i.bend)

The generator is the secp256k1 one (tools/generators/secp256k1_group/gen_cert.py,
same checked step lists on proofs/crypto/secp256k1/group/bn.bend and the same
theorem, proofs/math/number/nt_pock.bend); nothing here is trusted.
"""
import os, sys
HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, os.path.join(HERE, '..', 'secp256k1_group'))
import gen_cert as G

G.OUT = os.path.join(HERE, '..', '..', '..', 'proofs', 'crypto', 'ed25519', 'group')
G.HEAD = '''# GENERATED by tools/generators/ed25519_group/gen_cert.py; edit the generator
import Base
import ../../secp256k1/group/bn.bend as B
import ../../secp256k1/group/bnx.bend as X
import ../../secp256k1/group/certl.bend as CL
import ../../../math/number/nt_prime.bend as PM
import ../../../math/number/nt_pock.bend as PK

# %s
# Every literal below (quotients and remainders of each squaring, bases,
# Bezout witnesses) is checked by closed computation on bn.bend's binary
# numbers; the numbers are X.bvalo(one, literal), never expanded.
'''

P = 2**255 - 19
L = 2**252 + 27742317777372353535851937790883648493
D = (-121665 * pow(121666, -1, P)) % P

if __name__ == '__main__':
    which = sys.argv[1:] or ['p', 'l', 'd', 'i']
    if 'p' in which:
        print(G.write('cert_p.bend', 'Pocklington certificate: p = 2^255 - 19 is prime', P))
    if 'l' in which:
        print(G.write('cert_l.bend', 'Pocklington certificate: the group order L = 2^252 + 27742317777372353535851937790883648493 is prime', L))
    if 'd' in which:
        c = G.write_pow('cert_d.bend', 'd^((p - 1) / 2) mod p, for d = -121665 / 121666', D, (P - 1) // 2, P)
        assert c == P - 1
    if 'i' in which:
        c = G.write_pow('cert_i.bend', '2^((p - 1) / 4) mod p', 2, (P - 1) // 4, P)
        assert c * c % P == P - 1
        print('sqrt(-1)', c)
