#!/usr/bin/env python3
"""[L]B = O for the base point of edwards25519, by checked computation.

  python3 tools/generators/ed25519_group/gen_lb.py [OPS]

writes proofs/crypto/ed25519/group/lblits.bend (the chain's cut points),
lb_NN.bend (one independent root per segment of at most OPS group
operations: LK.Reach from one cut to the next, a closed evaluation of
lbk.bend's checker on the literals below) and lbz.bend (the conclusion, from
the segments' Reach as hypotheses, by lbt.bend's soundness).

The chain is double-and-add on the bits of L, most significant first:
[n]B -> [2n]B (D) and [n]B -> [n + 1]B (A), affine, each operation with its
result and the quotients of lbk.bend's check. Nothing here is trusted:
a wrong literal fails a segment's check.
"""
import os, sys
HERE = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.join(HERE, '..', '..', '..', 'proofs', 'crypto', 'ed25519', 'group')

P = 2**255 - 19
L = 2**252 + 27742317777372353535851937790883648493
D = (-121665 * pow(121666, -1, P)) % P
BX = 15112221349535400772501151409588531511454012693041857206046113283949847762202
BY = 46316835694926478169428394003475163141307993866256225615783033603165251855960
OPS = 28


def raw(v):
    s = 'B.BZ{}'
    bits = []
    while v:
        bits.append(v & 1)
        v >>= 1
    for b in reversed(bits):
        s = ('B.B1{%s}' if b else 'B.B0{%s}') % s
    return s


def add(p, q):
    """(x3, y3) and the quotients kt, jx, kx, ky of lbk.bend's step"""
    (x1, y1), (x2, y2) = p, q
    kt, t = divmod(D * ((x1 * x2) * (y1 * y2)), P)
    nx, ny = x1 * y2 + y1 * x2, y1 * y2 + x1 * x2
    x3 = nx * pow(1 + t, -1, P) % P
    y3 = ny * pow(1 - t, -1, P) % P
    kx, r = divmod((1 + t) * x3 - nx, P)
    assert r == 0
    jx, kx = (0, kx) if kx >= 0 else (-kx, 0)
    ky, r = divmod(ny + t * y3 - y3, P)
    assert r == 0 and ky >= 0
    return (x3, y3), (kt, jx, kx, ky)


def chain():
    """[(op, n, (x, y), (kt, jx, kx, ky))]: the states after each operation, from (1, B)"""
    n, pt, out = 1, (BX, BY), []
    for b in bin(L)[3:]:
        pt, ks = add(pt, pt)
        n = 2 * n
        out.append(('D', n, pt, ks))
        if b == '1':
            pt, ks = add((BX, BY), pt)
            n += 1
            out.append(('A', n, pt, ks))
    assert n == L and pt == (0, 1), pt
    return out


HEAD = '''# GENERATED by tools/generators/ed25519_group/gen_lb.py; edit the generator
import Base
import ../../secp256k1/group/bn.bend as B
'''


def main():
    ops = int(sys.argv[1]) if len(sys.argv) > 1 else OPS
    only = sys.argv[2:]          # segment numbers, for tests
    ch = chain()
    nseg = -(-len(ch) // ops)
    size = -(-len(ch) // nseg)   # balanced
    segs = [ch[i:i + size] for i in range(0, len(ch), size)]
    # cut k: the state after segment k - 1 (cut 0 is (1, B), the last is (L, (0, 1)))
    cuts = [('B.B1{B.BZ{}}', 'PL.bxl()', 'PL.byl()')]
    lits = [HEAD, '# The cut points of the chain [1]B -> [L]B of lb_NN.bend: [nK]B == (xK, yK).', '']
    for k, s in enumerate(segs[:-1]):
        _, n, (x, y), _ = s[-1]
        for nm, v in (('n', n), ('x', x), ('y', y)):
            lits.append('def %s%d() -> B.Bn:\n  %s\n' % (nm, k + 1, raw(v)))
        cuts.append(tuple('LL.%s%d()' % (nm, k + 1) for nm in 'nxy'))
    cuts.append(('PL.ll()', 'B.BZ{}', 'B.B1{B.BZ{}}'))
    open(os.path.join(OUT, 'lblits.bend'), 'w').write('\n'.join(lits))
    head = HEAD + 'import ./plits.bend as PL\nimport ./lblits.bend as LL\nimport ./lbk.bend as LK\n'
    for k, s in enumerate(segs):
        if only and str(k) not in only:
            continue
        body = ', '.join('LK.%s{%s}' % (op, ', '.join(raw(v) for v in (x, y) + ks)) for op, n, (x, y), ks in s)
        text = head + '''
# Segment %d of %d of the chain [1]B -> [L]B (%d operations, up to the scalar
# %d):
# the checker of lbk.bend accepts them, by closed computation.

def ops() -> List<&2, LK.Op>:
  [%s]

def seg() -> LK.Reach(%s, %s):
  (ops(), {==})
''' % (k, len(segs), len(s), s[-1][1], body, ', '.join(cuts[k]), ', '.join(cuts[k + 1]))
        open(os.path.join(OUT, 'lb_%02d.bend' % k), 'w').write(text)
    hyps = ''.join(', +r%d: LK.Reach(%s, %s)' % (k, ', '.join(cuts[k]), ', '.join(cuts[k + 1])) for k in range(len(segs)))
    term = 'LT.pt_one(one, h1, hc)'
    for k in range(len(segs)):
        term = 'LT.reach(one, h1, hc, %s, %s, %s, r%d)' % (', '.join(cuts[k]), ', '.join(cuts[k + 1]), term, k)
    mp, d = 'X.bvalo(one, PF.p1l())', 'X.bvalo(one, PF.dl())'
    open(os.path.join(OUT, 'lbz.bend'), 'w').write(head + '''import ../../secp256k1/group/bnx.bend as X
import ../../../../spec/crypto/curve25519/edwards.bend as G
import ./pfacts.bend as PF
import ./lbt.bend as LT

# [L]B == O: the base point B of edwards25519 has order dividing L (the
# group order, PF.ll()), from the %d checked segments lb_NN.bend of the
# chain [1]B -> [L]B (hypotheses: each is the `seg` of an independent root)
# and the parameters of the curve.

def lbz(+one: Nat, +h1: {one == 1n : Nat}, +hc: G.Curve(%s, %s)%s) -> {G.nmul(1n+%s, %s, X.bvalo(one, PF.ll()), G.APt{X.bvalo(one, PF.bxl()), X.bvalo(one, PF.byl())}) == G.azero() : G.APt}:
  LT.lb_fin(one, h1, hc, %s)
''' % (len(segs), mp, d, hyps, mp, d, term))
    print(len(ch), 'operations,', len(segs), 'segments of', size)


if __name__ == '__main__':
    main()
