#!/usr/bin/env python3
"""Certificates for edwards25519, as Bend files (proofs/crypto/ed25519/group/cert_*.bend).

  python3 tools/generators/ed25519_group/gen_cert.py [lits] [p] [q] [l] [d] [i]

  lits  plits.bend: the literals every certificate and pfacts.src name (PL.pl(), ...)
  p     p = 2^255 - 19 is prime, given that q1 (the big prime factor of
        p - 1) is                                                 cert_p.bend
  q     q1 is prime: its Pocklington step, given its two prime factors
        and 2^(q1 - 1) == 1                                       cert_q.bend
        2^(q1 - 1) == 1 (mod q1), and the 55-bit factor is prime  cert_q1.bend
        the 116-bit factor is prime                               cert_q2.bend
  l     the group order L is prime, given 2^(L - 1) == 1 and the
        88-bit prime of its chain                                 cert_l.bend
        2^(L - 1) == 1 (mod L), and the 88-bit prime              cert_l1.bend
  d     d^((p - 1) / 2) mod p == p - 1 (d is not a square), given
        the first half of the computation                         cert_d.bend
        the first half                                            cert_d0.bend
  i     2^((p - 1) / 4) mod p (a square root of -1)               cert_i.bend

Every file is an independent proof root (none imports another; each stays
near 300 steps of 255 bits, which is what a root can hold in 800 MB): a
certificate that is too heavy for one root is cut, and the upper part takes
the conclusions of the lower parts as hypotheses, stated on the literals of
plits.bend, which both name.

The step lists, the literals and the glue are those of the secp256k1
generator (tools/generators/secp256k1_group/gen_cert.py, on
proofs/crypto/secp256k1/group/bn.bend, with the theorem of
proofs/math/number/nt_pock.bend); nothing here is trusted. Factorizations
that sympy does not find quickly are in KNOWN (checked below: the product
is asserted, the primality of each factor is what the certificate proves).
"""
import os, sys
from sympy import factorint
HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, os.path.join(HERE, '..', 'secp256k1_group'))
import gen_cert as G

G.OUT = os.path.join(HERE, '..', '..', '..', 'proofs', 'crypto', 'ed25519', 'group')
G.HEAD = '''# GENERATED by tools/generators/ed25519_group/gen_cert.py; edit the generator
import Base
import ../../secp256k1/group/bn.bend as B
import ../../secp256k1/group/bnx.bend as X
import ../../secp256k1/group/certl.bend as CL
import ../../../math/number/nt_prime.bend as PM
import ../../../math/number/nt_pock.bend as PK
import ./plits.bend as PL

# %s
# Every literal below (quotients and remainders of each squaring, bases,
# Bezout witnesses) is checked by closed computation on bn.bend's binary
# numbers; the numbers are X.bvalo(one, literal), never expanded.
'''

P = 2**255 - 19
L = 2**252 + 27742317777372353535851937790883648493
D = (-121665 * pow(121666, -1, P)) % P
I = pow(2, (P - 1) // 4, P)
Q1 = 74058212732561358302231226437062788676166966415465897661863160754340907   # p - 1 = 2^2 * 3 * 65147 * Q1
Q116 = 75445702479781427272750846543864801          # Q1 - 1 = 2 * 3 * 353 * 57467 * Q116 * Q55 ...
Q55 = 31757755568855353
L88 = 172054593956031949258510691                   # in L's chain: L - 1 <- 276602624281642239937218680557139826668747 <- 19757330305831588566944191468367130476339 <- L88
assert (P - 1) % Q1 == 0 and (Q1 - 1) % (Q116 * Q55) == 0 and I * I % P == P - 1

# n -> the factorization of n - 1, where sympy is slow
KNOWN = {
    L: {2: 2, 3: 1, 11: 1, 198211423230930754013084525763697: 1, 276602624281642239937218680557139826668747: 1},
}


def fact(m):
    f = KNOWN.get(m + 1)
    if f is None:
        return factorint(m)
    x = 1
    for q, e in f.items():
        x *= q ** e
    assert x == m, m
    return f


G.factorint = fact

# d^((p - 1) / 2): the state after the first DCUT steps
_st = G.steps(D, (P - 1) // 2, P)[0]
DCUT = len(_st) // 2
DM, DE = _st[DCUT - 1][1], _st[DCUT - 1][2]

# plits.bend: name -> (value, comment)
LITS = [
    ('pl', P, 'p = 2^255 - 19'),
    ('p1l', P - 1, 'p - 1'),
    ('p2l', P - 2, 'p - 2'),
    ('p3l', P - 3, 'p - 3'),
    ('p5l', P - 5, 'p - 5'),
    ('hl', (P - 1) // 2, '(p - 1) / 2'),
    ('q4l', (P - 1) // 4, '(p - 1) / 4'),
    ('e58l', (P - 5) // 8, '(p - 5) / 8'),
    ('q1l', Q1, 'q1, the big prime factor of p - 1 = 2^2 * 3 * 65147 * q1:\n# %d' % Q1),
    ('q1m1l', Q1 - 1, 'q1 - 1'),
    ('q116l', Q116, 'the two big prime factors of q1 - 1: %d' % Q116),
    ('q55l', Q55, '%d' % Q55),
    ('ll', L, 'the group order L = 2^252 + 27742317777372353535851937790883648493'),
    ('l1l', L - 1, 'L - 1'),
    ('l88l', L88, "a prime of L's Pocklington chain: %d" % L88),
    ('dl', D, 'd = -121665 / 121666 mod p\n#   = %d' % D),
    ('dcl', P - 1 - D, 'p - 1 - d'),
    ('dkl', (121666 * D + 121665) // P, '(121666 d + 121665) / p'),
    ('dml', DM, 'd^dme mod p, the middle of the computation of d^((p - 1) / 2)'),
    ('dme', DE, None),
    ('il', I, 'I = 2^((p - 1) / 4) mod p, a square root of -1\n#   = %d' % I),
    ('icl', P - 1 - I, 'p - 1 - I'),
    ('ikl', (I * I + 1) // P, '(I^2 + 1) / p'),
    ('c5l', 121665, '121665 and 121666'),
    ('c6l', 121666, None),
    ('l2', 2, 'small numbers'),
    ('l4', 4, None),
    ('l5', 5, None),
    ('l8', 8, None),
    ('l19', 19, None),
    ('dm1l', D - 1, 'for cpar.bend (d == -121665 / 121666 as the specification writes it): d - 1'),
    ('dnl', P - 121665, 'p - 121665 == 121666 d mod p'),
    ('dk1l', (121666 * D + 121665) // P - 1, '(121666 d - (p - 121665)) / p'),
    ('c5cl', P - 121666, 'p - 1 - 121665'),
    ('c6cl', P - 121667, 'p - 1 - 121666'),
    ('c4l', 121664, None),
]
NAMES = {v: nm for nm, v, _ in LITS if v >= 2**20}
assert len(NAMES) == len([1 for _, v, _ in LITS if v >= 2**20])


def lit(v):
    """a number of plits.bend by its name there; else as the secp256k1 generator does"""
    if v in NAMES:
        return 'PL.%s()' % NAMES[v]
    return lit0(v)


lit0 = G.lit
G.lit = lit


def pub(v):
    """a literal of a root's interface: it must be one both sides can name"""
    assert v in NAMES or v < 2**20, v
    return lit(v)


def write_lits():
    out = ['# GENERATED by tools/generators/ed25519_group/gen_cert.py (lits); edit the generator',
           'import Base', 'import ../../secp256k1/group/bn.bend as B', '',
           "# edwards25519's constants as binary literals (bn.bend's B.Bn, least",
           '# significant bit outermost): the numbers that the certificates',
           '# (cert_*.bend) and the bridges to the specification (pfacts.bend) both',
           '# name. Only literals: no proof here.', '']
    for nm, v, c in LITS:
        if c:
            out.append('# ' + c)
        out.append('def %s() -> B.Bn:\n  %s\n' % (nm, G.raw(v)))
    open(os.path.join(G.OUT, 'plits.bend'), 'w').write('\n'.join(out))


def inv_type(key):
    a, e, n = key[:3]
    x = key[3] if len(key) > 3 else pow(a, e, n)
    return 'CL.Inv(one, %s, %s, %s, %s)' % (pub(a), pub(n), pub(x), pub(e))


def hyp_decl(hyps, used):
    return ''.join(', +%s: %s' % (hyps[h], inv_type(h) if isinstance(h, tuple) else 'PM.Prime(X.bvalo(one, %s))' % pub(h)) for h in used)


def chain(nm, a, e, n, defs, hyps, lo=0, hi=None):
    """defs nm_0.. proving CL.Inv(one, a, n, x, ex) chunk by chunk, for the steps lo..hi of a^e mod n
    (from a^1 if lo == 0, else from the hypothesis hyps[(a, ex_lo, n, x_lo)]); if the whole chain is
    the hypothesis hyps[(a, e, n)], no def. Returns (the proof term, the hypotheses used, x)"""
    if lo == 0 and hi is None and (a, e, n) in hyps:
        return hyps[(a, e, n)], [(a, e, n)], pow(a, e, n)
    st, x = G.steps(a, e, n)
    if hi is None:
        hi = len(st)
    size = max(16, int(G.CHUNK * (256 / n.bit_length()) ** 2))
    if lo == 0:
        prev, used, px, pe = 'CL.inv0(one, h1, %s, %s)' % (lit(a), lit(n)), [], a, 1
    else:
        px, pe = st[lo - 1][1], st[lo - 1][2]
        key = (a, pe, n, px)
        prev, used = hyps[key], [key]
    decl = hyp_decl(hyps, used)
    args = ''.join(', ' + hyps[h] for h in used)
    for i in range(lo, max(hi, lo + 1), size):
        part = st[i:min(i + size, hi)]
        cx, ce = (part[-1][1], part[-1][2]) if part else (px, pe)
        last = '%s_%d' % (nm, (i - lo) // size)
        defs.append('def %s(+one: Nat, +h1: {one == 1n : Nat}%s) -> CL.Inv(one, %s, %s, %s, %s):\n  CL.ck_o(one, h1, %s, %s, %s, %s, %s, [%s], %s, %s, {==}, %s, {==}, {==})\n' % (
            last, decl, lit(a), lit(n), lit(cx), lit(ce), lit(a), lit(n), lit(n - 1), lit(px), lit(pe), ', '.join(p[0] for p in part), lit(cx), lit(ce), prev))
        prev = '%s(one, h1%s)' % (last, args)
        px, pe = cx, ce
    assert (pe == e and px == x) if hi == len(st) else (px, pe) == (st[hi - 1][1], st[hi - 1][2])
    return prev, used, px


def level(n, defs, done, hyps):
    """append the defs proving Prime(bvalo(one, lit(n))); returns (the proof term, the hypotheses it uses).
    hyps: prime, or chain (a, e, n) -> parameter name, for what the root takes as hypotheses"""
    if n in hyps:
        return hyps[n], [n]
    nm = G.name(n)
    if n in done:
        return done[n]
    if n < G.SMALL:
        defs.append('def %s(+one: Nat, +h1: {one == 1n : Nat}) -> PM.Prime(X.bvalo(one, %s)):\n  CL.sp_o(one, h1, %s, {==})\n' % (nm, lit(n), lit(n)))
        done[n] = ('%s(one, h1)' % nm, [])
        return done[n]
    qs, a = G.plan(n)
    subs, used = [], []

    def use(u):
        used.extend(h for h in u if h not in used)
    for q in qs:
        t, u = level(q, defs, done, hyps)
        subs.append(t)
        use(u)
    out = ['# %d = 1 + %s m, base %d' % (n, ' * '.join(str(q) for q in qs), a)]
    l3, u, x = chain(nm + '_a', a, n - 1, n, out, hyps)
    use(u)
    assert x == 1
    cert = 'PK.cert_nil(X.bvalo(one, %s))' % lit(n)
    tail = 'Nil{}'
    fb, fh, F = 'B.B1{B.BZ{}}', 'X.one_o(one, h1)', 1      # the tail's product: Bn term, proof, value
    fnat = '1n'
    for i in range(len(qs) - 1, -1, -1):
        q = qs[i]
        m = (n - 1) // q
        b = pow(a, m, n)
        u = pow(b - 1, -1, n)
        v = (u * (b - 1) - 1) // n
        l4, u4, x = chain('%s_b%d' % (nm, i), a, m, n, out, hyps)
        use(u4)
        assert x == b
        e2 = 'X.e2_o(one, h1, %s, %s, %s, {==})' % (lit(n), lit(q), lit(m))
        e3 = 'CL.fin3_o(one, h1, %s, %s, %s, %s, %s, %s, %s, {==}, %s, {==}, {==})' % (lit(a), lit(n), lit(n - 1), lit(n - 1), lit(q), lit(m), lit(n - 2), l3)
        e4 = 'CL.fin_o(one, h1, %s, %s, %s, %s, %s, %s, {==}, %s, {==})' % (lit(a), lit(n), lit(n - 1), lit(b), lit(m), lit(n - 1 - b), l4)
        e5 = 'X.e5_o(one, h1, %s, %s, %s, %s, %s, {==}, {==})' % (lit(u), lit(b), lit(b - 1), lit(v), lit(n))
        if F == 1:
            e6 = 'X.e6_1(one, h1, %s, %s, {==})' % (lit(q), lit(q - 2))
        else:
            k, r = divmod(F, q)
            assert r > 0
            e6 = 'X.e6_o(one, h1, %s, %s, %s, %s, %s, %s, %s, {==}, {==})' % (fb, fnat, fh, lit(q), lit(k), lit(r - 1), lit(q - r - 1))
        ent = 'PK.PE{X.bvalo(one, %s), X.bvalo(one, %s), X.bvalo(one, %s), X.bvalo(one, %s), X.bvalo(one, %s), X.bvalo(one, %s)}' % (lit(q), lit(m), lit(a), lit(b), lit(u), lit(v))
        cert = 'PK.cert_cons(X.bvalo(one, %s), X.bvalo(one, %s), X.bvalo(one, %s), X.bvalo(one, %s), X.bvalo(one, %s), X.bvalo(one, %s), X.bvalo(one, %s), %s, %s, %s, %s, %s, %s, %s, %s)' % (
            lit(n), lit(q), lit(m), lit(a), lit(b), lit(u), lit(v), tail, subs[i], e2, e3, e4, e5, e6, cert)
        tail = '%s <> %s' % (ent, tail)
        fh = 'X.fp_o(one, h1, %s, %s, %s, %s)' % (lit(q), fb, fnat, fh)
        fnat = 'Nat.mul(X.bvalo(one, %s), %s)' % (lit(q), fnat)
        fb = 'B.bmul(%s, %s)' % (lit(q), fb)
        F *= q
    hf = 'X.hf_o(one, h1, %s, %s, %s, %s, %s, {==})' % (lit(n), fb, fnat, fh, lit(F * F - n))
    out.append('def %s(+one: Nat, +h1: {one == 1n : Nat}%s) -> PM.Prime(X.bvalo(one, %s)):\n  PK.pocklington(X.bvalo(one, %s), X.bvalo(one, %s), X.suc2_o(one, h1, %s, %s, {==}), %s, %s, %s)\n' % (
        nm, hyp_decl(hyps, used), lit(n), lit(n), lit(n - 2), lit(n), lit(n - 2), tail, cert, hf))
    defs.extend(out)
    done[n] = ('%s(one, h1%s)' % (nm, ''.join(', ' + hyps[h] for h in used)), used)
    return done[n]


def pchain(n):
    """the chain 2^(n - 1) mod n == 1 of n's Pocklington step"""
    return (G.plan(n)[1], n - 1, n)


def root(fn, what, exports, hyp=()):
    """a proof root. exports: (name, prime) or (name, (a, e, n)) or (name, (a, e, n, lo, hi)): the defs
    `name` proving Prime(bvalo(one, prime)) or CL.Inv(one, a, n, x, e') for the steps lo..hi of a^e mod n;
    hyp: what they assume, primes and chains (a, e, n) or chain states (a, e', n, x); in the order
    given, the parameters after (one, h1) of each export that uses them"""
    defs = []
    G.CONSTS.clear()
    del G.CDEFS[:]
    hyps = {h: 'hy%d' % i for i, h in enumerate(hyp)}
    done, seen = {}, []
    for name, what_ in exports:
        if isinstance(what_, tuple):
            a, e, n = what_[:3]
            lo, hi = what_[3:] if len(what_) > 3 else (0, None)
            term, used, x = chain(name + '_c', a, e, n, defs, hyps, lo, hi)
            ex = e if hi is None else G.steps(a, e, n)[0][hi - 1][2]
            ty = inv_type((a, ex, n, x))
        else:
            term, used = level(what_, defs, done, hyps)
            ty = 'PM.Prime(X.bvalo(one, %s))' % pub(what_)
        used = [h for h in hyp if h in used]
        seen += used
        defs.append('def %s(+one: Nat, +h1: {one == 1n : Nat}%s) -> %s:\n  %s\n' % (name, hyp_decl(hyps, used), ty, term))
    assert set(seen) == set(hyp), (fn, seen)
    open(os.path.join(G.OUT, fn), 'w').write(G.HEAD % what + '\n' + '\n'.join(G.CDEFS) + '\n' + '\n'.join(defs))
    return fn


if __name__ == '__main__':
    which = sys.argv[1:] or ['lits', 'p', 'q', 'l', 'd', 'i']
    if 'lits' in which:
        write_lits()
    if 'p' in which:
        print(root('cert_p.bend', 'Pocklington certificate: p = 2^255 - 19 (PL.pl()) is prime, given that q1 (PL.q1l(), the big prime factor of p - 1) is',
                   [('top_prime', P)], [Q1]))
    if 'q' in which:
        print(root('cert_q.bend', 'Pocklington certificate: q1 (PL.q1l()) is prime, given that its factors PL.q116l() and PL.q55l() are and that 2^(q1 - 1) == 1 (mod q1)',
                   [('top_prime', Q1)], [Q116, Q55, pchain(Q1)]))
        print(root('cert_q1.bend', '2^(q1 - 1) == 1 (mod q1) (PL.q1l()), and the Pocklington certificate of PL.q55l()',
                   [('pw', pchain(Q1)), ('prime_55', Q55)]))
        print(root('cert_q2.bend', 'Pocklington certificate: PL.q116l() is prime', [('top_prime', Q116)]))
    if 'l' in which:
        print(root('cert_l.bend', 'Pocklington certificate: the group order L = 2^252 + 27742317777372353535851937790883648493 (PL.ll()) is prime, given that PL.l88l() is and that 2^(L - 1) == 1 (mod L)',
                   [('top_prime', L)], [L88, pchain(L)]))
        print(root('cert_l1.bend', '2^(L - 1) == 1 (mod L) (PL.ll()), and the Pocklington certificate of PL.l88l()',
                   [('pw', pchain(L)), ('prime_88', L88)]))
    if 'd' in which:
        h = (P - 1) // 2
        assert pow(D, h, P) == P - 1
        print(root('cert_d0.bend', 'd^dme mod p == dml, for d = -121665 / 121666: the first half of d^((p - 1) / 2)', [('pw', (D, h, P, 0, DCUT))]))
        print(root('cert_d.bend', 'd^((p - 1) / 2) mod p == p - 1, for d = -121665 / 121666, given the first half of the computation (d^dme mod p == dml)',
                   [('pw', (D, h, P, DCUT, len(_st)))], [(D, DE, P, DM)]))
    if 'i' in which:
        print(root('cert_i.bend', '2^((p - 1) / 4) mod p == I', [('pw', (2, (P - 1) // 4, P))]))
