#!/usr/bin/env python3
"""Identities by reflection for the edwards25519 group law: the generator's library.

An identity is an equation modulo m = 1 + mp between two values written with
the residue operations FS.fadd, FS.fsub, FS.fmul of spec/crypto/curve25519/field.bend
(the sum, difference and product modulo m; they unfold to the same terms as the
madd, msub, mmul of spec/crypto/secp256k1/field.bend, in which the reflection
lemmas of proofs/crypto/secp256k1/group are stated). For each value the generator writes it as an expression literal
(proofs/crypto/ed25519/group/ex.bend: X.ev of the literal unfolds to the value,
X.pl is its polynomial of proofs/crypto/secp256k1/group/poly.bend, and X.sound
proves once that the value is the polynomial's, Z.Rel); the identity is
I.ident with a {==} check that the
difference of the two polynomials, reduced by the rules "monomial -> polynomial"
(proofs/crypto/ed25519/group/redm.bend) that the hypotheses give, computes to [].

The polynomials are also computed here (dictionaries), only to decide how many
reduction passes to write; nothing here is trusted: a wrong polynomial, a
missing pass or a false identity fails the check.
"""
import os

HERE = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.join(HERE, '..', '..', '..', 'proofs', 'crypto', 'ed25519', 'group')

HEAD = '''# GENERATED by tools/generators/ed25519_group/gen_ids.py; edit the generator
import Base
import ../../../../spec/crypto/curve25519/field.bend as FS
import ../../../../spec/crypto/curve25519/edwards.bend as G
import ../../secp256k1/group/poly.bend as P
import ../../secp256k1/group/pev.bend as E
import ../../secp256k1/group/zm.bend as Z
import ../../secp256k1/group/ident.bend as I
import ../../secp256k1/group/fld.bend as F
import ./ex.bend as X
import ./redm.bend as RM
import ./idm.bend as IM
'''

M = '1n+mp'


# ---- polynomials (exponent tuple -> coefficient), mirroring poly.bend ----

def padd(a, b):
    r = dict(a)
    for e, c in b.items():
        v = r.get(e, 0) + c
        if v:
            r[e] = v
        else:
            r.pop(e, None)
    return r


def pneg(a):
    return {e: -c for e, c in a.items()}


def pmul(a, b):
    r = {}
    for e, c in a.items():
        for f, d in b.items():
            g = tuple(x + y for x, y in zip(e, f))
            v = r.get(g, 0) + c * d
            if v:
                r[g] = v
            else:
                r.pop(g, None)
    return r


def ppow(f, n, k):
    r = {(0,) * n: 1}
    for _ in range(k):
        r = pmul(f, r)
    return r


def redm(n, u, f, a):
    """one pass of RM.redm: every term in which x^u fits k >= 1 times becomes c x^(e - k u) f^k"""
    r, changed = {}, False
    for e, c in a.items():
        ks = [e[i] // u[i] for i in range(n) if u[i] > 0]
        k = min(ks) if ks else 0
        if k == 0:
            r = padd(r, {e: c})
        else:
            changed = True
            r = padd(r, pmul({tuple(e[i] - k * u[i] for i in range(n)): c}, ppow(f, n, k)))
    return r, changed


class V:
    def __init__(self, spec, ex, val):
        self.spec, self.ex, self.val = spec, ex, val


class Rule:
    """x^u -> F, from the hypothesis h : {Nat.mod(mono, m) == Nat.mod(F, m)}"""

    def __init__(self, c, mono, F, h, hyp=None):
        assert len(mono.val) == 1 and list(mono.val.values()) == [1], mono.val
        self.u = list(mono.val.keys())[0]
        self.us = '[' + ', '.join('%dn' % k for k in self.u) + ']'
        self.F = F
        self.fp = c.poly(F)
        self.hyp = '+%s: %s' % (h, hyp or '{Nat.mod(%s, %s) == Nat.mod(%s, %s) : Nat}' % (mono.spec, M, F.spec, M))
        self.rel = 'IM.mono_rel(mp, %s, %s, %s, %s, %s, %s, {==}, {==}, %s, %s, %s)' % (mono.spec, F.spec, c.poly(mono), self.us, self.fp, c.env, c.rel(mono), h, c.rel(F))


class Ctx:
    """names: the variables (Nat parameters)"""

    def __init__(self, names):
        self.names = list(names)
        self.n = len(self.names)
        self.env = '[' + ', '.join(self.names) + ']'
        self.params = ', '.join('+%s: Nat' % v for v in ['mp'] + self.names)
        self.args = ', '.join(['mp'] + self.names)
        self.defs = []
        self.k = 0

    def unit(self, i=None):
        return tuple(1 if j == i else 0 for j in range(self.n))

    def poly(self, v):
        return 'X.pl(%dn, %s)' % (self.n, v.ex)

    def rel(self, v):
        return 'X.sound(mp, %dn, %s, %s, {==})' % (self.n, self.env, v.ex)

    def var(self, i):
        if isinstance(i, str):
            i = self.names.index(i)
        return V(self.names[i], 'X.V{%dn}' % i, {self.unit(i): 1})

    def vars(self, *names):
        return [self.var(x) for x in names]

    def zero(self):
        return V('0n', 'X.Z{}', {})

    def const(self, k):
        return V('%dn' % k, 'X.K{%dn}' % k, {self.unit(): k})

    def mul(self, a, b, *more):
        r = V('FS.fmul(%s, %s, %s)' % (M, a.spec, b.spec), 'X.M{%s, %s}' % (a.ex, b.ex), pmul(a.val, b.val))
        for c in more:
            r = self.mul(r, c)
        return r

    def add(self, a, b, *more):
        r = V('FS.fadd(%s, %s, %s)' % (M, a.spec, b.spec), 'X.A{%s, %s}' % (a.ex, b.ex), padd(a.val, b.val))
        for c in more:
            r = self.add(r, c)
        return r

    def sub(self, a, b):
        return V('FS.fsub(%s, %s, %s)' % (M, a.spec, b.spec), 'X.S{%s, %s}' % (a.ex, b.ex), padd(a.val, pneg(b.val)))

    def sq(self, a):
        return self.mul(a, a)

    def named(self, name, v):
        """a def for the expression"""
        self.defs.append('def %s() -> X.Ex:\n  %s\n' % (name, v.ex))
        return V(v.spec, '%s()' % name, v.val)

    def share(self, v):
        """named with a fresh name: for a value used several times"""
        self.k += 1
        return self.named('s%d' % self.k, v)

    def specdef(self, name, v):
        """a def for the value (so that hand proofs can name it)"""
        self.defs.append('def %s(%s) -> Nat:\n  %s\n' % (name, self.params, v.spec))
        return V('%s(%s)' % (name, self.args), v.ex, v.val)

    def rule(self, mono, F, h, hyp=None):
        """hyp: the hypothesis's type when it is a named one (it must unfold to mono == F modulo m)"""
        return Rule(self, mono, F, h, hyp)

    def call(self, spec, v):
        """the same value under a name of the specification (a call that unfolds to v's expression)"""
        return V(spec, v.ex, v.val)

    def reduce(self, name, d, val, rules):
        """the chain of reductions of the polynomial d (a term) to []: the proof of SameM(0, 0, d)"""
        seq = []
        changed = True
        while val and changed:
            changed = False
            for r in rules:
                val2, ch = redm(self.n, r.u, r.F.val, val)
                if ch:
                    seq.append(r)
                    val = val2
                    changed = True
        if val:
            raise ValueError('%s: not zero after reduction: %d terms left, e.g. %s' % (name, len(val), list(val.items())[:4]))
        self.defs.append('def %s_d0() -> List<&2, P.Tm>:\n  %s\n' % (name, d))
        for j, r in enumerate(seq):
            self.defs.append('def %s_d%d() -> List<&2, P.Tm>:\n  RM.redm(%dn, %s, %s, %s_d%d())\n' % (name, j + 1, self.n, r.us, r.fp, name, j))
        hz = 'I.sm_nil(mp, %s_d%d(), %s, {==})' % (name, len(seq), self.env)
        for j in range(len(seq) - 1, -1, -1):
            r = seq[j]
            hz = 'RM.sm_redm(mp, %dn, %s, %s, %s_d%d(), %s, %s, %s)' % (self.n, r.us, r.fp, name, j, self.env, r.rel, hz)
        return hz, len(seq)

    def ident(self, name, a, b, rules=(), comment=''):
        hyp_params = ''.join(', ' + r.hyp for r in rules)
        a, b = self.named(name + '_a', a), self.named(name + '_b', b)
        hz, np = self.reduce(name, 'P.psub(%s, %s)' % (self.poly(a), self.poly(b)), padd(a.val, pneg(b.val)), rules)
        self.defs.append('%sdef %s(%s%s) -> {Nat.mod(%s, %s) == Nat.mod(%s, %s) : Nat}:\n  I.ident(mp, %s, %s, %s, %s, %s, %s, %s, %s)\n'
                         % (('# ' + comment + '\n') if comment else '', name, self.params, hyp_params, a.spec, M, b.spec, M,
                            a.spec, b.spec, self.poly(a), self.poly(b), self.env, self.rel(a), self.rel(b), hz))
        return np

    def conseq(self, name, a, combos, rules=(), comment=''):
        """a == sum (L_i - R_i) c_i modulo the rules; with hypotheses L_i == R_i (mod m): a == 0 (mod m)"""
        b = None
        for L, R, cof in combos:
            t = self.mul(self.sub(L, R), cof)
            b = t if b is None else self.add(b, t)
        a, b = self.named(name + '_a', a), self.named(name + '_b', b)
        hyp_params = ''.join(', ' + r.hyp for r in rules) + ''.join(', +e%d: {Nat.mod(%s, %s) == Nat.mod(%s, %s) : Nat}' % (i + 1, L.spec, M, R.spec, M) for i, (L, R, cof) in enumerate(combos))
        hz, np = self.reduce(name, 'P.psub(%s, %s)' % (self.poly(a), self.poly(b)), padd(a.val, pneg(b.val)), rules)

        def side(i, hole):
            out = None
            for j, (L, R, cof) in enumerate(combos):
                h = '_' if j == hole else ('FS.fsub(%s, %s, %s)' % (M, L.spec, R.spec) if j < i else '0n')
                t = 'FS.fmul(%s, %s, %s)' % (M, h, cof.spec)
                out = t if out is None else 'FS.fadd(%s, %s, %s)' % (M, out, t)
            return out
        steps = ''
        for i, (L, R, cof) in enumerate(combos):
            steps += '  %%IM.fsub_eq0(mp, %s, %s, e%d) : {Nat.mod(%s, %s) == Nat.mod(%s, %s) : Nat}\n' % (L.spec, R.spec, i + 1, a.spec, M, side(i, i), M)
        self.defs.append('%sdef %s(%s%s) -> {Nat.mod(%s, %s) == 0n : Nat}:\n%s  I.ident(mp, %s, %s, %s, %s, %s, %s, %s, %s)\n'
                         % (('# ' + comment + '\n') if comment else '', name, self.params, hyp_params, a.spec, M, steps,
                            a.spec, b.spec, self.poly(a), self.poly(b), self.env, self.rel(a), self.rel(b), hz))
        return np

    def write(self, fname, header):
        with open(os.path.join(OUT, fname), 'w') as f:
            f.write(HEAD + '\n' + header + '\n' + '\n'.join(self.defs))
