#!/usr/bin/env python3
"""Identities by reflection for the edwards25519 group law: the generator's library.

An identity is an equation modulo m = 1 + mp between two values written with
the residue operations FS.fadd, FS.fsub, FS.fmul of spec/crypto/curve25519/field.bend
(the sum, difference and product modulo m; they unfold to the same terms as the
madd, msub, mmul of spec/crypto/secp256k1/field.bend, in which the reflection
lemmas of proofs/crypto/secp256k1/group are stated). For each value the generator writes its polynomial
(proofs/crypto/secp256k1/group/poly.bend) and the proof that the value is the
polynomial's (Z.Rel); the identity is I.ident with a {==} check that the
difference of the two polynomials, reduced by the rules "monomial -> polynomial"
(proofs/crypto/ed25519/group/redm.bend) that the hypotheses give, computes to [].

The polynomials are also computed here (dictionaries), only to decide how many
reduction passes to write; nothing here is trusted: a wrong polynomial, a
missing pass or a false identity fails the check.
"""
import os

HERE = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.join(HERE, '..', '..', '..', 'proofs', 'crypto', 'ed25519', 'group')

HEAD = '''# GENERATED by tools/generators/ed25519_group/gen_ids.py; edit the generator
import Base
import ../../../../spec/crypto/curve25519/field.bend as FS
import ../../secp256k1/group/poly.bend as P
import ../../secp256k1/group/pev.bend as E
import ../../secp256k1/group/zm.bend as Z
import ../../secp256k1/group/ident.bend as I
import ../../secp256k1/group/fld.bend as F
import ./redm.bend as RM
import ./idm.bend as IM
'''

M = '1n+mp'


# ---- polynomials (exponent tuple -> coefficient), mirroring poly.bend ----

def padd(a, b):
    r = dict(a)
    for e, c in b.items():
        v = r.get(e, 0) + c
        if v:
            r[e] = v
        else:
            r.pop(e, None)
    return r


def pneg(a):
    return {e: -c for e, c in a.items()}


def pmul(a, b):
    r = {}
    for e, c in a.items():
        for f, d in b.items():
            g = tuple(x + y for x, y in zip(e, f))
            v = r.get(g, 0) + c * d
            if v:
                r[g] = v
            else:
                r.pop(g, None)
    return r


def ppow(f, n, k):
    r = {(0,) * n: 1}
    for _ in range(k):
        r = pmul(f, r)
    return r


def redm(n, u, f, a):
    """one pass of RM.redm: every term in which x^u fits k >= 1 times becomes c x^(e - k u) f^k"""
    r, changed = {}, False
    for e, c in a.items():
        ks = [e[i] // u[i] for i in range(n) if u[i] > 0]
        k = min(ks) if ks else 0
        if k == 0:
            r = padd(r, {e: c})
        else:
            changed = True
            r = padd(r, pmul({tuple(e[i] - k * u[i] for i in range(n)): c}, ppow(f, n, k)))
    return r, changed


class V:
    def __init__(self, spec, poly, rel, val):
        self.spec, self.poly, self.rel, self.val = spec, poly, rel, val


class Rule:
    """x^u -> F, from the hypothesis h : {Nat.mod(mono, m) == Nat.mod(F, m)}"""

    def __init__(self, c, mono, F, h):
        assert len(mono.val) == 1 and list(mono.val.values()) == [1], mono.val
        self.u = list(mono.val.keys())[0]
        self.us = '[' + ', '.join('%dn' % k for k in self.u) + ']'
        self.F = F
        self.hyp = '+%s: {Nat.mod(%s, %s) == Nat.mod(%s, %s) : Nat}' % (h, mono.spec, M, F.spec, M)
        self.rel = 'IM.mono_rel(mp, %s, %s, %s, %s, %s, %s, {==}, {==}, %s, %s, %s)' % (mono.spec, F.spec, mono.poly, self.us, F.poly, c.env, mono.rel, h, F.rel)


class Ctx:
    """names: the variables (Nat parameters)"""

    def __init__(self, names):
        self.names = list(names)
        self.n = len(self.names)
        self.env = '[' + ', '.join(self.names) + ']'
        self.params = ', '.join('+%s: Nat' % v for v in ['mp'] + self.names)
        self.args = ', '.join(['mp'] + self.names)
        self.defs = []
        self.k = 0

    def unit(self, i=None):
        return tuple(1 if j == i else 0 for j in range(self.n))

    def var(self, i):
        if isinstance(i, str):
            i = self.names.index(i)
        return V(self.names[i], 'P.pvar(%dn, %dn)' % (self.n, i), 'I.var_rel(mp, %dn, %dn, %s, {==})' % (self.n, i, self.env), {self.unit(i): 1})

    def vars(self, *names):
        return [self.var(x) for x in names]

    def zero(self):
        return V('0n', 'Nil{}', '{==}', {})

    def const(self, k):
        return V('%dn' % k, 'P.pconst(%dn, %dn)' % (self.n, k), '{==}', {self.unit(): k})

    def op(self, f, g, lem, a, b, val):
        return V('FS.%s(%s, %s, %s)' % (f, M, a.spec, b.spec), 'P.%s(%s, %s)' % (g, a.poly, b.poly),
                 'I.%s(mp, %s, %s, %s, %s, %s, %s, %s)' % (lem, a.spec, b.spec, a.poly, b.poly, self.env, a.rel, b.rel), val)

    def mul(self, a, b, *more):
        r = self.op('fmul', 'pmul', 'rel_pmul', a, b, pmul(a.val, b.val))
        for c in more:
            r = self.mul(r, c)
        return r

    def add(self, a, b, *more):
        r = self.op('fadd', 'padd', 'rel_padd', a, b, padd(a.val, b.val))
        for c in more:
            r = self.add(r, c)
        return r

    def sub(self, a, b):
        return self.op('fsub', 'psub', 'rel_psub', a, b, padd(a.val, pneg(b.val)))

    def sq(self, a):
        return self.mul(a, a)

    def named(self, name, v):
        """a def for the polynomial and a lemma for its relation (checked once)"""
        self.defs.append('def %s_p() -> List<&2, P.Tm>:\n  %s\n' % (name, v.poly))
        self.defs.append('def %s_r(%s) -> Z.Rel(mp, %s, E.eP(%s_p(), %s), E.eN(%s_p(), %s)):\n  %s\n'
                         % (name, self.params, v.spec, name, self.env, name, self.env, v.rel))
        return V(v.spec, '%s_p()' % name, '%s_r(%s)' % (name, self.args), v.val)

    def specdef(self, name, v):
        """a def for the value (so that hand proofs can name it)"""
        self.defs.append('def %s(%s) -> Nat:\n  %s\n' % (name, self.params, v.spec))
        return V('%s(%s)' % (name, self.args), v.poly, v.rel, v.val)

    def rule(self, mono, F, h):
        return Rule(self, mono, F, h)

    def reduce(self, name, d, val, rules):
        """the chain of reductions of the polynomial d (a term) to []: the proof of SameM(0, 0, d)"""
        seq = []
        changed = True
        while val and changed:
            changed = False
            for r in rules:
                val2, ch = redm(self.n, r.u, r.F.val, val)
                if ch:
                    seq.append(r)
                    val = val2
                    changed = True
        if val:
            raise ValueError('%s: not zero after reduction: %d terms left, e.g. %s' % (name, len(val), list(val.items())[:4]))
        self.defs.append('def %s_d0() -> List<&2, P.Tm>:\n  %s\n' % (name, d))
        for j, r in enumerate(seq):
            self.defs.append('def %s_d%d() -> List<&2, P.Tm>:\n  RM.redm(%dn, %s, %s, %s_d%d())\n' % (name, j + 1, self.n, r.us, r.F.poly, name, j))
        hz = 'I.sm_nil(mp, %s_d%d(), %s, {==})' % (name, len(seq), self.env)
        for j in range(len(seq) - 1, -1, -1):
            r = seq[j]
            hz = 'RM.sm_redm(mp, %dn, %s, %s, %s_d%d(), %s, %s, %s)' % (self.n, r.us, r.F.poly, name, j, self.env, r.rel, hz)
        return hz, len(seq)

    def ident(self, name, a, b, rules=(), comment=''):
        hyp_params = ''.join(', ' + r.hyp for r in rules)
        hz, np = self.reduce(name, 'P.psub(%s, %s)' % (a.poly, b.poly), padd(a.val, pneg(b.val)), rules)
        self.defs.append('%sdef %s(%s%s) -> {Nat.mod(%s, %s) == Nat.mod(%s, %s) : Nat}:\n  I.ident(mp, %s, %s, %s, %s, %s, %s, %s, %s)\n'
                         % (('# ' + comment + '\n') if comment else '', name, self.params, hyp_params, a.spec, M, b.spec, M,
                            a.spec, b.spec, a.poly, b.poly, self.env, a.rel, b.rel, hz))
        return np

    def conseq(self, name, a, combos, rules=(), comment=''):
        """a == sum (L_i - R_i) c_i modulo the rules; with hypotheses L_i == R_i (mod m): a == 0 (mod m)"""
        b = None
        for L, R, cof in combos:
            t = self.mul(self.sub(L, R), cof)
            b = t if b is None else self.add(b, t)
        hyp_params = ''.join(', ' + r.hyp for r in rules) + ''.join(', +e%d: {Nat.mod(%s, %s) == Nat.mod(%s, %s) : Nat}' % (i + 1, L.spec, M, R.spec, M) for i, (L, R, cof) in enumerate(combos))
        hz, np = self.reduce(name, 'P.psub(%s, %s)' % (a.poly, b.poly), padd(a.val, pneg(b.val)), rules)

        def side(i, hole):
            out = None
            for j, (L, R, cof) in enumerate(combos):
                h = '_' if j == hole else ('FS.fsub(%s, %s, %s)' % (M, L.spec, R.spec) if j < i else '0n')
                t = 'FS.fmul(%s, %s, %s)' % (M, h, cof.spec)
                out = t if out is None else 'FS.fadd(%s, %s, %s)' % (M, out, t)
            return out
        steps = ''
        for i, (L, R, cof) in enumerate(combos):
            steps += '  %%IM.fsub_eq0(mp, %s, %s, e%d) : {Nat.mod(%s, %s) == Nat.mod(%s, %s) : Nat}\n' % (L.spec, R.spec, i + 1, a.spec, M, side(i, i), M)
        self.defs.append('%sdef %s(%s%s) -> {Nat.mod(%s, %s) == 0n : Nat}:\n%s  I.ident(mp, %s, %s, %s, %s, %s, %s, %s, %s)\n'
                         % (('# ' + comment + '\n') if comment else '', name, self.params, hyp_params, a.spec, M, steps,
                            a.spec, b.spec, a.poly, b.poly, self.env, a.rel, b.rel, hz))
        return np

    def write(self, fname, header):
        with open(os.path.join(OUT, fname), 'w') as f:
            f.write(HEAD + '\n' + header + '\n' + '\n'.join(self.defs))
