#!/usr/bin/env python3
"""Pruned library copies for the edwards25519 group-law proofs.

  python3 tools/generators/ed25519_group/shake_ed.py

The same tool as tools/generators/shake.py (secp256k1), for the proof files of
proofs/crypto/ed25519/group: it writes under proofs/crypto/ed25519/group/lite/
a copy of every library file (proofs/lib, proofs/math) and of the few
secp256k1 group files that import the number theory (fld.bend, nc.bend),
restricted to the definitions these proofs reach, with the text of every
kept definition unchanged. It then points the imports of the group files
(the .bend files and their .src sources) at the copies. The number theory
of proofs/math/number/nt_prime.bend imports the trial-division proof of
small primes, which the group law never uses: pruning it out saves about
300 MB in every root.

The certificate roots (cert*.bend) and the files they read are left as they
are (they use the small-prime check). Nothing is trusted: the copies are
checked like any other proof file. Run it again after changing which
library lemmas the proofs use.
"""
import os, re, sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
ROOT = HERE.parents[2]
sys.path.insert(0, str(HERE.parent))
import shake as SH

CONS = ROOT / 'proofs/crypto/ed25519/group'
SRCS = HERE
LITE = CONS / 'lite'
KEEP = {'proofs/lib/logic.bend'}
EXTRA = {'proofs/crypto/secp256k1/group/fld.bend', 'proofs/crypto/secp256k1/group/nc.bend'}


def rel(p):
    return os.path.relpath(p, ROOT)


def is_copy(r):
    return ((r.startswith('proofs/lib/') or r.startswith('proofs/math/')) and r not in KEEP) or r in EXTRA


def lite_path(r):
    return LITE / r[len('proofs/'):]


def excluded(name):
    return name.startswith('cert') or name.startswith('lite')


IMP = re.compile(r'^import\s+(\S+\.bend)\s+as\s+(\w+)', re.M)


def resolve(base_dir, t):
    """the original repo-relative target of an import (a lite path mapped back)"""
    r = rel(os.path.normpath(os.path.join(base_dir, t)))
    lr = rel(LITE)
    if r.startswith(lr + '/'):
        r = 'proofs/' + r[len(lr) + 1:]
    return r


def main():
    files = {}

    def get(r):
        if r not in files:
            files[r] = SH.File(r)
        return files[r]

    need, work = set(), []

    def want(r, name):
        f = get(r)
        parts = name.split('.')
        for k in range(len(parts), 0, -1):
            n = '.'.join(parts[:k])
            if n in f.names:
                if (r, n) not in need:
                    need.add((r, n))
                    work.append((r, n))
                return True
        return False

    def scan(text, imports, own):
        text = '\n'.join(l for l in text.split('\n') if not l.lstrip().startswith('#'))
        for tok in SH.DOTTED.findall(text):
            head = tok.split('.')[0]
            if head in imports and '.' in tok:
                t = imports[head]
                if is_copy(t):
                    want(t, tok[len(head) + 1:])
            elif own is not None:
                want(own, tok)

    consumers = [p for p in sorted(CONS.glob('*.bend')) if not excluded(p.name)]
    for p in consumers:
        text = p.read_text()
        imports = {al: resolve(CONS, t) for t, al in IMP.findall(text)}
        scan(text, imports, None)
    while work:
        r, n = work.pop()
        f = get(r)
        imports = {al: t for al, t in f.imports.items()}
        for i in f.names[n]:
            scan(f.blocks[i][1], imports, r)

    if LITE.exists():
        for p in sorted(LITE.rglob('*.bend')):
            p.unlink()
    kept = {}
    for (r, n) in need:
        kept.setdefault(r, set()).add(n)
    total = 0
    for r, names in sorted(kept.items()):
        f = files[r]
        out = lite_path(r)
        out.parent.mkdir(parents=True, exist_ok=True)
        body = [b for (n, b) in f.blocks if n in names]
        text = '\n'.join(body)
        lines = ['# GENERATED by tools/generators/ed25519_group/shake_ed.py from %s (the' % r,
                 '# definitions the edwards25519 group proofs reach, unchanged); edit the library, then run the tool.', 'import Base']
        for alias, t in f.imports.items():
            if alias is None or not re.search(r'(?<![A-Za-z0-9_.])%s\.' % re.escape(alias), text):
                continue
            if is_copy(t):
                if t not in kept:
                    continue
                tp = lite_path(t)
            else:
                tp = ROOT / t
            rp = os.path.relpath(tp, out.parent)
            if not rp.startswith('.'):
                rp = './' + rp
            lines.append('import %s as %s' % (rp, alias))
        out.write_text('\n'.join(lines) + '\n\n' + text)
        total += len(body)

    # point the consumers (and their sources) at the copies
    def rewrite(p, base_dir):
        text = p.read_text()

        def sub(m):
            t, al = m.group(1), m.group(2)
            r = resolve(base_dir, t)
            if is_copy(r) and r in kept:
                np = os.path.relpath(lite_path(r), base_dir)
            elif is_copy(r):
                np = os.path.relpath(ROOT / r, base_dir)
            else:
                return m.group(0)
            if not np.startswith('.'):
                np = './' + np
            return 'import %s as %s' % (np, al)
        new = IMP.sub(sub, text)
        if new != text:
            p.write_text(new)
            return 1
        return 0
    n = sum(rewrite(p, CONS) for p in consumers)
    srcs = [p for p in sorted(SRCS.glob('*.src')) if not excluded(p.name)]
    n += sum(rewrite(p, CONS) for p in srcs)
    print('lite: %d files, %d definitions (of %d files read); %d consumer files rewritten' % (len(kept), total, len(files), n))


if __name__ == '__main__':
    main()
