#!/usr/bin/env python3
"""Make a family of clauses unconditional.

  python3 tools/generators/secp256k1_group/close_laws.py <stem> [name=call ...]

reads proofs/crypto/secp256k1/laws_<stem>.bend (laws that take certificate
facts as hypotheses, e.g. hp, hc) and proof_<stem>.bend (their proofs
`def Laws.X(..)`), and rewrites the three files

  group/<stem>p.bend     the same clauses as plain lemmas, hypotheses kept
                         (what other proofs import)
  laws_<stem>.bend       the clauses without those hypotheses
  proof_<stem>.bend      the closing root: each lemma applied to the certificates

The hypotheses removed are those named in CERT (default hp, hc), replaced
by the given calls. Run once per family (the inputs are overwritten).
"""
import os, re, sys
HERE = os.path.dirname(os.path.abspath(__file__))
D = os.path.join(HERE, '..', '..', '..', 'proofs', 'crypto', 'secp256k1')
CERT = {'hp': 'PC.prime_p(one, h1)', 'hc': 'PC.cube_spec(one, h1)'}
SIG = {'hp': 'PM.Prime(FS.prime(one))', 'hc': 'FS.mpow(FS.prime(one), Nat.sub(FS.prime(one), 7n)', 'hq': 'PM.Prime(FS.order(one))'}
CERT_IMPORTS = {'PC.': 'import ./group/certpc.bend as PC', 'CN.': 'import ./group/certn.bend as CN'}


def main():
    stem = sys.argv[1]
    cert = dict(CERT)
    extra_imports = []
    for a in sys.argv[2:]:
        if a.startswith('import '):
            extra_imports.append(a)
        else:
            k, v = a.split('=', 1)
            cert[k] = v
    laws = open(os.path.join(D, 'laws_%s.bend' % stem)).read()
    proof = open(os.path.join(D, 'proof_%s.bend' % stem)).read()
    # ---- parse the laws
    lines = laws.split('\n')
    starts = [i for i, l in enumerate(lines) if l.startswith('law ')]
    items, first = [], None
    for i in starts:
        j = i
        while j > 0 and lines[j - 1].startswith('#'):
            j -= 1
        if first is None:
            first = j
        k = i + 1
        while k < len(lines) and lines[k].startswith('  '):
            k += 1
        body = lines[i + 1:k]
        fors = [l.strip()[4:] for l in body if l.strip().startswith('for ')]
        concl = [l.strip() for l in body if not l.strip().startswith('for ')][-1]
        items.append((lines[j:i], lines[i][4:].rstrip(':'), fors, concl))
    head = '\n'.join(lines[:first])
    # ---- parse the proofs
    defs = {}
    for m in re.finditer(r'^def Laws\.([A-Za-z0-9_.]+)\((.*?)\):\n((?:  .*\n?)+)', proof, re.M):
        defs[m.group(1)] = (m.group(2), m.group(3))
    pimports = [l for l in proof.split('\n') if l.startswith('import ') and 'laws_%s.bend' % stem not in l]

    def up(l):
        m = re.match(r'import (\S+) as (\w+)$', l)
        if not m:
            return l
        path = m.group(1)
        if path.startswith('./group/'):
            path = './' + path[len('./group/'):]
        elif path.startswith('./'):
            path = '../' + path[2:]
        elif path.startswith('../'):
            path = '../' + path
        return 'import %s as %s' % (path, m.group(2))
    low = lambda n: n.lower().replace('.', '_')
    pf = '# GENERATED by tools/generators/secp256k1_group/close_laws.py from laws_%s.bend / proof_%s.bend\n' % (stem, stem)
    pf += '\n'.join(up(l) for l in pimports) + '\n\n'
    pf += '# The clauses of laws_%s.bend with the certificate facts (%s) as\n# hypotheses: what other proofs import (the certificates are applied in\n# the closing root proof_%s.bend).\n' % (stem, ', '.join(sorted(cert)), stem)
    nl = head.rstrip('\n') + '\n'
    pr = '# GENERATED by tools/generators/secp256k1_group/close_laws.py\nimport Base\nimport ./laws_%s.bend as Laws\nimport ./group/%sp.bend as LP\n' % (stem, stem)
    used = ''.join(cert.values())
    for k, imp in CERT_IMPORTS.items():
        if k in used:
            pr += imp + '\n'
    for imp in extra_imports:
        pr += imp + '\n'
    pr += '\n# The clauses of laws_%s.bend: `bend proofs/crypto/secp256k1/proof_%s.bend`.\n# Each is its lemma of group/%sp.bend applied to the certificates.\n' % (stem, stem, stem)
    for com, name, fors, concl in items:
        args, body = defs[name]
        pf += '\n' + '\n'.join(com) + ('\n' if com else '') + 'def %s(%s) -> %s:\n%s' % (low(name), ', '.join(fors), concl, body if body.endswith('\n') else body + '\n')
        names = [re.match(r'[+-]?([A-Za-z0-9_]+):', f).group(1) for f in fors]
        iscert = [n in cert and SIG.get(n, '') in f for f, n in zip(fors, names)]
        keep = [f for f, c in zip(fors, iscert) if not c]
        nl += '\n' + '\n'.join(com) + ('\n' if com else '') + 'law %s:\n' % name + ''.join('  for %s\n' % f for f in keep) + '  %s\n' % concl
        pr += '\ndef Laws.%s(%s):\n  LP.%s(%s)\n' % (name, ', '.join(n for n, c in zip(names, iscert) if not c), low(name), ', '.join(cert[n] if c else n for n, c in zip(names, iscert)))
    open(os.path.join(D, 'group', '%sp.bend' % stem), 'w').write(pf)
    open(os.path.join(D, 'laws_%s.bend' % stem), 'w').write(nl)
    open(os.path.join(D, 'proof_%s.bend' % stem), 'w').write(pr)


if __name__ == '__main__':
    main()
