#!/usr/bin/env python3
"""Writes proofs/crypto/secp256k1/group/schs.bend: BIP-340 signing succeeds and
verifies, on the specification's terms (spec/crypto/secp256k1/schnorr.bend),
from the generic lemmas of schg.bend moved to p = FS.prime(one), n = FS.order(one),
G = CS.g(one). Plain text generation (the terms are long and repetitive).

  python3 tools/generators/secp256k1_group/gen_schs.py
"""
import os
HERE = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.join(HERE, '..', '..', '..', 'proofs', 'crypto', 'secp256k1')
p, n, G = 'FS.prime(one)', 'FS.order(one)', 'CS.g(one)'
PM1, NM1 = '1n+GF.pm(one)', '1n+nm(one)'
HCT = '{Nat.is_eq(FS.mpow(FS.prime(one), Nat.sub(FS.prime(one), 7n), Nat.div(Nat.sub(FS.prime(one), 1n), 3n)), 1n) == False{} : Bool}'
HGT = '{GS.valid(FS.prime(one), CS.g(one)) == True{} : Bool}'
HNGT = '{GS.equiv(FS.prime(one), GS.smul(FS.prime(one), FS.order(one), CS.g(one)), CS.infinity()) == True{} : Bool}'
HD = '+one: Nat, +h1: {one == 1n : Nat}, +hp: PM.Prime(FS.prime(one)), +hc: %s, +hq: PM.Prime(FS.order(one)), +hg: %s, +hng: %s' % (HCT, HGT, HNGT)
HA = 'one, h1, hp, hc, hq, hg, hng'
FPA = 'GF.pm(one), GF.hp_m(one, h1, hp), CB.p_mod3(one, h1), GF.hc_m(one, h1, hc), GF.h21_m(one, h1)'
SQA = 'one, h1, X.bvalo(one, EB.s4l()), EG.he_m(one, h1), EG.hodd_m(one, h1), EG.h256_m(one, h1)'
GAm = 'nm(one), hq_m(one, h1, hq), CS.g(one), vg_m(one, h1, hg), hng_m(one, h1, hng), hgo_m(one, h1)'
BYTES = 'List<&2, U32>'
MB = 'Maybe<&2, List<&2, U32>>'


def down_p(prop, h):
    """a fact about FS.prime(one) moved to 1 + pm; prop is a function of the modulus"""
    return 'Lg.subst(Nat, t => %s, FS.prime(one), %s, CB.p_suc(one, h1), %s)' % (prop('t'), PM1, h)


def down_n(prop, h):
    return 'Lg.subst(Nat, t => %s, FS.order(one), %s, CB.n_suc(one, h1), %s)' % (prop('t'), NM1, h)


def up(prop2, h):
    """a fact about (1 + pm, 1 + nm) moved to (p, n); prop2 is a function of both moduli"""
    inner = 'Lg.subst(Nat, t => %s, %s, FS.order(one), Equal.sym(Nat, FS.order(one), %s, CB.n_suc(one, h1)), %s)' % (prop2(PM1, 't'), NM1, NM1, h)
    return 'Lg.subst(Nat, t => %s, %s, FS.prime(one), Equal.sym(Nat, FS.prime(one), %s, CB.p_suc(one, h1)), %s)' % (prop2('t', n), PM1, PM1, inner)


def V(q, a):
    return '{GS.valid(%s, %s) == True{} : Bool}' % (q, a)


def E(q, a, b):
    return '{GS.equiv(%s, %s, %s) == True{} : Bool}' % (q, a, b)


def LT(a, b):
    return '{Nat.is_lt(%s, %s) == True{} : Bool}' % (a, b)


def ta(q, j):
    return 'CS.to_affine(%s, CS.pmul(%s, %s, CS.g(one)))' % (q, q, j)


def evr(q, m, j):
    return 'SG.EvR(%s, %s, CS.g(one), CS.aff_x(%s), CS.aff_y(%s), %s, Nat.mod(CS.aff_y(%s), 2n))' % (q, m, ta(q, j), ta(q, j), j, ta(q, j))


def subst_chain(ty, steps, final):
    """steps: list of (type, motive fn of t, old term, new term, proof of {old == new}); the goal is motive(old) at
    the first step; returns a proof of the first goal from `final`, a proof of the last motive at its new term"""
    out = final
    for T, mot, old, new, pr in reversed(steps):
        out = 'Lg.subst(%s, t => %s, %s, %s, Equal.sym(%s, %s, %s, %s), %s)' % (T, mot('t'), new, old, T, old, new, pr, out)
    return out


def main():
    o = []
    o.append('''# GENERATED by tools/generators/secp256k1_group/gen_schs.py; edit the generator
import Base
import ../../../../spec/lib/common.bend as C
import ../../../../spec/crypto/secp256k1/field.bend as FS
import ../../../../spec/crypto/secp256k1/curve.bend as CS
import ../../../../spec/crypto/secp256k1/group.bend as GS
import ../../../../spec/crypto/secp256k1/schnorr.bend as SS
import ../../../lib/logic.bend as Lg
import ../../../lib/nat.bend as N
import ../../../math/number/nt_prime.bend as PM
import ./bnx.bend as X
import ./certb.bend as CB
import ./gfp.bend as GF
import ./encb.bend as EB
import ./encg.bend as EG
import ./enco.bend as EO
import ./sqrt.bend as SQ
import ./sym.bend as S
import ./schg.bend as SG
import ./schd.bend as D

# BIP-340 on the specification's terms: signing succeeds (its final
# self-verification never fails) and the signature verifies. The facts
# about p, n and G are hypotheses, each proved in a root of its own:
#   hp: p is prime;  hc: (-7)^((p-1)/3) != 1;  hq: n is prime;
#   hg: G is a point of the group;  hng: [n] G is O.

# ---- the hypotheses on the moduli 1 + pm and 1 + nm ----

def nm(+one: Nat) -> Nat:
  X.bvalo(one, CB.n1l())

def hq_m(+one: Nat, +h1: {one == 1n : Nat}, +hq: PM.Prime(FS.order(one))) -> PM.Prime(1n+nm(one)):
  %s

def vg_m(+one: Nat, +h1: {one == 1n : Nat}, +hg: %s) -> %s:
  %s

def hng_m(+one: Nat, +h1: {one == 1n : Nat}, +hng: %s) -> %s:
  %s

def pz(a: CS.SPoint) -> Nat:
  match a:
    case CS.SPoint{x, y, z}:
      z

def gno_a(+mp: Nat, +h21: {Nat.is_lt(21n, 1n+mp) == True{} : Bool}, a: CS.SPoint, +one: Nat, +h1: {one == 1n : Nat}, +hz: {pz(a) == one : Nat}) -> {GS.equiv(1n+mp, a, CS.infinity()) == False{} : Bool}:
  match a:
    case CS.SPoint{+x, +y, +z}:
      Lg.subst(Nat, t => {GS.equiv(1n+mp, CS.SPoint{x, y, t}, CS.infinity()) == False{} : Bool}, one, z, Equal.sym(Nat, z, one, hz), SG.gno(mp, h21, x, y, one, h1))

def hgo_m(+one: Nat, +h1: {one == 1n : Nat}) -> {GS.equiv(1n+GF.pm(one), CS.g(one), CS.infinity()) == False{} : Bool}:
  gno_a(GF.pm(one), GF.h21_m(one, h1), CS.g(one), one, h1, {==})

def hn256_m(+one: Nat, +h1: {one == 1n : Nat}) -> {Nat.is_le(1n+nm(one), C.shift(256n, one)) == True{} : Bool}:
  %s
''' % (down_n(lambda t: 'PM.Prime(%s)' % t, 'hq'),
       HGT, V(PM1, G), down_p(lambda t: V(t, G), 'hg'),
       HNGT, E(PM1, 'GS.smul(%s, %s, %s)' % (PM1, NM1, G), 'CS.infinity()'),
       down_n(lambda t: E(PM1, 'GS.smul(%s, %s, %s)' % (PM1, t, G), 'CS.infinity()'), down_p(lambda t: E(t, 'GS.smul(%s, %s, %s)' % (t, n, G), 'CS.infinity()'), 'hng')),
       down_n(lambda t: '{Nat.is_le(%s, C.shift(256n, one)) == True{} : Bool}' % t, 'SQ.sub_le(FS.w256(one), FS.cn(one))')))
    # transported lemmas
    o.append('''
# ---- the lemmas of schg.bend on p, n and G ----

# the even-y representative of [j] G (0 < j < n)
def tev(%s, +j: Nat, +hj0: {Nat.is_eq(j, 0n) == False{} : Bool}, +hjn: %s) -> %s:
  %s

def tvr(%s, +d: Nat, +k: Nat, +e: Nat, +pp: CS.SPoint, +rx: Nat, +ey: Nat, +hk: %s, +vp: %s, +hpp: %s, +ve: %s, +hre: %s, +hrx: %s, +hey: %s, +hev: {Nat.mod(ey, 2n) == 0n : Nat}) -> SG.VR(FS.prime(one), FS.order(one), CS.g(one), d, k, e, pp, rx):
  %s

def taxb(+one: Nat, +h1: {one == 1n : Nat}, +a: CS.SPoint) -> SG.AxB(FS.prime(one), a):
  Lg.subst(Nat, t => SG.AxB(t, a), 1n+GF.pm(one), FS.prime(one), Equal.sym(Nat, FS.prime(one), 1n+GF.pm(one), CB.p_suc(one, h1)), SG.axb(GF.pm(one), one, h1, EG.h256_m(one, h1), a))

def tsb(+one: Nat, +h1: {one == 1n : Nat}, +v: Nat) -> SG.SB(FS.order(one), v):
  Lg.subst(Nat, t => SG.SB(t, v), 1n+nm(one), FS.order(one), Equal.sym(Nat, FS.order(one), 1n+nm(one), CB.n_suc(one, h1)), SG.sb(nm(one), one, h1, hn256_m(one, h1), v))

def tel(+one: Nat, +h1: {one == 1n : Nat}, +b: Nat, +j: Nat, +hjn: %s) -> SG.EL(FS.order(one), b, j):
  Lg.subst(Nat, t => SG.EL(t, b, j), 1n+nm(one), FS.order(one), Equal.sym(Nat, FS.order(one), 1n+nm(one), CB.n_suc(one, h1)), SG.el(nm(one), b, j, %s))
''' % (HD, LT('j', n), evr(p, n, 'j'),
       up(lambda q, m: evr(q, m, 'j'), 'SG.evp2(%s, %s, %s, hn256_m(one, h1), j, hj0, %s)' % (FPA, SQA, GAm, down_n(lambda t: LT('j', t), 'hjn'))),
       HD, LT('k', n), V(p, 'pp'), E(p, 'pp', 'GS.smul(%s, d, %s)' % (p, G)), V(p, 'CS.SPoint{rx, ey, 1n}'), E(p, 'CS.SPoint{rx, ey, 1n}', 'GS.smul(%s, k, %s)' % (p, G)), LT('rx', p), LT('ey', p),
       up(lambda q, m: 'SG.VR(%s, %s, CS.g(one), d, k, e, pp, rx)' % (q, m),
          'SG.vrf2(%s, one, h1, nm(one), hn256_m(one, h1), CS.g(one), vg_m(one, h1, hg), hng_m(one, h1, hng), d, k, e, pp, rx, ey, %s, %s, %s, %s, %s, %s, %s, hev)' % (
              FPA, down_n(lambda t: LT('k', t), 'hk'), down_p(lambda t: V(t, 'pp'), 'vp'), down_p(lambda t: E(t, 'pp', 'GS.smul(%s, d, %s)' % (t, G)), 'hpp'),
              down_p(lambda t: V(t, 'CS.SPoint{rx, ey, 1n}'), 've'), down_p(lambda t: E(t, 'CS.SPoint{rx, ey, 1n}', 'GS.smul(%s, k, %s)' % (t, G)), 'hre'),
              down_p(lambda t: LT('rx', t), 'hrx'), down_p(lambda t: LT('ey', t), 'hey'))),
       LT('j', n), down_n(lambda t: LT('j', t), 'hjn')))
    open(os.path.join(OUT, 'group', 'schs.bend'), 'w').write('\n'.join(o))



def eq_true(x):
    return '{%s == True{} : Bool}' % x


PROTO_HEAD = """# GENERATED by tools/generators/secp256k1_group/gen_schs.py; edit the generator
import Base
import ../../../../spec/lib/common.bend as C
import ../../../../spec/crypto/secp256k1/field.bend as FS
import ../../../../spec/crypto/secp256k1/curve.bend as CS
import ../../../../spec/crypto/secp256k1/group.bend as GS
import ../../../../spec/crypto/secp256k1/schnorr.bend as SS
import ../../../lib/logic.bend as Lg
import ../../../lib/nat.bend as N
import ../../../math/number/nt_prime.bend as PM
import ./enco.bend as EO
import ./schg.bend as SG
import ./schd.bend as D
import ./schs.bend as SH

# BIP-340 (spec/crypto/secp256k1/schnorr.bend): signing succeeds whenever
# the nonce is not zero, its signature verifies, and what sign returns
# always verifies. The values are those of schd.bend; the facts about p, n
# and G are the hypotheses of schs.bend.

# ---- octets ----

def len_app(a: List<&2, U32>, +b: List<&2, U32>) -> {List.length(&2, U32, List.append(&2, U32, a, b)) == Nat.add(List.length(&2, U32, a), List.length(&2, U32, b)) : Nat}:
  match a:
    case Nil{}:
      {==}
    case h <> +t:
      Equal.cong(Nat, Nat, z => 1n+z, List.length(&2, U32, List.append(&2, U32, t, b)), Nat.add(List.length(&2, U32, t), List.length(&2, U32, b)), len_app(t, b))

def len32(+x: Nat) -> {CS.length_is(32n, SS.bytes32(x)) == True{} : Bool}:
  Lg.subst(Nat, t => {Nat.is_eq(t, 32n) == True{} : Bool}, 32n, List.length(&2, U32, CS.i2osp(32n, x)), Equal.sym(Nat, List.length(&2, U32, CS.i2osp(32n, x)), 32n, EO.len_i2(32n, x)), {==})

def len64(+x: Nat, +y: Nat) -> {CS.length_is(64n, SS.cat(SS.bytes32(x), SS.bytes32(y))) == True{} : Bool}:
  Lg.subst(Nat, t => {Nat.is_eq(t, 64n) == True{} : Bool}, Nat.add(List.length(&2, U32, CS.i2osp(32n, x)), List.length(&2, U32, CS.i2osp(32n, y))), List.length(&2, U32, List.append(&2, U32, CS.i2osp(32n, x), CS.i2osp(32n, y))), Equal.sym(Nat, List.length(&2, U32, List.append(&2, U32, CS.i2osp(32n, x), CS.i2osp(32n, y))), Nat.add(List.length(&2, U32, CS.i2osp(32n, x)), List.length(&2, U32, CS.i2osp(32n, y))), len_app(CS.i2osp(32n, x), CS.i2osp(32n, y))),
    Lg.subst(Nat, t => {Nat.is_eq(Nat.add(t, List.length(&2, U32, CS.i2osp(32n, y))), 64n) == True{} : Bool}, 32n, List.length(&2, U32, CS.i2osp(32n, x)), Equal.sym(Nat, List.length(&2, U32, CS.i2osp(32n, x)), 32n, EO.len_i2(32n, x)),
      Lg.subst(Nat, t => {Nat.is_eq(Nat.add(32n, t), 64n) == True{} : Bool}, 32n, List.length(&2, U32, CS.i2osp(32n, y)), Equal.sym(Nat, List.length(&2, U32, CS.i2osp(32n, y)), 32n, EO.len_i2(32n, y)), {==})))

# ---- the specification's steps on a computed point ----

def eta_p(+one: Nat, +d0: Nat, +m: List<&2, U32>, +aux: List<&2, U32>, a: CS.SPoint) -> {SS.sign_p(one, d0, m, aux, CS.to_affine(SS.p(one), a)) == SS.sign_k(one, SS.th(one, SS.tag_challenge()), SS.even(SS.n(one), CS.aff_y(CS.to_affine(SS.p(one), a)), d0), SS.bytes32(CS.aff_x(CS.to_affine(SS.p(one), a))), m, Nat.mod(CS.os2ip(SS.tagged_h(SS.th(one, SS.tag_nonce()), SS.cat(SS.xor_bytes(SS.bytes32(SS.even(SS.n(one), CS.aff_y(CS.to_affine(SS.p(one), a)), d0)), SS.tagged_h(SS.th(one, SS.tag_aux()), aux)), SS.cat(SS.bytes32(CS.aff_x(CS.to_affine(SS.p(one), a))), m)))), SS.n(one))) : MBT}:
  match a:
    case CS.SPoint{x, y, z}:
      {==}

def eta_r(+one: Nat, +d: Nat, +pb: List<&2, U32>, +m: List<&2, U32>, +k0: Nat, a: CS.SPoint) -> {SS.sign_r(one, SS.th(one, SS.tag_challenge()), d, pb, m, k0, CS.to_affine(SS.p(one), a)) == SS.sign_fin(one, SS.th(one, SS.tag_challenge()), pb, m, SS.cat(SS.bytes32(CS.aff_x(CS.to_affine(SS.p(one), a))), SS.bytes32(FS.madd(SS.n(one), SS.even(SS.n(one), CS.aff_y(CS.to_affine(SS.p(one), a)), k0), FS.mmul(SS.n(one), Nat.mod(CS.os2ip(SS.tagged_h(SS.th(one, SS.tag_challenge()), SS.cat(SS.bytes32(CS.aff_x(CS.to_affine(SS.p(one), a))), SS.cat(pb, m)))), SS.n(one)), d))))) : MBT}:
  match a:
    case CS.SPoint{x, y, z}:
      {==}

def eta_pub(+one: Nat, a: CS.SPoint) -> {SS.pub_of(CS.to_affine(SS.p(one), a)) == SS.bytes32(CS.aff_x(CS.to_affine(SS.p(one), a))) : List<&2, U32>}:
  match a:
    case CS.SPoint{x, y, z}:
      {==}

# ---- the folded tagged hash of schd.bend is the specification's ----

def tg_eq(+tag: List<&2, U32>, x: List<&2, U32>) -> {D.tg(tag, x) == SS.tagged(tag, x) : List<&2, U32>}:
  match x:
    case Nil{}:
      {==}
    case h <> r:
      {==}

# the tag hashes of the specification (SS.th looks at one first)
def th_tagged(one: Nat, +tag: List<&2, U32>, +x: List<&2, U32>) -> {SS.tagged(tag, x) == SS.tagged_h(SS.th(one, tag), x) : List<&2, U32>}:
  match one:
    case 0n:
      {==}
    case 1n+k:
      {==}

def tg_eq1(+one: Nat, +tag: List<&2, U32>, +x: List<&2, U32>) -> {D.tg(tag, x) == SS.tagged_h(SS.th(one, tag), x) : List<&2, U32>}:
  Equal.trans(List<&2, U32>, D.tg(tag, x), SS.tagged(tag, x), SS.tagged_h(SS.th(one, tag), x), tg_eq(tag, x), th_tagged(one, tag, x))

def eta_p2(+one: Nat, +d0: Nat, +m: List<&2, U32>, +aux: List<&2, U32>, +a: CS.SPoint) -> {SS.sign_p(one, d0, m, aux, CS.to_affine(SS.p(one), a)) == SS.sign_kz(one, SS.th(one, SS.tag_challenge()), SS.even(SS.n(one), CS.aff_y(CS.to_affine(SS.p(one), a)), d0), SS.bytes32(CS.aff_x(CS.to_affine(SS.p(one), a))), m, Nat.mod(CS.os2ip(D.tg(SS.tag_nonce(), SS.cat(SS.xor_bytes(SS.bytes32(SS.even(SS.n(one), CS.aff_y(CS.to_affine(SS.p(one), a)), d0)), D.tg(SS.tag_aux(), aux)), SS.cat(SS.bytes32(CS.aff_x(CS.to_affine(SS.p(one), a))), m)))), SS.n(one)), Nat.is_eq(Nat.mod(CS.os2ip(D.tg(SS.tag_nonce(), SS.cat(SS.xor_bytes(SS.bytes32(SS.even(SS.n(one), CS.aff_y(CS.to_affine(SS.p(one), a)), d0)), D.tg(SS.tag_aux(), aux)), SS.cat(SS.bytes32(CS.aff_x(CS.to_affine(SS.p(one), a))), m)))), SS.n(one)), 0n)) : Maybe<&2, List<&2, U32>>}:
  Equal.trans(Maybe<&2, List<&2, U32>>, SS.sign_p(one, d0, m, aux, CS.to_affine(SS.p(one), a)), SS.sign_k(one, SS.th(one, SS.tag_challenge()), SS.even(SS.n(one), CS.aff_y(CS.to_affine(SS.p(one), a)), d0), SS.bytes32(CS.aff_x(CS.to_affine(SS.p(one), a))), m, Nat.mod(CS.os2ip(SS.tagged_h(SS.th(one, SS.tag_nonce()), SS.cat(SS.xor_bytes(SS.bytes32(SS.even(SS.n(one), CS.aff_y(CS.to_affine(SS.p(one), a)), d0)), SS.tagged_h(SS.th(one, SS.tag_aux()), aux)), SS.cat(SS.bytes32(CS.aff_x(CS.to_affine(SS.p(one), a))), m)))), SS.n(one))), SS.sign_kz(one, SS.th(one, SS.tag_challenge()), SS.even(SS.n(one), CS.aff_y(CS.to_affine(SS.p(one), a)), d0), SS.bytes32(CS.aff_x(CS.to_affine(SS.p(one), a))), m, Nat.mod(CS.os2ip(D.tg(SS.tag_nonce(), SS.cat(SS.xor_bytes(SS.bytes32(SS.even(SS.n(one), CS.aff_y(CS.to_affine(SS.p(one), a)), d0)), D.tg(SS.tag_aux(), aux)), SS.cat(SS.bytes32(CS.aff_x(CS.to_affine(SS.p(one), a))), m)))), SS.n(one)), Nat.is_eq(Nat.mod(CS.os2ip(D.tg(SS.tag_nonce(), SS.cat(SS.xor_bytes(SS.bytes32(SS.even(SS.n(one), CS.aff_y(CS.to_affine(SS.p(one), a)), d0)), D.tg(SS.tag_aux(), aux)), SS.cat(SS.bytes32(CS.aff_x(CS.to_affine(SS.p(one), a))), m)))), SS.n(one)), 0n)), eta_p(one, d0, m, aux, a),
    Equal.trans(Maybe<&2, List<&2, U32>>, SS.sign_k(one, SS.th(one, SS.tag_challenge()), SS.even(SS.n(one), CS.aff_y(CS.to_affine(SS.p(one), a)), d0), SS.bytes32(CS.aff_x(CS.to_affine(SS.p(one), a))), m, Nat.mod(CS.os2ip(SS.tagged_h(SS.th(one, SS.tag_nonce()), SS.cat(SS.xor_bytes(SS.bytes32(SS.even(SS.n(one), CS.aff_y(CS.to_affine(SS.p(one), a)), d0)), SS.tagged_h(SS.th(one, SS.tag_aux()), aux)), SS.cat(SS.bytes32(CS.aff_x(CS.to_affine(SS.p(one), a))), m)))), SS.n(one))), SS.sign_k(one, SS.th(one, SS.tag_challenge()), SS.even(SS.n(one), CS.aff_y(CS.to_affine(SS.p(one), a)), d0), SS.bytes32(CS.aff_x(CS.to_affine(SS.p(one), a))), m, Nat.mod(CS.os2ip(D.tg(SS.tag_nonce(), SS.cat(SS.xor_bytes(SS.bytes32(SS.even(SS.n(one), CS.aff_y(CS.to_affine(SS.p(one), a)), d0)), SS.tagged_h(SS.th(one, SS.tag_aux()), aux)), SS.cat(SS.bytes32(CS.aff_x(CS.to_affine(SS.p(one), a))), m)))), SS.n(one))), SS.sign_kz(one, SS.th(one, SS.tag_challenge()), SS.even(SS.n(one), CS.aff_y(CS.to_affine(SS.p(one), a)), d0), SS.bytes32(CS.aff_x(CS.to_affine(SS.p(one), a))), m, Nat.mod(CS.os2ip(D.tg(SS.tag_nonce(), SS.cat(SS.xor_bytes(SS.bytes32(SS.even(SS.n(one), CS.aff_y(CS.to_affine(SS.p(one), a)), d0)), D.tg(SS.tag_aux(), aux)), SS.cat(SS.bytes32(CS.aff_x(CS.to_affine(SS.p(one), a))), m)))), SS.n(one)), Nat.is_eq(Nat.mod(CS.os2ip(D.tg(SS.tag_nonce(), SS.cat(SS.xor_bytes(SS.bytes32(SS.even(SS.n(one), CS.aff_y(CS.to_affine(SS.p(one), a)), d0)), D.tg(SS.tag_aux(), aux)), SS.cat(SS.bytes32(CS.aff_x(CS.to_affine(SS.p(one), a))), m)))), SS.n(one)), 0n)),
      Equal.cong(List<&2, U32>, Maybe<&2, List<&2, U32>>, t => SS.sign_k(one, SS.th(one, SS.tag_challenge()), SS.even(SS.n(one), CS.aff_y(CS.to_affine(SS.p(one), a)), d0), SS.bytes32(CS.aff_x(CS.to_affine(SS.p(one), a))), m, Nat.mod(CS.os2ip(t), SS.n(one))), SS.tagged_h(SS.th(one, SS.tag_nonce()), SS.cat(SS.xor_bytes(SS.bytes32(SS.even(SS.n(one), CS.aff_y(CS.to_affine(SS.p(one), a)), d0)), SS.tagged_h(SS.th(one, SS.tag_aux()), aux)), SS.cat(SS.bytes32(CS.aff_x(CS.to_affine(SS.p(one), a))), m))), D.tg(SS.tag_nonce(), SS.cat(SS.xor_bytes(SS.bytes32(SS.even(SS.n(one), CS.aff_y(CS.to_affine(SS.p(one), a)), d0)), SS.tagged_h(SS.th(one, SS.tag_aux()), aux)), SS.cat(SS.bytes32(CS.aff_x(CS.to_affine(SS.p(one), a))), m))), Equal.sym(List<&2, U32>, D.tg(SS.tag_nonce(), SS.cat(SS.xor_bytes(SS.bytes32(SS.even(SS.n(one), CS.aff_y(CS.to_affine(SS.p(one), a)), d0)), SS.tagged_h(SS.th(one, SS.tag_aux()), aux)), SS.cat(SS.bytes32(CS.aff_x(CS.to_affine(SS.p(one), a))), m))), SS.tagged_h(SS.th(one, SS.tag_nonce()), SS.cat(SS.xor_bytes(SS.bytes32(SS.even(SS.n(one), CS.aff_y(CS.to_affine(SS.p(one), a)), d0)), SS.tagged_h(SS.th(one, SS.tag_aux()), aux)), SS.cat(SS.bytes32(CS.aff_x(CS.to_affine(SS.p(one), a))), m))), tg_eq1(one, SS.tag_nonce(), SS.cat(SS.xor_bytes(SS.bytes32(SS.even(SS.n(one), CS.aff_y(CS.to_affine(SS.p(one), a)), d0)), SS.tagged_h(SS.th(one, SS.tag_aux()), aux)), SS.cat(SS.bytes32(CS.aff_x(CS.to_affine(SS.p(one), a))), m))))),
      Equal.cong(List<&2, U32>, Maybe<&2, List<&2, U32>>, t => SS.sign_k(one, SS.th(one, SS.tag_challenge()), SS.even(SS.n(one), CS.aff_y(CS.to_affine(SS.p(one), a)), d0), SS.bytes32(CS.aff_x(CS.to_affine(SS.p(one), a))), m, Nat.mod(CS.os2ip(D.tg(SS.tag_nonce(), SS.cat(SS.xor_bytes(SS.bytes32(SS.even(SS.n(one), CS.aff_y(CS.to_affine(SS.p(one), a)), d0)), t), SS.cat(SS.bytes32(CS.aff_x(CS.to_affine(SS.p(one), a))), m)))), SS.n(one))), SS.tagged_h(SS.th(one, SS.tag_aux()), aux), D.tg(SS.tag_aux(), aux), Equal.sym(List<&2, U32>, D.tg(SS.tag_aux(), aux), SS.tagged_h(SS.th(one, SS.tag_aux()), aux), tg_eq1(one, SS.tag_aux(), aux)))))

def eta_r2(+one: Nat, +d: Nat, +pb: List<&2, U32>, +m: List<&2, U32>, +k0: Nat, +a: CS.SPoint) -> {SS.sign_r(one, SS.th(one, SS.tag_challenge()), d, pb, m, k0, CS.to_affine(SS.p(one), a)) == SS.sign_fin(one, SS.th(one, SS.tag_challenge()), pb, m, SS.cat(SS.bytes32(CS.aff_x(CS.to_affine(SS.p(one), a))), SS.bytes32(FS.madd(SS.n(one), SS.even(SS.n(one), CS.aff_y(CS.to_affine(SS.p(one), a)), k0), FS.mmul(SS.n(one), Nat.mod(CS.os2ip(D.tg(SS.tag_challenge(), SS.cat(SS.bytes32(CS.aff_x(CS.to_affine(SS.p(one), a))), SS.cat(pb, m)))), SS.n(one)), d))))) : Maybe<&2, List<&2, U32>>}:
  Equal.trans(Maybe<&2, List<&2, U32>>, SS.sign_r(one, SS.th(one, SS.tag_challenge()), d, pb, m, k0, CS.to_affine(SS.p(one), a)), SS.sign_fin(one, SS.th(one, SS.tag_challenge()), pb, m, SS.cat(SS.bytes32(CS.aff_x(CS.to_affine(SS.p(one), a))), SS.bytes32(FS.madd(SS.n(one), SS.even(SS.n(one), CS.aff_y(CS.to_affine(SS.p(one), a)), k0), FS.mmul(SS.n(one), Nat.mod(CS.os2ip(SS.tagged_h(SS.th(one, SS.tag_challenge()), SS.cat(SS.bytes32(CS.aff_x(CS.to_affine(SS.p(one), a))), SS.cat(pb, m)))), SS.n(one)), d))))), SS.sign_fin(one, SS.th(one, SS.tag_challenge()), pb, m, SS.cat(SS.bytes32(CS.aff_x(CS.to_affine(SS.p(one), a))), SS.bytes32(FS.madd(SS.n(one), SS.even(SS.n(one), CS.aff_y(CS.to_affine(SS.p(one), a)), k0), FS.mmul(SS.n(one), Nat.mod(CS.os2ip(D.tg(SS.tag_challenge(), SS.cat(SS.bytes32(CS.aff_x(CS.to_affine(SS.p(one), a))), SS.cat(pb, m)))), SS.n(one)), d))))), eta_r(one, d, pb, m, k0, a), Equal.cong(List<&2, U32>, Maybe<&2, List<&2, U32>>, t => SS.sign_fin(one, SS.th(one, SS.tag_challenge()), pb, m, SS.cat(SS.bytes32(CS.aff_x(CS.to_affine(SS.p(one), a))), SS.bytes32(FS.madd(SS.n(one), SS.even(SS.n(one), CS.aff_y(CS.to_affine(SS.p(one), a)), k0), FS.mmul(SS.n(one), Nat.mod(CS.os2ip(t), SS.n(one)), d))))), SS.tagged_h(SS.th(one, SS.tag_challenge()), SS.cat(SS.bytes32(CS.aff_x(CS.to_affine(SS.p(one), a))), SS.cat(pb, m))), D.tg(SS.tag_challenge(), SS.cat(SS.bytes32(CS.aff_x(CS.to_affine(SS.p(one), a))), SS.cat(pb, m))), Equal.sym(List<&2, U32>, D.tg(SS.tag_challenge(), SS.cat(SS.bytes32(CS.aff_x(CS.to_affine(SS.p(one), a))), SS.cat(pb, m))), SS.tagged_h(SS.th(one, SS.tag_challenge()), SS.cat(SS.bytes32(CS.aff_x(CS.to_affine(SS.p(one), a))), SS.cat(pb, m))), tg_eq1(one, SS.tag_challenge(), SS.cat(SS.bytes32(CS.aff_x(CS.to_affine(SS.p(one), a))), SS.cat(pb, m))))))

def vp_raw(+one: Nat, +pk: List<&2, U32>, +m: List<&2, U32>, +sig: List<&2, U32>, +pp: CS.SPoint) -> {SS.verify_p(one, SS.th(one, SS.tag_challenge()), pk, m, sig, Some{pp}) == SS.verify_ok(one, CS.os2ip(CS.first(32n, sig)), CS.os2ip(CS.after(32n, sig)), Nat.mod(CS.os2ip(SS.tagged_h(SS.th(one, SS.tag_challenge()), SS.cat(CS.first(32n, sig), SS.cat(pk, m)))), SS.n(one)), pp, Bool.and(Nat.is_lt(CS.os2ip(CS.first(32n, sig)), SS.p(one)), Nat.is_lt(CS.os2ip(CS.after(32n, sig)), SS.n(one)))) : Bool}:
  {==}

# verify_p on a lifted key, with the challenge folded
def vp_unf(+one: Nat, +pk: List<&2, U32>, +m: List<&2, U32>, +sig: List<&2, U32>, +pp: CS.SPoint) -> {SS.verify_p(one, SS.th(one, SS.tag_challenge()), pk, m, sig, Some{pp}) == SS.verify_ok(one, CS.os2ip(CS.first(32n, sig)), CS.os2ip(CS.after(32n, sig)), Nat.mod(CS.os2ip(D.tg(SS.tag_challenge(), SS.cat(CS.first(32n, sig), SS.cat(pk, m)))), SS.n(one)), pp, Bool.and(Nat.is_lt(CS.os2ip(CS.first(32n, sig)), SS.p(one)), Nat.is_lt(CS.os2ip(CS.after(32n, sig)), SS.n(one)))) : Bool}:
  Equal.trans(Bool, SS.verify_p(one, SS.th(one, SS.tag_challenge()), pk, m, sig, Some{pp}), SS.verify_ok(one, CS.os2ip(CS.first(32n, sig)), CS.os2ip(CS.after(32n, sig)), Nat.mod(CS.os2ip(SS.tagged_h(SS.th(one, SS.tag_challenge()), SS.cat(CS.first(32n, sig), SS.cat(pk, m)))), SS.n(one)), pp, Bool.and(Nat.is_lt(CS.os2ip(CS.first(32n, sig)), SS.p(one)), Nat.is_lt(CS.os2ip(CS.after(32n, sig)), SS.n(one)))), SS.verify_ok(one, CS.os2ip(CS.first(32n, sig)), CS.os2ip(CS.after(32n, sig)), Nat.mod(CS.os2ip(D.tg(SS.tag_challenge(), SS.cat(CS.first(32n, sig), SS.cat(pk, m)))), SS.n(one)), pp, Bool.and(Nat.is_lt(CS.os2ip(CS.first(32n, sig)), SS.p(one)), Nat.is_lt(CS.os2ip(CS.after(32n, sig)), SS.n(one)))), vp_raw(one, pk, m, sig, pp), Equal.cong(List<&2, U32>, Bool, t => SS.verify_ok(one, CS.os2ip(CS.first(32n, sig)), CS.os2ip(CS.after(32n, sig)), Nat.mod(CS.os2ip(t), SS.n(one)), pp, Bool.and(Nat.is_lt(CS.os2ip(CS.first(32n, sig)), SS.p(one)), Nat.is_lt(CS.os2ip(CS.after(32n, sig)), SS.n(one)))), SS.tagged_h(SS.th(one, SS.tag_challenge()), SS.cat(CS.first(32n, sig), SS.cat(pk, m))), D.tg(SS.tag_challenge(), SS.cat(CS.first(32n, sig), SS.cat(pk, m))), Equal.sym(List<&2, U32>, D.tg(SS.tag_challenge(), SS.cat(CS.first(32n, sig), SS.cat(pk, m))), SS.tagged_h(SS.th(one, SS.tag_challenge()), SS.cat(CS.first(32n, sig), SS.cat(pk, m))), tg_eq1(one, SS.tag_challenge(), SS.cat(CS.first(32n, sig), SS.cat(pk, m))))))

# ---- the secret key ----

def so_d0(+one: Nat, +sk: List<&2, U32>, +hso: {SS.secret_ok(one, sk) == True{} : Bool}) -> {Nat.is_eq(CS.os2ip(sk), 0n) == False{} : Bool}:
  Lg.not_true(Nat.is_eq(CS.os2ip(sk), 0n), Lg.and_left(Bool.not(Nat.is_eq(CS.os2ip(sk), 0n)), Nat.is_lt(CS.os2ip(sk), SS.n(one)), Lg.and_right(CS.length_is(32n, sk), Bool.and(Bool.not(Nat.is_eq(CS.os2ip(sk), 0n)), Nat.is_lt(CS.os2ip(sk), SS.n(one))), hso)))

def so_dn(+one: Nat, +sk: List<&2, U32>, +hso: {SS.secret_ok(one, sk) == True{} : Bool}) -> {Nat.is_lt(CS.os2ip(sk), FS.order(one)) == True{} : Bool}:
  Lg.and_right(Bool.not(Nat.is_eq(CS.os2ip(sk), 0n)), Nat.is_lt(CS.os2ip(sk), SS.n(one)), Lg.and_right(CS.length_is(32n, sk), Bool.and(Bool.not(Nat.is_eq(CS.os2ip(sk), 0n)), Nat.is_lt(CS.os2ip(sk), SS.n(one))), hso))

# PubKey(sk) = bytes(x(d' G))
def pubkey(+one: Nat, +sk: List<&2, U32>, +hso: {SS.secret_ok(one, sk) == True{} : Bool}) -> {SS.pubkey(one, sk) == Some{D.pkb(one, sk)} : MBT}:
  Equal.trans(MBT, SS.pubkey(one, sk), Some{SS.pub_of(TAPX)}, Some{D.pkb(one, sk)}, Equal.cong(Bool, MBT, t => SS.pubkey_ok(one, sk, t), SS.secret_ok(one, sk), True{}, hso), Equal.cong(List<&2, U32>, MBT, t => Some{t}, SS.pub_of(TAPX), D.pkb(one, sk), eta_pub(one, PMDX)))
"""


def protocol():
    d0 = 'CS.os2ip(sk)'
    TAP = ta(p, d0)
    px, py = 'CS.aff_x(%s)' % TAP, 'CS.aff_y(%s)' % TAP
    bP = 'Nat.mod(%s, 2n)' % py
    KEY, PKB, K0, CH, SV = 'D.key(one, sk)', 'D.pkb(one, sk)', 'D.nonce(one, sk, m, aux)', 'D.chal(one, sk, m, aux)', 'D.sval(one, sk, m, aux)'
    TAR = ta(p, K0)
    rx, ry = 'CS.aff_x(%s)' % TAR, 'CS.aff_y(%s)' % TAR
    bR = 'Nat.mod(%s, 2n)' % ry
    KK = 'SS.even_b(%s, %s, %s)' % (n, bR, K0)
    DK = 'SS.even_b(%s, %s, %s)' % (n, bP, d0)
    SVV = 'Nat.add(SS.even(SS.n(one), %s, %s), FS.mmul(SS.n(one), %s, %s))' % (ry, K0, CH, KEY)
    RB, SBY = 'SS.bytes32(%s)' % rx, 'SS.bytes32(%s)' % SV
    SIGX = 'SS.cat(%s, %s)' % (RB, SBY)
    SIG = 'D.sigv(one, sk, m, aux)'
    PP = 'CS.SPoint{%s, SS.even_b(%s, %s, %s), 1n}' % (px, p, bP, py)
    EYP = 'SS.even_b(%s, %s, %s)' % (p, bP, py)
    EYR = 'SS.even_b(%s, %s, %s)' % (p, bR, ry)
    PMD, PMK = 'CS.pmul(%s, %s, %s)' % (p, d0, G), 'CS.pmul(%s, %s, %s)' % (p, K0, G)
    SO = '+hso: {SS.secret_ok(one, sk) == True{} : Bool}'
    HK0 = '+hk0: {Nat.is_eq(%s, 0n) == False{} : Bool}' % K0
    HLA = '+hla: {CS.length_is(32n, aux) == True{} : Bool}'
    VARS = '+sk: List<&2, U32>, +m: List<&2, U32>, +aux: List<&2, U32>'
    aP = '%s, %s, %s, %s, %s, %s, %s' % (p, n, G, px, py, d0, bP)
    aK = '%s, %s, %s, %s, %s, %s, %s' % (p, n, G, rx, ry, K0, bR)
    MSP = 'Maybe<&2, CS.SPoint>'

    def lt(a, b):
        return 'Nat.is_lt(%s, %s)' % (a, b)

    def AND(a, b):
        return 'Bool.and(%s, %s)' % (a, b)

    # ---- the core on variables ----
    PKv, RBv, SBv = 'SS.bytes32(px)', 'SS.bytes32(rx)', 'SS.bytes32(sv)'
    SGv = 'SS.cat(%s, %s)' % (RBv, SBv)
    PPv = 'CS.SPoint{px, ey, 1n}'
    AFT = 'CS.after(32n, %s)' % SGv
    FST = 'CS.first(32n, %s)' % SGv

    def VO(r, s_, f_, ok):
        return 'SS.verify_ok(one, %s, %s, Nat.mod(CS.os2ip(D.tg(SS.tag_challenge(), SS.cat(%s, SS.cat(%s, m)))), SS.n(one)), %s, %s)' % (r, s_, f_, PKv, PPv, ok)

    full = VO('CS.os2ip(%s)' % FST, 'CS.os2ip(%s)' % AFT, FST, AND(lt('CS.os2ip(%s)' % FST, 'SS.p(one)'), lt('CS.os2ip(%s)' % AFT, 'SS.n(one)')))
    len_rb = 'EO.len_i2(32n, rx)'
    steps = [
        ('Bool', lambda t: eq_true('SS.verify_len(one, SS.th(one, SS.tag_challenge()), %s, m, %s, %s)' % (PKv, SGv, t)), AND('CS.length_is(32n, %s)' % PKv, 'CS.length_is(64n, %s)' % SGv), 'True{}',
         'Lg.and_intro(CS.length_is(32n, %s), CS.length_is(64n, %s), len32(px), len64(rx, sv))' % (PKv, SGv)),
        ('Nat', lambda t: eq_true('SS.verify_p(one, SS.th(one, SS.tag_challenge()), %s, m, %s, SS.lift_x(one, %s))' % (PKv, SGv, t)), 'CS.os2ip(%s)' % PKv, 'px', 'EO.os_i2_32(px, hfpx)'),
        ('Bool', lambda t: eq_true('SS.verify_p(one, SS.th(one, SS.tag_challenge()), %s, m, %s, SS.lift_if(one, px, %s))' % (PKv, SGv, t)), lt('px', 'SS.p(one)'), 'True{}', 'hpx'),
        (MSP, lambda t: eq_true('SS.verify_p(one, SS.th(one, SS.tag_challenge()), %s, m, %s, %s)' % (PKv, SGv, t)), 'CS.decompress(SS.p(one), px, 0n)', 'Some{%s}' % PPv, 'hdec'),
        ('Bool', lambda t: eq_true(t), 'SS.verify_p(one, SS.th(one, SS.tag_challenge()), %s, m, %s, Some{%s})' % (PKv, SGv, PPv), full, 'vp_unf(one, %s, m, %s, %s)' % (PKv, SGv, PPv)),
        (BYTES, lambda t: eq_true(VO('CS.os2ip(%s)' % t, 'CS.os2ip(%s)' % AFT, t, AND(lt('CS.os2ip(%s)' % t, 'SS.p(one)'), lt('CS.os2ip(%s)' % AFT, 'SS.n(one)')))),
         FST, RBv, 'EO.first_app(%s, 32n, %s, %s)' % (RBv, SBv, len_rb)),
        (BYTES, lambda t: eq_true(VO('CS.os2ip(%s)' % RBv, 'CS.os2ip(%s)' % t, RBv, AND(lt('CS.os2ip(%s)' % RBv, 'SS.p(one)'), lt('CS.os2ip(%s)' % t, 'SS.n(one)')))),
         AFT, SBv, 'EO.after_app(%s, 32n, %s, %s)' % (RBv, SBv, len_rb)),
        ('Nat', lambda t: eq_true(VO(t, 'CS.os2ip(%s)' % SBv, RBv, AND(lt(t, 'SS.p(one)'), lt('CS.os2ip(%s)' % SBv, 'SS.n(one)')))), 'CS.os2ip(%s)' % RBv, 'rx', 'EO.os_i2_32(rx, hfrx)'),
        ('Nat', lambda t: eq_true(VO('rx', t, RBv, AND(lt('rx', 'SS.p(one)'), lt(t, 'SS.n(one)')))), 'CS.os2ip(%s)' % SBv, 'sv', 'EO.os_i2_32(sv, hfsv)'),
        ('Bool', lambda t: eq_true(VO('rx', 'sv', RBv, AND(t, lt('sv', 'SS.n(one)')))), lt('rx', 'SS.p(one)'), 'True{}', 'hrx'),
        ('Bool', lambda t: eq_true(VO('rx', 'sv', RBv, AND('True{}', t))), lt('sv', 'SS.n(one)'), 'True{}', 'hsv'),
    ]
    vcore = subst_chain('Bool', steps, 'hvr')

    def cong(mot, a, b, pr):
        return 'Equal.cong(Bool, %s, t => %s, %s, %s, %s)' % (MB, mot('t'), a, b, pr)

    def tr(a, b, c, h1_, h2_):
        return 'Equal.trans(%s, %s, %s, %s, %s, %s)' % (MB, a, b, c, h1_, h2_)

    def sy(a, b, h):
        return 'Equal.sym(%s, %s, %s, %s)' % (MB, a, b, h)

    B0 = AND('CS.length_is(32n, aux)', 'SS.secret_ok(one, sk)')
    A0 = 'SS.sign(one, sk, m, aux)'
    A1 = 'SS.sign_p(one, %s, m, aux, %s)' % (d0, TAP)
    A2 = 'SS.sign_kz(one, SS.th(one, SS.tag_challenge()), %s, %s, m, %s, Nat.is_eq(%s, 0n))' % (KEY, PKB, K0, K0)
    A3 = 'SS.sign_r(one, SS.th(one, SS.tag_challenge()), %s, %s, m, %s, %s)' % (KEY, PKB, K0, TAR)
    A4 = 'SS.sign_if(%s, SS.verify(one, %s, m, %s))' % (SIGX, PKB, SIGX)
    A5 = 'Some{%s}' % SIG
    VER = 'SS.verify(one, %s, m, %s)' % (PKB, SIGX)
    c_ok = lambda val, h: cong(lambda t: 'SS.sign_ok(one, sk, m, aux, %s)' % t, B0, val, h)
    c_kz = lambda val, h: cong(lambda t: 'SS.sign_kz(one, SS.th(one, SS.tag_challenge()), %s, %s, m, %s, %s)' % (KEY, PKB, K0, t), 'Nat.is_eq(%s, 0n)' % K0, val, h)
    c_if = lambda val, h: cong(lambda t: 'SS.sign_if(%s, %s)' % (SIGX, t), VER, val, h)
    e1 = 'eta_p2(one, %s, m, aux, %s)' % (d0, PMD)
    e3 = 'eta_r2(one, %s, %s, m, %s, %s)' % (KEY, PKB, K0, PMK)
    goal = '{SS.verify(one, pk, m, sig) == True{} : Bool}'
    HS = '+sig: List<&2, U32>, +pk: List<&2, U32>, +hpk: {SS.pubkey(one, sk) == Some{pk} : %s}' % MB
    NS = lambda lhs, h: 'Lg.none_some(List<&2, U32>, sig, %s)' % tr('None{}', lhs, 'Some{sig}', h, 'hs')
    o = [PROTO_HEAD.replace('MBT', MB).replace('TAPX', TAP).replace('PMDX', PMD)]
    o.append('# ---- verification, on variables ----\n')
    o.append('# a key (px, ey) that lift_x finds, R with x = rx, s = sv, and the verification equation: Verify accepts\n'
             'def vcore(+one: Nat, +px: Nat, +ey: Nat, +rx: Nat, +sv: Nat, +m: List<&2, U32>, +hfpx: {C.fits(256n, px) == True{} : Bool}, +hpx: %s, +hdec: {CS.decompress(SS.p(one), px, 0n) == Some{%s} : %s}, +hfrx: {C.fits(256n, rx) == True{} : Bool}, +hrx: %s, +hfsv: {C.fits(256n, sv) == True{} : Bool}, +hsv: %s, +hvr: %s) -> %s:\n  %s\n' % (
                 eq_true(lt('px', 'SS.p(one)')), PPv, MSP, eq_true(lt('rx', 'SS.p(one)')), eq_true(lt('sv', 'SS.n(one)')),
                 eq_true('SS.verify_rs(one, rx, sv, Nat.mod(CS.os2ip(D.tg(SS.tag_challenge(), SS.cat(%s, SS.cat(%s, m)))), SS.n(one)), %s)' % (RBv, PKv, PPv)), eq_true('SS.verify(one, %s, m, %s)' % (PKv, SGv)), vcore))
    o.append('# ---- the facts about the two points of a signature ----\n')
    NV = 'CS.os2ip(D.tg(SS.tag_nonce(), SS.cat(SS.xor_bytes(SS.bytes32(D.key(one, sk)), D.tg(SS.tag_aux(), aux)), SS.cat(D.pkb(one, sk), m))))'
    o.append('def k_lt(+one: Nat, +h1: {one == 1n : Nat}, %s) -> %s:\n  SG.sb_lt(%s, %s, SH.tsb(one, h1, %s))\n' % (VARS, eq_true(lt(K0, n)), n, NV, NV))
    o.append('def ev_p(%s, +sk: List<&2, U32>, %s) -> SG.EvR(%s):\n  SH.tev(%s, %s, so_d0(one, sk, hso), so_dn(one, sk, hso))\n' % (HD, SO, aP, HA, d0))
    o.append('def ev_k(%s, %s, %s) -> SG.EvR(%s):\n  SH.tev(%s, %s, hk0, k_lt(one, h1, sk, m, aux))\n' % (HD, VARS, HK0, aK, HA, K0))
    evP, evK = 'ev_p(%s, sk, hso)' % HA, 'ev_k(%s, sk, m, aux, hk0)' % HA
    o.append('def vr_f(%s, %s, %s, %s) -> SG.VR(%s, %s, %s, %s, %s, %s, %s, %s):\n  SH.tvr(%s, %s, %s, %s, %s, %s, %s, SH.tel(one, h1, %s, %s, k_lt(one, h1, sk, m, aux)), SG.ev3(%s, %s), SG.ev2(%s, %s), SG.ev3(%s, %s), SG.ev2(%s, %s), SG.ax_lt(%s, %s, SH.taxb(one, h1, %s)), SG.ev5(%s, %s), SG.ev4(%s, %s))\n' % (
        HD, VARS, SO, HK0, p, n, G, DK, KK, CH, PP, rx,
        HA, DK, KK, CH, PP, rx, EYR, bR, K0, aP, evP, aP, evP, aK, evK, aK, evK, p, PMK, PMK, aK, evK, aK, evK))
    o.append('# ---- verification of the signature signing computes ----\n')
    o.append('def verifies(%s, %s, %s, %s) -> {SS.verify(one, %s, m, %s) == True{} : Bool}:\n  vcore(one, %s, %s, %s, %s, m, SG.ax_fit(%s, %s, SH.taxb(one, h1, %s)), SG.ax_lt(%s, %s, SH.taxb(one, h1, %s)), SG.ev1(%s, %s), SG.ax_fit(%s, %s, SH.taxb(one, h1, %s)), SG.ax_lt(%s, %s, SH.taxb(one, h1, %s)), SG.sb_fit(%s, %s, SH.tsb(one, h1, %s)), SG.sb_lt(%s, %s, SH.tsb(one, h1, %s)), vr_f(%s, sk, m, aux, hso, hk0))\n' % (
        HD, VARS, SO, HK0, PKB, SIG,
        px, EYP, rx, SV, p, PMD, PMD, p, PMD, PMD, aP, evP, p, PMK, PMK, p, PMK, PMK, n, SVV, SVV, n, SVV, SVV, HA))
    o.append('# ---- signing ----\n')
    o.append('def sign_a2(+one: Nat, %s, +hb: %s) -> {%s == %s : %s}:\n  %s\n' % (VARS, eq_true(B0), A0, A2, MB, tr(A0, A1, A2, c_ok('True{}', 'hb'), e1)))
    o.append('def sign_a4(+one: Nat, %s, %s) -> {%s == %s : %s}:\n  %s\n' % (VARS, HK0, A2, A4, MB, tr(A2, A3, A4, c_kz('False{}', 'hk0'), e3)))
    o.append('# Sign(sk, m, a) succeeds when the nonce is not 0, with the signature of schd.bend\n'
             'def signs(%s, %s, %s, %s, %s) -> {%s == %s : %s}:\n  %s\n' % (
                 HD, VARS, HLA, SO, HK0, A0, A5, MB,
                 tr(A0, A2, A5, 'sign_a2(one, sk, m, aux, Lg.and_intro(CS.length_is(32n, aux), SS.secret_ok(one, sk), hla, hso))',
                    tr(A2, A4, A5, 'sign_a4(one, sk, m, aux, hk0)', c_if('True{}', 'verifies(%s, sk, m, aux, hso, hk0)' % HA)))))
    o.append('# ---- what sign returns verifies (from its final self-check alone) ----\n')
    o.append('def sv3(+one: Nat, %s, %s, %s, +hs: {%s == Some{sig} : %s}, c: Bool, +hc: {%s == c : Bool}) -> %s:\n  match c:\n    case False{}:\n      Empty.absurd(%s, %s)\n    case True{}:\n      %s\n' % (
        VARS, HS, SO, A4, MB, VER, goal, goal, NS(A4, sy(A4, 'None{}', c_if('False{}', 'hc'))),
        'Lg.subst(List<&2, U32>, t => {SS.verify(one, t, m, sig) == True{} : Bool}, %s, pk, Lg.some_inj(List<&2, U32>, %s, pk, %s), Lg.subst(List<&2, U32>, t => {SS.verify(one, %s, m, t) == True{} : Bool}, %s, sig, Lg.some_inj(List<&2, U32>, %s, sig, %s), hc))' % (
            PKB, PKB, tr('Some{%s}' % PKB, 'SS.pubkey(one, sk)', 'Some{pk}', sy('SS.pubkey(one, sk)', 'Some{%s}' % PKB, 'pubkey(one, sk, hso)'), 'hpk'),
            PKB, SIGX, SIGX, tr('Some{%s}' % SIGX, A4, 'Some{sig}', sy(A4, 'Some{%s}' % SIGX, c_if('True{}', 'hc')), 'hs'))))
    o.append('def sv2(+one: Nat, %s, %s, %s, +hs: {%s == Some{sig} : %s}, c: Bool, +hc: {Nat.is_eq(%s, 0n) == c : Bool}) -> %s:\n  match c:\n    case True{}:\n      Empty.absurd(%s, %s)\n    case False{}:\n      sv3(one, sk, m, aux, sig, pk, hpk, hso, %s, %s, {==})\n' % (
        VARS, HS, SO, A2, MB, K0, goal, goal, NS(A2, sy(A2, 'None{}', c_kz('True{}', 'hc'))),
        tr(A4, A2, 'Some{sig}', sy(A2, A4, 'sign_a4(one, sk, m, aux, hc)'), 'hs'), VER))
    o.append('def sv1(+one: Nat, %s, %s, +hs: {%s == Some{sig} : %s}, c: Bool, +hc: {%s == c : Bool}) -> %s:\n  match c:\n    case False{}:\n      Empty.absurd(%s, %s)\n    case True{}:\n      sv2(one, sk, m, aux, sig, pk, hpk, Lg.and_right(CS.length_is(32n, aux), SS.secret_ok(one, sk), hc), %s, Nat.is_eq(%s, 0n), {==})\n' % (
        VARS, HS, A0, MB, B0, goal, goal, NS(A0, sy(A0, 'None{}', c_ok('False{}', 'hc'))),
        tr(A2, A0, 'Some{sig}', sy(A0, A2, 'sign_a2(one, sk, m, aux, hc)'), 'hs'), K0))
    o.append('# Sign(sk, m, a) == sig and PubKey(sk) == pk: Verify(pk, m, sig)\n'
             'def sign_verify(+one: Nat, %s, %s, +hs: {%s == Some{sig} : %s}) -> %s:\n  sv1(one, sk, m, aux, sig, pk, hpk, hs, %s, {==})\n' % (VARS, HS, A0, MB, goal, B0))
    kz = 'Nat.is_eq(%s, 0n)' % K0
    o.append('def sn_c(%s, %s, %s, %s, +hs: {%s == None{} : %s}, c: Bool, +hcc: {%s == c : Bool}) -> {%s == True{} : Bool}:\n  match c:\n    case True{}:\n      hcc\n    case False{}:\n      Empty.absurd({%s == True{} : Bool}, Lg.none_some(List<&2, U32>, %s, %s))\n' % (
        HD, VARS, HLA, SO, A0, MB, kz, kz, kz, SIG, tr('None{}', A0, A5, sy(A0, 'None{}', 'hs'), 'signs(%s, sk, m, aux, hla, hso, hcc)' % HA)))
    o.append('# Sign fails (for a valid key and 32 bytes of aux) only when the nonce is 0\n'
             'def sign_none(%s, %s, %s, %s, +hs: {%s == None{} : %s}) -> {%s == True{} : Bool}:\n  sn_c(%s, sk, m, aux, hla, hso, hs, %s, {==})\n' % (HD, VARS, HLA, SO, A0, MB, kz, HA, kz))
    open(os.path.join(OUT, 'group', 'schp.bend'), 'w').write('\n'.join(o))


def laws():
    K0, SIG, PKB = 'D.nonce(one, sk, m, aux)', 'D.sigv(one, sk, m, aux)', 'D.pkb(one, sk)'
    hyp = [('one', 'Nat'), ('h1', '{one == 1n : Nat}'), ('hp', 'PM.Prime(FS.prime(one))'), ('hc', HCT), ('hq', 'PM.Prime(FS.order(one))'), ('hg', HGT), ('hng', HNGT)]
    B = 'List<&2, U32>'
    so = ('hso', '{SS.secret_ok(one, sk) == True{} : Bool}')
    hla = ('hla', '{CS.length_is(32n, aux) == True{} : Bool}')
    hk0 = ('hk0', '{Nat.is_eq(%s, 0n) == False{} : Bool}' % K0)
    L = [
        ('Schnorr.tagged', 'the folded tagged hash of group/schd.bend is the specification\'s', [('tag', B), ('x', B)], '{D.tg(tag, x) == SS.tagged(tag, x) : List<&2, U32>}', 'P.tg_eq(tag, x)'),
        ('Schnorr.pubkey', 'PubKey(sk) is bytes(x(d\' G)) for a valid secret key', [('one', 'Nat'), ('sk', B), so], '{SS.pubkey(one, sk) == Some{%s} : %s}' % (PKB, MB), 'P.pubkey(one, sk, hso)'),
        ('Schnorr.sign', 'Sign(sk, m, a) succeeds when the nonce k\' is not 0 (its final self-verification never fails) and returns bytes(x(R)) || bytes((k + e d) mod n)',
         hyp + [('sk', B), ('m', B), ('aux', B), hla, so, hk0], '{SS.sign(one, sk, m, aux) == Some{%s} : %s}' % (SIG, MB), 'P.signs(%s, sk, m, aux, hla, hso, hk0)' % HA),
        ('Schnorr.verify', 'Verify(PubKey(sk), m, Sign(sk, m, a)) holds',
         hyp + [('sk', B), ('m', B), ('aux', B), so, hk0], '{SS.verify(one, %s, m, %s) == True{} : Bool}' % (PKB, SIG), 'P.verifies(%s, sk, m, aux, hso, hk0)' % HA),
        ('Schnorr.sign_verify', 'whatever Sign returns verifies under PubKey(sk) (from the self-verification alone)',
         [('one', 'Nat'), ('sk', B), ('m', B), ('aux', B), ('sig', B), ('pk', B), ('hpk', '{SS.pubkey(one, sk) == Some{pk} : %s}' % MB), ('hs', '{SS.sign(one, sk, m, aux) == Some{sig} : %s}' % MB)],
         '{SS.verify(one, pk, m, sig) == True{} : Bool}', 'P.sign_verify(one, sk, m, aux, sig, pk, hpk, hs)'),
        ('Schnorr.sign_none', 'Sign fails, for a valid key and 32 bytes of aux, only when the nonce k\' is 0',
         hyp + [('sk', B), ('m', B), ('aux', B), hla, so, ('hs', '{SS.sign(one, sk, m, aux) == None{} : %s}' % MB)], '{Nat.is_eq(%s, 0n) == True{} : Bool}' % K0, 'P.sign_none(%s, sk, m, aux, hla, hso, hs)' % HA),
    ]
    laws = """# GENERATED by tools/generators/secp256k1_group/gen_schs.py; edit the generator
import Base
import ../../../spec/crypto/secp256k1/field.bend as FS
import ../../../spec/crypto/secp256k1/curve.bend as CS
import ../../../spec/crypto/secp256k1/group.bend as GS
import ../../../spec/crypto/secp256k1/schnorr.bend as SS
import ../../math/number/nt_prime.bend as PM
import ./group/schd.bend as D

# BIP-340 Schnorr signatures on the specification
# (spec/crypto/secp256k1/schnorr.bend), through the group law: signing
# succeeds and its signature verifies, for every secret key, message and
# auxiliary randomness. group/schd.bend names the values signing computes
# (the key d with even y, the public key bytes pkb, the nonce k', the
# challenge, the signature sigv).
#
# The clauses that use the group take five facts about the curve as
# hypotheses, each proved in a root of its own (closed computations too
# heavy to import here):
#   hp:  p is prime                       (group/certa.bend)
#   hc:  (-7)^((p - 1) / 3) != 1 in GF(p) (group/certd.bend)
#   hq:  n is prime                       (group/certn.bend)
#   hg:  G is a point of the group        (group/ptv.bend)
#   hng: [n] G is the point at infinity   (group/pte.bend and its chunk roots)
# Proved by `bend proofs/crypto/secp256k1/proof_schnorr_group.bend`.
"""
    proof = """# GENERATED by tools/generators/secp256k1_group/gen_schs.py; edit the generator
import Base
import ./laws_schnorr_group.bend as Laws
import ./group/schp.bend as P

# BIP-340 through the group law (laws_schnorr_group.bend):
# `bend proofs/crypto/secp256k1/proof_schnorr_group.bend`. The lemmas are in
# group/schg.bend (the group part, generic in the moduli), group/schs.bend
# (moved to the specification's p, n, G) and group/schp.bend (the protocol).
"""
    for name, com, vs, concl, pr in L:
        laws += '\n# %s\nlaw %s:\n' % (com, name) + ''.join('  for +%s: %s\n' % v for v in vs) + '  %s\n' % concl
        proof += '\ndef Laws.%s(%s):\n  %s\n' % (name, ', '.join(v for v, _ in vs), pr)
    open(os.path.join(OUT, 'laws_schnorr_group.bend'), 'w').write(laws)
    open(os.path.join(OUT, 'proof_schnorr_group.bend'), 'w').write(proof)


if __name__ == '__main__':
    main()
    protocol()
    laws()
