#!/usr/bin/env python3
"""Generator of the clauses about the generator's order and the GLV
endomorphism of secp256k1:

  proofs/crypto/secp256k1/group/orderp.bend, glvp.bend
      the clauses as plain lemmas that keep the expensive facts as
      hypotheses (what other proofs import)
  proofs/crypto/secp256k1/laws_{order,glv,glvsplit}.bend
      the unconditional clauses
  proofs/crypto/secp256k1/proof_{order,glv,glvsplit}.bend
      the closing roots: the lemmas applied to the certificates and to the
      chunk facts of the double-and-add computations

  python3 tools/generators/secp256k1_group/gen_ngl.py
"""
import os
HERE = os.path.dirname(os.path.abspath(__file__))
D = os.path.join(HERE, '..', '..', '..', 'proofs', 'crypto', 'secp256k1')
HEAD = '# GENERATED by tools/generators/secp256k1_group/gen_ngl.py; edit the generator\n'
P, N, G, O = 'FS.prime(one)', 'FS.order(one)', 'CS.g(one)', 'CS.infinity()'
BE, LA = 'GV.beta(one)', 'GV.lambda(one)'
PMo, NQ = 'GF.pm(one)', 'X.bvalo(one, CB.n1l())'
FPA = 'GF.pm(one), GF.hp_m(one, h1, hp), CB.p_mod3(one, h1), GF.hc_m(one, h1, hc), GF.h21_m(one, h1)'


def T(b):
    return '{%s == True{} : Bool}' % b


def V(p, a):
    return T('GS.valid(%s, %s)' % (p, a))


def E(p, a, b):
    return T('GS.equiv(%s, %s, %s)' % (p, a, b))


def S(p, k, a):
    return 'GS.smul(%s, %s, %s)' % (p, k, a)


def A(p, a, b):
    return 'CS.padd(%s, %s, %s)' % (p, a, b)


def PH(p, a, be=BE):
    return 'GV.phi(%s, %s, %s)' % (p, be, a)


HYP = {
    'hp': 'PM.Prime(FS.prime(one))',
    'hc': '{Nat.is_eq(FS.mpow(FS.prime(one), Nat.sub(FS.prime(one), 7n), Nat.div(Nat.sub(FS.prime(one), 1n), 3n)), 1n) == False{} : Bool}',
    'hq': 'PM.Prime(FS.order(one))',
    'hg': V(P, G),
    'hn': E(P, S(P, N, G), O),
    'hf': E(P, PH(P, G), S(P, LA, G)),
}


def to_m(ty, h):
    """a fact about FS.prime(one) moved to the modulus 1 + pm"""
    return 'Lg.subst(Nat, q => %s, FS.prime(one), 1n+GF.pm(one), CB.p_suc(one, h1), %s)' % (ty('q'), h)


def from_m(ty, pr):
    return 'Lg.subst(Nat, q => %s, 1n+GF.pm(one), FS.prime(one), Equal.sym(Nat, FS.prime(one), 1n+GF.pm(one), CB.p_suc(one, h1)), %s)' % (ty('q'), pr)


def n_to(ty, h):
    """a fact about FS.order(one) moved to 1 + nq"""
    return 'Lg.subst(Nat, n => %s, FS.order(one), 1n+%s, CB.n_suc(one, h1), %s)' % (ty('n'), NQ, h)


def n_from(ty, pr):
    return 'Lg.subst(Nat, n => %s, 1n+%s, FS.order(one), Equal.sym(Nat, FS.order(one), 1n+%s, CB.n_suc(one, h1)), %s)' % (ty('n'), NQ, NQ, pr)


HG_M = to_m(lambda q: V(q, G), 'hg')
HN_M = to_m(lambda q: E(q, S(q, '1n+' + NQ, G), O), n_to(lambda n: E(P, S(P, n, G), O), 'hn'))
HQ_M = n_to(lambda n: 'PM.Prime(%s)' % n, 'hq')
HF_M = to_m(lambda q: E(q, PH(q, G), S(q, LA, G)), 'hf')
HB_M = 'Lg.subst(Nat, b => {FS.mmul(1n+GF.pm(one), FS.mmul(1n+GF.pm(one), b, b), b) == 1n : Nat}, X.bvalo(one, GC.betal()), GV.beta(one), GC.beta_is(one, h1), GC.beta_cube_m(one, h1))'

# (family, law name, comment, hypotheses used, [(var, type)], conclusion, proof of the lemma)
CL = []


def clause(fam, name, com, hyps, vars_, concl, proof):
    CL.append((fam, name, com, hyps, vars_, concl, proof))


# ---- the order of G
clause('order', 'Generator.valid', 'G is a point of the group', [], [], V(P, G), 'PV.g_valid(one, h1)')
clause('order', 'Generator.order', '[n] G is O', ['hn'], [], E(P, S(P, N, G), O), 'hn')
kmod = lambda q, n: E(q, S(q, 'k', G), S(q, 'Nat.mod(k, %s)' % n, G))
clause('order', 'Generator.mod', '[k] G depends only on k mod n', ['hp', 'hc', 'hg', 'hn'], [('k', 'Nat')], kmod(P, N),
       'PW.k_mod(one, h1, hp, hc, k, CS.g(one), hg, hn)')
clause('order', 'Generator.add_mod', '[j] G + [k] G is [(j + k) mod n] G', ['hp', 'hc', 'hg', 'hn'], [('j', 'Nat'), ('k', 'Nat')],
       E(P, A(P, S(P, 'j', G), S(P, 'k', G)), S(P, 'Nat.mod(Nat.add(j, k), %s)' % N, G)), 'PW.add_mod(one, h1, hp, hc, j, k, CS.g(one), hg, hn)')
clause('order', 'Generator.mul_mod', '[j] ([k] G) is [(j k) mod n] G', ['hp', 'hc', 'hg', 'hn'], [('j', 'Nat'), ('k', 'Nat')],
       E(P, S(P, 'j', S(P, 'k', G)), S(P, 'Nat.mod(Nat.mul(j, k), %s)' % N, G)), 'PW.mul_mod(one, h1, hp, hc, j, k, CS.g(one), hg, hn)')
ni = lambda q: '{GS.equiv(%s, %s, %s) == False{} : Bool}' % (q, S(q, 'k', G), O)
clause('order', 'Generator.not_infinity', 'for 0 < k < n, [k] G is not O: the order of G is exactly n (n is prime)', ['hp', 'hc', 'hq', 'hg', 'hn'],
       [('k', 'Nat'), ('h0', T('Nat.is_lt(0n, k)')), ('hl', T('Nat.is_lt(k, %s)' % N))], ni(P),
       from_m(ni, 'PO.not_inf(%s, %s, %s, CS.g(one), %s, h1, %s, k, PO.nz_k(%s, k, h0, %s))'
              % (FPA, NQ, HQ_M, HG_M, HN_M, NQ, n_to(lambda n: T('Nat.is_lt(k, %s)' % n), 'hl'))))

# ---- GLV
bc = lambda q, b: '{FS.mmul(%s, FS.mmul(%s, %s, %s), %s) == 1n : Nat}' % (q, q, b, b, b)
clause('glv', 'Glv.beta_cube', 'beta^3 == 1 in GF(p)', [], [], bc(P, BE),
       'Lg.subst(Nat, b => %s, X.bvalo(one, GC.betal()), GV.beta(one), GC.beta_is(one, h1), GC.beta_cube(one, h1))' % bc(P, 'b'))
clause('glv', 'Glv.beta_nontrivial', 'beta != 1', [], [], '{Nat.is_eq(%s, 1n) == False{} : Bool}' % BE,
       'Lg.subst(Nat, b => {Nat.is_eq(b, 1n) == False{} : Bool}, X.bvalo(one, GC.betal()), GV.beta(one), GC.beta_is(one, h1), GC.beta_ne1(one, h1))')
lq = lambda l, n: '{Nat.mod(Nat.add(Nat.add(Nat.mul(%s, %s), %s), 1n), %s) == 0n : Nat}' % (l, l, l, n)
clause('glv', 'Glv.lambda', 'lambda^2 + lambda + 1 == 0 modulo n', [], [], lq(LA, N),
       'Lg.subst(Nat, l => %s, X.bvalo(one, GC.laml()), GV.lambda(one), GC.lam_is(one, h1), %s)'
       % (lq('l', N), n_from(lambda n: lq('X.bvalo(one, GC.laml())', n),
                             'Lg.subst(Nat, v => {Nat.mod(v, 1n+%s) == 0n : Nat}, Nat.mul(X.bvalo(one, GC.lamkl()), 1n+%s), Nat.add(Nat.add(Nat.mul(X.bvalo(one, GC.laml()), X.bvalo(one, GC.laml())), X.bvalo(one, GC.laml())), 1n), Equal.sym(Nat, Nat.add(Nat.add(Nat.mul(X.bvalo(one, GC.laml()), X.bvalo(one, GC.laml())), X.bvalo(one, GC.laml())), 1n), Nat.mul(X.bvalo(one, GC.lamkl()), 1n+%s), %s), PM.mod_mul0(%s, X.bvalo(one, GC.lamkl())))'
                             % (NQ, NQ, NQ, n_to(lambda n: '{Nat.add(Nat.add(Nat.mul(X.bvalo(one, GC.laml()), X.bvalo(one, GC.laml())), X.bvalo(one, GC.laml())), 1n) == Nat.mul(X.bvalo(one, GC.lamkl()), %s) : Nat}' % n, 'GC.lam_eq(one, h1)'), NQ))))
pv = lambda q: V(q, PH(q, 'a'))
clause('glv', 'Glv.phi_valid', 'phi(A) is a point of the group', [], [('a', 'CS.SPoint'), ('va', V(P, 'a'))], pv(P),
       from_m(pv, 'GLV.phi_valid(GF.pm(one), GV.beta(one), %s, a, %s)' % (HB_M, to_m(lambda q: V(q, 'a'), 'va'))))
pa = lambda q: '{%s == %s : CS.SPoint}' % (A(q, PH(q, 'a'), PH(q, 'b')), PH(q, A(q, 'a', 'b')))
clause('glv', 'Glv.phi_add', 'phi(A) + phi(B) is phi(A + B), as triples', [], [('a', 'CS.SPoint'), ('b', 'CS.SPoint')], pa(P),
       from_m(pa, 'GLV.phi_add(GF.pm(one), GV.beta(one), %s, a, b)' % HB_M))
clause('glv', 'Glv.generator', 'phi(G) is [lambda] G', ['hf'], [], HYP['hf'], 'hf')
mu = lambda q: E(q, PH(q, S(q, 'k', G)), S(q, LA, S(q, 'k', G)))
clause('glv', 'Glv.multiples', 'phi([k] G) is [lambda] ([k] G), for every k', ['hp', 'hc', 'hg', 'hf'], [('k', 'Nat')], mu(P),
       from_m(mu, 'GLV.glv_main(%s, GV.beta(one), %s, GV.lambda(one), CS.g(one), %s, %s, k)' % (FPA, HB_M, HG_M, HF_M)))
KK = 'Nat.add(k1, Nat.mul(k2, %s))' % LA
sp = lambda q: E(q, S(q, 'k', G), A(q, S(q, 'k1', G), S(q, 'k2', PH(q, G))))
clause('glvsplit', 'Glv.split', 'for k == k1 + k2 lambda (mod n): [k] G is [k1] G + [k2] phi(G)', ['hp', 'hc', 'hg', 'hn', 'hf'],
       [('k', 'Nat'), ('k1', 'Nat'), ('k2', 'Nat'), ('hk', '{Nat.mod(k, %s) == Nat.mod(%s, %s) : Nat}' % (N, KK, N))], sp(P),
       from_m(sp, 'GLS.split_main(%s, GV.beta(one), %s, GV.lambda(one), CS.g(one), %s, %s, %s, %s, k, k1, k2, %s)'
              % (FPA, HB_M, HG_M, HF_M, NQ, HN_M, n_to(lambda n: '{Nat.mod(k, %s) == Nat.mod(%s, %s) : Nat}' % (n, KK, n), 'hk'))))

IMP = '''import Base
import ../../../lib/logic.bend as Lg
import ../../../../spec/crypto/secp256k1/field.bend as FS
import ../../../../spec/crypto/secp256k1/curve.bend as CS
import ../../../../spec/crypto/secp256k1/group.bend as GS
import ../../../../spec/crypto/secp256k1/glv.bend as GV
import ../../../math/number/nt_prime.bend as PM
import ./bnx.bend as X
import ./certb.bend as CB
import ./gfp.bend as GF
'''
LIMP = '''import Base
import ../../../spec/crypto/secp256k1/field.bend as FS
import ../../../spec/crypto/secp256k1/curve.bend as CS
import ../../../spec/crypto/secp256k1/group.bend as GS
import ../../../spec/crypto/secp256k1/glv.bend as GV
'''
NOTP = '''# NOT proved: phi(A) is [lambda] A for an arbitrary point A of the group.
# That needs every point of the curve to be a multiple of G, i.e.
# #E(F_p) = n (point counting), which is not proved here.
'''
FAM = {
    'order': dict(
        lem='orderp', ns='OP', limp='import ./ptv.bend as PV\nimport ./pto.bend as PO\nimport ./ptw.bend as PW\n',
        lhead='''# The order of the generator G of secp256k1, as plain lemmas that keep the
# expensive facts as hypotheses: hp (p is prime) and hc ((-7)^((p-1)/3) != 1)
# as in group/glawp.bend, hq (n is prime), hg (G is a point of the group)
# and hn ([n] G is O). proof_order.bend applies the certificates.
''',
        head='''# The generator G of secp256k1 (spec/crypto/secp256k1/curve.bend, g) has
# order exactly n = FS.order(one), in the group of
# spec/crypto/secp256k1/group.bend (valid, equiv, smul): G is a point of
# the group, [n] G is O, [k] G depends only on k modulo n, and [k] G is not
# O for 0 < k < n. Every clause is for every input; `one` is the number 1
# kept symbolic (h1). Proved by `bend proofs/crypto/secp256k1/proof_order.bend`
# from the certificates that p and n are prime and that -7 is not a cube
# modulo p, and a double-and-add computation over the bits of n in eight
# closed chunks (group/ptn_1.bend .. ptn_8.bend).
''',
        phead='''# The order of G (laws_order.bend):
# `bend proofs/crypto/secp256k1/proof_order.bend`. Each clause is its lemma
# of group/orderp.bend applied to the certificates (group/certpc.bend: p is
# prime and -7 is not a cube; group/certn.bend: n is prime), to G's
# validity (group/ptv.bend) and to [n] G equiv O (group/pte.bend from the
# eight chunk facts group/ptn_<i>.bend).
'''),
    'glv': dict(
        lem='glvp', ns='GP', limp='import ./glv.bend as GLV\nimport ./glvc.bend as GC\n',
        lhead='''# The GLV endomorphism of secp256k1 on the specification's constants
# (spec/crypto/secp256k1/glv.bend), as plain lemmas that keep the expensive
# facts as hypotheses: hp, hc as in group/glawp.bend, hg (G is a point of
# the group) and hf (phi(G) is [lambda] G). proof_glv.bend applies the
# certificates.
#
''' + NOTP,
        head='''# The GLV endomorphism of secp256k1 (spec/crypto/secp256k1/glv.bend: beta,
# lambda, phi(X : Y : Z) = (beta X : Y : Z)): beta is a nontrivial cube
# root of 1 in GF(p), lambda^2 + lambda + 1 == 0 modulo n, phi maps the
# group to itself and commutes with the complete addition, phi(G) is
# [lambda] G, and so phi([k] G) is [lambda] ([k] G) for every k. Every
# clause is for every input; `one` is the number 1 kept symbolic (h1).
# Proved by `bend proofs/crypto/secp256k1/proof_glv.bend`.
#
''' + NOTP,
        phead='''# The GLV endomorphism (laws_glv.bend):
# `bend proofs/crypto/secp256k1/proof_glv.bend`. Each clause is its lemma
# of group/glvp.bend applied to the certificates (group/certpc.bend), to
# G's validity (group/ptv.bend) and to phi(G) equiv [lambda] G
# (group/glvf.bend from the eight chunk facts group/ptg_<i>.bend).
'''),
    'glvsplit': dict(
        lem='glvsplitp', ns='GQ', limp='import ./glvc.bend as GC\nimport ./glvs.bend as GLS\n',
        lhead='''# The GLV decomposition on the multiples of G, as a plain lemma that keeps
# the expensive facts as hypotheses: hp, hc, hg, hn ([n] G is O) and hf
# (phi(G) is [lambda] G). proof_glvsplit.bend applies the certificates.
''',
        head='''# The GLV decomposition of a scalar multiplication on the generator of
# secp256k1: for k == k1 + k2 lambda (mod n), [k] G is [k1] G + [k2] phi(G)
# (what a GLV implementation computes, with k1 and k2 of half length).
# Proved by `bend proofs/crypto/secp256k1/proof_glvsplit.bend`, which needs
# both double-and-add computations (over n and over lambda).
'''),
}
FAM['glvsplit']['phead'] = '''# The GLV decomposition (laws_glvsplit.bend):
# `bend proofs/crypto/secp256k1/proof_glvsplit.bend`: the lemma of
# group/glvsplitp.bend applied to the certificates, to [n] G equiv O
# (group/pte.bend, chunks group/ptn_<i>.bend) and to phi(G) equiv [lambda] G
# (group/glvf.bend, chunks group/ptg_<i>.bend).
'''
NGC = 'PE.ng(one, h1, PC.prime_p(one, h1), PC.cube_spec(one, h1), %s)' % ', '.join('N%d.fact(one, h1)' % i for i in range(1, 9))
HF_T = lambda q, b, l: E(q, 'GV.phi(%s, %s, %s)' % (q, b, G), S(q, l, G))
PHC = ('Lg.subst(Nat, b => %s, X.bvalo(one, GC.betal()), GV.beta(one), GC.beta_is(one, h1), Lg.subst(Nat, l => %s, X.bvalo(one, GC.laml()), GV.lambda(one), GC.lam_is(one, h1), GLF.phi_g(one, h1, PC.prime_p(one, h1), PC.cube_spec(one, h1), %s)))'
       % (HF_T(P, 'b', LA), HF_T(P, 'X.bvalo(one, GC.betal())', 'l'), ', '.join('L%d.fact(one, h1)' % i for i in range(1, 9))))
CLOSE = {'hp': 'PC.prime_p(one, h1)', 'hc': 'PC.cube_spec(one, h1)', 'hq': 'CN.prime_n(one, h1)', 'hg': 'PV.g_valid(one, h1)', 'hn': 'ng(one, h1)', 'hf': 'phig(one, h1)'}
CIMP = {'hp': ['import ./group/certpc.bend as PC'], 'hc': ['import ./group/certpc.bend as PC'], 'hq': ['import ./group/certn.bend as CN'], 'hg': ['import ./group/ptv.bend as PV'],
        'hn': ['import ./group/certpc.bend as PC', 'import ./group/pte.bend as PE'] + ['import ./group/ptn_%d.bend as N%d' % (i, i) for i in range(1, 9)],
        'hf': ['import ./group/certpc.bend as PC', 'import ./group/bnx.bend as X', 'import ./group/glvc.bend as GC', 'import ./group/glvf.bend as GLF', '../../lib/logic.bend as Lg'] + ['import ./group/ptg_%d.bend as L%d' % (i, i) for i in range(1, 9)]}
HELP = {'hn': '# [n] G is O\ndef ng(+one: Nat, +h1: {one == 1n : Nat}) -> %s:\n  %s\n' % (HYP['hn'], NGC),
        'hf': '# phi(G) is [lambda] G\ndef phig(+one: Nat, +h1: {one == 1n : Nat}) -> %s:\n  %s\n' % (HYP['hf'], PHC)}


def main():
    for fam, cfg in FAM.items():
        cl = [c for c in CL if c[0] == fam]
        lem = IMP + cfg['limp'] + '\n' + cfg['lhead']
        laws = LIMP + '\n' + cfg['head']
        used = []
        body = ''
        for _, name, com, hyps, vars_, concl, proof in cl:
            fn = name.lower().replace('.', '_')
            sig = ''.join(', +%s: %s' % (h, HYP[h]) for h in hyps) + ''.join(', +%s: %s' % v for v in vars_)
            lem += '\n# %s\ndef %s(+one: Nat, +h1: {one == 1n : Nat}%s) -> %s:\n  %s\n' % (com, fn, sig, concl, proof)
            laws += '\n# %s\nlaw %s:\n  for +one: Nat\n  for +h1: {one == 1n : Nat}\n%s  %s\n' % (com, name, ''.join('  for +%s: %s\n' % v for v in vars_), concl)
            args = ', '.join(['one', 'h1'] + [v for v, _ in vars_])
            call = ', '.join(['one', 'h1'] + [CLOSE[h] for h in hyps] + [v for v, _ in vars_])
            body += '\ndef Laws.%s(%s):\n  %s.%s(%s)\n' % (name, args, cfg['ns'], fn, call)
            used += [h for h in hyps if h not in used]
        imps = ['import ./laws_%s.bend as Laws' % fam, 'import ./group/%s.bend as %s' % (cfg['lem'], cfg['ns'])]
        need_spec = any(h in used for h in ('hn', 'hf'))
        for h in used:
            for i in CIMP[h]:
                i = i if i.startswith('import ') else 'import ' + i + ''
                if i not in imps:
                    imps.append(i)
        spec = ''
        if need_spec:
            spec = ('import ../../../spec/crypto/secp256k1/field.bend as FS\nimport ../../../spec/crypto/secp256k1/curve.bend as CS\n'
                    'import ../../../spec/crypto/secp256k1/group.bend as GS\nimport ../../../spec/crypto/secp256k1/glv.bend as GV\n')
        imps = [i.replace('import ../../lib/logic.bend as Lg', 'import ../../lib/logic.bend as Lg') for i in imps]
        proof = HEAD + 'import Base\n' + spec + '\n'.join(imps) + '\n\n' + cfg['phead'] + ''.join('\n' + HELP[h] for h in used if h in HELP) + body
        open(os.path.join(D, 'group', cfg['lem'] + '.bend'), 'w').write(HEAD + lem)
        open(os.path.join(D, 'laws_%s.bend' % fam), 'w').write(HEAD + laws)
        open(os.path.join(D, 'proof_%s.bend' % fam), 'w').write(proof)


if __name__ == '__main__':
    main()
