#!/usr/bin/env python3
"""Generator of the identity instances (proofs/crypto/secp256k1/group/id_*.bend).

Each instance is an equation modulo m = 1 + mp between two values of the
specification (registers of CS.run on the add/dbl programs, FS.mmul/msub of
them, the coordinates). The generator only writes down, for each value, its
polynomial (group/poly.bend) and the proof that the value is the
polynomial's (Z.Rel, from group/sym.bend and group/ident.bend); the identity
itself is I.ident with a {==} check that the difference of the two
polynomials, reduced by the curve equations, computes to []. Nothing here is
trusted: a wrong polynomial or a false identity fails the check.

  python3 tools/generators/secp256k1_group/gen_ids.py        (writes all id_*.bend)
"""
import os, sys
HERE = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.join(HERE, '..', '..', '..', 'proofs', 'crypto', 'secp256k1', 'group')

HEAD = '''# GENERATED by tools/generators/secp256k1_group/gen_ids.py; edit the generator
import Base
import ../../../../spec/crypto/secp256k1/field.bend as FS
import ../../../../spec/crypto/secp256k1/curve.bend as CS
import ./poly.bend as P
import ./pev.bend as E
import ./zm.bend as Z
import ./sym.bend as S
import ./ident.bend as I
'''

M = '1n+mp'


class V:
    def __init__(self, spec, poly, rel):
        self.spec, self.poly, self.rel = spec, poly, rel


class Ctx:
    """names: the variables (Nat parameters); extra: literal values appended to env"""

    def __init__(self, names, extra=()):
        self.names = list(names)
        self.vals = list(names) + list(extra)
        self.n = len(self.vals)
        self.env = '[' + ', '.join(self.vals) + ']'
        self.params = ', '.join('+%s: Nat' % v for v in ['mp'] + self.names)
        self.args = ', '.join(['mp'] + self.names)
        self.defs = []

    def var(self, i):
        return V(self.vals[i], 'P.pvar(%dn, %dn)' % (self.n, i), 'I.var_rel(mp, %dn, %dn, %s, {==})' % (self.n, i, self.env))

    def zero(self):
        return V('0n', 'Nil{}', '{==}')

    def const(self, k):
        return V('%dn' % k, 'P.pconst(%dn, %dn)' % (self.n, k), '{==}')

    def cmul(self, k, i, val):
        """the literal val = k * (value of variable i), as k x_i"""
        return V('%dn' % val, '[P.Tm{P.zc(%dn), P.unit(%dn, %dn, 1n)}]' % (k, self.n, i), '{==}')

    def op(self, f, g, lem, a, b):
        return V('FS.%s(%s, %s, %s)' % (f, M, a.spec, b.spec), 'P.%s(%s, %s)' % (g, a.poly, b.poly),
                 'I.%s(mp, %s, %s, %s, %s, %s, %s, %s)' % (lem, a.spec, b.spec, a.poly, b.poly, self.env, a.rel, b.rel))

    def mul(self, a, b):
        return self.op('mmul', 'pmul', 'rel_pmul', a, b)

    def add(self, a, b):
        return self.op('madd', 'padd', 'rel_padd', a, b)

    def sub(self, a, b):
        return self.op('msub', 'psub', 'rel_psub', a, b)

    def run(self, prog, ins, k):
        specs = '[' + ', '.join(v.spec for v in ins) + ']'
        polys = '[' + ', '.join(v.poly for v in ins) + ']'
        ag = 'Unit{}'
        for v in reversed(ins):
            ag = 'S.Both{%s, %s}' % (v.rel, ag)
        return V('CS.nth(%dn, CS.run(%s, %s, %s))' % (k, M, prog, specs),
                 'S.snth(%dn, S.srun(%s, %s))' % (k, prog, polys),
                 'S.reg_v(mp, %s, %s, %s, %s, %s, %dn)' % (self.env, prog, polys, specs, ag, k))

    def named(self, name, v, hyps=()):
        """a def for the polynomial and a lemma for its relation (checked once)"""
        self.defs.append('def %s_p() -> List<&2, P.Tm>:\n  %s\n' % (name, v.poly))
        self.defs.append('def %s_r(%s) -> Z.Rel(mp, %s, E.eP(%s_p(), %s), E.eN(%s_p(), %s)):\n  %s\n'
                         % (name, self.params, v.spec, name, self.env, name, self.env, v.rel))
        return V(v.spec, '%s_p()' % name, '%s_r(%s)' % (name, self.args))

    def curve(self, ix, iy, iz, ib):
        """the value Y^2 Z - b Z^3 for the point at (ix, iy, iz): what X^3 is replaced by"""
        y, z, b = self.var(iy), self.var(iz), self.var(ib)
        return self.sub(self.mul(self.mul(y, y), z), self.mul(b, self.mul(self.mul(z, z), z)))

    def ident(self, name, a, b, curves=(), comment=''):
        """curves: list of (ix, F, hyp name): hypothesis x^3 == F.spec"""
        hyp_params = ''.join(', +%s: {FS.mmul(%s, FS.mmul(%s, %s, %s), %s) == %s : Nat}'
                             % (h, M, M, self.vals[ix], self.vals[ix], self.vals[ix], F.spec) for ix, F, h in curves)
        d = 'P.psub(%s, %s)' % (a.poly, b.poly)
        polys = [d]
        for ix, F, h in curves:
            polys.append('P.red(%dn, %dn, %s, %s)' % (self.n, ix, F.poly, polys[-1]))
        hz = 'I.sm_nil(mp, %s, %s, {==})' % (polys[-1], self.env)
        for j in range(len(curves) - 1, -1, -1):
            ix, F, h = curves[j]
            cur = 'I.cur_rel(mp, %s, %s, E.eP(%s, %s), E.eN(%s, %s), %s, %s)' % (self.vals[ix], F.spec, F.poly, self.env, F.poly, self.env, h, F.rel)
            hz = 'I.sm_red(mp, %dn, %dn, %s, %s, %s, {==}, %s, %s)' % (self.n, ix, F.poly, polys[j], self.env, cur, hz)
        self.defs.append('%sdef %s(%s%s) -> {Nat.mod(%s, %s) == Nat.mod(%s, %s) : Nat}:\n  I.ident(mp, %s, %s, %s, %s, %s, %s, %s, %s)\n'
                         % (('# ' + comment + '\n') if comment else '', name, self.params, hyp_params, a.spec, M, b.spec, M,
                            a.spec, b.spec, a.poly, b.poly, self.env, a.rel, b.rel, hz))

    def write(self, fname, header):
        with open(os.path.join(OUT, fname), 'w') as f:
            f.write(HEAD + '\n' + header + '\n' + '\n'.join(self.defs))


ADD, DBL = 'CS.add_prog()', 'CS.dbl_prog()'


def padd(c, p, q, b3):
    return [c.run(ADD, list(p) + list(q) + [b3], k) for k in (33, 36, 39)]


def pdbl(c, p, b3):
    return [c.run(DBL, list(p) + [b3], k) for k in (21, 18, 13)]


def point(c, i):
    return [c.var(3 * i), c.var(3 * i + 1), c.var(3 * i + 2)]


def gen_comm():
    c = Ctx(['x1', 'y1', 'z1', 'x2', 'y2', 'z2', 'w'])
    p, q, w = point(c, 0), point(c, 1), c.var(6)
    l, r = padd(c, p, q, w), padd(c, q, p, w)
    for k, nm in enumerate('xyz'):
        c.ident('comm_' + nm, l[k], r[k], comment='coordinate %s of P + Q and of Q + P (any b3 = w)' % nm.upper())
    c.write('id_comm.bend', '# The complete addition is commutative, coordinate by coordinate.\n')


def curve_val(c, v, b7):
    """X^3 and Y^2 Z - b Z^3 of the point v"""
    x, y, z = v
    return c.mul(c.mul(x, x), x), c.sub(c.mul(c.mul(y, y), z), c.mul(b7, c.mul(c.mul(z, z), z)))


def gen_curve():
    c = Ctx(['x1', 'y1', 'z1', 'x2', 'y2', 'z2'], ['7n'])
    p, q, b7, b3 = point(c, 0), point(c, 1), c.var(6), c.cmul(3, 6, 21)
    cv = [(0, c.curve(0, 1, 2, 6), 'h1'), (3, c.curve(3, 4, 5, 6), 'h2')]
    s = padd(c, p, q, b3)
    a, b = curve_val(c, s, b7)
    c.ident('add_curve', a, b, cv, 'P and Q on the curve X^3 = Y^2 Z - 7 Z^3: so is P + Q')
    c.write('id_curve.bend', '# The sum of two points of the curve is on the curve.\n')


def gen_assoc(i, j):
    nm = 'xyz'[i] + 'xyz'[j]
    c = Ctx(['x1', 'y1', 'z1', 'x2', 'y2', 'z2', 'x3', 'y3', 'z3'], ['7n'])
    p, q, r, b3 = point(c, 0), point(c, 1), point(c, 2), c.cmul(3, 9, 21)
    cv = [(0, c.curve(0, 1, 2, 9), 'h1'), (3, c.curve(3, 4, 5, 9), 'h2'), (6, c.curve(6, 7, 8, 9), 'h3')]
    l = padd(c, padd(c, p, q, b3), r, b3)
    rr = padd(c, p, padd(c, q, r, b3), b3)
    li, lj = c.named('l' + 'xyz'[i], l[i]), c.named('l' + 'xyz'[j], l[j])
    ri, rj = c.named('r' + 'xyz'[i], rr[i]), c.named('r' + 'xyz'[j], rr[j])
    c.ident('assoc_' + nm, c.mul(li, rj), c.mul(ri, lj), cv,
            'L = (P + Q) + R, Rr = P + (Q + R): L.%s Rr.%s == Rr.%s L.%s for points of the curve' % (nm[0], nm[1], nm[0], nm[1]))
    c.write('id_assoc_%s.bend' % nm, '# Associativity of the complete addition, up to projective scaling:\n# one of the three cross products.\n')


if __name__ == '__main__':
    gen_comm()
    gen_curve()
    for i, j in ((0, 1), (0, 2), (1, 2)):
        gen_assoc(i, j)
