#!/usr/bin/env python3
"""Writes proofs/crypto/secp256k1/group/ecdp.bend: the lemmas of ecdw.bend (stated for
moduli 1 + mp, 1 + nm and a generator g with hypotheses) moved to the
specification's FS.prime(one), FS.order(one) and CS.g(one), with these facts
as hypotheses: hp (p prime), hc (the cube fact), hq (n prime), hg (G valid),
hng ([n] G equiv O). Each lemma's statement is read from ecdw.bend; the
moduli appear in it only as `1n+mp` and `1n+nm`, so the move is two
Lg.subst along FS.prime(one) == 1 + pm and FS.order(one) == 1 + nm.

  python3 tools/generators/secp256k1_group/gen_ecdp.py     (after gen_ecd.py)
"""
import os, re
from gen_ecd import split_args
HERE = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.join(HERE, '..', '..', '..', 'proofs', 'crypto', 'secp256k1', 'group')
P1, N1, G1 = 'FS.prime(one)', 'FS.order(one)', 'CS.g(one)'
PMO, NMO = '1n+GF.pm(one)', '1n+nmo(one)'
CUBE = '{Nat.is_eq(FS.mpow(FS.prime(one), Nat.sub(FS.prime(one), 7n), Nat.div(Nat.sub(FS.prime(one), 1n), 3n)), 1n) == False{} : Bool}'
HD = '+one: Nat, +h1: {one == 1n : Nat}, +hp: PM.Prime(FS.prime(one)), +hc: %s, +hq: PM.Prime(FS.order(one)), +hg: {GS.valid(FS.prime(one), CS.g(one)) == True{} : Bool}, +hng: {GS.equiv(FS.prime(one), GS.smul(FS.prime(one), FS.order(one), CS.g(one)), CS.infinity()) == True{} : Bool}' % CUBE
CTX = {
    'one': 'one', 'h1': 'h1',
    'mp': 'GF.pm(one)', 'hp': 'GF.hp_m(one, h1, hp)', 'h3': 'CB.p_mod3(one, h1)', 'hnc': 'GF.hc_m(one, h1, hc)', 'h21': 'GF.h21_m(one, h1)',
    'nm': 'nmo(one)', 'hq': 'hq_m(one, h1, hq)', 'g': 'CS.g(one)', 'vg': 'hg_m(one, h1, hg)', 'hng': 'hng_m(one, h1, hng)', 'hgo': 'hgo_m(one, h1)',
    'hn256': 'hn256_m(one, h1)', 's4': 'X.bvalo(one, EB.s4l())', 'he': 'ENG.he_m(one, h1)', 'hodd': 'ENG.hodd_m(one, h1)', 'h256': 'ENG.h256_m(one, h1)',
}
HEAD = '''# GENERATED by tools/generators/secp256k1_group/gen_ecdp.py; edit the generator
import Base
import ../../../lib/lemmas/proofs/nat_algebra.bend as NA
import ../../../lib/logic.bend as Lg
import ../../../lib/nat.bend as N
import ../../../math/natural/arith.bend as NR
import ../../../../spec/lib/common.bend as C
import ../../../../spec/crypto/secp256k1/field.bend as FS
import ../../../../spec/crypto/secp256k1/curve.bend as CS
import ../../../../spec/crypto/secp256k1/group.bend as GS
import ../../../../spec/crypto/secp256k1/ecdsa.bend as ES
import ../../../math/number/nt_prime.bend as PM
import ./bn.bend as B
import ./bnx.bend as X
import ./certb.bend as CB
import ./gfp.bend as GF
import ./encb.bend as EB
import ./encg.bend as ENG
import ./sqrt.bend as SQ
import ./affx.bend as AX
import ./ecdg.bend as EG
import ./ecdv.bend as EV
import ./ecdw.bend as EW

# The ECDSA lemmas of ecdw.bend on the specification's p = FS.prime(one),
# n = FS.order(one) and G = CS.g(one), with the facts about them as
# hypotheses (each proved in its own root): hp (p is prime), hc (-7 is not a
# cube: (-7)^((p-1)/3) != 1), hq (n is prime), hg (G is a point of the
# group), hng ([n] G equiv O).

# n - 1, never expanded
def nmo(+one: Nat) -> Nat:
  X.bvalo(one, CB.n1l())

def hq_m(+one: Nat, +h1: {one == 1n : Nat}, +hq: PM.Prime(FS.order(one))) -> PM.Prime(1n+nmo(one)):
  Lg.subst(Nat, n => PM.Prime(n), FS.order(one), 1n+nmo(one), CB.n_suc(one, h1), hq)

def hg_m(+one: Nat, +h1: {one == 1n : Nat}, +hg: {GS.valid(FS.prime(one), CS.g(one)) == True{} : Bool}) -> {GS.valid(1n+GF.pm(one), CS.g(one)) == True{} : Bool}:
  Lg.subst(Nat, p => {GS.valid(p, CS.g(one)) == True{} : Bool}, FS.prime(one), 1n+GF.pm(one), CB.p_suc(one, h1), hg)

def hng_m(+one: Nat, +h1: {one == 1n : Nat}, +hng: {GS.equiv(FS.prime(one), GS.smul(FS.prime(one), FS.order(one), CS.g(one)), CS.infinity()) == True{} : Bool}) -> {GS.equiv(1n+GF.pm(one), GS.smul(1n+GF.pm(one), 1n+nmo(one), CS.g(one)), CS.infinity()) == True{} : Bool}:
  Lg.subst(Nat, n => {GS.equiv(1n+GF.pm(one), GS.smul(1n+GF.pm(one), n, CS.g(one)), CS.infinity()) == True{} : Bool}, FS.order(one), 1n+nmo(one), CB.n_suc(one, h1), Lg.subst(Nat, p => {GS.equiv(p, GS.smul(p, FS.order(one), CS.g(one)), CS.infinity()) == True{} : Bool}, FS.prime(one), 1n+GF.pm(one), CB.p_suc(one, h1), hng))

# n <= 2^256
def hn256_m(+one: Nat, +h1: {one == 1n : Nat}) -> {Nat.is_le(1n+nmo(one), C.shift(256n, one)) == True{} : Bool}:
  Lg.subst(Nat, n => {Nat.is_le(n, C.shift(256n, one)) == True{} : Bool}, FS.order(one), 1n+nmo(one), CB.n_suc(one, h1), SQ.sub_le(C.shift(256n, one), FS.cn(one)))

def px(a: CS.SPoint) -> Nat:
  match a:
    case CS.SPoint{x, y, z}:
      x

def py(a: CS.SPoint) -> Nat:
  match a:
    case CS.SPoint{x, y, z}:
      y

def gz1(+mp: Nat, +h21: {Nat.is_lt(21n, 1n+mp) == True{} : Bool}, +x: Nat, +y: Nat, c: Bool, +hc: {GS.equiv(1n+mp, CS.SPoint{x, y, 1n}, CS.infinity()) == c : Bool}) -> {GS.equiv(1n+mp, CS.SPoint{x, y, 1n}, CS.infinity()) == False{} : Bool}:
  match c:
    case False{}:
      hc
    case True{}:
      Empty.absurd({GS.equiv(1n+mp, CS.SPoint{x, y, 1n}, CS.infinity()) == False{} : Bool}, N.succ_zero(0n, Equal.trans(Nat, 1n, Nat.mod(1n, 1n+mp), 0n, Equal.sym(Nat, Nat.mod(1n, 1n+mp), 1n, NR.mod_of(0n, mp, 1n, N.lt_trans(1n, 21n, 1n+mp, {==}, h21))), AX.eqv_z0(mp, x, y, 1n, hc))))

# G is not the point at infinity (its z is 1)
def hgo_m(+one: Nat, +h1: {one == 1n : Nat}) -> {GS.equiv(1n+GF.pm(one), CS.g(one), CS.infinity()) == False{} : Bool}:
  Lg.subst(Nat, z => {GS.equiv(1n+GF.pm(one), CS.SPoint{px(CS.g(one)), py(CS.g(one)), z}, CS.infinity()) == False{} : Bool}, 1n, one, Equal.sym(Nat, one, 1n, h1), gz1(GF.pm(one), GF.h21_m(one, h1), px(CS.g(one)), py(CS.g(one)), GS.equiv(1n+GF.pm(one), CS.SPoint{px(CS.g(one)), py(CS.g(one)), 1n}, CS.infinity()), {==}))

# 2 n - p - 1
def dl() -> B.Bn:
  %(DL)s

def p2n_b(+one: Nat, +h1: {one == 1n : Nat}) -> {Nat.is_lt(X.bvalo(one, CB.pl()), Nat.add(X.bvalo(one, CB.nl()), X.bvalo(one, CB.nl()))) == True{} : Bool}:
  Lg.subst(Nat, z => {Nat.is_lt(X.bvalo(one, CB.pl()), z) == True{} : Bool}, X.bvalo(one, B.badd(CB.nl(), CB.nl())), Nat.add(X.bvalo(one, CB.nl()), X.bvalo(one, CB.nl())), X.add_o(one, h1, CB.nl(), CB.nl()), X.lt_o(one, h1, CB.pl(), B.badd(CB.nl(), CB.nl()), dl(), {==}))

# p < 2 n
def p2n(+one: Nat, +h1: {one == 1n : Nat}) -> {Nat.is_lt(FS.prime(one), Nat.double(FS.order(one))) == True{} : Bool}:
  Lg.subst(Nat, z => {Nat.is_lt(FS.prime(one), z) == True{} : Bool}, Nat.add(FS.order(one), FS.order(one)), Nat.double(FS.order(one)), Equal.sym(Nat, Nat.double(FS.order(one)), Nat.add(FS.order(one), FS.order(one)), NA.double_self(FS.order(one))),
    Lg.subst(Nat, z => {Nat.is_lt(FS.prime(one), Nat.add(z, z)) == True{} : Bool}, X.bvalo(one, CB.nl()), FS.order(one), CB.n_is(one, h1),
      Lg.subst(Nat, z => {Nat.is_lt(z, Nat.add(X.bvalo(one, CB.nl()), X.bvalo(one, CB.nl()))) == True{} : Bool}, X.bvalo(one, CB.pl()), FS.prime(one), CB.p_is(one, h1), p2n_b(one, h1))))
'''


def lit(v):
    s = 'B.BZ{}'
    bits = []
    while v:
        bits.append(v & 1)
        v >>= 1
    for b in reversed(bits):
        s = ('B.B1{%s}' if b else 'B.B0{%s}') % s
    return s


def sub_mods(t, p, n, g=G1):
    t = t.replace('1n+mp', p).replace('1n+nm', n)
    t = re.sub(r'(?<![A-Za-z0-9_.])g(?![A-Za-z0-9_({])', g, t)
    assert not re.search(r'(?<![A-Za-z0-9_.])(mp|nm)(?![A-Za-z0-9_])', t), t
    return t


def move(t, to_spec, inner):
    """inner proves t at (1+pm, 1+nm) [to_spec] or at (p, n) [not to_spec]; the result proves the other"""
    has_p, has_n = '1n+mp' in t, '1n+nm' in t
    out = inner
    if to_spec:
        if has_n:
            out = 'Lg.subst(Nat, n => %s, %s, %s, Equal.sym(Nat, %s, %s, CB.n_suc(one, h1)), %s)' % (sub_mods(t, PMO, 'n'), NMO, N1, N1, NMO, out)
        if has_p:
            out = 'Lg.subst(Nat, p => %s, %s, %s, Equal.sym(Nat, %s, %s, CB.p_suc(one, h1)), %s)' % (sub_mods(t, 'p', N1), PMO, P1, P1, PMO, out)
    else:
        if has_p:
            out = 'Lg.subst(Nat, p => %s, %s, %s, CB.p_suc(one, h1), %s)' % (sub_mods(t, 'p', N1), P1, PMO, out)
        if has_n:
            out = 'Lg.subst(Nat, n => %s, %s, %s, CB.n_suc(one, h1), %s)' % (sub_mods(t, PMO, 'n'), N1, NMO, out)
    return out


def main():
    p = 2**256 - 2**32 - 977
    n = 0xFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFEBAAEDCE6AF48A03BBFD25E8CD0364141
    out = HEAD % {'DL': lit(2 * n - p - 1)}
    src = open(os.path.join(OUT, 'ecdw.bend')).read()
    for m in re.finditer(r'^((?:#[^\n]*\n)*)def ([a-z0-9_]+)\((.*)\) -> (\{.*\}):$', src, re.M):
        com, name, params, ret = m.group(1), m.group(2), m.group(3), m.group(4)
        if ('1n+mp' not in params and '1n+nm' not in params) or 'F.NZ(' in params or name in ('lows_t',):
            continue
        params = re.sub(r'(?<![A-Za-z0-9_.])(pkb|jb|idn)\(', r'EW.\1(', params)
        ret = re.sub(r'(?<![A-Za-z0-9_.])(pkb|jb|idn)\(', r'EW.\1(', ret)
        decl, args = [], []
        for prm in split_args(params):
            nm_, ty = prm.split(':', 1)
            nm_ = nm_.strip().lstrip('+')
            ty = ty.strip()
            if nm_ in CTX:
                args.append(CTX[nm_])
            elif '1n+mp' in ty or '1n+nm' in ty or re.search(r'(?<![A-Za-z0-9_.])g(?![A-Za-z0-9_({])', ty):
                decl.append('+%s: %s' % (nm_, sub_mods(ty, P1, N1)))
                args.append(move(ty, False, nm_))
            else:
                decl.append('+%s: %s' % (nm_, ty))
                args.append(nm_)
        out += '\n%sdef %s(%s%s) -> %s:\n  %s\n' % (com, name, HD, ''.join(', ' + d for d in decl), sub_mods(ret, P1, N1), move(ret, True, 'EW.%s(%s)' % (name, ', '.join(args))))
    open(os.path.join(OUT, 'ecdp.bend'), 'w').write(out)


if __name__ == '__main__':
    main()
