#!/usr/bin/env python3
"""Generator of the chunked double-and-add computations on literal points
(proofs/crypto/secp256k1/group/ptl_<name>.bend: the literals; pt<name>_<i>.bend:
one root per chunk, a closed check of the machine of ptm.bend through
ptc.chunk). Nothing here is trusted: the intermediate points are only
proposals, each chunk is verified by the checker.

  python3 tools/generators/secp256k1_group/gen_pt.py            (writes all)
"""
import os, sys
HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)
from ptlib import *
OUT = os.path.join(HERE, '..', '..', '..', 'proofs', 'crypto', 'secp256k1', 'group')
G = (GX, GY, 1)


def gen(name, scalar, nbits, size, what):
    bits = bits_of(scalar, nbits)
    chunks = [bits[i:i + size] for i in range(0, nbits, size)]
    pts = [(0, 1, 0)]
    for ch in chunks:
        pts.append(lmul(ch, G, pts[-1]))
    L = ['# GENERATED by tools/generators/secp256k1_group/gen_pt.py; edit the generator', 'import Base', 'import ./bn.bend as B', '',
         '# The literals of the double-and-add for %s: its %d bits (most significant' % (what, nbits),
         '# first) in chunks of %d, and the projective points reached after each chunk' % size,
         '# from (0 : 1 : 0) (proposals, verified by the roots pt%s_<i>.bend).' % name, '']
    for i, ch in enumerate(chunks):
        L += ['def b%d() -> List<&2, Nat>:' % (i + 1), '  [' + ', '.join('%dn' % b for b in ch) + ']', '']
    for i, pt in enumerate(pts):
        for nm, v in zip('xyz', pt):
            L += ['def a%d%s() -> B.Bn:' % (i, nm), '  ' + lit(v), '']
    open(os.path.join(OUT, 'ptl_%s.bend' % name), 'w').write('\n'.join(L))
    for i in range(1, len(chunks) + 1):
        a0 = 'L.a%dx(), L.a%dy(), L.a%dz()' % (i - 1, i - 1, i - 1)
        a1 = 'L.a%dx(), L.a%dy(), L.a%dz()' % (i, i, i)
        g = 'PC.gxl(), PC.gyl(), B.B1{B.BZ{}}'
        T = '''# GENERATED by tools/generators/secp256k1_group/gen_pt.py; edit the generator
import Base
import ../../../../spec/crypto/secp256k1/curve.bend as CS
import ./bn.bend as B
import ./bnx.bend as X
import ./certb.bend as CB
import ./ptm.bend as M
import ./ptc.bend as PC
import ./ptl_%s.bend as L

# Chunk %d of the double-and-add for %s: from the literal point a%d the bits
# b%d give the literal point a%d (one closed check of the machine of ptm.bend).

def hr() -> {M.ok3(CB.pl(), M.BP{%s}) == True{} : Bool}:
  {==}

def ck() -> {PC.fck(M.blmul(L.b%d(), PC.cl(), CB.pl(), M.BP{%s}, M.RP{M.BP{%s}, True{}}), M.BP{%s}) == True{} : Bool}:
  {==}

def fact(+one: Nat, +h1: {one == 1n : Nat}) -> {CS.lmul(1n+X.bvalo(one, CB.p1l()), L.b%d(), PC.spo(one, M.BP{%s}), PC.spo(one, M.BP{%s})) == PC.spo(one, M.BP{%s}) : CS.SPoint}:
  PC.chunk(one, h1, CB.pl(), CB.p1l(), PC.cl(), L.b%d(), %s, %s, %s, PC.hn_p(), PC.hw_p(), PC.h21_p(), PC.hz_p(), PC.hg_p(), hr(), ck())
''' % (name, i, what, i - 1, i, i, a0, i, g, a0, a1, i, g, a0, a1, i, g, a0, a1)
        open(os.path.join(OUT, 'pt%s_%d.bend' % (name, i)), 'w').write(T)
    return pts


def chunk_type(name, i):
    a0 = 'L.a%dx(), L.a%dy(), L.a%dz()' % (i - 1, i - 1, i - 1)
    a1 = 'L.a%dx(), L.a%dy(), L.a%dz()' % (i, i, i)
    return '{CS.lmul(1n+X.bvalo(one, CB.p1l()), L.b%d(), SG, PC.spo(one, M.BP{%s})) == PC.spo(one, M.BP{%s}) : CS.SPoint}' % (i, a0, a1)


def gen_loop(name, k, what):
    """pt<name>.bend: the k chunk facts (hypotheses) give the whole loop from O"""
    SG = 'PC.spo(one, M.BP{PC.gxl(), PC.gyl(), B.B1{B.BZ{}}})'
    hyps = ''.join(', +c%d: %s' % (i, chunk_type(name, i)) for i in range(1, k + 1)).replace('SG', SG)
    def bits(i):
        return 'L.b%d()' % i if i == k else 'List.append(&2, Nat, L.b%d(), %s)' % (i, bits(i + 1))
    def pt(i):
        return 'PC.spo(one, M.BP{L.a%dx(), L.a%dy(), L.a%dz()})' % (i, i, i)
    def comp(i):
        if i == k:
            return 'c%d' % k
        return 'PO.capp(1n+X.bvalo(one, CB.p1l()), L.b%d(), %s, %s, %s, %s, %s, c%d, %s)' % (i, bits(i + 1), SG, pt(i - 1), pt(i), pt(k), i, comp(i + 1))
    T = '''# GENERATED by tools/generators/secp256k1_group/gen_pt.py; edit the generator
import Base
import ../../../lib/lemmas/proofs/nat_algebra.bend as NA
import ../../../lib/logic.bend as Lg
import ../../../../spec/crypto/secp256k1/field.bend as FS
import ../../../../spec/crypto/secp256k1/curve.bend as CS
import ../../../../spec/crypto/secp256k1/group.bend as GS
import ./bn.bend as B
import ./bnx.bend as X
import ./certb.bend as CB
import ./gfp.bend as GF
import ./ptm.bend as M
import ./ptc.bend as PC
import ./ptv.bend as PV
import ./ptk.bend as PO
import ./ptl_%s.bend as L

# The double-and-add for %s, whole: the chunk facts c1..c%d (each proved by
# its own root pt%s_<i>.bend, fact) compose into the loop from O over all
# the bits (loop), with G the specification's generator.

# (0 : 1 : 0) as a literal
def inf_o(+one: Nat, +h1: {one == 1n : Nat}) -> {PC.spo(one, M.BP{L.a0x(), L.a0y(), L.a0z()}) == CS.infinity() : CS.SPoint}:
  %%Equal.sym(Nat, Nat.add(one, 0n), one, NA.add_zero(one)) : {CS.SPoint{0n, _, 0n} == CS.SPoint{0n, 1n, 0n} : CS.SPoint}
  %%Equal.sym(Nat, one, 1n, h1) : {CS.SPoint{0n, _, 0n} == CS.SPoint{0n, 1n, 0n} : CS.SPoint}
  {==}

def loop(+one: Nat, +h1: {one == 1n : Nat}%s) -> {CS.lmul(1n+X.bvalo(one, CB.p1l()), BITS, CS.g(one), CS.infinity()) == %s : CS.SPoint}:
  Lg.subst(CS.SPoint, z => {CS.lmul(1n+X.bvalo(one, CB.p1l()), BITS, z, CS.infinity()) == PTK : CS.SPoint}, SGG, CS.g(one), PV.g_is(one, h1), Lg.subst(CS.SPoint, z => {CS.lmul(1n+X.bvalo(one, CB.p1l()), BITS, SGG, z) == PTK : CS.SPoint}, PT0, CS.infinity(), inf_o(one, h1), COMP))
''' % (name, what, k, name, hyps, pt(k))
    T = T.replace('PTK', pt(k)).replace('SGG', SG).replace('PT0', pt(0)).replace('COMP', comp(1))
    open(os.path.join(OUT, 'pt%s.bend' % name), 'w').write(T.replace('BITS', bits(1)))


def gen_end_n(k):
    """pte.bend: [n] G equiv O from the chunk facts"""
    def bits(i):
        return 'L.b%d()' % i if i == k else 'List.append(&2, Nat, L.b%d(), %s)' % (i, bits(i + 1))
    SG = 'PC.spo(one, M.BP{PC.gxl(), PC.gyl(), B.B1{B.BZ{}}})'
    hyps = ''.join(', +c%d: %s' % (i, chunk_type('n', i)) for i in range(1, k + 1)).replace('SG', SG)
    cs = ', '.join('c%d' % i for i in range(1, k + 1))
    PM_ = 'X.bvalo(one, CB.p1l())'
    ptk = 'PC.spo(one, M.BP{L.a%dx(), L.a%dy(), L.a%dz()})' % (k, k, k)
    HPC = '+hp: PM.Prime(FS.prime(one)), +hc: {Nat.is_eq(FS.mpow(FS.prime(one), Nat.sub(FS.prime(one), 7n), Nat.div(Nat.sub(FS.prime(one), 1n), 3n)), 1n) == False{} : Bool}'
    T = '''# GENERATED by tools/generators/secp256k1_group/gen_pt.py; edit the generator
import Base
import ../../../lib/logic.bend as Lg
import ../../../../spec/crypto/secp256k1/field.bend as FS
import ../../../../spec/crypto/secp256k1/curve.bend as CS
import ../../../../spec/crypto/secp256k1/group.bend as GS
import ../../../math/number/nt_prime.bend as PM
import ./bn.bend as B
import ./bnx.bend as X
import ./certb.bend as CB
import ./gfp.bend as GF
import ./ptm.bend as M
import ./ptc.bend as PC
import ./ptv.bend as PV
import ./pto.bend as PO
import ./ptl_n.bend as L
import ./ptn.bend as PN

# [n] G equiv O: the generator has order dividing n (n is prime: exactly n).
# From the chunk facts c1..c%d of the double-and-add over the bits of n
# (each proved by its own root ptn_<i>.bend, fact): the loop ends at
# (0 : y : 0), and the bits are the number n. hp and hc are the facts about
# p of the group-law clauses (laws_group.bend).

def ng_m(+one: Nat, +h1: {one == 1n : Nat}, HPC%s) -> {GS.equiv(1n+PM_, GS.smul(1n+PM_, X.bvalo(one, CB.nl()), CS.g(one)), CS.infinity()) == True{} : Bool}:
  PO.ord(PM_, GF.hp_m(one, h1, hp), CB.p_mod3(one, h1), GF.hc_m(one, h1, hc), GF.h21_m(one, h1), one, h1, BITS, CS.g(one), PTK, X.bvalo(one, CB.nl()), PV.g_valid_m(one, h1), PN.loop(one, h1, %s), {==}, {==})

# [n] G equiv O, on the specification's p and n
def ng(+one: Nat, +h1: {one == 1n : Nat}, HPC%s) -> {GS.equiv(FS.prime(one), GS.smul(FS.prime(one), FS.order(one), CS.g(one)), CS.infinity()) == True{} : Bool}:
  Lg.subst(Nat, q => {GS.equiv(q, GS.smul(q, FS.order(one), CS.g(one)), CS.infinity()) == True{} : Bool}, 1n+PM_, FS.prime(one), Equal.sym(Nat, FS.prime(one), 1n+PM_, CB.p_suc(one, h1)),
    Lg.subst(Nat, k => {GS.equiv(1n+PM_, GS.smul(1n+PM_, k, CS.g(one)), CS.infinity()) == True{} : Bool}, X.bvalo(one, CB.nl()), FS.order(one), CB.n_is(one, h1), ng_m(one, h1, hp, hc, %s)))
''' % (k, hyps, cs, hyps, cs)
    T = T.replace('HPC', HPC).replace('PM_', PM_).replace('BITS', bits(1)).replace('PTK', ptk)
    open(os.path.join(OUT, 'pte.bend'), 'w').write(T)


if __name__ == '__main__':
    gen('n', N, 256, 32, 'the group order n')
    gen('g', LAM, 256, 32, 'the GLV scalar lambda')
    gen_loop('n', 8, 'the group order n')
    gen_loop('g', 8, 'the GLV scalar lambda')
    gen_end_n(8)
