#!/usr/bin/env python3
"""Generator of the affine addition chains on literal points
(proofs/crypto/secp256k1/group/ptan.bend: [n - 1] G = -G;
ptag.bend: [lambda] G = (beta Gx, Gy)), for the machine of pta.bend: a
4-bit window chain with the slope of every step as a witness. Nothing here
is trusted: the slopes and the expected results are only proposals, the
chain is verified by the checker (one closed check per file).

  python3 tools/generators/secp256k1_group/gen_pta.py
"""
import os, sys
HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)
from ptlib import *
OUT = os.path.join(HERE, '..', '..', '..', 'proofs', 'crypto', 'secp256k1', 'group')


def chain(K):
    """entries [(k, x, y)], steps [('D', i, l) | ('A', i, j, l)] with entry 0 = G"""
    ents, steps = [(1, GX, GY)], []

    def dbl(i):
        k, x, y = ents[i]
        l = 3 * x * x * pow(2 * y, -1, P) % P
        x3 = (l * l - 2 * x) % P
        ents.append((2 * k, x3, (l * (x - x3) - y) % P))
        steps.append(('D', i, l))
        return len(ents) - 1

    def add(i, j):
        k1, x1, y1 = ents[i]
        k2, x2, y2 = ents[j]
        assert x1 != x2
        l = (y2 - y1) * pow(x2 - x1, -1, P) % P
        x3 = (l * l - x1 - x2) % P
        ents.append((k1 + k2, x3, (l * (x1 - x3) - y1) % P))
        steps.append(('A', i, j, l))
        return len(ents) - 1

    tab = {1: 0, 2: dbl(0)}
    for k in range(3, 16):
        tab[k] = add(tab[k - 1], 0)
    digs = []
    while K:
        digs.append(K & 15)
        K >>= 4
    digs.reverse()
    acc = tab[digs[0]]
    for d in digs[1:]:
        for _ in range(4):
            acc = dbl(acc)
        if d:
            acc = add(acc, tab[d])
    return ents, steps, acc


def gen(name, K, kl, what, expect):
    ents, steps, idx = chain(K)
    k, x, y = ents[idx]
    assert k == K and (x, y) == expect
    sl = ', '.join('A.AD{%dn, %s}' % (s[1], lit(s[2])) if s[0] == 'D' else 'A.AA{%dn, %dn, %s}' % (s[1], s[2], lit(s[3])) for s in steps)
    T = '''# GENERATED by tools/generators/secp256k1_group/gen_pta.py; edit the generator
import Base
import ./bn.bend as B
import ./certb.bend as CB
import ./ptc.bend as PC
import ./pta.bend as A
%s
# The addition chain for %s on G, in affine coordinates: %d steps (a
# 4-bit window: the multiples 2 G .. 15 G, then four doublings and one
# addition per digit), each with its slope; entry %d is the result. One
# closed check of the machine of pta.bend (ck).

def steps() -> List<&2, A.AS>:
  [%s]

def ex() -> B.Bn:
  %s

def ey() -> B.Bn:
  %s

def ck() -> {A.acheck(steps(), PC.cl(), CB.pl(), A.AE{B.B1{B.BZ{}}, PC.gxl(), PC.gyl()}, %dn, %s, ex(), ey()) == True{} : Bool}:
  {==}
''' % ('import ./glvc.bend as GC\n' if 'GC.' in kl else '', what, len(steps), idx, sl, lit(expect[0]), lit(expect[1]), idx, kl)
    open(os.path.join(OUT, 'pta%s.bend' % name), 'w').write(T)


if __name__ == '__main__':
    gen('n', N - 1, 'CB.n1l()', 'n - 1', (GX, P - GY))
    gen('g', LAM, 'GC.laml()', 'the GLV scalar lambda', (BETA * GX % P, GY))
