#!/usr/bin/env python3
"""Generator of the chunked double-and-add computations on literal points
(proofs/crypto/secp256k1/group/ptl_<name>.bend: the literals; pt<name>_<i>.bend:
one root per chunk, a closed check of the machine of ptm.bend through
ptc.chunk). Nothing here is trusted: the intermediate points are only
proposals, each chunk is verified by the checker.

  python3 tools/generators/secp256k1_group/gen_pt.py            (writes all)
"""
import os, sys
HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)
from ptlib import *
OUT = os.path.join(HERE, '..', '..', '..', 'proofs', 'crypto', 'secp256k1', 'group')
G = (GX, GY, 1)


def gen(name, scalar, nbits, size, what):
    bits = bits_of(scalar, nbits)
    chunks = [bits[i:i + size] for i in range(0, nbits, size)]
    pts = [(0, 1, 0)]
    for ch in chunks:
        pts.append(lmul(ch, G, pts[-1]))
    L = ['# GENERATED by tools/generators/secp256k1_group/gen_pt.py; edit the generator', 'import Base', 'import ./bn.bend as B', '',
         '# The literals of the double-and-add for %s: its %d bits (most significant' % (what, nbits),
         '# first) in chunks of %d, and the projective points reached after each chunk' % size,
         '# from (0 : 1 : 0) (proposals, verified by the roots pt%s_<i>.bend).' % name, '']
    for i, ch in enumerate(chunks):
        L += ['def b%d() -> List<&2, Nat>:' % (i + 1), '  [' + ', '.join('%dn' % b for b in ch) + ']', '']
    for i, pt in enumerate(pts):
        for nm, v in zip('xyz', pt):
            L += ['def a%d%s() -> B.Bn:' % (i, nm), '  ' + lit(v), '']
    open(os.path.join(OUT, 'ptl_%s.bend' % name), 'w').write('\n'.join(L))
    for i in range(1, len(chunks) + 1):
        a0 = 'L.a%dx(), L.a%dy(), L.a%dz()' % (i - 1, i - 1, i - 1)
        a1 = 'L.a%dx(), L.a%dy(), L.a%dz()' % (i, i, i)
        g = 'PC.gxl(), PC.gyl(), B.B1{B.BZ{}}'
        T = '''# GENERATED by tools/generators/secp256k1_group/gen_pt.py; edit the generator
import Base
import ../../../../spec/crypto/secp256k1/curve.bend as CS
import ./bn.bend as B
import ./bnx.bend as X
import ./certb.bend as CB
import ./ptm.bend as M
import ./ptc.bend as PC
import ./ptl_%s.bend as L

# Chunk %d of the double-and-add for %s: from the literal point a%d the bits
# b%d give the literal point a%d (one closed check of the machine of ptm.bend).

def hr() -> {M.ok3(CB.pl(), M.BP{%s}) == True{} : Bool}:
  {==}

def ck() -> {PC.fck(M.blmul(L.b%d(), PC.cl(), CB.pl(), M.BP{%s}, M.RP{M.BP{%s}, True{}}), M.BP{%s}) == True{} : Bool}:
  {==}

def fact(+one: Nat, +h1: {one == 1n : Nat}) -> {CS.lmul(1n+X.bvalo(one, CB.p1l()), L.b%d(), PC.spo(one, M.BP{%s}), PC.spo(one, M.BP{%s})) == PC.spo(one, M.BP{%s}) : CS.SPoint}:
  PC.chunk(one, h1, CB.pl(), CB.p1l(), PC.cl(), L.b%d(), %s, %s, %s, PC.hn_p(), PC.hw_p(), PC.h21_p(), PC.hz_p(), PC.hg_p(), hr(), ck())
''' % (name, i, what, i - 1, i, i, a0, i, g, a0, a1, i, g, a0, a1, i, g, a0, a1)
        open(os.path.join(OUT, 'pt%s_%d.bend' % (name, i)), 'w').write(T)
    return pts


if __name__ == '__main__':
    gen('n', N, 256, 32, 'the group order n')
    gen('g', LAM, 256, 32, 'the GLV scalar lambda')
