#!/usr/bin/env python3
"""Generator of the identity instances (proofs/crypto/secp256k1/group/id_*.bend).

Each instance is an equation modulo m = 1 + mp between two values of the
specification (registers of CS.run on the add/dbl programs, FS.mmul/msub of
them, the coordinates). The generator only writes down, for each value, its
polynomial (group/poly.bend) and the proof that the value is the
polynomial's (Z.Rel, from group/sym.bend and group/ident.bend); the identity
itself is I.ident with a {==} check that the difference of the two
polynomials, reduced by the curve equations, computes to []. Nothing here is
trusted: a wrong polynomial or a false identity fails the check.

  python3 tools/generators/secp256k1_group/gen_ids.py        (writes all id_*.bend)
"""
import os, sys
HERE = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.join(HERE, '..', '..', '..', 'proofs', 'crypto', 'secp256k1', 'group')

HEAD = '''# GENERATED by tools/generators/secp256k1_group/gen_ids.py; edit the generator
import Base
import ../../../../spec/crypto/secp256k1/field.bend as FS
import ../../../../spec/crypto/secp256k1/curve.bend as CS
import ./poly.bend as P
import ./pev.bend as E
import ./zm.bend as Z
import ./sym.bend as S
import ./ident.bend as I
import ./fld.bend as F
'''

M = '1n+mp'


class V:
    def __init__(self, spec, poly, rel):
        self.spec, self.poly, self.rel = spec, poly, rel


class Ctx:
    """names: the variables (Nat parameters); extra: literal values appended to env"""

    def __init__(self, names, extra=()):
        self.names = list(names)
        self.vals = list(names) + list(extra)
        self.n = len(self.vals)
        self.env = '[' + ', '.join(self.vals) + ']'
        self.params = ', '.join('+%s: Nat' % v for v in ['mp'] + self.names)
        self.args = ', '.join(['mp'] + self.names)
        self.defs = []

    def var(self, i):
        return V(self.vals[i], 'P.pvar(%dn, %dn)' % (self.n, i), 'I.var_rel(mp, %dn, %dn, %s, {==})' % (self.n, i, self.env))

    def zero(self):
        return V('0n', 'Nil{}', '{==}')

    def const(self, k):
        return V('%dn' % k, 'P.pconst(%dn, %dn)' % (self.n, k), '{==}')

    def cmul(self, k, i, val):
        """the literal val = k * (value of variable i), as k x_i"""
        return V('%dn' % val, '[P.Tm{P.zc(%dn), P.unit(%dn, %dn, 1n)}]' % (k, self.n, i), '{==}')

    def op(self, f, g, lem, a, b):
        return V('FS.%s(%s, %s, %s)' % (f, M, a.spec, b.spec), 'P.%s(%s, %s)' % (g, a.poly, b.poly),
                 'I.%s(mp, %s, %s, %s, %s, %s, %s, %s)' % (lem, a.spec, b.spec, a.poly, b.poly, self.env, a.rel, b.rel))

    def mul(self, a, b):
        return self.op('mmul', 'pmul', 'rel_pmul', a, b)

    def add(self, a, b):
        return self.op('madd', 'padd', 'rel_padd', a, b)

    def sub(self, a, b):
        return self.op('msub', 'psub', 'rel_psub', a, b)

    def run(self, prog, ins, k):
        specs = '[' + ', '.join(v.spec for v in ins) + ']'
        polys = '[' + ', '.join(v.poly for v in ins) + ']'
        ag = 'Unit{}'
        for v in reversed(ins):
            ag = 'S.Both{%s, %s}' % (v.rel, ag)
        return V('CS.nth(%dn, CS.run(%s, %s, %s))' % (k, M, prog, specs),
                 'S.snth(%dn, S.srun(%s, %s))' % (k, prog, polys),
                 'S.reg_v(mp, %s, %s, %s, %s, %s, %dn)' % (self.env, prog, polys, specs, ag, k))

    def named(self, name, v, hyps=()):
        """a def for the polynomial and a lemma for its relation (checked once)"""
        self.defs.append('def %s_p() -> List<&2, P.Tm>:\n  %s\n' % (name, v.poly))
        self.defs.append('def %s_r(%s) -> Z.Rel(mp, %s, E.eP(%s_p(), %s), E.eN(%s_p(), %s)):\n  %s\n'
                         % (name, self.params, v.spec, name, self.env, name, self.env, v.rel))
        return V(v.spec, '%s_p()' % name, '%s_r(%s)' % (name, self.args))

    def rule_curve(self, ix, iy, iz, ib, h):
        """hypothesis h: X^3 == Y^2 Z - b Z^3 (as residues) for the point at (ix, iy, iz); the rule X^3 -> that"""
        y, z, b = self.var(iy), self.var(iz), self.var(ib)
        F = self.sub(self.mul(self.mul(y, y), z), self.mul(b, self.mul(self.mul(z, z), z)))
        x = self.vals[ix]
        rel = 'I.cur_rel(mp, %s, %s, E.eP(%s, %s), E.eN(%s, %s), %s, %s)' % (x, F.spec, F.poly, self.env, F.poly, self.env, h, F.rel)
        return (ix, 2, F.poly, rel, '+%s: {FS.mmul(%s, FS.mmul(%s, %s, %s), %s) == %s : Nat}' % (h, M, M, x, x, x, F.spec))

    def rule_zero(self, ix, h):
        """hypothesis h: x == 0 (mod m); the rule x -> 0"""
        x = self.vals[ix]
        return (ix, 0, 'Nil{}', 'I.lin_rel(mp, %s, %s)' % (x, h), '+%s: {Nat.mod(%s, %s) == 0n : Nat}' % (h, x, M))

    def ident(self, name, a, b, rules=(), comment=''):
        hyp_params = ''.join(', ' + r[4] for r in rules)
        d = 'P.psub(%s, %s)' % (a.poly, b.poly)
        polys = [d]
        for ix, dp, fp, rel, hd in rules:
            polys.append('P.redf(%dn, %dn, %dn, %s, %s)' % (self.n, ix, dp, fp, polys[-1]))
        hz = 'I.sm_nil(mp, %s, %s, {==})' % (polys[-1], self.env)
        for j in range(len(rules) - 1, -1, -1):
            ix, dp, fp, rel, hd = rules[j]
            hz = 'I.sm_redf(mp, %dn, %dn, %dn, %s, %s, %s, {==}, %s, %s)' % (self.n, ix, dp, fp, polys[j], self.env, rel, hz)
        self.defs.append('%sdef %s(%s%s) -> {Nat.mod(%s, %s) == Nat.mod(%s, %s) : Nat}:\n  I.ident(mp, %s, %s, %s, %s, %s, %s, %s, %s)\n'
                         % (('# ' + comment + '\n') if comment else '', name, self.params, hyp_params, a.spec, M, b.spec, M,
                            a.spec, b.spec, a.poly, b.poly, self.env, a.rel, b.rel, hz))

    def specdef(self, name, v):
        """a def for the specification value (so that hand proofs can name it)"""
        self.defs.append('def %s(%s) -> Nat:\n  %s\n' % (name, self.params, v.spec))
        return V('%s(%s)' % (name, self.args), v.poly, v.rel)

    def conseq(self, name, a, combos, rules=(), comment=''):
        """a == sum (L_i - R_i) c_i as polynomials; with hypotheses L_i == R_i: a == 0 (mod m)"""
        b = None
        for L, R, cof in combos:
            t = self.mul(self.sub(L, R), cof)
            b = t if b is None else self.add(b, t)
        hyp_params = ''.join(', ' + r[4] for r in rules) + ''.join(', +e%d: {%s == %s : Nat}' % (i + 1, L.spec, R.spec) for i, (L, R, cof) in enumerate(combos))
        d = 'P.psub(%s, %s)' % (a.poly, b.poly)
        polys = [d]
        for ix, dp, fp, rel, hd in rules:
            polys.append('P.redf(%dn, %dn, %dn, %s, %s)' % (self.n, ix, dp, fp, polys[-1]))
        hz = 'I.sm_nil(mp, %s, %s, {==})' % (polys[-1], self.env)
        for j in range(len(rules) - 1, -1, -1):
            ix, dp, fp, rel, hd = rules[j]
            hz = 'I.sm_redf(mp, %dn, %dn, %dn, %s, %s, %s, {==}, %s, %s)' % (self.n, ix, dp, fp, polys[j], self.env, rel, hz)
        # the right side with the first i differences written out and 0 for the others
        def side(i, hole):
            out = None
            for j, (L, R, cof) in enumerate(combos):
                h = '_' if j == hole else ('FS.msub(%s, %s, %s)' % (M, L.spec, R.spec) if j < i else '0n')
                t = 'FS.mmul(%s, %s, %s)' % (M, h, cof.spec)
                out = t if out is None else 'FS.madd(%s, %s, %s)' % (M, out, t)
            return out
        steps = ''
        for i, (L, R, cof) in enumerate(combos):
            steps += '  %%F.msub_eq0(mp, %s, %s, e%d) : {Nat.mod(%s, %s) == Nat.mod(%s, %s) : Nat}\n' % (L.spec, R.spec, i + 1, a.spec, M, side(i, i), M)
        self.defs.append('%sdef %s(%s%s) -> {Nat.mod(%s, %s) == 0n : Nat}:\n%s  I.ident(mp, %s, %s, %s, %s, %s, %s, %s, %s)\n'
                         % (('# ' + comment + '\n') if comment else '', name, self.params, hyp_params, a.spec, M, steps,
                            a.spec, b.spec, a.poly, b.poly, self.env, a.rel, b.rel, hz))

    def write(self, fname, header):
        with open(os.path.join(OUT, fname), 'w') as f:
            f.write(HEAD + '\n' + header + '\n' + '\n'.join(self.defs))


ADD, DBL = 'CS.add_prog()', 'CS.dbl_prog()'


def padd(c, p, q, b3):
    return [c.run(ADD, list(p) + list(q) + [b3], k) for k in (33, 36, 39)]


def pdbl(c, p, b3):
    return [c.run(DBL, list(p) + [b3], k) for k in (21, 18, 13)]


def point(c, i):
    return [c.var(3 * i), c.var(3 * i + 1), c.var(3 * i + 2)]


def gen_comm():
    c = Ctx(['x1', 'y1', 'z1', 'x2', 'y2', 'z2', 'w'])
    p, q, w = point(c, 0), point(c, 1), c.var(6)
    l, r = padd(c, p, q, w), padd(c, q, p, w)
    for k, nm in enumerate('xyz'):
        c.ident('comm_' + nm, l[k], r[k], comment='coordinate %s of P + Q and of Q + P (any b3 = w)' % nm.upper())
    c.write('id_comm.bend', '# The complete addition is commutative, coordinate by coordinate.\n')


def cube(c, v):
    return c.mul(c.mul(v, v), v)


def curve_val(c, v, b7):
    """X^3 and Y^2 Z - b Z^3 of the point v"""
    x, y, z = v
    return cube(c, x), c.sub(c.mul(c.mul(y, y), z), c.mul(b7, cube(c, z)))


def gen_curve():
    c = Ctx(['x1', 'y1', 'z1', 'x2', 'y2', 'z2'], ['7n'])
    p, q, b7, b3 = point(c, 0), point(c, 1), c.var(6), c.cmul(3, 6, 21)
    cv = [c.rule_curve(0, 1, 2, 6, 'h1'), c.rule_curve(3, 4, 5, 6, 'h2')]
    s = padd(c, p, q, b3)
    s = [c.specdef('aX', s[0]), s[1], c.specdef('aZ', s[2])]
    # completeness: c2 Y3 == N^3 + 7 D^3 with N / D the x-coordinate a 2-torsion point P - Q would have
    x1, y1, z1 = p
    x2, y2, z2 = q
    ay = c.specdef('aY', s[1])
    s[1] = ay
    a, b = curve_val(c, s, b7)
    c.ident('add_curve', a, b, cv, 'P and Q on the curve X^3 = Y^2 Z - 7 Z^3: so is P + Q')
    zz = c.specdef('cZ', c.mul(z1, z2))
    sh = c.specdef('cS', c.add(c.mul(x1, z2), c.mul(x2, z1)))
    pi = c.mul(x1, x2)
    n = c.specdef('cN', c.sub(c.mul(sh, pi), c.mul(c.cmul(4, 6, 28), c.mul(zz, zz))))
    d = c.specdef('cD', c.add(c.mul(sh, sh), c.mul(c.const(2), c.mul(pi, zz))))
    k = c.add(c.add(c.mul(c.const(3), c.mul(c.mul(x1, x1), c.mul(x2, z2))), c.mul(c.const(3), c.mul(c.mul(x1, z1), c.mul(x2, x2)))),
              c.add(c.add(c.mul(c.mul(y1, y1), c.mul(z2, z2)), c.mul(c.mul(z1, z1), c.mul(y2, y2))), c.mul(c.cmul(6, 6, 42), c.mul(zz, zz))))
    w = c.specdef('cW', c.mul(c.mul(zz, zz), k))
    c.ident('compl_y', c.mul(w, ay), c.add(cube(c, n), c.mul(b7, cube(c, d))), cv,
            'W Y3 == N^3 + 7 D^3: the Y of P + Q vanishes only with a cube root N / D of -7')
    c.ident('compl_s', c.add(cube(c, sh), c.mul(b7, cube(c, c.mul(c.const(2), zz)))), c.sub(c.mul(sh, d), c.mul(c.mul(c.const(2), zz), n)), (),
            's^3 + 7 (2 z1 z2)^3 == s D - 2 z1 z2 N')
    c.ident('inf_y', ay, c.mul(c.mul(y1, y1), c.mul(y2, y2)), [c.rule_zero(0, 'hx'), c.rule_zero(2, 'hz')],
            'P at infinity (x1 == z1 == 0): the Y of P + Q is y1^2 y2^2')
    c.ident('inf_x', cube(c, x1), c.zero(), [cv[0], c.rule_zero(2, 'hz')], 'a point of the curve with z == 0 has x^3 == 0')
    c.write('id_curve.bend', '# The sum of two points of the curve is on the curve, and it is not\n# (0, 0, 0): the identities behind completeness.\n')


def gen_dbl():
    c = Ctx(['x', 'y', 'z'], ['7n'])
    p, b7, b3 = point(c, 0), c.var(3), c.cmul(3, 3, 21)
    cv = [c.rule_curve(0, 1, 2, 3, 'h')]
    d, a = pdbl(c, p, b3), padd(c, p, p, b3)
    for k, nm in enumerate('xyz'):
        c.ident('dbl_' + nm, d[k], a[k], cv, 'coordinate %s of 2 P (the doubling program) and of P + P, for P on the curve' % nm.upper())
    x, y, z = p
    o = [c.zero(), c.const(1), c.zero()]
    u = padd(c, p, o, b3)
    for k, nm in enumerate('xyz'):
        c.ident('unit_' + nm, u[k], c.mul(p[k], y), (), 'P + (0, 1, 0) == y P, coordinate %s' % nm.upper())
    ng = padd(c, p, [x, c.sub(c.zero(), y), z], b3)
    c.ident('unit_ex', c.mul(u[0], y), c.mul(x, u[1]), (), 'P + (0, 1, 0) and P: cross product x, y')
    c.ident('unit_ez', c.mul(u[2], y), c.mul(z, u[1]), (), 'P + (0, 1, 0) and P: cross product z, y')
    ny = c.sub(c.zero(), y)
    c.ident('neg_curve', cube(c, x), c.sub(c.mul(c.mul(ny, ny), z), c.mul(b7, cube(c, z))), cv, '(x, -y, z) is on the curve when (x, y, z) is')
    c.ident('inf_curve', cube(c, c.zero()), c.sub(c.mul(c.mul(c.const(1), c.const(1)), c.zero()), c.mul(b7, cube(c, c.zero()))), (), '(0, 1, 0) is on the curve')
    x3, y2z, sz = cube(c, x), c.mul(c.mul(y, y), z), c.mul(b7, cube(c, z))
    c.conseq('to_x', c.sub(x3, c.sub(y2z, sz)), [(c.add(x3, sz), y2z, c.const(1))], (), 'X^3 + 7 Z^3 == Y^2 Z gives X^3 == Y^2 Z - 7 Z^3')
    c.conseq('to_y', c.sub(y2z, c.add(x3, sz)), [(c.sub(y2z, sz), x3, c.const(1))], (), 'and conversely')
    c.ident('neg_x', ng[0], c.zero(), (), 'P + (x, -y, z) has X == 0')
    c.ident('neg_z', ng[2], c.zero(), (), 'P + (x, -y, z) has Z == 0')
    c.write('id_dbl.bend', '# Doubling is adding a point to itself; (0, 1, 0) is the identity and\n# (x, -y, z) the inverse, up to scaling.\n')


def gen_hom():
    c = Ctx(['x1', 'y1', 'z1', 'x2', 'y2', 'z2', 'l', 'w'])
    p, q, l, w = point(c, 0), point(c, 1), c.var(6), c.var(7)
    s, t = padd(c, p, q, w), padd(c, [c.mul(l, v) for v in p], q, w)
    for k, nm in enumerate('xyz'):
        c.ident('hom_' + nm, t[k], c.mul(c.mul(l, l), s[k]), (), '(l P) + Q == l^2 (P + Q), coordinate %s' % nm.upper())
    c.write('id_hom.bend', '# The complete addition is homogeneous of degree 2 in its first argument.\n')


def gen_alg():
    c = Ctx(['a1', 'b1', 'a2', 'b2', 'a3', 'b3'])
    a1, b1, a2, b2, a3, b3 = [c.var(i) for i in range(6)]
    c.conseq('ratio_trans', c.mul(c.sub(c.mul(a1, b3), c.mul(a3, b1)), b2),
             [(c.mul(a1, b2), c.mul(a2, b1), b3), (c.mul(a2, b3), c.mul(a3, b2), b1)], (),
             'a1 b2 == a2 b1 and a2 b3 == a3 b2 give (a1 b3 - a3 b1) b2 == 0')
    c.write('id_alg1.bend', '# Transitivity of equal ratios.\n')
    c = Ctx(['a', 'b', 'sx', 'sy', 'tx', 'ty'])
    a, b, sx, sy, tx, ty = [c.var(i) for i in range(6)]
    c.conseq('scale_eqv', c.mul(c.sub(c.mul(sx, ty), c.mul(tx, sy)), c.mul(a, b)),
             [(c.mul(a, sx), c.mul(b, tx), c.mul(b, ty)), (c.mul(b, ty), c.mul(a, sy), c.mul(b, tx))], (),
             'a S == b T (coordinates x and y) gives (sx ty - tx sy) a b == 0')
    c.write('id_alg2.bend', '# Proportional triples have equal cross products.\n')
    c = Ctx(['u', 'v', 'w'])
    u, v, w = [c.var(i) for i in range(3)]
    g = c.mul(v, w)
    c.conseq('cube_t', c.add(cube(c, c.mul(u, w)), c.const(7)),
             [(c.add(cube(c, u), c.mul(c.const(7), cube(c, v))), c.zero(), cube(c, w)),
              (c.const(1), g, c.mul(c.const(7), c.add(c.add(c.const(1), g), c.mul(g, g))))], (),
             'u^3 + 7 v^3 == 0 and v w == 1 give (u w)^3 + 7 == 0')
    c.write('id_alg3.bend', '# A projective cube root of -7 gives an affine one.\n')


def gen_alg4():
    c = Ctx(['a1', 'b1', 'a2', 'b2'])
    a1, b1, a2, b2 = [c.var(i) for i in range(4)]
    n1, n2 = c.sub(c.zero(), b1), c.sub(c.zero(), b2)
    c.conseq('neg_ratio', c.sub(c.mul(a1, n2), c.mul(a2, n1)), [(c.mul(a2, b1), c.mul(a1, b2), c.const(1))], (),
             'a2 b1 == a1 b2 gives a1 (-b2) - a2 (-b1) == 0')
    c.write('id_alg4.bend', '# Ratios and negation.\n')


def gen_assoc(i, j):
    nm = 'xyz'[i] + 'xyz'[j]
    c = Ctx(['x1', 'y1', 'z1', 'x2', 'y2', 'z2', 'x3', 'y3', 'z3'], ['7n'])
    p, q, r, b3 = point(c, 0), point(c, 1), point(c, 2), c.cmul(3, 9, 21)
    cv = [c.rule_curve(0, 1, 2, 9, 'h1'), c.rule_curve(3, 4, 5, 9, 'h2'), c.rule_curve(6, 7, 8, 9, 'h3')]
    l = padd(c, padd(c, p, q, b3), r, b3)
    rr = padd(c, p, padd(c, q, r, b3), b3)
    li, lj = c.named('l' + 'xyz'[i], l[i]), c.named('l' + 'xyz'[j], l[j])
    ri, rj = c.named('r' + 'xyz'[i], rr[i]), c.named('r' + 'xyz'[j], rr[j])
    c.ident('assoc_' + nm, c.mul(li, rj), c.mul(ri, lj), cv,
            'L = (P + Q) + R, Rr = P + (Q + R): L.%s Rr.%s == Rr.%s L.%s for points of the curve' % (nm[0], nm[1], nm[0], nm[1]))
    c.write('id_assoc_%s.bend' % nm, '# Associativity of the complete addition, up to projective scaling:\n# one of the three cross products.\n')


if __name__ == '__main__':
    gen_comm()
    gen_curve()
    gen_dbl()
    gen_hom()
    gen_alg()
    gen_alg4()
    for i, j in ((0, 1), (1, 2)):
        gen_assoc(i, j)
