#!/usr/bin/env python3
"""Writes proofs/crypto/secp256k1/group/schs.bend: BIP-340 signing succeeds and
verifies, on the specification's terms (spec/crypto/secp256k1/schnorr.bend),
from the generic lemmas of schg.bend moved to p = FS.prime(one), n = FS.order(one),
G = CS.g(one). Plain text generation (the terms are long and repetitive).

  python3 tools/generators/secp256k1_group/gen_schs.py
"""
import os
HERE = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.join(HERE, '..', '..', '..', 'proofs', 'crypto', 'secp256k1')
p, n, G = 'FS.prime(one)', 'FS.order(one)', 'CS.g(one)'
PM1, NM1 = '1n+GF.pm(one)', '1n+nm(one)'
HCT = '{Nat.is_eq(FS.mpow(FS.prime(one), Nat.sub(FS.prime(one), 7n), Nat.div(Nat.sub(FS.prime(one), 1n), 3n)), 1n) == False{} : Bool}'
HGT = '{GS.valid(FS.prime(one), CS.g(one)) == True{} : Bool}'
HNGT = '{GS.equiv(FS.prime(one), GS.smul(FS.prime(one), FS.order(one), CS.g(one)), CS.infinity()) == True{} : Bool}'
HD = '+one: Nat, +h1: {one == 1n : Nat}, +hp: PM.Prime(FS.prime(one)), +hc: %s, +hq: PM.Prime(FS.order(one)), +hg: %s, +hng: %s' % (HCT, HGT, HNGT)
HA = 'one, h1, hp, hc, hq, hg, hng'
FPA = 'GF.pm(one), GF.hp_m(one, h1, hp), CB.p_mod3(one, h1), GF.hc_m(one, h1, hc), GF.h21_m(one, h1)'
SQA = 'one, h1, X.bvalo(one, EB.s4l()), EG.he_m(one, h1), EG.hodd_m(one, h1), EG.h256_m(one, h1)'
GAm = 'nm(one), hq_m(one, h1, hq), CS.g(one), vg_m(one, h1, hg), hng_m(one, h1, hng), hgo_m(one, h1)'
BYTES = 'List<&2, U32>'
MB = 'Maybe<&2, List<&2, U32>>'


def down_p(prop, h):
    """a fact about FS.prime(one) moved to 1 + pm; prop is a function of the modulus"""
    return 'Lg.subst(Nat, t => %s, FS.prime(one), %s, CB.p_suc(one, h1), %s)' % (prop('t'), PM1, h)


def down_n(prop, h):
    return 'Lg.subst(Nat, t => %s, FS.order(one), %s, CB.n_suc(one, h1), %s)' % (prop('t'), NM1, h)


def up(prop2, h):
    """a fact about (1 + pm, 1 + nm) moved to (p, n); prop2 is a function of both moduli"""
    inner = 'Lg.subst(Nat, t => %s, %s, FS.order(one), Equal.sym(Nat, FS.order(one), %s, CB.n_suc(one, h1)), %s)' % (prop2(PM1, 't'), NM1, NM1, h)
    return 'Lg.subst(Nat, t => %s, %s, FS.prime(one), Equal.sym(Nat, FS.prime(one), %s, CB.p_suc(one, h1)), %s)' % (prop2('t', n), PM1, PM1, inner)


def V(q, a):
    return '{GS.valid(%s, %s) == True{} : Bool}' % (q, a)


def E(q, a, b):
    return '{GS.equiv(%s, %s, %s) == True{} : Bool}' % (q, a, b)


def LT(a, b):
    return '{Nat.is_lt(%s, %s) == True{} : Bool}' % (a, b)


def ta(q, j):
    return 'CS.to_affine(%s, CS.pmul(%s, %s, CS.g(one)))' % (q, q, j)


def evr(q, m, j):
    return 'SG.EvR(%s, %s, CS.g(one), CS.aff_x(%s), CS.aff_y(%s), %s, Nat.mod(CS.aff_y(%s), 2n))' % (q, m, ta(q, j), ta(q, j), j, ta(q, j))


def subst_chain(ty, steps, final):
    """steps: list of (type, motive fn of t, old term, new term, proof of {old == new}); the goal is motive(old) at
    the first step; returns a proof of the first goal from `final`, a proof of the last motive at its new term"""
    out = final
    for T, mot, old, new, pr in reversed(steps):
        out = 'Lg.subst(%s, t => %s, %s, %s, Equal.sym(%s, %s, %s, %s), %s)' % (T, mot('t'), new, old, T, old, new, pr, out)
    return out


def main():
    o = []
    o.append('''# GENERATED by tools/generators/secp256k1_group/gen_schs.py; edit the generator
import Base
import ../../../../spec/lib/common.bend as C
import ../../../../spec/crypto/secp256k1/field.bend as FS
import ../../../../spec/crypto/secp256k1/curve.bend as CS
import ../../../../spec/crypto/secp256k1/group.bend as GS
import ../../../../spec/crypto/secp256k1/schnorr.bend as SS
import ../../../lib/logic.bend as Lg
import ../../../lib/nat.bend as N
import ../../../math/number/nt_prime.bend as PM
import ./bnx.bend as X
import ./certb.bend as CB
import ./gfp.bend as GF
import ./encb.bend as EB
import ./encg.bend as EG
import ./enco.bend as EO
import ./sqrt.bend as SQ
import ./sym.bend as S
import ./schg.bend as SG
import ./schd.bend as D

# BIP-340 on the specification's terms: signing succeeds (its final
# self-verification never fails) and the signature verifies. The facts
# about p, n and G are hypotheses, each proved in a root of its own:
#   hp: p is prime;  hc: (-7)^((p-1)/3) != 1;  hq: n is prime;
#   hg: G is a point of the group;  hng: [n] G is O.

# ---- the hypotheses on the moduli 1 + pm and 1 + nm ----

def nm(+one: Nat) -> Nat:
  X.bvalo(one, CB.n1l())

def hq_m(+one: Nat, +h1: {one == 1n : Nat}, +hq: PM.Prime(FS.order(one))) -> PM.Prime(1n+nm(one)):
  %s

def vg_m(+one: Nat, +h1: {one == 1n : Nat}, +hg: %s) -> %s:
  %s

def hng_m(+one: Nat, +h1: {one == 1n : Nat}, +hng: %s) -> %s:
  %s

def pz(a: CS.SPoint) -> Nat:
  match a:
    case CS.SPoint{x, y, z}:
      z

def gno_a(+mp: Nat, +h21: {Nat.is_lt(21n, 1n+mp) == True{} : Bool}, a: CS.SPoint, +one: Nat, +h1: {one == 1n : Nat}, +hz: {pz(a) == one : Nat}) -> {GS.equiv(1n+mp, a, CS.infinity()) == False{} : Bool}:
  match a:
    case CS.SPoint{+x, +y, +z}:
      Lg.subst(Nat, t => {GS.equiv(1n+mp, CS.SPoint{x, y, t}, CS.infinity()) == False{} : Bool}, one, z, Equal.sym(Nat, z, one, hz), SG.gno(mp, h21, x, y, one, h1))

def hgo_m(+one: Nat, +h1: {one == 1n : Nat}) -> {GS.equiv(1n+GF.pm(one), CS.g(one), CS.infinity()) == False{} : Bool}:
  gno_a(GF.pm(one), GF.h21_m(one, h1), CS.g(one), one, h1, {==})

def hn256_m(+one: Nat, +h1: {one == 1n : Nat}) -> {Nat.is_le(1n+nm(one), C.shift(256n, one)) == True{} : Bool}:
  %s
''' % (down_n(lambda t: 'PM.Prime(%s)' % t, 'hq'),
       HGT, V(PM1, G), down_p(lambda t: V(t, G), 'hg'),
       HNGT, E(PM1, 'GS.smul(%s, %s, %s)' % (PM1, NM1, G), 'CS.infinity()'),
       down_n(lambda t: E(PM1, 'GS.smul(%s, %s, %s)' % (PM1, t, G), 'CS.infinity()'), down_p(lambda t: E(t, 'GS.smul(%s, %s, %s)' % (t, n, G), 'CS.infinity()'), 'hng')),
       down_n(lambda t: '{Nat.is_le(%s, C.shift(256n, one)) == True{} : Bool}' % t, 'SQ.sub_le(FS.w256(one), FS.cn(one))')))
    # transported lemmas
    o.append('''
# ---- the lemmas of schg.bend on p, n and G ----

# the even-y representative of [j] G (0 < j < n)
def tev(%s, +j: Nat, +hj0: {Nat.is_eq(j, 0n) == False{} : Bool}, +hjn: %s) -> %s:
  %s

def tvr(%s, +d: Nat, +k: Nat, +e: Nat, +pp: CS.SPoint, +rx: Nat, +ey: Nat, +hk: %s, +vp: %s, +hpp: %s, +ve: %s, +hre: %s, +hrx: %s, +hey: %s, +hev: {Nat.mod(ey, 2n) == 0n : Nat}) -> SG.VR(FS.prime(one), FS.order(one), CS.g(one), d, k, e, pp, rx):
  %s

def taxb(+one: Nat, +h1: {one == 1n : Nat}, +a: CS.SPoint) -> SG.AxB(FS.prime(one), a):
  Lg.subst(Nat, t => SG.AxB(t, a), 1n+GF.pm(one), FS.prime(one), Equal.sym(Nat, FS.prime(one), 1n+GF.pm(one), CB.p_suc(one, h1)), SG.axb(GF.pm(one), one, h1, EG.h256_m(one, h1), a))

def tsb(+one: Nat, +h1: {one == 1n : Nat}, +v: Nat) -> SG.SB(FS.order(one), v):
  Lg.subst(Nat, t => SG.SB(t, v), 1n+nm(one), FS.order(one), Equal.sym(Nat, FS.order(one), 1n+nm(one), CB.n_suc(one, h1)), SG.sb(nm(one), one, h1, hn256_m(one, h1), v))

def tel(+one: Nat, +h1: {one == 1n : Nat}, +b: Nat, +j: Nat, +hjn: %s) -> SG.EL(FS.order(one), b, j):
  Lg.subst(Nat, t => SG.EL(t, b, j), 1n+nm(one), FS.order(one), Equal.sym(Nat, FS.order(one), 1n+nm(one), CB.n_suc(one, h1)), SG.el(nm(one), b, j, %s))
''' % (HD, LT('j', n), evr(p, n, 'j'),
       up(lambda q, m: evr(q, m, 'j'), 'SG.evp2(%s, %s, %s, hn256_m(one, h1), j, hj0, %s)' % (FPA, SQA, GAm, down_n(lambda t: LT('j', t), 'hjn'))),
       HD, LT('k', n), V(p, 'pp'), E(p, 'pp', 'GS.smul(%s, d, %s)' % (p, G)), V(p, 'CS.SPoint{rx, ey, 1n}'), E(p, 'CS.SPoint{rx, ey, 1n}', 'GS.smul(%s, k, %s)' % (p, G)), LT('rx', p), LT('ey', p),
       up(lambda q, m: 'SG.VR(%s, %s, CS.g(one), d, k, e, pp, rx)' % (q, m),
          'SG.vrf2(%s, one, h1, nm(one), hn256_m(one, h1), CS.g(one), vg_m(one, h1, hg), hng_m(one, h1, hng), d, k, e, pp, rx, ey, %s, %s, %s, %s, %s, %s, %s, hev)' % (
              FPA, down_n(lambda t: LT('k', t), 'hk'), down_p(lambda t: V(t, 'pp'), 'vp'), down_p(lambda t: E(t, 'pp', 'GS.smul(%s, d, %s)' % (t, G)), 'hpp'),
              down_p(lambda t: V(t, 'CS.SPoint{rx, ey, 1n}'), 've'), down_p(lambda t: E(t, 'CS.SPoint{rx, ey, 1n}', 'GS.smul(%s, k, %s)' % (t, G)), 'hre'),
              down_p(lambda t: LT('rx', t), 'hrx'), down_p(lambda t: LT('ey', t), 'hey'))),
       LT('j', n), down_n(lambda t: LT('j', t), 'hjn')))
    open(os.path.join(OUT, 'group', 'schs.bend'), 'w').write('\n'.join(o))


if __name__ == '__main__':
    main()
