#!/usr/bin/env python3
"""Generator of the affine addition chains on literal points
(proofs/crypto/secp256k1/group/ptan.bend: [n - 1] G = -G;
ptag.bend: [lambda] G = (beta Gx, Gy)), for the machine of pta.bend: a
4-bit window chain with the slope of every step as a witness. Nothing here
is trusted: the slopes and the expected results are only proposals, the
chain is verified by the checker (one closed check per file).

  python3 tools/generators/secp256k1_group/gen_pta.py
"""
import os, sys
HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)
from ptlib import *
OUT = os.path.join(HERE, '..', '..', '..', 'proofs', 'crypto', 'secp256k1', 'group')


def chain(K):
    """entries [(k, x, y)], steps [('D', i, l) | ('A', i, j, l)] with entry 0 = G"""
    ents, steps = [(1, GX, GY)], []

    def dbl(i):
        k, x, y = ents[i]
        l = 3 * x * x * pow(2 * y, -1, P) % P
        x3 = (l * l - 2 * x) % P
        ents.append((2 * k, x3, (l * (x - x3) - y) % P))
        steps.append(('D', i, l))
        return len(ents) - 1

    def add(i, j):
        k1, x1, y1 = ents[i]
        k2, x2, y2 = ents[j]
        assert x1 != x2
        l = (y2 - y1) * pow(x2 - x1, -1, P) % P
        x3 = (l * l - x1 - x2) % P
        ents.append((k1 + k2, x3, (l * (x1 - x3) - y1) % P))
        steps.append(('A', i, j, l))
        return len(ents) - 1

    tab = {1: 0, 2: dbl(0)}
    for k in range(3, 16):
        tab[k] = add(tab[k - 1], 0)
    digs = []
    while K:
        digs.append(K & 15)
        K >>= 4
    digs.reverse()
    acc = tab[digs[0]]
    for d in digs[1:]:
        for _ in range(4):
            acc = dbl(acc)
        if d:
            acc = add(acc, tab[d])
    return ents, steps, acc


PM_ = 'X.bvalo(one, CB.p1l())'
G1 = 'CS.SPoint{X.bvalo(one, PC.gxl()), X.bvalo(one, PC.gyl()), 1n}'
HPC = '+hp: PM.Prime(FS.prime(one)), +hc: {Nat.is_eq(FS.mpow(FS.prime(one), Nat.sub(FS.prime(one), 7n), Nat.div(Nat.sub(FS.prime(one), 1n), 3n)), 1n) == False{} : Bool}'
FPA = 'X.bvalo(one, CB.p1l()), GF.hp_m(one, h1, hp), CB.p_mod3(one, h1), GF.hc_m(one, h1, hc), GF.h21_m(one, h1)'
IMPS = '''import Base
import ../../../lib/logic.bend as Lg
import ../../../../spec/crypto/secp256k1/field.bend as FS
import ../../../../spec/crypto/secp256k1/curve.bend as CS
import ../../../../spec/crypto/secp256k1/group.bend as GS
import ../../../../spec/crypto/secp256k1/affine.bend as GA
import ../../../../spec/crypto/secp256k1/glv.bend as GV
import ../../../math/number/nt_prime.bend as PM
import ./bn.bend as B
import ./bnx.bend as X
import ./certb.bend as CB
import ./gfp.bend as GF
import ./ptc.bend as PC
import ./ptv.bend as PV
'''


def bo(a):
    return 'X.bvalo(one, %s)' % a


def fact_t(kl, m):
    return '{GA.of_proj(1n+%s, GS.smul(1n+%s, %s, %s)) == GA.APt{%s, %s} : GA.APoint}' % (PM_, PM_, bo(kl), G1, bo(m + 'ex()'), bo(m + 'ey()'))


def gen(name, K, kl, what, expect):
    ents, steps, idx = chain(K)
    k, x, y = ents[idx]
    assert k == K and (x, y) == expect
    sl = ', '.join('A.AD{%dn, %s}' % (s[1], lit(s[2])) if s[0] == 'D' else 'A.AA{%dn, %dn, %s}' % (s[1], s[2], lit(s[3])) for s in steps)
    T = '''# GENERATED by tools/generators/secp256k1_group/gen_pta.py; edit the generator
%simport ./pta.bend as A
%s
# The addition chain for %s on G, in affine coordinates: %d steps (a
# 4-bit window: the multiples 2 G .. 15 G, then four doublings and one
# addition per digit), each with its slope; entry %d is the result. One
# closed check of the machine of pta.bend (ck), and what it proves (fact):
# the affine point of the multiple of G, for hp and hc the facts about p of
# group/glawp.bend.

def steps() -> List<&2, A.AS>:
  [%s]

def ex() -> B.Bn:
  %s

def ey() -> B.Bn:
  %s

def ck() -> {A.acheck(steps(), PC.cl(), CB.pl(), A.AE{B.B1{B.BZ{}}, PC.gxl(), PC.gyl()}, %dn, %s, ex(), ey()) == True{} : Bool}:
  {==}

def fact(+one: Nat, +h1: {one == 1n : Nat}, %s) -> %s:
  A.chain_o(one, h1, CB.pl(), CB.p1l(), PC.cl(), GF.hp_m(one, h1, hp), CB.p_mod3(one, h1), GF.hc_m(one, h1, hc), GF.h21_m(one, h1), PC.hn_p(), PC.hw_p(), PC.hz_p(), {==}, {==}, PC.gxl(), PC.gyl(), {==}, {==}, PV.g1_valid(one, h1), steps(), %dn, %s, ex(), ey(), ck())
''' % (IMPS, 'import ./glvc.bend as GC\n' if 'GC.' in kl else '', what, len(steps), idx, sl, lit(expect[0]), lit(expect[1]), idx, kl, HPC, fact_t(kl, ''), idx, kl)
    open(os.path.join(OUT, 'pta%s.bend' % name), 'w').write(T)


def gen_ends():
    hn = 'PC.hn_p()'
    NQ = bo('CB.n1l()')
    ord_c = lambda z: '{GS.equiv(1n+%s, CS.padd(1n+%s, GS.smul(1n+%s, %s, %s), %s), CS.infinity()) == True{} : Bool}' % (PM_, PM_, PM_, NQ, z, z)
    hf = 'Lg.subst(Nat, v => {GA.of_proj(1n+%s, GS.smul(1n+%s, %s, %s)) == GA.APt{v, %s} : GA.APoint}, %s, %s, X.eq_o(one, h1, AN.ex(), PC.gxl(), {==}), AN.fact(one, h1, hp, hc))' % (PM_, PM_, NQ, G1, bo('AN.ey()'), bo('AN.ex()'), bo('PC.gxl()'))
    T = '''# GENERATED by tools/generators/secp256k1_group/gen_pta.py; edit the generator
%simport ./ptf.bend as PF
import ./ptan.bend as AN

# [n] G equiv O: the generator has order dividing n (n is prime: exactly
# n). The chain of group/ptan.bend gives the affine point of [n - 1] G,
# which is (Gx, p - Gy) = -G; so [n] G = [n - 1] G + G is O. hp and hc are
# the facts about p of group/glawp.bend.

def ng_m(+one: Nat, +h1: {one == 1n : Nat}, %s) -> {GS.equiv(1n+%s, GS.smul(1n+%s, 1n+%s, CS.g(one)), CS.infinity()) == True{} : Bool}:
  Lg.subst(CS.SPoint, z => %s, %s, CS.g(one), PV.g1_is(one, h1),
    PF.ord_aff(%s, %s, %s, %s, %s, PV.g1_valid(one, h1), PF.lt_p1(one, h1, PC.gxl(), CB.pl(), CB.p1l(), %s, %s, {==}), PF.sum_p1(one, h1, PC.gyl(), AN.ey(), CB.pl(), CB.p1l(), %s, {==}), PF.lt_p1(one, h1, AN.ey(), CB.pl(), CB.p1l(), %s, %s, {==}), %s))

# [n] G equiv O, on the specification's p and n
def ng(+one: Nat, +h1: {one == 1n : Nat}, %s) -> {GS.equiv(FS.prime(one), GS.smul(FS.prime(one), FS.order(one), CS.g(one)), CS.infinity()) == True{} : Bool}:
  Lg.subst(Nat, q => {GS.equiv(q, GS.smul(q, FS.order(one), CS.g(one)), CS.infinity()) == True{} : Bool}, 1n+%s, FS.prime(one), Equal.sym(Nat, FS.prime(one), 1n+%s, CB.p_suc(one, h1)),
    Lg.subst(Nat, k => {GS.equiv(1n+%s, GS.smul(1n+%s, k, CS.g(one)), CS.infinity()) == True{} : Bool}, 1n+%s, FS.order(one), Equal.sym(Nat, FS.order(one), 1n+%s, CB.n_suc(one, h1)), ng_m(one, h1, hp, hc)))
''' % (IMPS, HPC, PM_, PM_, NQ, ord_c('z'), G1, FPA, bo('PC.gxl()'), bo('PC.gyl()'), bo('AN.ey()'), NQ, lit(P - GX - 1), hn, hn, lit(GY - 1), hn, hf,
       HPC, PM_, PM_, PM_, PM_, NQ, NQ)
    open(os.path.join(OUT, 'pte.bend'), 'w').write(T)
    BE, LA = bo('GC.betal()'), bo('GC.laml()')
    ex = BETA * GX % P
    glv_c = lambda q, z: '{GS.equiv(%s, GV.phi(%s, %s, %s), GS.smul(%s, %s, %s)) == True{} : Bool}' % (q, q, BE, z, q, LA, z)
    hf = 'Lg.subst(Nat, v => {GA.of_proj(1n+%s, GS.smul(1n+%s, %s, %s)) == GA.APt{%s, v} : GA.APoint}, %s, %s, X.eq_o(one, h1, AG.ey(), PC.gyl(), {==}), AG.fact(one, h1, hp, hc))' % (PM_, PM_, LA, G1, bo('AG.ex()'), bo('AG.ey()'), bo('PC.gyl()'))
    T = '''# GENERATED by tools/generators/secp256k1_group/gen_pta.py; edit the generator
%simport ./glvc.bend as GC
import ./ptf.bend as PF
import ./ptag.bend as AG

# phi(G) equiv [lambda] G, with beta = X.bvalo(one, GC.betal()) and
# lambda = X.bvalo(one, GC.laml()): the chain of group/ptag.bend gives the
# affine point of [lambda] G, which is (beta Gx mod p, Gy), the affine
# point of phi(G) = (beta Gx : Gy : 1). hp and hc are the facts about p of
# group/glawp.bend.

def phi_g_m(+one: Nat, +h1: {one == 1n : Nat}, %s) -> %s:
  Lg.subst(CS.SPoint, z => %s, %s, CS.g(one), PV.g1_is(one, h1),
    PF.glv_aff(%s, %s, GC.beta_cube_m(one, h1), %s, %s, %s, %s, PV.g1_valid(one, h1), PF.lt_p1(one, h1, PC.gyl(), CB.pl(), CB.p1l(), %s, %s, {==}), PF.mulmod_o(one, h1, GC.betal(), PC.gxl(), %s, CB.pl(), CB.p1l(), AG.ex(), %s, %s, {==}, {==}), %s))

# phi(G) equiv [lambda] G
def phi_g(+one: Nat, +h1: {one == 1n : Nat}, %s) -> %s:
  Lg.subst(Nat, q => %s, 1n+%s, FS.prime(one), Equal.sym(Nat, FS.prime(one), 1n+%s, CB.p_suc(one, h1)), phi_g_m(one, h1, hp, hc))
''' % (IMPS, HPC, glv_c('1n+' + PM_, 'CS.g(one)'), glv_c('1n+' + PM_, 'z'), G1, FPA, BE, bo('PC.gxl()'), bo('PC.gyl()'), bo('AG.ex()'), LA,
       lit(P - GY - 1), hn, lit(BETA * GX // P), lit(P - ex - 1), hn, hf, HPC, glv_c('FS.prime(one)', 'CS.g(one)'), glv_c('q', 'CS.g(one)'), PM_, PM_)
    open(os.path.join(OUT, 'glvf.bend'), 'w').write(T)


if __name__ == '__main__':
    gen('n', N - 1, 'CB.n1l()', 'n - 1', (GX, P - GY))
    gen('g', LAM, 'GC.laml()', 'the GLV scalar lambda', (BETA * GX % P, GY))
    gen_ends()
