#!/usr/bin/env python3
"""Generate src/crypto/aes/bitslice.bend: AES on two blocks at a time, bitsliced
over eight U32 words (the representation of BearSSL's aes_ct).

  python3 tools/generators/aes/bitslice.py
"""
from pathlib import Path

ROOT = Path(__file__).resolve().parents[3]
CIRC = (Path(__file__).resolve().parent / 'bp_circuit.txt').read_text().strip().splitlines()
Q = ['q%d' % i for i in range(8)]


def sbox():
    out = ['# SubBytes on both blocks: the Boyar-Peralta circuit on the eight bit planes',
           '# (x0 is plane 7, the bytes\' most significant bits; s0 lands in plane 7).',
           'def sub_bytes(q: Q8) -> Q8:', '  match q:',
           '    case Q8{%s}:' % ', '.join('+' + x for x in Q)]
    for i in range(8):
        out.append('      +x%d = q%d' % (i, 7 - i))
    for line in CIRC:
        lhs, rhs = [s.strip() for s in line.split('=')]
        a, op, b = rhs.split()
        f = 'U32.xor' if op == '^' else 'U32.and'
        if b.startswith('~'):
            b = 'U32.xor(4294967295, %s)' % b[1:]
        out.append('      +%s = %s(%s, %s)' % (lhs, f, a, b))
    out.append('      Q8{%s}' % ', '.join('s%d' % (7 - i) for i in range(8)))
    return out


def main():
    out = '''import Base

# Generated by tools/generators/aes/bitslice.py.
#
# AES encryption of two blocks at once, bitsliced: after `ortho`, word q_i
# holds bit i of all 32 bytes of the two blocks (BearSSL's aes_ct layout).
# Every step is a fixed sequence of U32 AND/XOR/OR/shifts: no table, no
# branch on data. proofs/crypto/aes/bitslice*.bend prove each step equal to
# the byte-level step of src/crypto/aes/aes.bend on every position.

type Q8 is Data:
  Q8{q0: U32, q1: U32, q2: U32, q3: U32, q4: U32, q5: U32, q6: U32, q7: U32}

def swap_lo(+m: U32, +s: Nat, +x: U32, +y: U32) -> U32:
  U32.or(U32.and(m, x), U32.shln(U32.and(m, y), s))

def swap_hi(+m: U32, +s: Nat, +x: U32, +y: U32) -> U32:
  U32.or(U32.shrn(U32.and(m, x), s), U32.and(m, y))

# The bit-matrix transposition between four little-endian words per block
# and the eight bit planes; its own inverse.
def ortho(q: Q8) -> Q8:
  match q:
    case Q8{+a0, +a1, +a2, +a3, +a4, +a5, +a6, +a7}:
      +b0 = swap_lo(1431655765, 1n, a0, a1)
      +b1 = swap_hi(2863311530, 1n, a0, a1)
      +b2 = swap_lo(1431655765, 1n, a2, a3)
      +b3 = swap_hi(2863311530, 1n, a2, a3)
      +b4 = swap_lo(1431655765, 1n, a4, a5)
      +b5 = swap_hi(2863311530, 1n, a4, a5)
      +b6 = swap_lo(1431655765, 1n, a6, a7)
      +b7 = swap_hi(2863311530, 1n, a6, a7)
      +c0 = swap_lo(858993459, 2n, b0, b2)
      +c2 = swap_hi(3435973836, 2n, b0, b2)
      +c1 = swap_lo(858993459, 2n, b1, b3)
      +c3 = swap_hi(3435973836, 2n, b1, b3)
      +c4 = swap_lo(858993459, 2n, b4, b6)
      +c6 = swap_hi(3435973836, 2n, b4, b6)
      +c5 = swap_lo(858993459, 2n, b5, b7)
      +c7 = swap_hi(3435973836, 2n, b5, b7)
      Q8{swap_lo(252645135, 4n, c0, c4), swap_lo(252645135, 4n, c1, c5), swap_lo(252645135, 4n, c2, c6), swap_lo(252645135, 4n, c3, c7),
        swap_hi(4042322160, 4n, c0, c4), swap_hi(4042322160, 4n, c1, c5), swap_hi(4042322160, 4n, c2, c6), swap_hi(4042322160, 4n, c3, c7)}

'''.split('\n')
    out += sbox()
    out += '''
def shift_word(+x: U32) -> U32:
  U32.or(U32.and(255, x), U32.or(U32.shrn(U32.and(64512, x), 2n), U32.or(U32.shln(U32.and(768, x), 6n),
    U32.or(U32.shrn(U32.and(15728640, x), 4n), U32.or(U32.shln(U32.and(983040, x), 4n),
    U32.or(U32.shrn(U32.and(3221225472, x), 6n), U32.shln(U32.and(1056964608, x), 2n)))))))

def shift_rows(q: Q8) -> Q8:
  match q:
    case Q8{a0, a1, a2, a3, a4, a5, a6, a7}:
      Q8{shift_word(a0), shift_word(a1), shift_word(a2), shift_word(a3), shift_word(a4), shift_word(a5), shift_word(a6), shift_word(a7)}

def rot8(+x: U32) -> U32:
  U32.or(U32.shrn(x, 8n), U32.shln(x, 24n))

def rot16(+x: U32) -> U32:
  U32.or(U32.shln(x, 16n), U32.shrn(x, 16n))

def mix_columns(q: Q8) -> Q8:
  match q:
    case Q8{+a0, +a1, +a2, +a3, +a4, +a5, +a6, +a7}:
      +r0 = rot8(a0)
      +r1 = rot8(a1)
      +r2 = rot8(a2)
      +r3 = rot8(a3)
      +r4 = rot8(a4)
      +r5 = rot8(a5)
      +r6 = rot8(a6)
      +r7 = rot8(a7)
      +t7 = U32.xor(a7, r7)
      Q8{U32.xor(U32.xor(t7, r0), rot16(U32.xor(a0, r0))),
        U32.xor(U32.xor(U32.xor(U32.xor(a0, r0), t7), r1), rot16(U32.xor(a1, r1))),
        U32.xor(U32.xor(U32.xor(a1, r1), r2), rot16(U32.xor(a2, r2))),
        U32.xor(U32.xor(U32.xor(U32.xor(a2, r2), t7), r3), rot16(U32.xor(a3, r3))),
        U32.xor(U32.xor(U32.xor(U32.xor(a3, r3), t7), r4), rot16(U32.xor(a4, r4))),
        U32.xor(U32.xor(U32.xor(a4, r4), r5), rot16(U32.xor(a5, r5))),
        U32.xor(U32.xor(U32.xor(a5, r5), r6), rot16(U32.xor(a6, r6))),
        U32.xor(U32.xor(U32.xor(a6, r6), r7), rot16(U32.xor(a7, r7)))}

def add_round_key(q: Q8, k: Q8) -> Q8:
  match q k:
    case Q8{a0, a1, a2, a3, a4, a5, a6, a7} Q8{k0, k1, k2, k3, k4, k5, k6, k7}:
      Q8{U32.xor(a0, k0), U32.xor(a1, k1), U32.xor(a2, k2), U32.xor(a3, k3), U32.xor(a4, k4), U32.xor(a5, k5), U32.xor(a6, k6), U32.xor(a7, k7)}

def round(q: Q8, k: Q8) -> Q8:
  add_round_key(mix_columns(shift_rows(sub_bytes(q))), k)
'''.split('\n')
    (ROOT / 'src/crypto/aes/bitslice.bend').write_text('\n'.join(out))


if __name__ == '__main__':
    main()
