"""The layer lemmas of the bitsliced AES (proofs/crypto/aes/bs/layers.bend);
run through tools/generators/aes/bsproof.py."""
from bitsym import *  # noqa
from bsproof import OUT, N32, pos_byte, mix_sym, ortho_sym, ROW_EXPR

HEAD = '''import Base
import ../../../../src/crypto/aes/types.bend as T
import ../../../../src/crypto/aes/sbox.bend as SB
import ../../../../src/crypto/aes/aes.bend as A
import ../../../../src/crypto/aes/bitslice.bend as X
import ../../../../src/crypto/aes/fast.bend as F
import ./defs.bend as D
import ./words.bend as W
import ./bytes.bend as Y
import ./mix.bend as M

# Generated by tools/generators/aes/bsproof.py.
#
# Each bitsliced step of bitslice.bend, applied to the planes B(sa, sb) of two
# states, gives the planes of the byte-level step of aes.bend applied to each
# state. The equalities are assembled plane by plane and bit by bit
# (D.q8_ext, D.u32_ext) from the bit lemmas of words/bytes/mix.bend.
'''

ROUND = '''
def round_ok(+sa: T.State, +sb: T.State, +k: T.State) -> {X.round(D.B(sa, sb), F.plane_key(k)) == D.B(A.round(sa, k), A.round(sb, k)) : X.Q8}:
  %Equal.sym(X.Q8, F.plane_key(k), D.B(k, k), key_ok(k)) : {X.add_round_key(X.mix_columns(X.shift_rows(X.sub_bytes(D.B(sa, sb)))), _) == D.B(A.round(sa, k), A.round(sb, k)) : X.Q8}
  %Equal.sym(X.Q8, X.sub_bytes(D.B(sa, sb)), D.B(A.sub_bytes(sa), A.sub_bytes(sb)), sub_ok(sa, sb)) : {X.add_round_key(X.mix_columns(X.shift_rows(_)), D.B(k, k)) == D.B(A.round(sa, k), A.round(sb, k)) : X.Q8}
  %Equal.sym(X.Q8, X.shift_rows(D.B(A.sub_bytes(sa), A.sub_bytes(sb))), D.B(A.shift_rows(A.sub_bytes(sa)), A.shift_rows(A.sub_bytes(sb))), shift_ok(A.sub_bytes(sa), A.sub_bytes(sb))) : {X.add_round_key(X.mix_columns(_), D.B(k, k)) == D.B(A.round(sa, k), A.round(sb, k)) : X.Q8}
  %Equal.sym(X.Q8, X.mix_columns(D.B(A.shift_rows(A.sub_bytes(sa)), A.shift_rows(A.sub_bytes(sb)))), D.B(A.mix_columns(A.shift_rows(A.sub_bytes(sa))), A.mix_columns(A.shift_rows(A.sub_bytes(sb)))), mix_ok(A.shift_rows(A.sub_bytes(sa)), A.shift_rows(A.sub_bytes(sb)))) : {X.add_round_key(_, D.B(k, k)) == D.B(A.round(sa, k), A.round(sb, k)) : X.Q8}
  ark_ok(A.mix_columns(A.shift_rows(A.sub_bytes(sa))), A.mix_columns(A.shift_rows(A.sub_bytes(sb))), k)

# The last round: SubBytes and ShiftRows in planes.
def last_ok(+sa: T.State, +sb: T.State) -> {X.shift_rows(X.sub_bytes(D.B(sa, sb))) == D.B(A.shift_rows(A.sub_bytes(sa)), A.shift_rows(A.sub_bytes(sb))) : X.Q8}:
  %Equal.sym(X.Q8, X.sub_bytes(D.B(sa, sb)), D.B(A.sub_bytes(sa), A.sub_bytes(sb)), sub_ok(sa, sb)) : {X.shift_rows(_) == D.B(A.shift_rows(A.sub_bytes(sa)), A.shift_rows(A.sub_bytes(sb))) : X.Q8}
  shift_ok(A.sub_bytes(sa), A.sub_bytes(sb))
'''


def qvars(prefix):
    return ['%s%d' % (prefix, i) for i in range(16)]


def state(prefix):
    v = qvars(prefix)
    return 'T.S{%s}' % ', '.join('T.W{%s}' % ', '.join(v[4 * c:4 * c + 4]) for c in range(4))


def quad(prefix, c):
    return 'T.W{%s}' % ', '.join(qvars(prefix)[4 * c:4 * c + 4])


def bytes_at(p):
    blk, col, row = pos_byte(p)
    return '%s%d' % ('ab'[blk], 4 * col + row)


def dbit(n, k):
    return 'D.bit(%s, %dn)' % (n, k)


def q8_ext(L, R, P):
    return 'D.q8_ext(%s, %s, %s)' % (', '.join(L), ', '.join(R), ', '.join(P))


def u32_ext(L, R, P):
    return 'D.u32_ext(%s, %s, %s)' % (', '.join(L), ', '.join(R), ', '.join(P))


def plane(i):
    return [dbit(bytes_at(p), i) for p in N32]


def shift_perm(x):
    def m(k, w):
        return wand(const(k), w)
    return wor(m(255, x), wor(shr(m(64512, x), 2), wor(shl(m(768, x), 6), wor(shr(m(15728640, x), 4), wor(shl(m(983040, x), 4), wor(shr(m(3221225472, x), 6), shl(m(1056964608, x), 2)))))))


def layer_lemmas():
    out = HEAD.split('\n')
    SA, SB_, SK = state('a'), state('b'), state('k')
    ST = '%s %s' % (SA, SB_)
    # ---- le32 on four bytes
    out += ['def le32_ok(+a: U32, +b: U32, +c: U32, +d: U32) -> {F.le32(a, b, c, d) == %s : U32}:' % word([dbit(n, k) for n in 'abcd' for k in range(8)]),
            '  match a b c d:', '    case %s:' % ' '.join(word(['%s%d' % (n, k) for k in N32]) for n in 'abcd'),
            '      W.le32_bits(%s)' % ', '.join('%s%d' % (n, k) for n in 'abcd' for k in N32), '']
    # ---- load
    qa = ['qa%d' % c for c in range(4)]
    qb = ['qb%d' % c for c in range(4)]
    qw, clean = [], []
    for c in range(4):
        for pre in 'ab':
            v = ['%s%d' % (pre, 4 * c + r) for r in range(4)]
            qw.append('F.le32(%s)' % ', '.join(v))
            clean.append(word([dbit(x, k) for x in v for k in range(8)]))
    out += ['# Two states into bit planes.',
            'def load_ok(%s) -> {X.ortho(X.Q8{%s}) == D.B(T.S{%s}, T.S{%s}) : X.Q8}:' % (
                ', '.join('+%s: T.Quad' % q for q in qa + qb), ', '.join('F.quad_word(%s)' % x for c in range(4) for x in (qa[c], qb[c])),
                ', '.join(qa), ', '.join(qb)),
            '  match %s:' % ' '.join(qa + qb),
            '    case %s:' % ' '.join([quad('a', c) for c in range(4)] + [quad('b', c) for c in range(4)])]
    for i in range(8):
        c, pre = i // 2, 'ab'[i % 2]
        v = ['%s%d' % (pre, 4 * c + r) for r in range(4)]
        motive = clean[:i] + ['_'] + qw[i + 1:]
        out.append('      %%Equal.sym(U32, F.le32(%s), %s, le32_ok(%s)) : {X.ortho(X.Q8{%s}) == D.B(%s, %s) : X.Q8}' % (
            ', '.join(v), clean[i], ', '.join(v), ', '.join(motive), SA, SB_))
    out += ['      W.ortho_bits(%s)' % ', '.join(dbit('%s%d' % (pre, 4 * c + r), k) for c in range(4) for pre in 'ab' for r in range(4) for k in range(8)), '']
    out += ['# A round key in planes (the same key for both blocks).',
            'def key_ok(+k: T.State) -> {F.plane_key(k) == D.B(k, k) : X.Q8}:',
            '  match k:', '    case T.S{q0, q1, q2, q3}:', '      load_ok(q0, q1, q2, q3, q0, q1, q2, q3)', '']
    # ---- SubBytes
    Lw, Rw, Pw = [], [], []
    for i in range(8):
        L = ['Y.sf%d(%s)' % (i, ', '.join(dbit(bytes_at(p), k) for k in range(8))) for p in N32]
        R = ['D.bit(SB.sbox(%s), %dn)' % (bytes_at(p), i) for p in N32]
        P = ['Y.sbox_bit%d(%s)' % (i, bytes_at(p)) for p in N32]
        Lw.append(word(L))
        Rw.append(word(R))
        Pw.append(u32_ext(L, R, P))
    out += ['def sub_ok(+sa: T.State, +sb: T.State) -> {X.sub_bytes(D.B(sa, sb)) == D.B(A.sub_bytes(sa), A.sub_bytes(sb)) : X.Q8}:',
            '  match sa sb:', '    case %s:' % ST, '      %s' % q8_ext(Lw, Rw, Pw), '']
    # ---- ShiftRows
    Lw, Rw, Pw = [], [], []
    for i in range(8):
        pl = plane(i)
        Lw.append('X.shift_word(%s)' % word(pl))
        Pw.append('W.shift_bits(%s)' % ', '.join(pl))
        Rw.append(word([leaves(b)[0] for b in shift_perm([var(t) for t in pl])]))
    out += ['def shift_ok(+sa: T.State, +sb: T.State) -> {X.shift_rows(D.B(sa, sb)) == D.B(A.shift_rows(sa), A.shift_rows(sb)) : X.Q8}:',
            '  match sa sb:', '    case %s:' % ST, '      %s' % q8_ext(Lw, Rw, Pw), '']
    # ---- MixColumns
    Mx = mix_sym([[var(t) for t in plane(i)] for i in range(8)])
    Lw, Rw, Pw = [], [], []
    for j in range(8):
        L, R, P = [], [], []
        for p in N32:
            blk, col, row = pos_byte(p)
            u = ['%s%d' % ('ab'[blk], 4 * col + r) for r in range(4)]
            L.append(show(Mx[j][p]))
            e = ROW_EXPR[row]
            for r in range(4):
                e = e.replace('u%d' % r, u[r])
            R.append('D.bit(%s, %dn)' % (e, j))
            P.append('M.mix%d_%d(%s)' % (row, j, ', '.join(u)))
        Lw.append(word(L))
        Rw.append(word(R))
        Pw.append(u32_ext(L, R, P))
    out += ['def mix_ok(+sa: T.State, +sb: T.State) -> {X.mix_columns(D.B(sa, sb)) == D.B(A.mix_columns(sa), A.mix_columns(sb)) : X.Q8}:',
            '  match sa sb:', '    case %s:' % ST, '      %s' % q8_ext(Lw, Rw, Pw), '']
    # ---- AddRoundKey
    Lw, Rw, Pw = [], [], []
    for i in range(8):
        L, R, P = [], [], []
        for p in N32:
            blk, col, row = pos_byte(p)
            t, kk = bytes_at(p), 'k%d' % (4 * col + row)
            L.append('Bool.xor(%s, %s)' % (dbit(t, i), dbit(kk, i)))
            R.append('D.bit(U32.xor(%s, %s), %dn)' % (t, kk, i))
            P.append('Y.xor_bit%d(%s, %s)' % (i, t, kk))
        Lw.append(word(L))
        Rw.append(word(R))
        Pw.append(u32_ext(L, R, P))
    out += ['def ark_ok(+sa: T.State, +sb: T.State, +k: T.State) -> {X.add_round_key(D.B(sa, sb), D.B(k, k)) == D.B(A.add_round_key(sa, k), A.add_round_key(sb, k)) : X.Q8}:',
            '  match sa sb k:', '    case %s %s:' % (ST, SK), '      %s' % q8_ext(Lw, Rw, Pw), '']
    out += ROUND.split('\n')
    # ---- the planes back to bytes, with the last round key added
    rhs = []
    for blk in range(2):
        for t in range(16):
            rhs.append('U32.xor(D.byte_of(%s), k%d)' % (', '.join(dbit('%s%d' % ('ab'[blk], t), k) for k in range(8)), t))
    orth = ortho_sym([[var(t) for t in plane(i)] for i in range(8)])
    out_words = ', '.join(word([leaves(b)[0] for b in orth[w]]) for w in range(8))
    ortho_args = ', '.join(t for i in range(8) for t in plane(i))
    RHS = '[%s]' % ', '.join(rhs)
    out += ['# The planes back to the bytes of the two states, xor a key.',
            'def store_ok(+sa: T.State, +sb: T.State, +k: T.State) -> {F.stream(F.Out{X.ortho(D.B(sa, sb)), k}) == D.store(sa, sb, k) : List<&2, U32>}:',
            '  match sa sb k:', '    case %s %s:' % (ST, SK),
            '      %%Equal.sym(X.Q8, X.ortho(D.planes(%s)), X.Q8{%s}, W.ortho_bits(%s)) : {F.stream(F.Out{_, %s}) == %s : List<&2, U32>}' % (
                ', '.join(qvars('a') + qvars('b')), out_words, ortho_args, SK, RHS),
            '      {==}', '']
    # ---- the stored bytes of the last round are the byte-level output
    sh = [[None] * 4 for _ in range(4)]   # shifted state: column c, row r -> source byte index
    for c in range(4):
        for r in range(4):
            sh[c][r] = 4 * ((c + r) % 4) + r
    L, R, P = [], [], []
    for pre in 'ab':
        for c in range(4):
            for r in range(4):
                x = 'SB.sbox(%s%d)' % (pre, sh[c][r])
                kk = 'k%d' % (4 * c + r)
                bo = 'D.byte_of(%s)' % ', '.join('D.bit(%s, %dn)' % (x, k) for k in range(8))
                L.append('U32.xor(%s, %s)' % (bo, kk))
                R.append('U32.xor(%s, %s)' % (x, kk))
                P.append('Equal.cong(U32, U32, v => U32.xor(v, %s), %s, %s, Y.sbox_canon(%s%d))' % (kk, bo, x, pre, sh[c][r]))
    out += ['# After SubBytes the bytes are bytes: storing them is the last AddRoundKey.',
            'def store_last(+sa: T.State, +sb: T.State, +k: T.State) -> {D.store(A.shift_rows(A.sub_bytes(sa)), A.shift_rows(A.sub_bytes(sb)), k) == List.append(&2, U32, A.bytes_of(A.add_round_key(A.shift_rows(A.sub_bytes(sa)), k)), A.bytes_of(A.add_round_key(A.shift_rows(A.sub_bytes(sb)), k))) : List<&2, U32>}:',
            '  match sa sb k:', '    case %s %s:' % (ST, SK.replace('k', '+k').replace('T.S{T.W{+k', 'T.S{T.W{+k')),
            '      D.list_ext32(%s, %s, %s)' % (', '.join(L), ', '.join(R), ', '.join(P)), '']
    (OUT / 'layers.bend').write_text('\n'.join(out))
