#!/usr/bin/env python3
"""Generate the bit-level proofs of the bitsliced AES (src/crypto/aes/bitslice.bend,
the AES part of src/crypto/aes/fast.bend) in proofs/crypto/aes/bs/.

  python3 tools/generators/aes/bsproof.py

The relation: B(sa, sb) is the eight bit planes of two AES states, plane i
bit p = bit i of byte (block p % 2, column (p / 2) % 4, row p / 8). Each
bitsliced step is proved equal, under B, to the byte-level step of
src/crypto/aes/aes.bend, bit by bit: the checker reduces both sides to one
Bool expression per bit, and the two expressions of a bit are proved equal
by `{==}`, by `bit_id` (x OR False is x) or by a lemma that case-splits
their few variables.
"""
import itertools, sys
from pathlib import Path
sys.path.insert(0, str(Path(__file__).resolve().parent))
from bitsym import *  # noqa

ROOT = Path(__file__).resolve().parents[3]
OUT = ROOT / 'proofs/crypto/aes/bs'
CIRC = (Path(__file__).resolve().parent / 'bp_circuit.txt').read_text().strip().splitlines()
N32 = range(32)


def pos_byte(p):
    """plane position p -> (block, column, row)"""
    return p % 2, (p // 2) % 4, p // 8


def byte_name(blk, col, row):
    return '%s%d' % ('a' if blk == 0 else 'b', 4 * col + row)


STATE_A = 'T.S{T.W{a0, a1, a2, a3}, T.W{a4, a5, a6, a7}, T.W{a8, a9, a10, a11}, T.W{a12, a13, a14, a15}}'
STATE_B = STATE_A.replace('a', 'b').replace('T.S', 'T.S').replace('T.W', 'T.W')
STATE_B = 'T.S{T.W{b0, b1, b2, b3}, T.W{b4, b5, b6, b7}, T.W{b8, b9, b10, b11}, T.W{b12, b13, b14, b15}}'


def dbit(name, i):
    return 'D.bit(%s, %dn)' % (name, i)


def plane_bits(i, bitf=dbit):
    """plane i of B(sa, sb): 32 bit terms"""
    return [bitf(byte_name(*pos_byte(p)), i) for p in N32]


# ---------------------------------------------------------------- defs

def store_list():
    r = []
    for pre in 'ab':
        for t in range(16):
            r.append('U32.xor(byte_of(%s), k%d)' % (', '.join('bit(%s%d, %dn)' % (pre, t, k) for k in range(8)), t))
    return ', '.join(r)


def defs():
    B = []
    for i in range(8):
        B.append(word(plane_bits(i, lambda n, k: 'bit(%s, %dn)' % (n, k))))
    X = ['x%d' % i for i in N32]
    Y = ['y%d' % i for i in N32]
    ext = ['def u32_ext(%s, %s, %s) -> {%s == %s : U32}:' % (
        ', '.join('+%s: Bool' % v for v in X), ', '.join('+%s: Bool' % v for v in Y),
        ', '.join('e%d: {%s == %s : Bool}' % (i, X[i], Y[i]) for i in N32), word(X), word(Y))]
    for i in N32:
        ext.append('  %%e%d : {%s == %s : U32}' % (i, word(X), word(X[:i] + ['_'] + Y[i + 1:])))
    ext.append('  {==}')
    A8 = ['a%d' % i for i in range(8)]
    B8 = ['b%d' % i for i in range(8)]
    q8 = ['def q8_ext(%s, %s, %s) -> {X.Q8{%s} == X.Q8{%s} : X.Q8}:' % (
        ', '.join('+%s: U32' % v for v in A8), ', '.join('+%s: U32' % v for v in B8),
        ', '.join('e%d: {%s == %s : U32}' % (i, A8[i], B8[i]) for i in range(8)), ', '.join(A8), ', '.join(B8))]
    for i in range(8):
        q8.append('  %%e%d : {X.Q8{%s} == X.Q8{%s} : X.Q8}' % (i, ', '.join(A8), ', '.join(A8[:i] + ['_'] + B8[i + 1:])))
    q8.append('  {==}')
    text = '''import Base
import ../../../../src/crypto/aes/types.bend as T
import ../../../../src/crypto/aes/bitslice.bend as X

# Generated by tools/generators/aes/bsproof.py.
#
# The bits of a byte, the bit-plane relation B and the extensionality lemmas
# the bit-level proofs assemble their results with.

def wbit(n: Nat, w: Word(n), i: Nat) -> Bool:
  match n w i:
    case 0n WNil{} _:
      False{}
    case 1n+p WCon{b, t} 0n:
      b
    case 1n+p WCon{b, t} 1n+j:
      wbit(p, t, j)

# Bit i of a U32 (bit 0 the least significant).
def bit(x: U32, i: Nat) -> Bool:
  match x:
    case U32{w}: wbit(32n, w, i)

# The byte with bits b0 (least significant) .. b7.
def byte_of(b0: Bool, b1: Bool, b2: Bool, b3: Bool, b4: Bool, b5: Bool, b6: Bool, b7: Bool) -> U32:
  U32{WCon{b0, WCon{b1, WCon{b2, WCon{b3, WCon{b4, WCon{b5, WCon{b6, WCon{b7, Word.zero(24n)}}}}}}}}}

# The bit planes of two states (the layout of bitslice.bend): plane i, bit
# p = bit i of byte (row p / 8, column (p / 2) %% 4) of state p %% 2.
def planes(%s, %s) -> X.Q8:
  X.Q8{%s}

def B(sa: T.State, sb: T.State) -> X.Q8:
  match sa sb:
    case %s %s:
      planes(%s, %s)

# The low bytes of two states, each xor a key (what the planes store).
def store(sa: T.State, sb: T.State, k: T.State) -> List<&2, U32>:
  match sa sb k:
    case %s %s %s:
      [%s]

def bit_id(f: Bool -> Bool, +x: Bool, ht: {f(True{}) == True{} : Bool}, hf: {f(False{}) == False{} : Bool}) -> {f(x) == x : Bool}:
  match x:
    case True{}: ht
    case False{}: hf

%s

%s
''' % (', '.join('+a%d: U32' % i for i in range(16)), ', '.join('+b%d: U32' % i for i in range(16)), ', '.join(B),
       STATE_A, STATE_B, ', '.join('a%d' % i for i in range(16)), ', '.join('b%d' % i for i in range(16)),
       STATE_A.replace('a', '+a'), STATE_B.replace('b', '+b'), STATE_A.replace('a', '+k'), store_list(),
       '\n'.join(ext), '\n'.join(q8))
    (OUT / 'defs.bend').write_text(text)


# ---------------------------------------------------------------- word lemmas

def bit_proof(lhs, rhs):
    """a proof of {lhs == rhs : Bool} for a lhs with at most one variable,
    rhs being that variable (lhs x or x OR False ...)"""
    if lhs == rhs:
        return '{==}'
    vs = leaves(lhs)
    assert len(vs) == 1 and rhs == ('v', vs[0]), (show(lhs), show(rhs))
    f = subst(lhs, vs[0], ('v', 'z'))
    return 'D.bit_id(z => %s, %s, {==}, {==})' % (show(f), vs[0])


def ext_word(lhs, rhs, proofs):
    return 'D.u32_ext(%s, %s, %s)' % (', '.join(show(b) for b in lhs), ', '.join(show(b) for b in rhs), ', '.join(proofs))


def cleanup_lemma(name, params, lhs_expr, words_in, fn, out_perm_words):
    """a lemma {fn(words) == perm words} proved per bit with bit_id"""
    raise NotImplementedError


def ortho_sym(q):
    def swap_lo(m, s, x, y):
        return wor(wand(const(m), x), shl(wand(const(m), y), s))

    def swap_hi(m, s, x, y):
        return wor(shr(wand(const(m), x), s), wand(const(m), y))
    a = q
    b = [None] * 8
    for i in (0, 2, 4, 6):
        b[i] = swap_lo(0x55555555, 1, a[i], a[i + 1])
        b[i + 1] = swap_hi(0xAAAAAAAA, 1, a[i], a[i + 1])
    c = [None] * 8
    for (i, j) in ((0, 2), (1, 3), (4, 6), (5, 7)):
        c[i] = swap_lo(0x33333333, 2, b[i], b[j])
        c[j] = swap_hi(0xCCCCCCCC, 2, b[i], b[j])
    return [swap_lo(0x0F0F0F0F, 4, c[i], c[i + 4]) for i in range(4)] + [swap_hi(0xF0F0F0F0, 4, c[i], c[i + 4]) for i in range(4)]


def one_var(e):
    vs = leaves(e)
    return ('v', vs[0]) if len(vs) == 1 else e


def word_lemmas():
    out = ['import Base',
           'import ../../../../src/crypto/aes/types.bend as T',
           'import ../../../../src/crypto/aes/bitslice.bend as X',
           'import ../../../../src/crypto/aes/fast.bend as F',
           'import ./defs.bend as D', '',
           '# Generated by tools/generators/aes/bsproof.py.', '']
    # ORTHO: 256 variables q<w>_<p>
    Q = [[var('q%d_%d' % (w, p)) for p in N32] for w in range(8)]
    R = ortho_sym(Q)
    params = ', '.join('+q%d_%d: Bool' % (w, p) for w in range(8) for p in N32)
    ins = ', '.join(word([show(b) for b in Q[w]]) for w in range(8))
    rhs_words = [[one_var(b) for b in R[w]] for w in range(8)]
    outs = ', '.join(word([show(b) for b in rhs_words[w]]) for w in range(8))
    proofs = [ext_word(R[w], rhs_words[w], [bit_proof(R[w][p], rhs_words[w][p]) for p in N32]) for w in range(8)]
    out += ['# The transposition, bit by bit.',
            'def ortho_bits(%s) -> {X.ortho(X.Q8{%s}) == X.Q8{%s} : X.Q8}:' % (params, ins, outs),
            '  D.q8_ext(%s, %s, %s)' % (', '.join(word([show(b) for b in R[w]]) for w in range(8)), outs, ', '.join(proofs)), '']
    # SHIFTW
    x = [var('x%d' % p) for p in N32]
    def m(k, w): return wand(const(k), w)
    sw = wor(m(255, x), wor(shr(m(64512, x), 2), wor(shl(m(768, x), 6), wor(shr(m(15728640, x), 4), wor(shl(m(983040, x), 4), wor(shr(m(3221225472, x), 6), shl(m(1056964608, x), 2)))))))
    rw = [one_var(b) for b in sw]
    out += ['def shift_bits(%s) -> {X.shift_word(%s) == %s : U32}:' % (', '.join('+x%d: Bool' % p for p in N32), word([show(b) for b in x]), word([show(b) for b in rw])),
            '  %s' % ext_word(sw, rw, [bit_proof(sw[p], rw[p]) for p in N32]), '']
    # LE32 of four bytes, each 32 bits
    by = [[var('%s%d' % (n, k)) for k in N32] for n in 'abcd']
    le = wor(m(255, by[0]), wor(shl(m(255, by[1]), 8), wor(shl(m(255, by[2]), 16), shl(m(255, by[3]), 24))))
    rl = [one_var(b) for b in le]
    out += ['def le32_bits(%s) -> {F.le32(%s) == %s : U32}:' % (
        ', '.join('+%s%d: Bool' % (n, k) for n in 'abcd' for k in N32), ', '.join(word([show(b) for b in by[i]]) for i in range(4)), word([show(b) for b in rl])),
        '  %s' % ext_word(le, rl, [bit_proof(le[p], rl[p]) for p in N32]), '']
    (OUT / 'words.bend').write_text('\n'.join(out))
    return R, rw, rl


def main():
    OUT.mkdir(parents=True, exist_ok=True)
    defs()
    word_lemmas()



# ---------------------------------------------------------------- byte lemmas

B32 = ['b%d' % i for i in N32]


def circuit_fn(name, out):
    """sf<i>(b0..b7): bit i of the S-box output, by the circuit (x0 = b7)"""
    L = ['def %s(%s) -> Bool:' % (name, ', '.join('+b%d: Bool' % i for i in range(8)))]
    for i in range(8):
        L.append('  +x%d = b%d' % (i, 7 - i))
    for line in CIRC:
        lhs, rhs = [s.strip() for s in line.split('=')]
        a, op, b = rhs.split()
        f = 'Bool.xor' if op == '^' else 'Bool.and'
        if b.startswith('~'):
            b = 'Bool.xor(True{}, %s)' % b[1:]
        L.append('  +%s = %s(%s, %s)' % (lhs, f, a, b))
    L.append('  %s' % out)
    return L


def enum_cases(vs, body='{==}', indent='  '):
    L = [indent + 'match %s:' % ' '.join(vs)]
    for combo in itertools.product(['True{}', 'False{}'], repeat=len(vs)):
        L.append(indent + '  case %s:' % ' '.join(combo))
        L.append(indent + '    ' + body)
    return L


def byte_lemmas():
    out = ['import Base',
           'import ../../../../src/crypto/aes/sbox.bend as SB',
           'import ./defs.bend as D', '',
           '# Generated by tools/generators/aes/bsproof.py.', '']
    for i in range(8):
        out += circuit_fn('sf%d' % i, 's%d' % (7 - i)) + ['']
    bits8 = ['D.bit(x, %dn)' % k for k in range(8)]
    sfx = ['sf%d(%s)' % (i, ', '.join(bits8)) for i in range(8)]
    canon = word(['b%d' % k for k in range(8)] + ['False{}'] * 24)
    full = word(B32)
    sf8 = ['sf%d(%s)' % (i, ', '.join('b%d' % k for k in range(8))) for i in range(8)]
    out += ['# The S-box circuit on one byte is the Boolean circuit sf0..sf7 (all 256 bytes).',
            'def sbox_byte(%s) -> {SB.sbox(%s) == D.byte_of(%s) : U32}:' % (', '.join('+b%d: Bool' % k for k in range(8)), canon, ', '.join(sf8))]
    out += enum_cases(['b%d' % k for k in range(8)])
    out += ['', 'def sbox_word(%s) -> {SB.sbox(%s) == D.byte_of(%s) : U32}:' % (', '.join('+%s: Bool' % b for b in B32), full, ', '.join(sf8)),
            '  Equal.trans(U32, SB.sbox(%s), SB.sbox(%s), D.byte_of(%s), {==}, sbox_byte(%s))' % (full, canon, ', '.join(sf8), ', '.join('b%d' % k for k in range(8))), '',
            'def sbox_ok(+x: U32) -> {SB.sbox(x) == D.byte_of(%s) : U32}:' % ', '.join(sfx),
            '  match x:', '    case %s:' % full, '      sbox_word(%s)' % ', '.join(B32), '']
    for i in range(8):
        out += ['def sbox_bit%d(+x: U32) -> {%s == D.bit(SB.sbox(x), %dn) : Bool}:' % (i, sfx[i], i),
                '  %%Equal.sym(U32, SB.sbox(x), D.byte_of(%s), sbox_ok(x)) : {%s == D.bit(_, %dn) : Bool}' % (', '.join(sfx), sfx[i], i),
                '  {==}', '']
    dbx = ['D.bit(SB.sbox(x), %dn)' % k for k in range(8)]
    out += ['# The S-box output is a byte.',
            'def sbox_canon(+x: U32) -> {D.byte_of(%s) == SB.sbox(x) : U32}:' % ', '.join(dbx),
            '  %%Equal.sym(U32, SB.sbox(x), D.byte_of(%s), sbox_ok(x)) : {D.byte_of(%s) == _ : U32}' % (', '.join(sfx), ', '.join(dbx)),
            '  %%Equal.sym(U32, SB.sbox(x), D.byte_of(%s), sbox_ok(x)) : {D.byte_of(%s) == D.byte_of(%s) : U32}' % (', '.join(sfx), ', '.join('D.bit(_, %dn)' % k for k in range(8)), ', '.join(sfx)),
            '  {==}', '']
    for fname, opc in (('xtime', 'x'), ('mul3', 'm')):
        bx = lambda k: 'b%d' % k
        t8 = ', '.join(op_bit(opc, bx, k) for k in range(8))
        tx = ', '.join(op_bit(opc, lambda k: 'D.bit(x, %dn)' % k, k) for k in range(8))
        out += ['def %s_byte(%s) -> {SB.%s(%s) == D.byte_of(%s) : U32}:' % (fname, ', '.join('+b%d: Bool' % k for k in range(8)), fname, canon, t8)]
        out += enum_cases(['b%d' % k for k in range(8)])
        out += ['', 'def %s_word(%s) -> {SB.%s(%s) == D.byte_of(%s) : U32}:' % (fname, ', '.join('+%s: Bool' % b for b in B32), fname, full, t8),
                '  Equal.trans(U32, SB.%s(%s), SB.%s(%s), D.byte_of(%s), {==}, %s_byte(%s))' % (fname, full, fname, canon, t8, fname, ', '.join('b%d' % k for k in range(8))), '',
                'def %s_ok(+x: U32) -> {SB.%s(x) == D.byte_of(%s) : U32}:' % (fname, fname, tx),
                '  match x:', '    case %s:' % full, '      %s_word(%s)' % (fname, ', '.join(B32)), '']
    for i in range(8):
        X, Y = word(['x%d' % k for k in N32]), word(['y%d' % k for k in N32])
        out += ['def xor_bit%d(+x: U32, +y: U32) -> {Bool.xor(D.bit(x, %dn), D.bit(y, %dn)) == D.bit(U32.xor(x, y), %dn) : Bool}:' % (i, i, i, i),
                '  match x y:', '    case %s %s:' % (X, Y), '      {==}', '']
    (OUT / 'bytes.bend').write_text('\n'.join(out))


# ---------------------------------------------------------------- mix columns

def mix_sym(q):
    def rot8(x):
        return wor(shr(x, 8), shl(x, 24))

    def rot16(x):
        return wor(shl(x, 16), shr(x, 16))
    r = [rot8(x) for x in q]
    a = q
    t7 = wxor(a[7], r[7])
    X = wxor
    return [X(X(t7, r[0]), rot16(X(a[0], r[0]))),
            X(X(X(X(a[0], r[0]), t7), r[1]), rot16(X(a[1], r[1]))),
            X(X(X(a[1], r[1]), r[2]), rot16(X(a[2], r[2]))),
            X(X(X(X(a[2], r[2]), t7), r[3]), rot16(X(a[3], r[3]))),
            X(X(X(X(a[3], r[3]), t7), r[4]), rot16(X(a[4], r[4]))),
            X(X(X(a[4], r[4]), r[5]), rot16(X(a[5], r[5]))),
            X(X(X(a[5], r[5]), r[6]), rot16(X(a[6], r[6]))),
            X(X(X(a[6], r[6]), r[7]), rot16(X(a[7], r[7])))]


ROW_EXPR = ['U32.xor(U32.xor(U32.xor(SB.xtime(u0), SB.mul3(u1)), u2), u3)',
            'U32.xor(U32.xor(U32.xor(u0, SB.xtime(u1)), SB.mul3(u2)), u3)',
            'U32.xor(U32.xor(U32.xor(u0, u1), SB.xtime(u2)), SB.mul3(u3))',
            'U32.xor(U32.xor(U32.xor(SB.mul3(u0), u1), u2), SB.xtime(u3))']
ROW_OPS = [['x', 'm', 'p', 'p'], ['p', 'x', 'm', 'p'], ['p', 'p', 'x', 'm'], ['m', 'p', 'p', 'x']]


def xt_bit(b, k):
    """bit k of xtime of a byte with bits b(0..7) (Bool expression text)"""
    if k == 0:
        return b(7)
    if k in (1, 3, 4):
        return 'Bool.xor(%s, %s)' % (b(k - 1), b(7))
    return b(k - 1)


def m3_bit(b, k):
    return 'Bool.xor(%s, %s)' % (xt_bit(b, k), b(k))


def op_bit(op, b, k):
    return {'x': xt_bit, 'm': m3_bit, 'p': lambda b, k: b(k)}[op](b, k)


def mix_lemmas():
    planes = [[var('D.bit(%s, %dn)' % (byte_name(*pos_byte(p)), i)) for p in N32] for i in range(8)]
    M = mix_sym(planes)
    shapes = {}
    for j in range(8):
        for p in N32:
            blk, col, row = pos_byte(p)
            ren = {}
            for r in range(4):
                for k in range(8):
                    ren['D.bit(%s, %dn)' % (byte_name(blk, col, r), k)] = 'u%d_%d' % (r, k)

            def rn(e):
                if e[0] == 'v':
                    return ('v', ren[e[1]])
                if e[0] == 'c':
                    return e
                return (e[0],) + tuple(rn(x) for x in e[1:])
            g = rn(M[j][p])
            if (row, j) in shapes:
                assert shapes[(row, j)] == g
            shapes[(row, j)] = g
    out = ['import Base',
           'import ../../../../src/crypto/aes/sbox.bend as SB',
           'import ./defs.bend as D',
           'import ./bytes.bend as Y', '',
           '# Generated by tools/generators/aes/bsproof.py.',
           '#',
           '# Bit j of each byte of a MixColumns output column (u0..u3 the input',
           '# rows) as the bitsliced MixColumns computes it: first the Boolean',
           '# identity over the few bits involved (all cases), then the byte-level',
           '# column through xtime / mul3 as bits (bytes.bend) and xor_bit.', '']
    for (row, j), g in sorted(shapes.items()):
        vs = sorted(leaves(g), key=lambda v: (int(v[1]), int(v.split('_')[1])))
        ub = lambda r: (lambda k: 'u%d_%d' % (r, k))
        terms = [op_bit(ROW_OPS[row][r], ub(r), j) for r in range(4)]
        rhs = 'Bool.xor(Bool.xor(Bool.xor(%s, %s), %s), %s)' % tuple(terms)
        name = 'mix%d_%d' % (row, j)
        out += ['def %s_bool(%s) -> {%s == %s : Bool}:' % (name, ', '.join('+%s: Bool' % v for v in vs), show(g), rhs)]
        out += enum_cases(vs)
        # the U32 level
        def dsub(t):
            for r in range(4):
                for k in range(8):
                    t = t.replace('u%d_%d' % (r, k), 'D.bit(u%d, %dn)' % (r, k))
            return t
        L = dsub(show(g))
        ubits = lambda r: (lambda k: 'D.bit(u%d, %dn)' % (r, k))
        bytes_ = []
        for r in range(4):
            op = ROW_OPS[row][r]
            if op == 'p':
                bytes_.append('u%d' % r)
            else:
                bytes_.append('D.byte_of(%s)' % ', '.join(op_bit(op, ubits(r), k) for k in range(8)))
        e1 = 'U32.xor(%s, %s)' % (bytes_[0], bytes_[1])
        e2 = 'U32.xor(%s, u2)' % e1 if row != 2 else None
        # build the chain of xor_bit rewrites: D.bit(xor(xor(xor(A,B),C),D), j)
        A, Bx, C, Dd = bytes_
        x1 = 'U32.xor(%s, %s)' % (A, Bx)
        x2 = 'U32.xor(%s, %s)' % (x1, C)
        x3 = 'U32.xor(%s, %s)' % (x2, Dd)
        RB = lambda t: 'D.bit(%s, %dn)' % (t, j)
        fin = 'Bool.xor(Bool.xor(Bool.xor(%s, %s), %s), %s)' % (RB(A), RB(Bx), RB(C), RB(Dd))
        body = ['def %s(+u0: U32, +u1: U32, +u2: U32, +u3: U32) -> {%s == D.bit(%s, %dn) : Bool}:' % (name, L, ROW_EXPR[row], j)]
        for r in range(4):
            op = ROW_OPS[row][r]
            if op == 'p':
                continue
            f = 'SB.xtime' if op == 'x' else 'SB.mul3'
            lem = 'Y.xtime_ok' if op == 'x' else 'Y.mul3_ok'
            cur = ROW_EXPR[row]
            for r2 in range(4):
                op2 = ROW_OPS[row][r2]
                if r2 < r and op2 != 'p':
                    cur = cur.replace('%s(u%d)' % ('SB.xtime' if op2 == 'x' else 'SB.mul3', r2), bytes_[r2])
            motive = cur.replace('%s(u%d)' % (f, r), '_')
            body.append('  %%Equal.sym(U32, %s(u%d), %s, %s(u%d)) : {%s == D.bit(%s, %dn) : Bool}' % (f, r, bytes_[r], lem, r, L, motive, j))
        body.append('  %%Y.xor_bit%d(%s, %s) : {%s == _ : Bool}' % (j, x2, Dd, L))
        body.append('  %%Y.xor_bit%d(%s, %s) : {%s == Bool.xor(_, %s) : Bool}' % (j, x1, C, L, RB(Dd)))
        body.append('  %%Y.xor_bit%d(%s, %s) : {%s == Bool.xor(Bool.xor(_, %s), %s) : Bool}' % (j, A, Bx, L, RB(C), RB(Dd)))
        body.append('  %s_bool(%s)' % (name, ', '.join('D.bit(u%s, %sn)' % (v[1], v.split('_')[1]) for v in vs)))
        out += [''] + body + ['']
    (OUT / 'mix.bend').write_text('\n'.join(out))
    return M, shapes


def main2():
    byte_lemmas()
    mix_lemmas()



def main_all():
    OUT.mkdir(parents=True, exist_ok=True)
    defs()
    word_lemmas()
    byte_lemmas()
    mix_lemmas()
    import bslayers
    bslayers.layer_lemmas()


if __name__ == '__main__':
    main_all()
