#!/usr/bin/env python3
"""Generate proofs/crypto/aes/fast/ghash.bend: the fast GHASH equals gcm.bend's.

  python3 tools/generators/aes/fastproof.py
"""
from pathlib import Path

ROOT = Path(__file__).resolve().parents[3]
OUT = ROOT / 'proofs/crypto/aes/fast'
B = ['b%d' % i for i in range(16)]
Blk = 'G.Block'


def grp(j):
    return ', '.join(B[4 * j:4 * j + 4])


def ghash_file():
    out = ['import Base',
           'import ../../../../src/crypto/aes/gcm.bend as G',
           'import ../../../../src/crypto/aes/fast.bend as F', '',
           '# Generated by tools/generators/aes/fastproof.py.',
           '#',
           '# The fast GHASH (Algorithm 1 unrolled over 32 bits of X at a time) is',
           '# gcm.bend\'s GHASH: the same masked steps in the same order. The 32-bit',
           '# piece is proved once over an abstract accumulator.', '',
           'def m4(+b0: U32, +b1: U32, +b2: U32, +b3: U32, a: G.Acc) -> G.Acc:',
           '  G.mul_bytes([b0, b1, b2, b3], a)', '',
           'def word_ok(+b0: U32, +b1: U32, +b2: U32, +b3: U32, +a: G.Acc) -> {F.word_mul(b0, b1, b2, b3, a) == m4(b0, b1, b2, b3, a) : G.Acc}:',
           '  match a:', '    case G.Acc{G.B{z0, z1, z2, z3}, G.B{v0, v1, v2, v3}}:', '      {==}', '']
    X = ['x%d' % i for i in range(16)]
    yb = []
    for w in range(4):
        for r in range(4):
            sh = 24 - 8 * r
            e = 'U32.and(255, y%d)' % w if sh == 0 else 'U32.and(255, U32.shrn(y%d, %dn))' % (w, sh)
            yb.append('U32.xor(%s, x%d)' % (e, 4 * w + r))
    g = lambda j: ', '.join(yb[4 * j:4 * j + 4])
    A0 = 'G.Acc{G.zero(), h}'
    mm = [A0]
    for j in range(4):
        mm.append('m4(%s, %s)' % (g(j), mm[-1]))
    wm = lambda j, a: 'F.word_mul(%s, %s)' % (g(j), a)
    rhs = 'G.acc_z(%s)' % mm[4]
    body = ['# One block: (Y xor X) * H.',
            'def absorb_ok(+h: G.Block, +y: G.Block, %s) -> {F.absorb(h, y, %s) == G.absorb(h, y, [%s]) : G.Block}:' % (
                ', '.join('+%s: U32' % x for x in X), ', '.join(X), ', '.join(X)),
            '  match y:', '    case G.B{+y0, +y1, +y2, +y3}:']
    for j in range(4):
        # words 0..j-1 already rewritten to m4 form; rewrite word j
        inner = mm[j]
        motive = '_'
        for k in range(j + 1, 4):
            motive = wm(k, motive)
        body.append('      %%Equal.sym(G.Acc, %s, %s, word_ok(%s, %s)) : {G.acc_z(%s) == %s : G.Block}' % (
            wm(j, inner), mm[j + 1], g(j), inner, motive, rhs))
    body.append('      {==}')
    out += body + ['']
    (OUT / 'ghash.bend').write_text('\n'.join(out))


if __name__ == '__main__':
    OUT.mkdir(parents=True, exist_ok=True)
    ghash_file()

