#!/usr/bin/env python3
"""Generate proofs/crypto/aes/fast/gcm.bend: the fast GCM of fast.bend equals
gcm.bend's GCM-AE / GCM-AD.

  python3 tools/generators/aes/fastgcm.py
"""
from pathlib import Path

ROOT = Path(__file__).resolve().parents[3]
OUT = ROOT / 'proofs/crypto/aes/fast'
LU = 'List<&2, U32>'
X16 = ['x%d' % i for i in range(16)]
X32 = ['x%d' % i for i in range(32)]
OUTPAT = 'F.Out{X.Q8{a0, b0, a1, b1, a2, b2, a3, b3}, T.S{T.W{k0, k1, k2, k3}, T.W{k4, k5, k6, k7}, T.W{k8, k9, k10, k11}, T.W{k12, k13, k14, k15}}}'
S = 'A.Schedule{nr, ks}'
Q = 'q0, q1, q2'
KEYS = 'F.Keys{nr, F.key_planes(ks)}'
NON = 'F.N{F.quad_word(q0), F.quad_word(q1), F.quad_word(q2)}'
X = 'F.Ctx{%s, %s, hh, lens, j0}' % (KEYS, NON)
PW = 'hh'
HWF = '+h: {List.length(&2, T.State, ks) == 2n+Nat.sub(nr, 1n) : Nat}'
COMMON = '+nr: Nat, +ks: List<&2, T.State>, %s, +q0: T.Quad, +q1: T.Quad, +q2: T.Quad' % HWF
COMMON_ARGS = 'nr, ks, h, q0, q1, q2'
CTXP = '+hh: G.Block, +lens: %s, +j0: %s' % (LU, LU)


def L(v):
    return '[%s]' % ', '.join(v)


def cons(items, tail):
    return ' <> '.join(list(items) + [tail])


def KS(c):
    return 'G.keystream(%s, %s, %s)' % (S, Q, c)


def ks_byte(t):
    w = ['a0', 'a1', 'a2', 'a3', 'b0', 'b1', 'b2', 'b3'][t // 4]
    r = t % 4
    e = 'U32.and(255, %s)' % w if r == 0 else 'U32.and(255, U32.shrn(%s, %dn))' % (w, 8 * r)
    return 'U32.xor(%s, k%d)' % (e, t % 16)


STREAM = L([ks_byte(t) for t in range(32)])
Z0 = 'T.S{T.W{0, 0, 0, 0}, T.W{0, 0, 0, 0}, T.W{0, 0, 0, 0}, T.W{0, 0, 0, 0}}'
ST_A = 'T.S{T.W{s0, s1, s2, s3}, T.W{s4, s5, s6, s7}, T.W{s8, s9, s10, s11}, T.W{s12, s13, s14, s15}}'
ST_B = ST_A.replace('s', 'u').replace('T.Su', 'T.S')
ST_B = 'T.S{T.W{u0, u1, u2, u3}, T.W{u4, u5, u6, u7}, T.W{u8, u9, u10, u11}, T.W{u12, u13, u14, u15}}'


def head():
    return ['import Base',
            'import ../../../lib/nat.bend as N',
            'import ../../../lib/logic.bend as LG',
            'import ../../../../src/crypto/aes/types.bend as T',
            'import ../../../../src/crypto/aes/aes.bend as A',
            'import ../../../../src/crypto/aes/bitslice.bend as X',
            'import ../../../../src/crypto/aes/gcm.bend as G',
            'import ../../../../src/crypto/aes/fast.bend as F',
            'import ../../../../src/crypto/subtle.bend as Subtle',
            'import ../bs/cipher.bend as C',
            'import ./ghash.bend as H', '',
            '# Generated by tools/generators/aes/fastgcm.py.',
            '#',
            '# The fast GCM of fast.bend (two counter blocks per bitsliced encryption,',
            '# encryption and GHASH in one pass over the message) equals gcm.bend\'s',
            '# GCM-AE and GCM-AD for every well-formed key schedule, nonce, AAD and',
            '# message.', '']


def ghash_list():
    out = ['# GHASH over a byte list (a last partial block padded with zeros).',
           'def ghash_ok(+h: G.Block, +xs: %s, +y: G.Block) -> {F.ghash(h, xs, y) == G.ghash(h, xs, y) : G.Block}:' % LU,
           '  match xs:',
           '    case %s:' % cons(X16, 'rest'),
           '      %%Equal.sym(G.Block, F.absorb(h, y, %s), G.absorb(h, y, %s), H.absorb_ok(h, y, %s)) : {F.ghash(h, rest, _) == G.ghash(h, rest, G.absorb(h, y, %s)) : G.Block}' % (
               ', '.join(X16), L(X16), ', '.join(X16), L(X16)),
           '      ghash_ok(h, rest, G.absorb(h, y, %s))' % L(X16),
           '    case Nil{}:', '      {==}']
    for k in range(1, 16):
        full = X16[:k] + ['0'] * (16 - k)
        out += ['    case %s:' % cons(X16[:k], 'Nil{}'), '      H.absorb_ok(h, y, %s)' % ', '.join(full)]
    return out + ['']


def small():
    out = []
    # the keystream of two counters
    out += ['# Two counter blocks: the keystreams of counters c and c + 1.',
            'def ctr_ok(%s, +c: U32) -> {F.stream(F.ctr2(%s, %s, c)) == List.append(&2, U32, %s, %s) : %s}:' % (
                COMMON, KEYS, NON, KS('c'), KS('U32.inc(c)'), LU),
            '  C.encrypt2_ok(nr, ks, h, q0, q1, q2, T.W{U32.and(255, U32.shrn(c, 24n)), U32.and(255, U32.shrn(c, 16n)), U32.and(255, U32.shrn(c, 8n)), U32.and(255, c)}, q0, q1, q2, T.W{U32.and(255, U32.shrn(U32.inc(c), 24n)), U32.and(255, U32.shrn(U32.inc(c), 16n)), U32.and(255, U32.shrn(U32.inc(c), 8n)), U32.and(255, U32.inc(c))})', '']
    # hash key
    out += ['def hk_state(+sa: T.State, +sb: T.State) -> {F.hash_key(List.append(&2, U32, A.bytes_of(sa), A.bytes_of(sb))) == G.pack(sa) : G.Block}:',
            '  match sa sb:', '    case %s %s:' % (ST_A, ST_B), '      {==}', '',
            '# H = E(K, 0).',
            'def hk_ok(+nr: Nat, +ks: List<&2, T.State>, %s) -> {F.hash_key(F.stream(F.encrypt2(%s, 0, 0, 0, 0, 0, 0, 0, 0))) == G.hash_key(%s) : G.Block}:' % (HWF, KEYS, S),
            '  %%Equal.sym(%s, F.stream(F.encrypt2(%s, 0, 0, 0, 0, 0, 0, 0, 0)), List.append(&2, U32, A.bytes_of(A.cipher(nr, %s, ks)), A.bytes_of(A.cipher(nr, %s, ks))), C.encrypt2_ok(nr, ks, h, T.W{0, 0, 0, 0}, T.W{0, 0, 0, 0}, T.W{0, 0, 0, 0}, T.W{0, 0, 0, 0}, T.W{0, 0, 0, 0}, T.W{0, 0, 0, 0}, T.W{0, 0, 0, 0}, T.W{0, 0, 0, 0})) : {F.hash_key(_) == G.hash_key(%s) : G.Block}' % (LU, KEYS, Z0, Z0, S),
            '  hk_state(A.cipher(nr, T.S{T.W{0, 0, 0, 0}, T.W{0, 0, 0, 0}, T.W{0, 0, 0, 0}, T.W{0, 0, 0, 0}}, ks), A.cipher(nr, T.S{T.W{0, 0, 0, 0}, T.W{0, 0, 0, 0}, T.W{0, 0, 0, 0}, T.W{0, 0, 0, 0}}, ks))', '']
    # lengths
    out += ['def len_append(+xs: %s, +ys: %s) -> {List.length(&2, U32, List.append(&2, U32, xs, ys)) == Nat.add(List.length(&2, U32, xs), List.length(&2, U32, ys)) : Nat}:' % (LU, LU),
            '  match xs:', '    case Nil{}:', '      {==}', '    case x <> rest:',
            '      N.succ_cong(List.length(&2, U32, List.append(&2, U32, rest, ys)), Nat.add(List.length(&2, U32, rest), List.length(&2, U32, ys)), len_append(rest, ys))', '']
    out += ['def len16(%s, +st: T.State) -> {List.length(&2, U32, G.xor_bytes(%s, A.bytes_of(st))) == 16n : Nat}:' % (', '.join('+%s: U32' % x for x in X16), L(X16)),
            '  match st:', '    case %s:' % ST_A, '      {==}', '']
    for k in range(1, 16):
        out += ['def lenp%d(%s, +st: T.State) -> {List.length(&2, U32, G.xor_bytes(%s, A.bytes_of(st))) == %dn : Nat}:' % (k, ', '.join('+%s: U32' % x for x in X16[:k]), L(X16[:k]), k),
                '  match st:', '    case %s:' % ST_A, '      {==}', '']
    gc = lambda xs, c: 'G.gctr(%s, %s, %s, %s)' % (S, xs, Q, c)
    out += ['# Counter mode keeps the length.',
            'def gctr_len(+nr: Nat, +ks: List<&2, T.State>, +q0: T.Quad, +q1: T.Quad, +q2: T.Quad, +xs: %s, +c: U32) -> {List.length(&2, U32, %s) == List.length(&2, U32, xs) : Nat}:' % (LU, gc('xs', 'c')),
            '  match xs:',
            '    case %s:' % cons(X16, 'rest'),
            '      %%Equal.sym(Nat, List.length(&2, U32, List.append(&2, U32, G.xor_bytes(%s, %s), %s)), Nat.add(List.length(&2, U32, G.xor_bytes(%s, %s)), List.length(&2, U32, %s)), len_append(G.xor_bytes(%s, %s), %s)) : {_ == List.length(&2, U32, %s) : Nat}' % (
                L(X16), KS('c'), gc('rest', 'U32.inc(c)'), L(X16), KS('c'), gc('rest', 'U32.inc(c)'), L(X16), KS('c'), gc('rest', 'U32.inc(c)'), cons(X16, 'rest')),
            '      %%Equal.sym(Nat, List.length(&2, U32, G.xor_bytes(%s, %s)), 16n, len16(%s, A.encrypt_state(%s, G.counter(%s, c)))) : {Nat.add(_, List.length(&2, U32, %s)) == List.length(&2, U32, %s) : Nat}' % (
                L(X16), KS('c'), ', '.join(X16), S, Q, gc('rest', 'U32.inc(c)'), cons(X16, 'rest')),
            '      %%Equal.sym(Nat, List.length(&2, U32, %s), List.length(&2, U32, rest), gctr_len(nr, ks, q0, q1, q2, rest, U32.inc(c))) : {Nat.add(16n, _) == List.length(&2, U32, %s) : Nat}' % (gc('rest', 'U32.inc(c)'), cons(X16, 'rest')),
            '      {==}',
            '    case Nil{}:', '      {==}']
    for k in range(1, 16):
        out += ['    case %s:' % cons(X16[:k], 'Nil{}'),
                '      lenp%d(%s, A.encrypt_state(%s, G.counter(%s, c)))' % (k, ', '.join(X16[:k]), S, Q)]
    out += ['']
    return out


def xor_lemmas():
    out = []
    ba, bb = 'A.bytes_of(sa)', 'A.bytes_of(sb)'
    out += ['# 32 bytes: the two keystream blocks, as one xor.',
            'def og32(%s, +r: %s, +sa: T.State, +sb: T.State) -> {List.append(&2, U32, G.xor_bytes(%s, %s), List.append(&2, U32, G.xor_bytes(%s, %s), r)) == F.xor_into(%s, List.append(&2, U32, %s, %s), r) : %s}:' % (
                ', '.join('+%s: U32' % x for x in X32), LU, L(X32[:16]), ba, L(X32[16:]), bb, L(X32), ba, bb, LU),
            '  match sa sb:', '    case %s %s:' % (ST_A, ST_B), '      {==}', '']
    for k in range(1, 32):
        xs = X32[:k]
        if k < 16:
            lhs = 'G.xor_bytes(%s, %s)' % (L(xs), ba)
        else:
            lhs = 'List.append(&2, U32, G.xor_bytes(%s, %s), G.xor_bytes(%s, %s))' % (L(X32[:16]), ba, L(X32[16:k]), bb)
        out += ['def short%d(%s, +sa: T.State, +sb: T.State) -> {%s == F.xor_into(%s, List.append(&2, U32, %s, %s), Nil{}) : %s}:' % (
                    k, ', '.join('+%s: U32' % x for x in xs), lhs, L(xs), ba, bb, LU),
                '  match sa sb:', '    case %s %s:' % (ST_A, ST_B), '      {==}', '']
    return out


def st(c):
    return 'A.encrypt_state(%s, G.counter(%s, %s))' % (S, Q, c)


ARGS = 'nr, ks, q0, q1, q2'
XARGS = 'nr, ks, q0, q1, q2, hh, lens, j0'
HELP_T = '+nr: Nat, +ks: List<&2, T.State>, +q0: T.Quad, +q1: T.Quad, +q2: T.Quad'
XHELP_T = HELP_T + ', ' + CTXP


def helpers():
    return ['# Shorthands (they unfold to the terms of fast.bend and gcm.bend).',
            'def ks2(%s, +c: U32) -> %s:' % (HELP_T, LU), '  List.append(&2, U32, %s, %s)' % (KS('c'), KS('U32.inc(c)')), '',
            'def gc(%s, +xs: %s, +c: U32) -> %s:' % (HELP_T, LU, LU), '  G.gctr(%s, xs, %s, c)' % (S, Q), '',
            'def xc(%s) -> F.Ctx:' % XHELP_T, '  %s' % X, '',
            'def fin(%s, +ct: %s, +y: G.Block) -> %s:' % (XHELP_T, LU, LU), '  F.finish(xc(%s), F.ghash(hh, ct, y))' % XARGS, '']


def GCx(xs, c):
    return 'gc(%s, %s, %s)' % (ARGS, xs, c)


def FINx(ct, y):
    return 'fin(%s, %s, %s)' % (XARGS, ct, y)


HOX = '+ho: {F.stream(o) == ks2(%s, c) : %s}' % (ARGS, LU)


def seal_body():
    cc = 'U32.inc(U32.inc(c))'
    out = ['# The last bytes of a message (fewer than 32).',
           'def seal_tail_ok(%s, %s, +l: %s, +c: U32, +y: G.Block, +o: F.Out, %s, +hl: {Nat.is_lt(List.length(&2, U32, l), 32n) == True{} : Bool}) -> {F.seal_tail(xc(%s), F.xor_into(l, F.stream(o), Nil{}), y) == List.append(&2, U32, %s, %s) : %s}:' % (
               COMMON, CTXP, LU, HOX, XARGS, GCx('l', 'c'), FINx(GCx('l', 'c'), 'y'), LU),
           '  %%Equal.sym(%s, %s, F.xor_into(l, ks2(%s, c), Nil{}), short_gctr(%s, l, c, hl)) : {F.seal_tail(xc(%s), F.xor_into(l, F.stream(o), Nil{}), y) == List.append(&2, U32, _, %s) : %s}' % (
               LU, GCx('l', 'c'), ARGS, COMMON_ARGS, XARGS, FINx('_', 'y'), LU),
           '  %%ho : {F.seal_tail(xc(%s), F.xor_into(l, F.stream(o), Nil{}), y) == List.append(&2, U32, F.xor_into(l, _, Nil{}), %s) : %s}' % (
               XARGS, FINx('F.xor_into(l, _, Nil{})', 'y'), LU),
           '  {==}', '']
    goal = lambda xs: '{F.seal_body(xc(%s), %s, c, y, o) == List.append(&2, U32, %s, %s) : %s}' % (XARGS, xs, GCx(xs, 'c'), FINx(GCx(xs, 'c'), 'y'), LU)
    out += ['# The one-pass loop: ciphertext of the rest, then the tag.',
            'def seal_body_ok(%s, %s, +xs: %s, +c: U32, +y: G.Block, +o: F.Out, %s) -> %s:' % (COMMON, CTXP, LU, HOX, goal('xs')),
            '  match xs:']
    R = GCx('rest', cc)
    xin = lambda K, r: 'F.xor_into(%s, %s, %s)' % (L(X32), K, r)
    E = ['U32.xor(%s, %s)' % (X32[t], ks_byte(t)) for t in range(32)]
    y2 = 'F.absorb(hh, F.absorb(hh, y, %s), %s)' % (', '.join(E[:16]), ', '.join(E[16:]))
    old_ct = 'List.append(&2, U32, G.xor_bytes(%s, %s), List.append(&2, U32, G.xor_bytes(%s, %s), %s))' % (L(X32[:16]), KS('c'), L(X32[16:]), KS('U32.inc(c)'), R)
    lhs_goal = 'F.seal_body(xc(%s), %s, c, y, %s)' % (XARGS, cons(X32, 'rest'), OUTPAT)
    SO = 'F.stream(%s)' % OUTPAT
    ih = 'seal_body_ok(%s, hh, lens, j0, rest, %s, %s, F.ctr2(%s, %s, %s), ctr_ok(%s, %s))' % (COMMON_ARGS, cc, y2, KEYS, NON, cc, COMMON_ARGS, cc)
    ih_l = 'F.seal_body(xc(%s), rest, %s, %s, F.ctr2(%s, %s, %s))' % (XARGS, cc, y2, KEYS, NON, cc)
    ih_r = 'List.append(&2, U32, %s, %s)' % (R, FINx(R, y2))
    out += ['    case %s:' % cons(X32, 'rest'),
            '      match o:', '        case %s:' % OUTPAT,
            '          %%Equal.sym(%s, %s, %s, og32(%s, %s, %s, %s)) : {%s == List.append(&2, U32, _, %s) : %s}' % (
                LU, old_ct, xin('ks2(%s, c)' % ARGS, R), ', '.join(X32), R, st('c'), st('U32.inc(c)'), lhs_goal, FINx('_', 'y'), LU),
            '          %%ho : {%s == List.append(&2, U32, %s, %s) : %s}' % (lhs_goal, xin('_', R), FINx(xin('_', R), 'y'), LU),
            '          %%Equal.sym(%s, %s, %s, %s) : {%s == %s : %s}' % (LU, ih_l, ih_r, ih, xin(SO, '_'), xin(SO, ih_r), LU),
            '          {==}',
            '    case Nil{}:', '      {==}']
    for k in range(1, 32):
        xs = cons(X32[:k], 'Nil{}')
        out += ['    case %s:' % xs, '      seal_tail_ok(%s, hh, lens, j0, %s, c, y, o, ho, {==})' % (COMMON_ARGS, xs)]
    return out + ['']


def main():
    OUT.mkdir(parents=True, exist_ok=True)
    out = head() + ghash_list() + small() + xor_lemmas() + seal_body()
    (OUT / 'gcm.bend').write_text('\n'.join(out))


if __name__ == '__main__':
    main()


HK = 'F.hash_key(F.stream(F.encrypt2(%s, 0, 0, 0, 0, 0, 0, 0, 0)))' % KEYS
J0 = 'List.take(&2, U32, F.stream(F.ctr2(%s, %s, 1)), 16n)' % (KEYS, NON)
HS = 'G.hash_key(%s)' % S


def ctx(hh, lens, j0):
    return 'F.Ctx{%s, %s, %s, %s, %s}' % (KEYS, NON, hh, lens, j0)


def tag_lemmas():
    out = []
    out += ['def gctr16(+nr: Nat, +ks: List<&2, T.State>, +q0: T.Quad, +q1: T.Quad, +q2: T.Quad, +y: G.Block) -> {G.gctr(%s, G.unpack(y), %s, 1) == List.append(&2, U32, G.xor_bytes(G.unpack(y), %s), G.xor_bytes(Nil{}, %s)) : %s}:' % (S, Q, KS('1'), KS('U32.inc(1)'), LU),
            '  match y:', '    case G.B{y0, y1, y2, y3}:', '      {==}', '',
            'def tagx(+y: G.Block, +sa: T.State, +sb: T.State) -> {F.xor_into(G.unpack(y), List.take(&2, U32, List.append(&2, U32, A.bytes_of(sa), A.bytes_of(sb)), 16n), Nil{}) == List.append(&2, U32, G.xor_bytes(G.unpack(y), A.bytes_of(sa)), G.xor_bytes(Nil{}, A.bytes_of(sb))) : %s}:' % LU,
            '  match y sa sb:', '    case G.B{y0, y1, y2, y3} %s %s:' % (ST_A, ST_B), '      {==}', '']
    # the tag
    Y1f = 'F.ghash(%s, aad, G.zero())'
    Y2f = 'F.ghash(%s, c, %s)'
    Y1 = lambda h: 'F.ghash(%s, aad, G.zero())' % h
    Y1g = 'G.ghash(%s, aad, G.zero())' % HS
    Y2 = lambda h, y1: 'F.ghash(%s, c, %s)' % (h, y1)
    Y2g = 'G.ghash(%s, c, %s)' % (HS, Y1g)
    lensF = 'F.lengths(aad, mm)'
    lensG = 'G.lengths(aad, c)'
    fin = lambda h, lens, j0, y: 'F.xor_into(G.unpack(F.ghash(%s, %s, %s)), %s, Nil{})' % (h, lens, y, j0)
    RHS = 'G.tag(%s, %s, aad, c)' % (S, Q)
    Yfin = 'G.ghash(%s, %s, %s)' % (HS, lensG, Y2g)
    out += ['# The tag: GHASH of A, C and their lengths under H = E(K, 0), xor E(K, J0).',
            'def tag_ok(%s, +aad: %s, +c: %s, +mm: Nat, +hl: {List.length(&2, U32, c) == mm : Nat}) -> {F.finish(%s, %s) == %s : %s}:' % (
                COMMON, LU, LU, ctx(HK, lensF, J0), Y2(HK, Y1(HK)), RHS, LU),
            '  %%Equal.sym(G.Block, %s, %s, hk_ok(nr, ks, h)) : {%s == %s : %s}' % (HK, HS, fin('_', lensF, J0, Y2('_', Y1('_'))), RHS, LU),
            '  %%Equal.sym(G.Block, %s, %s, ghash_ok(%s, aad, G.zero())) : {%s == %s : %s}' % (Y1(HS), Y1g, HS, fin(HS, lensF, J0, Y2(HS, '_')), RHS, LU),
            '  %%Equal.sym(G.Block, %s, %s, ghash_ok(%s, c, %s)) : {%s == %s : %s}' % (Y2(HS, Y1g), Y2g, HS, Y1g, fin(HS, lensF, J0, '_'), RHS, LU),
            '  %%hl : {%s == %s : %s}' % (fin(HS, 'F.lengths(aad, _)', J0, Y2g), RHS, LU),
            '  %%Equal.sym(G.Block, F.ghash(%s, %s, %s), %s, ghash_ok(%s, %s, %s)) : {F.xor_into(G.unpack(_), %s, Nil{}) == %s : %s}' % (
                HS, lensG, Y2g, Yfin, HS, lensG, Y2g, J0, RHS, LU),
            '  %%Equal.sym(%s, F.stream(F.ctr2(%s, %s, 1)), List.append(&2, U32, %s, %s), ctr_ok(%s, 1)) : {F.xor_into(G.unpack(%s), List.take(&2, U32, _, 16n), Nil{}) == %s : %s}' % (
                LU, KEYS, NON, KS('1'), KS('U32.inc(1)'), COMMON_ARGS, Yfin, RHS, LU),
            '  Equal.trans(%s, F.xor_into(G.unpack(%s), List.take(&2, U32, List.append(&2, U32, %s, %s), 16n), Nil{}), List.append(&2, U32, G.xor_bytes(G.unpack(%s), %s), G.xor_bytes(Nil{}, %s)), %s,' % (
                LU, Yfin, KS('1'), KS('U32.inc(1)'), Yfin, KS('1'), KS('U32.inc(1)'), RHS),
            '    tagx(%s, %s, %s),' % (Yfin, st('1'), st('U32.inc(1)')),
            '    Equal.sym(%s, %s, List.append(&2, U32, G.xor_bytes(G.unpack(%s), %s), G.xor_bytes(Nil{}, %s)), gctr16(nr, ks, q0, q1, q2, %s)))' % (
                LU, RHS, Yfin, KS('1'), KS('U32.inc(1)'), Yfin), '']
    # seal
    C_ = 'G.gctr(%s, pt, %s, 2)' % (S, Q)
    X0 = ctx(HK, 'F.lengths(aad, List.length(&2, U32, pt))', J0)
    sbo = 'seal_body_ok(%s, %s, F.lengths(aad, List.length(&2, U32, pt)), %s, pt, 2, %s, F.ctr2(%s, %s, 2), ctr_ok(%s, 2))' % (
        COMMON_ARGS, HK, J0, Y1(HK), KEYS, NON, COMMON_ARGS)
    fin_new = 'F.finish(%s, F.ghash(%s, %s, %s))' % (X0, HK, C_, Y1(HK))
    out += ['# GCM-AE.',
            'def seal_ok(%s, +aad: %s, +pt: %s) -> {F.seal(%s, %s, aad, pt) == G.seal_core(%s, %s, aad, pt) : %s}:' % (COMMON, LU, LU, KEYS, NON, S, Q, LU),
            '  Equal.trans(%s, F.seal(%s, %s, aad, pt), List.append(&2, U32, %s, %s), G.seal_core(%s, %s, aad, pt), %s,' % (LU, KEYS, NON, C_, fin_new, S, Q, sbo),
            '    Equal.cong(%s, %s, t => List.append(&2, U32, %s, t), %s, G.tag(%s, %s, aad, %s),' % (LU, LU, C_, fin_new, S, Q, C_),
            '      tag_ok(%s, aad, %s, List.length(&2, U32, pt), gctr_len(nr, ks, q0, q1, q2, pt, 2))))' % (COMMON_ARGS, C_), '']
    return out


def open_short():
    out = []
    gc = lambda xs, c: 'G.gctr(%s, %s, %s, %s)' % (S, xs, Q, c)
    KK = 'List.append(&2, U32, %s, %s)' % (KS('c'), KS('U32.inc(c)'))
    # any short list
    out += ['# Counter mode on fewer than 32 bytes: one xor with both keystream blocks.',
            'def short_gctr(%s, +l: %s, +c: U32, +hl: {Nat.is_lt(List.length(&2, U32, l), 32n) == True{} : Bool}) -> {%s == F.xor_into(l, %s, Nil{}) : %s}:' % (COMMON, LU, gc('l', 'c'), KK, LU),
            '  match l:', '    case Nil{}:', '      {==}']
    for k in range(1, 32):
        xs = X32[:k]
        out += ['    case %s:' % cons(xs, 'Nil{}'), '      short%d(%s, %s, %s)' % (k, ', '.join(xs), st('c'), st('U32.inc(c)'))]
    out += ['    case %s:' % cons(X32, 'rest'),
            '      Empty.absurd({%s == F.xor_into(%s, %s, Nil{}) : %s}, N.lt_zero_absurd(List.length(&2, U32, rest), hl))' % (gc(cons(X32, 'rest'), 'c'), cons(X32, 'rest'), KK, LU), '']
    out += ['def take_le(+xs: %s, +k: Nat) -> {Nat.is_le(List.length(&2, U32, List.take(&2, U32, xs, k)), k) == True{} : Bool}:' % LU,
            '  match xs k:', '    case Nil{} _:', '      N.zero_le(k)', '    case x <> t 0n:', '      {==}', '    case x <> t 1n+p:', '      take_le(t, p)', '',
            'def take_len(+xs: %s, +k: Nat, +hk: {Nat.is_le(k, List.length(&2, U32, xs)) == True{} : Bool}) -> {List.length(&2, U32, List.take(&2, U32, xs, k)) == k : Nat}:' % LU,
            '  match xs k:', '    case Nil{} 0n:', '      {==}',
            '    case Nil{} 1n+p:', '      Empty.absurd({0n == 1n+p : Nat}, LG.false_true(hk))',
            '    case x <> t 0n:', '      {==}',
            '    case x <> t 1n+p:', '      N.succ_cong(List.length(&2, U32, List.take(&2, U32, t, p)), p, take_len(t, p, hk))', '']
    return out


def open_lemmas():
    out = []
    out += ['# The last bytes of the ciphertext (fewer than 32) and the tag.',
            'def open_tail_ok(%s, %s, +l: %s, +t: %s, +c: U32, +y: G.Block, +o: F.Out, %s, +hl: {Nat.is_lt(List.length(&2, U32, l), 32n) == True{} : Bool}) -> {F.open_tail(xc(%s), l, t, y, o) == F.Opened{%s, Subtle.eq(t, %s)} : F.Opened}:' % (
                COMMON, CTXP, LU, LU, HOX, XARGS, GCx('l', 'c'), FINx('l', 'y')),
            '  %%Equal.sym(%s, %s, F.xor_into(l, ks2(%s, c), Nil{}), short_gctr(%s, l, c, hl)) : {F.open_tail(xc(%s), l, t, y, o) == F.Opened{_, Subtle.eq(t, %s)} : F.Opened}' % (
                LU, GCx('l', 'c'), ARGS, COMMON_ARGS, XARGS, FINx('l', 'y')),
            '  %%ho : {F.open_tail(xc(%s), l, t, y, o) == F.Opened{F.xor_into(l, _, Nil{}), Subtle.eq(t, %s)} : F.Opened}' % (XARGS, FINx('l', 'y')),
            '  {==}', '']
    rhs = lambda xs, m: 'F.Opened{%s, Subtle.eq(List.drop(&2, U32, %s, %s), %s)}' % (GCx('List.take(&2, U32, %s, %s)' % (xs, m), 'c'), xs, m, FINx('List.take(&2, U32, %s, %s)' % (xs, m), 'y'))
    out += ['# The one-pass loop of decryption.',
            'def open_body_ok(%s, %s, +m: Nat, +xs: %s, +c: U32, +y: G.Block, +o: F.Out, %s) -> {F.open_body(xc(%s), m, xs, c, y, o) == %s : F.Opened}:' % (
                COMMON, CTXP, LU, HOX, XARGS, rhs('xs', 'm')),
            '  match m xs:']
    for k in range(32):
        tk = 'List.take(&2, U32, xs, %dn)' % k
        hl = 'N.le_lt_trans(List.length(&2, U32, %s), %dn, 32n, take_le(xs, %dn), {==})' % (tk, k, k)
        out += ['    case %dn _:' % k,
                '      open_tail_ok(%s, hh, lens, j0, %s, List.drop(&2, U32, xs, %dn), c, y, o, ho, %s)' % (COMMON_ARGS, tk, k, hl)]
    for k in range(32):
        l = cons(X32[:k], 'Nil{}')
        out += ['    case 32n+p %s:' % l,
                '      open_tail_ok(%s, hh, lens, j0, %s, Nil{}, c, y, o, ho, {==})' % (COMMON_ARGS, l)]
    cc = 'U32.inc(U32.inc(c))'
    tr = 'List.take(&2, U32, rest, p)'
    R = GCx(tr, cc)
    E = ['U32.xor(%s, %s)' % (X32[t], ks_byte(t)) for t in range(32)]
    y2 = 'F.absorb(hh, F.absorb(hh, y, %s), %s)' % (', '.join(X32[:16]), ', '.join(X32[16:]))
    old_ct = 'List.append(&2, U32, G.xor_bytes(%s, %s), List.append(&2, U32, G.xor_bytes(%s, %s), %s))' % (L(X32[:16]), KS('c'), L(X32[16:]), KS('U32.inc(c)'), R)
    xin = lambda K: 'F.xor_into(%s, %s, %s)' % (L(X32), K, R)
    xs_full = cons(X32, 'rest')
    g = 'F.open_body(xc(%s), 32n+p, %s, c, y, %s)' % (XARGS, xs_full, OUTPAT)
    tail_eq = 'Subtle.eq(List.drop(&2, U32, rest, p), %s)' % FINx(tr, y2)
    ih = 'open_body_ok(%s, hh, lens, j0, p, rest, %s, %s, F.ctr2(%s, %s, %s), ctr_ok(%s, %s))' % (COMMON_ARGS, cc, y2, KEYS, NON, cc, COMMON_ARGS, cc)
    ih_l = 'F.open_body(xc(%s), p, rest, %s, %s, F.ctr2(%s, %s, %s))' % (XARGS, cc, y2, KEYS, NON, cc)
    ih_r = 'F.Opened{%s, %s}' % (R, tail_eq)
    out += ['    case 32n+p %s:' % xs_full,
            '      match o:', '        case %s:' % OUTPAT,
            '          %%Equal.sym(%s, %s, %s, og32(%s, %s, %s, %s)) : {%s == F.Opened{_, %s} : F.Opened}' % (
                LU, old_ct, xin('ks2(%s, c)' % ARGS), ', '.join(X32), R, st('c'), st('U32.inc(c)'), g, tail_eq),
            '          %%ho : {%s == F.Opened{%s, %s} : F.Opened}' % (g, xin('_'), tail_eq),
            '          %%Equal.sym(F.Opened, %s, %s, %s) : {F.prepend32(%s, _) == F.Opened{%s, %s} : F.Opened}' % (
                ih_l, ih_r, ih, ', '.join(E), xin('F.stream(%s)' % OUTPAT), tail_eq),
            '          {==}', '']
    return out


def main_all():
    OUT.mkdir(parents=True, exist_ok=True)
    out = head() + ghash_list() + small() + xor_lemmas() + seal_body() + tag_lemmas() + open_lemmas()
    (OUT / 'gcm.bend').write_text('\n'.join(out))


if __name__ == '__main__':
    main_all()


def top_lemmas():
    out = []
    M = 'Maybe<&2, List<&2, U32>>'
    m = 'Nat.sub(List.length(&2, U32, input), 16n)'
    tk = 'List.take(&2, U32, input, %s)' % m
    dr = 'List.drop(&2, U32, input, %s)' % m
    Y1 = 'F.ghash(%s, aad, G.zero())' % HK
    X1 = ctx(HK, 'F.lengths(aad, %s)' % m, J0)
    obo = 'open_body_ok(%s, %s, F.lengths(aad, %s), %s, %s, input, 2, %s, F.ctr2(%s, %s, 2), ctr_ok(%s, 2))' % (
        COMMON_ARGS, HK, m, J0, m, Y1, KEYS, NON, COMMON_ARGS)
    fin = 'F.finish(%s, F.ghash(%s, %s, %s))' % (X1, HK, tk, Y1)
    gct = 'G.gctr(%s, %s, %s, 2)' % (S, tk, Q)
    tag = 'G.tag(%s, %s, aad, %s)' % (S, Q, tk)
    out += ['def sub_le(+a: Nat, +b: Nat) -> {Nat.is_le(Nat.sub(a, b), a) == True{} : Bool}:',
            '  match a b:', '    case 0n _:', '      {==}', '    case 1n+p 0n:', '      N.le_refl(1n+p)',
            '    case 1n+p 1n+q:', '      N.le_trans(Nat.sub(p, q), p, 1n+p, sub_le(p, q), N.le_succ(p))', '',
            'def split_ok(%s, +aad: %s, +input: %s, +short: Bool) -> {F.open_split(%s, %s, aad, input, %s, short) == G.open_split(%s, %s, aad, input, List.length(&2, U32, input), short) : %s}:' % (
                COMMON, LU, LU, KEYS, NON, m, S, Q, M),
            '  match short:', '    case True{}:', '      {==}', '    case False{}:',
            '      Equal.trans(%s, F.accept(F.open_body(%s, %s, input, 2, %s, F.ctr2(%s, %s, 2))), F.accept(F.Opened{%s, Subtle.eq(%s, %s)}), G.accept(Subtle.eq(%s, %s), %s),' % (
                M, X1, m, Y1, KEYS, NON, gct, dr, fin, dr, tag, gct),
            '        Equal.cong(F.Opened, %s, F.accept, F.open_body(%s, %s, input, 2, %s, F.ctr2(%s, %s, 2)), F.Opened{%s, Subtle.eq(%s, %s)}, %s),' % (
                M, X1, m, Y1, KEYS, NON, gct, dr, fin, obo),
            '        Equal.cong(%s, %s, t => G.accept(Subtle.eq(%s, t), %s), %s, %s, tag_ok(%s, aad, %s, %s, take_len(input, %s, sub_le(List.length(&2, U32, input), 16n)))))' % (
                LU, M, dr, gct, fin, tag, COMMON_ARGS, tk, m, m), '',
            '# GCM-AD.',
            'def open_ok(%s, +aad: %s, +input: %s) -> {F.open(%s, %s, aad, input) == G.open_core(%s, %s, aad, input) : %s}:' % (COMMON, LU, LU, KEYS, NON, S, Q, M),
            '  split_ok(%s, aad, input, Nat.is_lt(List.length(&2, U32, input), 16n))' % COMMON_ARGS, '']
    # nonce level
    NB = ['n%d' % i for i in range(13)]
    QN = 'T.W{n0, n1, n2, n3}, T.W{n4, n5, n6, n7}, T.W{n8, n9, n10, n11}'
    for kind, fn, gn, last, lem in (('seal', 'F.seal_nonce', 'G.seal_nonce', 'pt', 'seal_ok'), ('open', 'F.open_nonce', 'G.open_nonce', 'input', 'open_ok')):
        out += ['def %s_nonce_ok(+nr: Nat, +ks: List<&2, T.State>, %s, +nonce: %s, +aad: %s, +%s: %s) -> {%s(%s, nonce, aad, %s) == %s(%s, nonce, aad, %s) : %s}:' % (
                    kind, HWF, LU, LU, last, LU, fn, S, last, gn, S, last, M),
                '  match nonce:', '    case Nil{}:', '      {==}']
        for k in range(1, 12):
            out += ['    case %s:' % cons(NB[:k], 'Nil{}'), '      {==}']
        body = '%s(nr, ks, h, %s, aad, %s)' % (lem, QN, last)
        if kind == 'seal':
            body = 'Equal.cong(%s, %s, v => Some{v}, F.seal(%s, F.N{F.quad_word(T.W{n0, n1, n2, n3}), F.quad_word(T.W{n4, n5, n6, n7}), F.quad_word(T.W{n8, n9, n10, n11})}, aad, pt), G.seal_core(%s, %s, aad, pt), %s)' % (
                LU, M, KEYS, S, QN, body)
        out += ['    case %s:' % cons(NB[:12], 'Nil{}'), '      %s' % body,
                '    case %s:' % cons(NB[:13], 'rest'), '      {==}', '']
    return out


def main_all2():
    OUT.mkdir(parents=True, exist_ok=True)
    out = head() + helpers() + ghash_list() + small() + xor_lemmas() + open_short() + seal_body() + tag_lemmas() + open_lemmas() + top_lemmas()
    (OUT / 'gcm.bend').write_text('\n'.join(out))


if __name__ == '__main__':
    main_all2()
