#!/usr/bin/env python3
"""Generate proofs/crypto/aes/ghash_bits.bend: the bit-level lemmas relating
the implementation's GHASH words (src/crypto/aes/gcm.bend) to the
specification's field elements (spec/crypto/aes/gcm.bend).

Each lemma splits its U32 arguments into their 32 bits and closes the goal
by evaluation ({==}), after a case split on the few bits a mask or a carry
depends on, or (word_ok) through one-bit rewrites Bool.or(x, False) == x.

  python3 tools/generators/aes/ghash_bits.py
"""
from pathlib import Path

ROOT = Path(__file__).resolve().parents[3]


def bits(name, n=32):
    return ['%s_%d' % (name, i) for i in range(n)]


def word(names, tail='WNil{}'):
    s = tail
    for n in reversed(names):
        s = 'WCon{%s, %s}' % (n, s)
    return s


def u32(name):
    return 'U32{%s}' % word(bits(name))


def block(name):
    return 'I.B{%s}' % ', '.join(u32('%s%d' % (name, i)) for i in range(4))


def cases(vs):
    import itertools
    for combo in itertools.product(['True{}', 'False{}'], repeat=len(vs)):
        yield ' '.join(combo)


def main():
    out = ['import Base',
           'import ../../../src/crypto/aes/types.bend as T',
           'import ../../../src/crypto/aes/gcm.bend as I',
           'import ../../../spec/crypto/aes/poly.bend as P',
           'import ../../../spec/crypto/aes/aes.bend as S',
           'import ../../../spec/crypto/aes/gcm.bend as G',
           'import ./ghash_defs.bend as D',
           '',
           '# Generated by tools/generators/aes/ghash_bits.py.',
           '']
    # Z ^= V & mask
    out += ['# Z xor (V and (0 - bit)) is Z + c*V.',
            'def zstep_ok(+c: Bool, +z: I.Block, +v: I.Block) -> {D.R(I.add_masked(D.bit(c), z, v)) == Word.xor(128n, D.R(z), P.wscale(128n, c, D.R(v))) : Word(128n)}:',
            '  match c:']
    for c in ['True{}', 'False{}']:
        out += ['    case %s:' % c, '      match z v:', '        case %s %s:' % (block('z'), block('v')), '          {==}']
    out.append('')
    # V * x
    args = ['x0', 'xt', 'y0', 'yt', 'z0', 'zt', 'u0', 'ut']
    v = 'I.B{U32{WCon{x0, xt}}, U32{WCon{y0, yt}}, U32{WCon{z0, zt}}, U32{WCon{u0, ut}}}'
    out += ['def mulx_w(+x0: Bool, +y0: Bool, +z0: Bool, +u0: Bool, +xt: Word(31n), +yt: Word(31n), +zt: Word(31n), +ut: Word(31n)) -> {D.R(I.mulx(%s)) == P.times_x(128n, G.low(), D.R(%s)) : Word(128n)}:' % (v, v),
            '  match x0 y0 z0 u0:']
    for c in cases(['x0', 'y0', 'z0', 'u0']):
        out += ['    case %s:' % c, '      match xt yt zt ut:',
                '        case %s %s %s %s:' % tuple(word(bits(n, 31)) for n in ['a', 'b', 'c', 'd']),
                '          {==}']
    out += ['',
            '# V * x: the shift toward x^127 with the reduction by R.',
            'def mulx_ok(+v: I.Block) -> {D.R(I.mulx(v)) == P.times_x(128n, G.low(), D.R(v)) : Word(128n)}:',
            '  match v:',
            '    case %s:' % v,
            '      mulx_w(x0, y0, z0, u0, xt, yt, zt, ut)',
            '']
    # mul_byte == steps over its bits
    out += ['def mul_byte_steps(+a: U32, +acc: I.Acc) -> {I.mul_byte(a, acc) == D.steps(G.byte_bits(a), acc) : I.Acc}:',
            '  match a:', '    case %s:' % u32('a'), '      {==}', '']
    # coefficients of (Y xor X) are the bits of the bytes of Y xor X
    ys = ['y%d' % i for i in range(4)]
    xs = ['x%d' % i for i in range(16)]
    yb = 'I.B{%s}' % ', '.join(ys)
    xl = '[%s]' % ', '.join(xs)
    out += ['def block_xor_ok(%s) -> {P.coefficients(128n, Word.xor(128n, D.R(%s), G.block(%s))) == G.string_bits(I.xor_bytes(I.unpack(%s), %s)) : List<&2, Bool>}:'
            % (', '.join('+%s: U32' % n for n in ys + xs), yb, xl, yb, xl),
            '  match %s:' % ' '.join(ys + xs),
            '    case %s:' % ' '.join(u32(n) for n in ys + xs),
            '      {==}', '']
    # Bool.or(x, False) == x and the packing of four bytes
    out += ['def or_false(+x: Bool) -> {Bool.or(x, False{}) == x : Bool}:',
            '  match x:', '    case True{}:', '      {==}', '    case False{}:', '      {==}', '']
    X = bits('x'); Y = bits('y')
    out.append('def u32_ext(%s, %s) -> {U32{%s} == U32{%s} : U32}:' % (
        ', '.join('+%s: Bool' % n for n in X + Y),
        ', '.join('+e%d: {%s == %s : Bool}' % (i, X[i], Y[i]) for i in range(32)),
        word(X), word(Y)))
    for i in range(32):
        motive = word(X[:i] + ['_'] + Y[i + 1:])
        out.append('  %%e%d : {U32{%s} == U32{%s} : U32}' % (i, word(X), motive))
    out += ['  {==}', '']
    names = ['a', 'b', 'c', 'd']
    lhs, rhs, prf = [], [], []
    lane = {0: 'd', 1: 'c', 2: 'b', 3: 'a'}
    for p in range(32):
        n = lane[p // 8]
        x = '%s_%d' % (n, p % 8)
        rhs.append(x)
        if p < 8:
            lhs.append(x); prf.append('{==}')
        else:
            lhs.append('Bool.or(%s, False{})' % x); prf.append('or_false(%s)' % x)
    out += ['# The implementation packs four bytes into a big-endian word.',
            'def word_ok(+a: U32, +b: U32, +c: U32, +d: U32) -> {I.word(T.W{a, b, c, d}) == G.int32(a, b, c, d) : U32}:',
            '  match a b c d:',
            '    case %s:' % ' '.join(u32(n) for n in names),
            '      u32_ext(%s, %s, %s)' % (', '.join(lhs), ', '.join(rhs), ', '.join(prf)), '']
    As = ['a%d' % i for i in range(16)]
    blk = 'I.B{%s}' % ', '.join('G.int32(%s)' % ', '.join(As[4 * i:4 * i + 4]) for i in range(4))
    out += ['def pack_int(%s) -> {D.R(%s) == G.block([%s]) : Word(128n)}:' % (', '.join('+%s: U32' % n for n in As), blk, ', '.join(As)),
            '  match %s:' % ' '.join(As),
            '    case %s:' % ' '.join(u32(n) for n in As),
            '      {==}', '']
    # block_bytes of a block's element are its bytes
    out += ['def bb_ok(+s: I.Block) -> {G.block_bytes(D.R(s)) == I.unpack(s) : List<&2, U32>}:',
            '  match s:', '    case %s:' % block('s'), '      {==}', '']
    # the counter bytes
    ctr = '[U32.and(255, U32.shrn(c, 24n)), U32.and(255, U32.shrn(c, 16n)), U32.and(255, U32.shrn(c, 8n)), U32.and(255, c)]'
    out += ['def int32_ctr(+c: U32) -> {G.int32(U32.and(255, U32.shrn(c, 24n)), U32.and(255, U32.shrn(c, 16n)), U32.and(255, U32.shrn(c, 8n)), U32.and(255, c)) == c : U32}:',
            '  match c:', '    case %s:' % u32('c'), '      {==}', '',
            'def str32_ctr(+c: U32) -> {G.str32(c) == %s : List<&2, U32>}:' % ctr,
            '  match c:', '    case %s:' % u32('c'), '      {==}', '']
    (ROOT / 'proofs/crypto/aes/ghash_bits.bend').write_text('\n'.join(out))


if __name__ == '__main__':
    main()
