#!/usr/bin/env python3
"""Generate proofs/crypto/aes/sbox.bend: the byte-level leaf lemmas of AES.

Each lemma states, for every U32 x, that an implementation function of
src/crypto/aes/sbox.bend equals its FIPS 197 counterpart in
spec/crypto/aes/aes.bend. Both sides read only the low eight bits of x, so
the proof splits x into its 32 bits and case-splits the low eight: 256
cases, each closed by evaluation ({==}).

  python3 tools/generators/aes/sbox.py
"""
from pathlib import Path

ROOT = Path(__file__).resolve().parents[3]
BITS = ['b%d' % i for i in range(32)]


def word(names):
    s = 'WNil{}'
    for n in reversed(names):
        s = 'WCon{%s, %s}' % (n, s)
    return 'U32{%s}' % s


def lemma(name, impl, spec):
    w = word(BITS)
    out = ['law %s_bits:' % name]
    out += ['  for b%d: Bool' % i for i in range(32)]
    out += ['  {%s == %s : U32}' % (impl % w, spec % w), '',
            'def %s_bits(%s):' % (name, ', '.join(BITS)),
            '  match b0 b1 b2 b3 b4 b5 b6 b7:']
    for v in range(256):
        out.append('    case %s:' % ' '.join('True{}' if (v >> i) & 1 else 'False{}' for i in range(8)))
        out.append('      {==}')
    out += ['', 'law %s_ok:' % name, '  for +x: U32', '  {%s == %s : U32}' % (impl % 'x', spec % 'x'), '',
            'def %s_ok(x):' % name, '  match x:', '    case %s:' % w,
            '      %s_bits(%s)' % (name, ', '.join(BITS)), '']
    return out


def gmul(a, b):
    r = 0
    for i in range(8):
        if (b >> i) & 1:
            r ^= a << i
    for i in range(15, 7, -1):
        if (r >> i) & 1:
            r ^= 0x11b << (i - 8)
    return r


def check_inverse():
    """spec/crypto/aes/aes.bend states the inverse as a^254: check it is the
    field inverse (a * a^254 = {01} for a != 0, and 0 -> 0)."""
    for a in range(256):
        p, x = 1, a
        for bit in range(8):
            if (254 >> bit) & 1:
                p = gmul(p, x)
            x = gmul(x, x)
        assert (a == 0 and p == 0) or gmul(a, p) == 1, a


def main():
    check_inverse()
    out = ['import Base',
           'import ../../../src/crypto/aes/sbox.bend as B',
           'import ../../../spec/crypto/aes/aes.bend as S',
           '',
           '# Generated by tools/generators/aes/sbox.py. The constant-time byte',
           '# functions equal FIPS 197 on every U32 (both read only the low 8 bits).',
           '']
    out += lemma('sbox', 'B.sbox(%s)', 'S.sbox(%s)')
    out += lemma('xtime', 'B.xtime(%s)', 'S.mul(2, %s)')
    out += lemma('mul3', 'B.mul3(%s)', 'S.mul(3, %s)')
    (ROOT / 'proofs/crypto/aes/sbox.bend').write_text('\n'.join(out))


if __name__ == '__main__':
    main()
