#!/usr/bin/env python3
"""Generate the fused ChaCha20-Poly1305 seal (one pass: each 64-byte
keystream block is XORed onto the plaintext and its four 16-byte
ciphertext blocks absorbed at once) and its proof.

  python3 tools/generators/aead_fused.py

rewrites the section between the FUSED markers of
src/crypto/aead/chacha20poly1305.bend and proofs/crypto/aead/fused.bend.
Nothing here is trusted: the checker verifies the generated proof.
"""
import os

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
SRC = os.path.join(ROOT, 'src', 'crypto', 'aead', 'chacha20poly1305.bend')
PRF = os.path.join(ROOT, 'proofs', 'crypto', 'aead', 'fused.bend')

X = ['x%d' % i for i in range(64)]
Y = ['y%d' % i for i in range(64)]
W = ['w%d' % i for i in range(16)]


def ybytes(i):
    w = 'w%d' % (i // 4)
    return ['U32.and(%s,255)' % w, 'U32.and(U32.shrn(%s,8n),255)' % w, 'U32.and(U32.shrn(%s,16n),255)' % w, 'U32.shrn(%s,24n)' % w][i % 4]


def lets(ind, kk='kk', h='h', cnt='cnt'):
    L = []
    for i in range(64):
        L.append('+y%d = U32.xor(x%d, %s)' % (i, i, ybytes(i)))
    prev = h
    for b in range(4):
        L.append('+h%d = L.block(%s, %s, L.load(%s, pone))' % (b + 1, kk, prev, ', '.join('L.byte(y%d)' % (16 * b + j) for j in range(16))))
        prev = 'h%d' % (b + 1)
    L.append('+cnt4 = Nat.add(Nat.add(Nat.add(Nat.add(%s, 16n), 16n), 16n), 16n)' % cnt)
    return [ind + l for l in L]


def src_section():
    L = []
    L.append('# ---- FUSED (generated by tools/generators/aead_fused.py; do not edit)')
    L.append('''
# The end of the tag computation: the ciphertext's last bytes ct absorbed
# with their padding onto h (cnt bytes so far), then the two lengths.
def ftail(+ct: List<&2, U32>, +pone: Nat, +kk: L.K, sv: L.F, la: Nat, h: L.F, cnt: Nat) -> List<&2, U32>:
  List.append(&2, U32, ct, P.tag_len(pone, kk, sv, la, P.absorb_pad(pone, ct, kk, h, cnt)))

# The ciphertext of the last 0..63 bytes (st: the keystream state of the
# block under counter c).
def fct(fuel: Nat, xs: List<&2, U32>, +st: C.State, +r: Nat, +k: CH.Key, +c: U32, +n: CH.Nonce) -> List<&2, U32>:
  match fuel:
    case 0n: Nil{}
    case 1n+p: CH.xstream(p, C.bytes(st), xs, r, k, U32.add(c, 1), n)

# ciphertext || tag in one pass: st is the keystream state of the block
# under counter c; each full 64-byte block of xs is XORed with it and its
# four 16-byte ciphertext blocks absorbed onto h at once. The next state is
# computed only when bytes follow the block.
def fseal(fuel: Nat, xs: List<&2, U32>, +st: C.State, +r: Nat, +k: CH.Key, +c: U32, +n: CH.Nonce, +pone: Nat, +kk: L.K, +sv: L.F, +la: Nat, h: L.F, cnt: Nat) -> List<&2, U32>:
  match fuel xs st:''')
    L.append('    case 1n+p %s <> x64 <> rest C.S{%s}:' % (' <> '.join(X), ', '.join('+' + w for w in W)))
    L.extend(lets('      '))
    L.append('      +c1 = U32.add(c, 1)')
    L.append('      %s <> fseal(p, x64 <> rest, C.block(r, CH.state(k, c1, n)), r, k, c1, n, pone, kk, sv, la, h4, cnt4)' % ' <> '.join(Y))
    L.append('    case 1n+p %s <> Nil{} C.S{%s}:' % (' <> '.join(X), ', '.join('+' + w for w in W)))
    L.extend(lets('      '))
    L.append('      %s <> ftail(Nil{}, pone, kk, sv, la, h4, cnt4)' % ' <> '.join(Y))
    L.append('    case _ _ _:')
    L.append('      ftail(fct(fuel, xs, st, r, k, c, n), pone, kk, sv, la, h, cnt)')
    L.append('''
# seal after the aad: ciphertext || tag of pt, from the accumulator a over aad.
def sela(+pone: Nat, +kk: L.K, +sv: L.F, a: P.A, pt: List<&2, U32>, +k: CH.Key, +n: CH.Nonce) -> List<&2, U32>:
  match a pt:
    case P.A{h, la} Nil{}: ftail(Nil{}, pone, kk, sv, la, h, 0n)
    case P.A{h, la} +x <> +rest: fseal(List.length(&2, U32, x <> rest), x <> rest, C.block(10n, CH.state(k, 1, n)), 10n, k, 1, n, pone, kk, sv, la, h, 0n)

def selk(%s, aad: List<&2, U32>, pt: List<&2, U32>, +k: CH.Key, +n: CH.Nonce) -> List<&2, U32>:
  +kk = L.key(P.r_of(%s))
  sela(1n, kk, P.s_of(%s), P.absorb_pad(1n, aad, kk, L.zero(), 0n), pt, k, n)

def sell(pk: List<&2, U32>, aad: List<&2, U32>, pt: List<&2, U32>, +k: CH.Key, +n: CH.Nonce) -> List<&2, U32>:
  match pk:
    case %s <> rest: selk(%s, aad, pt, k, n)
    case _: Nil{}

# ciphertext || tag (RFC 8439 2.8) in one pass over the plaintext;
# proofs/crypto/aead/fused.bend proves it equal to seal_ref.
def seal(+key: List<&2, U32>, +nonce: List<&2, U32>, +aad: List<&2, U32>, +pt: List<&2, U32>) -> List<&2, U32>:
  sell(P.pad(32n, poly_key(key, nonce)), aad, pt, CH.key(key), CH.nonce(nonce))
# ---- end FUSED''' % (', '.join('+k%d: U32' % i for i in range(32)), ', '.join('k%d' % i for i in range(16)), ', '.join('k%d' % i for i in range(16, 32)),
                        ' <> '.join('k%d' % i for i in range(32)), ', '.join('k%d' % i for i in range(32))))
    return '\n'.join(L)


def nested(ind, depth, nil_fn, leaf_fn, var='x', tl='t', head='xs', last_rest='rest', start=0):
    """match head as depth cells: nil_fn(j) at a Nil after j cells, leaf_fn at depth cells"""
    L = [ind + 'match %s:' % head, ind + '  case Nil{}: ' + nil_fn(0)]
    cur = ind + '  '
    for j in range(depth):
        t = '%s%d' % (tl, j) if j < depth - 1 else last_rest
        L.append(cur + 'case +%s%d <> +%s:' % (var, start + j, t))
        if j < depth - 1:
            L.append(cur + '  match %s%d:' % (tl, j))
            L.append(cur + '    case Nil{}: ' + nil_fn(j + 1))
            cur += '    '
        else:
            L.extend(leaf_fn(cur + '  '))
    return L


FUEL_TEXT = 'law fseal_eq:\n  for fuel: Nat\n  for +xs: List<&2, U32>\n  for +st: C.State\n  for +r: Nat\n  for +k: CH.Key\n  for +c: U32\n  for +n: CH.Nonce\n  for +pone: Nat\n  for +kk: L.K\n  for +sv: L.F\n  for +la: Nat\n  for +h: L.F\n  for +cnt: Nat\n  {I.fseal(fuel, xs, st, r, k, c, n, pone, kk, sv, la, h, cnt) == I.ftail(I.fct(fuel, xs, st, r, k, c, n), pone, kk, sv, la, h, cnt) : List<&2, U32>}\n\ndef fseal_eq(fuel, xs, st, r, k, c, n, pone, kk, sv, la, h, cnt):\n  match fuel:\n    case 0n: {==}\n    case 1n+p: fseal_eq1(p, xs, st, r, k, c, n, pone, kk, sv, la, h, cnt)\n'


B1 = 'C.block(r, CH.state(k, U32.add(c, 1), n))'
C1 = 'U32.add(c, 1)'
C4 = 'Nat.add(Nat.add(Nat.add(Nat.add(cnt, 16n), 16n), 16n), 16n)'


def ycell(i):
    return 'U32.xor(x%d, %s)' % (i, ybytes(i))


def H4():
    prev = 'h'
    for b in range(4):
        prev = 'L.block(kk, %s, L.load(%s, pone))' % (prev, ', '.join('L.byte(%s)' % ycell(16 * b + j) for j in range(16)))
    return prev


def fstep():
    Ws = ', '.join(W)
    return '''# one full block, given the rest (ih): both sides are the block's 64
# ciphertext bytes in front of the rest
law fstep:
  for +q: Nat
%s
  for +x64: U32
  for +rest: List<&2, U32>
%s
  for +r: Nat
  for +k: CH.Key
  for +c: U32
  for +n: CH.Nonce
  for +pone: Nat
  for +kk: L.K
  for +sv: L.F
  for +la: Nat
  for +h: L.F
  for +cnt: Nat
  for +ih: {I.fseal(1n+q, x64 <> rest, %s, r, k, %s, n, pone, kk, sv, la, %s, %s) == I.ftail(I.fct(1n+q, x64 <> rest, %s, r, k, %s, n), pone, kk, sv, la, %s, %s) : List<&2, U32>}
  {I.fseal(1n+1n+q, %s <> x64 <> rest, C.S{%s}, r, k, c, n, pone, kk, sv, la, h, cnt) == I.ftail(I.fct(1n+1n+q, %s <> x64 <> rest, C.S{%s}, r, k, c, n), pone, kk, sv, la, h, cnt) : List<&2, U32>}

def fstep(q, %s, x64, rest, %s, r, k, c, n, pone, kk, sv, la, h, cnt, ih):
  Equal.cong(List<&2, U32>, List<&2, U32>, z => %s <> z, I.fseal(1n+q, x64 <> rest, %s, r, k, %s, n, pone, kk, sv, la, %s, %s), I.ftail(I.fct(1n+q, x64 <> rest, %s, r, k, %s, n), pone, kk, sv, la, %s, %s), ih)
''' % ('\n'.join('  for +x%d: U32' % i for i in range(64)), '\n'.join('  for +w%d: U32' % i for i in range(16)),
       B1, C1, H4(), C4, B1, C1, H4(), C4, ' <> '.join(X), Ws, ' <> '.join(X), Ws,
       ', '.join(X), Ws, ' <> '.join(ycell(i) for i in range(64)), B1, C1, H4(), C4, B1, C1, H4(), C4)


def proof():
    P_ = []
    P_.append('''import Base
import ../../../src/crypto/chacha/core.bend as C
import ../../../src/crypto/chacha/chacha20.bend as CH
import ../../../src/crypto/poly1305/limbs.bend as L
import ../../../src/crypto/poly1305/poly1305.bend as P
import ../../../src/crypto/aead/chacha20poly1305.bend as I
import ../../../src/crypto/subtle.bend as S
import ../../lib/nat.bend as NL
import ../../lib/logic.bend as LG

# Generated by tools/generators/aead_fused.py (do not edit).
#
# The one-pass seal of src/crypto/aead/chacha20poly1305.bend is seal_ref
# (ciphertext, then the tag of the ciphertext, appended): fseal with the
# keystream state st of counter c is ftail of fct (the ciphertext xstream
# gives from st on), block by block; fct from the first state is the
# ciphertext of encrypt_rounds (xstream); and seal unfolds mac_aead's steps (its padded key, the aad's
# accumulator) the way seal_ref's tag does.

law fseal_eq1:
  for p: Nat
  for +xs: List<&2, U32>
  for +st: C.State
  for +r: Nat
  for +k: CH.Key
  for +c: U32
  for +n: CH.Nonce
  for +pone: Nat
  for +kk: L.K
  for +sv: L.F
  for +la: Nat
  for +h: L.F
  for +cnt: Nat
  {I.fseal(1n+p, xs, st, r, k, c, n, pone, kk, sv, la, h, cnt) == I.ftail(I.fct(1n+p, xs, st, r, k, c, n), pone, kk, sv, la, h, cnt) : List<&2, U32>}
''')
    A = 'r, k, c, n, pone, kk, sv, la, h, cnt'

    def make(zero):
        def leaf(ind):
            L = [ind + 'match st:']
            L.append(ind + '  case C.S{%s}:' % ', '.join('+' + w for w in W))
            if zero:
                L.append(ind + '    {==}')
                return L
            L.append(ind + '    fstep(q, %s, x64, rest, %s, r, k, c, n, pone, kk, sv, la, h, cnt, fseal_eq1(q, x64 <> rest, %s, r, k, %s, n, pone, kk, sv, la, %s, %s))' % (', '.join(X), ', '.join(W), B1, C1, H4(), C4))
            return L

        def leaf64(ind):
            L = [ind + 'match rest:']
            L.append(ind + '  case Nil{}:')
            L.append(ind + '    match st:')
            L.append(ind + '      case C.S{%s}: {==}' % ', '.join(W))
            L.append(ind + '  case +x64 <> +rest:')
            L.extend(leaf(ind + '    '))
            return L
        pv = '0n' if zero else '1n+q'
        return nested('      ', 64, lambda j: '\n'.join(['', 'MATCHST']), leaf64, last_rest='rest')

    def fix(lines):
        out = []
        for l in lines:
            if l.endswith('case Nil{}: ') or l.endswith('case Nil{}: \nMATCHST'):
                pass
            out.append(l)
        return out
    P_.append('def fseal_eq1(p, xs, st, r, k, c, n, pone, kk, sv, la, h, cnt):')
    P_.append('  match p:')
    P_.append('    case 0n:')
    P_.extend(make(True))
    P_.append('    case 1n++q:')
    P_.extend(make(False))
    P_.append('')
    P_.append(FUEL_TEXT)
    return '\n'.join(P_)


def fpart():
    """the fallback of fseal (1..63 bytes): fseal == ftail(fct) after the
    match on st (fseal's third scrutinee) and p (xstream's fuel)"""
    W_ = ', '.join(W)
    return '''law fpart:
  for +p: Nat
  for +xs: List<&2, U32>
  for +st: C.State
  for +r: Nat
  for +k: CH.Key
  for +c: U32
  for +n: CH.Nonce
  for +pone: Nat
  for +kk: L.K
  for +sv: L.F
  for +la: Nat
  for +h: L.F
  for +cnt: Nat
  {I.fseal(1n+p, xs, st, r, k, c, n, pone, kk, sv, la, h, cnt) == I.ftail(I.fct(1n+p, xs, st, r, k, c, n), pone, kk, sv, la, h, cnt) : List<&2, U32>}

def fpart(p, xs, st, r, k, c, n, pone, kk, sv, la, h, cnt):
  match st:
    case C.S{%s}: {==}
''' % W_


def top():
    pk = 'pk'
    ks = []
    e = pk
    for i in range(32):
        ks.append('P.kh(%s)' % e)
        e = 'P.tl(%s)' % e
    kk = 'L.key(P.r_of(%s))' % ', '.join(ks[:16])
    sv = 'P.s_of(%s)' % ', '.join(ks[16:])

    def one(aad):
        return 'selaq(1n, %s, %s, P.absorb_pad(1n, %s, %s, L.zero(), 0n), pt, k, n)' % (kk, sv, aad, kk)
    return '''# sela is ciphertext || tag_ct of the ciphertext
law selaq:
  for +pone: Nat
  for +kk: L.K
  for +sv: L.F
  for +a: P.A
  for +pt: List<&2, U32>
  for +k: CH.Key
  for +n: CH.Nonce
  {I.sela(pone, kk, sv, a, pt, k, n) == List.append(&2, U32, CH.xstream(List.length(&2, U32, pt), [], pt, 10n, k, 1, n), P.tag_ct(pone, kk, sv, a, CH.xstream(List.length(&2, U32, pt), [], pt, 10n, k, 1, n))) : List<&2, U32>}

def selaq(pone, kk, sv, a, pt, k, n):
  match a pt:
    case P.A{+h, +la} Nil{}: {==}
    case P.A{+h, +la} +x <> +rest:
      fseal_eq(List.length(&2, U32, x <> rest), x <> rest, C.block(10n, CH.state(k, 1, n)), 10n, k, 1, n, pone, kk, sv, la, h, 0n)

# with the one-time key pk, the keystream key k and nonce n kept abstract
law sealq:
  for +pk: List<&2, U32>
  for +aad: List<&2, U32>
  for +pt: List<&2, U32>
  for +k: CH.Key
  for +n: CH.Nonce
  {I.sell(P.pad(32n, pk), aad, pt, k, n) == List.append(&2, U32, CH.xstream(List.length(&2, U32, pt), [], pt, 10n, k, 1, n), P.mac_aead(pk, aad, CH.xstream(List.length(&2, U32, pt), [], pt, 10n, k, 1, n))) : List<&2, U32>}

def sealq(pk, aad, pt, k, n):
  match aad:
    case Nil{}: %s
    case +x <> +rest: %s

# the one-pass seal is seal_ref
law seal_fused:
  for +key: List<&2, U32>
  for +nonce: List<&2, U32>
  for +aad: List<&2, U32>
  for +pt: List<&2, U32>
  {I.seal(key, nonce, aad, pt) == I.seal_ref(key, nonce, aad, pt) : List<&2, U32>}

def seal_fused(key, nonce, aad, pt):
  sealq(I.poly_key(key, nonce), aad, pt, CH.key(key), CH.nonce(nonce))
''' % (one('[]'), one('x <> rest'))


def main():
    s = open(SRC).read()
    i = s.find('# ---- FUSED')
    if i >= 0:
        j = s.index('# ---- end FUSED') + len('# ---- end FUSED')
        s = s[:i] + src_section() + s[j:]
    else:
        old = '''def seal(+key: List<&2, U32>, +nonce: List<&2, U32>, +aad: List<&2, U32>, +pt: List<&2, U32>) -> List<&2, U32>:
  +ct = encrypt_ct(key, nonce, pt)
  List.append(&2, U32, ct, tag(key, nonce, aad, ct))'''
        assert old in s
        s = s.replace(old, old.replace('def seal(', 'def seal_ref(') + '\n\n' + src_section())
    i = s.find('# ---- FUSED OPEN')
    if i >= 0:
        j = s.index('# ---- end FUSED OPEN') + len('# ---- end FUSED OPEN')
        s = s[:i] + open_section() + s[j:]
    else:
        old = '''def open(+key: List<&2, U32>, +nonce: List<&2, U32>, +aad: List<&2, U32>, +data: List<&2, U32>) -> Maybe<&2, List<&2, U32>>:
  match data:
    case x0 <> x1 <> x2 <> x3 <> x4 <> x5 <> x6 <> x7 <> x8 <> x9 <> x10 <> x11 <> x12 <> x13 <> x14 <> x15 <> rest:
      open_split(key, nonce, aad, body(rest, data), tail(rest, data))
    case _: None{}'''
        assert old in s
        s = s.replace(old, old.replace('def open(', 'def open_ref(') + '\n\n' + open_section())
    open(SRC, 'w').write(s)
    pr = proof()
    # fpart goes before fseal_eq
    out = []
    for l in pr.split('\n'):
        if l.endswith('case Nil{}: ') :
            ind = l[:len(l) - len(l.lstrip())]
            out.append(ind + 'case Nil{}:')
            out.append(ind + '  match st:')
            out.append(ind + '    case C.S{%s}: {==}' % ', '.join(W))
        elif l == 'MATCHST':
            continue
        else:
            out.append(l)
    pr = '\n'.join(out)
    k = pr.index('law fseal_eq1:')
    pr = pr[:k] + fstep() + '\n' + pr[k:]
    op = fix_nil_leaves(open_proof())
    open(PRF, 'w').write(pr + '\n' + top() + '\n' + op + '\n' + open_top())



# ================================================================ fused open

def olets(ind, h='h', cnt='cnt'):
    """the four ciphertext blocks x0..x63 absorbed (g1..g4) and the count"""
    L = []
    prev = h
    for b in range(4):
        L.append('+g%d = L.block(kk, %s, L.load(%s, pone))' % (b + 1, prev, ', '.join('L.byte(x%d)' % (16 * b + j) for j in range(16))))
        prev = 'g%d' % (b + 1)
    L.append('+cnt4 = Nat.add(Nat.add(Nat.add(Nat.add(%s, 16n), 16n), 16n), 16n)' % cnt)
    return [ind + l for l in L]


LC = ['l%d' % i for i in range(65)]


def open_section():
    ys = ' <> '.join(ycell(i) for i in range(64))
    w17 = ' <> '.join(['_'] * 17) + ' <> _'
    fb = ['otag(xs, pone, kk, sv, la, h, cnt)']
    L = ['# ---- FUSED OPEN (generated by tools/generators/aead_fused.py; do not edit)', """
# Some(pt) when ok.
def owhen(ok: Bool, pt: List<&2, U32>) -> Maybe<&2, List<&2, U32>>:
  match ok:
    case True{}: Some{pt}
    case False{}: None{}

# Whether the tag of the data xs (ciphertext || tag) matches, the
# ciphertext absorbed onto h (cnt bytes so far) with its padding, then the
# lengths.
def otag(+xs: List<&2, U32>, +pone: Nat, +kk: L.K, +sv: L.F, +la: Nat, h: L.F, cnt: Nat) -> Bool:
  +ld = CH.skip(16n, xs)
  S.eq(tail(ld, xs), P.tag_len(pone, kk, sv, la, P.absorb_pad(pone, body(ld, xs), kk, h, cnt)))

# Whether the tag matches. xs is the data (ciphertext || tag) from some
# point on: while at least 65 ciphertext bytes remain (81 bytes of data),
# 64 of them are absorbed onto h per step; then the rest (the data but its
# last 16 bytes) with its padding and the lengths, and the tag (the last 16
# bytes) compared. No list is built on the way.
def opoly(fuel: Nat, +xs: List<&2, U32>, +pone: Nat, +kk: L.K, +sv: L.F, +la: Nat, h: L.F, cnt: Nat) -> Bool:
  match fuel:"""]
    L.append('    case 0n:')
    L.extend('      ' + l for l in fb)
    L.append('    case 1n+p:')
    L.append('      match xs:')
    L.append('        case %s <> +xrest:' % ' <> '.join('+' + x for x in X))
    L.append('          match xrest:')
    L.append('            case %s:' % w17)
    L.extend(olets('              '))
    L.append('              opoly(p, xrest, pone, kk, sv, la, g4, cnt4)')
    L.append('            case _:')
    L.extend('              ' + l for l in fb)
    L.append('        case _:')
    L.extend('          ' + l for l in fb)
    L.append("""
# The plaintext: 64 bytes per step (st: the keystream state of counter c)
# while at least 65 ciphertext bytes remain, then fct on the rest.
def odec(fuel: Nat, +xs: List<&2, U32>, +st: C.State, +r: Nat, +k: CH.Key, +c: U32, +n: CH.Nonce) -> List<&2, U32>:
  match fuel:""")
    fd = 'fct(fuel, body(CH.skip(16n, xs), xs), st, r, k, c, n)'
    L.append('    case 0n: ' + fd.replace('fct(fuel,', 'fct(0n,'))
    L.append('    case 1n+p:')
    L.append('      match xs:')
    L.append('        case %s <> +xrest:' % ' <> '.join('+' + x for x in X))
    L.append('          match xrest:')
    L.append('            case %s:' % w17)
    L.append('              match st:')
    L.append('                case C.S{%s}:' % ', '.join('+' + w for w in W))
    L.append('                  +c1 = U32.add(c, 1)')
    L.append('                  %s <> odec(p, xrest, C.block(r, CH.state(k, c1, n)), r, k, c1, n)' % ys)
    L.append('            case _:')
    L.append('              ' + fd.replace('fct(fuel,', 'fct(1n+p,'))
    L.append('        case _:')
    L.append('          ' + fd.replace('fct(fuel,', 'fct(1n+p,'))
    L.append("""
def osela(+pone: Nat, +kk: L.K, +sv: L.F, a: P.A, lead: List<&2, U32>, +xs: List<&2, U32>, +k: CH.Key, +n: CH.Nonce) -> Maybe<&2, List<&2, U32>>:
  match a lead:
    case P.A{h, la} Nil{}: owhen(S.eq(xs, P.tag_len(pone, kk, sv, la, P.absorb_pad(pone, Nil{}, kk, h, 0n))), Nil{})
    case P.A{h, la} +l <> +lt: owhen(opoly(List.length(&2, U32, l <> lt), xs, pone, kk, sv, la, h, 0n), odec(List.length(&2, U32, l <> lt), xs, C.block(10n, CH.state(k, 1, n)), 10n, k, 1, n))

def oselk(%s, aad: List<&2, U32>, lead: List<&2, U32>, +xs: List<&2, U32>, +k: CH.Key, +n: CH.Nonce) -> Maybe<&2, List<&2, U32>>:
  +kk = L.key(P.r_of(%s))
  osela(1n, kk, P.s_of(%s), P.absorb_pad(1n, aad, kk, L.zero(), 0n), lead, xs, k, n)

def osel(pk: List<&2, U32>, aad: List<&2, U32>, lead: List<&2, U32>, +xs: List<&2, U32>, +k: CH.Key, +n: CH.Nonce) -> Maybe<&2, List<&2, U32>>:
  match pk:
    case %s <> rest: oselk(%s, aad, lead, xs, k, n)
    case _: None{}

# The plaintext of ciphertext || tag, or None: one pass over the data for
# the tag and one for the plaintext, without splitting it;
# proofs/crypto/aead/fused.bend proves it equal to open_ref.
def open(+key: List<&2, U32>, +nonce: List<&2, U32>, +aad: List<&2, U32>, +data: List<&2, U32>) -> Maybe<&2, List<&2, U32>>:
  match data:
    case x0 <> x1 <> x2 <> x3 <> x4 <> x5 <> x6 <> x7 <> x8 <> x9 <> x10 <> x11 <> x12 <> x13 <> x14 <> x15 <> rest:
      osel(P.pad(32n, poly_key(key, nonce)), aad, rest, data, CH.key(key), CH.nonce(nonce))
    case _: None{}
# ---- end FUSED OPEN""" % (', '.join('+k%d: U32' % i for i in range(32)), ', '.join('k%d' % i for i in range(16)), ', '.join('k%d' % i for i in range(16, 32)),
                           ' <> '.join('k%d' % i for i in range(32)), ', '.join('k%d' % i for i in range(32))))
    return '\n'.join(L)


def G4():
    prev = 'h'
    for b in range(4):
        prev = 'L.block(kk, %s, L.load(%s, pone))' % (prev, ', '.join('L.byte(x%d)' % (16 * b + j) for j in range(16)))
    return prev


XR = ['x%d' % i for i in range(64, 81)]


def open_proof():
    AD = 'r, k, c, n'
    AD1 = 'r, k, %s, n' % C1
    ysl = ' <> '.join(ycell(i) for i in range(64))
    xsn = ' <> '.join(X)
    xrn = ' <> '.join(XR) + ' <> rr'
    Ws = ', '.join(W)
    fors = lambda names, ty: '\n'.join('  for +%s: %s' % (v, ty) for v in names)
    TP = lambda xs_, hh, cn: 'I.otag(%s, pone, kk, sv, la, %s, %s)' % (xs_, hh, cn)
    P_ = ['# ---------------------------------------------------------------- open\n']

    def xr_nest(ind, leaf, nil=''):
        return nested(ind, 17, lambda j: nil, leaf, var='x', tl='v', head='xrest', last_rest='rr', start=64)

    def pleaf(ind):
        return [ind + 'opoly_eq(p, %s, pone, kk, sv, la, %s, %s)' % (xrn, G4(), C4)]

    def pxs(ind):
        return xr_nest(ind, pleaf, '{==}')
    P_.append("""law opoly_eq:
  for fuel: Nat
  for +xs: List<&2, U32>
  for +pone: Nat
  for +kk: L.K
  for +sv: L.F
  for +la: Nat
  for +h: L.F
  for +cnt: Nat
  {I.opoly(fuel, xs, pone, kk, sv, la, h, cnt) == %s : Bool}

def opoly_eq(fuel, xs, pone, kk, sv, la, h, cnt):
  match fuel:
    case 0n: {==}
    case 1n++p:""" % TP('xs', 'h', 'cnt'))
    P_.extend(nested('      ', 64, lambda j: '{==}', pxs, var='x', tl='u', head='xs', last_rest='xrest'))
    P_.append('')
    common = """  for +r: Nat
  for +k: CH.Key
  for +c: U32
  for +n: CH.Nonce"""
    P_.append("""# a full block with at least 65 more ciphertext bytes (x64..x80 and rr)
law dstep:
  for +q: Nat
%s
%s
  for +rr: List<&2, U32>
%s
%s
  for +ih: {I.odec(1n+q, %s, %s, %s) == I.fct(1n+q, I.body(CH.skip(16n, %s), %s), %s, %s) : List<&2, U32>}
  {I.odec(1n+1n+q, %s <> %s, C.S{%s}, %s) == I.fct(1n+1n+q, I.body(CH.skip(16n, %s <> %s), %s <> %s), C.S{%s}, %s) : List<&2, U32>}

def dstep(q, %s, %s, rr, %s, r, k, c, n, ih):
  Equal.cong(List<&2, U32>, List<&2, U32>, z => %s <> z, I.odec(1n+q, %s, %s, %s), I.fct(1n+q, I.body(CH.skip(16n, %s), %s), %s, %s), ih)
""" % (fors(X, 'U32'), fors(XR, 'U32'), fors(W, 'U32'), common,
       xrn, B1, AD1, xrn, xrn, B1, AD1,
       xsn, xrn, Ws, AD, xsn, xrn, xsn, xrn, Ws, AD,
       ', '.join(X), ', '.join(XR), Ws, ysl, xrn, B1, AD1, xrn, xrn, B1, AD1))

    def make(zero):
        def dleaf(ind):
            if zero:
                return [ind + 'match st:', ind + '  case C.S{%s}: {==}' % Ws]
            return [ind + 'match st:', ind + '  case C.S{%s}: dstep(q, %s, %s, rr, %s, %s, odec_eq1(q, %s, %s, %s))' % (
                ', '.join('+' + w for w in W), ', '.join(X), ', '.join(XR), Ws, AD, xrn, B1, AD1)]

        def dxs(ind):
            return xr_nest(ind, dleaf)
        return nested('      ', 64, lambda j: '', dxs, var='x', tl='u', head='xs', last_rest='xrest')

    P_.append("""law odec_eq1:
  for p: Nat
  for +xs: List<&2, U32>
  for +st: C.State
%s
  {I.odec(1n+p, xs, st, %s) == I.fct(1n+p, I.body(CH.skip(16n, xs), xs), st, %s) : List<&2, U32>}
""" % (common, AD, AD))
    P_.append('def odec_eq1(p, xs, st, %s):' % AD)
    P_.append('  match p:')
    P_.append('    case 0n:')
    P_.extend(make(True))
    P_.append('    case 1n++q:')
    P_.extend(make(False))
    P_.append("""
law odec_eq:
  for fuel: Nat
  for +xs: List<&2, U32>
  for +st: C.State
%s
  {I.odec(fuel, xs, st, %s) == I.fct(fuel, I.body(CH.skip(16n, xs), xs), st, %s) : List<&2, U32>}

def odec_eq(fuel, xs, st, %s):
  match fuel:
    case 0n: {==}
    case 1n+p: odec_eq1(p, xs, st, %s)
""" % (common, AD, AD, AD, AD))
    return '\n'.join(P_)


def fix_nil_leaves(pr):
    """a Nil leaf ('case Nil{}: ' with nothing after it) of the nested open proof: {==} after matching st"""
    out = []
    for l in pr.split('\n'):
        if l.endswith('case Nil{}: '):
            ind = l[:len(l) - len(l.lstrip())]
            out.append(ind + 'case Nil{}:')
            out.append(ind + '  match st:')
            out.append(ind + '    case C.S{%s}: {==}' % ', '.join(W))
        else:
            out.append(l)
    return '\n'.join(out)


def open_top():
    ks = []
    e = 'pk'
    for i in range(32):
        ks.append('P.kh(%s)' % e)
        e = 'P.tl(%s)' % e
    kk = 'L.key(P.r_of(%s))' % ', '.join(ks[:16])
    sv = 'P.s_of(%s)' % ', '.join(ks[16:])
    X16 = ' <> '.join('x%d' % i for i in range(16))
    X16C = ', '.join('x%d' % i for i in range(16))
    X16P = '\n'.join('  for +x%d: U32' % i for i in range(16))
    X16T = ', '.join('+x%d: U32' % i for i in range(16))

    def one(aad):
        return 'osq(1n, %s, %s, P.absorb_pad(1n, %s, %s, L.zero(), 0n), %s, lead, k, n, hl)' % (kk, sv, aad, kk, X16C)

    def nest16(ind, leaf):
        L = [ind + 'match data:', ind + '  case Nil{}: {==}']
        cur = ind + '  '
        for j in range(16):
            t = 't%d' % j if j < 15 else 'rest'
            L.append(cur + 'case +x%d <> +%s:' % (j, t))
            if j < 15:
                L.append(cur + '  match t%d:' % j)
                L.append(cur + '    case Nil{}: {==}')
                cur += '    '
            else:
                L.append(cur + '  ' + leaf)
        return '\n'.join(L)
    T = """
# the length of body(lead, xs) is lead's when xs is at least as long
law blen:
  for +l: List<&2, U32>
  for +xs: List<&2, U32>
  for +h: {Nat.is_le(List.length(&2, U32, l), List.length(&2, U32, xs)) == True{} : Bool}
  {List.length(&2, U32, I.body(l, xs)) == List.length(&2, U32, l) : Nat}

def blen(l, xs, h):
  match l xs:
    case Nil{} _: {==}
    case y <> yt Nil{}: Empty.absurd({List.length(&2, U32, I.body(y <> yt, [])) == List.length(&2, U32, y <> yt) : Nat}, LG.false_true(h))
    case y <> yt x <> xt: Equal.cong(Nat, Nat, m => 1n+m, List.length(&2, U32, I.body(yt, xt)), List.length(&2, U32, yt), blen(yt, xt, h))

law le16:
  for +m: Nat
  {Nat.is_le(m, 16n+m) == True{} : Bool}

def le16(m):
  match m:
    case 0n: {==}
    case 1n+j: le16(j)

law otag_eq:
  for +ok: Bool
  for +key: List<&2, U32>
  for +nonce: List<&2, U32>
  for +ct: List<&2, U32>
  {I.open_tag(ok, key, nonce, ct) == I.owhen(ok, CH.encrypt_rounds(10n, key, 1, nonce, ct)) : Maybe<&2, List<&2, U32>>}

def otag_eq(ok, key, nonce, ct):
  match ok:
    case True{}: {==}
    case False{}: {==}

# the fuel of the ciphertext's stream: the ciphertext's length
law ofuel:
  for +l: U32
  for +lt: List<&2, U32>
  for +xs: List<&2, U32>
  for +hl: {List.length(&2, U32, I.body(l <> lt, xs)) == List.length(&2, U32, l <> lt) : Nat}
  for +k: CH.Key
  for +n: CH.Nonce
  {I.fct(List.length(&2, U32, l <> lt), I.body(l <> lt, xs), C.block(10n, CH.state(k, 1, n)), 10n, k, 1, n) == CH.xstream(List.length(&2, U32, I.body(l <> lt, xs)), [], I.body(l <> lt, xs), 10n, k, 1, n) : List<&2, U32>}

def ofuel(l, lt, xs, hl, k, n):
  match xs:
    case Nil{}: Empty.absurd({I.fct(List.length(&2, U32, l <> lt), I.body(l <> lt, []), C.block(10n, CH.state(k, 1, n)), 10n, k, 1, n) == CH.xstream(List.length(&2, U32, I.body(l <> lt, [])), [], I.body(l <> lt, []), 10n, k, 1, n) : List<&2, U32>}, NL.succ_zero(List.length(&2, U32, lt), Equal.sym(Nat, 0n, 1n+List.length(&2, U32, lt), hl)))
    case +x <> +xt:
      +b = I.body(lt, xt)
      +e = NL.succ_inj(List.length(&2, U32, b), List.length(&2, U32, lt), hl)
      Equal.cong(Nat, List<&2, U32>, m => CH.xstream(m, C.bytes(C.block(10n, CH.state(k, 1, n))), x <> b, 10n, k, U32.add(1, 1), n), List.length(&2, U32, lt), List.length(&2, U32, b), Equal.sym(Nat, List.length(&2, U32, b), List.length(&2, U32, lt), e))

# osela is owhen(tag matches, plaintext) of the ciphertext body(lead, xs),
# for the data xs = x0..x15 <> lead
law osq:
  for +pone: Nat
  for +kk: L.K
  for +sv: L.F
  for +a: P.A
X16P
  for +lead: List<&2, U32>
  for +k: CH.Key
  for +n: CH.Nonce
  for +hl: {List.length(&2, U32, I.body(lead, X16 <> lead)) == List.length(&2, U32, lead) : Nat}
  {I.osela(pone, kk, sv, a, lead, X16 <> lead, k, n) == I.owhen(S.eq(I.tail(lead, X16 <> lead), P.tag_ct(pone, kk, sv, a, I.body(lead, X16 <> lead))), CH.xstream(List.length(&2, U32, I.body(lead, X16 <> lead)), [], I.body(lead, X16 <> lead), 10n, k, 1, n)) : Maybe<&2, List<&2, U32>>}

def osq(pone, kk, sv, a, X16C, lead, k, n, hl):
  match a lead:
    case P.A{+h, +la} Nil{}: {==}
    case P.A{+h, +la} +l <> +lt:
      +xs = {X16 <> l <> lt : List<&2, U32>}
      +f = List.length(&2, U32, l <> lt)
      +b0 = C.block(10n, CH.state(k, 1, n))
      +bd = I.body(l <> lt, xs)
      +e1 = S.eq(I.tail(l <> lt, xs), P.tag_len(pone, kk, sv, la, P.absorb_pad(pone, bd, kk, h, 0n)))
      +d1 = I.odec(f, xs, b0, 10n, k, 1, n)
      +d2 = CH.xstream(List.length(&2, U32, bd), [], bd, 10n, k, 1, n)
      Equal.trans(Maybe<&2, List<&2, U32>>, I.owhen(I.opoly(f, xs, pone, kk, sv, la, h, 0n), d1), I.owhen(e1, d1), I.owhen(e1, d2),
        Equal.cong(Bool, Maybe<&2, List<&2, U32>>, z => I.owhen(z, d1), I.opoly(f, xs, pone, kk, sv, la, h, 0n), e1, opoly_eq(f, xs, pone, kk, sv, la, h, 0n)),
        Equal.cong(List<&2, U32>, Maybe<&2, List<&2, U32>>, z => I.owhen(e1, z), d1, d2, Equal.trans(List<&2, U32>, d1, I.fct(f, bd, b0, 10n, k, 1, n), d2, odec_eq(f, xs, b0, 10n, k, 1, n), ofuel(l, lt, xs, hl, k, n))))

# with the one-time key pk, the keystream key k and nonce n kept abstract
law oq:
  for +pk: List<&2, U32>
  for +aad: List<&2, U32>
X16P
  for +lead: List<&2, U32>
  for +k: CH.Key
  for +n: CH.Nonce
  for +hl: {List.length(&2, U32, I.body(lead, X16 <> lead)) == List.length(&2, U32, lead) : Nat}
  {I.osel(P.pad(32n, pk), aad, lead, X16 <> lead, k, n) == I.owhen(S.eq(I.tail(lead, X16 <> lead), P.mac_aead(pk, aad, I.body(lead, X16 <> lead))), CH.xstream(List.length(&2, U32, I.body(lead, X16 <> lead)), [], I.body(lead, X16 <> lead), 10n, k, 1, n)) : Maybe<&2, List<&2, U32>>}

def oq(pk, aad, X16C, lead, k, n, hl):
  match aad:
    case Nil{}: OQNIL
    case +x <> +rest: OQCONS

# the one-pass open is open_ref
law open_fused:
  for +key: List<&2, U32>
  for +nonce: List<&2, U32>
  for +aad: List<&2, U32>
  for +data: List<&2, U32>
  {I.open(key, nonce, aad, data) == I.open_ref(key, nonce, aad, data) : Maybe<&2, List<&2, U32>>}

def ofull(+key: List<&2, U32>, +nonce: List<&2, U32>, +aad: List<&2, U32>, X16T, +rest: List<&2, U32>) -> {I.open(key, nonce, aad, X16 <> rest) == I.open_ref(key, nonce, aad, X16 <> rest) : Maybe<&2, List<&2, U32>>}:
  +d = {X16 <> rest : List<&2, U32>}
  +ct = I.body(rest, d)
  +t = I.tail(rest, d)
  +hl = blen(rest, d, le16(List.length(&2, U32, rest)))
  Equal.trans(Maybe<&2, List<&2, U32>>, I.open(key, nonce, aad, d), I.owhen(S.eq(t, P.mac_aead(I.poly_key(key, nonce), aad, ct)), CH.xstream(List.length(&2, U32, ct), [], ct, 10n, CH.key(key), 1, CH.nonce(nonce))), I.open_ref(key, nonce, aad, d),
    oq(I.poly_key(key, nonce), aad, X16C, rest, CH.key(key), CH.nonce(nonce), hl),
    Equal.sym(Maybe<&2, List<&2, U32>>, I.open_ref(key, nonce, aad, d), I.owhen(S.eq(t, P.mac_aead(I.poly_key(key, nonce), aad, ct)), CH.xstream(List.length(&2, U32, ct), [], ct, 10n, CH.key(key), 1, CH.nonce(nonce))), otag_eq(S.eq(t, I.tag(key, nonce, aad, ct)), key, nonce, ct)))

def open_fused(key, nonce, aad, data):
NEST16
"""
    return (T.replace('OQNIL', one('[]')).replace('OQCONS', one('x <> rest'))
             .replace('X16P', X16P).replace('X16T', X16T).replace('X16C', X16C).replace('X16', X16)
             .replace('NEST16', nest16('  ', 'ofull(key, nonce, aad, %s, rest)' % X16C)))


if __name__ == '__main__':
    main()
