#!/usr/bin/env python3
"""Generates the repetitive Argon2 Bend files (implementation and proofs).

  python3 tools/generators/argon2_gen.py

Writes src/crypto/argon2/{types,blamka,sub}.bend and the generated proof
files proofs/crypto/argon2/{blamka,rows,cols,sub}.bend. Written by hand:
the rest of src/crypto/argon2/, spec/crypto/argon2/ and
proofs/crypto/argon2/.

A block is 128 64-bit lanes, as eight rows T.V{v0..v15} of sixteen lanes
(lane n is row n / 16, position n mod 16), each lane T.W{lo, hi}.
"""
import os

ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), '..', '..'))
SRC = os.path.join(ROOT, 'src/crypto/argon2')
PRF = os.path.join(ROOT, 'proofs/crypto/argon2')
HEADER = '# Generated by tools/generators/argon2_gen.py; do not edit by hand.\n'

# RFC 9106 section 3.6: the eight GB applications of the permutation P.
STEPS = [(0, 4, 8, 12), (1, 5, 9, 13), (2, 6, 10, 14), (3, 7, 11, 15),
         (0, 5, 10, 15), (1, 6, 11, 12), (2, 7, 8, 13), (3, 4, 9, 14)]


def write(path, text):
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, 'w') as f:
        f.write(text)


def csv(xs):
    return ','.join(xs)


def st(xs):
    return 'T.V{' + csv(xs) + '}'


def blk(rows):
    return 'A.B{' + csv(rows) + '}'


def lanes(p='l', n=128):
    return ['%s%d' % (p, i) for i in range(n)]


def block_of_lanes(ls):
    return blk([st(ls[16 * r:16 * r + 16]) for r in range(8)])


def col_lanes(i):
    """Lane numbers of column i, in state order: 2i, 2i+1, 2i+16, 2i+17, ..."""
    out = []
    for k in range(8):
        out += [16 * k + 2 * i, 16 * k + 2 * i + 1]
    return out


# ---------------------------------------------------------------- implementation

def types():
    return (HEADER + 'import Base\nimport ../blake/blake2b/types.bend as T\n\n'
            '# A 1024-byte block: 128 64-bit lanes as eight rows of sixteen\n'
            '# (lane n is row n / 16, position n mod 16).\n'
            'type Block is Data:\n  B{' + ', '.join('r%d: T.State' % i for i in range(8)) + '}\n')


def step_fns(k, a, b, c, d):
    """Step k of P: GB on positions a, b, c, d of the state."""
    others = [i for i in range(16) if i not in (a, b, c, d)]
    xs = ['x%d' % i for i in range(16)]
    s = ''
    # put_k: write the four results back
    params = ', '.join('x%d: T.Lane' % i for i in others)
    out = []
    for i in range(16):
        if i == a:
            out.append('ya')
        elif i == b:
            out.append('yb')
        elif i == c:
            out.append('yc')
        elif i == d:
            out.append('yd')
        else:
            out.append('x%d' % i)
    s += 'def put%d(q: T.Quad, %s) -> T.State:\n' % (k, params)
    s += '  match q:\n    case T.Q{ya,yb,yc,yd}:\n'
    s += '      ' + st(out) + '\n\n'
    s += '# GB on positions %d, %d, %d, %d.\n' % (a, b, c, d)
    s += 'def step%d(v: T.State) -> T.State:\n' % k
    s += '  match v:\n    case ' + st(xs) + ':\n'
    s += '      put%d(gb(x%d,x%d,x%d,x%d),%s)\n\n' % (k, a, b, c, d, csv('x%d' % i for i in others))
    return s


def blamka():
    s = HEADER
    s += ('import Base\n'
          'import ../../math/w64.bend as X\n'
          'import ../blake/blake2b/types.bend as T\n'
          'import ../blake/blake2b/lane.bend as L\n'
          'import ./types.bend as A\n\n')
    s += ('# The low half of a lane (trunc in RFC 9106).\n'
          'def lo(x: T.Lane) -> U32:\n  match x:\n    case T.W{l,h}: l\n\n'
          '# The full 64-bit product of two U32 (src/math/w64.bend, proved).\n'
          'def prod(+a: U32, +b: U32) -> T.Lane:\n'
          '  +m = X.mul32(a,b)\n'
          '  T.W{X.lo(m),X.hi(m)}\n\n'
          '# fBlaMka(x, y) = x + y + 2 * trunc(x) * trunc(y) mod 2^64 (RFC 9106 section 3.6).\n'
          'def bla(x: T.Lane, y: T.Lane) -> T.Lane:\n'
          '  match x y:\n'
          '    case T.W{+xl,+xh} T.W{+yl,+yh}:\n'
          '      +p = prod(xl,yl)\n'
          '      L.add(L.add(T.W{xl,xh},T.W{yl,yh}),L.add(p,p))\n\n')
    s += ('# GB (RFC 9106 section 3.6), one assignment pair per function.\n'
          'def gb4(+a2: T.Lane, +b1: T.Lane, +c2: T.Lane, +d2: T.Lane) -> T.Quad:\n'
          '  T.Q{a2,L.rot63(L.xor(b1,c2)),c2,d2}\n\n'
          'def gb3(+a2: T.Lane, +b1: T.Lane, +c1: T.Lane, +d1: T.Lane) -> T.Quad:\n'
          '  +d2 = L.rot16(L.xor(d1,a2))\n'
          '  gb4(a2,b1,bla(c1,d2),d2)\n\n'
          'def gb2(+a1: T.Lane, +b: T.Lane, +c1: T.Lane, +d1: T.Lane) -> T.Quad:\n'
          '  +b1 = L.rot24(L.xor(b,c1))\n'
          '  gb3(bla(a1,b1),b1,c1,d1)\n\n'
          'def gb1(+a1: T.Lane, +b: T.Lane, +c: T.Lane, +d: T.Lane) -> T.Quad:\n'
          '  +d1 = L.rot32(L.xor(d,a1))\n'
          '  gb2(a1,b,bla(c,d1),d1)\n\n'
          'def gb(+a: T.Lane, +b: T.Lane, +c: T.Lane, +d: T.Lane) -> T.Quad:\n'
          '  gb1(bla(a,b),b,c,d)\n\n')
    for k, (a, b, c, d) in enumerate(STEPS):
        s += step_fns(k, a, b, c, d)
    s += ('# The permutation P on sixteen lanes.\n'
          'def p(v: T.State) -> T.State:\n'
          '  step7(step6(step5(step4(step3(step2(step1(step0(v))))))))\n\n')
    # rows
    s += ('# P on each row: lanes 16i .. 16i+15.\n'
          'def rows(b: A.Block) -> A.Block:\n'
          '  match b:\n    case A.B{r0,r1,r2,r3,r4,r5,r6,r7}:\n'
          '      A.B{p(r0),p(r1),p(r2),p(r3),p(r4),p(r5),p(r6),p(r7)}\n\n')
    # cols
    L = lanes()
    cs = ['c%d' % i for i in range(8)]
    ys = [['y%d_%d' % (i, j) for j in range(16)] for i in range(8)]
    s += '# The eight permuted columns back into rows: column i holds lanes 2i, 2i+1 of every row.\n'
    s += 'def untr(%s) -> A.Block:\n' % ', '.join('%s: T.State' % c for c in cs)
    s += '  match %s:\n' % ' '.join(cs)
    s += '    case %s:\n' % ' '.join(st(y) for y in ys)
    rows = []
    for k in range(8):
        row = []
        for i in range(8):
            row += [ys[i][2 * k], ys[i][2 * k + 1]]
        rows.append(st(row))
    s += '      ' + blk(rows) + '\n\n'
    s += ('# P on each column: lanes 2i, 2i+1, 2i+16, 2i+17, .., 2i+112, 2i+113.\n'
          'def cols(b: A.Block) -> A.Block:\n'
          '  match b:\n    case ' + block_of_lanes(L) + ':\n'
          '      untr(' + csv('p(' + st(['l%d' % n for n in col_lanes(i)]) + ')' for i in range(8)) + ')\n\n')
    # xor
    xs = lanes('x')
    zs = lanes('y')
    s += ('# Lane-wise XOR of two rows, and of two blocks (row by row).\n'
          'def xs(s: T.State, t: T.State) -> T.State:\n'
          '  match s t:\n    case ' + st(['x%d' % i for i in range(16)]) + ' ' + st(['y%d' % i for i in range(16)]) + ':\n'
          '      ' + st(['L.xor(x%d,y%d)' % (i, i) for i in range(16)]) + '\n\n'
          'def xor(x: A.Block, y: A.Block) -> A.Block:\n'
          '  match x y:\n    case A.B{x0,x1,x2,x3,x4,x5,x6,x7} A.B{y0,y1,y2,y3,y4,y5,y6,y7}:\n'
          '      A.B{' + csv('xs(x%d,y%d)' % (i, i) for i in range(8)) + '}\n\n')
    s += ('# G(X, Y) = P(R) XOR R with R = X XOR Y, P on the rows then the columns\n'
          '# (RFC 9106 section 3.5).\n'
          'def fin(+r: A.Block) -> A.Block:\n'
          '  xor(cols(rows(r)),r)\n\n'
          'def compress(x: A.Block, y: A.Block) -> A.Block:\n'
          '  fin(xor(x,y))\n\n'
          '# Version 0x13 passes after the first: G(X, Y) XOR the block being overwritten.\n'
          'def compress_xor(x: A.Block, y: A.Block, old: A.Block) -> A.Block:\n'
          '  xor(compress(x,y),old)\n\n'
          '# The all-zero block.\n'
          'def zero() -> A.Block:\n'
          '  ' + block_of_lanes(['T.W{0,0}'] * 128) + '\n')
    return s


def sub():
    """Blocks as lists of 256 words (the memory stores lane n at words 2n, 2n+1)."""
    s = HEADER
    s += ('import Base\n'
          'import ../blake/blake2b/types.bend as T\n'
          'import ./types.bend as A\n\n')
    wl = []
    for n in range(128):
        wl += ['l%d' % n, 'h%d' % n]
    rl = []
    for n in range(16):
        rl += ['l%d' % n, 'h%d' % n]
    s += ('# The 32 words of a row: lane n is words 2n (low) and 2n+1 (high).\n'
          'def row_words(v: T.State) -> List<&2,U32>:\n'
          '  match v:\n    case ' + st(['T.W{l%d,h%d}' % (n, n) for n in range(16)]) + ':\n'
          '      [' + csv(rl) + ']\n\n'
          'def app(xs: List<&2,U32>, ys: List<&2,U32>) -> List<&2,U32>:\n'
          '  List.append(&2, U32, xs, ys)\n\n'
          '# The 256 words of a block, row after row.\n'
          'def words(b: A.Block) -> List<&2,U32>:\n'
          '  match b:\n    case A.B{r0,r1,r2,r3,r4,r5,r6,r7}:\n'
          '      ' + ''.join('app(row_words(r%d),' % i for i in range(8)) + 'Nil{}' + ')' * 8 + '\n\n')
    w = ['w%d' % i for i in range(32)]
    s += ('# Sixteen lanes from 32 words, and the words left over.\n'
          'def row(ws: List<&2,U32>) -> T.State & List<&2,U32>:\n'
          '  match ws:\n'
          '    case ' + ' <> '.join(w) + ' <> rest:\n'
          '      (' + st(['T.W{w%d,w%d}' % (2 * i, 2 * i + 1) for i in range(16)]) + ',rest)\n'
          '    case _: (' + st(['T.W{0,0}'] * 16) + ',Nil{})\n\n')
    for r in reversed(range(8)):
        prev = ''.join('r%d: T.State, ' % i for i in range(r))
        s += 'def rows8_%d(%sp: T.State & List<&2,U32>) -> A.Block:\n' % (r, prev)
        s += '  (r%d,ws) = p\n' % r
        if r < 7:
            s += '  rows8_%d(%srow(ws))\n\n' % (r + 1, ''.join('r%d,' % i for i in range(r + 1)))
        else:
            s += '  A.B{r0,r1,r2,r3,r4,r5,r6,r7}\n\n'
    s += '# The block of 256 words (the inverse of words).\n'
    s += 'def rows8(ws: List<&2,U32>) -> A.Block:\n  rows8_0(row(ws))\n'
    return s


def proof_blamka():
    """proofs/crypto/argon2/blamka.bend: P, the rows and columns, XOR and G."""
    s = HEADER
    s += ('import Base\n'
          'import ../../../src/crypto/blake/blake2b/types.bend as T\n'
          'import ../../../src/crypto/argon2/types.bend as A\n'
          'import ../../../src/crypto/argon2/blamka.bend as I\n'
          'import ../../../spec/crypto/argon2/blamka.bend as S\n'
          'import ./gb.bend as GB\n\n'
          '# The compression function of the implementation equals G of the\n'
          '# specification for every two blocks: P step by step (each step one GB,\n'
          '# gb.bend), then P on the rows and on the columns, then the XORs.\n'
          '# Every function the proofs apply to symbolic arguments matches its\n'
          '# argument first, so the checker keeps such calls folded.\n\n')
    xs = ['x%d' % i for i in range(16)]
    for k, (a, b, c, d) in enumerate(STEPS):
        others = [i for i in range(16) if i not in (a, b, c, d)]
        oth = csv('x%d' % i for i in others)
        s += ('def step%d_correct(+v: T.State) -> {I.step%d(v) == S.GBi(v, %dn, %dn, %dn, %dn) : T.State}:\n'
              '  match v:\n'
              '    case %s:\n'
              '      Equal.cong(T.Quad, T.State, q => I.put%d(q, %s), I.gb(x%d, x%d, x%d, x%d), S.GB(x%d, x%d, x%d, x%d), GB.gb_correct(x%d, x%d, x%d, x%d))\n\n'
              % (k, k, a, b, c, d, st(xs), k, oth, a, b, c, d, a, b, c, d, a, b, c, d))
    # p_correct
    sv = ['v']
    for k, (a, b, c, d) in enumerate(STEPS):
        sv.append('S.GBi(%s, %dn, %dn, %dn, %dn)' % (sv[-1], a, b, c, d))
    def impl_after(k, z):
        # I.step7(..I.step_k(z)..)
        t = z
        for j in range(k, 8):
            t = 'I.step%d(%s)' % (j, t)
        return t
    def chain(k):
        # proof of impl_after(k, sv[k]) == sv[8]
        if k == 7:
            return 'step7_correct(%s)' % sv[7]
        return ('Equal.trans(T.State, %s, %s, %s,\n    Equal.cong(T.State, T.State, z => %s, I.step%d(%s), %s, step%d_correct(%s)),\n    %s)'
                % (impl_after(k, sv[k]), impl_after(k + 1, sv[k + 1]), sv[8], impl_after(k + 1, 'z'), k, sv[k], sv[k + 1], k, sv[k], chain(k + 1)))
    s += ('# P, one GB at a time.\n'
          'def p_correct(+v: T.State) -> {I.p(v) == S.P(v) : T.State}:\n'
          '  ' + chain(0) + '\n\n')
    # rows
    L = lanes()
    V = [st(L[16 * r:16 * r + 16]) for r in range(8)]
    def rows_mid(k):
        return blk(['S.P(%s)' % V[r] if r < k else 'I.p(%s)' % V[r] for r in range(8)])
    def rows_chain(k):
        if k == 8:
            return None
        hole = blk(['S.P(%s)' % V[r] if r < k else ('z' if r == k else 'I.p(%s)' % V[r]) for r in range(8)])
        step = 'Equal.cong(T.State, A.Block, z => %s, I.p(%s), S.P(%s), p_correct(%s))' % (hole, V[k], V[k], V[k])
        rest = rows_chain(k + 1)
        if rest is None:
            return step
        return 'Equal.trans(A.Block, %s, %s, %s,\n        %s,\n        %s)' % (rows_mid(k), rows_mid(k + 1), rows_mid(8), step, rest)
    s += ('# P on the rows: the rows are the specification\'s gathered lanes.\n'
          'def rows_correct(+b: A.Block) -> {I.rows(b) == S.rows(b) : A.Block}:\n'
          '  match b:\n'
          '    case ' + block_of_lanes(L) + ':\n'
          '      ' + rows_chain(0) + '\n\n')
    # cols
    C = [st(['l%d' % n for n in col_lanes(i)]) for i in range(8)]
    def cols_mid(k):
        return 'I.untr(' + csv('S.P(%s)' % C[i] if i < k else 'I.p(%s)' % C[i] for i in range(8)) + ')'
    def cols_chain(k):
        if k == 8:
            return None
        hole = 'I.untr(' + csv('S.P(%s)' % C[i] if i < k else ('z' if i == k else 'I.p(%s)' % C[i]) for i in range(8)) + ')'
        step = 'Equal.cong(T.State, A.Block, z => %s, I.p(%s), S.P(%s), p_correct(%s))' % (hole, C[k], C[k], C[k])
        rest = cols_chain(k + 1)
        if rest is None:
            return step
        return 'Equal.trans(A.Block, %s, %s, %s,\n        %s,\n        %s)' % (cols_mid(k), cols_mid(k + 1), cols_mid(8), step, rest)
    s += ('# P on the columns: column i of the specification is lanes 2i, 2i+1, 2i+16, ...\n'
          'def cols_correct(+b: A.Block) -> {I.cols(b) == S.cols(b) : A.Block}:\n'
          '  match b:\n'
          '    case ' + block_of_lanes(L) + ':\n'
          '      ' + cols_chain(0) + '\n\n')
    # xor
    xw = ['T.W{a%d,b%d}' % (i, i) for i in range(128)]
    yw = ['T.W{c%d,d%d}' % (i, i) for i in range(128)]
    s += ('# Two rows XORed, lane by lane.\n'
          'def xs_correct(+s: T.State, +t: T.State) -> {I.xs(s, t) == S.xor_state(s, t) : T.State}:\n'
          '  match s t:\n'
          '    case ' + st(['T.W{a%d,b%d}' % (i, i) for i in range(16)]) + ' ' + st(['T.W{c%d,d%d}' % (i, i) for i in range(16)]) + ':\n'
          '      {==}\n\n')
    xr = ['x%d' % i for i in range(8)]
    yr = ['y%d' % i for i in range(8)]
    out = ('# X XOR Y, row by row.\n'
           'def xor_correct(+x: A.Block, +y: A.Block) -> {I.xor(x, y) == S.xor(x, y) : A.Block}:\n'
           '  match x y:\n'
           '    case A.B{+x0,+x1,+x2,+x3,+x4,+x5,+x6,+x7} A.B{+y0,+y1,+y2,+y3,+y4,+y5,+y6,+y7}:\n')
    cur = ['I.xs(x%d, y%d)' % (i, i) for i in range(8)]
    for i in range(8):
        pat = list(cur); pat[i] = '_'
        out += ('      %%Equal.sym(T.State, I.xs(x%d, y%d), S.xor_state(x%d, y%d), xs_correct(x%d, y%d)) : {A.B{%s} == S.xor(A.B{%s}, A.B{%s}) : A.Block}\n'
                % (i, i, i, i, i, i, ', '.join(pat), csv(xr), csv(yr)))
        cur[i] = 'S.xor_state(x%d, y%d)' % (i, i)
    out += '      {==}\n\n'
    s += out
    # compress
    R = 'S.xor(x, y)'
    s += ('# G(X, Y): the compression function.\n'
          'def compress_correct(+x: A.Block, +y: A.Block) -> {I.compress(x, y) == S.G(x, y) : A.Block}:\n'
          '  Equal.trans(A.Block, I.xor(I.cols(I.rows(I.xor(x, y))), I.xor(x, y)), I.xor(I.cols(I.rows(%(R)s)), %(R)s), S.xor(S.cols(S.rows(%(R)s)), %(R)s),\n'
          '    Equal.cong(A.Block, A.Block, +z => I.xor(I.cols(I.rows(z)), z), I.xor(x, y), %(R)s, xor_correct(x, y)),\n'
          '    Equal.trans(A.Block, I.xor(I.cols(I.rows(%(R)s)), %(R)s), I.xor(I.cols(S.rows(%(R)s)), %(R)s), S.xor(S.cols(S.rows(%(R)s)), %(R)s),\n'
          '      Equal.cong(A.Block, A.Block, z => I.xor(I.cols(z), %(R)s), I.rows(%(R)s), S.rows(%(R)s), rows_correct(%(R)s)),\n'
          '      Equal.trans(A.Block, I.xor(I.cols(S.rows(%(R)s)), %(R)s), I.xor(S.cols(S.rows(%(R)s)), %(R)s), S.xor(S.cols(S.rows(%(R)s)), %(R)s),\n'
          '        Equal.cong(A.Block, A.Block, z => I.xor(z, %(R)s), I.cols(S.rows(%(R)s)), S.cols(S.rows(%(R)s)), cols_correct(S.rows(%(R)s))),\n'
          '        xor_correct(S.cols(S.rows(%(R)s)), %(R)s))))\n\n' % {'R': R})
    s += ('# Version 0x13 passes after the first: G(X, Y) XOR the old block.\n'
          'def compress_xor_correct(+x: A.Block, +y: A.Block, +old: A.Block) -> {I.compress_xor(x, y, old) == S.xor(S.G(x, y), old) : A.Block}:\n'
          '  Equal.trans(A.Block, I.xor(I.compress(x, y), old), I.xor(S.G(x, y), old), S.xor(S.G(x, y), old),\n'
          '    Equal.cong(A.Block, A.Block, z => I.xor(z, old), I.compress(x, y), S.G(x, y), compress_correct(x, y)),\n'
          '    xor_correct(S.G(x, y), old))\n\n'
          '# The all-zero block.\n'
          'def zero_correct() -> {I.zero() == S.zero() : A.Block}:\n'
          '  {==}\n')
    return s


# ---------------------------------------------------------------- block access (memory)

W32 = 32


def row_state(xs):
    """T.V of sixteen lanes from 32 word terms (lane n is words 2n, 2n+1)."""
    return 'T.V{' + ', '.join('T.W{%s, %s}' % (xs[2 * k], xs[2 * k + 1]) for k in range(16)) + '}'


def access():
    """src/crypto/argon2/access.bend: blocks read and written word by word
    with Base's O(1) Array.get / Array.set, no intermediate lists."""
    s = (HEADER + 'import Base\nimport ../blake/blake2b/types.bend as T\nimport ./types.bend as A\n\n'
         '# Block b of the memory is words 256 b .. 256 b + 255, row after row (lane n\n'
         '# of a row at words 2n, low half, and 2n + 1, high half).\n\n'
         '# ---------------------------------------------------------------- reading\n\n'
         '# rr_k: words i .. i + k - 1 read (w0 ..), pair holds the memory and word i + k.\n')
    for k in reversed(range(W32)):
        ws = ''.join('w%d: U32, ' % j for j in range(k))
        s += 'def rr%d(+i: Nat, %spair: Array<U32> & U32) -> Array<U32> & T.State:\n' % (k, ws)
        s += '  (a, w%d) = pair\n' % k
        if k == W32 - 1:
            s += '  (a, %s)\n\n' % row_state(['w%d' % j for j in range(W32)])
        else:
            s += '  rr%d(i, %sArray.get(U32, a, U32.from_nat(Nat.add(%dn, i))))\n\n' % (k + 1, ''.join('w%d, ' % j for j in range(k + 1)), k + 1)
    s += ('# The row of words i .. i + 31; the memory is handed back.\n'
          'def row(+i: Nat, a: Array<U32>) -> Array<U32> & T.State:\n'
          '  rr0(i, Array.get(U32, a, U32.from_nat(i)))\n\n'
          '# rd_r: rows 0 .. r - 1 read, p holds the memory and row r (words i + 32 r ..).\n')
    for r in reversed(range(8)):
        rs = ''.join('r%d: T.State, ' % j for j in range(r))
        s += 'def rd%d(+i: Nat, %sp: Array<U32> & T.State) -> Array<U32> & A.Block:\n' % (r, rs)
        s += '  (a, r%d) = p\n' % r
        if r == 7:
            s += '  (a, A.B{%s})\n\n' % ', '.join('r%d' % j for j in range(8))
        else:
            s += '  rd%d(i, %srow(Nat.add(%dn, i), a))\n\n' % (r + 1, ''.join('r%d, ' % j for j in range(r + 1)), 32 * (r + 1))
    s += ('# Block b; the memory is handed back.\n'
          'def get(+b: Nat, a: Array<U32>) -> Array<U32> & A.Block:\n'
          '  +i = Nat.mul(b, 256n)\n'
          '  rd0(i, row(i, a))\n\n'
          '# ---------------------------------------------------------------- writing\n\n'
          '# The row v stored at words i .. i + 31.\n'
          'def wrow(v: T.State, +i: Nat, a: Array<U32>) -> Array<U32>:\n'
          '  match v:\n'
          '    case %s:\n' % row_state(['w%d' % j for j in range(W32)]))
    for k in range(1, W32):
        s += '      +i%d = Nat.add(%s, 1n)\n' % (k, 'i' if k == 1 else 'i%d' % (k - 1))
    e = 'a'
    for k in range(W32):
        e = 'Array.set(U32, %s, U32.from_nat(%s), w%d)' % (e, 'i' if k == 0 else 'i%d' % k, k)
    s += '      ' + e + '\n\n'
    nx = 'i'
    for k in range(W32):
        nx = 'Nat.add(%s, 1n)' % nx
    s += ('# i + 32, as 32 steps of one.\n'
          'def nx(+i: Nat) -> Nat:\n'
          '  ' + nx + '\n\n'
          '# The memory with block b replaced by v.\n'
          'def put(+b: Nat, v: A.Block, a: Array<U32>) -> Array<U32>:\n'
          '  match v:\n'
          '    case A.B{r0, r1, r2, r3, r4, r5, r6, r7}:\n'
          '      +i0 = Nat.mul(b, 256n)\n')
    for r in range(1, 8):
        s += '      +i%d = nx(i%d)\n' % (r, r - 1)
    e = 'a'
    for r in range(8):
        e = 'wrow(r%d, i%d, %s)' % (r, r, e)
    s += '      ' + e + '\n'
    return s


def proof_access():
    """proofs/crypto/argon2/access.bend: access.bend's reads on the mirror tree
    of a word list, and its writes against memory.bend's word-by-word wr."""
    AR_ = 'AR.thaw(U32, MEM.tree(d, ws))'
    D = 'SC.drop(U32, ws, i)'
    s = (HEADER + 'import Base\n'
         'import ../../../spec/lib/common.bend as SC\n'
         'import ../../lib/array.bend as AR\n'
         'import ../../lib/nat.bend as N\n'
         'import ../../lib/logic.bend as L\n'
         'import ../../../src/crypto/blake/blake2b/types.bend as T\n'
         'import ../../../src/crypto/argon2/types.bend as A\n'
         'import ../../../src/crypto/argon2/sub.bend as SB\n'
         'import ../../../src/crypto/argon2/access.bend as X\n'
         'import ./memory.bend as MEM\n\n'
         '# ---------------------------------------------------------------- reading\n\n'
         '# Word k + i of the tree of ws is word k of ws from i on.\n'
         'def get_word_drop(+d: Nat, +ws: List<&2, U32>, +i: Nat, +k: Nat, +hd: {Nat.is_lt(d, 32n) == True{} : Bool}, +hl: {SC.length(U32, ws) == SC.pow2(d) : Nat}, +h: {Nat.is_lt(Nat.add(k, i), SC.pow2(d)) == True{} : Bool}) -> {Array.get(U32, %(AR)s, U32.from_nat(Nat.add(k, i))) == (%(AR)s, MEM.nthv(%(D)s, k)) : Array<U32> & U32}:\n'
         '  -ar = %(AR)s\n'
         '  +e = Equal.trans(U32, MEM.nthv(ws, Nat.add(k, i)), MEM.nthv(ws, Nat.add(i, k)), MEM.nthv(%(D)s, k),\n'
         '    Equal.cong(Nat, U32, z => MEM.nthv(ws, z), Nat.add(k, i), Nat.add(i, k), N.add_comm(k, i)),\n'
         '    Equal.sym(U32, MEM.nthv(%(D)s, k), MEM.nthv(ws, Nat.add(i, k)), MEM.nth_drop(ws, i, k)))\n'
         '  Equal.trans(Array<U32> & U32, Array.get(U32, ar, U32.from_nat(Nat.add(k, i))), (ar, MEM.nthv(ws, Nat.add(k, i))), (ar, MEM.nthv(%(D)s, k)),\n'
         '    MEM.get_word(d, ws, Nat.add(k, i), hd, hl, h),\n'
         '    Equal.cong(U32, Array<U32> & U32, z => (ar, z), MEM.nthv(ws, Nat.add(k, i)), MEM.nthv(%(D)s, k), e))\n\n'
         '# k + i < n from k < m and m + i <= n.\n'
         'def lt_k(+k: Nat, +m: Nat, +i: Nat, +n: Nat, +hk: {Nat.is_lt(k, m) == True{} : Bool}, +h: {Nat.is_le(Nat.add(m, i), n) == True{} : Bool}) -> {Nat.is_lt(Nat.add(k, i), n) == True{} : Bool}:\n'
         '  N.lt_le_trans(Nat.add(k, i), Nat.add(m, i), n, N.lt_add_r2(k, m, i, hk), h)\n\n'
         '# The row of words 0 .. 31 of ys.\n'
         'def rowl(+ys: List<&2, U32>) -> T.State:\n'
         '  %(ROWL)s\n\n') % {'AR': AR_, 'D': D, 'ROWL': row_state(['MEM.nthv(ys, %dn)' % j for j in range(W32)])}
    hyp = '+d: Nat, +ws: List<&2, U32>, +i: Nat, +hd: {Nat.is_lt(d, 32n) == True{} : Bool}, +hl: {SC.length(U32, ws) == SC.pow2(d) : Nat}, +h: {Nat.is_le(Nat.add(32n, i), SC.pow2(d)) == True{} : Bool}'
    for k in reversed(range(W32)):
        ws = ''.join(', +w%d: U32' % j for j in range(k))
        xs = ['w%d' % j if j < k else 'MEM.nthv(%s, %dn)' % (D, j) for j in range(W32)]
        rhs = '(%s, %s)' % (AR_, row_state(xs))
        args = ''.join('w%d, ' % j for j in range(k))
        s += 'def rr%d_eq(%s%s) -> {X.rr%d(i, %s(%s, MEM.nthv(%s, %dn))) == %s : Array<U32> & T.State}:\n' % (k, hyp, ws, k, args, AR_, D, k, rhs)
        if k == W32 - 1:
            s += '  {==}\n\n'
        else:
            nxt = 'MEM.nthv(%s, %dn)' % (D, k)
            s += ('  %%Equal.sym(Array<U32> & U32, Array.get(U32, %(AR)s, U32.from_nat(Nat.add(%(k1)dn, i))), (%(AR)s, MEM.nthv(%(D)s, %(k1)dn)), get_word_drop(d, ws, i, %(k1)dn, hd, hl, lt_k(%(k1)dn, 32n, i, SC.pow2(d), {==}, h))) : {X.rr%(k1)d(i, %(args)s%(nxt)s, _) == %(rhs)s : Array<U32> & T.State}\n'
                  '  rr%(k1)d_eq(d, ws, i, hd, hl, h, %(args)s%(nxt)s)\n\n') % {'AR': AR_, 'D': D, 'k1': k + 1, 'args': args, 'nxt': nxt, 'rhs': rhs}
    s += ('# X.row reads the row of words i .. i + 31 of the tree of ws.\n'
          'def row_eq(%s) -> {X.row(i, %s) == (%s, rowl(%s)) : Array<U32> & T.State}:\n'
          '  %%Equal.sym(Array<U32> & U32, Array.get(U32, %s, U32.from_nat(Nat.add(0n, i))), (%s, MEM.nthv(%s, 0n)), get_word_drop(d, ws, i, 0n, hd, hl, lt_k(0n, 32n, i, SC.pow2(d), {==}, h))) : {X.rr0(i, _) == (%s, rowl(%s)) : Array<U32> & T.State}\n'
          '  rr0_eq(d, ws, i, hd, hl, h)\n\n') % (hyp, AR_, AR_, D, AR_, AR_, D, AR_, D)
    # rows
    hypb = '+d: Nat, +ws: List<&2, U32>, +i: Nat, +hd: {Nat.is_lt(d, 32n) == True{} : Bool}, +hl: {SC.length(U32, ws) == SC.pow2(d) : Nat}, +h: {Nat.is_le(Nat.add(256n, i), SC.pow2(d)) == True{} : Bool}'
    def base(r):
        return 'i' if r == 0 else 'Nat.add(%dn, i)' % (32 * r)
    def rowd(r):
        return 'rowl(SC.drop(U32, ws, %s))' % base(r)
    s += ('# m + i <= n from m <= 256 and 256 + i <= n.\n'
          'def le_k(+m: Nat, +i: Nat, +n: Nat, +hm: {Nat.is_lt(m, 256n) == True{} : Bool}, +h: {Nat.is_le(Nat.add(256n, i), n) == True{} : Bool}) -> {Nat.is_le(Nat.add(m, i), n) == True{} : Bool}:\n'
          '  N.lt_le(Nat.add(m, i), n, lt_k(m, 256n, i, n, hm, h))\n\n')
    for r in reversed(range(8)):
        rs = ''.join(', +r%d: T.State' % j for j in range(r))
        args = ''.join('r%d, ' % j for j in range(r))
        rhs = '(%s, A.B{%s})' % (AR_, ', '.join(['r%d' % j for j in range(r)] + [rowd(j) for j in range(r, 8)]))
        s += 'def rd%d_eq(%s%s) -> {X.rd%d(i, %s(%s, %s)) == %s : Array<U32> & A.Block}:\n' % (r, hypb, rs, r, args, AR_, rowd(r), rhs)
        if r == 7:
            s += '  {==}\n\n'
        else:
            hle = 'h' if r == 6 else 'le_k(%dn, i, SC.pow2(d), {==}, h)' % (32 * (r + 2))
            s += ('  %%Equal.sym(Array<U32> & T.State, X.row(%(b1)s, %(AR)s), (%(AR)s, %(row1)s), row_eq(d, ws, %(b1)s, hd, hl, %(hle)s)) : {X.rd%(r1)d(i, %(args)s%(rowr)s, _) == %(rhs)s : Array<U32> & A.Block}\n'
                  '  rd%(r1)d_eq(d, ws, i, hd, hl, h, %(args)s%(rowr)s)\n\n') % {
                      'b1': base(r + 1), 'AR': AR_, 'row1': rowd(r + 1), 'hle': hle, 'r1': r + 1, 'args': args, 'rowr': rowd(r), 'rhs': rhs}
    rhs = '(%s, A.B{%s})' % (AR_, ', '.join(rowd(j) for j in range(8)))
    s += ('# X.get reads the eight rows of block b of the tree of ws.\n'
          'def get_eq(+d: Nat, +ws: List<&2, U32>, +b: Nat, +hd: {Nat.is_lt(d, 32n) == True{} : Bool}, +hl: {SC.length(U32, ws) == SC.pow2(d) : Nat}, +h: {Nat.is_le(Nat.add(256n, Nat.mul(b, 256n)), SC.pow2(d)) == True{} : Bool}) -> {X.get(b, %(AR)s) == %(rhs)s : Array<U32> & A.Block}:\n'
          '  +i = Nat.mul(b, 256n)\n'
          '  %%Equal.sym(Array<U32> & T.State, X.row(i, %(AR)s), (%(AR)s, %(row0)s), row_eq(d, ws, i, hd, hl, le_k(32n, i, SC.pow2(d), {==}, h))) : {X.rd0(i, _) == %(rhs)s : Array<U32> & A.Block}\n'
          '  rd0_eq(d, ws, i, hd, hl, h)\n\n') % {'AR': AR_, 'rhs': rhs.replace('i)', 'Nat.mul(b, 256n))').replace('ws, i)', 'ws, Nat.mul(b, 256n))'), 'row0': rowd(0)}
    # rows of a block's words
    ls = ['l%d' % j for j in range(W32)]
    pat = row_state(ls)
    s += ('# ---------------------------------------------------------------- a block\'s words\n\n'
          'def rowl_app(+r: T.State, +x: List<&2, U32>, +e: List<&2, U32>) -> {rowl(SC.append(U32, SB.app(SB.row_words(r), x), e)) == r : T.State}:\n'
          '  match r:\n'
          '    case %s:\n'
          '      {==}\n\n'
          'def drop_row(+r: T.State, +x: List<&2, U32>, +e: List<&2, U32>) -> {SC.drop(U32, SC.append(U32, SB.app(SB.row_words(r), x), e), 32n) == SC.append(U32, x, e) : List<&2, U32>}:\n'
          '  match r:\n'
          '    case %s:\n'
          '      Equal.trans(List<&2, U32>, SC.drop(U32, SC.append(U32, SB.app(SB.row_words(%s), x), e), 32n), SC.drop(U32, SC.append(U32, x, e), 0n), SC.append(U32, x, e), {==}, MEM.drop_zero(SC.append(U32, x, e)))\n\n') % (pat, pat, pat)
    # writing
    s += ('# ---------------------------------------------------------------- writing\n\n'
          '# Storing a row with MEM.wr is X.wrow, and wr goes on at i + 32.\n'
          'def wr_row(+r: T.State, +x: List<&2, U32>, +i: Nat, -a: Array<U32>) -> {MEM.wr(SB.app(SB.row_words(r), x), i, a) == MEM.wr(x, X.nx(i), X.wrow(r, i, a)) : Array<U32>}:\n'
          '  match r:\n'
          '    case %s:\n'
          '      {==}\n\n') % pat
    def tail(r):
        e = 'Nil{}'
        for j in reversed(range(r, 8)):
            e = 'SB.app(SB.row_words(r%d), %s)' % (j, e)
        return e
    def idx(r):
        e = 'Nat.mul(b, 256n)'
        for _ in range(r):
            e = 'X.nx(%s)' % e
        return e
    def arr(r):
        e = 'a'
        for j in range(r):
            e = 'X.wrow(r%d, %s, %s)' % (j, idx(j), e)
        return e
    s += ('# X.put is MEM.wr of the block\'s words.\n'
          'def put_eq(+b: Nat, +v: A.Block, -a: Array<U32>) -> {X.put(b, v, a) == MEM.wr(SB.words(v), Nat.mul(b, 256n), a) : Array<U32>}:\n'
          '  match v:\n'
          '    case A.B{+r0, +r1, +r2, +r3, +r4, +r5, +r6, +r7}:\n'
          '      -goal = X.put(b, A.B{r0, r1, r2, r3, r4, r5, r6, r7}, a)\n')
    for r in range(8):
        s += ('      %%Equal.sym(Array<U32>, MEM.wr(%s, %s, %s), MEM.wr(%s, %s, %s), wr_row(r%d, %s, %s, %s)) : {goal == _ : Array<U32>}\n'
              % (tail(r), idx(r), arr(r), tail(r + 1), idx(r + 1), arr(r + 1), r, tail(r + 1), idx(r), arr(r)))
    s += '      {==}\n'
    return s


def main():
    write(os.path.join(SRC, 'types.bend'), types())
    write(os.path.join(SRC, 'blamka.bend'), blamka())
    write(os.path.join(SRC, 'sub.bend'), sub())
    write(os.path.join(PRF, 'blamka.bend'), proof_blamka())
    write(os.path.join(SRC, 'access.bend'), access())
    write(os.path.join(PRF, 'access.bend'), proof_access())


if __name__ == '__main__':
    main()
