#!/usr/bin/env python3
"""Emit the repetitive BLAKE2s Bend sources (implementation and proofs).

  python3 tools/generators/blake2s_gen.py

Writes, relative to the repository root:
  src/crypto/blake/blake2s/compress.bend   unrolled compression function F
  src/crypto/blake/blake2s/blake2s.bend    block reads, final block, public API
  proofs/crypto/blake/blake2s/bytes.bend   byte <-> word bridge lemmas
  proofs/crypto/blake/blake2s/compress.bend  F refinement (per round, then composed)
  proofs/crypto/blake/blake2s/reads.bend   block-read refinement and the API theorem

The hand-written files (types.bend, hex.bend, proof.bend, laws.bend; the spec is spec/crypto/blake/blake2s.bend)
are not generated.
"""
import os

ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), '..', '..'))
SRC = os.path.join(ROOT, 'src/crypto/blake/blake2s')
PRF = os.path.join(ROOT, 'proofs/crypto/blake/blake2s')

IV = [0x6A09E667, 0xBB67AE85, 0x3C6EF372, 0xA54FF53A,
      0x510E527F, 0x9B05688C, 0x1F83D9AB, 0x5BE0CD19]
SIGMA = [
    [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15],
    [14, 10, 4, 8, 9, 15, 13, 6, 1, 12, 0, 2, 11, 7, 5, 3],
    [11, 8, 12, 0, 5, 2, 15, 13, 10, 14, 3, 6, 7, 1, 9, 4],
    [7, 9, 3, 1, 13, 12, 11, 14, 2, 6, 5, 10, 4, 0, 15, 8],
    [9, 0, 5, 7, 2, 4, 10, 15, 14, 1, 11, 12, 6, 8, 3, 13],
    [2, 12, 6, 10, 0, 11, 8, 3, 4, 13, 7, 5, 15, 14, 1, 9],
    [12, 5, 1, 15, 14, 13, 4, 10, 0, 7, 6, 3, 9, 2, 8, 11],
    [13, 11, 7, 14, 12, 1, 3, 9, 5, 0, 15, 4, 8, 6, 2, 10],
    [6, 15, 14, 9, 11, 3, 0, 8, 12, 2, 13, 7, 1, 4, 10, 5],
    [10, 2, 8, 4, 7, 6, 1, 5, 15, 11, 9, 14, 3, 12, 13, 0],
]
# G(v, a, b, c, d, x, y) applications of one round, in RFC 7693 order.
GS = [(0, 4, 8, 12), (1, 5, 9, 13), (2, 6, 10, 14), (3, 7, 11, 15),
      (0, 5, 10, 15), (1, 6, 11, 12), (2, 7, 8, 13), (3, 4, 9, 14)]
ROUNDS = 10


def ws(p, n, plus=''):
    return ','.join('%s%s%d' % (plus, p, i) for i in range(n))


def params(p, n, ty='U32', plus=''):
    return ','.join('%s%s%d: %s' % (plus, p, i, ty) for i in range(n))


def write(path, text):
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, 'w') as f:
        f.write(text)
    print('wrote', os.path.relpath(path, ROOT))


# ---------------------------------------------------------------- compress

def rotr(x, n):
    return 'U32.or(U32.shrn(%s,%dn),U32.shln(%s,%dn))' % (x, n, x, 32 - n)


def gen_compress():
    L = ['# Generated by tools/generators/blake2s_gen.py; do not edit.',
         '# BLAKE2s compression function F (RFC 7693 section 3.2). One round is fully',
         '# unrolled (eight G steps, constant rotations); each round index selects the',
         '# SIGMA-permuted message words by a branch, never by a run-time table.',
         'import Base', 'import ./types.bend as T', '']
    # round: v record in, x0..x15 = message words in schedule order
    L.append('def round(v: T.Vector,%s) -> T.Vector:' % params('x', 16))
    L.append('  match v:')
    L.append('    case T.V{%s}:' % ws('a', 16, '+'))
    cur = ['a%d' % i for i in range(16)]
    k = 0
    for gi, (a, b, c, d) in enumerate(GS):
        x, y = 'x%d' % (2 * gi), 'x%d' % (2 * gi + 1)
        va, vb, vc, vd = cur[a], cur[b], cur[c], cur[d]
        n = lambda: 't%d' % (len(L))
        a1 = 'g%da1' % gi; d1 = 'g%dd1' % gi; c1 = 'g%dc1' % gi; b1 = 'g%db1' % gi
        a2 = 'g%da2' % gi; d2 = 'g%dd2' % gi; c2 = 'g%dc2' % gi; b2 = 'g%db2' % gi
        def rot(dst, p, q, n):
            L.append('      +%sx = U32.xor(%s,%s)' % (dst, p, q))
            L.append('      +%s = %s' % (dst, rotr(dst + 'x', n)))
        L.append('      +%s = U32.add(U32.add(%s,%s),%s)' % (a1, va, vb, x))
        rot(d1, vd, a1, 16)
        L.append('      +%s = U32.add(%s,%s)' % (c1, vc, d1))
        rot(b1, vb, c1, 12)
        L.append('      +%s = U32.add(U32.add(%s,%s),%s)' % (a2, a1, b1, y))
        rot(d2, d1, a2, 8)
        L.append('      +%s = U32.add(%s,%s)' % (c2, c1, d2))
        rot(b2, b1, c2, 7)
        cur[a], cur[b], cur[c], cur[d] = a2, b2, c2, d2
    L.append('      T.V{%s}' % ','.join(cur))
    L.append('')
    # init
    L.append('def flag(last: Bool) -> U32:')
    L.append('  match last:')
    L.append('    case True{}: %d' % (IV[6] ^ 0xFFFFFFFF))
    L.append('    case False{}: %d' % IV[6])
    L.append('')
    L.append('def init(h: T.State,t0: U32,t1: U32,last: Bool) -> T.Vector:')
    L.append('  match h:')
    L.append('    case T.H{%s}:' % ws('h', 8))
    L.append('      T.V{%s,%d,%d,%d,%d,U32.xor(%d,t0),U32.xor(%d,t1),flag(last),%d}' % (
        ws('h', 8), IV[0], IV[1], IV[2], IV[3], IV[4], IV[5], IV[7]))
    L.append('')
    L.append('def finish(h: T.State,v: T.Vector) -> T.State:')
    L.append('  match h v:')
    L.append('    case T.H{%s} T.V{%s}:' % (ws('h', 8), ws('v', 16)))
    L.append('      T.H{%s}' % ','.join('U32.xor(U32.xor(h%d,v%d),v%d)' % (i, i, i + 8) for i in range(8)))
    L.append('')
    L.append('# F(h, m, t, f): ten rounds, round r reading the words in SIGMA[r] order.')
    L.append('def compress(+h: T.State,%s,t0: U32,t1: U32,last: Bool) -> T.State:' % params('m', 16, plus='+'))
    e = 'init(h,t0,t1,last)'
    for r in range(ROUNDS):
        e = 'round(%s,%s)' % (e, perm(r))
    L.append('  finish(h,%s)' % e)
    L.append('')
    write(os.path.join(SRC, 'compress.bend'), '\n'.join(L))


# ---------------------------------------------------------------- blake2s

def gen_api():
    L = ['# Generated by tools/generators/blake2s_gen.py; do not edit.',
         'import Base', 'import ./types.bend as T', 'import ./compress.bend as C', '']
    # counter
    L += ['# The 64-bit byte counter t is kept as two U32 halves (t0 low, t1 high).',
          'def carry(c: Bool, hi: U32) -> U32:',
          '  match c:',
          '    case True{}: U32.add(hi,1)',
          '    case False{}: hi',
          '',
          'def count_hi(+lo: U32, hi: U32, +n: U32) -> U32:',
          '  carry(U32.is_lt(U32.add(lo,n),n),hi)',
          '']
    # full block reads
    L.append('def read15(+index: U32, h: T.State, t0: U32, t1: U32, %s, pair: Array<U32> & U32) -> Array<U32> & T.State:' % params('w', 15))
    L.append('  (a,w15) = pair')
    L.append('  (a,C.compress(h,%s,t0,t1,False{}))' % ws('w', 16))
    L.append('')
    for k in range(14, -1, -1):
        pw = (', ' + params('w', k)) if k else ''
        L.append('def read%d(+index: U32, h: T.State, t0: U32, t1: U32%s, pair: Array<U32> & U32) -> Array<U32> & T.State:' % (k, pw))
        L.append('  (a,w%d) = pair' % k)
        L.append('  read%d(index,h,t0,t1,%s,Array.get(U32,a,U32.add(index,%d)))' % (k + 1, ws('w', k + 1), k + 1))
        L.append('')
    L += ['def absorb(a: Array<U32>, +index: U32, h: T.State, t0: U32, t1: U32) -> Array<U32> & T.State:',
          '  read0(index,h,t0,t1,Array.get(U32,a,index))', '']
    # final block
    L += ['# The final block keeps the bytes before the logical length and zeroes the rest.',
          '# keep(n, w) keeps the low n bytes of w.',
          'def keep(n: Nat, +w: U32) -> U32:',
          '  match n:',
          '    case 0n: 0',
          '    case 1n: U32.and(255,w)',
          '    case 2n: U32.and(65535,w)',
          '    case 3n: U32.and(16777215,w)',
          '    case 4n+p: w',
          '',
          'def pad_word(w: U32, +pos: Nat, +remain: Nat) -> U32:',
          '  keep(Nat.sub(remain,pos),w)',
          '']
    L.append('def pad15(+remain: Nat, +index: U32, h: T.State, t0: U32, t1: U32, %s, pair: Array<U32> & U32) -> T.State:' % params('w', 15))
    L.append('  (a,w15) = pair')
    L.append('  C.compress(h,%s,t0,t1,True{})' % ','.join('pad_word(w%d,%dn,remain)' % (i, 4 * i) for i in range(16)))
    L.append('')
    for k in range(14, -1, -1):
        pw = (', ' + params('w', k)) if k else ''
        L.append('def pad%d(+remain: Nat, +index: U32, h: T.State, t0: U32, t1: U32%s, pair: Array<U32> & U32) -> T.State:' % (k, pw))
        L.append('  (a,w%d) = pair' % k)
        L.append('  pad%d(remain,index,h,t0,t1,%s,Array.get(U32,a,U32.add(index,%d)))' % (k + 1, ws('w', k + 1), k + 1))
        L.append('')
    L += ['def finish(a: Array<U32>, +index: U32, +t0: U32, t1: U32, +remain: Nat, h: T.State) -> T.State:',
          '  +n = U32.from_nat(remain)',
          '  pad0(remain,index,h,U32.add(t0,n),count_hi(t0,t1,n),Array.get(U32,a,index))',
          '',
          'def blocks(n: Nat, +index: U32, +t0: U32, t1: U32, +remain: Nat, pair: Array<U32> & T.State) -> T.State:',
          '  match n pair:',
          '    case 0n Tuple{a,h}: finish(a,index,t0,t1,remain,h)',
          '    case 1n+p Tuple{a,h}:',
          '      +c0 = U32.add(t0,64)',
          '      +c1 = count_hi(t0,t1,64)',
          '      blocks(p,U32.add(index,16),c0,c1,remain,absorb(a,index,h,c0,c1))',
          '',
          '# Parameter block for an unkeyed 32-byte digest: h0 = IV0 ^ 0x01010020.',
          'def initial() -> T.State:',
          '  T.H{%s}' % ','.join(str(x) for x in [IV[0] ^ 0x01010020] + IV[1:]),
          '',
          '# Blocks before the last one: max(1, ceil(length/64)) - 1.',
          'def leading(length: Nat) -> Nat:',
          '  Nat.sub(Nat.div(Nat.add(length,63n),64n),1n)',
          '',
          'def unchecked(a: Array<U32>, +length: Nat) -> T.State:',
          '  +n = leading(length)',
          '  blocks(n,0,0,0,Nat.sub(length,Nat.mul(64n,n)),(a,initial()))',
          '',
          'def digest(h: T.State) -> Array<U32>:',
          '  match h:',
          '    case T.H{%s}:' % ws('h', 8),
          '      a = Array.new(U32,3n,0)']
    for i in range(8):
        L.append('      a = Array.set(U32,a,%d,h%d)' % (i, i))
    L += ['      a', '',
          'def checked(valid: Bool, a: Array<U32>, length: Nat) -> Maybe<&1,Array<U32>>:',
          '  match valid:',
          '    case False{}: None{}',
          '    case True{}: Some{digest(unchecked(a,length))}',
          '',
          'def sized(+length: Nat, pair: Array<U32> & U32) -> Maybe<&1,Array<U32>>:',
          '  (a,capacity) = pair',
          '  checked(Nat.is_le(length,Nat.mul(4n,U32.to_nat(capacity))),a,length)',
          '',
          '# BLAKE2s-256 of the first `length` bytes of `a` (four little-endian bytes per',
          '# word): the eight little-endian digest words, or None when length exceeds',
          '# 4 * the array capacity.',
          'def blake2s(a: Array<U32>, length: Nat) -> Maybe<&1,Array<U32>>:',
          '  sized(length,Array.size(U32,a))',
          '']
    write(os.path.join(SRC, 'blake2s.bend'), '\n'.join(L))




# ---------------------------------------------------------------- proofs: compress

def mlist():
    return '[%s]' % ','.join('m%d' % i for i in range(16))


def perm(r):
    return ','.join('m%d' % j for j in SIGMA[r])


def tail_expr(k, v):
    e = v
    for r in range(k, ROUNDS):
        e = 'C.round(%s,%s)' % (e, perm(r))
    return e


def gen_compress_proof():
    M = mlist()
    ms = ws('m', 16)
    mfor = ['  for +m%d: U32' % i for i in range(16)]
    L = ['# Generated by tools/generators/blake2s_gen.py; do not edit.',
         '# The unrolled compression function refines the list-based RFC 7693 F.',
         '#',
         '# The implementation runs ten explicit rounds. A proof-side model runs the',
         '# same round function r times, selecting the permuted words by round index;',
         '# for an abstract r both the model and the specification stay symbolic, so',
         '# every comparison below is between one round at most. The theorem is then',
         '# instantiated at r = 10, where the model coincides with the implementation.',
         'import Base',
         'import ../../../../src/crypto/blake/blake2s/types.bend as T',
         'import ../../../../src/crypto/blake/blake2s/compress.bend as C',
         'import ../../../../spec/crypto/blake/blake2s.bend as R',
         '',
         '# The work vector as the RFC list v[0..15], one projection per entry, so',
         '# that the list has its shape even when the vector is abstract.']
    for i in range(16):
        L += ['def p%d(v: T.Vector) -> U32:' % i, '  match v:',
              '    case T.V{%s}: a%d' % (ws('a', 16), i), '']
    L += ['def vec(+v: T.Vector) -> List<&2,U32>:',
          '  [%s]' % ','.join('p%d(v)' % i for i in range(16)), '']
    # model
    L.append('# Model: round i of the implementation reads the words in SIGMA[i mod 10] order.')
    L.append('def round_at(i: Nat, v: T.Vector,%s) -> T.Vector:' % params('m', 16, plus='+'))
    L.append('  match i:')
    for r in range(ROUNDS):
        L.append('    case %dn: C.round(v,%s)' % (r, perm(r)))
    L.append('    case 10n+p: round_at(p,v,%s)' % ms)
    L.append('')
    L.append('def rounds(n: Nat, +i: Nat, v: T.Vector,%s) -> T.Vector:' % params('m', 16, plus='+'))
    L.append('  match n:')
    L.append('    case 0n: v')
    L.append('    case 1n+p: rounds(p,1n+i,round_at(i,v,%s),%s)' % (ms, ms))
    L.append('')
    L.append('def model(+r: Nat, +h: T.State,%s,t0: U32,t1: U32,last: Bool) -> T.State:' % params('m', 16, plus='+'))
    L.append('  C.finish(h,rounds(r,0n,C.init(h,t0,t1,last),%s))' % ms)
    L.append('')
    # per-round lemmas
    for r in range(ROUNDS):
        L += ['law round%d_correct:' % r, '  for +v: T.Vector'] + mfor
        L += ['  {vec(round_at(%dn,v,%s)) == R.round(vec(v),R.sigma(%dn),%s) : List<&2,U32>}' % (r, ms, r, M), '',
              'def round%d_correct(v,%s):' % (r, ms),
              '  match v:',
              '    case T.V{%s}: {==}' % ws('a', 16), '']
    L += ['law round_correct:', '  for +i: Nat', '  for +v: T.Vector'] + mfor
    L += ['  {vec(round_at(i,v,%s)) == R.round(vec(v),R.sigma(i),%s) : List<&2,U32>}' % (ms, M), '',
          'def round_correct(i,v,%s):' % ms, '  match i:']
    for r in range(ROUNDS):
        L.append('    case %dn: round%d_correct(v,%s)' % (r, r, ms))
    L += ['    case 10n+p: round_correct(p,v,%s)' % ms, '']
    # rounds, by induction on an abstract count
    L += ['law rounds_correct:', '  for +n: Nat', '  for +i: Nat', '  for +v: T.Vector'] + mfor
    L += ['  {vec(rounds(n,i,v,%s)) == R.rounds(n,i,vec(v),%s) : List<&2,U32>}' % (ms, M), '',
          'def rounds_correct(n,i,v,%s):' % ms,
          '  match n:',
          '    case 0n: {==}',
          '    case 1n+p:',
          '      Equal.trans(List<&2,U32>,',
          '        vec(rounds(p,1n+i,round_at(i,v,%s),%s)),' % (ms, ms),
          '        R.rounds(p,1n+i,vec(round_at(i,v,%s)),%s),' % (ms, M),
          '        R.rounds(p,1n+i,R.round(vec(v),R.sigma(i),%s),%s),' % (M, M),
          '        rounds_correct(p,1n+i,round_at(i,v,%s),%s),' % (ms, ms),
          '        Equal.cong(List<&2,U32>,List<&2,U32>,x => R.rounds(p,1n+i,x,%s),vec(round_at(i,v,%s)),R.round(vec(v),R.sigma(i),%s),round_correct(i,v,%s)))' % (M, ms, M, ms),
          '']
    # finish / init
    hs = ws('h', 8)
    H = 'T.H{%s}' % hs
    L += ['def fin(%s,+l: List<&2,U32>) -> T.State:' % params('h', 8),
          '  T.H{%s}' % ','.join('U32.xor(U32.xor(h%d,R.get(l,%dn)),R.get(l,%dn))' % (i, i, i + 8) for i in range(8)),
          '',
          'law finish_correct:'] + ['  for +h%d: U32' % i for i in range(8)] + [
          '  for +v: T.Vector',
          '  {C.finish(%s,v) == fin(%s,vec(v)) : T.State}' % (H, hs), '',
          'def finish_correct(%s,v):' % hs,
          '  match v:',
          '    case T.V{%s}: {==}' % ws('a', 16), '']
    V2 = '[%s,%d,%d,%d,%d,U32.xor(%d,t0),U32.xor(%d,t1),%d,%d]' % (hs, IV[0], IV[1], IV[2], IV[3], IV[4], IV[5], IV[6], IV[7])
    L += ['law init_correct:'] + ['  for +h%d: U32' % i for i in range(8)] + [
          '  for +t0: U32', '  for +t1: U32', '  for +last: Bool',
          '  {vec(C.init(%s,t0,t1,last)) == R.invert(last,%s) : List<&2,U32>}' % (H, V2), '',
          'def init_correct(%s,t0,t1,last):' % hs,
          '  match last:',
          '    case True{}: {==}',
          '    case False{}: {==}', '']
    X = 'rounds(r,0n,C.init(%s,t0,t1,last),%s)' % (H, ms)
    I = 'C.init(%s,t0,t1,last)' % H
    L += ['law model_correct:', '  for +r: Nat', '  for +h: T.State'] + mfor + [
          '  for +t0: U32', '  for +t1: U32', '  for +last: Bool',
          '  {model(r,h,%s,t0,t1,last) == R.compress(r,h,%s,t0,t1,last) : T.State}' % (ms, M), '',
          'def model_correct(r,h,%s,t0,t1,last):' % ms,
          '  match h:',
          '    case T.H{%s}:' % hs,
          '      Equal.trans(T.State,',
          '        C.finish(%s,%s),' % (H, X),
          '        fin(%s,vec(%s)),' % (hs, X),
          '        R.compress(r,%s,%s,t0,t1,last),' % (H, M),
          '        finish_correct(%s,%s),' % (hs, X),
          '        Equal.trans(T.State,',
          '          fin(%s,vec(%s)),' % (hs, X),
          '          fin(%s,R.rounds(r,0n,vec(%s),%s)),' % (hs, I, M),
          '          R.compress(r,%s,%s,t0,t1,last),' % (H, M),
          '          Equal.cong(List<&2,U32>,T.State,l => fin(%s,l),vec(%s),R.rounds(r,0n,vec(%s),%s),rounds_correct(r,0n,%s,%s)),' % (hs, X, I, M, I, ms),
          '          Equal.cong(List<&2,U32>,T.State,l => fin(%s,R.rounds(r,0n,l,%s)),vec(%s),R.invert(last,%s),init_correct(%s,t0,t1,last))))' % (hs, M, I, V2, hs),
          '']
    L += ['# F as implemented (ten unrolled rounds) is F of the specification with r = 10.',
          'law compress_correct:', '  for +h: T.State'] + mfor + [
          '  for +t0: U32', '  for +t1: U32', '  for +last: Bool',
          '  {C.compress(h,%s,t0,t1,last) == R.compress(10n,h,%s,t0,t1,last) : T.State}' % (ms, M), '',
          'def compress_correct(h,%s,t0,t1,last):' % ms,
          '  Equal.trans(T.State,C.compress(h,%s,t0,t1,last),model(10n,h,%s,t0,t1,last),R.compress(10n,h,%s,t0,t1,last),' % (ms, ms, M),
          '    {==},model_correct(10n,h,%s,t0,t1,last))' % ms, '']
    write(os.path.join(PRF, 'compress.bend'), '\n'.join(L))


# ---------------------------------------------------------------- proofs: bytes

def u32word(xs):
    s = 'WNil{}'
    for x in reversed(xs):
        s = 'WCon{%s, %s}' % (x, s)
    return 'U32{%s}' % s


def gen_bytes_proof():
    N = 32
    ys = ['y%d' % i for i in range(N)]
    zs = ['z%d' % i for i in range(N)]
    xs = ['x%d' % i for i in range(N)]
    L = ['# Generated by tools/generators/blake2s_gen.py; do not edit.',
         '# Bytes and words: the specification reassembles block words from',
         '# little-endian bytes and zero-pads the last block byte by byte; the',
         '# implementation reads whole words and masks the last partial word.',
         '# The bit-level facts are proven on the 32 Bool digits of a U32.',
         'import Base',
         'import ../../../../src/crypto/blake/blake2s/blake2s.bend as K',
         'import ../../../../spec/crypto/blake/blake2s.bend as R',
         '',
         '# Two words are equal when their digits are.',
         'law bits32:']
    L += ['  for -y%d: Bool' % i for i in range(N)]
    L += ['  for -z%d: Bool' % i for i in range(N)]
    L += ['  for e%d: {y%d == z%d : Bool}' % (i, i, i) for i in range(N)]
    L += ['  {%s == %s : U32}' % (u32word(ys), u32word(zs)), '']
    L += ['def bits32(%s):' % ','.join(ys + zs + ['e%d' % i for i in range(N)])]
    for i in range(N):
        L.append('  %%e%d : {%s == %s : U32}' % (i, u32word(ys), u32word(ys[:i] + ['_'] + zs[i + 1:])))
    L += ['  {==}', '']
    for k in (1, 2, 3):
        e = 'x'
        for _ in range(k):
            e = 'Bool.or(%s, False{})' % e
        L += ['law or%d:' % k, '  for +x: Bool', '  {%s == x : Bool}' % e, '',
              'def or%d(x):' % k, '  match x:', '    case True{}: {==}', '    case False{}: {==}', '']
    pat = u32word(xs)

    def bit_lhs(i, kept):
        if i // 8 >= kept:
            return 'False{}'
        e = 'x%d' % i
        for _ in range(3 - i // 8):
            e = 'Bool.or(%s, False{})' % e
        return e

    def bit_pf(i, kept):
        if i // 8 >= kept or i // 8 == 3:
            return '{==}'
        return 'or%d(x%d)' % (3 - i // 8, i)

    def bit_rhs(i, kept):
        return 'x%d' % i if i // 8 < kept else 'False{}'

    names = {4: 'full', 3: 'part3', 2: 'part2', 1: 'part1'}
    masks = {3: 16777215, 2: 65535, 1: 255}
    for kept in (4, 3, 2, 1):
        bs = ['R.byte(w,%dn)' % j if j < kept else '0' for j in range(4)]
        rhs = 'w' if kept == 4 else 'U32.and(%d,w)' % masks[kept]
        L += ['law %s:' % names[kept], '  for +w: U32',
              '  {R.word(%s) == %s : U32}' % (','.join(bs), rhs), '',
              'def %s(w):' % names[kept], '  match w:', '    case %s:' % pat,
              '      bits32(%s)' % ','.join([bit_lhs(i, kept) for i in range(N)] + [bit_rhs(i, kept) for i in range(N)] + [bit_pf(i, kept) for i in range(N)]),
              '']
    L += ['# The bytes at message offsets i..i+3 of one word, zeroed from offset len on.',
          'def kept(+w: U32, +i: Nat, +len: Nat) -> U32:',
          '  R.word(R.keep_if(Nat.is_lt(i,len),R.byte(w,0n)),R.keep_if(Nat.is_lt(1n+i,len),R.byte(w,1n)),R.keep_if(Nat.is_lt(2n+i,len),R.byte(w,2n)),R.keep_if(Nat.is_lt(3n+i,len),R.byte(w,3n)))',
          '',
          'law pad_word_correct:', '  for +w: U32', '  for +i: Nat', '  for +len: Nat',
          '  {kept(w,i,len) == K.pad_word(w,i,len) : U32}', '',
          'def pad_word_correct(w,i,len):',
          '  match i len:',
          '    case 0n 0n: {==}',
          '    case 0n 1n: part1(w)',
          '    case 0n 2n: part2(w)',
          '    case 0n 3n: part3(w)',
          '    case 0n 4n+p: full(w)',
          '    case 1n+j 0n: {==}',
          '    case 1n+j 1n+l: pad_word_correct(w,j,l)',
          '',
          '# Whole blocks: reassembling the serialized words gives the words back.',
          'law words_serialize:', '  for +ws: List<&2,U32>',
          '  {R.words(R.serialize(ws)) == ws : List<&2,U32>}', '',
          'def words_serialize(ws):',
          '  match ws:',
          '    case Nil{}: {==}',
          '    case w <> rest:',
          '      Equal.trans(List<&2,U32>,',
          '        R.words(R.serialize(w <> rest)),',
          '        R.word(R.byte(w,0n),R.byte(w,1n),R.byte(w,2n),R.byte(w,3n)) <> rest,',
          '        w <> rest,',
          '        Equal.cong(List<&2,U32>,List<&2,U32>,t => R.word(R.byte(w,0n),R.byte(w,1n),R.byte(w,2n),R.byte(w,3n)) <> t,R.words(R.serialize(rest)),rest,words_serialize(rest)),',
          '        Equal.cong(U32,List<&2,U32>,x => x <> rest,R.word(R.byte(w,0n),R.byte(w,1n),R.byte(w,2n),R.byte(w,3n)),w,full(w)))',
          '',
          '# The last block: the implementation masks word j with pad_word(w, i + 4j, len).',
          'def masked(ws: List<&2,U32>, +i: Nat, +len: Nat) -> List<&2,U32>:',
          '  match ws:',
          '    case Nil{}: Nil{}',
          '    case w <> rest: K.pad_word(w,i,len) <> masked(rest,4n+i,len)',
          '',
          'law words_pad:', '  for +ws: List<&2,U32>', '  for +i: Nat', '  for +len: Nat',
          '  {R.words(R.pad(R.serialize(ws),i,len)) == masked(ws,i,len) : List<&2,U32>}', '',
          'def words_pad(ws,i,len):',
          '  match ws:',
          '    case Nil{}: {==}',
          '    case w <> rest:',
          '      Equal.trans(List<&2,U32>,',
          '        R.words(R.pad(R.serialize(w <> rest),i,len)),',
          '        kept(w,i,len) <> masked(rest,4n+i,len),',
          '        K.pad_word(w,i,len) <> masked(rest,4n+i,len),',
          '        Equal.cong(List<&2,U32>,List<&2,U32>,t => kept(w,i,len) <> t,R.words(R.pad(R.serialize(rest),4n+i,len)),masked(rest,4n+i,len),words_pad(rest,4n+i,len)),',
          '        Equal.cong(U32,List<&2,U32>,x => x <> masked(rest,4n+i,len),kept(w,i,len),K.pad_word(w,i,len),pad_word_correct(w,i,len)))',
          '']
    write(os.path.join(PRF, 'bytes.bend'), '\n'.join(L))


# ---------------------------------------------------------------- proofs: reads and API

def gen_reads_proof():
    L = ['# Generated by tools/generators/blake2s_gen.py; do not edit.',
         '# Block reads, the last block, the block loop and the public API.',
         '# The implementation keeps its own copy of the counter carry; each lemma',
         '# carries the spec-side high counter half u1 with a proof e : t1 == u1.',
         'import Base',
         'import ../../../../src/crypto/blake/blake2s/types.bend as T',
         'import ../../../../src/crypto/blake/blake2s/compress.bend as C',
         'import ../../../../src/crypto/blake/blake2s/blake2s.bend as K',
         'import ../../../../spec/crypto/blake/blake2s.bend as R',
         'import ./compress.bend as P',
         'import ./bytes.bend as B',
         'import ./array.bend as A',
         '',
         'law carry_correct:', '  for +c: Bool', '  for +hi: U32',
         '  {K.carry(c,hi) == R.carry(c,hi) : U32}', '',
         'def carry_correct(c,hi):', '  match c:', '    case True{}: {==}', '    case False{}: {==}', '',
         'law count_correct:', '  for +lo: U32', '  for +hi: U32', '  for +n: U32',
         '  {K.count_hi(lo,hi,n) == R.count_hi(lo,hi,n) : U32}', '',
         'def count_correct(lo,hi,n):', '  carry_correct(U32.is_lt(U32.add(lo,n),n),hi)', '']
    W = ws('w', 16)
    WL = '[%s]' % W
    wfor = ['  for +w%d: U32' % i for i in range(16)]
    # block_correct
    L += ['law block_correct:', '  for +h: T.State'] + wfor + [
          '  for +t0: U32', '  for +t1: U32', '  for +u1: U32', '  for e: {t1 == u1 : U32}',
          '  {C.compress(h,%s,t0,t1,False{}) == R.compress(10n,h,R.words(R.serialize(%s)),t0,u1,False{}) : T.State}' % (W, WL), '',
          'def block_correct(h,%s,t0,t1,u1,e):' % W,
          '  %%e : {C.compress(h,%s,t0,t1,False{}) == R.compress(10n,h,R.words(R.serialize(%s)),t0,_,False{}) : T.State}' % (W, WL),
          '  Equal.trans(T.State,C.compress(h,%s,t0,t1,False{}),R.compress(10n,h,%s,t0,t1,False{}),R.compress(10n,h,R.words(R.serialize(%s)),t0,t1,False{}),' % (W, WL, WL),
          '    P.compress_correct(h,%s,t0,t1,False{}),' % W,
          '    Equal.cong(List<&2,U32>,T.State,l => R.compress(10n,h,l,t0,t1,False{}),%s,R.words(R.serialize(%s)),Equal.sym(List<&2,U32>,R.words(R.serialize(%s)),%s,B.words_serialize(%s))))' % (WL, WL, WL, WL, WL),
          '']
    PW = ','.join('K.pad_word(w%d,%dn,remain)' % (i, 4 * i) for i in range(16))
    PWL = '[%s]' % PW
    L += ['law last_correct:', '  for +remain: Nat', '  for +h: T.State'] + wfor + [
          '  for +t0: U32', '  for +t1: U32', '  for +u1: U32', '  for e: {t1 == u1 : U32}',
          '  {C.compress(h,%s,t0,t1,True{}) == R.compress(10n,h,R.words(R.pad(R.serialize(%s),0n,remain)),t0,u1,True{}) : T.State}' % (PW, WL), '',
          'def last_correct(remain,h,%s,t0,t1,u1,e):' % W,
          '  %%e : {C.compress(h,%s,t0,t1,True{}) == R.compress(10n,h,R.words(R.pad(R.serialize(%s),0n,remain)),t0,_,True{}) : T.State}' % (PW, WL),
          '  Equal.trans(T.State,C.compress(h,%s,t0,t1,True{}),R.compress(10n,h,%s,t0,t1,True{}),R.compress(10n,h,R.words(R.pad(R.serialize(%s),0n,remain)),t0,t1,True{}),' % (PW, PWL, WL),
          '    P.compress_correct(h,%s,t0,t1,True{}),' % PW,
          '    Equal.cong(List<&2,U32>,T.State,l => R.compress(10n,h,l,t0,t1,True{}),%s,R.words(R.pad(R.serialize(%s),0n,remain)),Equal.sym(List<&2,U32>,R.words(R.pad(R.serialize(%s),0n,remain)),%s,B.words_pad(%s,0n,remain))))' % (PWL, WL, WL, PWL, WL),
          '']
    # read chain
    def acc(k):
        return '[%s]' % ','.join('w%d' % j for j in range(k - 1, -1, -1))
    for k in range(15, -1, -1):
        wk = ''.join(',w%d' % j for j in range(k))
        L += ['law read%d_correct:' % k, '  for +index: U32', '  for +h: T.State', '  for +t0: U32', '  for +t1: U32', '  for +u1: U32', '  for e: {t1 == u1 : U32}']
        L += ['  for +w%d: U32' % j for j in range(k)]
        L += ['  for pair: Array<U32> & U32',
              '  {K.read%d(index,h,t0,t1%s,pair) == R.full_block(10n,R.gather(%dn,index,%d,%s,pair),h,t0,u1) : Array<U32> & T.State}' % (k, wk, 15 - k, k + 1, acc(k)), '',
              'def read%d_correct(index,h,t0,t1,u1,e%s,pair):' % (k, wk),
              '  (a,w%d) = pair' % k]
        if k == 15:
            L += ['  Equal.cong(T.State,Array<U32> & T.State,s => (a,s),C.compress(h,%s,t0,t1,False{}),R.compress(10n,h,R.words(R.serialize(%s)),t0,u1,False{}),block_correct(h,%s,t0,t1,u1,e))' % (W, WL, W), '']
        else:
            L += ['  read%d_correct(index,h,t0,t1,u1,e%s,w%d,Array.get(U32,a,U32.add(index,%d)))' % (k + 1, wk, k, k + 1), '']
    for k in range(15, -1, -1):
        wk = ''.join(',w%d' % j for j in range(k))
        L += ['law pad%d_correct:' % k, '  for +remain: Nat', '  for +index: U32', '  for +h: T.State', '  for +t0: U32', '  for +t1: U32', '  for +u1: U32', '  for e: {t1 == u1 : U32}']
        L += ['  for +w%d: U32' % j for j in range(k)]
        L += ['  for pair: Array<U32> & U32',
              '  {K.pad%d(remain,index,h,t0,t1%s,pair) == R.last_block(10n,R.gather(%dn,index,%d,%s,pair),remain,h,t0,u1) : T.State}' % (k, wk, 15 - k, k + 1, acc(k)), '',
              'def pad%d_correct(remain,index,h,t0,t1,u1,e%s,pair):' % (k, wk),
              '  (a,w%d) = pair' % k]
        if k == 15:
            L += ['  last_correct(remain,h,%s,t0,t1,u1,e)' % W, '']
        else:
            L += ['  pad%d_correct(remain,index,h,t0,t1,u1,e%s,w%d,Array.get(U32,a,U32.add(index,%d)))' % (k + 1, wk, k, k + 1), '']
    L += ['law absorb_correct:', '  for a: Array<U32>', '  for +index: U32', '  for +h: T.State', '  for +t0: U32', '  for +t1: U32', '  for +u1: U32', '  for e: {t1 == u1 : U32}',
          '  {K.absorb(a,index,h,t0,t1) == R.absorb(10n,a,index,h,t0,u1) : Array<U32> & T.State}', '',
          'def absorb_correct(a,index,h,t0,t1,u1,e):',
          '  read0_correct(index,h,t0,t1,u1,e,Array.get(U32,a,index))', '',
          'law finish_correct:', '  for a: Array<U32>', '  for +index: U32', '  for +t0: U32', '  for +t1: U32', '  for +remain: Nat', '  for +h: T.State',
          '  {K.finish(a,index,t0,t1,remain,h) == R.finish(10n,a,index,t0,t1,remain,h) : T.State}', '',
          'def finish_correct(a,index,t0,t1,remain,h):',
          '  pad0_correct(remain,index,h,U32.add(t0,U32.from_nat(remain)),K.count_hi(t0,t1,U32.from_nat(remain)),R.count_hi(t0,t1,U32.from_nat(remain)),count_correct(t0,t1,U32.from_nat(remain)),Array.get(U32,a,index))', '']
    C0 = 'U32.add(t0,64)'
    KC = 'K.count_hi(t0,t1,64)'
    RC = 'R.count_hi(t0,t1,64)'
    NX = 'U32.add(index,16)'
    TT = 'A.thaw(tree)'
    L += ['law blocks_step:', '  for +n: Nat', '  for +index: U32', '  for +t0: U32', '  for +t1: U32', '  for +remain: Nat', '  for -a: Array<U32>', '  for +h: T.State',
          '  for view: Sigma<&2,&1,A.Tree,t => {a == A.thaw(t) : Array<U32>}>',
          '  for recurse: @pair: (Array<U32> & T.State) -> {K.blocks(n,%s,%s,%s,remain,pair) == R.blocks(10n,n,%s,%s,%s,remain,pair) : T.State}' % (NX, C0, KC, NX, C0, RC),
          '  {K.blocks(1n+n,index,t0,t1,remain,(a,h)) == R.blocks(10n,1n+n,index,t0,t1,remain,(a,h)) : T.State}', '',
          'def blocks_step(n,index,t0,t1,remain,a,h,view,recurse):',
          '  match view:',
          '    case Tuple{+tree,pf}:',
          '      %%Equal.sym(Array<U32>,a,%s,pf) : {K.blocks(1n+n,index,t0,t1,remain,(_,h)) == R.blocks(10n,1n+n,index,t0,t1,remain,(_,h)) : T.State}' % TT,
          '      Equal.trans(T.State,',
          '        K.blocks(n,%s,%s,%s,remain,K.absorb(%s,index,h,%s,%s)),' % (NX, C0, KC, TT, C0, KC),
          '        R.blocks(10n,n,%s,%s,%s,remain,K.absorb(%s,index,h,%s,%s)),' % (NX, C0, RC, TT, C0, KC),
          '        R.blocks(10n,n,%s,%s,%s,remain,R.absorb(10n,%s,index,h,%s,%s)),' % (NX, C0, RC, TT, C0, RC),
          '        recurse(K.absorb(%s,index,h,%s,%s)),' % (TT, C0, KC),
          '        Equal.cong(Array<U32> & T.State,T.State,pair => R.blocks(10n,n,%s,%s,%s,remain,pair),K.absorb(%s,index,h,%s,%s),R.absorb(10n,%s,index,h,%s,%s),absorb_correct(%s,index,h,%s,%s,%s,count_correct(t0,t1,64))))' % (NX, C0, RC, TT, C0, KC, TT, C0, RC, TT, C0, KC, RC),
          '',
          'law blocks_correct:', '  for +n: Nat', '  for +index: U32', '  for +t0: U32', '  for +t1: U32', '  for +u1: U32', '  for e: {t1 == u1 : U32}', '  for +remain: Nat', '  for pair: Array<U32> & T.State',
          '  {K.blocks(n,index,t0,t1,remain,pair) == R.blocks(10n,n,index,t0,u1,remain,pair) : T.State}', '',
          'def blocks_correct(n,index,t0,t1,u1,e,remain,pair):',
          '  match n pair:',
          '    case 0n Tuple{a,h}:',
          '      %e : {K.blocks(0n,index,t0,t1,remain,(a,h)) == R.blocks(10n,0n,index,t0,_,remain,(a,h)) : T.State}',
          '      finish_correct(a,index,t0,t1,remain,h)',
          '    case 1n+p Tuple{a,h}:',
          '      %e : {K.blocks(1n+p,index,t0,t1,remain,(a,h)) == R.blocks(10n,1n+p,index,t0,_,remain,(a,h)) : T.State}',
          '      blocks_step(p,index,t0,t1,remain,a,h,A.reify(a),pair => blocks_correct(p,%s,%s,%s,%s,count_correct(t0,t1,64),remain,pair))' % (NX, C0, KC, RC),
          '',
          'law leading_correct:', '  for +length: Nat',
          '  {K.leading(length) == Nat.sub(R.block_count(length),1n) : Nat}', '',
          'def leading_correct(length):', '  match length:', '    case 0n: {==}', '    case 1n+p: {==}', '',
          'law hash_tail:', '  for -a: Array<U32>', '  for +length: Nat',
          '  {R.blocks(10n,K.leading(length),0,0,0,Nat.sub(length,Nat.mul(64n,K.leading(length))),(a,K.initial())) == R.hash(10n,a,length) : T.State}', '',
          'def hash_tail(a,length):',
          '  %leading_correct(length) : {R.blocks(10n,K.leading(length),0,0,0,Nat.sub(length,Nat.mul(64n,K.leading(length))),(a,K.initial())) == R.blocks(10n,_,0,0,0,Nat.sub(length,Nat.mul(64n,_)),(a,R.initial())) : T.State}',
          '  {==}', '',
          'law unchecked_correct:', '  for a: Array<U32>', '  for +length: Nat',
          '  {K.unchecked(a,length) == R.hash(10n,a,length) : T.State}', '',
          'def unchecked_correct(a,length):',
          '  Equal.trans(T.State,K.unchecked(a,length),R.blocks(10n,K.leading(length),0,0,0,Nat.sub(length,Nat.mul(64n,K.leading(length))),(a,K.initial())),R.hash(10n,a,length),',
          '    blocks_correct(K.leading(length),0,0,0,0,{==},Nat.sub(length,Nat.mul(64n,K.leading(length))),(a,K.initial())),',
          '    hash_tail(a,length))', '',
          'law digest_correct:', '  for +h: T.State', '  {K.digest(h) == R.digest(h) : Array<U32>}', '',
          'def digest_correct(h):', '  match h:', '    case T.H{%s}: {==}' % ws('h', 8), '',
          'law checked_true:', '  for -a: Array<U32>', '  for +length: Nat',
          '  for view: Sigma<&2,&1,A.Tree,t => {a == A.thaw(t) : Array<U32>}>',
          '  {K.checked(True{},a,length) == R.checked(10n,True{},a,length) : Maybe<&1,Array<U32>>}', '',
          'def checked_true(a,length,view):',
          '  match view:',
          '    case Tuple{+tree,pf}:',
          '      %%Equal.sym(Array<U32>,a,%s,pf) : {K.checked(True{},_,length) == R.checked(10n,True{},_,length) : Maybe<&1,Array<U32>>}' % TT,
          '      Equal.trans(Maybe<&1,Array<U32>>,',
          '        Some{K.digest(K.unchecked(%s,length))},' % TT,
          '        Some{K.digest(R.hash(10n,%s,length))},' % TT,
          '        Some{R.digest(R.hash(10n,%s,length))},' % TT,
          '        Equal.cong(T.State,Maybe<&1,Array<U32>>,s => Some{K.digest(s)},K.unchecked(%s,length),R.hash(10n,%s,length),unchecked_correct(%s,length)),' % (TT, TT, TT),
          '        Equal.cong(Array<U32>,Maybe<&1,Array<U32>>,d => Some{d},K.digest(R.hash(10n,%s,length)),R.digest(R.hash(10n,%s,length)),digest_correct(R.hash(10n,%s,length))))' % (TT, TT, TT),
          '',
          'law checked_correct:', '  for +valid: Bool', '  for a: Array<U32>', '  for +length: Nat',
          '  {K.checked(valid,a,length) == R.checked(10n,valid,a,length) : Maybe<&1,Array<U32>>}', '',
          'def checked_correct(valid,a,length):', '  match valid:', '    case False{}: {==}', '    case True{}: checked_true(a,length,A.reify(a))', '',
          'law sized_correct:', '  for +length: Nat', '  for pair: Array<U32> & U32',
          '  {K.sized(length,pair) == R.sized(10n,length,pair) : Maybe<&1,Array<U32>>}', '',
          'def sized_correct(length,pair):', '  (a,capacity) = pair',
          '  checked_correct(Nat.is_le(length,Nat.mul(4n,U32.to_nat(capacity))),a,length)', '',
          'law blake2s_correct:', '  for a: Array<U32>', '  for +length: Nat',
          '  {K.blake2s(a,length) == R.blake2s(a,length) : Maybe<&1,Array<U32>>}', '',
          'def blake2s_correct(a,length):', '  sized_correct(length,Array.size(U32,a))', '']
    write(os.path.join(PRF, 'reads.bend'), '\n'.join(L))


if __name__ == '__main__':
    import sys
    what = sys.argv[1:] or ['impl', 'proof']
    if 'impl' in what:
        gen_compress()
        gen_api()
    if 'proof' in what:
        gen_compress_proof()
        gen_bytes_proof()
        gen_reads_proof()


