#!/usr/bin/env python3
"""Emit tests/crypto/blake/blake2s/main.bend with expected BLAKE2s-256 digests.

  python3 tools/generators/blake2s_tests.py

Expected digests come from Python's hashlib.blake2s (the BLAKE2 reference code)
and are cross-checked here against the official C reference
benchmarks/native/blake/blake2s-ref.c, compiled on the fly.
"""
import hashlib, os, subprocess, tempfile

ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), '..', '..'))
OUT = os.path.join(ROOT, 'tests/crypto/blake/blake2s/main.bend')
REF = os.path.join(ROOT, 'benchmarks/native/blake')

M32 = 0xFFFFFFFF


def pattern_words(n, seed):
    return [(i * 2654435761 + seed) & M32 for i in range(n)]


def to_bytes(words):
    return b''.join(w.to_bytes(4, 'little') for w in words)


def depth_for(length, extra):
    words = (length + 3) // 4 + extra
    return max(0, (words - 1).bit_length())


# (label, kind, length, seed, depth): kind 'pattern' fills every slot with
# i*2654435761+seed; 'sequence' holds bytes 0,1,2,...; 'abc' is the RFC vector.
CASES = [('rfc7693 abc', 'abc', 3, 0, 0)]
for n in range(0, 257):
    CASES.append(('kat %d' % n, 'sequence', n, 0, 6))
for n in [0, 1, 3, 4, 5, 63, 64, 65, 127, 128, 129, 191, 192, 193, 1023, 1024, 1025, 2048, 3073, 8193]:
    for seed, extra in [(42, 0), (7, 3)]:
        CASES.append(('pattern %d seed %d' % (n, seed), 'pattern', n, seed, depth_for(n, extra)))
CASES.append(('pattern 65536', 'pattern', 65536, 99, 14))
CASES.append(('pattern 100000', 'pattern', 100000, 5, 15))


def message(kind, length, seed, depth):
    if kind == 'abc':
        return b'abc'
    if kind == 'sequence':
        return bytes(i % 256 for i in range(length))
    return to_bytes(pattern_words(1 << depth, seed))[:length]


def c_reference(msgs):
    drv = r'''
#include <stdio.h>
#include <stdlib.h>
#include "blake2.h"
int main(void){ size_t n; static unsigned char buf[1<<20]; unsigned char out[32];
 while (scanf("%zu", &n) == 1) { for (size_t i = 0; i < n; i++) { unsigned x; scanf("%2x", &x); buf[i] = x; }
  blake2s(out, 32, buf, n, NULL, 0); for (int j = 0; j < 32; j++) printf("%02x", out[j]); printf("\n"); } return 0; }
'''
    with tempfile.TemporaryDirectory() as d:
        src = os.path.join(d, 'drv.c'); exe = os.path.join(d, 'drv')
        open(src, 'w').write(drv)
        subprocess.run(['cc', '-O2', '-I', REF, '-o', exe, src, os.path.join(REF, 'blake2s-ref.c')], check=True)
        inp = ''.join('%d %s\n' % (len(m), m.hex()) for m in msgs)
        return subprocess.run([exe], input=inp, capture_output=True, text=True, check=True).stdout.split()


def main():
    msgs = [message(k, n, s, d) for (_, k, n, s, d) in CASES]
    want = [hashlib.blake2s(m).hexdigest() for m in msgs]
    ref = c_reference(msgs)
    assert want == ref, 'hashlib and the C reference disagree'
    assert want[0] == '508c5e8c327c14e2e1a72ba34eeb452f37458b209ed63a294d999b4c86675982'
    L = ['# Generated by tools/generators/blake2s_tests.py; do not edit.',
         '# Expected digests: hashlib.blake2s, cross-checked with the official C reference.',
         'import Base',
         'import ../../../../src/crypto/blake/blake2s/blake2s.bend as B',
         'import ../../../../src/crypto/blake/blake2s/hex.bend as H',
         '',
         'def fill(n: Nat, +i: U32, +seed: U32, a: Array<U32>) -> Array<U32>:',
         '  match n:',
         '    case 0n: a',
         '    case 1n+p: fill(p,U32.inc(i),seed,Array.set(U32,a,i,U32.add(U32.mul(i,2654435761),seed)))',
         '',
         '# Bytes 0,1,2,... (mod 256), four per little-endian word.',
         'def sequence(n: Nat, +i: U32, a: Array<U32>) -> Array<U32>:',
         '  match n:',
         '    case 0n: a',
         '    case 1n+p:',
         '      +b = U32.and(U32.mul(i,4),255)',
         '      +w = U32.or(U32.or(U32.or(b,U32.shln(U32.add(b,1),8n)),U32.shln(U32.add(b,2),16n)),U32.shln(U32.add(b,3),24n))',
         '      sequence(p,U32.inc(i),Array.set(U32,a,i,w))',
         '',
         'def show(r: Maybe<&1,Array<U32>>) -> String:',
         '  match r:',
         '    case None{}: "invalid"',
         '    case Some{a}: H.hex(a)',
         '',
         'def verdict(ok: Bool, label: String, got: String, want: String) -> IO(Bool):',
         '  match ok:',
         '    case True{}:',
         '      IO.pure(Bool,True{})',
         '    case False{}:',
         '      do IO<Bool>:',
         '        IO.print("FAIL " ++ label ++ ": got " ++ got ++ " want " ++ want)',
         '        return False{}',
         '',
         'def check(label: String, +got: String, +want: String) -> IO(Bool):',
         '  verdict(String.eq(got,want),label,got,want)',
         '',
         'def pattern(+n: Nat, +seed: U32, +depth: Nat) -> String:',
         '  show(B.blake2s(fill(Nat.pow(2n,depth),0,seed,Array.new(U32,depth,0)),n))',
         '',
         'def kat(+n: Nat) -> String:',
         '  show(B.blake2s(sequence(64n,0,Array.new(U32,6n,0)),n))',
         '',
         'def abc() -> String:',
         '  show(B.blake2s(Array.set(U32,Array.new(U32,0n,0),0,6513249),3n))',
         '',
         'def count(b: Bool, n: Nat) -> Nat:',
         '  match b:',
         '    case True{}: 1n+n',
         '    case False{}: n',
         '']
    steps = []
    for (label, kind, n, seed, depth), w in zip(CASES, want):
        if kind == 'abc':
            e = 'abc()'
        elif kind == 'sequence':
            e = 'kat(%dn)' % n
        else:
            e = 'pattern(%dn,%d,%dn)' % (n, seed, depth)
        steps.append((label, e, w))
    # Capacity gate: 4 bytes fit a one-word array, 5 do not.
    steps.append(('capacity 4 of 4', 'pattern(4n,1,0n)', hashlib.blake2s(to_bytes(pattern_words(1, 1))[:4]).hexdigest()))
    steps.append(('capacity 5 of 4', 'pattern(5n,1,0n)', 'invalid'))
    steps.append(('capacity 4097 of 4096', 'pattern(4097n,1,10n)', 'invalid'))
    # Chunks of 32 cases per def keep each IO block small.
    chunks = [steps[i:i + 32] for i in range(0, len(steps), 32)]
    for ci, ch in enumerate(chunks):
        L.append('def part%d(n: Nat) -> IO(Nat):' % ci)
        L.append('  do IO<Nat>:')
        for j, (label, e, w) in enumerate(ch):
            L.append('    ok%d : Bool <- check("%s",%s,"%s")' % (j, label, e, w))
        acc = 'n'
        for j in range(len(ch)):
            acc = 'count(ok%d,%s)' % (j, acc)
        L.append('    return %s' % acc)
        L.append('')
    L.append('def main() -> IO(Unit):')
    L.append('  do IO<Unit>:')
    L.append('    n0 : Nat <- part0(0n)')
    for ci in range(1, len(chunks)):
        L.append('    n%d : Nat <- part%d(n%d)' % (ci, ci, ci - 1))
    L.append('    IO.print("blake2s: " ++ Nat.show(n%d) ++ "/%d vectors pass")' % (len(chunks) - 1, len(steps)))
    L.append('')
    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    open(OUT, 'w').write('\n'.join(L))
    print('wrote', os.path.relpath(OUT, ROOT), len(steps), 'cases')


if __name__ == '__main__':
    main()
