#!/usr/bin/env python3
"""Generates the repetitive BLAKE2b Bend files (implementation and proofs).

  python3 tools/generators/blake2b_gen.py

Writes src/crypto/blake/blake2b/{types,lane,compress,blake2b}.bend,
proofs/crypto/blake/blake2b/{compress,blocks}.bend and
tests/crypto/blake/blake2b/main.bend (expected digests from hashlib).
Written by hand: src/.../hex.bend and proofs/.../{spec,laws,api,array,proof}.bend.
"""
import os

ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), '..', '..'))
SRC = os.path.join(ROOT, 'src/crypto/blake/blake2b')
PRF = os.path.join(ROOT, 'proofs/crypto/blake/blake2b')

IV = [0x6a09e667f3bcc908, 0xbb67ae8584caa73b, 0x3c6ef372fe94f82b, 0xa54ff53a5f1d36f1,
      0x510e527fade682d1, 0x9b05688c2b3e6c1f, 0x1f83d9abfb41bd6b, 0x5be0cd19137e2179]
SIGMA = [
    [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15],
    [14, 10, 4, 8, 9, 15, 13, 6, 1, 12, 0, 2, 11, 7, 5, 3],
    [11, 8, 12, 0, 5, 2, 15, 13, 10, 14, 3, 6, 7, 1, 9, 4],
    [7, 9, 3, 1, 13, 12, 11, 14, 2, 6, 5, 10, 4, 0, 15, 8],
    [9, 0, 5, 7, 2, 4, 10, 15, 14, 1, 11, 12, 6, 8, 3, 13],
    [2, 12, 6, 10, 0, 11, 8, 3, 4, 13, 7, 5, 15, 14, 1, 9],
    [12, 5, 1, 15, 14, 13, 4, 10, 0, 7, 6, 3, 9, 2, 8, 11],
    [13, 11, 7, 14, 12, 1, 3, 9, 5, 0, 15, 4, 8, 6, 2, 10],
    [6, 15, 14, 9, 11, 3, 0, 8, 12, 2, 13, 7, 1, 4, 10, 5],
    [10, 2, 8, 4, 7, 6, 1, 5, 15, 11, 9, 14, 3, 12, 13, 0],
]
COLS = [(0, 4, 8, 12), (1, 5, 9, 13), (2, 6, 10, 14), (3, 7, 11, 15)]
DIAGS = [(0, 5, 10, 15), (1, 6, 11, 12), (2, 7, 8, 13), (3, 4, 9, 14)]
NW = 32          # U32 words per 128-byte block
ROUNDS = 12
HEADER = '# Generated by tools/generators/blake2b_gen.py; do not edit by hand.\n'


def lane(x):
    return 'T.W{%d,%d}' % (x & 0xffffffff, x >> 32)


def csv(xs):
    return ','.join(xs)


def ws(n, p='w'):
    return ['%s%d' % (p, i) for i in range(n)]


def write(path, text):
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, 'w') as f:
        f.write(text)


# ---------------------------------------------------------------- implementation

def types():
    return (HEADER + 'import Base\n\n'
            '# A 64-bit word as two 32-bit halves, low half first.\n'
            'type Lane is Data:\n  W{lo: U32, hi: U32}\n\n'
            '# The 16-word working vector v[0..15].\n'
            'type State is Data:\n  V{' + ', '.join('v%d: Lane' % i for i in range(16)) + '}\n\n'
            '# The chaining value h[0..7].\n'
            'type Chain is Data:\n  H{' + ', '.join('h%d: Lane' % i for i in range(8)) + '}\n\n'
            '# The four words G returns: v[a], v[b], v[c], v[d].\n'
            'type Quad is Data:\n  Q{a: Lane, b: Lane, c: Lane, d: Lane}\n\n'
            '# The 128-bit byte counter t as four little-endian 32-bit limbs.\n'
            'type Counter is Data:\n  C{c0: U32, c1: U32, c2: U32, c3: U32}\n')


def rot_small(n):
    # rotate right by 0 < n < 32
    return ('T.W{U32.or(U32.shrn(lo,%dn),U32.shln(hi,%dn)),U32.or(U32.shrn(hi,%dn),U32.shln(lo,%dn))}'
            % (n, 32 - n, n, 32 - n))


def lane_ops():
    s = HEADER + 'import Base\nimport ./types.bend as T\n\n'
    s += ('# 64-bit addition modulo 2^64: the low halves add, their carry-out enters the high half.\n'
          'def add(a: T.Lane, b: T.Lane) -> T.Lane:\n  match a b:\n    case T.W{+al,ah} T.W{bl,bh}:\n'
          '      +lo = U32.add(al,bl)\n'
          '      T.W{lo,U32.add(U32.add(ah,bh),Bool.to_u32(U32.is_lt(lo,al)))}\n\n')
    s += ('def xor(a: T.Lane, b: T.Lane) -> T.Lane:\n  match a b:\n'
          '    case T.W{al,ah} T.W{bl,bh}: T.W{U32.xor(al,bl),U32.xor(ah,bh)}\n\n')
    s += '# The four fixed right rotations of BLAKE2b.\n'
    s += 'def rot32(a: T.Lane) -> T.Lane:\n  match a:\n    case T.W{lo,hi}: T.W{hi,lo}\n\n'
    for n in (24, 16):
        s += 'def rot%d(a: T.Lane) -> T.Lane:\n  match a:\n    case T.W{+lo,+hi}:\n      %s\n\n' % (n, rot_small(n))
    # rotr 63 = rotr 31 of the swapped halves
    s += ('def rot63(a: T.Lane) -> T.Lane:\n  match a:\n    case T.W{+lo,+hi}:\n'
          '      T.W{U32.or(U32.shrn(hi,31n),U32.shln(lo,1n)),U32.or(U32.shrn(lo,31n),U32.shln(hi,1n))}\n')
    return s


def g_lets(names, a, b, c, d, x, y, tag):
    """Emit the eight G steps on v[a],v[b],v[c],v[d]; names maps index -> current binder."""
    out = []
    va, vb, vc, vd = names[a], names[b], names[c], names[d]
    A1, D1, C1, B1 = 'a%s1' % tag, 'd%s1' % tag, 'c%s1' % tag, 'b%s1' % tag
    A2, D2, C2, B2 = 'a%s2' % tag, 'd%s2' % tag, 'c%s2' % tag, 'b%s2' % tag
    out.append('+%s = L.add(L.add(%s,%s),%s)' % (A1, va, vb, x))
    out.append('+%s = L.rot32(L.xor(%s,%s))' % (D1, vd, A1))
    out.append('+%s = L.add(%s,%s)' % (C1, vc, D1))
    out.append('+%s = L.rot24(L.xor(%s,%s))' % (B1, vb, C1))
    out.append('+%s = L.add(L.add(%s,%s),%s)' % (A2, A1, B1, y))
    out.append('+%s = L.rot16(L.xor(%s,%s))' % (D2, D1, A2))
    out.append('+%s = L.add(%s,%s)' % (C2, C1, D2))
    out.append('+%s = L.rot63(L.xor(%s,%s))' % (B2, B1, C2))
    names[a], names[b], names[c], names[d] = A2, B2, C2, D2
    return out


def g_def():
    s = '# G (RFC 7693 section 3.1) on four words and two message words.\n'
    s += 'def g(a: T.Lane, +b: T.Lane, c: T.Lane, d: T.Lane, x: T.Lane, y: T.Lane) -> T.Quad:\n'
    for l in ('+a1 = L.add(L.add(a,b),x)', '+d1 = L.rot32(L.xor(d,a1))', '+c1 = L.add(c,d1)',
              '+b1 = L.rot24(L.xor(b,c1))', '+a2 = L.add(L.add(a1,b1),y)', '+d2 = L.rot16(L.xor(d1,a2))',
              '+c2 = L.add(c1,d2)', '+b2 = L.rot63(L.xor(b1,c2))'):
        s += '  %s\n' % l
    s += '  T.Q{a2,b2,c2,d2}\n\n'
    return s


def half(name, quads, doc):
    """name(v, x0..x7) applies G to the four quads in order; name_k receives the k-th G result."""
    xs = ws(8, 'x')
    defs = []
    cur = {i: 's%d' % i for i in range(16)}

    def call(k, cur):
        a, b, c, d = quads[k]
        others = [i for i in range(16) if i not in quads[k]]
        args = ['g(%s,%s,%s,%s,%s,%s)' % (cur[a], cur[b], cur[c], cur[d], xs[2 * k], xs[2 * k + 1])]
        args += [cur[i] for i in others] + xs[2 * k + 2:]
        return '%s_%d(%s)' % (name, k + 1, csv(args)), others
    body, others = call(0, cur)
    head = '# %s\n' % doc
    head += 'def %s(v: T.State, %s) -> T.State:\n  match v:\n' % (name, ', '.join('%s: T.Lane' % x for x in xs))
    head += '    case T.V{%s}:\n      %s\n\n' % (csv('s%d' % i for i in range(16)), body)
    defs.append(head)
    for k in range(1, 5):
        prev = quads[k - 1]
        params = ['q: T.Quad'] + ['%s: T.Lane' % cur[i] for i in others] + ['%s: T.Lane' % x for x in xs[2 * k:]]
        new = {i: 't%d_%d' % (k, i) for i in prev}
        d = 'def %s_%d(%s) -> T.State:\n  match q:\n' % (name, k, ', '.join(params))
        d += '    case T.Q{%s}:\n' % csv(new[i] for i in prev)
        cur = dict(cur)
        cur.update(new)
        if k == 4:
            d += '      T.V{%s}\n\n' % csv(cur[i] for i in range(16))
        else:
            body, others = call(k, cur)
            d += '      %s\n\n' % body
        defs.append(d)
    return ''.join(reversed(defs))


def compress_src():
    ms = ws(16, 'm')
    s = HEADER + 'import Base\nimport ./types.bend as T\nimport ./lane.bend as L\n\n'
    s += g_def()
    # Every round gets its own copies of the column and diagonal steps, so each
    # function has a single call site and the C compiler inlines the whole
    # twelve-round schedule into one function (no argument marshalling between rounds).
    for r in range(ROUNDS):
        s += half('column%d' % r, COLS, 'Round %d, G on the four columns: (0,4,8,12), (1,5,9,13), (2,6,10,14), (3,7,11,15).' % r)
        s += half('diagonal%d' % r, DIAGS, 'Round %d, G on the four diagonals: (0,5,10,15), (1,6,11,12), (2,7,8,13), (3,4,9,14).' % r)
        sg = SIGMA[r % 10]
        s += '# Round %d uses the message schedule SIGMA[%d], fixed at compile time.\n' % (r, r % 10)
        s += 'def round%d(v: T.State, %s) -> T.State:\n' % (r, ', '.join('%s: T.Lane' % m for m in ms))
        # each message word is used exactly once per round
        s += '  diagonal%d(column%d(v,%s),%s)\n\n' % (r, r, csv('m%d' % sg[j] for j in range(8)), csv('m%d' % sg[j] for j in range(8, 16)))
    s += 'def rounds(v: T.State, %s) -> T.State:\n' % ', '.join('+%s: T.Lane' % m for m in ms)
    e = 'v'
    for r in range(ROUNDS):
        e = 'round%d(%s,%s)' % (r, e, csv(ms))
    s += '  %s\n\n' % e
    iv = [lane(x) for x in IV]
    for nm, v14, doc in (('start', iv[6], 'a block that is not the last'),
                         ('start_last', 'L.xor(%s,T.W{4294967295,4294967295})' % iv[6], 'the last block (v14 inverted)')):
        s += '# v = h[0..7] || IV[0..7], v12 ^= t low 64 bits, v13 ^= t high 64 bits; %s.\n' % doc
        s += 'def %s(h: T.Chain, t: T.Counter) -> T.State:\n  match h t:\n' % nm
        s += '    case T.H{%s} T.C{t0,t1,t2,t3}:\n' % csv('h%d' % i for i in range(8))
        s += '      T.V{%s,%s,%s,%s,%s,L.xor(%s,T.W{t0,t1}),L.xor(%s,T.W{t2,t3}),%s,%s}\n\n' % (
            csv('h%d' % i for i in range(8)), iv[0], iv[1], iv[2], iv[3], iv[4], iv[5], v14, iv[7])
    s += '# h[i] ^= v[i] ^ v[i+8].\n'
    s += 'def finish(h: T.Chain, v: T.State) -> T.Chain:\n  match h v:\n'
    s += '    case T.H{%s} T.V{%s}:\n' % (csv('h%d' % i for i in range(8)), csv('v%d' % i for i in range(16)))
    s += '      T.H{%s}\n\n' % csv('L.xor(L.xor(h%d,v%d),v%d)' % (i, i, i + 8) for i in range(8))
    wl = ', '.join('%s: U32' % w for w in ws(NW))
    lanes = csv('T.W{w%d,w%d}' % (2 * i, 2 * i + 1) for i in range(16))
    for nm, st in (('compress', 'start'), ('compress_last', 'start_last')):
        s += '# The compression function F on one block of 32 little-endian words.\n'
        s += 'def %s(+h: T.Chain, t: T.Counter, %s) -> T.Chain:\n' % (nm, wl)
        s += '  finish(h,rounds(%s(h,t),%s))\n\n' % (st, lanes)
    s += ('# t += x on the 128-bit counter.\n'
          'def bump(c: T.Counter, +x: U32) -> T.Counter:\n  match c:\n    case T.C{c0,c1,c2,c3}:\n'
          '      +s0 = U32.add(c0,x)\n      +k0 = Bool.to_u32(U32.is_lt(s0,x))\n'
          '      +s1 = U32.add(c1,k0)\n      +k1 = Bool.to_u32(U32.is_lt(s1,k0))\n'
          '      +s2 = U32.add(c2,k1)\n'
          '      T.C{s0,s1,s2,U32.add(c3,Bool.to_u32(U32.is_lt(s2,k1)))}\n')
    return s


def api_src():
    s = HEADER + 'import Base\nimport ./types.bend as T\nimport ./compress.bend as F\n\n'
    # absorb chain (defined last word first: no forward references)
    for k in range(NW - 1, -1, -1):
        prev = ''.join(', w%d: U32' % i for i in range(k))
        s += 'def read%d(+index: U32, t: T.Counter, h: T.Chain%s, pair: Array<U32> & U32) -> Array<U32> & T.Chain:\n' % (k, prev)
        s += '  (a,w%d) = pair\n' % k
        if k == NW - 1:
            s += '  (a,F.compress(h,t,%s))\n\n' % csv(ws(NW))
        else:
            s += '  read%d(index,t,h,%s,Array.get(U32,a,U32.add(index,%d)))\n\n' % (k + 1, csv(ws(k + 1)), k + 1)
    s += ('def absorb(a: Array<U32>, +index: U32, t: T.Counter, h: T.Chain) -> Array<U32> & T.Chain:\n'
          '  read0(index,t,h,Array.get(U32,a,index))\n\n')
    s += ('# Only the first n bytes of the word are message bytes; the rest are zero.\n'
          'def keep(w: U32, n: Nat) -> U32:\n  match n:\n    case 0n: 0\n    case 1n: U32.and(w,255)\n'
          '    case 2n: U32.and(w,65535)\n    case 3n: U32.and(w,16777215)\n    case _: w\n\n'
          'def mask(w: U32, +pos: Nat, +remain: Nat) -> U32:\n  keep(w,Nat.sub(remain,pos))\n\n')
    for k in range(NW - 1, -1, -1):
        prev = ''.join(', w%d: U32' % i for i in range(k))
        s += 'def last%d(+remain: Nat, +index: U32, t: T.Counter, h: T.Chain%s, pair: Array<U32> & U32) -> T.Chain:\n' % (k, prev)
        s += '  (a,w%d) = pair\n' % k
        if k == NW - 1:
            s += '  F.compress_last(h,t,%s)\n\n' % csv('mask(w%d,%dn,remain)' % (i, 4 * i) for i in range(NW))
        else:
            s += '  last%d(remain,index,t,h,%s,Array.get(U32,a,U32.add(index,%d)))\n\n' % (k + 1, csv(ws(k + 1)), k + 1)
    s += ('# The last block holds the final 1..128 bytes (0 for the empty message).\n'
          'def final(a: Array<U32>, +index: U32, +remain: Nat, t: T.Counter, h: T.Chain) -> T.Chain:\n'
          '  last0(remain,index,F.bump(t,U32.from_nat(remain)),h,Array.get(U32,a,index))\n\n'
          'def blocks(n: Nat, +index: U32, +remain: Nat, t: T.Counter, pair: Array<U32> & T.Chain) -> T.Chain:\n'
          '  match n pair:\n'
          '    case 0n Tuple{a,h}: final(a,index,remain,t,h)\n'
          '    case 1n+p Tuple{a,h}:\n'
          '      +t2 = F.bump(t,128)\n'
          '      blocks(p,U32.add(index,32),remain,t2,absorb(a,index,t2,h))\n\n')
    h0 = IV[0] ^ 0x01010040
    s += ('# IV with the parameter block folded into h0: digest length 64, no key, fanout 1, depth 1.\n'
          'def initial() -> T.Chain:\n  T.H{%s}\n\n' % csv([lane(h0)] + [lane(x) for x in IV[1:]]))
    s += ('def unchecked(a: Array<U32>, +length: Nat) -> T.Chain:\n'
          '  +n = Nat.div(Nat.sub(length,1n),128n)\n'
          '  blocks(n,0,Nat.sub(length,Nat.mul(n,128n)),T.C{0,0,0,0},(a,initial()))\n\n')
    s += 'def digest(h: T.Chain) -> Array<U32>:\n  match h:\n'
    s += '    case T.H{%s}:\n' % csv('T.W{l%d,u%d}' % (i, i) for i in range(8))
    s += '      a = Array.new(U32,4n,0)\n'
    for i in range(8):
        s += '      a = Array.set(U32,a,%d,l%d)\n      a = Array.set(U32,a,%d,u%d)\n' % (2 * i, i, 2 * i + 1, i)
    s += '      a\n\n'
    s += ('def checked(valid: Bool, a: Array<U32>, length: Nat) -> Maybe<&1,Array<U32>>:\n  match valid:\n'
          '    case False{}: None{}\n    case True{}: Some{digest(unchecked(a,length))}\n\n'
          'def sized(+length: Nat, pair: Array<U32> & U32) -> Maybe<&1,Array<U32>>:\n  (a,capacity) = pair\n'
          '  checked(Nat.is_le(length,Nat.mul(4n,U32.to_nat(capacity))),a,length)\n\n'
          '# BLAKE2b-512, unkeyed. The message is packed little-endian, four bytes per word;\n'
          '# byte_length is its length in bytes (None when it exceeds 4 * capacity). The\n'
          '# digest is 16 little-endian words (64 bytes).\n'
          'def blake2b(words: Array<U32>, byte_length: Nat) -> Maybe<&1,Array<U32>>:\n'
          '  sized(byte_length,Array.size(U32,words))\n')
    return s


# ---------------------------------------------------------------- proofs

def spec_chain(v, quads, xs):
    e = v
    for k, (a, b, c, d) in enumerate(quads):
        e = 'S.G(%s,%dn,%dn,%dn,%dn,%s,%s)' % (e, a, b, c, d, xs[2 * k], xs[2 * k + 1])
    return e


def compress_proof():
    xs = ws(8, 'x')
    ms = ws(16, 'm')
    pat = 'T.V{%s}' % csv('T.W{l%d,u%d}' % (i, i) for i in range(16))
    s = HEADER + ('import Base\nimport ../../../../src/crypto/blake/blake2b/types.bend as T\n'
                  'import ../../../../src/crypto/blake/blake2b/compress.bend as I\nimport ../../../../spec/crypto/blake/blake2b.bend as S\n\n')
    mlist = '[%s]' % csv(ms)
    for r in range(ROUNDS):
        for nm, quads in (('column%d' % r, COLS), ('diagonal%d' % r, DIAGS)):
            s += 'law %s_correct:\n  for +v: T.State\n' % nm
            s += ''.join('  for +%s: T.Lane\n' % x for x in xs)
            s += '  {I.%s(v,%s) == %s : T.State}\n\n' % (nm, csv(xs), spec_chain('v', quads, xs))
            s += 'def %s_correct(v,%s):\n  match v %s:\n    case %s %s: {==}\n\n' % (
                nm, csv(xs), ' '.join(xs), pat, ' '.join('T.W{p%d,q%d}' % (i, i) for i in range(8)))
        sg = SIGMA[r % 10]
        cx = ['m%d' % sg[j] for j in range(8)]
        dx = ['m%d' % sg[j] for j in range(8, 16)]
        colS = spec_chain('v', COLS, cx)
        s += 'law round%d_correct:\n  for +v: T.State\n' % r
        s += ''.join('  for +%s: T.Lane\n' % m for m in ms)
        s += '  {I.round%d(v,%s) == S.round(v,%s,S.sigma(%dn)) : T.State}\n\n' % (r, csv(ms), mlist, r % 10)
        s += 'def round%d_correct(v,%s):\n' % (r, csv(ms))
        s += '  Equal.trans(T.State,\n'
        s += '    I.diagonal%d(I.column%d(v,%s),%s),\n' % (r, r, csv(cx), csv(dx))
        s += '    I.diagonal%d(%s,%s),\n' % (r, colS, csv(dx))
        s += '    %s,\n' % spec_chain(colS, DIAGS, dx)
        s += '    Equal.cong(T.State,T.State,t => I.diagonal%d(t,%s),I.column%d(v,%s),%s,column%d_correct(v,%s)),\n' % (
            r, csv(dx), r, csv(cx), colS, r, csv(cx))
        s += '    diagonal%d_correct(%s,%s))\n\n' % (r, colS, csv(dx))
    # twelve rounds, innermost first
    s += 'law rounds_correct:\n  for +v: T.State\n' + ''.join('  for +%s: T.Lane\n' % m for m in ms)
    s += '  {I.rounds(v,%s) == S.rounds(12n,0n,v,%s) : T.State}\n\n' % (csv(ms), mlist)
    # left side after k rounds (impl) and right side after k rounds (spec)
    def imp(k):
        e = 'v'
        for r in range(k):
            e = 'I.round%d(%s,%s)' % (r, e, csv(ms))
        return e

    def spc(k):
        e = 'v'
        for r in range(k):
            e = 'S.round(%s,%s,S.sigma(%dn))' % (e, mlist, r % 10)
        return e

    def mixed(k, n):
        # impl rounds k..n-1 applied to the spec result of the first k rounds
        e = spc(k)
        for r in range(k, n):
            e = 'I.round%d(%s,%s)' % (r, e, csv(ms))
        return e
    s += 'def rounds_correct(v,%s):\n' % csv(ms)
    # chain: mixed(0,12) -> mixed(1,12) -> ... -> mixed(12,12)=spc(12)
    s += '  %s\n\n' % chain_rounds(mixed, spc, ms, mlist, 12)
    # start / finish / compress
    hp = 'T.H{%s}' % csv('T.W{g%d,e%d}' % (i, i) for i in range(8))
    tp = 'T.C{t0,t1,t2,t3}'
    for nm, f in (('start', 'False{}'), ('start_last', 'True{}')):
        s += 'law %s_correct:\n  for +h: T.Chain\n  for +t: T.Counter\n' % nm
        s += '  {I.%s(h,t) == S.start(h,t,%s) : T.State}\n\n' % (nm, f)
        s += 'def %s_correct(h,t):\n  match h t:\n    case %s %s: {==}\n\n' % (nm, hp, tp)
    s += 'law finish_correct:\n  for +h: T.Chain\n  for +v: T.State\n  {I.finish(h,v) == S.finish(h,v) : T.Chain}\n\n'
    s += 'def finish_correct(h,v):\n  match h v:\n    case %s %s: {==}\n\n' % (hp, pat)
    lanes = csv('T.W{w%d,w%d}' % (2 * i, 2 * i + 1) for i in range(16))
    for nm, st, f in (('compress', 'start', 'False{}'), ('compress_last', 'start_last', 'True{}')):
        s += 'law %s_correct:\n  for +h: T.Chain\n  for +t: T.Counter\n' % nm
        s += ''.join('  for +w%d: U32\n' % i for i in range(NW))
        s += '  {I.%s(h,t,%s) == S.compress(h,[%s],t,%s) : T.Chain}\n\n' % (nm, csv(ws(NW)), lanes, f)
        s += 'def %s_correct(h,t,%s):\n' % (nm, csv(ws(NW)))
        L = '[%s]' % lanes
        a0 = 'I.finish(h,I.rounds(I.%s(h,t),%s))' % (st, lanes)
        a1 = 'I.finish(h,S.rounds(12n,0n,I.%s(h,t),%s))' % (st, L)
        a2 = 'I.finish(h,S.rounds(12n,0n,S.start(h,t,%s),%s))' % (f, L)
        a3 = 'S.finish(h,S.rounds(12n,0n,S.start(h,t,%s),%s))' % (f, L)
        s += '  Equal.trans(T.Chain,%s,%s,%s,\n' % (a0, a1, a3)
        s += '    Equal.cong(T.State,T.Chain,x => I.finish(h,x),I.rounds(I.%s(h,t),%s),S.rounds(12n,0n,I.%s(h,t),%s),rounds_correct(I.%s(h,t),%s)),\n' % (
            st, lanes, st, L, st, lanes)
        s += '    Equal.trans(T.Chain,%s,%s,%s,\n' % (a1, a2, a3)
        s += '      Equal.cong(T.State,T.Chain,x => I.finish(h,S.rounds(12n,0n,x,%s)),I.%s(h,t),S.start(h,t,%s),%s_correct(h,t)),\n' % (L, st, f, st)
        s += '      finish_correct(h,S.rounds(12n,0n,S.start(h,t,%s),%s))))\n\n' % (f, L)
    s += ('law bump_correct:\n  for +c: T.Counter\n  for +x: U32\n  {I.bump(c,x) == S.advance(c,x) : T.Counter}\n\n'
          'def bump_correct(c,x):\n  match c:\n    case T.C{c0,c1,c2,c3}: {==}\n')
    return s


def chain_rounds(mixed, spc, ms, mlist, n):
    # Proves mixed(0,n) == spc(n) by n steps; step k turns round k of the impl into the spec round.
    def step(k):
        # {mixed(k,n) == mixed(k+1,n)}: replace I.round_k(spc(k)) by S.round(spc(k),..)
        inner_i = 'I.round%d(%s,%s)' % (k, spc(k), csv(ms))
        inner_s = 'S.round(%s,%s,S.sigma(%dn))' % (spc(k), mlist, k % 10)
        ctx = 'x'
        for r in range(k + 1, n):
            ctx = 'I.round%d(%s,%s)' % (r, ctx, csv(ms))
        pf = 'round%d_correct(%s,%s)' % (k, spc(k), csv(ms))
        if k + 1 == n:
            return pf
        return 'Equal.cong(T.State,T.State,x => %s,%s,%s,%s)' % (ctx, inner_i, inner_s, pf)
    e = step(n - 1)
    for k in range(n - 2, -1, -1):
        e = 'Equal.trans(T.State,%s,%s,%s,\n    %s,\n    %s)' % (mixed(k, n), mixed(k + 1, n), spc(n), step(k), e)
    return e


def blocks_proof():
    s = HEADER + ('import Base\nimport ../../../../src/crypto/blake/blake2b/types.bend as T\n'
                  'import ../../../../src/crypto/blake/blake2b/compress.bend as F\n'
                  'import ../../../../src/crypto/blake/blake2b/blake2b.bend as I\n'
                  'import ../../../../spec/crypto/blake/blake2b.bend as S\nimport ./compress.bend as C\nimport ./array.bend as A\n\n')
    lanes = csv('T.W{w%d,w%d}' % (2 * i, 2 * i + 1) for i in range(16))
    # read chain (non-final blocks)
    for k in range(NW - 1, -1, -1):
        prev = ws(k)
        s += 'law read%d_correct:\n  for +index: U32\n  for +t: T.Counter\n  for +h: T.Chain\n' % k
        s += ''.join('  for +%s: U32\n' % w for w in prev)
        s += '  for pair: Array<U32> & U32\n'
        acc = '[%s]' % csv(reversed(prev))
        s += '  {I.read%d(index,t,h,%spair) == S.gather(%dn,index,%d,False{},0n,t,h,%s,pair) : Array<U32> & T.Chain}\n\n' % (
            k, ''.join(w + ',' for w in prev), NW - 1 - k, k + 1, acc)
        s += 'def read%d_correct(index,t,h,%spair):\n' % (k, ''.join(w + ',' for w in prev))
        s += '  (a,w%d) = pair\n' % k
        if k == NW - 1:
            s += '  Equal.cong(T.Chain,Array<U32> & T.Chain,x => (a,x),F.compress(h,t,%s),S.compress(h,[%s],t,False{}),C.compress_correct(h,t,%s))\n\n' % (
                csv(ws(NW)), lanes, csv(ws(NW)))
        else:
            s += '  read%d_correct(index,t,h,%s,Array.get(U32,a,U32.add(index,%d)))\n\n' % (k + 1, csv(ws(k + 1)), k + 1)
    s += ('law absorb_correct:\n  for a: Array<U32>\n  for +index: U32\n  for +t: T.Counter\n  for +h: T.Chain\n'
          '  {I.absorb(a,index,t,h) == S.absorb(a,index,t,h) : Array<U32> & T.Chain}\n\n'
          'def absorb_correct(a,index,t,h):\n  read0_correct(index,t,h,Array.get(U32,a,index))\n\n')
    # masking of the last block
    s += ('law keep_correct:\n  for +w: U32\n  for +n: Nat\n  {I.keep(w,n) == S.keep(w,n) : U32}\n\n'
          'def keep_correct(w,n):\n  match n:\n    case 0n: {==}\n    case 1n: {==}\n    case 2n: {==}\n    case 3n: {==}\n    case 4n+p: {==}\n\n')
    im = ['I.mask(w%d,%dn,remain)' % (i, 4 * i) for i in range(NW)]
    sm = ['S.mask(w%d,%dn,remain)' % (i, 4 * i) for i in range(NW)]
    s += 'law masks_correct:\n  for +remain: Nat\n' + ''.join('  for +w%d: U32\n' % i for i in range(NW))
    s += '  {[%s] == S.trim([%s],0n,remain) : List<&2,U32>}\n\n' % (csv(im), csv(ws(NW)))
    # rewrite each I.mask into S.mask, last word first
    s += 'def masks_correct(remain,%s):\n' % csv(ws(NW))
    for i in range(NW):
        cur = sm[:i] + ['_'] + im[i + 1:]
        s += '  %%Equal.sym(U32,I.mask(w%d,%dn,remain),S.mask(w%d,%dn,remain),keep_correct(w%d,Nat.sub(remain,%dn))) : {[%s] == S.trim([%s],0n,remain) : List<&2,U32>}\n' % (
            i, 4 * i, i, 4 * i, i, 4 * i, csv(cur), csv(ws(NW)))
    s += '  {==}\n\n'
    mlanes = csv('T.W{%s,%s}' % (im[2 * i], im[2 * i + 1]) for i in range(16))
    for k in range(NW - 1, -1, -1):
        prev = ws(k)
        s += 'law last%d_correct:\n  for +remain: Nat\n  for +index: U32\n  for +t: T.Counter\n  for +h: T.Chain\n' % k
        s += ''.join('  for +%s: U32\n' % w for w in prev)
        s += '  for pair: Array<U32> & U32\n'
        acc = '[%s]' % csv(reversed(prev))
        s += '  {I.last%d(remain,index,t,h,%spair) == Pair.snd(Array<U32>,T.Chain,S.gather(%dn,index,%d,True{},remain,t,h,%s,pair)) : T.Chain}\n\n' % (
            k, ''.join(w + ',' for w in prev), NW - 1 - k, k + 1, acc)
        s += 'def last%d_correct(remain,index,t,h,%spair):\n' % (k, ''.join(w + ',' for w in prev))
        s += '  (a,+w%d) = pair\n' % k
        if k == NW - 1:
            L = '[%s]' % csv(im)
            R = 'S.trim([%s],0n,remain)' % csv(ws(NW))
            s += '  Equal.trans(T.Chain,F.compress_last(h,t,%s),S.compress(h,[%s],t,True{}),S.compress(h,S.lanes(%s),t,True{}),\n' % (csv(im), mlanes, R)
            s += '    C.compress_last_correct(h,t,%s),\n' % csv(im)
            s += '    Equal.cong(List<&2,U32>,T.Chain,x => S.compress(h,S.lanes(x),t,True{}),%s,%s,masks_correct(remain,%s)))\n\n' % (L, R, csv(ws(NW)))
        else:
            s += '  last%d_correct(remain,index,t,h,%s,Array.get(U32,a,U32.add(index,%d)))\n\n' % (k + 1, csv(ws(k + 1)), k + 1)
    s += ('law final_correct:\n  for a: Array<U32>\n  for +index: U32\n  for +remain: Nat\n  for +t: T.Counter\n  for +h: T.Chain\n'
          '  {I.final(a,index,remain,t,h) == S.final(a,index,remain,t,h) : T.Chain}\n\n'
          'def final_correct(a,index,remain,t,h):\n'
          '  %Equal.sym(T.Counter,F.bump(t,U32.from_nat(remain)),S.advance(t,U32.from_nat(remain)),C.bump_correct(t,U32.from_nat(remain))) : '
          '{I.last0(remain,index,_,h,Array.get(U32,a,index)) == S.final(a,index,remain,t,h) : T.Chain}\n'
          '  last0_correct(remain,index,S.advance(t,U32.from_nat(remain)),h,Array.get(U32,a,index))\n\n')
    s += '''law blocks_step:
  for +n: Nat
  for +index: U32
  for +remain: Nat
  for +t: T.Counter
  for -a: Array<U32>
  for +h: T.Chain
  for view: Sigma<&2,&1,A.Tree,z => {a == A.thaw(z) : Array<U32>}>
  for recurse: @pair: (Array<U32> & T.Chain) -> {I.blocks(n,U32.add(index,32),remain,S.advance(t,128),pair) == S.blocks(n,U32.add(index,32),remain,S.advance(t,128),pair) : T.Chain}
  {I.blocks(1n+n,index,remain,t,(a,h)) == S.blocks(1n+n,index,remain,t,(a,h)) : T.Chain}

def blocks_step(n,index,remain,t,a,h,view,recurse):
  match view:
    case Tuple{+tree,pf}:
      %Equal.sym(Array<U32>,a,A.thaw(tree),pf) : {I.blocks(1n+n,index,remain,t,(_,h)) == S.blocks(1n+n,index,remain,t,(_,h)) : T.Chain}
      %Equal.sym(T.Counter,F.bump(t,128),S.advance(t,128),C.bump_correct(t,128)) : {I.blocks(n,U32.add(index,32),remain,_,I.absorb(A.thaw(tree),index,_,h)) == S.blocks(1n+n,index,remain,t,(A.thaw(tree),h)) : T.Chain}
      Equal.trans(T.Chain,
        I.blocks(n,U32.add(index,32),remain,S.advance(t,128),I.absorb(A.thaw(tree),index,S.advance(t,128),h)),
        S.blocks(n,U32.add(index,32),remain,S.advance(t,128),I.absorb(A.thaw(tree),index,S.advance(t,128),h)),
        S.blocks(n,U32.add(index,32),remain,S.advance(t,128),S.absorb(A.thaw(tree),index,S.advance(t,128),h)),
        recurse(I.absorb(A.thaw(tree),index,S.advance(t,128),h)),
        Equal.cong(Array<U32> & T.Chain,T.Chain,pair => S.blocks(n,U32.add(index,32),remain,S.advance(t,128),pair),
          I.absorb(A.thaw(tree),index,S.advance(t,128),h),S.absorb(A.thaw(tree),index,S.advance(t,128),h),absorb_correct(A.thaw(tree),index,S.advance(t,128),h)))

law blocks_correct:
  for +n: Nat
  for +index: U32
  for +remain: Nat
  for +t: T.Counter
  for pair: Array<U32> & T.Chain
  {I.blocks(n,index,remain,t,pair) == S.blocks(n,index,remain,t,pair) : T.Chain}

def blocks_correct(n,index,remain,t,pair):
  match n pair:
    case 0n Tuple{a,h}: final_correct(a,index,remain,t,h)
    case 1n+p Tuple{a,h}:
      blocks_step(p,index,remain,t,a,h,A.reify(a),pair => blocks_correct(p,U32.add(index,32),remain,S.advance(t,128),pair))

law unchecked_correct:
  for a: Array<U32>
  for +length: Nat
  {I.unchecked(a,length) == S.unchecked(a,length) : T.Chain}

def unchecked_correct(a,length):
  blocks_correct(Nat.div(Nat.sub(length,1n),128n),0,Nat.sub(length,Nat.mul(Nat.div(Nat.sub(length,1n),128n),128n)),T.C{0,0,0,0},(a,I.initial()))

law digest_correct:
  for +h: T.Chain
  {I.digest(h) == S.digest(h) : Array<U32>}

def digest_correct(h):
  match h:
    case T.H{@PAT@}: {==}
'''.replace('@PAT@', csv('T.W{l%d,u%d}' % (i, i) for i in range(8)))
    s += '''
law checked_true_reified:
  for -a: Array<U32>
  for +length: Nat
  for view: Sigma<&2,&1,A.Tree,z => {a == A.thaw(z) : Array<U32>}>
  {I.checked(True{},a,length) == S.checked(True{},a,length) : Maybe<&1,Array<U32>>}

def checked_true_reified(a,length,view):
  match view:
    case Tuple{+tree,pf}:
      %Equal.sym(Array<U32>,a,A.thaw(tree),pf) : {I.checked(True{},_,length) == S.checked(True{},_,length) : Maybe<&1,Array<U32>>}
      Equal.trans(Maybe<&1,Array<U32>>,
        Some{I.digest(I.unchecked(A.thaw(tree),length))},
        Some{I.digest(S.unchecked(A.thaw(tree),length))},
        Some{S.digest(S.unchecked(A.thaw(tree),length))},
        Equal.cong(T.Chain,Maybe<&1,Array<U32>>,x => Some{I.digest(x)},I.unchecked(A.thaw(tree),length),S.unchecked(A.thaw(tree),length),unchecked_correct(A.thaw(tree),length)),
        Equal.cong(Array<U32>,Maybe<&1,Array<U32>>,x => Some{x},I.digest(S.unchecked(A.thaw(tree),length)),S.digest(S.unchecked(A.thaw(tree),length)),digest_correct(S.unchecked(A.thaw(tree),length))))

law checked_correct:
  for +valid: Bool
  for a: Array<U32>
  for +length: Nat
  {I.checked(valid,a,length) == S.checked(valid,a,length) : Maybe<&1,Array<U32>>}

def checked_correct(valid,a,length):
  match valid:
    case False{}: {==}
    case True{}: checked_true_reified(a,length,A.reify(a))

law sized_correct:
  for +length: Nat
  for pair: Array<U32> & U32
  {I.sized(length,pair) == S.sized(length,pair) : Maybe<&1,Array<U32>>}

def sized_correct(length,pair):
  (a,capacity) = pair
  checked_correct(Nat.is_le(length,Nat.mul(4n,U32.to_nat(capacity))),a,length)

law blake2b_correct:
  for words: Array<U32>
  for +byte_length: Nat
  {I.blake2b(words,byte_length) == S.blake2b(words,byte_length) : Maybe<&1,Array<U32>>}

def blake2b_correct(words,byte_length):
  sized_correct(byte_length,Array.size(U32,words))
'''
    return s


def main():
    write(os.path.join(SRC, 'types.bend'), types())
    write(os.path.join(SRC, 'lane.bend'), lane_ops())
    write(os.path.join(SRC, 'compress.bend'), compress_src())
    write(os.path.join(SRC, 'blake2b.bend'), api_src())
    write(os.path.join(PRF, 'compress.bend'), compress_proof())
    write(os.path.join(PRF, 'blocks.bend'), blocks_proof())
    write_tests()



# ---------------------------------------------------------------- tests

LENGTHS = [0, 1, 3, 4, 63, 64, 65, 127, 128, 129, 1023, 1024, 1025, 2048, 3073, 8193]


def filled(depth, seed):
    out = bytearray()
    for i in range(1 << depth):
        out += ((i * 2654435761 + seed) & 0xffffffff).to_bytes(4, 'little')
    return bytes(out)


def min_depth(n):
    return max(0, (((n + 3) // 4) - 1).bit_length())


def tests_src():
    import hashlib
    s = HEADER + '''import Base
import ../../../../src/crypto/blake/blake2b/blake2b.bend as B
import ../../../../src/crypto/blake/blake2b/hex.bend as H
import ../../../../spec/crypto/blake/blake2b.bend as S

# BLAKE2b-512 test vectors. Expected digests come from Python's hashlib.blake2b
# (and RFC 7693 Appendix A for "abc"). Each line prints "ok" or "FAIL"; the last
# line counts the failures. The spec rows run the executable specification.

def fill(n: Nat, +i: U32, +seed: U32, a: Array<U32>) -> Array<U32>:
  match n:
    case 0n: a
    case 1n+p: fill(p,U32.inc(i),seed,Array.set(U32,a,i,U32.add(U32.mul(i,2654435761),seed)))

def pack(ws: List<&2,U32>, +i: U32, a: Array<U32>) -> Array<U32>:
  match ws:
    case Nil{}: a
    case w <> rest: pack(rest,U32.inc(i),Array.set(U32,a,i,w))

def show(r: Maybe<&1,Array<U32>>) -> String:
  match r:
    case None{}: "invalid"
    case Some{a}: H.hex(a)

def report(name: String, got: String, want: String, same: Bool) -> IO(U32):
  match same:
    case True{}:
      do IO<U32>:
        IO.print("ok   " ++ name)
        return 0
    case False{}:
      do IO<U32>:
        IO.print("FAIL " ++ name ++ " got " ++ got ++ " want " ++ want)
        return 1

def verdict(name: String, +got: String, +want: String) -> IO(U32):
  report(name,got,want,String.eq(got,want))

def filled(name: String, +length: Nat, +seed: U32, +depth: Nat, +want: String) -> IO(U32):
  verdict(name,show(B.blake2b(fill(Nat.pow(2n,depth),0,seed,Array.new(U32,depth,0)),length)),want)

def spec_filled(name: String, +length: Nat, +seed: U32, +depth: Nat, +want: String) -> IO(U32):
  verdict(name,show(S.blake2b(fill(Nat.pow(2n,depth),0,seed,Array.new(U32,depth,0)),length)),want)

def packed(name: String, ws: List<&2,U32>, +length: Nat, +depth: Nat, +want: String) -> IO(U32):
  verdict(name,show(B.blake2b(pack(ws,0,Array.new(U32,depth,0)),length)),want)

def main() -> IO(Unit):
  do IO<Unit>:
'''
    rows = []

    def words_of(b):
        b = b + bytes((-len(b)) % 4)
        return [int.from_bytes(b[i:i + 4], 'little') for i in range(0, len(b), 4)] or [0]
    for name, msg in (('rfc7693 abc', b'abc'), ('empty string', b''),
                      ('quick brown fox', b'The quick brown fox jumps over the lazy dog')):
        w = words_of(msg)
        d = max(0, (len(w) - 1).bit_length())
        rows.append('packed("%s",[%s],%dn,%dn,"%s")' % (name, ','.join(str(x) for x in w), len(msg), d,
                                                      hashlib.blake2b(msg).hexdigest()))
    for n in LENGTHS:
        for extra in (0, 1):
            d = min_depth(n) + extra
            seed = (n * 7 + 42 + extra) & 0xffffffff
            want = hashlib.blake2b(filled(d, seed)[:n]).hexdigest()
            rows.append('filled("len %d depth %d",%dn,%d,%dn,"%s")' % (n, d, n, seed, d, want))
    # byte_length past 4 * capacity
    rows.append('filled("len 5 over capacity 4",5n,1,0n,"invalid")')
    rows.append('filled("len 1025 over capacity 1024",1025n,1,8n,"invalid")')
    for n in (0, 3, 128, 129, 300):
        d = min_depth(n) + 1
        seed = 99 + n
        want = hashlib.blake2b(filled(d, seed)[:n]).hexdigest()
        rows.append('spec_filled("spec len %d depth %d",%dn,%d,%dn,"%s")' % (n, d, n, seed, d, want))
    for i, r in enumerate(rows):
        s += '    f%d : U32 <- %s\n' % (i, r)
    total = ' + '.join('f%d' % i for i in range(len(rows)))
    s += '    IO.print("failures: " ++ U32.show((%s : U32)))\n' % total
    return s


def write_tests():
    write(os.path.join(ROOT, 'tests/crypto/blake/blake2b/main.bend'), tests_src())



if __name__ == '__main__':
    main()
