#!/usr/bin/env python3
"""Emit the repetitive ChaCha8Rand Bend sources (implementation and proofs).

  python3 tools/generators/chacha8rand_gen.py

Writes, relative to the repository root:
  src/math/random/chacha8/block.bend          the unrolled ChaCha8 double round,
                                              block and four-block group
  proofs/math/random/chacha8/rounds.bend      the double round against the
                                              list-based specification

The specification (spec/math/random/chacha8rand.bend), the source
(src/math/random/chacha8.bend) and the other proofs are hand-written.
"""
import os

ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), '..', '..'))
SRC = os.path.join(ROOT, 'src/math/random/chacha8')
PRF = os.path.join(ROOT, 'proofs/math/random/chacha8')

# "expand 32-byte k" as four little-endian words
SIGMA = [0x61707865, 0x3320646E, 0x79622D32, 0x6B206574]
# quarter rounds of one double round (RFC 8439 section 2.3): columns, diagonals
QRS = [(0, 4, 8, 12), (1, 5, 9, 13), (2, 6, 10, 14), (3, 7, 11, 15),
       (0, 5, 10, 15), (1, 6, 11, 12), (2, 7, 8, 13), (3, 4, 9, 14)]


def ws(p, n, plus=''):
    return ','.join('%s%s%d' % (plus, p, i) for i in range(n))


def write(path, text):
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, 'w') as f:
        f.write(text)
    print('wrote', os.path.relpath(path, ROOT))


def rotl(x, n):
    return 'U32.or(U32.shln(%s,%dn),U32.shrn(%s,%dn))' % (x, n, x, 32 - n)


def gen_block():
    L = ['# Generated by tools/generators/chacha8rand_gen.py; do not edit.',
         '# The ChaCha8 core of ChaCha8Rand (C2SP chacha8rand; Go\'s',
         '# internal/chacha8rand block_generic). One double round is fully unrolled',
         '# (four column and four diagonal quarter rounds, RFC 8439 section 2.1-2.3,',
         '# constant rotations); a block is four double rounds (eight rounds). As',
         '# C2SP specifies, only the key words 4..11 are added back after the rounds:',
         '# the constants and the counter are not (the standard ChaCha output minus',
         '# them). A group is four consecutive blocks interleaved word by word, read',
         '# as 32 little-endian 64-bit words: word 2w of the group is word w of the',
         '# first block (low half) and of the second (high half), word 2w + 1 the',
         '# same for the third and fourth block.',
         '#',
         '# Proved equal to spec/math/random/chacha8rand.bend for every key and',
         '# counter (proofs/math/random/chacha8/).',
         'import Base',
         'import ../../u64.bend as W',
         '',
         '# the 256-bit key as eight little-endian words',
         'type Key is Data:',
         '  K{%s}' % ', '.join('k%d: U32' % i for i in range(8)),
         '',
         '# the ChaCha state x[0..15]',
         'type Vector is Data:',
         '  V{%s}' % ', '.join('v%d: U32' % i for i in range(16)),
         '',
         '# the initial state: constants, key, 32-bit block counter, zero nonce',
         'def init(k: Key, +ctr: U32) -> Vector:',
         '  match k:',
         '    case K{%s}:' % ws('k', 8),
         '      V{%s,%s,ctr,0,0,0}' % (','.join(str(c) for c in SIGMA), ws('k', 8)),
         '',
         '# one double round: four column quarter rounds, then four diagonal ones',
         'def dr(v: Vector) -> Vector:',
         '  match v:',
         '    case V{%s}:' % ws('a', 16, '+')]
    cur = ['a%d' % i for i in range(16)]
    for qi, (a, b, c, d) in enumerate(QRS):
        va, vb, vc, vd = cur[a], cur[b], cur[c], cur[d]
        n = lambda s: 'q%d%s' % (qi, s)

        def rot(dst, p, q, r):
            L.append('      +%sx = U32.xor(%s,%s)' % (dst, p, q))
            L.append('      +%s = %s' % (dst, rotl(dst + 'x', r)))
        L.append('      +%s = U32.add(%s,%s)' % (n('a1'), va, vb))
        rot(n('d1'), vd, n('a1'), 16)
        L.append('      +%s = U32.add(%s,%s)' % (n('c1'), vc, n('d1')))
        rot(n('b1'), vb, n('c1'), 12)
        L.append('      +%s = U32.add(%s,%s)' % (n('a2'), n('a1'), n('b1')))
        rot(n('d2'), n('d1'), n('a2'), 8)
        L.append('      +%s = U32.add(%s,%s)' % (n('c2'), n('c1'), n('d2')))
        rot(n('b2'), n('b1'), n('c2'), 7)
        cur[a], cur[b], cur[c], cur[d] = n('a2'), n('b2'), n('c2'), n('d2')
    L.append('      V{%s}' % ','.join(cur))
    L += ['',
          '# the key words added back to words 4..11',
          'def finish(k: Key, v: Vector) -> Vector:',
          '  match k v:',
          '    case K{%s} V{%s}:' % (ws('k', 8), ws('v', 16)),
          '      V{v0,v1,v2,v3,%s,v12,v13,v14,v15}' % ','.join('U32.add(v%d,k%d)' % (i + 4, i) for i in range(8)),
          '',
          '# the ChaCha8Rand block with counter ctr: eight rounds',
          'def block(+k: Key, +ctr: U32) -> Vector:',
          '  finish(k,dr(dr(dr(dr(init(k,ctr))))))',
          '',
          '# four blocks interleaved word by word, as 32 little-endian 64-bit words',
          'def interleave(a: Vector, b: Vector, c: Vector, d: Vector) -> List<&2,W.U64>:',
          '  match a b c d:',
          '    case V{%s} V{%s} V{%s} V{%s}:' % (ws('a', 16), ws('b', 16), ws('c', 16), ws('d', 16)),
          '      [%s]' % ','.join('W.U64{a%d,b%d},W.U64{c%d,d%d}' % (w, w, w, w) for w in range(16)),
          '',
          '# the group of the blocks ctr, ctr + 1, ctr + 2, ctr + 3',
          'def group(+k: Key, +ctr: U32) -> List<&2,W.U64>:',
          '  interleave(block(k,ctr),block(k,U32.add(ctr,1)),block(k,U32.add(ctr,2)),block(k,U32.add(ctr,3)))',
          '']
    write(os.path.join(SRC, 'block.bend'), '\n'.join(L))


def main():
    gen_block()


if __name__ == '__main__':
    main()
