#!/usr/bin/env python3
"""Generate the doubly linked list's shadow, abstraction and invariant
(proofs/doubly_linked_list/state.bend).

The invariant is a conjunction of Bool components over the shadow's fields;
the generator writes each component, the conjunction goodF, one accessor
g_<c> per component, and good_intro, which builds goodF from the components.
"""
import pathlib

ROOT = pathlib.Path(__file__).resolve().parents[2]
STATE = ROOT / "proofs/doubly_linked_list/state.bend"

P = ("+tag: U32, +cap: U32, +fresh: U32, +free: U32, +head: U32, +tail: U32, +depth: Nat, "
     "+vT: AR.Tree<Maybe<&2, T>>, +pT: AR.Tree<U32>, +nT: AR.Tree<U32>, +gT: AR.Tree<U32>, "
     "+sl: List<&2, Nat>, +fl: List<&2, Nat>")
A = "tag, cap, fresh, free, head, tail, depth, vT, pT, nT, gT, sl, fl"
VL = "AR.slots(Maybe<&2, T>, vT)"
PL = "AR.slots(U32, pT)"
NL = "AR.slots(U32, nT)"
FR = "UD.v(fresh)"

COMPS = [
    ("cdep", "Nat.is_lt(depth, 30n)"),
    ("ccap", "Nat.is_eq(UD.v(cap), SC.pow2(depth))"),
    ("cpv", "AR.perfect(Maybe<&2, T>, depth, vT)"),
    ("cpp", "AR.perfect(U32, depth, pT)"),
    ("cpn", "AR.perfect(U32, depth, nT)"),
    ("cpg", "AR.perfect(U32, depth, gT)"),
    ("cfr", f"Nat.is_le({FR}, UD.v(cap))"),
    ("cseg", f"seg({PL}, {NL}, sl, 0, 0)"),
    ("chead", "U32.is_eq(head, LK.fst_or(sl, 0))"),
    ("ctail", "U32.is_eq(tail, LK.last_or(sl, 0))"),
    ("cnd", "NL.nodupn(sl)"),
    ("csl", f"slok(~T, sl, {FR}, {VL})"),
    ("cfree", "U32.is_eq(free, LK.fst_or(fl, 0))"),
    ("cfll", f"fll({NL}, fl)"),
    ("cfl", f"flok(~T, fl, {FR}, {VL})"),
    ("cfnd", "NL.nodupn(fl)"),
    ("cgz", f"gz(AR.slots(U32, gT), {FR})"),
    ("clv", f"lvin(~T, {VL}, 0n, sl)"),
]
NAMES = [c for c, _ in COMPS]

BASE = '''import Base
import ../lib/logic.bend as L
import ../lib/nat.bend as N
import ../lib/array.bend as AR
import ../spec/common.bend as SC
import ../spec/doubly_linked_list.bend as S
import ../math/u32div.bend as UD
import ../../src/containers/doubly_linked_list.bend as D
import ../../src/containers/internal/dlist_storage.bend as R
import ../../src/containers/types/doubly_linked_list.bend as E
import ../lib/nat_list.bend as NL
import ../lib/links.bend as LK
import ../lib/words32.bend as W32

# The doubly linked list's shadow: the public list's fields, one mirror tree
# per array (values, prev links, next links, generations), the ids of the
# list in order and the free stack (both ghost). The storage's count is the
# order's length, and its depth and capacity are the public ones.
# (generated by tools/generators/dll_state.py)

type Sh<-T: Data> is Data:
  LS{tag: U32, cap: U32, fresh: U32, free: U32, head: U32, tail: U32, depth: Nat, vT: AR.Tree<Maybe<&2, T>>, pT: AR.Tree<U32>, nT: AR.Tree<U32>, gT: AR.Tree<U32>, sl: List<&2, Nat>, fl: List<&2, Nat>}

def real(~T: Data, sh: Sh<T>) -> D.DList<T>:
  match sh:
    case LS{+tag, +cap, +fresh, +free, +head, +tail, +depth, +vT, +pT, +nT, +gT, +sl, +fl}:
      D.DL{tag, depth, cap, R.DL{tag, fresh, free, SC.length(Nat, sl), head, tail, depth, cap, AR.thaw(Maybe<&2, T>, vT), AR.thaw(U32, pT), AR.thaw(U32, nT)}, AR.thaw(U32, gT)}

def model(~T: Data, sh: Sh<T>) -> S.DS<T>:
  match sh:
    case LS{+tag, +cap, +fresh, +free, +head, +tail, +depth, +vT, +pT, +nT, +gT, +sl, +fl}:
      S.DS{tag, sl, SC.take(Maybe<&2, T>, AR.slots(Maybe<&2, T>, vT), UD.v(fresh)), SC.take(U32, AR.slots(U32, gT), UD.v(fresh)), fl}

# ---- links (lnk, fst_or, last_or, nodupn: the LRU's, proofs/lru/state.bend) ----

# the segment sl: its first id's prev is p, its last id's next is q, and
# consecutive ids are linked both ways
def seg(+pl: List<&2, U32>, +nl: List<&2, U32>, sl: List<&2, Nat>, +p: U32, +q: U32) -> Bool:
  match sl:
    case Nil{}:
      True{}
    case Con{+s, +t}:
      Bool.and(U32.is_eq(W32.nth0(pl, s), p), Bool.and(U32.is_eq(W32.nth0(nl, s), LK.fst_or(t, q)), seg(pl, nl, t, LK.lnk(s), q)))

# the free stack: each id's next is the id after it (0 for the last)
def fll(+nl: List<&2, U32>, fl: List<&2, Nat>) -> Bool:
  match fl:
    case Nil{}:
      True{}
    case Con{+s, +t}:
      Bool.and(U32.is_eq(W32.nth0(nl, s), LK.fst_or(t, 0)), fll(nl, t))

def some_b(-T: Data, m: Maybe<&2, T>) -> Bool:
  match m:
    case None{}:
      False{}
    case Some{v}:
      True{}

def live(-T: Data, +vl: List<&2, Maybe<&2, T>>, +x: Nat) -> Bool:
  some_b(T, S.val_of(T, vl, x))

# every id of xs is below fr and live
def slok(~T: Data, xs: List<&2, Nat>, +fr: Nat, +vl: List<&2, Maybe<&2, T>>) -> Bool:
  match xs:
    case Nil{}:
      True{}
    case Con{+x, t}:
      Bool.and(Bool.and(Nat.is_lt(x, fr), live(T, vl, x)), slok(~T, t, fr, vl))

# every id of xs is below fr and vacant
def flok(~T: Data, xs: List<&2, Nat>, +fr: Nat, +vl: List<&2, Maybe<&2, T>>) -> Bool:
  match xs:
    case Nil{}:
      True{}
    case Con{+x, t}:
      Bool.and(Bool.and(Nat.is_lt(x, fr), Bool.not(live(T, vl, x))), flok(~T, t, fr, vl))

# every generation from index fr on is 0 (the ids not issued yet)
def gz(gl: List<&2, U32>, +fr: Nat) -> Bool:
  match gl fr:
    case Nil{} _:
      True{}
    case Con{+g, +t} 0n:
      Bool.and(U32.is_eq(g, 0), gz(t, 0n))
    case Con{+g, +t} 1n+p:
      gz(t, p)

# every live value slot (index k on) is an id of sl
def lvin(~T: Data, vl: List<&2, Maybe<&2, T>>, +k: Nat, +sl: List<&2, Nat>) -> Bool:
  match vl:
    case Nil{}:
      True{}
    case Con{m, t}:
      Bool.and(Bool.or(Bool.not(some_b(T, m)), NL.memn(k, sl)), lvin(~T, t, 1n+k, sl))

# ---- the invariant ----
'''


def call(c, pre="", args=A):
    return f"{pre}{c}(~T, {args})"


def rest(i, pre="", args=A):
    if i == len(NAMES) - 1:
        return call(NAMES[i], pre, args)
    return f"Bool.and({call(NAMES[i], pre, args)}, {rest(i + 1, pre, args)})"


def T_(x):
    return "{" + x + " == True{} : Bool}"


def intro(i, hs):
    if i == len(NAMES) - 1:
        return hs[i]
    return f"L.and_intro({call(NAMES[i])}, {rest(i + 1)}, {hs[i]}, {intro(i + 1, hs)})"


def block():
    out = [BASE]
    for c, body in COMPS:
        out.append(f"def {c}(~T: Data, {P}) -> Bool:\n  {body}\n")
    out.append(f"def goodF(~T: Data, {P}) -> Bool:\n  {rest(0)}\n")
    out.append('''def good(~T: Data, sh: Sh<T>) -> Bool:
  match sh:
    case LS{+tag, +cap, +fresh, +free, +head, +tail, +depth, +vT, +pT, +nT, +gT, +sl, +fl}:
      goodF(~T, tag, cap, fresh, free, head, tail, depth, vT, pT, nT, gT, sl, fl)
''')
    prs = ["g"]
    for i in range(len(NAMES) - 1):
        prs.append(f"L.and_right({call(NAMES[i])}, {rest(i + 1)}, {prs[i]})")
    for i, c in enumerate(NAMES):
        body = f"L.and_left({call(c)}, {rest(i + 1)}, {prs[i]})" if i < len(NAMES) - 1 else prs[i]
        out.append(f"def g_{c}(~T: Data, {P}, +g: {T_(call('goodF'))}) -> {T_(call(c))}:\n  {body}\n")
    hs = ", ".join(f"+h_{c}: {T_(call(c))}" for c in NAMES)
    out.append("# the invariant from its components\n"
               f"def good_intro(~T: Data, {P}, {hs}) -> {T_(call('goodF'))}:\n  {intro(0, ['h_' + c for c in NAMES])}\n")
    return "\n".join(out)


def main():
    STATE.write_text(block())


if __name__ == "__main__":
    main()
