#!/usr/bin/env python3
"""Generate the hash map invariant (proofs/containers/hash_table/state.bend, between the
free-list comment and the slot-value section) and its rebuild lemmas
(proofs/containers/hash_table/rebuild.bend).

The invariant is a conjunction of Bool components over the shadow's fields;
the generator writes each component, the conjunction goodF, one accessor
g_<c> per component, and good_intro, which builds goodF from the components.
"""
import pathlib
import sys
sys.path.insert(0, str(pathlib.Path(__file__).resolve().parent))
from conj import Conj

ROOT = pathlib.Path(__file__).resolve().parents[2]
STATE = ROOT / "proofs/containers/hash_table/state.bend"
REBUILD = ROOT / "proofs/containers/hash_table/rebuild.bend"

P = ("+n: U32, +k: Nat, +td: U32, +fresh: U32, +sz: U32, +sd: Nat, +sdU: U32, +free: U32, "
     "+tabT: AR.Tree<U32>, +kl: List<&2, String>, +pk: Bool, +vsT: AR.Tree<Maybe<&2, V>>, +nxT: AR.Tree<U32>")
A = "n, k, td, fresh, sz, sd, sdU, free, tabT, kl, pk, vsT, nxT"
BS = "TB.buckets(AR.slots(U32, tabT), kl, SC.pow2(k))"

FREE_LIST = '''# the free list from link f has exactly cnt links: each slot on it is below
# fresh, used by no bucket and not repeated, and the list ends after them
def fl_ok(+bs: List<&2, B.Bk>, +nb: Nat, +nxl: List<&2, U32>, +cnt: Nat, +f: U32, +fr: Nat, +seen: List<&2, Nat>) -> Bool:
  match cnt:
    case 0n:
      U32.is_eq(f, 0)
    case 1n+p:
      Bool.and(Bool.not(U32.is_eq(f, 0)), Bool.and(Bool.and(Nat.is_lt(UD.v(H.slot(f)), fr), Bool.and(noslot(bs, UD.v(H.slot(f)), nb), Bool.not(NL.memn(UD.v(H.slot(f)), seen)))), fl_ok(bs, nb, nxl, p, W32.nth0(nxl, UD.v(H.slot(f))), fr, Con{UD.v(H.slot(f)), seen})))
'''

COMPS = [
    ("ck", "Bool.and(Nat.is_lt(k, 31n), Nat.is_lt(0n, k))"),
    ("csd", "Nat.is_lt(sd, 32n)"),
    ("cpt", "AR.perfect(U32, 1n+k, tabT)"),
    ("cpk", "pk"),
    ("cpv", "AR.perfect(Maybe<&2, V>, sd, vsT)"),
    ("cpn", "AR.perfect(U32, sd, nxT)"),
    ("ctd", "Nat.is_eq(UD.v(td), 1n+k)"),
    ("csz", "Nat.is_eq(UD.v(sz), SC.pow2(sd))"),
    ("csdu", "Nat.is_eq(UD.v(sdU), sd)"),
    ("cwell", f"B.all_lt(B.PWell{{{BS}, sd}}, SC.pow2(k))"),
    ("cclus", f"B.cluster({BS}, SC.pow2(k), CY.msk(k))"),
    ("cuniq", f"B.all_lt(B.PUniq{{{BS}}}, SC.pow2(k))"),
    ("cn", f"Nat.is_eq(UD.v(n), IV.occn({BS}, SC.pow2(k)))"),
    ("cload", "Nat.is_le(Nat.double(UD.v(n)), SC.pow2(k))"),
    ("clive", f"B.all_lt(B.PLive{{{BS}, lvs(~V, AR.slots(Maybe<&2, V>, vsT)), UD.v(fresh)}}, SC.pow2(k))"),
    ("cfresh", "Nat.is_le(UD.v(fresh), UD.v(sz))"),
    ("cfree", f"Bool.and(Nat.is_le(UD.v(n), UD.v(fresh)), fl_ok({BS}, SC.pow2(k), AR.slots(U32, nxT), Nat.sub(UD.v(fresh), UD.v(n)), free, UD.v(fresh), Nil{{}}))"),
    ("csdk", "Nat.is_lt(sd, k)"),
]
NAMES = [c for c, _ in COMPS]


def call(c, pre="", args=A):
    return f"{pre}{c}(~V, {args})"




def T(x):
    return "{" + x + " == True{} : Bool}"


C = Conj(NAMES, lambda c, pre="", args=None: call(c, pre, A if args is None else args), f"~V: Data, {P}")


def state_block():
    out = [FREE_LIST]
    for c, body in COMPS:
        out.append(f"def {c}(~V: Data, {P}) -> Bool:\n  {body}\n")
    out += C.suffixes()
    out.append('''def good(~V: Data, sh: Sh<V>) -> Bool:
  match sh:
    case HS{+n, +k, +td, +fresh, +sz, +sd, +sdU, +free, +tabT, +ksT, +vsT, +nxT}:
      goodF(~V, n, k, td, fresh, sz, sd, sdU, free, tabT, AR.slots(String, ksT), AR.perfect(String, sd, ksT), vsT, nxT)
''')
    out += C.projections(A)
    hs = ", ".join(f"+h_{c}: {T(call(c))}" for c in NAMES)
    out.append("# the invariant from its components\n"
               f"def good_intro(~V: Data, {P}, {hs}) -> {T(call('goodF'))}:\n  {C.intro()}\n")
    return "\n".join(out)


def rebuild():
    a2 = A.replace("vsT, nxT", "vsT2, nxT")
    hs = []
    for c in NAMES:
        if c in ("cpv", "clive"):
            hs.append(f"h_{c}")
        else:
            hs.append(f"ST.g_{c}(~V, {A}, hg)")
    return f'''import Base
import ../../lib/logic.bend as L
import ../../lib/array.bend as AR
import ./state.bend as ST
import ../../lib/nat_list.bend as NL

# Rebuilding the invariant when an operation changes some of its components.
# (generated by tools/generators/hash_table_state.py)

def good_vs(~V: Data, {P}, +hg: {T(call('goodF', 'ST.'))}, +vsT2: AR.Tree<Maybe<&2, V>>, +h_cpv: {T(call('cpv', 'ST.', a2))}, +h_clive: {T(call('clive', 'ST.', a2))}) -> {T(call('goodF', 'ST.', a2))}:
  ST.good_intro(~V, {a2}, {", ".join(hs)})
'''


def main():
    text = STATE.read_text()
    start = text.index("# the free list from link f")
    end = text.index("# ---- slot values ----")
    STATE.write_text(text[:start] + state_block() + "\n" + text[end:])
    REBUILD.write_text(rebuild())


if __name__ == "__main__":
    main()
