#!/usr/bin/env python3
"""Emit tests/crypto/poly1305/main.bend: the RFC 8439 Poly1305 vectors
(section 2.5.2 and all eleven Appendix A.3 vectors, transcribed from the RFC
text) run through src/crypto/poly1305/poly1305.bend.

  python3 tools/generators/poly1305_tests.py

The driver prints one FAIL line per mismatch and a final "poly1305: k / n
passed" line.
"""
import os

ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), '..', '..'))
OUT = os.path.join(ROOT, 'tests/crypto/poly1305/main.bend')

VECTORS = [
    ('rfc8439 2.5.2',
     '85d6be7857556d337f4452fe42d506a80103808afb0db2fd4abff6af4149f51b',
     '43727970746f6772617068696320466f72756d2052657365617263682047726f7570',
     'a8061dc1305136c6c22b8baf0c0127a9'),
    ('rfc8439 A.3 #1',
     '0000000000000000000000000000000000000000000000000000000000000000',
     '00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000',
     '00000000000000000000000000000000'),
    ('rfc8439 A.3 #2',
     '0000000000000000000000000000000036e5f6b5c5e06070f0efca96227a863e',
     '416e79207375626d697373696f6e20746f20746865204945544620696e74656e6465642062792074686520436f6e7472696275746f7220666f72207075626c69636174696f6e20617320616c6c206f722070617274206f6620616e204945544620496e7465726e65742d4472616674206f722052464320616e6420616e792073746174656d656e74206d6164652077697468696e2074686520636f6e74657874206f6620616e204945544620616374697669747920697320636f6e7369646572656420616e20224945544620436f6e747269627574696f6e222e20537563682073746174656d656e747320696e636c756465206f72616c2073746174656d656e747320696e20494554462073657373696f6e732c2061732077656c6c206173207772697474656e20616e6420656c656374726f6e696320636f6d6d756e69636174696f6e73206d61646520617420616e792074696d65206f7220706c6163652c207768696368206172652061646472657373656420746f',
     '36e5f6b5c5e06070f0efca96227a863e'),
    ('rfc8439 A.3 #3',
     '36e5f6b5c5e06070f0efca96227a863e00000000000000000000000000000000',
     '416e79207375626d697373696f6e20746f20746865204945544620696e74656e6465642062792074686520436f6e7472696275746f7220666f72207075626c69636174696f6e20617320616c6c206f722070617274206f6620616e204945544620496e7465726e65742d4472616674206f722052464320616e6420616e792073746174656d656e74206d6164652077697468696e2074686520636f6e74657874206f6620616e204945544620616374697669747920697320636f6e7369646572656420616e20224945544620436f6e747269627574696f6e222e20537563682073746174656d656e747320696e636c756465206f72616c2073746174656d656e747320696e20494554462073657373696f6e732c2061732077656c6c206173207772697474656e20616e6420656c656374726f6e696320636f6d6d756e69636174696f6e73206d61646520617420616e792074696d65206f7220706c6163652c207768696368206172652061646472657373656420746f',
     'f3477e7cd95417af89a6b8794c310cf0'),
    ('rfc8439 A.3 #4',
     '1c9240a5eb55d38af333888604f6b5f0473917c1402b80099dca5cbc207075c0',
     '2754776173206272696c6c69672c20616e642074686520736c6974687920746f7665730a446964206779726520616e642067696d626c6520696e2074686520776162653a0a416c6c206d696d737920776572652074686520626f726f676f7665732c0a416e6420746865206d6f6d65207261746873206f757467726162652e',
     '4541669a7eaaee61e708dc7cbcc5eb62'),
    ('rfc8439 A.3 #5',
     '0200000000000000000000000000000000000000000000000000000000000000',
     'ffffffffffffffffffffffffffffffff',
     '03000000000000000000000000000000'),
    ('rfc8439 A.3 #6',
     '02000000000000000000000000000000ffffffffffffffffffffffffffffffff',
     '02000000000000000000000000000000',
     '03000000000000000000000000000000'),
    ('rfc8439 A.3 #7',
     '0100000000000000000000000000000000000000000000000000000000000000',
     'fffffffffffffffffffffffffffffffff0ffffffffffffffffffffffffffffff11000000000000000000000000000000',
     '05000000000000000000000000000000'),
    ('rfc8439 A.3 #8',
     '0100000000000000000000000000000000000000000000000000000000000000',
     'fffffffffffffffffffffffffffffffffbfefefefefefefefefefefefefefefe01010101010101010101010101010101',
     '00000000000000000000000000000000'),
    ('rfc8439 A.3 #9',
     '0200000000000000000000000000000000000000000000000000000000000000',
     'fdffffffffffffffffffffffffffffff',
     'faffffffffffffffffffffffffffffff'),
    ('rfc8439 A.3 #10',
     '0100000000000000040000000000000000000000000000000000000000000000',
     'e33594d7505e43b900000000000000003394d7505e4379cd01000000000000000000000000000000000000000000000001000000000000000000000000000000',
     '14000000000000005500000000000000'),
    ('rfc8439 A.3 #11',
     '0100000000000000040000000000000000000000000000000000000000000000',
     'e33594d7505e43b900000000000000003394d7505e4379cd010000000000000000000000000000000000000000000000',
     '13000000000000000000000000000000'),
]

HEAD = '''# Generated by tools/generators/poly1305_tests.py; do not edit.
# RFC 8439 Poly1305 vectors (2.5.2 and Appendix A.3 #1-#11).
import Base
import ../../../src/crypto/poly1305/poly1305.bend as P

def digit_if(small: Bool, x: U32) -> Char:
  match small:
    case True{}: Chr{U32.add(48, x)}
    case False{}: Chr{U32.add(87, x)}

def hex_digit(+x: U32) -> Char:
  digit_if(U32.is_lt(x, 10), x)

def hex(bs: List<&2, U32>) -> String:
  match bs:
    case Nil{}: ""
    case +b <> t: SCon{hex_digit(U32.shrn(b, 4n)), SCon{hex_digit(U32.and(b, 15)), hex(t)}}

def show(r: Maybe<&2, List<&2, U32>>) -> String:
  match r:
    case None{}: "none"
    case Some{x}: hex(x)

def bit(b: Bool) -> String:
  match b:
    case True{}: "true"
    case False{}: "false"

def verdict(ok: Bool, label: String, got: String, want: String, n: Nat) -> IO(Nat):
  match ok:
    case True{}: IO.pure(Nat, 1n+n)
    case False{}:
      do IO<Nat>:
        IO.print("FAIL " ++ label ++ ": got " ++ got ++ " want " ++ want)
        return n

def check(label: String, +got: String, +want: String, n: Nat) -> IO(Nat):
  verdict(String.eq(got, want), label, got, want, n)

def main() -> IO(Unit):
  do IO<Unit>:
    n0 : Nat <- IO.pure(Nat, 0n)
'''


def blist(h):
    return '[' + ', '.join(str(int(h[i:i + 2], 16)) for i in range(0, len(h), 2)) + ']'


def main():
    body = []
    i = 0
    cases = []
    for name, k, m, t in VECTORS:
        cases.append((name + ' mac', 'hex(P.mac(%s, %s))' % (blist(k), blist(m)), t))
        cases.append((name + ' poly1305', 'show(P.poly1305(%s, %s))' % (blist(k), blist(m)), t))
        cases.append((name + ' verify', 'bit(P.verify(%s, %s, %s))' % (blist(k), blist(m), blist(t)), 'true'))
        bad = t[:-2] + '%02x' % (int(t[-2:], 16) ^ 1)
        cases.append((name + ' verify bad tag', 'bit(P.verify(%s, %s, %s))' % (blist(k), blist(m), blist(bad)), 'false'))
    k0 = VECTORS[0][1]
    cases.append(('short key', 'show(P.poly1305(%s, [1, 2, 3]))' % blist(k0[:62]), 'none'))
    cases.append(('long key', 'show(P.poly1305(%s, [1, 2, 3]))' % blist(k0 + '00'), 'none'))
    cases.append(('verify short key', 'bit(P.verify(%s, [], %s))' % (blist(k0[:62]), blist(VECTORS[0][3])), 'false'))
    for j, (label, expr, want) in enumerate(cases):
        body.append('    n%d : Nat <- check("%s", %s, "%s", n%d)' % (j + 1, label, expr, want, j))
    body.append('    IO.print("poly1305: " ++ Nat.show(n%d) ++ " / %d passed")' % (len(cases), len(cases)))
    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    with open(OUT, 'w') as f:
        f.write(HEAD + '\n'.join(body) + '\n')


if __name__ == '__main__':
    main()
