#!/usr/bin/env python3
"""Write tools/generators/secp256k1_hand/pwin.src: the proofs of the 4-bit
fixed-window scalar multiplication of src/crypto/secp256k1/pt.bend (tab,
tsel, wgo, wmul) from the group law (proofs/crypto/secp256k1/group/).

  python3 tools/generators/secp256k1_win.py
  python3 tools/generators/rw.py tools/generators/secp256k1_hand/pwin.src proofs/crypto/secp256k1/pwin.bend

The statement: for a point a of the group and bits of a multiple of 4 bits,
wmul(bits, a) is a point of the group, equivalent (the same projective
point) to [v] a, v the number the bits spell. The facts hp (p is prime) and
hc (-7 is no cube) of the group law are hypotheses, discharged by the
closing roots.
"""
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
P = 'FS.prime(one)'
HYP0 = '+one: Nat, +h1: {one == 1n : Nat}'
HYP = '+one: Nat, +h1: {one == 1n : Nat}, +hp: NP.Prime(FS.prime(one)), +hc: {Nat.is_eq(FS.mpow(FS.prime(one), Nat.sub(FS.prime(one), 7n), Nat.div(Nat.sub(FS.prime(one), 1n), 3n)), 1n) == False{} : Bool}'
ARG = 'one, h1, hp, hc'


def eq(a, b):
    return '{GS.equiv(%s, %s, %s) == True{} : Bool}' % (P, a, b)


def vd(a):
    return '{GS.valid(%s, %s) == True{} : Bool}' % (P, a)


def pd(a):
    return '{PP.pred(one, %s) == True{} : Bool}' % a


def pdbl(x, n=1):
    for _ in range(n):
        x = 'CV.pdbl(%s, %s)' % (P, x)
    return x


def xdbl(x, n=1):
    for _ in range(n):
        x = 'PX.dbl(%s)' % x
    return x


def ndbl(x, n=1):
    for _ in range(n):
        x = 'Nat.double(%s)' % x
    return x


def padd(a, b):
    return 'CV.padd(%s, %s, %s)' % (P, a, b)


def smul(k, a):
    return 'GS.smul(%s, %s, %s)' % (P, k, a)


def tree(leaf, node, bits=('b4', 'b3', 'b2', 'b1')):
    cur = [leaf(i) for i in range(16)]
    for b in bits:
        cur = [node(b, cur[2 * j + 1], cur[2 * j]) for j in range(len(cur) // 2)]
    return cur[0]


o = []
a = o.append
a('''import Base
import ../../../spec/lib/common.bend as C
import ../../../spec/crypto/secp256k1/field.bend as FS
import ../../../spec/crypto/secp256k1/curve.bend as CV
import ../../../spec/crypto/secp256k1/group.bend as GS
import ../../../src/crypto/secp256k1/pt.bend as PX
import ../../lib/logic.bend as Lg
import ./lite/lib/nat.bend as N
import ./lite/lib/lemmas/proofs/nat_algebra.bend as NA
import ./lite/math/number/nt_prime.bend as NP
import ./lite/crypto/secp256k1/group/glawp.bend as GP
import ./lite/crypto/secp256k1/group/glaw4.bend as G4
import ./bitsv.bend as BV
import ./ptp.bend as PP
import ./ptm.bend as PM

# GENERATED by tools/generators/secp256k1_win.py; edit the generator.
#
# The 4-bit fixed-window multiplication of src/crypto/secp256k1/pt.bend
# (tab, tsel, wgo, wmul) on the group of spec/crypto/secp256k1/group.bend:
# for a point a of the group, wmul(bits, a) is a point of the group and the
# same projective point as [v] a, v the number the bits spell (G4.bvl). hp
# (p is prime) and hc (-7 is no cube modulo p) are the hypotheses of the
# group law, discharged by the closing roots.

# ---- on the specification's points ----
''')

a('''def dbl_vd(%(H)s, +r: CV.SPoint, +vr: %(vr)s) -> %(vdr)s:
  %%rw GP.group_double(%(A)s, r, vr)
  GP.group_closed(%(A)s, r, r, vr, vr)

# R is [v] A: 2 R is [2 v] A
def dbl_e(%(H)s, +a: CV.SPoint, +r: CV.SPoint, +v: Nat, +va: %(va)s, +vr: %(vr)s, +hr: %(hr)s) -> %(concl)s:
  +s = %(s)s
  +vs = GP.scalar_closed(%(A)s, v, a, va)
  %%rw GP.group_double(%(A)s, r, vr)
  %%rw NA.double_self(v)
  GP.equiv_trans(%(A)s, %(rr)s, %(ss)s, %(svv)s, GP.group_closed(%(A)s, s, s, vs, vs), GP.equiv_trans(%(A)s, %(rr)s, %(sr)s, %(ss)s, GP.group_closed(%(A)s, s, r, vs, vr), GP.equiv_add_left(%(A)s, r, s, r, vr, vs, hr), GP.equiv_add_right(%(A)s, s, r, s, vr, vs, hr)), GP.equiv_sym(%(A)s, %(svv)s, %(ss)s, GP.scalar_add(%(A)s, v, v, a, va)))
''' % dict(H=HYP, A=ARG, vr=vd('r'), vdr=vd(pdbl('r')), va=vd('a'), hr=eq('r', smul('v', 'a')),
           concl=eq(pdbl('r'), smul('Nat.double(v)', 'a')), s=smul('v', 'a'), rr=padd('r', 'r'), ss=padd('s', 's'),
           sr=padd('s', 'r'), svv=smul('Nat.add(v, v)', 'a')))

a('''def dbl4_vd(%(H)s, +r: CV.SPoint, +vr: %(vr)s) -> %(vd4)s:
  dbl_vd(%(A)s, %(r3)s, dbl_vd(%(A)s, %(r2)s, dbl_vd(%(A)s, %(r1)s, dbl_vd(%(A)s, r, vr))))

# R is [v] A: 16 R is [16 v] A
def dbl4_e(%(H)s, +a: CV.SPoint, +r: CV.SPoint, +v: Nat, +va: %(va)s, +vr: %(vr)s, +hr: %(hr)s) -> %(concl)s:
  +v1 = dbl_vd(%(A)s, r, vr)
  +v2 = dbl_vd(%(A)s, %(r1)s, v1)
  +v3 = dbl_vd(%(A)s, %(r2)s, v2)
  +e1 = dbl_e(%(A)s, a, r, v, va, vr, hr)
  +e2 = dbl_e(%(A)s, a, %(r1)s, Nat.double(v), va, v1, e1)
  +e3 = dbl_e(%(A)s, a, %(r2)s, %(n2)s, va, v2, e2)
  dbl_e(%(A)s, a, %(r3)s, %(n3)s, va, v3, e3)

def comm_e(%(H)s, +a: CV.SPoint, +d: Nat, +k: Nat, +va: %(va)s) -> %(ce)s:
  %%rw GP.group_commutative(%(A)s, %(sk)s, %(sd)s)
  GP.equiv_sym(%(A)s, %(sdk)s, %(pdk)s, GP.scalar_add(%(A)s, d, k, a, va))

# R is [v] A: 16 R + [d] A is [d + 16 v] A
def wstep_e(%(H)s, +a: CV.SPoint, +r: CV.SPoint, +v: Nat, +d: Nat, +va: %(va)s, +vr: %(vr)s, +hr: %(hr)s) -> %(we)s:
  +r4 = %(r4)s
  +k = %(n4)s
  +sd = %(sd)s
  +sk = %(sk)s
  +v4 = dbl4_vd(%(A)s, r, vr)
  +vsd = GP.scalar_closed(%(A)s, d, a, va)
  +vsk = GP.scalar_closed(%(A)s, k, a, va)
  GP.equiv_trans(%(A)s, %(p1)s, %(p2)s, %(sdk)s, GP.group_closed(%(A)s, sk, sd, vsk, vsd), GP.equiv_add_left(%(A)s, r4, sk, sd, v4, vsk, dbl4_e(%(A)s, a, r, v, va, vr, hr)), comm_e(%(A)s, a, d, k, va))

def wstep_vd(%(H)s, +a: CV.SPoint, +r: CV.SPoint, +d: Nat, +va: %(va)s, +vr: %(vr)s) -> %(wv)s:
  GP.group_closed(%(A)s, %(r4)s, %(sd)s, dbl4_vd(%(A)s, r, vr), GP.scalar_closed(%(A)s, d, a, va))
''' % dict(H=HYP, A=ARG, vr=vd('r'), va=vd('a'), hr=eq('r', smul('v', 'a')), vd4=vd(pdbl('r', 4)),
           r1=pdbl('r', 1), r2=pdbl('r', 2), r3=pdbl('r', 3), r4=pdbl('r', 4), n2=ndbl('v', 2), n3=ndbl('v', 3), n4=ndbl('v', 4),
           concl=eq(pdbl('r', 4), smul(ndbl('v', 4), 'a')),
           ce=eq(padd(smul('k', 'a'), smul('d', 'a')), smul('Nat.add(d, k)', 'a')), sk=smul('k', 'a'), sd=smul('d', 'a'),
           sdk=smul('Nat.add(d, k)', 'a'), pdk=padd(smul('d', 'a'), smul('k', 'a')),
           we=eq(padd(pdbl('r', 4), smul('d', 'a')), smul('Nat.add(d, %s)' % ndbl('v', 4), 'a')),
           p1=padd('r4', 'sd'), p2=padd('sk', 'sd'), wv=vd(padd(pdbl('r', 4), smul('d', 'a')))))

# ---- the table ----
T = lambda i: 'tabp(%dn, a)' % i
a('''# ---- the table: entry i is i additions of a, [i] a exactly ----

def tabp(i: Nat, +a: PX.PT) -> PX.PT:
  match i:
    case 0n: PX.infinity()
    case 1n+j: PX.add(tabp(j, a), a)

def tabp_r(+one: Nat, +h1: {one == 1n : Nat}, i: Nat, +a: PX.PT, +ha: %(pa)s) -> %(pt)s:
  match i:
    case 0n:
      PM.pinf_r(one, h1)
    case 1n+ +j:
      PP.padd_r(one, h1, tabp(j, a), a, tabp_r(one, h1, j, a, ha), ha)

def tabp_v(+one: Nat, +h1: {one == 1n : Nat}, i: Nat, +a: PX.PT, +ha: %(pa)s) -> {PP.pv(one, tabp(i, a)) == %(sm)s : CV.SPoint}:
  match i:
    case 0n:
      PM.pinf_v(one, h1)
    case 1n+ +j:
      %%goal {PP.pv(one, PX.add(tabp(j, a), a)) == %(step)s : CV.SPoint}
      %%rw PP.padd_v(one, h1, tabp(j, a), a, tabp_r(one, h1, j, a, ha), ha)
      %%rw tabp_v(one, h1, j, a, ha)
      %%close

def tabp_vd(%(H)s, +i: Nat, +a: PX.PT, +ha: %(pa)s, +va: %(vpa)s) -> %(vt)s:
  %%rw tabp_v(one, h1, i, a, ha)
  GP.scalar_closed(%(A)s, i, PP.pv(one, a), va)

# ---- the selection: a tree of picks ----

def pick(b: Nat, +x: PX.PT, +y: PX.PT) -> PX.PT:
  match b:
    case 0n: y
    case 1n+k: x

def sel_pick(+one: Nat, +h1: {one == 1n : Nat}, b: Nat, +x: PX.PT, +y: PX.PT, +hb: {Nat.is_lt(b, 2n) == True{} : Bool}, +hx: %(px)s, +hy: %(py)s) -> {PX.select(b, x, y) == pick(b, x, y) : PX.PT}:
  match b:
    case 0n:
      PM.psel0(one, h1, x, y, hx, hy)
    case 1n:
      PM.psel1(one, h1, x, y, hx, hy)
    case 2n+ +k:
      Empty.absurd({PX.select(2n+k, x, y) == pick(2n+k, x, y) : PX.PT}, N.lt_zero_absurd(k, hb))

def pick_r(+one: Nat, b: Nat, +x: PX.PT, +y: PX.PT, +hx: %(px)s, +hy: %(py)s) -> %(ppick)s:
  match b:
    case 0n:
      hy
    case 1n+k:
      hx

def pick_vd(+one: Nat, b: Nat, +x: PX.PT, +y: PX.PT, +hx: %(vx)s, +hy: %(vy)s) -> %(vpick)s:
  match b:
    case 0n:
      hy
    case 1n+k:
      hx
''' % dict(H=HYP, A=ARG, pa=pd('a'), pt=pd('tabp(i, a)'), sm=smul('i', 'PP.pv(one, a)'),
           step=padd(smul('j', 'PP.pv(one, a)'), 'PP.pv(one, a)'), vpa=vd('PP.pv(one, a)'), vt=vd('PP.pv(one, tabp(i, a))'),
           px=pd('x'), py=pd('y'), ppick=pd('pick(b, x, y)'), vx=vd('PP.pv(one, x)'), vy=vd('PP.pv(one, y)'),
           vpick=vd('PP.pv(one, pick(b, x, y))')))

pk = lambda b, x, y: 'pick(%s, %s, %s)' % (b, x, y)
sl = lambda b, x, y: 'PX.select(%s, %s, %s)' % (b, x, y)
a('def tpk(+b1: Nat, +b2: Nat, +b3: Nat, +b4: Nat, +a: PX.PT) -> PX.PT:\n  %s\n' % tree(T, pk))

# pred and valid of the pick tree, and tsel(tab) == tpk
tr = lambda i: 'tabp_r(one, h1, %dn, a, ha)' % i
tv = lambda i: 'tabp_vd(%s, %dn, a, ha, va)' % (ARG, i)


def tree2(leaf, leafp, nodep, bits=('b4', 'b3', 'b2', 'b1')):
    """(term, proof) up the tree"""
    cur = [(leaf(i), leafp(i)) for i in range(16)]
    for b in bits:
        cur = [(pk(b, cur[2 * j + 1][0], cur[2 * j][0]), nodep(b, cur[2 * j + 1], cur[2 * j])) for j in range(len(cur) // 2)]
    return cur[0]


_, prf_r = tree2(T, tr, lambda b, x, y: 'pick_r(one, %s, %s, %s, %s, %s)' % (b, x[0], y[0], x[1], y[1]))
_, prf_v = tree2(T, tv, lambda b, x, y: 'pick_vd(one, %s, %s, %s, %s, %s)' % (b, x[0], y[0], x[1], y[1]))
BH = '+b1: Nat, +b2: Nat, +b3: Nat, +b4: Nat'
a('def tpk_r(+one: Nat, +h1: {one == 1n : Nat}, %s, +a: PX.PT, +ha: %s) -> %s:\n  %s\n' % (BH, pd('a'), pd('tpk(b1, b2, b3, b4, a)'), prf_r))
a('def tpk_vd(%s, %s, +a: PX.PT, +ha: %s, +va: %s) -> %s:\n  %s\n' % (HYP, BH, pd('a'), vd('PP.pv(one, a)'), vd('PP.pv(one, tpk(b1, b2, b3, b4, a))'), prf_v))

# tsel(tab(a)) == tpk: rewrite the selections level by level
HB = ', '.join('+hb%d: {Nat.is_lt(b%d, 2n) == True{} : Bool}' % (i, i) for i in (1, 2, 3, 4))
lines = ['def tsel_tab(+one: Nat, +h1: {one == 1n : Nat}, %s, %s, +a: PX.PT, +ha: %s) -> {PX.tsel(b1, b2, b3, b4, PX.tab(a)) == tpk(b1, b2, b3, b4, a) : PX.PT}:' % (BH, HB, pd('a'))]
lines.append('  %%goal {%s == %s : PX.PT}' % (tree(T, sl), tree(T, pk)))
cur = [(T(i), tr(i)) for i in range(16)]
for b in ('b4', 'b3', 'b2', 'b1'):
    nxt = []
    for j in range(len(cur) // 2):
        x, y = cur[2 * j + 1], cur[2 * j]
        lines.append('  %%rw sel_pick(one, h1, %s, %s, %s, h%s, %s, %s)' % (b, x[0], y[0], b, x[1], y[1]))
        nxt.append((pk(b, x[0], y[0]), 'pick_r(one, %s, %s, %s, %s, %s)' % (b, x[0], y[0], x[1], y[1])))
    cur = nxt
lines.append('  %close')
a('\n'.join(lines) + '\n')

# ---- one window ----
D4R = xdbl('r', 4)
a('''# ---- one window: 16 r + [k] a for the table entry k ----

def d4_r(+one: Nat, +h1: {one == 1n : Nat}, +r: PX.PT, +hr: %(pr)s) -> %(pd4)s:
  PP.pdbl_r(one, h1, %(x3)s, PP.pdbl_r(one, h1, %(x2)s, PP.pdbl_r(one, h1, %(x1)s, PP.pdbl_r(one, h1, r, hr))))

def d4_v(+one: Nat, +h1: {one == 1n : Nat}, +r: PX.PT, +hr: %(pr)s) -> {PP.pv(one, %(x4)s) == %(s4)s : CV.SPoint}:
  +q1 = PP.pdbl_r(one, h1, r, hr)
  +q2 = PP.pdbl_r(one, h1, %(x1)s, q1)
  +q3 = PP.pdbl_r(one, h1, %(x2)s, q2)
  %%rw PP.pdbl_v(one, h1, %(x3)s, q3)
  %%rw PP.pdbl_v(one, h1, %(x2)s, q2)
  %%rw PP.pdbl_v(one, h1, %(x1)s, q1)
  %%rw PP.pdbl_v(one, h1, r, hr)
  %%close

def wk_e(%(H)s, +a: PX.PT, +r: PX.PT, +v: Nat, +k: Nat, +ha: %(pa)s, +va: %(vpa)s, +hr: %(pr)s, +vr: %(vpr)s, +he: %(he)s) -> %(concl)s:
  %%rw PP.padd_v(one, h1, %(x4)s, tabp(k, a), d4_r(one, h1, r, hr), tabp_r(one, h1, k, a, ha))
  %%rw d4_v(one, h1, r, hr)
  %%rw tabp_v(one, h1, k, a, ha)
  wstep_e(%(A)s, PP.pv(one, a), PP.pv(one, r), v, k, va, vr, he)
''' % dict(H=HYP, A=ARG, pr=pd('r'), pd4=pd(D4R), x1=xdbl('r', 1), x2=xdbl('r', 2), x3=xdbl('r', 3), x4=D4R,
           s4=pdbl('PP.pv(one, r)', 4), pa=pd('a'), vpa=vd('PP.pv(one, a)'), vpr=vd('PP.pv(one, r)'),
           he=eq('PP.pv(one, r)', smul('v', 'PP.pv(one, a)')),
           concl=eq('PP.pv(one, PX.add(%s, tabp(k, a)))' % D4R, smul('Nat.add(k, %s)' % ndbl('v', 4), 'PP.pv(one, a)'))))

# the case tree over the four bits (deepest first)
CH = '+a: PX.PT, +r: PX.PT, +v: Nat, +ha: %s, +va: %s, +hr: %s, +vr: %s, +he: %s' % (pd('a'), vd('PP.pv(one, a)'), pd('r'), vd('PP.pv(one, r)'), eq('PP.pv(one, r)', smul('v', 'PP.pv(one, a)')))
CA = 'a, r, v, ha, va, hr, vr, he'


def nxt4(bs, v='v'):
    x = v
    for b in bs:
        x = 'G4.nxt(%s, %s)' % (b, x)
    return x


def lit(b):
    return '%dn' % b if isinstance(b, int) else b


for depth in (3, 2, 1, 0):
    for pre in range(1 << depth):
        pb = [(pre >> (depth - 1 - i)) & 1 for i in range(depth)]
        rest = ['b%d' % (i + 1) for i in range(depth, 4)]
        allb = pb + rest
        name = 'wt' + ''.join(map(str, pb))
        bparams = ', '.join('%s: Nat, +h%s: {Nat.is_lt(%s, 2n) == True{} : Bool}' % (b, b, b) for b in rest)
        ty = lambda bs: eq('PP.pv(one, PX.add(%s, tpk(%s, a)))' % (D4R, ', '.join(lit(b) for b in bs)), smul(nxt4([lit(b) for b in bs]), 'PP.pv(one, a)'))
        b0 = rest[0]
        ls = ['def %s(%s, %s, %s) -> %s:' % (name, HYP, CH, bparams, ty(allb)), '  match %s:' % b0]
        for val in (0, 1):
            child = pb + [val]
            cargs = ', '.join('%s, h%s' % (b, b) for b in rest[1:])
            if len(child) == 4:
                k = child[0] * 8 + child[1] * 4 + child[2] * 2 + child[3]
                call = 'wk_e(%s, a, r, v, %dn, ha, va, hr, vr, he)' % (ARG, k)
            else:
                call = 'wt%s(%s, %s%s)' % (''.join(map(str, child)), ARG, CA, ', ' + cargs if cargs else '')
            ls += ['    case %dn:' % val, '      ' + call]
        bad = [('2n+k' if b == b0 else b) for b in allb]
        ls += ['    case 2n+ +k:', '      Empty.absurd(%s, N.lt_zero_absurd(k, h%s))' % (ty(bad), b0)]
        a('\n'.join(ls) + '\n')

BB = 'b1: Nat, b2: Nat, b3: Nat, b4: Nat'
STEP = 'PX.add(%s, PX.tsel(b1, b2, b3, b4, PX.tab(a)))' % D4R
a('''# the step of the code
def wst_e(%(H)s, %(CH)s, +b1: Nat, +b2: Nat, +b3: Nat, +b4: Nat, %(HB)s) -> %(concl)s:
  %%rw tsel_tab(one, h1, b1, b2, b3, b4, hb1, hb2, hb3, hb4, a, ha)
  wt(%(A)s, %(CA)s, b1, hb1, b2, hb2, b3, hb3, b4, hb4)

def wst_r(+one: Nat, +h1: {one == 1n : Nat}, +a: PX.PT, +r: PX.PT, +ha: %(pa)s, +hr: %(pr)s, +b1: Nat, +b2: Nat, +b3: Nat, +b4: Nat, %(HB)s) -> %(cr)s:
  %%rw tsel_tab(one, h1, b1, b2, b3, b4, hb1, hb2, hb3, hb4, a, ha)
  PP.padd_r(one, h1, %(x4)s, tpk(b1, b2, b3, b4, a), d4_r(one, h1, r, hr), tpk_r(one, h1, b1, b2, b3, b4, a, ha))

def wst_vd(%(H)s, +a: PX.PT, +r: PX.PT, +ha: %(pa)s, +va: %(vpa)s, +hr: %(pr)s, +vr: %(vpr)s, +b1: Nat, +b2: Nat, +b3: Nat, +b4: Nat, %(HB)s) -> %(cv)s:
  %%rw tsel_tab(one, h1, b1, b2, b3, b4, hb1, hb2, hb3, hb4, a, ha)
  %%rw PP.padd_v(one, h1, %(x4)s, tpk(b1, b2, b3, b4, a), d4_r(one, h1, r, hr), tpk_r(one, h1, b1, b2, b3, b4, a, ha))
  %%rw d4_v(one, h1, r, hr)
  GP.group_closed(%(A)s, %(s4)s, PP.pv(one, tpk(b1, b2, b3, b4, a)), dbl4_vd(%(A)s, PP.pv(one, r), vr), tpk_vd(%(A)s, b1, b2, b3, b4, a, ha, va))
''' % dict(H=HYP, A=ARG, CH=CH, CA=CA, HB=HB, pa=pd('a'), pr=pd('r'), vpa=vd('PP.pv(one, a)'), vpr=vd('PP.pv(one, r)'), x4=D4R,
           s4=pdbl('PP.pv(one, r)', 4),
           concl=eq('PP.pv(one, %s)' % STEP, smul(nxt4(['b1', 'b2', 'b3', 'b4']), 'PP.pv(one, a)')),
           cr=pd(STEP), cv=vd('PP.pv(one, %s)' % STEP)))

# ---- the loop ----
SPLIT = '''      +c1 = Lg.and_right(Nat.is_lt(b1, 2n), BV.all01(b2 <> b3 <> b4 <> t), hb)
      +c2 = Lg.and_right(Nat.is_lt(b2, 2n), BV.all01(b3 <> b4 <> t), c1)
      +c3 = Lg.and_right(Nat.is_lt(b3, 2n), BV.all01(b4 <> t), c2)
      +hb1 = Lg.and_left(Nat.is_lt(b1, 2n), BV.all01(b2 <> b3 <> b4 <> t), hb)
      +hb2 = Lg.and_left(Nat.is_lt(b2, 2n), BV.all01(b3 <> b4 <> t), c1)
      +hb3 = Lg.and_left(Nat.is_lt(b3, 2n), BV.all01(b4 <> t), c2)
      +hb4 = Lg.and_left(Nat.is_lt(b4, 2n), BV.all01(t), c3)
      +hbt = Lg.and_right(Nat.is_lt(b4, 2n), BV.all01(t), c3)'''
STEPT = 'PX.add(%s, PX.tsel(b1, b2, b3, b4, PX.tab(a)))' % D4R


def loop(name, extra_h, concl, base, rec, absurd_ty, hyp=None):
    ls = ['def %s(%s, bs: List<&2, Nat>, +a: PX.PT, +r: PX.PT%s, +hb: {BV.all01(bs) == True{} : Bool}, +hq: {ok4(bs) == True{} : Bool}) -> %s:' % (name, hyp or HYP, extra_h, concl('bs', 'r', 'v')),
          '  match bs:', '    case Nil{}:', '      ' + base]
    for pat, lst in (('+b1 <> Nil{}', '[b1]'), ('+b1 <> +b2 <> Nil{}', '[b1, b2]'), ('+b1 <> +b2 <> +b3 <> Nil{}', '[b1, b2, b3]')):
        ls += ['    case %s:' % pat, '      Empty.absurd(%s, Lg.false_true(hq))' % absurd_ty(lst)]
    ls += ['    case +b1 <> +b2 <> +b3 <> +b4 <> +t:', SPLIT, rec]
    return '\n'.join(ls) + '\n'


a('''# ---- the loop over the windows ----

# a multiple of 4 bits
def ok4(xs: List<&2, Nat>) -> Bool:
  match xs:
    case Nil{}: True{}
    case b1 <> Nil{}: False{}
    case b1 <> b2 <> Nil{}: False{}
    case b1 <> b2 <> b3 <> Nil{}: False{}
    case b1 <> b2 <> b3 <> b4 <> t: ok4(t)
''')
PA = ', +ha: %s, +hr: %s' % (pd('a'), pd('r'))
a(loop('wgo_r', PA, lambda bs, r, v: pd('PX.wgo(%s, PX.tab(a), %s)' % (bs, r)), 'hr',
       '      wgo_r(one, h1, t, a, %s, ha, wst_r(one, h1, a, r, ha, hr, b1, b2, b3, b4, hb1, hb2, hb3, hb4), hbt, hq)' % STEPT,
       lambda lst: pd('PX.wgo(%s, PX.tab(a), r)' % lst), HYP0))
PV = ', +ha: %s, +va: %s, +hr: %s, +vr: %s' % (pd('a'), vd('PP.pv(one, a)'), pd('r'), vd('PP.pv(one, r)'))
a(loop('wgo_vd', PV, lambda bs, r, v: vd('PP.pv(one, PX.wgo(%s, PX.tab(a), %s))' % (bs, r)), 'vr',
       '      wgo_vd(%s, t, a, %s, ha, va, wst_r(one, h1, a, r, ha, hr, b1, b2, b3, b4, hb1, hb2, hb3, hb4), wst_vd(%s, a, r, ha, va, hr, vr, b1, b2, b3, b4, hb1, hb2, hb3, hb4), hbt, hq)' % (ARG, STEPT, ARG),
       lambda lst: vd('PP.pv(one, PX.wgo(%s, PX.tab(a), r))' % lst)))
PE = ', +v: Nat' + PV + ', +he: %s' % eq('PP.pv(one, r)', smul('v', 'PP.pv(one, a)'))
ce = lambda bs, r, v: eq('PP.pv(one, PX.wgo(%s, PX.tab(a), %s))' % (bs, r), smul('G4.bvl(%s, %s)' % (bs, v), 'PP.pv(one, a)'))
a(loop('wgo_e', PE, ce, 'he',
       '      wgo_e(%s, t, a, %s, %s, ha, va, wst_r(one, h1, a, r, ha, hr, b1, b2, b3, b4, hb1, hb2, hb3, hb4), wst_vd(%s, a, r, ha, va, hr, vr, b1, b2, b3, b4, hb1, hb2, hb3, hb4), wst_e(%s, %s, b1, b2, b3, b4, hb1, hb2, hb3, hb4), hbt, hq)' % (ARG, STEPT, nxt4(['b1', 'b2', 'b3', 'b4']), ARG, ARG, CA),
       lambda lst: ce(lst, 'r', 'v')))

# ---- wmul ----
INF_E = eq('PP.pv(one, PX.infinity())', smul('0n', 'PP.pv(one, a)'))
a('''# ---- [k] a ----

def inf_vd(%(H)s) -> %(vinf)s:
  %%rw PM.pinf_v(one, h1)
  GP.group_infinity(%(A)s)

def inf_e(%(H)s, +a: PX.PT) -> %(infe)s:
  %%rw PM.pinf_v(one, h1)
  GP.equiv_refl(%(A)s, CV.infinity())

def wmul_r(+one: Nat, +h1: {one == 1n : Nat}, bs: List<&2, Nat>, +a: PX.PT, +ha: %(pa)s, +hb: {BV.all01(bs) == True{} : Bool}, +hq: {ok4(bs) == True{} : Bool}) -> %(cr)s:
  match bs:
    case Nil{}:
      PM.pinf_r(one, h1)
    case +b <> +t:
      wgo_r(one, h1, b <> t, a, PX.infinity(), ha, PM.pinf_r(one, h1), hb, hq)

def wmul_vd(%(H)s, bs: List<&2, Nat>, +a: PX.PT, +ha: %(pa)s, +va: %(vpa)s, +hb: {BV.all01(bs) == True{} : Bool}, +hq: {ok4(bs) == True{} : Bool}) -> %(cv)s:
  match bs:
    case Nil{}:
      inf_vd(%(A)s)
    case +b <> +t:
      wgo_vd(%(A)s, b <> t, a, PX.infinity(), ha, va, PM.pinf_r(one, h1), inf_vd(%(A)s), hb, hq)

# wmul(bits, a) is [v] a for the number v of the bits
def wmul_e(%(H)s, bs: List<&2, Nat>, +a: PX.PT, +ha: %(pa)s, +va: %(vpa)s, +hb: {BV.all01(bs) == True{} : Bool}, +hq: {ok4(bs) == True{} : Bool}) -> %(ce)s:
  match bs:
    case Nil{}:
      inf_e(%(A)s, a)
    case +b <> +t:
      wgo_e(%(A)s, b <> t, a, PX.infinity(), 0n, ha, va, PM.pinf_r(one, h1), inf_vd(%(A)s), inf_e(%(A)s, a), hb, hq)
''' % dict(H=HYP, A=ARG, vinf=vd('PP.pv(one, PX.infinity())'), infe=INF_E, pa=pd('a'), vpa=vd('PP.pv(one, a)'),
           cr=pd('PX.wmul(bs, a)'), cv=vd('PP.pv(one, PX.wmul(bs, a))'),
           ce=eq('PP.pv(one, PX.wmul(bs, a))', smul('G4.bvl(bs, 0n)', 'PP.pv(one, a)'))))

# ---- two files: pwr.src, the definitions without the group law (the
# code's points: tab, pick, tsel and wmul are points of the curve's
# representation), for the roots that do not use the group law; pwin.src
# the rest, importing pwr.bend as WR ----
import re
text = '\n'.join(o)
head, _, body = text.partition('\n# ---- on the specification')
body = '# ---- on the specification' + body
blocks = re.split(r'(?m)^(?=def |# ----)', body)
names = [re.match(r'def (\w+)', b).group(1) if b.startswith('def ') else None for b in blocks]
GROUP = re.compile(r'(?<![\w.])(GP|GS|G4|NP)\.|\bhp\b|\bhc\b')
defs = set(n for n in names if n)
free = set()
changed = True
while changed:
    changed = False
    for n, b in zip(names, blocks):
        if not n or n in free or GROUP.search(b):
            continue
        refs = set(re.findall(r'(?<![\w.])(\w+)\(', b)) & defs
        if refs - {n} <= free:
            free.add(n); changed = True
R, W = [], []
for n, b in zip(names, blocks):
    (R if n in free else W).append(b)
q = re.compile(r'(?<![\w.])(%s)(?=\()' % '|'.join(sorted(free, key=len, reverse=True)))
W = [q.sub(r'WR.\1', b) for b in W]
hl = head.split('\n')
imp = [l for l in hl if l.startswith('import ')]
rest = [l for l in hl if not l.startswith('import ')]
rimp = [l for l in imp if not re.search(r' as (GP|GS|G4|NP|C|NA)$', l)]
(ROOT / 'tools/generators/secp256k1_hand/pwr.src').write_text('\n'.join(rimp + ['', '# GENERATED by tools/generators/secp256k1_win.py; edit the generator.', '#', '# The 4-bit fixed-window multiplication of src/crypto/secp256k1/pt.bend on', '# the code\'s points, without the group law: the table, the selection and', '# wmul are points of the representation (pred), and the table entries are', '# repeated additions (tabp). The group-law half is pwin.bend.', '']) + ''.join(R).rstrip('\n') + '\n')
(ROOT / 'tools/generators/secp256k1_hand/pwin.src').write_text('\n'.join(imp + ['import ./pwr.bend as WR'] + rest) + ''.join(W).rstrip('\n') + '\n')
print('wrote tools/generators/secp256k1_hand/pwr.src (%d defs), pwin.src' % len(free))
