#!/usr/bin/env python3
"""Fixed-window (4-bit) exponentiation for the secp256k1 records: the code
(emitted into src/crypto/secp256k1/fe.bend and se.bend by their generators)
and its proofs (written between the markers of
tools/generators/secp256k1_hand/fieldpow.src and scalarpow.src).

  python3 tools/generators/secp256k1_pw.py      rewrite the two .src regions

x^e for the bits of e, most significant first: a table x^0 .. x^15, then for
every 4 bits four squarings and one product by the table entry of the digit
(none for 0); fewer than 4 bits left are done bit by bit (pow_go). The value
is the one of square-and-multiply over the same bits (BV.hv): the proofs
split hv of 4 bits as hv(bits, 0) + 16 e and read the table entries as
x^k (tpow). The branch is on the public exponent only.
"""
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
N = 16


def fields(p, n=N):
    return ', '.join('%s%d' % (p, i) for i in range(n))


def code(T, T16, G, ctor, own_types):
    """Bend code: T the element type, T16 the table type, G the getter
    prefix, ctor the element constructor (for the wrapper); own_types: also
    define the T16 type and its getters"""
    out = []
    if own_types:
        out.append('''# ---- fixed-window exponentiation (GENERATED by tools/generators/secp256k1_pw.py) ----

# x^0, ..., x^15
type T16 is Data:
  T16{%s}
''' % ', '.join('t%d: FE' % i for i in range(16)))
        for i in range(16):
            out.append('def g%d(t: T16) -> FE:\n  match t:\n    case T16{%s}: t%d\n' % (i, fields('t'), i))
    else:
        out.append('# ---- fixed-window exponentiation (GENERATED by tools/generators/secp256k1_pw.py) ----\n')
    lets = '\n'.join('  +t%d = mul(%s, x)' % (i, 'x' if i == 2 else 't%d' % (i - 1)) for i in range(2, 16))
    out.append('''# x^k: k - 1 products for k >= 1 (the table's entries)
def tpow(k: Nat, +x: %(T)s) -> %(T)s:
  match k:
    case 0n: one()
    case 1n: x
    case 2n+j: mul(tpow(1n+j, x), x)

def table(+x: %(T)s) -> %(T16)s:
%(lets)s
  %(T16)s{one(), x, %(ts)s}

# the digit of 4 bits, most significant first
def wdig(+b1: Nat, +b2: Nat, +b3: Nat, +b4: Nat) -> Nat:
  Nat.add(Nat.add(Nat.add(Nat.mul(b1, 8n), Nat.mul(b2, 4n)), Nat.mul(b3, 2n)), b4)

# s x^d for the table t of x
def wstep(d: Nat, +t: %(T16)s, s: %(T)s) -> %(T)s:
  match d:
    case 0n: s
%(cases)s
    case 16n+k: s

# x^e from acc = x^e0: 4 bits at a time, the last 1 to 3 bits one by one
def pw_go(+x: %(T)s, +t: %(T16)s, bits: List<&2, Nat>, acc: %(T)s) -> %(T)s:
  match bits:
    case Nil{}: acc
    case b1 <> Nil{}: pow_go(x, [b1], acc)
    case b1 <> b2 <> Nil{}: pow_go(x, [b1, b2], acc)
    case b1 <> b2 <> b3 <> Nil{}: pow_go(x, [b1, b2, b3], acc)
    case b1 <> b2 <> b3 <> b4 <> r: pw_go(x, t, r, wstep(wdig(b1, b2, b3, b4), t, sq(sq(sq(sq(acc))))))

# the table only for some bits
def pw_go2(+x: %(T)s, bits: List<&2, Nat>, acc: %(T)s) -> %(T)s:
  match bits:
    case Nil{}: acc
    case b <> t: pw_go(x, table(x), b <> t, acc)

def pwx(x: %(T)s, bits: List<&2, Nat>, acc: %(T)s) -> %(T)s:
  match x:
    case %(ctor)s{%(xs)s}: pw_go2(%(ctor)s{%(xs)s}, bits, acc)

# (the bits and then x are looked at first, so that on unknown bits or an
# unknown x the proof checker keeps the exponentiation, and its table, folded)
def pw(x: %(T)s, bits: List<&2, Nat>, acc: %(T)s) -> %(T)s:
  match bits:
    case Nil{}: acc
    case b <> t: pwx(x, b <> t, acc)
''' % dict(T=T, T16=T16, lets=lets, ts=', '.join('t%d' % i for i in range(2, 16)),
           cases='\n'.join('    case %dn: mul(s, %s%d(t))' % (k, G, k) for k in range(1, 16)),
           ctor=ctor, xs=fields('x'), pxs=', '.join('+x%d' % i for i in range(N))))
    return '\n'.join(out)


def bits4(k):
    return [(k >> 3) & 1, (k >> 2) & 1, (k >> 1) & 1, k & 1]


def blist(bs):
    return '[' + ', '.join('%dn' % b if isinstance(b, int) else b for b in bs) + ']'


def proofs(P):
    """rw.py source of the proofs; P: the names of the instance"""
    o = []
    a = o.append
    X = 'LV.ev(R.to_list(x))'
    MP = P['MP']
    m = '1n+%s' % MP
    S4 = '%(M)s.sq(%(M)s.sq(%(M)s.sq(%(M)s.sq(acc))))' % P
    red = lambda t: '%s(one, %s)' % (P['RED'], t)
    hyps = '+one: Nat, +h1: {one == 1n : Nat}, +x: R.FE, +hx: {%s == True{} : Bool}' % red('x')
    ahyps = '+acc: R.FE, +ha: {%s == True{} : Bool}, +e: Nat, +he: {LV.ev(R.to_list(acc)) == Nat.mod(Nat.pow(%s, e), %s) : Nat}' % (red('acc'), X, m)
    aargs = 'one, h1, x, hx, acc, ha, e, he'
    rhyps = '+acc: R.FE, +ha: {%s == True{} : Bool}' % red('acc')
    rargs = 'one, h1, x, hx, acc, ha'
    ex = lambda t, k: '{LV.ev(R.to_list(%s)) == Nat.mod(Nat.pow(%s, %s), %s) : Nat}' % (t, X, k, m)
    a('''# ---- fixed-window exponentiation (GENERATED by tools/generators/secp256k1_pw.py) ----

# x^f x^g = x^(f + g) on residues
def wmul2(+mp: Nat, +x: Nat, +f: Nat, +g: Nat, +a: Nat, +b: Nat, +ha: {a == Nat.mod(Nat.pow(x, f), 1n+mp) : Nat}, +hb: {b == Nat.mod(Nat.pow(x, g), 1n+mp) : Nat}) -> {Nat.mod(Nat.mul(a, b), 1n+mp) == Nat.mod(Nat.pow(x, Nat.add(f, g)), 1n+mp) : Nat}:
  %%rwh ha : {a == Nat.mod(Nat.pow(x, f), 1n+mp) : Nat}
  %%rwh hb : {b == Nat.mod(Nat.pow(x, g), 1n+mp) : Nat}
  %%rw NR.mod_mul_l(mp, Nat.pow(x, f), Nat.mod(Nat.pow(x, g), 1n+mp))
  %%rw NR.mod_mul_r(mp, Nat.pow(x, f), Nat.pow(x, g))
  %%rw NR.pow_add(x, f, g)
  %%close

# e doubled once per bit
def wsh(bs: List<&2, Nat>, +e: Nat) -> Nat:
  match bs:
    case Nil{}: e
    case b <> t: wsh(t, Nat.double(e))

# square-and-multiply from f + e: the part from f, plus e doubled per bit
def whv_add(+one: Nat, bs: List<&2, Nat>, +f: Nat, +e: Nat) -> {BV.hv(bs, one, Nat.add(f, e)) == Nat.add(BV.hv(bs, one, f), wsh(bs, e)) : Nat}:
  match bs:
    case Nil{}:
      {==}
    case +b <> +t:
      %%goal {BV.hv(t, one, Nat.add(Nat.mul(b, one), Nat.double(Nat.add(f, e)))) == Nat.add(BV.hv(t, one, Nat.add(Nat.mul(b, one), Nat.double(f))), wsh(t, Nat.double(e))) : Nat}
      %%rw <- N.add_double(f, e)
      %%rw <- NA.add_assoc(Nat.mul(b, one), Nat.double(f), Nat.double(e))
      %%rw whv_add(one, t, Nat.add(Nat.mul(b, one), Nat.double(f)), Nat.double(e))
      %%close

# x = x^1
def wx1(%(hyps)s) -> %(ex1)s:
  %%goal {%(X)s == Nat.mod(Nat.mul(%(X)s, 1n), %(m)s) : Nat}
  %%rw NA.mul_one(%(X)s)
  Equal.sym(Nat, Nat.mod(%(X)s, %(m)s), %(X)s, NR.mod_of(0n, %(MP)s, %(X)s, %(RLT)s))

def wtp_r(+one: Nat, +h1: {one == 1n : Nat}, k: Nat, +x: R.FE, +hx: {%(redx)s == True{} : Bool}) -> {%(redt)s == True{} : Bool}:
  match k:
    case 0n:
      %(ONER)s
    case 1n:
      hx
    case 2n+ +j:
      %(MULR)s(one, h1, %(M)s.tpow(1n+j, x), x, wtp_r(one, h1, 1n+j, x, hx), hx)

def wtp_e(+one: Nat, +h1: {one == 1n : Nat}, k: Nat, +x: R.FE, +hx: {%(redx)s == True{} : Bool}) -> %(ext)s:
  match k:
    case 0n:
      %(ONEE)s
    case 1n:
      wx1(one, h1, x, hx)
    case 2n+ +j:
      %%goal {LV.ev(R.to_list(%(M)s.mul(%(M)s.tpow(1n+j, x), x))) == Nat.mod(Nat.pow(%(X)s, Nat.add(1n, 1n+j)), %(m)s) : Nat}
      %%rw %(MULE)s(one, h1, %(M)s.tpow(1n+j, x), x, wtp_r(one, h1, 1n+j, x, hx), hx)
      %%rw <- NA.add_comm(1n+j, 1n)
      ME.mul_step(%(MP)s, %(X)s, 1n+j, LV.ev(R.to_list(%(M)s.tpow(1n+j, x))), wtp_e(one, h1, 1n+j, x, hx))

def wsq_e(%(hyps)s, +y: R.FE, +hy: {%(redy)s == True{} : Bool}, +f: Nat, +hf: %(exyf)s) -> %(exsq)s:
  Equal.trans(Nat, LV.ev(R.to_list(%(M)s.sq(y))), Nat.mod(Nat.mul(LV.ev(R.to_list(y)), LV.ev(R.to_list(y))), %(m)s), Nat.mod(Nat.pow(%(X)s, Nat.double(f)), %(m)s), %(SQE)s(one, h1, y, hy), ME.sq_step(%(MP)s, %(X)s, f, LV.ev(R.to_list(y)), hf))

def wsq4_r(+one: Nat, +h1: {one == 1n : Nat}, +acc: R.FE, +ha: {%(reda)s == True{} : Bool}) -> {%(reds4)s == True{} : Bool}:
  %(SQR)s(one, h1, %(M)s.sq(%(M)s.sq(%(M)s.sq(acc))), %(SQR)s(one, h1, %(M)s.sq(%(M)s.sq(acc)), %(SQR)s(one, h1, %(M)s.sq(acc), %(SQR)s(one, h1, acc, ha))))

def wsq4_e(%(hyps)s, %(ahyps)s) -> %(exs4)s:
  +s1 = %(M)s.sq(acc)
  +s2 = %(M)s.sq(s1)
  +s3 = %(M)s.sq(s2)
  +r1 = %(SQR)s(one, h1, acc, ha)
  +r2 = %(SQR)s(one, h1, s1, r1)
  +r3 = %(SQR)s(one, h1, s2, r2)
  +e1 = wsq_e(one, h1, x, hx, acc, ha, e, he)
  +e2 = wsq_e(one, h1, x, hx, s1, r1, Nat.double(e), e1)
  +e3 = wsq_e(one, h1, x, hx, s2, r2, Nat.double(Nat.double(e)), e2)
  wsq_e(one, h1, x, hx, s3, r3, Nat.double(Nat.double(Nat.double(e))), e3)
''' % dict(P, hyps=hyps, ahyps=ahyps, X=X, m=m, ex1=ex('x', '1n'), RLT=P['RLT'] % ('x', 'hx'), redx=red('x'), redy=red('y'), reda=red('acc'),
           redt=red('%s.tpow(k, x)' % P['M']), ext=ex('%s.tpow(k, x)' % P['M'], 'k'), exyf=ex('y', 'f'),
           exsq=ex('%s.sq(y)' % P['M'], 'Nat.double(f)'), reds4=red(S4), exs4=ex(S4, 'Nat.double(Nat.double(Nat.double(Nat.double(e))))')))
    # the leaves: 4 known bits
    for k in range(16):
        bs = bits4(k)
        B = blist(bs)
        tgt = 'BV.hv(%s, one, e)' % B
        step = '%s.wstep(%dn, %s.table(x), %s)' % (P['M'], k, P['M'], S4)
        if k == 0:
            a('def wlf%d_e(%s, %s) -> %s:\n  wsq4_e(%s)\n' % (k, hyps, ahyps, ex(step, tgt), aargs))
            a('def wlf%d_r(%s, %s) -> {%s == True{} : Bool}:\n  wsq4_r(one, h1, acc, ha)\n' % (k, hyps, rhyps, red(step)))
            continue
        a('''def whk%(k)d(+one: Nat, +h1: {one == 1n : Nat}) -> {BV.hv(%(B)s, one, 0n) == %(k)dn : Nat}:
  %%rwh h1 : {one == 1n : Nat}
  %%close

def wlf%(k)d_e(%(hyps)s, %(ahyps)s) -> %(ext)s:
  %%goal {LV.ev(R.to_list(%(M)s.mul(%(S4)s, %(M)s.tpow(%(k)dn, x)))) == Nat.mod(Nat.pow(%(X)s, BV.hv(%(B)s, one, Nat.add(0n, e))), %(m)s) : Nat}
  %%rw whv_add(one, %(B)s, 0n, e)
  %%rw whk%(k)d(one, h1)
  %%rw NA.add_comm(%(k)dn, wsh(%(B)s, e))
  %%rw %(MULE)s(one, h1, %(S4)s, %(M)s.tpow(%(k)dn, x), wsq4_r(one, h1, acc, ha), wtp_r(one, h1, %(k)dn, x, hx))
  wmul2(%(MP)s, %(X)s, wsh(%(B)s, e), %(k)dn, LV.ev(R.to_list(%(S4)s)), LV.ev(R.to_list(%(M)s.tpow(%(k)dn, x))), wsq4_e(%(aargs)s), wtp_e(one, h1, %(k)dn, x, hx))

def wlf%(k)d_r(%(hyps)s, %(rhyps)s) -> {%(redst)s == True{} : Bool}:
  %(MULR)s(one, h1, %(S4)s, %(M)s.tpow(%(k)dn, x), wsq4_r(one, h1, acc, ha), wtp_r(one, h1, %(k)dn, x, hx))
''' % dict(P, k=k, B=B, hyps=hyps, ahyps=ahyps, rhyps=rhyps, ext=ex(step, tgt), S4=S4, X=X, m=m, aargs=aargs, redst=red(step)))
    # the tree over the 4 bits (deepest first, so that every def is declared before use)
    for depth in (3, 2, 1, 0):
        for pre in range(1 << depth):
            pb = [(pre >> (depth - 1 - i)) & 1 for i in range(depth)]
            rest = ['b%d' % (i + 1) for i in range(depth, 4)]
            allb = pb + rest
            name = 'wv' + ''.join(map(str, pb))
            bparams = ', '.join('%s: Nat, +h%s: {Nat.is_lt(%s, 2n) == True{} : Bool}' % (b, b, b) for b in rest)
            dig = '%s.wdig(%s)' % (P['M'], ', '.join('%dn' % b if isinstance(b, int) else b for b in allb))
            step = '%s.wstep(%s, %s.table(x), %s)' % (P['M'], dig, P['M'], S4)
            tgt = 'BV.hv(%s, one, e)' % blist(allb)
            b0 = rest[0]
            for kind in ('e', 'r'):
                ty = ex(step, tgt) if kind == 'e' else '{%s == True{} : Bool}' % red(step)
                lines = ['def %s_%s(%s, %s, %s) -> %s:' % (name, kind, hyps, ahyps if kind == 'e' else rhyps, bparams, ty), '  match %s:' % b0]
                args = aargs if kind == 'e' else rargs
                for v in (0, 1):
                    child = pb + [v]
                    cargs = ', '.join('%s, h%s' % (b, b) for b in rest[1:])
                    if len(child) == 4:
                        k = child[0] * 8 + child[1] * 4 + child[2] * 2 + child[3]
                        call = 'wlf%d_%s(%s)' % (k, kind, args)
                    else:
                        call = 'wv%s_%s(%s%s)' % (''.join(map(str, child)), kind, args, ', ' + cargs if cargs else '')
                    lines += ['    case %dn:' % v, '      ' + call]
                bad = [('2n+k' if b == b0 else b) for b in allb]
                dig2 = '%s.wdig(%s)' % (P['M'], ', '.join('%dn' % b if isinstance(b, int) else b for b in bad))
                step2 = '%s.wstep(%s, %s.table(x), %s)' % (P['M'], dig2, P['M'], S4)
                ty2 = ex(step2, 'BV.hv(%s, one, e)' % blist(bad)) if kind == 'e' else '{%s == True{} : Bool}' % red(step2)
                lines += ['    case 2n+ +k:', '      Empty.absurd(%s, N.lt_zero_absurd(k, h%s))' % (ty2, b0)]
                a('\n'.join(lines) + '\n')
    # the loop
    a('''def wpw_r(%(hyps)s, bs: List<&2, Nat>, +acc: R.FE, +ha: {%(reda)s == True{} : Bool}, +hb: {BV.all01(bs) == True{} : Bool}) -> {%(redpw)s == True{} : Bool}:
  match bs:
    case Nil{}:
      ha
    case +b1 <> Nil{}:
      %(POWR)s(one, h1, x, hx, [b1], acc, ha, hb)
    case +b1 <> +b2 <> Nil{}:
      %(POWR)s(one, h1, x, hx, [b1, b2], acc, ha, hb)
    case +b1 <> +b2 <> +b3 <> Nil{}:
      %(POWR)s(one, h1, x, hx, [b1, b2, b3], acc, ha, hb)
    case +b1 <> +b2 <> +b3 <> +b4 <> +r:
      +c1 = Lg.and_right(Nat.is_lt(b1, 2n), BV.all01(b2 <> b3 <> b4 <> r), hb)
      +c2 = Lg.and_right(Nat.is_lt(b2, 2n), BV.all01(b3 <> b4 <> r), c1)
      +c3 = Lg.and_right(Nat.is_lt(b3, 2n), BV.all01(b4 <> r), c2)
      +hb1 = Lg.and_left(Nat.is_lt(b1, 2n), BV.all01(b2 <> b3 <> b4 <> r), hb)
      +hb2 = Lg.and_left(Nat.is_lt(b2, 2n), BV.all01(b3 <> b4 <> r), c1)
      +hb3 = Lg.and_left(Nat.is_lt(b3, 2n), BV.all01(b4 <> r), c2)
      +hb4 = Lg.and_left(Nat.is_lt(b4, 2n), BV.all01(r), c3)
      +hr = Lg.and_right(Nat.is_lt(b4, 2n), BV.all01(r), c3)
      +ha2 = wv_r(one, h1, x, hx, acc, ha, b1, hb1, b2, hb2, b3, hb3, b4, hb4)
      wpw_r(one, h1, x, hx, r, %(M)s.wstep(%(M)s.wdig(b1, b2, b3, b4), %(M)s.table(x), %(S4)s), ha2, hr)

def wpw_e(%(hyps)s, bs: List<&2, Nat>, %(ahyps)s, +hb: {BV.all01(bs) == True{} : Bool}) -> %(expw)s:
  match bs:
    case Nil{}:
      he
    case +b1 <> Nil{}:
      %(POWE)s(one, h1, x, hx, [b1], acc, ha, e, he, hb)
    case +b1 <> +b2 <> Nil{}:
      %(POWE)s(one, h1, x, hx, [b1, b2], acc, ha, e, he, hb)
    case +b1 <> +b2 <> +b3 <> Nil{}:
      %(POWE)s(one, h1, x, hx, [b1, b2, b3], acc, ha, e, he, hb)
    case +b1 <> +b2 <> +b3 <> +b4 <> +r:
      +c1 = Lg.and_right(Nat.is_lt(b1, 2n), BV.all01(b2 <> b3 <> b4 <> r), hb)
      +c2 = Lg.and_right(Nat.is_lt(b2, 2n), BV.all01(b3 <> b4 <> r), c1)
      +c3 = Lg.and_right(Nat.is_lt(b3, 2n), BV.all01(b4 <> r), c2)
      +hb1 = Lg.and_left(Nat.is_lt(b1, 2n), BV.all01(b2 <> b3 <> b4 <> r), hb)
      +hb2 = Lg.and_left(Nat.is_lt(b2, 2n), BV.all01(b3 <> b4 <> r), c1)
      +hb3 = Lg.and_left(Nat.is_lt(b3, 2n), BV.all01(b4 <> r), c2)
      +hb4 = Lg.and_left(Nat.is_lt(b4, 2n), BV.all01(r), c3)
      +hr = Lg.and_right(Nat.is_lt(b4, 2n), BV.all01(r), c3)
      +st = %(M)s.wstep(%(M)s.wdig(b1, b2, b3, b4), %(M)s.table(x), %(S4)s)
      +rs = wv_r(one, h1, x, hx, acc, ha, b1, hb1, b2, hb2, b3, hb3, b4, hb4)
      +es = wv_e(one, h1, x, hx, acc, ha, e, he, b1, hb1, b2, hb2, b3, hb3, b4, hb4)
      wpw_e(one, h1, x, hx, r, st, rs, BV.hv([b1, b2, b3, b4], one, e), es, hr)

# pw looks at the bits, then at x (the table is never formed on unknown bits)
def pwx_is(x: R.FE, +bs: List<&2, Nat>, +acc: R.FE) -> {%(M)s.pwx(x, bs, acc) == %(M)s.pw_go2(x, bs, acc) : R.FE}:
  match x:
    case R.FE{%(as_)s}:
      {==}

def pw_is(+x: R.FE, bs: List<&2, Nat>, +acc: R.FE) -> {%(M)s.pw(x, bs, acc) == %(M)s.pw_go2(x, bs, acc) : R.FE}:
  match bs:
    case Nil{}:
      {==}
    case +b <> +t:
      pwx_is(x, b <> t, acc)

def wpw2_e(%(hyps)s, bs: List<&2, Nat>, %(ahyps)s, +hb: {BV.all01(bs) == True{} : Bool}) -> %(expw3)s:
  match bs:
    case Nil{}:
      he
    case +b <> +t:
      wpw_e(one, h1, x, hx, b <> t, acc, ha, e, he, hb)

def wpw2_r(%(hyps)s, bs: List<&2, Nat>, +acc: R.FE, +ha: {%(reda)s == True{} : Bool}, +hb: {BV.all01(bs) == True{} : Bool}) -> {%(redpw3)s == True{} : Bool}:
  match bs:
    case Nil{}:
      ha
    case +b <> +t:
      wpw_r(one, h1, x, hx, b <> t, acc, ha, hb)

def pw_ev(%(hyps)s, +bs: List<&2, Nat>, %(ahyps)s, +hb: {BV.all01(bs) == True{} : Bool}) -> %(expw2)s:
  %%rw pw_is(x, bs, acc)
  wpw2_e(one, h1, x, hx, bs, acc, ha, e, he, hb)

def pw_rv(%(hyps)s, +bs: List<&2, Nat>, +acc: R.FE, +ha: {%(reda)s == True{} : Bool}, +hb: {BV.all01(bs) == True{} : Bool}) -> {%(redpw2)s == True{} : Bool}:
  %%rw pw_is(x, bs, acc)
  wpw2_r(one, h1, x, hx, bs, acc, ha, hb)
''' % dict(P, hyps=hyps, ahyps=ahyps, reda=red('acc'), S4=S4, as_=fields('a'),
           redpw=red('%s.pw_go(x, %s.table(x), bs, acc)' % (P['M'], P['M'])),
           redpw2=red('%s.pw(x, bs, acc)' % P['M']),
           expw=ex('%s.pw_go(x, %s.table(x), bs, acc)' % (P['M'], P['M']), 'BV.hv(bs, one, e)'),
           expw2=ex('%s.pw(x, bs, acc)' % P['M'], 'BV.hv(bs, one, e)'),
           expw3=ex('%s.pw_go2(x, bs, acc)' % P['M'], 'BV.hv(bs, one, e)'),
           redpw3=red('%s.pw_go2(x, bs, acc)' % P['M'])))
    return '\n'.join(o)


FIELD = dict(M='R', RED='OP.red', MULE='OP.mul_e', SQE='OP.sq_e', MULR='OP.mul_r', SQR='OP.sq_r', MP='K.pp(one)',
             RLT='FO.rlt(one, h1, R.to_list(%s), %s)', ONER='one_r(one, h1)', ONEE='one_e(one, h1, LV.ev(R.to_list(x)))',
             POWE='pow_e', POWR='pow_r')
SCALAR = dict(M='SE', RED='SQ.sred', MULE='SQ.mul_e', SQE='SQ.sq_e', MULR='SQ.mul_r', SQR='SQ.sq_r', MP='K.np(one)',
              RLT='SQ.rlt(one, h1, %s, %s)', ONER='one_r(one, h1)', ONEE='one_e(one, h1, LV.ev(R.to_list(x)))',
              POWE='pow_e', POWR='pow_r')

BEGIN = '# ---- BEGIN windowed (secp256k1_pw.py) ----\n'
END = '# ---- END windowed ----\n'


def splice(path, text):
    s = path.read_text()
    i, j = s.index(BEGIN), s.index(END)
    path.write_text(s[:i + len(BEGIN)] + text + s[j:])


if __name__ == '__main__':
    H = ROOT / 'tools/generators/secp256k1_hand'
    splice(H / 'fieldpow.src', proofs(FIELD))
    print('wrote the windowed region of fieldpow.src')
