#!/usr/bin/env python3
"""Generate src/crypto/secp256k1/fe.bend (GF(p) on 16-field records) and the
bridge lemmas proofs/crypto/secp256k1/febr.bend.

  python3 tools/generators/secp256k1_fe.py

Every stage of fe.bend is straight-line code over the 16 (or 17, 18, 31, 32)
Nat fields of a record, written so that, with its lets substituted, it is
term for term the list function of proofs/crypto/secp256k1/fmod.bend on the
record's fields: febr.bend proves each stage equal to its list model by
normalization ({==}), and the list models carry the value lemmas. The
record stages exist for speed: the compiler keeps a record's fields in
registers, where a list is a chain of heap cells.
"""
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
N = 16

# ---------------------------------------------------------------- terms
# A term is a string; the helpers below build the normal forms of the list
# models (Nat.add(0n, y) reduces to y, as Nat.add looks at its first argument).


def add(x, y):
    return y if x == '0n' else 'Nat.add(%s, %s)' % (x, y)


def ladd(xs, ys):
    """L.add: limb-wise sum, the longer tail kept"""
    if not xs:
        return ys
    if not ys:
        return xs
    return [add(xs[0], ys[0])] + ladd(xs[1:], ys[1:])


def nmul(a, b):
    return 'nmul(%s, %s)' % (a, b)


class Emit:
    """straight-line code with lets; names stand for their terms"""

    def __init__(self, ind='      '):
        self.lines, self.ind, self.n = [], ind, 0

    def let(self, pfx, term):
        self.n += 1
        name = '%s%d' % (pfx, self.n)
        self.lines.append('%s+%s = %s' % (self.ind, name, term))
        return name


def carry(e, xs, n):
    """L.carry(n, xs, 0n) for len(xs) >= n: n limbs and the carry (plus what
    is left of xs, by horner)"""
    out, u = [], '0n'
    for k in range(n):
        s = e.let('s', add(u, xs[k]))
        out.append(e.let('l', 'L.lo16(%s)' % s))
        u = e.let('h', 'L.hi16(%s)' % s)
    rest = xs[n:]
    if not rest:
        out.append(u)
    else:
        # horner(x <> t) = Nat.add(Nat.mul(Nat.mul(horner(t), 256n), 256n), x); horner([]) = 0n
        h = '0n'
        for x in reversed(rest):
            h = x if h == '0n' else 'Nat.add(Nat.mul(Nat.mul(%s, 256n), 256n), %s)' % (h, x)
        out.append(e.let('t', add(u, h)))
    return out


def fields(p, n, plus=True):
    return ', '.join(('+' if plus else '') + '%s%d' % (p, i) for i in range(n))


def rec(ty, xs):
    return '%s{%s}' % (ty, ', '.join(xs))


OUT = []
w = OUT.append

w('''import Base
import ./limbs.bend as L

# GF(p), p = 2^256 - 2^32 - 977, on records of 16 Nat limbs in radix 2^16
# (GENERATED by tools/generators/secp256k1_fe.py; edit the generator).
#
# A record's fields stay in registers in compiled code (a list is a chain of
# heap cells), and the code is straight-line: the schoolbook product (256
# limb products, each a 32-bit multiplication of 16-bit limbs), carry passes
# with lo16 / hi16 (masks and shifts after compilation), and the folds of
# libsecp256k1's secp256k1_fe_mul_inner (2^256 = p + 2^32 + 977): the high
# half times 2^32 + 977 is added to the low half, twice more for the small
# carries out, and one conditional subtraction of p (computed as "add
# 2^32 + 977 and look at bit 256") gives the representative below p.
#
# Every stage is, with its lets substituted, term for term a list function
# of proofs/crypto/secp256k1/fmod.bend on the record's fields (proved by
# normalization in proofs/crypto/secp256k1/febr.bend); the values are proved
# on the lists. Selection is arithmetic and no code branches on a limb.

type FE is Data:
  FE{%s}

type W17 is Data:
  W17{%s}

type W31 is Data:
  W31{%s}


# a b for a, b below 2^16 (a 32-bit multiplication: no overflow check)
def nmul(+a: Nat, +b: Nat) -> Nat:
  U32.to_nat(U32.mul(U32.from_nat(a), U32.from_nat(b)))
''' % tuple(', '.join('l%d: Nat' % i for i in range(k)) for k in (16, 17, 31)))

# ---- the product columns ----


def convu(xs, ys):
    if not xs:
        return []
    return ladd([nmul(y, xs[0]) for y in ys], ['0n'] + convu(xs[1:], ys))


def sqru(xs):
    if not xs:
        return []
    x = xs[0]
    if len(xs) == 1:
        return [nmul(x, x)]
    return ladd([nmul(x, x)] + ['Nat.mul(%s, 2n)' % nmul(y, x) for y in xs[1:]], ['0n', '0n'] + sqru(xs[1:]))


A = ['a%d' % i for i in range(N)]
B = ['b%d' % i for i in range(N)]
cols = convu(A, B)
assert len(cols) == 31
w('# the columns of a b (proofs: fmod.convu)')
w('def cols(a: FE, b: FE) -> W31:')
w('  match a b:')
w('    case FE{%s} FE{%s}:' % (fields('a', N), fields('b', N)))
w('      ' + rec('W31', cols))
w('')
sq = sqru(A)
assert len(sq) == 31
w('# the columns of a^2, the cross products once and doubled (fmod.sqru)')
w('def sqcols(a: FE) -> W31:')
w('  match a:')
w('    case FE{%s}:' % fields('a', N))
w('      ' + rec('W31', sq))
w('')

# ---- carry passes ----


def stage(name, doc, ty_in, n_in, ty_out, body):
    e = Emit()
    xs = ['x%d' % i for i in range(n_in)]
    out = body(e, xs)
    w('# ' + doc)
    w('def %s(r: %s) -> %s:' % (name, ty_in, ty_out))
    w('  match r:')
    w('    case %s{%s}:' % (ty_in, fields('x', n_in)))
    OUT.extend(e.lines)
    w('      ' + rec(ty_out, out))
    w('')
    return out


def carryp(e, xs, n):
    """fmod.carryp(n, xs, 0n): n limbs, the carry added to the next limb, the rest kept"""
    out, u = [], '0n'
    for k in range(n):
        s = e.let('s', add(u, xs[k]))
        out.append(e.let('l', 'L.lo16(%s)' % s))
        u = e.let('h', 'L.hi16(%s)' % s)
    rest = xs[n:]
    if not rest:
        return out + [u]
    return out + [add(u, rest[0])] + rest[1:]


stage('carryp16', 'fmod.carryp(16n, xs, 0n) of the 31 columns: 16 limbs, then the high columns', 'W31', 31, 'W31', lambda e, xs: carryp(e, xs, 16))
stage('carry17', 'L.carry(16n, xs, 0n) of 17 limbs: 16 limbs and the rest', 'W17', 17, 'W17', lambda e, xs: carry(e, xs, 16))
stage('carry16', 'L.carry(16n, xs, 0n) of 16 limbs: 16 limbs and the carry', 'FE', 16, 'W17', lambda e, xs: carry(e, xs, 16))


def fold1(e, xs):
    lo, hi = xs[:16], xs[16:]
    return ladd(ladd(lo, ['Nat.mul(%s, 977n)' % h for h in hi]), ['0n', '0n'] + hi)


stage('fold1', 'lo + (2^32 + 977) hi for 16 limbs lo and 15 high columns hi (fmod.fold1)', 'W31', 31, 'W17', fold1)


def foldt(e, xs):
    top = xs[16]
    return ladd(xs[:16], ['Nat.mul(%s, 977n)' % top, '0n', top])


stage('foldt', 'lo + (2^32 + 977) t for 16 limbs lo and a top t (fmod.foldt)', 'W17', 17, 'FE', foldt)


def fin(e, xs):
    lo, t = xs[:16], xs[16]
    v = carry(e, ladd(lo, ['977n', '0n', '1n']), 16)
    f = e.let('f', add(t, v[16]))
    return ['Nat.add(%s, %s)' % (nmul(v[i], f), nmul(lo[i], 'Nat.sub(1n, %s)' % f)) for i in range(16)]


stage('fin', 'x mod p for x = lo + 2^256 t below 2 p: lo - p when x + 2^32 + 977 reaches 2^256 (fmod.fin)', 'W17', 17, 'FE', fin)

w('''# ---- operations (reduced inputs, reduced results) ----

''')
w('# the limb-wise sum (L.add)')
w('def addr(a: FE, b: FE) -> FE:')
w('  match a b:')
w('    case FE{%s} FE{%s}:' % (fields('x', N, False), fields('y', N, False)))
w('      ' + rec('FE', ladd(['x%d' % i for i in range(N)], ['y%d' % i for i in range(N)])))
w('')


def negraw(e, xs):
    t = carry(e, ladd(xs, ['977n', '0n', '1n']), 16)[:16]
    cm = ['L.comp1(%s)' % x for x in t]
    return ladd(cm, ['1n'])


stage('negr', 'p - b for b below p: (2^256 - 1 - (b + 2^32 + 977)) + 1 (L.neg_raw(F.c(), b))', 'FE', 16, 'FE', negraw)


def kscal(e, xs):
    return ['Nat.mul(%s, 21n)' % x for x in xs]


stage('mul21r', 'the limbs times 21 (L.scal(21n, xs))', 'FE', 16, 'FE', kscal)

w('''def add(a: FE, b: FE) -> FE:
  fin(carry16(addr(a, b)))

def sub(a: FE, b: FE) -> FE:
  fin(carry16(addr(a, negr(b))))

def neg(a: FE) -> FE:
  fin(carry16(negr(a)))

# the reduction of a product: the columns carried to 16 limbs, the high
# columns folded, twice more the carry out folded, and the final subtraction
def mred(c: W31) -> FE:
  fin(carry16(foldt(carry17(fold1(carryp16(c))))))

def mul(a: FE, b: FE) -> FE:
  mred(cols(a, b))

def sq(a: FE) -> FE:
  mred(sqcols(a))

# 21 a (21 = 3 b, the constant of the doubling and addition formulas)
def mul21(a: FE) -> FE:
  fin(carry16(foldt(carry16(mul21r(a)))))

# b x + (1 - b) y, limb-wise and branch-free, for b in {0, 1}
def sel1(+b: Nat, +x: Nat, +y: Nat) -> Nat:
  Nat.add(nmul(x, b), nmul(y, Nat.sub(1n, b)))

def select(+b: Nat, x: FE, y: FE) -> FE:
  match x y:
    case FE{%s} FE{%s}:
      FE{%s}

# x^e for the exponent e given by its bits, most significant first
# (square-and-multiply; the branch is on the public exponent)
def pow_step(b: Nat, +x: FE, s: FE) -> FE:
  match b:
    case 0n: s
    case 1n+k: mul(s, x)

def pow_go(+x: FE, bits: List<&2, Nat>, acc: FE) -> FE:
  match bits:
    case Nil{}: acc
    case b <> t: pow_go(x, t, pow_step(b, x, sq(acc)))

# (x is looked at first, so that on an unknown x the proof checker keeps the
# exponentiation folded)
def pow(x: FE, bits: List<&2, Nat>, acc: FE) -> FE:
  match x:
    case FE{%s}: pow_go(FE{%s}, bits, acc)

def zero() -> FE:
  FE{%s}

def one() -> FE:
  FE{1n, %s}

# ---- lists ----

def to_list(a: FE) -> List<&2, Nat>:
  match a:
    case FE{%s}:
      [%s]

# the record of a 16-limb list (anything else is 0: never met, as every
# list here is reduced), looking at the list first
def of_list(xs: List<&2, Nat>) -> FE:
''' % (fields('x', N), fields('y', N), ', '.join('sel1(b, x%d, y%d)' % (i, i) for i in range(N)), fields('x', N, False), fields('x', N, False), ', '.join(['0n'] * 16), ', '.join(['0n'] * 15), fields('x', N, False), fields('x', N, False)))


def of_list_body(i, ind):
    src = 'xs' if i == 0 else 't%d' % i
    lines = [ind + 'match %s:' % src, ind + '  case Nil{}: zero()']
    if i < N:
        lines.append(ind + '  case x%d <> t%d:' % (i, i + 1))
        lines += of_list_body(i + 1, ind + '    ')
    else:
        lines[-1] = ind + '  case Nil{}: FE{%s}' % fields('x', N, False)
        lines.append(ind + '  case y <> u: zero()')
    return lines


OUT.extend(of_list_body(0, '  '))
w('')

(ROOT / 'src/crypto/secp256k1/fe.bend').write_text('\n'.join(OUT) + '\n')
print('wrote src/crypto/secp256k1/fe.bend')

# ---------------------------------------------------------------- bridges
BR = []
b = BR.append
b('''# GENERATED by tools/generators/secp256k1_fe.py; edit the generator.
import Base
import ../../../spec/lib/common.bend as C
import ../../../spec/crypto/secp256k1/field.bend as FS
import ../../../src/crypto/secp256k1/limbs.bend as L
import ../../../src/crypto/secp256k1/fe.bend as F
import ../../lib/logic.bend as Lg
import ./fmod.bend as M

# Each stage of src/crypto/secp256k1/fe.bend is its list model of fmod.bend
# on the record's fields: both sides normalize to the same term (the
# record's fields are variables, so every limb operation stays folded).
''')
for ty, n in (('W17', 17), ('W31', 31)):
    b('def l%d(r: F.%s) -> List<&2, Nat>:' % (n, ty))
    b('  match r:')
    b('    case F.%s{%s}:' % (ty, fields('x', n, False)))
    b('      [%s]' % fields('x', n, False))
    b('')
NS = {'FE': 16, 'W17': 17, 'W31': 31}


def bridge(name, args, lhs, rhs):
    b('def %s(%s) -> {%s == %s : List<&2, Nat>}:' % (name, ', '.join('%s: F.%s' % (a, t) for a, t in args), lhs, rhs))
    b('  match %s:' % ' '.join(a for a, t in args))
    b('    case %s:' % ' '.join('F.%s{%s}' % (t, fields(a + '_', NS[t])) for a, t in args))
    b('      {==}')
    b('')


bridge('cols_b', [('a', 'FE'), ('c', 'FE')], 'l31(F.cols(a, c))', 'M.convu(F.to_list(a), F.to_list(c))')
bridge('sqcols_b', [('a', 'FE')], 'l31(F.sqcols(a))', 'M.sqru(F.to_list(a))')
bridge('carryp16_b', [('r', 'W31')], 'l31(F.carryp16(r))', 'M.carryp(16n, l31(r), 0n)')
bridge('carry17_b', [('r', 'W17')], 'l17(F.carry17(r))', 'L.carry(16n, l17(r), 0n)')
bridge('carry16_b', [('r', 'FE')], 'l17(F.carry16(r))', 'L.carry(16n, F.to_list(r), 0n)')
bridge('fold1_b', [('r', 'W31')], 'l17(F.fold1(r))', 'M.fold1(l31(r))')
bridge('foldt_b', [('r', 'W17')], 'F.to_list(F.foldt(r))', 'M.foldt(l17(r))')
bridge('fin_b', [('r', 'W17')], 'F.to_list(F.fin(r))', 'M.fin(l17(r))')
bridge('addr_b', [('a', 'FE'), ('c', 'FE')], 'F.to_list(F.addr(a, c))', 'L.add(F.to_list(a), F.to_list(c))')
bridge('negr_b', [('r', 'FE')], 'F.to_list(F.negr(r))', 'L.neg_raw([977n, 0n, 1n], F.to_list(r))')
bridge('mul21r_b', [('r', 'FE')], 'F.to_list(F.mul21r(r))', 'L.scal(21n, F.to_list(r))')

b('def select_b(+s: Nat, a: F.FE, c: F.FE) -> {F.to_list(F.select(s, a, c)) == M.selu(s, F.to_list(a), F.to_list(c)) : List<&2, Nat>}:')
b('  match a c:')
b('    case F.FE{%s} F.FE{%s}:' % (fields('a_', N), fields('c_', N)))
b('      {==}')
b('')

# a 16-limb list is the list of its record: one helper per limb, each
# refining the limb bound of the rest
b('# ---- the record of a 16-limb list ----')
b('')
for k in range(N, -1, -1):
    pre = ' <> '.join(['x%d' % i for i in range(k)] + ['xs'])
    params = ''.join('+x%d: Nat, ' % i for i in range(k))
    b('def shape%d(+one: Nat, %sxs: List<&2, Nat>, +h: {FS.limbs16(one, %dn, xs) == True{} : Bool}) -> {F.to_list(F.of_list(%s)) == %s : List<&2, Nat>}:' % (k, params, N - k, pre, pre))
    b('  match xs:')
    if k < N:
        b('    case Nil{}:')
        b('      Empty.absurd({F.to_list(F.of_list(%s)) == %s : List<&2, Nat>}, Lg.false_true(h))' % (pre.replace('xs', '[]'), pre.replace('xs', '[]')))
        b('    case +y <> +t:')
        args = ''.join('x%d, ' % i for i in range(k))
        b('      shape%d(one, %sy, t, Lg.and_right(Nat.is_lt(y, C.shift(16n, one)), FS.limbs16(one, %dn, t), h))' % (k + 1, args, N - k - 1))
    else:
        b('    case Nil{}:')
        b('      {==}')
        b('    case y <> t:')
        b('      Empty.absurd({F.to_list(F.of_list(%s)) == %s : List<&2, Nat>}, Lg.false_true(h))' % (pre.replace('xs', 'y <> t'), pre.replace('xs', 'y <> t')))
    b('')
b('def shape(+one: Nat, +xs: List<&2, Nat>, +h: {FS.limbs16(one, 16n, xs) == True{} : Bool}) -> {F.to_list(F.of_list(xs)) == xs : List<&2, Nat>}:')
b('  shape0(one, xs, h)')
b('')
(ROOT / 'proofs/crypto/secp256k1/febr.bend').write_text('\n'.join(BR) + '\n')
print('wrote proofs/crypto/secp256k1/febr.bend')
