#!/usr/bin/env python3
"""Generate src/crypto/secp256k1/se.bend (integers modulo the group order n on
the 16-limb records of fe.bend) and the bridge lemmas
proofs/crypto/secp256k1/sebr.bend.

  python3 tools/generators/secp256k1_se.py

The reduction is libsecp256k1's secp256k1_scalar_reduce_512 as
src/crypto/secp256k1/limbs.bend states it (L.reduce(c, 4n, xs): four folds
of the high half times c = 2^256 - n, a carry pass after each, and one
conditional subtraction), written out as straight-line stages over records
with 32-bit limb products. Each stage is, term for term, a list function of
proofs/crypto/secp256k1/smod.bend on the record's fields (sebr.bend, by
normalization); smod.bend shows the list functions are those of limbs.bend
on the lists of 16-bit limbs they are applied to.
"""
from pathlib import Path
import importlib.util

ROOT = Path(__file__).resolve().parents[2]
spec = importlib.util.spec_from_file_location('fegen', str(ROOT / 'tools/generators/secp256k1_fe.py'))
N = 16
CN = [48831, 12233, 41331, 16429, 24516, 20663, 8985, 17745, 1]   # 2^256 - n, radix 2^16


def add(x, y):
    return y if x == '0n' else 'Nat.add(%s, %s)' % (x, y)


def ladd(xs, ys):
    if not xs:
        return ys
    if not ys:
        return xs
    return [add(xs[0], ys[0])] + ladd(xs[1:], ys[1:])


def nmul(a, b):
    return 'FE.nmul(%s, %s)' % (a, b)


class Emit:
    def __init__(self, ind='      '):
        self.lines, self.ind, self.n = [], ind, 0

    def let(self, pfx, term):
        self.n += 1
        name = '%s%d' % (pfx, self.n)
        self.lines.append('%s+%s = %s' % (self.ind, name, term))
        return name


def carry(e, xs, n):
    """L.carry(n, xs, 0n): n limbs (xs padded with steps on Nil) and the rest"""
    out, u = [], '0n'
    for k in range(n):
        x = xs[k] if k < len(xs) else None
        s = e.let('s', add(u, x) if x is not None else 'Nat.add(%s, 0n)' % u)
        out.append(e.let('l', 'L.lo16(%s)' % s))
        u = e.let('h', 'L.hi16(%s)' % s)
    rest = xs[n:]
    if not rest:
        out.append(u)
    else:
        h = '0n'
        for x in reversed(rest):
            h = x if h == '0n' else 'Nat.add(Nat.mul(Nat.mul(%s, 256n), 256n), %s)' % (h, x)
        out.append(e.let('t', add(u, h)))
    return out


def horner(xs):
    h = '0n'
    for x in reversed(xs):
        h = x if h == '0n' else 'Nat.add(Nat.mul(Nat.mul(%s, 256n), 256n), %s)' % (h, x)
    return h


def convu(xs, ys):
    if not xs:
        return []
    return ladd([nmul(y, xs[0]) for y in ys], ['0n'] + convu(xs[1:], ys))


def fields(p, n, plus=True):
    return ', '.join(('+' if plus else '') + '%s%d' % (p, i) for i in range(n))


def rec(ty, xs):
    return '%s{%s}' % (ty, ', '.join(xs))


OUT = []
w = OUT.append
w('''import Base
import ./limbs.bend as L
import ./fe.bend as FE

# Integers modulo the group order n = 2^256 - c (SEC 2 section 2.4.1,
# c = 432420386565659656852420866390673177327 < 2^129) on the 16-limb
# records of fe.bend (GENERATED by tools/generators/secp256k1_se.py; edit
# the generator). A reduced element has 16 limbs below 2^16 and value below n.
#
# The reduction is libsecp256k1's secp256k1_scalar_reduce_512, as
# L.reduce(c, 4n, xs) of limbs.bend states it: four folds of the high half
# times c (32-bit limb products), a carry pass after each, and one
# conditional subtraction of n (computed as "add c and look at bit 256"),
# written out stage by stage over records. Each stage is, term for term, a
# list function of proofs/crypto/secp256k1/smod.bend on its fields
# (proofs/crypto/secp256k1/sebr.bend). No code branches on a limb.

type W9 is Data:
  W9{%s}

type W25 is Data:
  W25{%s}

type W33 is Data:
  W33{%s}

# 2^256 - n, in radix 2^16
def cn() -> W9:
  W9{%s}
''' % (', '.join('l%d: Nat' % i for i in range(9)), ', '.join('l%d: Nat' % i for i in range(25)), ', '.join('l%d: Nat' % i for i in range(33)), ', '.join('%dn' % v for v in CN)))


def stage(name, doc, args, ty_out, body):
    """args: [(var, type, n)]"""
    e = Emit()
    vs = [['%s%d' % (v, i) for i in range(n)] for v, t, n in args]
    out = body(e, *vs)
    w('# ' + doc)
    w('def %s(%s) -> %s:' % (name, ', '.join('%s: %s' % (v, t) for v, t, n in args), ty_out))
    w('  match %s:' % ' '.join(v for v, t, n in args))
    w('    case %s:' % ' '.join('%s{%s}' % (t.split('.')[-1] if not t.startswith('FE.') else t, fields(v, n)) for v, t, n in args))
    OUT.extend(e.lines)
    w('      ' + rec(ty_out, out))
    w('')


stage('carry32c', 'L.carry(32n, xs, 0n) of the 31 columns of a product: 32 limbs and the carry', [('x', 'FE.W31', 31)], 'W33', lambda e, xs: carry(e, xs, 32))
stage('foldu', 'lo + c hi for the first 16 limbs lo and the rest hi (smod.foldu)', [('c', 'W9', 9), ('x', 'W33', 33)], 'W25',
      lambda e, cs, xs: ladd(xs[:16], convu(xs[16:], cs)))
stage('carry32f', 'L.carry(32n, xs, 0n) of a fold', [('x', 'W25', 25)], 'W33', lambda e, xs: carry(e, xs, 32))
stage('take16', 'the first 16 limbs (L.take(16n, xs))', [('x', 'W33', 33)], 'FE.FE', lambda e, xs: xs[:16])


def canonu(e, cs, ts):
    u = carry(e, ladd(ts, cs), 32)
    f = e.let('f', horner(u[16:]))
    return ['Nat.add(%s, %s)' % (nmul(u[i], f), nmul(ts[i], 'Nat.sub(1n, %s)' % f)) for i in range(16)]


stage('canonu', 't mod n for t below 2^256: t + c has bit 256 set exactly when t >= n (smod.canonu)', [('c', 'W9', 9), ('t', 'FE.FE', 16)], 'FE.FE', canonu)

w('''# one fold of the high half and its carry pass (L.rounds' step)
def round(+c: W9, r: W33) -> W33:
  carry32f(foldu(c, r))

# x mod n for the 31 columns x of a product (L.reduce(c, 4n, xs))
def red(+c: W9, x: FE.W31) -> FE.FE:
  canonu(c, take16(round(c, round(c, round(c, round(c, carry32c(x)))))))

def mul(a: FE.FE, b: FE.FE) -> FE.FE:
  red(cn(), FE.cols(a, b))

def sq(a: FE.FE) -> FE.FE:
  red(cn(), FE.sqcols(a))

# x^e for the exponent e given by its bits, most significant first
# (square-and-multiply; the branch is on the public exponent)
def pow_step(b: Nat, +x: FE.FE, s: FE.FE) -> FE.FE:
  match b:
    case 0n: s
    case 1n+k: mul(s, x)

def pow_go(+x: FE.FE, bits: List<&2, Nat>, acc: FE.FE) -> FE.FE:
  match bits:
    case Nil{}: acc
    case b <> t: pow_go(x, t, pow_step(b, x, sq(acc)))

def one() -> FE.FE:
  FE.one()
''')
(ROOT / 'src/crypto/secp256k1/se.bend').write_text('\n'.join(OUT) + '\n')

BR = []
b = BR.append
b('''# GENERATED by tools/generators/secp256k1_se.py; edit the generator.
import Base
import ../../../src/crypto/secp256k1/limbs.bend as L
import ../../../src/crypto/secp256k1/fe.bend as FE
import ../../../src/crypto/secp256k1/se.bend as S
import ./fmod.bend as M
import ./febr.bend as FB
import ./smod.bend as SM

# Each stage of src/crypto/secp256k1/se.bend is its list model of
# smod.bend on the record's fields (normalization, the fields unknown).
''')
for ty, n in (('W9', 9), ('W25', 25), ('W33', 33)):
    b('def l%d(r: S.%s) -> List<&2, Nat>:' % (n, ty))
    b('  match r:')
    b('    case S.%s{%s}:' % (ty, fields('x', n, False)))
    b('      [%s]' % fields('x', n, False))
    b('')
NS = {'FE.FE': 16, 'FE.W31': 31, 'S.W9': 9, 'S.W25': 25, 'S.W33': 33}


def bridge(name, args, lhs, rhs):
    b('def %s(%s) -> {%s == %s : List<&2, Nat>}:' % (name, ', '.join('%s: %s' % (a, t) for a, t in args), lhs, rhs))
    b('  match %s:' % ' '.join(a for a, t in args))
    b('    case %s:' % ' '.join('%s{%s}' % (t, fields(a + '_', NS[t])) for a, t in args))
    b('      {==}')
    b('')


bridge('carry32c_b', [('r', 'FE.W31')], 'l33(S.carry32c(r))', 'L.carry(32n, FB.l31(r), 0n)')
bridge('foldu_b', [('c', 'S.W9'), ('r', 'S.W33')], 'l25(S.foldu(c, r))', 'SM.foldu(l9(c), l33(r))')
bridge('carry32f_b', [('r', 'S.W25')], 'l33(S.carry32f(r))', 'L.carry(32n, l25(r), 0n)')
bridge('take16_b', [('r', 'S.W33')], 'FE.to_list(S.take16(r))', 'L.take(16n, l33(r))')
bridge('canonu_b', [('c', 'S.W9'), ('t', 'FE.FE')], 'FE.to_list(S.canonu(c, t))', 'SM.canonu(l9(c), FE.to_list(t))')
(ROOT / 'proofs/crypto/secp256k1/sebr.bend').write_text('\n'.join(BR) + '\n')
print('wrote src/crypto/secp256k1/se.bend, proofs/crypto/secp256k1/sebr.bend')
