#!/usr/bin/env python3
"""Write tools/generators/secp256k1_hand/pwin.src: the proofs of the 4-bit
fixed-window scalar multiplication of src/crypto/secp256k1/pt.bend (tab,
tsel, wgo, wmul) from the group law (proofs/crypto/secp256k1/group/).

  python3 tools/generators/secp256k1_win.py
  python3 tools/generators/rw.py tools/generators/secp256k1_hand/pwin.src proofs/crypto/secp256k1/pwin.bend

The statement: for a point a of the group and bits of a multiple of 4 bits,
wmul(bits, a) is a point of the group, equivalent (the same projective
point) to [v] a, v the number the bits spell. The facts hp (p is prime) and
hc (-7 is no cube) of the group law are hypotheses, discharged by the
closing roots.
"""
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
P = 'FS.prime(one)'
HYP0 = '+one: Nat, +h1: {one == 1n : Nat}'
HYP = '+one: Nat, +h1: {one == 1n : Nat}, +hp: NP.Prime(FS.prime(one)), +hc: {Nat.is_eq(FS.mpow(FS.prime(one), Nat.sub(FS.prime(one), 7n), Nat.div(Nat.sub(FS.prime(one), 1n), 3n)), 1n) == False{} : Bool}'
ARG = 'one, h1, hp, hc'


def eq(a, b):
    return '{GS.equiv(%s, %s, %s) == True{} : Bool}' % (P, a, b)


def vd(a):
    return '{GS.valid(%s, %s) == True{} : Bool}' % (P, a)


def pd(a):
    return '{PP.pred(one, %s) == True{} : Bool}' % a


def pdbl(x, n=1):
    for _ in range(n):
        x = 'CV.pdbl(%s, %s)' % (P, x)
    return x


def xdbl(x, n=1):
    for _ in range(n):
        x = 'PX.dbl(%s)' % x
    return x


def ndbl(x, n=1):
    for _ in range(n):
        x = 'Nat.double(%s)' % x
    return x


def padd(a, b):
    return 'CV.padd(%s, %s, %s)' % (P, a, b)


def smul(k, a):
    return 'GS.smul(%s, %s, %s)' % (P, k, a)


def tree(leaf, node, bits=('b4', 'b3', 'b2', 'b1')):
    cur = [leaf(i) for i in range(16)]
    for b in bits:
        cur = [node(b, cur[2 * j + 1], cur[2 * j]) for j in range(len(cur) // 2)]
    return cur[0]


o = []
a = o.append
a('''import Base
import ../../../spec/lib/common.bend as C
import ../../../spec/crypto/secp256k1/field.bend as FS
import ../../../spec/crypto/secp256k1/curve.bend as CV
import ../../../spec/crypto/secp256k1/group.bend as GS
import ../../../src/crypto/secp256k1/pt.bend as PX
import ../../lib/logic.bend as Lg
import ./lite/lib/nat.bend as N
import ./lite/lib/lemmas/proofs/nat_algebra.bend as NA
import ./lite/math/number/nt_prime.bend as NP
import ./lite/crypto/secp256k1/group/glawp.bend as GP
import ./lite/crypto/secp256k1/group/glaw4.bend as G4
import ./bitsv.bend as BV
import ./ptp.bend as PP
import ./ptm.bend as PM

# GENERATED by tools/generators/secp256k1_win.py; edit the generator.
#
# The 4-bit fixed-window multiplication of src/crypto/secp256k1/pt.bend
# (tab, tsel, wgo, wmul) on the group of spec/crypto/secp256k1/group.bend:
# for a point a of the group, wmul(bits, a) is a point of the group and the
# same projective point as [v] a, v the number the bits spell (G4.bvl). hp
# (p is prime) and hc (-7 is no cube modulo p) are the hypotheses of the
# group law, discharged by the closing roots.

# ---- on the specification's points ----
''')

a('''def dbl_vd(%(H)s, +r: CV.SPoint, +vr: %(vr)s) -> %(vdr)s:
  %%rw GP.group_double(%(A)s, r, vr)
  GP.group_closed(%(A)s, r, r, vr, vr)

# R is [v] A: 2 R is [2 v] A
def dbl_e(%(H)s, +a: CV.SPoint, +r: CV.SPoint, +v: Nat, +va: %(va)s, +vr: %(vr)s, +hr: %(hr)s) -> %(concl)s:
  +s = %(s)s
  +vs = GP.scalar_closed(%(A)s, v, a, va)
  %%rw GP.group_double(%(A)s, r, vr)
  %%rw NA.double_self(v)
  GP.equiv_trans(%(A)s, %(rr)s, %(ss)s, %(svv)s, GP.group_closed(%(A)s, s, s, vs, vs), GP.equiv_trans(%(A)s, %(rr)s, %(sr)s, %(ss)s, GP.group_closed(%(A)s, s, r, vs, vr), GP.equiv_add_left(%(A)s, r, s, r, vr, vs, hr), GP.equiv_add_right(%(A)s, s, r, s, vr, vs, hr)), GP.equiv_sym(%(A)s, %(svv)s, %(ss)s, GP.scalar_add(%(A)s, v, v, a, va)))
''' % dict(H=HYP, A=ARG, vr=vd('r'), vdr=vd(pdbl('r')), va=vd('a'), hr=eq('r', smul('v', 'a')),
           concl=eq(pdbl('r'), smul('Nat.double(v)', 'a')), s=smul('v', 'a'), rr=padd('r', 'r'), ss=padd('s', 's'),
           sr=padd('s', 'r'), svv=smul('Nat.add(v, v)', 'a')))

a('''def dbl4_vd(%(H)s, +r: CV.SPoint, +vr: %(vr)s) -> %(vd4)s:
  dbl_vd(%(A)s, %(r3)s, dbl_vd(%(A)s, %(r2)s, dbl_vd(%(A)s, %(r1)s, dbl_vd(%(A)s, r, vr))))

# R is [v] A: 16 R is [16 v] A
def dbl4_e(%(H)s, +a: CV.SPoint, +r: CV.SPoint, +v: Nat, +va: %(va)s, +vr: %(vr)s, +hr: %(hr)s) -> %(concl)s:
  +v1 = dbl_vd(%(A)s, r, vr)
  +v2 = dbl_vd(%(A)s, %(r1)s, v1)
  +v3 = dbl_vd(%(A)s, %(r2)s, v2)
  +e1 = dbl_e(%(A)s, a, r, v, va, vr, hr)
  +e2 = dbl_e(%(A)s, a, %(r1)s, Nat.double(v), va, v1, e1)
  +e3 = dbl_e(%(A)s, a, %(r2)s, %(n2)s, va, v2, e2)
  dbl_e(%(A)s, a, %(r3)s, %(n3)s, va, v3, e3)

def comm_e(%(H)s, +a: CV.SPoint, +d: Nat, +k: Nat, +va: %(va)s) -> %(ce)s:
  %%rw GP.group_commutative(%(A)s, %(sk)s, %(sd)s)
  GP.equiv_sym(%(A)s, %(sdk)s, %(pdk)s, GP.scalar_add(%(A)s, d, k, a, va))

# R is [v] A: 16 R + [d] A is [d + 16 v] A
def wstep_e(%(H)s, +a: CV.SPoint, +r: CV.SPoint, +v: Nat, +d: Nat, +va: %(va)s, +vr: %(vr)s, +hr: %(hr)s) -> %(we)s:
  +r4 = %(r4)s
  +k = %(n4)s
  +sd = %(sd)s
  +sk = %(sk)s
  +v4 = dbl4_vd(%(A)s, r, vr)
  +vsd = GP.scalar_closed(%(A)s, d, a, va)
  +vsk = GP.scalar_closed(%(A)s, k, a, va)
  GP.equiv_trans(%(A)s, %(p1)s, %(p2)s, %(sdk)s, GP.group_closed(%(A)s, sk, sd, vsk, vsd), GP.equiv_add_left(%(A)s, r4, sk, sd, v4, vsk, dbl4_e(%(A)s, a, r, v, va, vr, hr)), comm_e(%(A)s, a, d, k, va))

def wstep_vd(%(H)s, +a: CV.SPoint, +r: CV.SPoint, +d: Nat, +va: %(va)s, +vr: %(vr)s) -> %(wv)s:
  GP.group_closed(%(A)s, %(r4)s, %(sd)s, dbl4_vd(%(A)s, r, vr), GP.scalar_closed(%(A)s, d, a, va))
''' % dict(H=HYP, A=ARG, vr=vd('r'), va=vd('a'), hr=eq('r', smul('v', 'a')), vd4=vd(pdbl('r', 4)),
           r1=pdbl('r', 1), r2=pdbl('r', 2), r3=pdbl('r', 3), r4=pdbl('r', 4), n2=ndbl('v', 2), n3=ndbl('v', 3), n4=ndbl('v', 4),
           concl=eq(pdbl('r', 4), smul(ndbl('v', 4), 'a')),
           ce=eq(padd(smul('k', 'a'), smul('d', 'a')), smul('Nat.add(d, k)', 'a')), sk=smul('k', 'a'), sd=smul('d', 'a'),
           sdk=smul('Nat.add(d, k)', 'a'), pdk=padd(smul('d', 'a'), smul('k', 'a')),
           we=eq(padd(pdbl('r', 4), smul('d', 'a')), smul('Nat.add(d, %s)' % ndbl('v', 4), 'a')),
           p1=padd('r4', 'sd'), p2=padd('sk', 'sd'), wv=vd(padd(pdbl('r', 4), smul('d', 'a')))))

# ---- the table ----
T = lambda i: 'tabp(%dn, a)' % i
a('''# ---- the table: entry i is i additions of a, [i] a exactly ----

def tabp(i: Nat, +a: PX.PT) -> PX.PT:
  match i:
    case 0n: PX.infinity()
    case 1n+j: PX.add(tabp(j, a), a)

def tabp_r(+one: Nat, +h1: {one == 1n : Nat}, i: Nat, +a: PX.PT, +ha: %(pa)s) -> %(pt)s:
  match i:
    case 0n:
      PM.pinf_r(one, h1)
    case 1n+ +j:
      PP.padd_r(one, h1, tabp(j, a), a, tabp_r(one, h1, j, a, ha), ha)

def tabp_v(+one: Nat, +h1: {one == 1n : Nat}, i: Nat, +a: PX.PT, +ha: %(pa)s) -> {PP.pv(one, tabp(i, a)) == %(sm)s : CV.SPoint}:
  match i:
    case 0n:
      PM.pinf_v(one, h1)
    case 1n+ +j:
      %%goal {PP.pv(one, PX.add(tabp(j, a), a)) == %(step)s : CV.SPoint}
      %%rw PP.padd_v(one, h1, tabp(j, a), a, tabp_r(one, h1, j, a, ha), ha)
      %%rw tabp_v(one, h1, j, a, ha)
      %%close

def tabp_vd(%(H)s, +i: Nat, +a: PX.PT, +ha: %(pa)s, +va: %(vpa)s) -> %(vt)s:
  %%rw tabp_v(one, h1, i, a, ha)
  GP.scalar_closed(%(A)s, i, PP.pv(one, a), va)

# ---- the selection: a tree of picks (PX.pick, the branch the public
# selection of pt.bend uses) ----

def sel_pick(+one: Nat, +h1: {one == 1n : Nat}, b: Nat, +x: PX.PT, +y: PX.PT, +hb: {Nat.is_lt(b, 2n) == True{} : Bool}, +hx: %(px)s, +hy: %(py)s) -> {PX.select(b, x, y) == pick(b, x, y) : PX.PT}:
  match b:
    case 0n:
      PM.psel0(one, h1, x, y, hx, hy)
    case 1n:
      PM.psel1(one, h1, x, y, hx, hy)
    case 2n+ +k:
      Empty.absurd({PX.select(2n+k, x, y) == pick(2n+k, x, y) : PX.PT}, N.lt_zero_absurd(k, hb))

def pick_r(+one: Nat, b: Nat, +x: PX.PT, +y: PX.PT, +hx: %(px)s, +hy: %(py)s) -> %(ppick)s:
  match b:
    case 0n:
      hy
    case 1n+k:
      hx

def pick_vd(+one: Nat, b: Nat, +x: PX.PT, +y: PX.PT, +hx: %(vx)s, +hy: %(vy)s) -> %(vpick)s:
  match b:
    case 0n:
      hy
    case 1n+k:
      hx
''' % dict(H=HYP, A=ARG, pa=pd('a'), pt=pd('tabp(i, a)'), sm=smul('i', 'PP.pv(one, a)'),
           step=padd(smul('j', 'PP.pv(one, a)'), 'PP.pv(one, a)'), vpa=vd('PP.pv(one, a)'), vt=vd('PP.pv(one, tabp(i, a))'),
           px=pd('x'), py=pd('y'), ppick=pd('pick(b, x, y)'), vx=vd('PP.pv(one, x)'), vy=vd('PP.pv(one, y)'),
           vpick=vd('PP.pv(one, pick(b, x, y))')))

pk = lambda b, x, y: 'pick(%s, %s, %s)' % (b, x, y)
sl = lambda b, x, y: 'PX.select(%s, %s, %s)' % (b, x, y)
a('def tpk(+b1: Nat, +b2: Nat, +b3: Nat, +b4: Nat, +a: PX.PT) -> PX.PT:\n  %s\n' % tree(T, pk))

# pred and valid of the pick tree, and tsel(tab) == tpk
tr = lambda i: 'tabp_r(one, h1, %dn, a, ha)' % i
tv = lambda i: 'tabp_vd(%s, %dn, a, ha, va)' % (ARG, i)


def tree2(leaf, leafp, nodep, bits=('b4', 'b3', 'b2', 'b1')):
    """(term, proof) up the tree"""
    cur = [(leaf(i), leafp(i)) for i in range(16)]
    for b in bits:
        cur = [(pk(b, cur[2 * j + 1][0], cur[2 * j][0]), nodep(b, cur[2 * j + 1], cur[2 * j])) for j in range(len(cur) // 2)]
    return cur[0]


_, prf_r = tree2(T, tr, lambda b, x, y: 'pick_r(one, %s, %s, %s, %s, %s)' % (b, x[0], y[0], x[1], y[1]))
_, prf_v = tree2(T, tv, lambda b, x, y: 'pick_vd(one, %s, %s, %s, %s, %s)' % (b, x[0], y[0], x[1], y[1]))
BH = '+b1: Nat, +b2: Nat, +b3: Nat, +b4: Nat'
a('def tpk_r(+one: Nat, +h1: {one == 1n : Nat}, %s, +a: PX.PT, +ha: %s) -> %s:\n  %s\n' % (BH, pd('a'), pd('tpk(b1, b2, b3, b4, a)'), prf_r))
a('def tpk_vd(%s, %s, +a: PX.PT, +ha: %s, +va: %s) -> %s:\n  %s\n' % (HYP, BH, pd('a'), vd('PP.pv(one, a)'), vd('PP.pv(one, tpk(b1, b2, b3, b4, a))'), prf_v))

# tsel(tab(a)) == tpk: rewrite the selections level by level
HB = ', '.join('+hb%d: {Nat.is_lt(b%d, 2n) == True{} : Bool}' % (i, i) for i in (1, 2, 3, 4))
lines = ['def tsel_tab(+one: Nat, +h1: {one == 1n : Nat}, %s, %s, +a: PX.PT, +ha: %s) -> {PX.tsel(b1, b2, b3, b4, PX.tab(a)) == tpk(b1, b2, b3, b4, a) : PX.PT}:' % (BH, HB, pd('a'))]
lines.append('  %%goal {%s == %s : PX.PT}' % (tree(T, sl), tree(T, pk)))
cur = [(T(i), tr(i)) for i in range(16)]
for b in ('b4', 'b3', 'b2', 'b1'):
    nxt = []
    for j in range(len(cur) // 2):
        x, y = cur[2 * j + 1], cur[2 * j]
        lines.append('  %%rw sel_pick(one, h1, %s, %s, %s, h%s, %s, %s)' % (b, x[0], y[0], b, x[1], y[1]))
        nxt.append((pk(b, x[0], y[0]), 'pick_r(one, %s, %s, %s, %s, %s)' % (b, x[0], y[0], x[1], y[1])))
    cur = nxt
lines.append('  %close')
a('\n'.join(lines) + '\n')

# ---- one window ----
D4R = xdbl('r', 4)
a('''# ---- one window: 16 r + [k] a for the table entry k ----

def d4_r(+one: Nat, +h1: {one == 1n : Nat}, +r: PX.PT, +hr: %(pr)s) -> %(pd4)s:
  PP.pdbl_r(one, h1, %(x3)s, PP.pdbl_r(one, h1, %(x2)s, PP.pdbl_r(one, h1, %(x1)s, PP.pdbl_r(one, h1, r, hr))))

def d4_v(+one: Nat, +h1: {one == 1n : Nat}, +r: PX.PT, +hr: %(pr)s) -> {PP.pv(one, %(x4)s) == %(s4)s : CV.SPoint}:
  +q1 = PP.pdbl_r(one, h1, r, hr)
  +q2 = PP.pdbl_r(one, h1, %(x1)s, q1)
  +q3 = PP.pdbl_r(one, h1, %(x2)s, q2)
  %%rw PP.pdbl_v(one, h1, %(x3)s, q3)
  %%rw PP.pdbl_v(one, h1, %(x2)s, q2)
  %%rw PP.pdbl_v(one, h1, %(x1)s, q1)
  %%rw PP.pdbl_v(one, h1, r, hr)
  %%close

def wk_e(%(H)s, +a: PX.PT, +r: PX.PT, +v: Nat, +k: Nat, +ha: %(pa)s, +va: %(vpa)s, +hr: %(pr)s, +vr: %(vpr)s, +he: %(he)s) -> %(concl)s:
  %%rw PP.padd_v(one, h1, %(x4)s, tabp(k, a), d4_r(one, h1, r, hr), tabp_r(one, h1, k, a, ha))
  %%rw d4_v(one, h1, r, hr)
  %%rw tabp_v(one, h1, k, a, ha)
  wstep_e(%(A)s, PP.pv(one, a), PP.pv(one, r), v, k, va, vr, he)
''' % dict(H=HYP, A=ARG, pr=pd('r'), pd4=pd(D4R), x1=xdbl('r', 1), x2=xdbl('r', 2), x3=xdbl('r', 3), x4=D4R,
           s4=pdbl('PP.pv(one, r)', 4), pa=pd('a'), vpa=vd('PP.pv(one, a)'), vpr=vd('PP.pv(one, r)'),
           he=eq('PP.pv(one, r)', smul('v', 'PP.pv(one, a)')),
           concl=eq('PP.pv(one, PX.add(%s, tabp(k, a)))' % D4R, smul('Nat.add(k, %s)' % ndbl('v', 4), 'PP.pv(one, a)'))))

# the case tree over the four bits (deepest first)
CH = '+a: PX.PT, +r: PX.PT, +v: Nat, +ha: %s, +va: %s, +hr: %s, +vr: %s, +he: %s' % (pd('a'), vd('PP.pv(one, a)'), pd('r'), vd('PP.pv(one, r)'), eq('PP.pv(one, r)', smul('v', 'PP.pv(one, a)')))
CA = 'a, r, v, ha, va, hr, vr, he'


def nxt4(bs, v='v'):
    x = v
    for b in bs:
        x = 'G4.nxt(%s, %s)' % (b, x)
    return x


def lit(b):
    return '%dn' % b if isinstance(b, int) else b


for depth in (3, 2, 1, 0):
    for pre in range(1 << depth):
        pb = [(pre >> (depth - 1 - i)) & 1 for i in range(depth)]
        rest = ['b%d' % (i + 1) for i in range(depth, 4)]
        allb = pb + rest
        name = 'wt' + ''.join(map(str, pb))
        bparams = ', '.join('%s: Nat, +h%s: {Nat.is_lt(%s, 2n) == True{} : Bool}' % (b, b, b) for b in rest)
        ty = lambda bs: eq('PP.pv(one, PX.add(%s, tpk(%s, a)))' % (D4R, ', '.join(lit(b) for b in bs)), smul(nxt4([lit(b) for b in bs]), 'PP.pv(one, a)'))
        b0 = rest[0]
        ls = ['def %s(%s, %s, %s) -> %s:' % (name, HYP, CH, bparams, ty(allb)), '  match %s:' % b0]
        for val in (0, 1):
            child = pb + [val]
            cargs = ', '.join('%s, h%s' % (b, b) for b in rest[1:])
            if len(child) == 4:
                k = child[0] * 8 + child[1] * 4 + child[2] * 2 + child[3]
                call = 'wk_e(%s, a, r, v, %dn, ha, va, hr, vr, he)' % (ARG, k)
            else:
                call = 'wt%s(%s, %s%s)' % (''.join(map(str, child)), ARG, CA, ', ' + cargs if cargs else '')
            ls += ['    case %dn:' % val, '      ' + call]
        bad = [('2n+k' if b == b0 else b) for b in allb]
        ls += ['    case 2n+ +k:', '      Empty.absurd(%s, N.lt_zero_absurd(k, h%s))' % (ty(bad), b0)]
        a('\n'.join(ls) + '\n')

BB = 'b1: Nat, b2: Nat, b3: Nat, b4: Nat'
STEP = 'PX.add(%s, PX.tsel(b1, b2, b3, b4, PX.tab(a)))' % D4R
a('''# the step of the code
def wst_e(%(H)s, %(CH)s, +b1: Nat, +b2: Nat, +b3: Nat, +b4: Nat, %(HB)s) -> %(concl)s:
  %%rw tsel_tab(one, h1, b1, b2, b3, b4, hb1, hb2, hb3, hb4, a, ha)
  wt(%(A)s, %(CA)s, b1, hb1, b2, hb2, b3, hb3, b4, hb4)

def wst_r(+one: Nat, +h1: {one == 1n : Nat}, +a: PX.PT, +r: PX.PT, +ha: %(pa)s, +hr: %(pr)s, +b1: Nat, +b2: Nat, +b3: Nat, +b4: Nat, %(HB)s) -> %(cr)s:
  %%rw tsel_tab(one, h1, b1, b2, b3, b4, hb1, hb2, hb3, hb4, a, ha)
  PP.padd_r(one, h1, %(x4)s, tpk(b1, b2, b3, b4, a), d4_r(one, h1, r, hr), tpk_r(one, h1, b1, b2, b3, b4, a, ha))

def wst_vd(%(H)s, +a: PX.PT, +r: PX.PT, +ha: %(pa)s, +va: %(vpa)s, +hr: %(pr)s, +vr: %(vpr)s, +b1: Nat, +b2: Nat, +b3: Nat, +b4: Nat, %(HB)s) -> %(cv)s:
  %%rw tsel_tab(one, h1, b1, b2, b3, b4, hb1, hb2, hb3, hb4, a, ha)
  %%rw PP.padd_v(one, h1, %(x4)s, tpk(b1, b2, b3, b4, a), d4_r(one, h1, r, hr), tpk_r(one, h1, b1, b2, b3, b4, a, ha))
  %%rw d4_v(one, h1, r, hr)
  GP.group_closed(%(A)s, %(s4)s, PP.pv(one, tpk(b1, b2, b3, b4, a)), dbl4_vd(%(A)s, PP.pv(one, r), vr), tpk_vd(%(A)s, b1, b2, b3, b4, a, ha, va))
''' % dict(H=HYP, A=ARG, CH=CH, CA=CA, HB=HB, pa=pd('a'), pr=pd('r'), vpa=vd('PP.pv(one, a)'), vpr=vd('PP.pv(one, r)'), x4=D4R,
           s4=pdbl('PP.pv(one, r)', 4),
           concl=eq('PP.pv(one, %s)' % STEP, smul(nxt4(['b1', 'b2', 'b3', 'b4']), 'PP.pv(one, a)')),
           cr=pd(STEP), cv=vd('PP.pv(one, %s)' % STEP)))

# ---- the loop ----
SPLIT = '''      +c1 = Lg.and_right(Nat.is_lt(b1, 2n), BV.all01(b2 <> b3 <> b4 <> t), hb)
      +c2 = Lg.and_right(Nat.is_lt(b2, 2n), BV.all01(b3 <> b4 <> t), c1)
      +c3 = Lg.and_right(Nat.is_lt(b3, 2n), BV.all01(b4 <> t), c2)
      +hb1 = Lg.and_left(Nat.is_lt(b1, 2n), BV.all01(b2 <> b3 <> b4 <> t), hb)
      +hb2 = Lg.and_left(Nat.is_lt(b2, 2n), BV.all01(b3 <> b4 <> t), c1)
      +hb3 = Lg.and_left(Nat.is_lt(b3, 2n), BV.all01(b4 <> t), c2)
      +hb4 = Lg.and_left(Nat.is_lt(b4, 2n), BV.all01(t), c3)
      +hbt = Lg.and_right(Nat.is_lt(b4, 2n), BV.all01(t), c3)'''
STEPT = 'PX.add(%s, PX.tsel(b1, b2, b3, b4, PX.tab(a)))' % D4R


def loop(name, extra_h, concl, base, rec, absurd_ty, hyp=None):
    ls = ['def %s(%s, bs: List<&2, Nat>, +a: PX.PT, +r: PX.PT%s, +hb: {BV.all01(bs) == True{} : Bool}, +hq: {ok4(bs) == True{} : Bool}) -> %s:' % (name, hyp or HYP, extra_h, concl('bs', 'r', 'v')),
          '  match bs:', '    case Nil{}:', '      ' + base]
    for pat, lst in (('+b1 <> Nil{}', '[b1]'), ('+b1 <> +b2 <> Nil{}', '[b1, b2]'), ('+b1 <> +b2 <> +b3 <> Nil{}', '[b1, b2, b3]')):
        ls += ['    case %s:' % pat, '      Empty.absurd(%s, Lg.false_true(hq))' % absurd_ty(lst)]
    ls += ['    case +b1 <> +b2 <> +b3 <> +b4 <> +t:', SPLIT, rec]
    return '\n'.join(ls) + '\n'


a('''# ---- the loop over the windows ----

# a multiple of 4 bits
def ok4(xs: List<&2, Nat>) -> Bool:
  match xs:
    case Nil{}: True{}
    case b1 <> Nil{}: False{}
    case b1 <> b2 <> Nil{}: False{}
    case b1 <> b2 <> b3 <> Nil{}: False{}
    case b1 <> b2 <> b3 <> b4 <> t: ok4(t)
''')
PA = ', +ha: %s, +hr: %s' % (pd('a'), pd('r'))
a(loop('wgo_r', PA, lambda bs, r, v: pd('PX.wgo(%s, PX.tab(a), %s)' % (bs, r)), 'hr',
       '      wgo_r(one, h1, t, a, %s, ha, wst_r(one, h1, a, r, ha, hr, b1, b2, b3, b4, hb1, hb2, hb3, hb4), hbt, hq)' % STEPT,
       lambda lst: pd('PX.wgo(%s, PX.tab(a), r)' % lst), HYP0))
PV = ', +ha: %s, +va: %s, +hr: %s, +vr: %s' % (pd('a'), vd('PP.pv(one, a)'), pd('r'), vd('PP.pv(one, r)'))
a(loop('wgo_vd', PV, lambda bs, r, v: vd('PP.pv(one, PX.wgo(%s, PX.tab(a), %s))' % (bs, r)), 'vr',
       '      wgo_vd(%s, t, a, %s, ha, va, wst_r(one, h1, a, r, ha, hr, b1, b2, b3, b4, hb1, hb2, hb3, hb4), wst_vd(%s, a, r, ha, va, hr, vr, b1, b2, b3, b4, hb1, hb2, hb3, hb4), hbt, hq)' % (ARG, STEPT, ARG),
       lambda lst: vd('PP.pv(one, PX.wgo(%s, PX.tab(a), r))' % lst)))
PE = ', +v: Nat' + PV + ', +he: %s' % eq('PP.pv(one, r)', smul('v', 'PP.pv(one, a)'))
ce = lambda bs, r, v: eq('PP.pv(one, PX.wgo(%s, PX.tab(a), %s))' % (bs, r), smul('G4.bvl(%s, %s)' % (bs, v), 'PP.pv(one, a)'))
a(loop('wgo_e', PE, ce, 'he',
       '      wgo_e(%s, t, a, %s, %s, ha, va, wst_r(one, h1, a, r, ha, hr, b1, b2, b3, b4, hb1, hb2, hb3, hb4), wst_vd(%s, a, r, ha, va, hr, vr, b1, b2, b3, b4, hb1, hb2, hb3, hb4), wst_e(%s, %s, b1, b2, b3, b4, hb1, hb2, hb3, hb4), hbt, hq)' % (ARG, STEPT, nxt4(['b1', 'b2', 'b3', 'b4']), ARG, ARG, CA),
       lambda lst: ce(lst, 'r', 'v')))

# ---- wmul ----
INF_E = eq('PP.pv(one, PX.infinity())', smul('0n', 'PP.pv(one, a)'))
a('''# ---- [k] a ----

def inf_vd(%(H)s) -> %(vinf)s:
  %%rw PM.pinf_v(one, h1)
  GP.group_infinity(%(A)s)

def inf_e(%(H)s, +a: PX.PT) -> %(infe)s:
  %%rw PM.pinf_v(one, h1)
  GP.equiv_refl(%(A)s, CV.infinity())

def wmul_r(+one: Nat, +h1: {one == 1n : Nat}, bs: List<&2, Nat>, +a: PX.PT, +ha: %(pa)s, +hb: {BV.all01(bs) == True{} : Bool}, +hq: {ok4(bs) == True{} : Bool}) -> %(cr)s:
  match bs:
    case Nil{}:
      PM.pinf_r(one, h1)
    case +b <> +t:
      wgo_r(one, h1, b <> t, a, PX.infinity(), ha, PM.pinf_r(one, h1), hb, hq)

def wmul_vd(%(H)s, bs: List<&2, Nat>, +a: PX.PT, +ha: %(pa)s, +va: %(vpa)s, +hb: {BV.all01(bs) == True{} : Bool}, +hq: {ok4(bs) == True{} : Bool}) -> %(cv)s:
  match bs:
    case Nil{}:
      inf_vd(%(A)s)
    case +b <> +t:
      wgo_vd(%(A)s, b <> t, a, PX.infinity(), ha, va, PM.pinf_r(one, h1), inf_vd(%(A)s), hb, hq)

# wmul(bits, a) is [v] a for the number v of the bits
def wmul_e(%(H)s, bs: List<&2, Nat>, +a: PX.PT, +ha: %(pa)s, +va: %(vpa)s, +hb: {BV.all01(bs) == True{} : Bool}, +hq: {ok4(bs) == True{} : Bool}) -> %(ce)s:
  match bs:
    case Nil{}:
      inf_e(%(A)s, a)
    case +b <> +t:
      wgo_e(%(A)s, b <> t, a, PX.infinity(), 0n, ha, va, PM.pinf_r(one, h1), inf_vd(%(A)s), inf_e(%(A)s, a), hb, hq)
''' % dict(H=HYP, A=ARG, vinf=vd('PP.pv(one, PX.infinity())'), infe=INF_E, pa=pd('a'), vpa=vd('PP.pv(one, a)'),
           cr=pd('PX.wmul(bs, a)'), cv=vd('PP.pv(one, PX.wmul(bs, a))'),
           ce=eq('PP.pv(one, PX.wmul(bs, a))', smul('G4.bvl(bs, 0n)', 'PP.pv(one, a)'))))

# ---- two scalars on one chain of doublings (pt.bend tpick, sgo, smul2) ----
#
# The invariant of the loop: r is [v] A + [w] B (J(v, w) below) for the
# numbers v and w the bits read so far spell.

def J(v, w, A='A', B='B'):
    return padd(smul(v, A), smul(w, B))


def trans(a, b, c, vb, hab, hbc):
    return 'GP.equiv_trans(%s, %s, %s, %s, %s, %s, %s)' % (ARG, a, b, c, vb, hab, hbc)


def cl(a, b, va, vb):
    return 'GP.group_closed(%s, %s, %s, %s, %s)' % (ARG, a, b, va, vb)


def sc(k, a, va):
    return 'GP.scalar_closed(%s, %s, %s, %s)' % (ARG, k, a, va)


def asc(a, b, c, va, vb, vc):
    return 'GP.group_associative(%s, %s, %s, %s, %s, %s, %s)' % (ARG, a, b, c, va, vb, vc)


def esym(a, b, h):
    return 'GP.equiv_sym(%s, %s, %s, %s)' % (ARG, a, b, h)


def eal(a, a2, b, va, va2, h):
    return 'GP.equiv_add_left(%s, %s, %s, %s, %s, %s, %s)' % (ARG, a, a2, b, va, va2, h)


def ear(a, b, b2, vb, vb2, h):
    return 'GP.equiv_add_right(%s, %s, %s, %s, %s, %s, %s)' % (ARG, a, b, b2, vb, vb2, h)


def comm_sub(a, b, c, lhs, rhs_of):
    """equiv(lhs, rhs_of(padd(c, b))) from lhs = rhs_of(padd(b, c)): the
    commutativity of the group (an equation) under a context"""
    return 'Lg.subst(CV.SPoint, t => %s, %s, %s, GP.group_commutative(%s, %s, %s), GP.equiv_refl(%s, %s))' % (
        eq(lhs, rhs_of('t')), padd(b, c), padd(c, b), ARG, b, c, ARG, lhs)


PT4 = '+a: CV.SPoint, +b: CV.SPoint, +c: CV.SPoint, +d: CV.SPoint, +va: %s, +vb: %s, +vc: %s, +vd: %s' % (vd('a'), vd('b'), vd('c'), vd('d'))
L0 = padd(padd('a', 'b'), padd('c', 'd'))
L1 = padd('a', padd('b', padd('c', 'd')))
L2 = padd('a', padd(padd('b', 'c'), 'd'))
L3 = padd('a', padd(padd('c', 'b'), 'd'))
L4 = padd('a', padd('c', padd('b', 'd')))
L5 = padd(padd('a', 'c'), padd('b', 'd'))
vcd = cl('c', 'd', 'vc', 'vd')
vbd = cl('b', 'd', 'vb', 'vd')
vbc = cl('b', 'c', 'vb', 'vc')
vcb = cl('c', 'b', 'vc', 'vb')
vL1 = cl('a', padd('b', padd('c', 'd')), 'va', cl('b', padd('c', 'd'), 'vb', vcd))
vL2 = cl('a', padd(padd('b', 'c'), 'd'), 'va', cl(padd('b', 'c'), 'd', vbc, 'vd'))
vL3 = cl('a', padd(padd('c', 'b'), 'd'), 'va', cl(padd('c', 'b'), 'd', vcb, 'vd'))
vL4 = cl('a', padd('c', padd('b', 'd')), 'va', cl('c', padd('b', 'd'), 'vc', vbd))
e01 = asc('a', 'b', padd('c', 'd'), 'va', 'vb', vcd)
e12 = ear('a', padd('b', padd('c', 'd')), padd(padd('b', 'c'), 'd'), cl('b', padd('c', 'd'), 'vb', vcd), cl(padd('b', 'c'), 'd', vbc, 'vd'),
          esym(padd(padd('b', 'c'), 'd'), padd('b', padd('c', 'd')), asc('b', 'c', 'd', 'vb', 'vc', 'vd')))
e23 = comm_sub('a', 'b', 'c', L2, lambda t: padd('a', padd(t, 'd')))
e34 = ear('a', padd(padd('c', 'b'), 'd'), padd('c', padd('b', 'd')), cl(padd('c', 'b'), 'd', vcb, 'vd'), cl('c', padd('b', 'd'), 'vc', vbd), asc('c', 'b', 'd', 'vc', 'vb', 'vd'))
e45 = esym(L5, L4, asc('a', 'c', padd('b', 'd'), 'va', 'vc', vbd))
a('''# ---- two scalars on one chain of doublings: [v] A + [w] B ----

# (a + b) + (c + d) = (a + c) + (b + d)
def x4(%s, %s) -> %s:
  %s
''' % (HYP, PT4, eq(L0, L5), trans(L0, L1, L5, vL1, e01, trans(L1, L2, L5, vL2, e12, trans(L2, L3, L5, vL3, e23, trans(L3, L4, L5, vL4, e34, e45))))))

AB = '+A: CV.SPoint, +B: CV.SPoint, +vA: %s, +vB: %s' % (vd('A'), vd('B'))
ABA = 'A, B, vA, vB'
sv, sw = smul('v', 'A'), smul('w', 'B')
vsv, vsw = sc('v', 'A', 'vA'), sc('w', 'B', 'vB')
vJ = cl(sv, sw, vsv, vsw)
a('''def jv(%s, %s, +v: Nat, +w: Nat) -> %s:
  %s
''' % (HYP, AB, vd(J('v', 'w')), vJ))

XH = '+x: CV.SPoint, +v: Nat, +w: Nat, +vx: %s, +hx: %s' % (vd('x'), eq('x', J('v', 'w')))
# x + [k] A: J(k + v, w)
sk = smul('k', 'A')
vsk = sc('k', 'A', 'vA')
M0 = padd('x', sk)
M1 = padd(J('v', 'w'), sk)
M2 = padd(sv, padd(sw, sk))
M3 = padd(sv, padd(sk, sw))
M4 = padd(padd(sv, sk), sw)
M5 = J('Nat.add(k, v)', 'w')
vM1 = cl(J('v', 'w'), sk, vJ, vsk)
vM2 = cl(sv, padd(sw, sk), vsv, cl(sw, sk, vsw, vsk))
vM3 = cl(sv, padd(sk, sw), vsv, cl(sk, sw, vsk, vsw))
vM4 = cl(padd(sv, sk), sw, cl(sv, sk, vsv, vsk), vsw)
f01 = eal('x', J('v', 'w'), sk, 'vx', vJ, 'hx')
f12 = asc(sv, sw, sk, vsv, vsw, vsk)
f23 = comm_sub(sv, sw, sk, M2, lambda t: padd(sv, t))
f34 = esym(M4, M3, asc(sv, sk, sw, vsv, vsk, vsw))
f45 = eal(padd(sv, sk), smul('Nat.add(k, v)', 'A'), sw, cl(sv, sk, vsv, vsk), sc('Nat.add(k, v)', 'A', 'vA'), 'comm_e(%s, A, k, v, vA)' % ARG)
a('''# x = J(v, w): x + [k] A = J(k + v, w)
def jl(%s, %s, %s, +k: Nat) -> %s:
  %s
''' % (HYP, AB, XH, eq(M0, M5), trans(M0, M1, M5, vM1, f01, trans(M1, M2, M5, vM2, f12, trans(M2, M3, M5, vM3, f23, trans(M3, M4, M5, vM4, f34, f45))))))

# x + [k] B: J(v, k + w)
skb = smul('k', 'B')
vskb = sc('k', 'B', 'vB')
N0 = padd('x', skb)
N1 = padd(J('v', 'w'), skb)
N2 = padd(sv, padd(sw, skb))
N3 = J('v', 'Nat.add(k, w)')
vN1 = cl(J('v', 'w'), skb, vJ, vskb)
vN2 = cl(sv, padd(sw, skb), vsv, cl(sw, skb, vsw, vskb))
g01 = eal('x', J('v', 'w'), skb, 'vx', vJ, 'hx')
g12 = asc(sv, sw, skb, vsv, vsw, vskb)
g23 = ear(sv, padd(sw, skb), smul('Nat.add(k, w)', 'B'), cl(sw, skb, vsw, vskb), sc('Nat.add(k, w)', 'B', 'vB'), 'comm_e(%s, B, k, w, vB)' % ARG)
a('''# x = J(v, w): x + [k] B = J(v, k + w)
def jr(%s, %s, %s, +k: Nat) -> %s:
  %s
''' % (HYP, AB, XH, eq(N0, N3), trans(N0, N1, N3, vN1, g01, trans(N1, N2, N3, vN2, g12, g23))))

# 2 x: J(2 v, 2 w)
Jvw = J('v', 'w')
D0 = padd('x', 'x')
D1 = padd(Jvw, 'x')
D2 = padd(Jvw, Jvw)
D3 = padd(padd(sv, sv), padd(sw, sw))
D4 = padd(smul('Nat.add(v, v)', 'A'), padd(sw, sw))
D5 = J('Nat.add(v, v)', 'Nat.add(w, w)')
vD1 = cl(Jvw, 'x', vJ, 'vx')
vD2 = cl(Jvw, Jvw, vJ, vJ)
vD3 = cl(padd(sv, sv), padd(sw, sw), cl(sv, sv, vsv, vsv), cl(sw, sw, vsw, vsw))
vD4 = cl(smul('Nat.add(v, v)', 'A'), padd(sw, sw), sc('Nat.add(v, v)', 'A', 'vA'), cl(sw, sw, vsw, vsw))
d01 = eal('x', Jvw, 'x', 'vx', vJ, 'hx')
d12 = ear(Jvw, 'x', Jvw, 'vx', vJ, 'hx')
d23 = 'x4(%s, %s, %s, %s, %s, %s, %s, %s, %s)' % (ARG, sv, sw, sv, sw, vsv, vsw, vsv, vsw)
d34 = eal(padd(sv, sv), smul('Nat.add(v, v)', 'A'), padd(sw, sw), cl(sv, sv, vsv, vsv), sc('Nat.add(v, v)', 'A', 'vA'),
          esym(smul('Nat.add(v, v)', 'A'), padd(sv, sv), 'GP.scalar_add(%s, v, v, A, vA)' % ARG))
d45 = ear(smul('Nat.add(v, v)', 'A'), padd(sw, sw), smul('Nat.add(w, w)', 'B'), cl(sw, sw, vsw, vsw), sc('Nat.add(w, w)', 'B', 'vB'),
          esym(smul('Nat.add(w, w)', 'B'), padd(sw, sw), 'GP.scalar_add(%s, w, w, B, vB)' % ARG))
a('''# x = J(v, w): 2 x = J(2 v, 2 w)
def jdbl(%s, %s, %s) -> %s:
  %%rw GP.group_double(%s, x, vx)
  %%rw NA.double_self(v)
  %%rw NA.double_self(w)
  %s

def j4(%s, %s, %s) -> %s:
  +v1 = dbl_vd(%s, x, vx)
  +v2 = dbl_vd(%s, %s, v1)
  +v3 = dbl_vd(%s, %s, v2)
  +e1 = jdbl(%s, %s, x, v, w, vx, hx)
  +e2 = jdbl(%s, %s, %s, Nat.double(v), Nat.double(w), v1, e1)
  +e3 = jdbl(%s, %s, %s, %s, %s, v2, e2)
  jdbl(%s, %s, %s, %s, %s, v3, e3)
''' % (HYP, AB, XH, eq(pdbl('x'), J('Nat.double(v)', 'Nat.double(w)')), ARG,
       trans(D0, D1, D5, vD1, d01, trans(D1, D2, D5, vD2, d12, trans(D2, D3, D5, vD3, d23, trans(D3, D4, D5, vD4, d34, d45)))),
       HYP, AB, XH, eq(pdbl('x', 4), J(ndbl('v', 4), ndbl('w', 4))),
       ARG, ARG, pdbl('x', 1), ARG, pdbl('x', 2),
       ARG, ABA, ARG, ABA, pdbl('x', 1), ARG, ABA, pdbl('x', 2), ndbl('v', 2), ndbl('w', 2),
       ARG, ABA, pdbl('x', 3), ndbl('v', 3), ndbl('w', 3)))

# ---- the code's steps ----
TPa = lambda bs: 'PX.tpick(%s, PX.tab(a))' % bs
TPb = lambda bs: 'PX.tpick(%s, PX.tab(b))' % bs
PAV, PBV = 'PP.pv(one, a)', 'PP.pv(one, b)'
JP = lambda v, w: J(v, w, PAV, PBV)
ABH = '+a: PX.PT, +b: PX.PT, +ha: %s, +hb: %s, +va: %s, +vb: %s' % (pd('a'), pd('b'), vd(PAV), vd(PBV))
ABHA = 'a, b, ha, hb, va, vb'
ABS = '%s, %s, va, vb' % (PAV, PBV)
RH = '+r: PX.PT, +v: Nat, +w: Nat, +hr: %s, +vr: %s, +he: %s' % (pd('r'), vd('PP.pv(one, r)'), eq('PP.pv(one, r)', JP('v', 'w')))
RHA = 'r, v, w, hr, vr, he'
a('''# the public selection is the proofs' pick tree (tpk)
def tpk_q(+b1: Nat, +b2: Nat, +b3: Nat, +b4: Nat, +a: PX.PT) -> {%s == tpk(b1, b2, b3, b4, a) : PX.PT}:
  {==}

def tpick_r(+one: Nat, +h1: {one == 1n : Nat}, +b1: Nat, +b2: Nat, +b3: Nat, +b4: Nat, +a: PX.PT, +ha: %s) -> %s:
  %%rw tpk_q(b1, b2, b3, b4, a)
  tpk_r(one, h1, b1, b2, b3, b4, a, ha)

def tpick_vd(%s, +b1: Nat, +b2: Nat, +b3: Nat, +b4: Nat, +a: PX.PT, +ha: %s, +va: %s) -> %s:
  %%rw tpk_q(b1, b2, b3, b4, a)
  tpk_vd(%s, b1, b2, b3, b4, a, ha, va)

# 16 r + [k] a
def sk_a(%s, %s, %s, +k: Nat) -> %s:
  %%rw PP.padd_v(one, h1, %s, tabp(k, a), d4_r(one, h1, r, hr), tabp_r(one, h1, k, a, ha))
  %%rw d4_v(one, h1, r, hr)
  %%rw tabp_v(one, h1, k, a, ha)
  jl(%s, %s, %s, %s, %s, dbl4_vd(%s, PP.pv(one, r), vr), j4(%s, %s, PP.pv(one, r), v, w, vr, he), k)

# s + [k] b
def sk_b(%s, %s, +s: PX.PT, +v: Nat, +w: Nat, +hs: %s, +vs: %s, +hq: %s, +k: Nat) -> %s:
  %%rw PP.padd_v(one, h1, s, tabp(k, b), hs, tabp_r(one, h1, k, b, hb))
  %%rw tabp_v(one, h1, k, b, hb)
  jr(%s, %s, PP.pv(one, s), v, w, vs, hq, k)
''' % (TPa('b1, b2, b3, b4'), pd('a'), pd(TPa('b1, b2, b3, b4')),
       HYP, pd('a'), vd(PAV), vd('PP.pv(one, %s)' % TPa('b1, b2, b3, b4')), ARG,
       HYP, ABH, RH, eq('PP.pv(one, PX.add(%s, tabp(k, a)))' % D4R, JP('Nat.add(k, %s)' % ndbl('v', 4), ndbl('w', 4))),
       D4R, ARG, ABS, pdbl('PP.pv(one, r)', 4), ndbl('v', 4), ndbl('w', 4), ARG, ARG, ABS,
       HYP, ABH, pd('s'), vd('PP.pv(one, s)'), eq('PP.pv(one, s)', JP('v', 'w')), eq('PP.pv(one, PX.add(s, tabp(k, b)))', JP('v', 'Nat.add(k, w)')),
       ARG, ABS))

# case trees over the bits: of a (after the doublings), then of b
S1 = lambda bs: 'PX.add(%s, %s)' % (D4R, TPa(bs))
for which in ('a', 'b'):
    for depth in (3, 2, 1, 0):
        for pre in range(1 << depth):
            pb = [(pre >> (depth - 1 - i)) & 1 for i in range(depth)]
            rest = ['b%d' % (i + 1) for i in range(depth, 4)]
            allb = pb + rest
            name = 's%s' % which + ''.join(map(str, pb))
            bparams = ', '.join('%s: Nat, +h%s: {Nat.is_lt(%s, 2n) == True{} : Bool}' % (b, b, b) for b in rest)
            if which == 'a':
                hyps, hargs = '%s, %s' % (ABH, RH), '%s, %s' % (ABHA, RHA)
                ty = lambda bs: eq('PP.pv(one, %s)' % S1(', '.join(lit(b) for b in bs)), JP(nxt4([lit(b) for b in bs]), ndbl('w', 4)))
            else:
                hyps = '%s, +s: PX.PT, +v: Nat, +w: Nat, +hs: %s, +vs: %s, +hq: %s' % (ABH, pd('s'), vd('PP.pv(one, s)'), eq('PP.pv(one, s)', JP('v', ndbl('w', 4))))
                hargs = '%s, s, v, w, hs, vs, hq' % ABHA
                ty = lambda bs: eq('PP.pv(one, PX.add(s, %s))' % TPb(', '.join(lit(b) for b in bs)), JP('v', nxt4([lit(b) for b in bs], 'w')))
            b0 = rest[0]
            ls = ['def %s(%s, %s, %s) -> %s:' % (name, HYP, hyps, bparams, ty(allb)), '  match %s:' % b0]
            for val in (0, 1):
                child = pb + [val]
                cargs = ', '.join('%s, h%s' % (b, b) for b in rest[1:])
                if len(child) == 4:
                    k = child[0] * 8 + child[1] * 4 + child[2] * 2 + child[3]
                    if which == 'a':
                        call = 'sk_a(%s, %s, %dn)' % (ARG, hargs, k)
                    else:
                        call = 'sk_b(%s, %s, s, v, %s, hs, vs, hq, %dn)' % (ARG, ABHA, ndbl('w', 4), k)
                else:
                    call = 's%s%s(%s, %s%s)' % (which, ''.join(map(str, child)), ARG, hargs, ', ' + cargs if cargs else '')
                ls += ['    case %dn:' % val, '      ' + call]
            bad = [('2n+k' if b == b0 else b) for b in allb]
            ls += ['    case 2n+ +k:', '      Empty.absurd(%s, N.lt_zero_absurd(k, h%s))' % (ty(bad), b0)]
            a('\n'.join(ls) + '\n')

# the step of the code
BB4 = lambda p: ', '.join('+%s%d: Nat' % (p, i) for i in (1, 2, 3, 4))
HB4 = lambda p: ', '.join('+h%s%d: {Nat.is_lt(%s%d, 2n) == True{} : Bool}' % (p, i, p, i) for i in (1, 2, 3, 4))
BI4 = lambda p: ', '.join('+%s%d: Nat, +h%s%d: {Nat.is_lt(%s%d, 2n) == True{} : Bool}' % (p, i, p, i, p, i) for i in (1, 2, 3, 4))
ARGB = lambda p: ', '.join('%s%d, h%s%d' % (p, i, p, i) for i in (1, 2, 3, 4))
BL = lambda p: '%s1, %s2, %s3, %s4' % (p, p, p, p)
ST1 = S1(BL('b'))
ST2 = 'PX.add(%s, %s)' % (ST1, TPb(BL('c')))
a('''def st_r(+one: Nat, +h1: {one == 1n : Nat}, +a: PX.PT, +b: PX.PT, +r: PX.PT, +ha: %(pa)s, +hb: %(pb)s, +hr: %(pr)s, %(bb)s, %(cc)s) -> %(pst)s:
  PP.padd_r(one, h1, %(st1)s, %(tpc)s, PP.padd_r(one, h1, %(x4)s, %(tpb)s, d4_r(one, h1, r, hr), tpick_r(one, h1, b1, b2, b3, b4, a, ha)), tpick_r(one, h1, c1, c2, c3, c4, b, hb))

def st_vd(%(H)s, %(abh)s, +r: PX.PT, +hr: %(pr)s, +vr: %(vpr)s, %(bb)s, %(cc)s) -> %(vst)s:
  +h1r = PP.padd_r(one, h1, %(x4)s, %(tpb)s, d4_r(one, h1, r, hr), tpick_r(one, h1, b1, b2, b3, b4, a, ha))
  %%rw PP.padd_v(one, h1, %(st1)s, %(tpc)s, h1r, tpick_r(one, h1, c1, c2, c3, c4, b, hb))
  %%rw PP.padd_v(one, h1, %(x4)s, %(tpb)s, d4_r(one, h1, r, hr), tpick_r(one, h1, b1, b2, b3, b4, a, ha))
  %%rw d4_v(one, h1, r, hr)
  GP.group_closed(%(A)s, %(p1)s, PP.pv(one, %(tpc)s), GP.group_closed(%(A)s, %(s4)s, PP.pv(one, %(tpb)s), dbl4_vd(%(A)s, PP.pv(one, r), vr), tpick_vd(%(A)s, b1, b2, b3, b4, a, ha, va)), tpick_vd(%(A)s, c1, c2, c3, c4, b, hb, vb))

def st_e(%(H)s, %(abh)s, %(rh)s, %(bi)s, %(ci)s) -> %(est)s:
  +h1r = PP.padd_r(one, h1, %(x4)s, %(tpb)s, d4_r(one, h1, r, hr), tpick_r(one, h1, b1, b2, b3, b4, a, ha))
  +v1r = GP.group_closed(%(A)s, %(s4)s, PP.pv(one, %(tpb)s), dbl4_vd(%(A)s, PP.pv(one, r), vr), tpick_vd(%(A)s, b1, b2, b3, b4, a, ha, va))
  +v1 = Lg.subst(CV.SPoint, t => %(vt)s, %(p1)s, PP.pv(one, %(st1)s), Equal.sym(CV.SPoint, PP.pv(one, %(st1)s), %(p1)s, Equal.trans(CV.SPoint, PP.pv(one, %(st1)s), CV.padd(FS.prime(one), PP.pv(one, %(x4)s), PP.pv(one, %(tpb)s)), %(p1)s, PP.padd_v(one, h1, %(x4)s, %(tpb)s, d4_r(one, h1, r, hr), tpick_r(one, h1, b1, b2, b3, b4, a, ha)), Equal.cong(CV.SPoint, CV.SPoint, t => CV.padd(FS.prime(one), t, PP.pv(one, %(tpb)s)), PP.pv(one, %(x4)s), %(s4)s, d4_v(one, h1, r, hr)))), v1r)
  +e1 = sa(%(A)s, %(abha)s, %(rha)s, %(abb)s)
  sb(%(A)s, %(abha)s, %(st1)s, %(nb)s, w, h1r, v1, e1, %(acc)s)
''' % dict(H=HYP, A=ARG, pa=pd('a'), pb=pd('b'), pr=pd('r'), vpr=vd('PP.pv(one, r)'), bb=BB4('b'), cc=BB4('c'), hbb=HB4('b'), hcc=HB4('c'),
           abh=ABH, rh=RH, abha=ABHA, rha=RHA, abb=ARGB('b'), acc=ARGB('c'), bi=BI4('b'), ci=BI4('c'),
           pst=pd(ST2), vst=vd('PP.pv(one, %s)' % ST2), st1=ST1, x4=D4R, tpb=TPa(BL('b')), tpc=TPb(BL('c')),
           s4=pdbl('PP.pv(one, r)', 4), p1=padd(pdbl('PP.pv(one, r)', 4), 'PP.pv(one, %s)' % TPa(BL('b'))),
           vt=vd('t'), nb=nxt4(['b1', 'b2', 'b3', 'b4']), w4=ndbl('w', 4),
           est=eq('PP.pv(one, %s)' % ST2, JP(nxt4(['b1', 'b2', 'b3', 'b4']), nxt4(['c1', 'c2', 'c3', 'c4'], 'w')))))

# ---- the loop ----
a('''# two bit lists of the same multiple of 4 bits
def ok44(bs: List<&2, Nat>, cs: List<&2, Nat>) -> Bool:
  match bs:
    case Nil{}:
      match cs:
        case Nil{}: True{}
        case c <> t: False{}
    case b1 <> Nil{}: False{}
    case b1 <> b2 <> Nil{}: False{}
    case b1 <> b2 <> b3 <> Nil{}: False{}
    case b1 <> b2 <> b3 <> b4 <> rb:
      match cs:
        case Nil{}: False{}
        case c1 <> Nil{}: False{}
        case c1 <> c2 <> Nil{}: False{}
        case c1 <> c2 <> c3 <> Nil{}: False{}
        case c1 <> c2 <> c3 <> c4 <> rc: ok44(rb, rc)
''')

SG = lambda bs, cs, r: 'PX.sgo(%s, %s, PX.tab(a), PX.tab(b), %s)' % (bs, cs, r)
STC = ST2.replace('PX.add(PX.add(PX.dbl', 'PX.add(PX.add(PX.dbl')


def cases_b(name, hdr, concl, base_nil, rec, extra_split=''):
    """the loop's case split: bs, then cs"""
    ls = [hdr, '  match bs:', '    case Nil{}:', base_nil]
    for pat, lst in (('+b1 <> Nil{}', '[b1]'), ('+b1 <> +b2 <> Nil{}', '[b1, b2]'), ('+b1 <> +b2 <> +b3 <> Nil{}', '[b1, b2, b3]')):
        ls += ['    case %s:' % pat, '      ' + concl(lst, 'cs')]
    ls += ['    case +b1 <> +b2 <> +b3 <> +b4 <> +rb:', '      match cs:']
    for pat, lst in (('Nil{}', 'Nil{}'), ('+c1 <> Nil{}', '[c1]'), ('+c1 <> +c2 <> Nil{}', '[c1, c2]'), ('+c1 <> +c2 <> +c3 <> Nil{}', '[c1, c2, c3]')):
        ls += ['        case %s:' % pat, '          ' + concl('b1 <> b2 <> b3 <> b4 <> rb', lst)]
    ls += ['        case +c1 <> +c2 <> +c3 <> +c4 <> +rc:'] + [('    ' + l if l.strip() else l) for l in extra_split.split('\n') if l] + ['          ' + rec]
    return '\n'.join(ls) + '\n'


RR = '+r: PX.PT, +hr: %s' % pd('r')
STR = 'PX.add(PX.add(%s, %s), %s)' % (D4R, TPa(BL('b')), TPb(BL('c')))
# pred: no hypotheses on the bits
hdr = 'def sgo_r(+one: Nat, +h1: {one == 1n : Nat}, bs: List<&2, Nat>, cs: List<&2, Nat>, +a: PX.PT, +b: PX.PT, +ha: %s, +hb: %s, %s) -> %s:' % (pd('a'), pd('b'), RR, pd(SG('bs', 'cs', 'r')))
a(cases_b('sgo_r', hdr, lambda bs, cs: 'hr', '      hr',
          'sgo_r(one, h1, rb, rc, a, b, ha, hb, %s, st_r(one, h1, a, b, r, ha, hb, hr, b1, b2, b3, b4, c1, c2, c3, c4))' % STR))
hdr = 'def sgo_vd(%s, bs: List<&2, Nat>, cs: List<&2, Nat>, %s, %s, +vr: %s) -> %s:' % (HYP, ABH, RR, vd('PP.pv(one, r)'), vd('PP.pv(one, %s)' % SG('bs', 'cs', 'r')))
a(cases_b('sgo_vd', hdr, lambda bs, cs: 'vr', '      vr',
          'sgo_vd(%s, rb, rc, %s, %s, st_r(one, h1, a, b, r, ha, hb, hr, b1, b2, b3, b4, c1, c2, c3, c4), st_vd(%s, %s, r, hr, vr, b1, b2, b3, b4, c1, c2, c3, c4))' % (ARG, ABHA, STR, ARG, ABHA)))
SPLITBC = '''      +q1 = Lg.and_right(Nat.is_lt(b1, 2n), BV.all01(b2 <> b3 <> b4 <> rb), hbb)
      +q2 = Lg.and_right(Nat.is_lt(b2, 2n), BV.all01(b3 <> b4 <> rb), q1)
      +q3 = Lg.and_right(Nat.is_lt(b3, 2n), BV.all01(b4 <> rb), q2)
      +hb1 = Lg.and_left(Nat.is_lt(b1, 2n), BV.all01(b2 <> b3 <> b4 <> rb), hbb)
      +hb2 = Lg.and_left(Nat.is_lt(b2, 2n), BV.all01(b3 <> b4 <> rb), q1)
      +hb3 = Lg.and_left(Nat.is_lt(b3, 2n), BV.all01(b4 <> rb), q2)
      +hb4 = Lg.and_left(Nat.is_lt(b4, 2n), BV.all01(rb), q3)
      +hbt = Lg.and_right(Nat.is_lt(b4, 2n), BV.all01(rb), q3)
      +d1 = Lg.and_right(Nat.is_lt(c1, 2n), BV.all01(c2 <> c3 <> c4 <> rc), hcc)
      +d2 = Lg.and_right(Nat.is_lt(c2, 2n), BV.all01(c3 <> c4 <> rc), d1)
      +d3 = Lg.and_right(Nat.is_lt(c3, 2n), BV.all01(c4 <> rc), d2)
      +hc1 = Lg.and_left(Nat.is_lt(c1, 2n), BV.all01(c2 <> c3 <> c4 <> rc), hcc)
      +hc2 = Lg.and_left(Nat.is_lt(c2, 2n), BV.all01(c3 <> c4 <> rc), d1)
      +hc3 = Lg.and_left(Nat.is_lt(c3, 2n), BV.all01(c4 <> rc), d2)
      +hc4 = Lg.and_left(Nat.is_lt(c4, 2n), BV.all01(rc), d3)
      +hct = Lg.and_right(Nat.is_lt(c4, 2n), BV.all01(rc), d3)'''
CE = lambda bs, cs: eq('PP.pv(one, %s)' % SG(bs, cs, 'r'), JP('G4.bvl(%s, v)' % bs, 'G4.bvl(%s, w)' % cs))
hdr = 'def sgo_e(%s, bs: List<&2, Nat>, cs: List<&2, Nat>, %s, %s, +hbb: {BV.all01(bs) == True{} : Bool}, +hcc: {BV.all01(cs) == True{} : Bool}, +hq: {ok44(bs, cs) == True{} : Bool}) -> %s:' % (HYP, ABH, RH, CE('bs', 'cs'))
absurd = lambda bs, cs: 'Empty.absurd(%s, Lg.false_true(hq))' % CE(bs, cs)
base = '''      match cs:
        case Nil{}:
          he
        case +c <> +t:
          %s''' % absurd('Nil{}', 'c <> t')
a(cases_b('sgo_e', hdr, absurd, base,
          'sgo_e(%s, rb, rc, %s, %s, %s, %s, st_r(one, h1, a, b, r, ha, hb, hr, b1, b2, b3, b4, c1, c2, c3, c4), st_vd(%s, %s, r, hr, vr, b1, b2, b3, b4, c1, c2, c3, c4), st_e(%s, %s, %s, %s, %s), hbt, hct, hq)'
          % (ARG, ABHA, STR, nxt4(['b1', 'b2', 'b3', 'b4']), nxt4(['c1', 'c2', 'c3', 'c4'], 'w'), ARG, ABHA, ARG, ABHA, RHA, ARGB('b'), ARGB('c')),
          extra_split=SPLITBC))

# ---- smul2 ----
SM2 = 'PX.smul2(bs, cs, a, b)'
J00 = JP('0n', '0n')
a('''# the point at infinity is J(0, 0)
def j00(%(H)s, %(abh)s) -> %(e00)s:
  %%rw PM.pinf_v(one, h1)
  GP.equiv_sym(%(A)s, %(j00)s, CV.infinity(), GP.group_identity(%(A)s, CV.infinity()))

def smul2_r(+one: Nat, +h1: {one == 1n : Nat}, bs: List<&2, Nat>, +cs: List<&2, Nat>, +a: PX.PT, +b: PX.PT, +ha: %(pa)s, +hb: %(pb)s) -> %(psm)s:
  match bs:
    case Nil{}:
      PM.pinf_r(one, h1)
    case +x <> +t:
      sgo_r(one, h1, x <> t, cs, a, b, ha, hb, PX.infinity(), PM.pinf_r(one, h1))

def smul2_vd(%(H)s, bs: List<&2, Nat>, +cs: List<&2, Nat>, %(abh)s) -> %(vsm)s:
  match bs:
    case Nil{}:
      inf_vd(%(A)s)
    case +x <> +t:
      sgo_vd(%(A)s, x <> t, cs, %(abha)s, PX.infinity(), PM.pinf_r(one, h1), inf_vd(%(A)s))

# smul2(bits j, bits k, a, b) is [j] a + [k] b
def smul2_e(%(H)s, bs: List<&2, Nat>, +cs: List<&2, Nat>, %(abh)s, +hbb: {BV.all01(bs) == True{} : Bool}, +hcc: {BV.all01(cs) == True{} : Bool}, +hq: {ok44(bs, cs) == True{} : Bool}) -> %(esm)s:
  match bs:
    case Nil{}:
      match cs:
        case Nil{}:
          j00(%(A)s, %(abha)s)
        case +c <> +t:
          Empty.absurd(%(abs)s, Lg.false_true(hq))
    case +x <> +t:
      sgo_e(%(A)s, x <> t, cs, %(abha)s, PX.infinity(), 0n, 0n, PM.pinf_r(one, h1), inf_vd(%(A)s), j00(%(A)s, %(abha)s), hbb, hcc, hq)
''' % dict(H=HYP, A=ARG, abh=ABH, abha=ABHA, pa=pd('a'), pb=pd('b'), e00=eq('PP.pv(one, PX.infinity())', J00), j00=J00,
           psm=pd(SM2), vsm=vd('PP.pv(one, %s)' % SM2),
           esm=eq('PP.pv(one, %s)' % SM2, JP('G4.bvl(bs, 0n)', 'G4.bvl(cs, 0n)')),
           abs=eq('PP.pv(one, PX.smul2(Nil{}, c <> t, a, b))', JP('G4.bvl(Nil{}, 0n)', 'G4.bvl(c <> t, 0n)'))))

# ---- two files: pwr.src, the definitions without the group law (the
# code's points: tab, pick, tsel and wmul are points of the curve's
# representation), for the roots that do not use the group law; pwin.src
# the rest, importing pwr.bend as WR ----
import re
text = re.sub(r'(?<![\w.])pick\(', 'PX.pick(', '\n'.join(o))
head, _, body = text.partition('\n# ---- on the specification')
body = '# ---- on the specification' + body
blocks = re.split(r'(?m)^(?=def |# ----)', body)
names = [re.match(r'def (\w+)', b).group(1) if b.startswith('def ') else None for b in blocks]
GROUP = re.compile(r'(?<![\w.])(GP|GS|G4|NP)\.|\bhp\b|\bhc\b')
defs = set(n for n in names if n)
free = set()
changed = True
while changed:
    changed = False
    for n, b in zip(names, blocks):
        if not n or n in free or GROUP.search(b):
            continue
        refs = set(re.findall(r'(?<![\w.])(\w+)\(', b)) & defs
        if refs - {n} <= free:
            free.add(n); changed = True
R, W = [], []
for n, b in zip(names, blocks):
    (R if n in free else W).append(b)
q = re.compile(r'(?<![\w.])(%s)(?=\()' % '|'.join(sorted(free, key=len, reverse=True)))
W = [q.sub(r'WR.\1', b) for b in W]
hl = head.split('\n')
imp = [l for l in hl if l.startswith('import ')]
rest = [l for l in hl if not l.startswith('import ')]
rimp = [l for l in imp if not re.search(r' as (GP|GS|G4|NP|C|NA)$', l)]
(ROOT / 'tools/generators/secp256k1_hand/pwr.src').write_text('\n'.join(rimp + ['', '# GENERATED by tools/generators/secp256k1_win.py; edit the generator.', '#', '# The 4-bit fixed-window multiplication of src/crypto/secp256k1/pt.bend on', '# the code\'s points, without the group law: the table, the selection and', '# wmul are points of the representation (pred), and the table entries are', '# repeated additions (tabp). The group-law half is pwin.bend.', '']) + ''.join(R).rstrip('\n') + '\n')
(ROOT / 'tools/generators/secp256k1_hand/pwin.src').write_text('\n'.join(imp + ['import ./pwr.bend as WR'] + rest) + ''.join(W).rstrip('\n') + '\n')
print('wrote tools/generators/secp256k1_hand/pwr.src (%d defs), pwin.src' % len(free))
