#!/usr/bin/env python3
"""Generate src/crypto/secp256k1/pt.bend (the secp256k1 group on the records of
fe.bend) and proofs/crypto/secp256k1/ptbr.bend (its formulas are the register
programs of proofs/crypto/secp256k1/pti.bend, by normalization).

  python3 tools/generators/secp256k1_pt.py

The addition and doubling are Algorithms 7 and 9 of Renes, Costello and
Batina (EUROCRYPT 2016) for a = 0, b3 = 21: the register programs of
spec/crypto/secp256k1/curve.bend, written out as straight-line code (the
compiled code keeps every register in machine registers).
"""
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
N = 16

# RCB 2016 Algorithm 7 / 9 as in spec/crypto/secp256k1/curve.bend
ADD = [('M', 0, 3), ('M', 1, 4), ('M', 2, 5), ('A', 0, 1), ('A', 3, 4), ('M', 10, 11), ('A', 7, 8), ('S', 12, 13), ('A', 1, 2), ('A', 4, 5),
       ('M', 15, 16), ('A', 8, 9), ('S', 17, 18), ('A', 0, 2), ('A', 3, 5), ('M', 20, 21), ('A', 7, 9), ('S', 22, 23), ('A', 7, 7), ('A', 25, 7),
       ('M', 6, 9), ('A', 8, 27), ('S', 8, 27), ('M', 6, 24), ('M', 19, 30), ('M', 14, 29), ('S', 32, 31), ('M', 30, 26), ('M', 29, 28), ('A', 35, 34),
       ('M', 26, 14), ('M', 28, 19), ('A', 38, 37)]
DBL = [('M', 1, 1), ('A', 4, 4), ('A', 5, 5), ('A', 6, 6), ('M', 1, 2), ('M', 2, 2), ('M', 3, 9), ('M', 10, 7), ('A', 4, 10), ('M', 8, 7),
       ('A', 10, 10), ('A', 14, 10), ('S', 4, 15), ('M', 16, 12), ('A', 11, 17), ('M', 0, 1), ('M', 16, 19), ('A', 20, 20)]
ADD_IN, ADD_OUT = ['x1', 'y1', 'z1', 'x2', 'y2', 'z2', 'b3()'], (33, 36, 39)
DBL_IN, DBL_OUT = ['x', 'y', 'z', 'b3()'], (21, 18, 13)


def rop(op, i, j, b3):
    """the record interpreter's instruction (squares as RSq, products by
    the register b3 as RMulB)"""
    if op == 'M':
        if i == b3:
            return 'I.RMulB{%dn, %dn}' % (i, j)
        return 'I.RSq{%dn}' % i if i == j else 'I.RMul{%dn, %dn}' % (i, j)
    return 'I.%s{%dn, %dn}' % ('RAdd' if op == 'A' else 'RSub', i, j)


def straight(prog, inputs, outs):
    regs, lines = list(inputs), []
    b3 = inputs.index('b3()')
    for op, i, j in prog:
        name = 'r%d' % len(regs)
        a, b = regs[i], regs[j]
        if op == 'M' and i == b3:
            e = 'F.mul21(%s)' % b
        elif op == 'M':
            e = 'F.sq(%s)' % a if i == j else 'F.mul(%s, %s)' % (a, b)
        else:
            e = 'F.%s(%s, %s)' % ('add' if op == 'A' else 'sub', a, b)
        lines.append('      +%s = %s' % (name, e))
        regs.append(name)
    lines.append('      PT{%s}' % ', '.join(regs[o] for o in outs))
    return '\n'.join(lines)


def ptree():
    cur = ['t%d' % i for i in range(16)]
    for b in ('b4', 'b3', 'b2', 'b1'):
        cur = ['pick(%s, %s, %s)' % (b, cur[2 * j + 1], cur[2 * j]) for j in range(len(cur) // 2)]
    return cur[0]


src = '''import Base
import ./fe.bend as F

# The secp256k1 group y^2 = x^3 + 7 over GF(p) on the records of fe.bend
# (GENERATED by tools/generators/secp256k1_pt.py; edit the generator), in
# homogeneous projective coordinates (X : Y : Z), the point at infinity
# (0 : 1 : 0). Addition and doubling are the complete formulas of Renes,
# Costello and Batina, "Complete addition formulas for prime order elliptic
# curves" (EUROCRYPT 2016), Algorithms 7 and 9 for a = 0 with b3 = 3 b = 21:
# the register programs of spec/crypto/secp256k1/curve.bend, written out
# register by register (rN is register N of the program; squares are
# F.sq, products by the register b3 are F.mul21). One formula for every
# pair of inputs, so no branch.
#
# Scalar multiplication is the specification's left-to-right double-and-add:
# mul_go adds in every step and selects with an arithmetic mask (secret
# scalars: no branch and no table index on a bit), vmul_go adds only when
# the bit is set (public scalars, as in verification).

type PT is Data:
  PT{x: F.FE, y: F.FE, z: F.FE}

def b3() -> F.FE:
  F.FE{21n, %s}

# RCB 2016 Algorithm 7 (a = 0)
def add(p: PT, q: PT) -> PT:
  match p q:
    case PT{+x1, +y1, +z1} PT{+x2, +y2, +z2}:
%s

# RCB 2016 Algorithm 9 (a = 0)
def dbl(p: PT) -> PT:
  match p:
    case PT{+x, +y, +z}:
%s

def infinity() -> PT:
  PT{F.zero(), F.one(), F.zero()}

# b ? p : q, coordinate-wise and branch-free, for b in {0, 1}
def select(+b: Nat, p: PT, q: PT) -> PT:
  match p q:
    case PT{x1, y1, z1} PT{x2, y2, z2}:
      PT{F.select(b, x1, x2), F.select(b, y1, y2), F.select(b, z1, z2)}

def step(+b: Nat, +p: PT, +d: PT) -> PT:
  select(b, add(d, p), d)

# [k] p from r for the bits of k, most significant first: double, then add
# (always, selected by the bit)
def mul_go(bits: List<&2, Nat>, +p: PT, r: PT) -> PT:
  match bits:
    case Nil{}: r
    case b <> t: mul_go(t, p, step(b, p, dbl(r)))

def vstep(b: Nat, +p: PT, +d: PT) -> PT:
  match b:
    case 0n: d
    case 1n+c: add(d, p)

# the same for a public scalar: the addition only when the bit is set
def vmul_go(bits: List<&2, Nat>, +p: PT, r: PT) -> PT:
  match bits:
    case Nil{}: r
    case b <> t: vmul_go(t, p, vstep(b, p, dbl(r)))

# ---- fixed windows of 4 bits ----

# [0] a, ..., [15] a, each the one before plus a
type T16 is Data:
  T16{t0: PT, t1: PT, t2: PT, t3: PT, t4: PT, t5: PT, t6: PT, t7: PT, t8: PT, t9: PT, t10: PT, t11: PT, t12: PT, t13: PT, t14: PT, t15: PT}

def tab(+a: PT) -> T16:
  +t0 = infinity()
  +t1 = add(t0, a)
  +t2 = add(t1, a)
  +t3 = add(t2, a)
  +t4 = add(t3, a)
  +t5 = add(t4, a)
  +t6 = add(t5, a)
  +t7 = add(t6, a)
  +t8 = add(t7, a)
  +t9 = add(t8, a)
  +t10 = add(t9, a)
  +t11 = add(t10, a)
  +t12 = add(t11, a)
  +t13 = add(t12, a)
  +t14 = add(t13, a)
  +t15 = add(t14, a)
  T16{t0, t1, t2, t3, t4, t5, t6, t7, t8, t9, t10, t11, t12, t13, t14, t15}

# the entry of the digit b1 b2 b3 b4 (most significant first), by a tree of
# masked selections: every entry is read, no branch or index on the bits
def tsel(+b1: Nat, +b2: Nat, +b3: Nat, +b4: Nat, t: T16) -> PT:
  match t:
    case T16{+t0, +t1, +t2, +t3, +t4, +t5, +t6, +t7, +t8, +t9, +t10, +t11, +t12, +t13, +t14, +t15}:
      +s0_0 = select(b4, t1, t0)
      +s0_1 = select(b4, t3, t2)
      +s0_2 = select(b4, t5, t4)
      +s0_3 = select(b4, t7, t6)
      +s0_4 = select(b4, t9, t8)
      +s0_5 = select(b4, t11, t10)
      +s0_6 = select(b4, t13, t12)
      +s0_7 = select(b4, t15, t14)
      +s1_0 = select(b3, s0_1, s0_0)
      +s1_1 = select(b3, s0_3, s0_2)
      +s1_2 = select(b3, s0_5, s0_4)
      +s1_3 = select(b3, s0_7, s0_6)
      +s2_0 = select(b2, s1_1, s1_0)
      +s2_1 = select(b2, s1_3, s1_2)
      +s3_0 = select(b1, s2_1, s2_0)
      s3_0

# 16 r + [digit] a for every 4 bits (bit lists of a multiple of 4 bits)
def wgo(bits: List<&2, Nat>, +t: T16, r: PT) -> PT:
  match bits:
    case Nil{}: r
    case b1 <> Nil{}: r
    case b1 <> b2 <> Nil{}: r
    case b1 <> b2 <> b3 <> Nil{}: r
    case b1 <> b2 <> b3 <> b4 <> rest: wgo(rest, t, add(dbl(dbl(dbl(dbl(r)))), tsel(b1, b2, b3, b4, t)))

# [k] a for the bits of a secret k (the table only for some bits, so that on
# unknown bits the proof checker never forms it)
def wmul(bits: List<&2, Nat>, +a: PT) -> PT:
  match bits:
    case Nil{}: infinity()
    case b <> t: wgo(b <> t, tab(a), infinity())

# ---- two public scalars (verification, recovery) ----

# x for b = 1, y for b = 0: a branch, for public bits only
def pick(b: Nat, +x: PT, +y: PT) -> PT:
  match b:
    case 0n: y
    case 1n+k: x

# the entry of 4 public bits (b1 the highest), the same tree as tsel
def tpick(+b1: Nat, +b2: Nat, +b3: Nat, +b4: Nat, t: T16) -> PT:
  match t:
    case T16{+t0, +t1, +t2, +t3, +t4, +t5, +t6, +t7, +t8, +t9, +t10, +t11, +t12, +t13, +t14, +t15}:
      %s

# [j] a + [k] b for the bits of public j and k (Strauss: one chain of
# doublings, then the entries of 4 bits of j and of k, for bit lists of the
# same multiple of 4 bits)
def sgo(bs: List<&2, Nat>, cs: List<&2, Nat>, +ta: T16, +tb: T16, r: PT) -> PT:
  match bs:
    case Nil{}: r
    case b1 <> Nil{}: r
    case b1 <> b2 <> Nil{}: r
    case b1 <> b2 <> b3 <> Nil{}: r
    case b1 <> b2 <> b3 <> b4 <> rb:
      match cs:
        case Nil{}: r
        case c1 <> Nil{}: r
        case c1 <> c2 <> Nil{}: r
        case c1 <> c2 <> c3 <> Nil{}: r
        case c1 <> c2 <> c3 <> c4 <> rc: sgo(rb, rc, ta, tb, add(add(dbl(dbl(dbl(dbl(r)))), tpick(b1, b2, b3, b4, ta)), tpick(c1, c2, c3, c4, tb)))

def smul2(bs: List<&2, Nat>, cs: List<&2, Nat>, +a: PT, +b: PT) -> PT:
  match bs:
    case Nil{}: infinity()
    case x <> t: sgo(x <> t, cs, tab(a), tab(b), infinity())
''' % (', '.join(['0n'] * 15), straight(ADD, ['x1', 'y1', 'z1', 'x2', 'y2', 'z2', 'b3()'], ADD_OUT), straight(DBL, ['x', 'y', 'z', 'b3()'], DBL_OUT), ptree())
(ROOT / 'src/crypto/secp256k1/pt.bend').write_text(src)

br = '''# GENERATED by tools/generators/secp256k1_pt.py; edit the generator.
import Base
import ../../../src/crypto/secp256k1/fe.bend as F
import ../../../src/crypto/secp256k1/pt.bend as PX
import ./pti.bend as I

# The straight-line formulas of src/crypto/secp256k1/pt.bend are the
# register programs of pti.bend run on the coordinates (normalization: the
# field operations stay folded on unknown coordinates).

def add_prog_l() -> {I.radd_prog() == [%s] : List<&2, I.ROp>}:
  {==}

def dbl_prog_l() -> {I.rdbl_prog() == [%s] : List<&2, I.ROp>}:
  {==}

def add_b(p: PX.PT, q: PX.PT) -> {PX.add(p, q) == I.add_out(I.rrun_go(I.radd_prog(), I.regs7(p, q))) : PX.PT}:
  match p q:
    case PX.PT{+x1, +y1, +z1} PX.PT{+x2, +y2, +z2}:
      {==}

def dbl_b(p: PX.PT) -> {PX.dbl(p) == I.dbl_out(I.rrun_go(I.rdbl_prog(), I.regs4(p))) : PX.PT}:
  match p:
    case PX.PT{+x, +y, +z}:
      {==}
''' % (', '.join(rop(*o, 6) for o in ADD), ', '.join(rop(*o, 3) for o in DBL))
(ROOT / 'proofs/crypto/secp256k1/ptbr.bend').write_text(br)
PROGS = (', '.join(rop(*o, 6) for o in ADD), ', '.join(rop(*o, 3) for o in DBL))
print('wrote src/crypto/secp256k1/pt.bend, proofs/crypto/secp256k1/ptbr.bend')
print('ADD', PROGS[0].replace('I.', ''))
print('DBL', PROGS[1].replace('I.', ''))
