#!/usr/bin/env python3
"""Generate proofs/tree_map.bend, the TreeMap's public proof entry point.

Every operation theorem of proofs/tree_map/{life,api,capi,vw,vapi}.bend is
re-exported under the operation's name with its statement copied verbatim
(names local to its module qualified), so checking the gate checks the whole
refinement and states it in one place. key_set, values and entry_set are the
implementation's iterator: they are stated over them and proved by
iterator_ok."""
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
TM = ROOT / 'proofs' / 'tree_map'
MODULES = [('LF', 'life'), ('API', 'api'), ('CA', 'capi'), ('VW', 'vw'), ('VA', 'vapi')]

HEADER = '''# Indexed TreeMap (src/containers/balanced_search_tree.bend): public proof
# entry point, generated by tools/generators/tm_gate.py.
#   shadow       ST.Sh: the map's Nat fields (size, root, first and last ids,
#                free head, limit and depth), the node and payload arrays as
#                lists, and two ghost values: the tree of ids (ST.Tr) and the
#                free list; ST.real(sh) is the map
#   abstraction  ST.model(sh): the limit and the entries of the tree's ids in
#                order, as a proofs/spec/tree_map.bend map (sorted entries);
#                a mirror cursor's model is the specification's cursor over
#                that map with the keys of its next and current ids
#                (CU.cmod), a mirror view's the specification's view
#                (VD.vmod)
#   invariant    ST.good(sh): the arrays laid out within the limit, the ghost
#                tree the red-black tree the links describe (parents, sides,
#                colours, black height), every id of the tree a live node with
#                a payload, the free list chained through the vacant slots,
#                the ids of tree and free list without repeats and covering
#                the slots, the entries sorted by a lawful comparator, and the
#                size, root and first/last ids those of the tree
#                (proofs/tree_map/state.bend); a cursor is good when its
#                shadow is and its ids are 0 or ids of the tree (CU.cgood)
#
# Proved for every lawful comparator (O.Order: flip, antisymmetry,
# transitivity), every key and value type (Data), every good shadow, cursor
# and view, and every argument: each operation's result is the real map (or
# cursor, or view) of a good shadow whose model is the specification's
# result, with the same answer (OK.POK / CU.CPOK / VD.VPOK and the like).
#   new, with_limit        a good shadow of the specification's empty map
#   reads                  size, is_empty, get, get_or_default, contains_key,
#                          contains_value, first/last entry and key, the
#                          lower/floor/ceiling/higher entries and keys
#   updates                put, put_if_absent, replace, replace_if_equal,
#                          remove, remove_if_equal, poll_first/last_entry,
#                          clear
#   cursors                iterator, descending_iterator, key_set, values,
#                          entry_set, iterator_next(_key, _value),
#                          iterator_has_next, iterator_set_value,
#                          iterator_remove, iterator_finish
#   views                  sub_map, head_map, tail_map, descending_map,
#                          view_reverse, view_finish, view_get,
#                          view_contains_key, view_put, view_remove,
#                          view_size, view_clear, view_first/last_entry,
#                          view_lower/floor/ceiling/higher_entry,
#                          view_iterator
'''


def split_top(s):
    out, depth, cur = [], 0, ''
    for i, ch in enumerate(s):
        if ch in '<({[':
            depth += 1
        elif ch in '>)}]' and not (ch == '>' and s[i - 1] == '-'):
            depth -= 1
        if ch == ',' and depth == 0:
            out.append(cur.strip())
            cur = ''
        else:
            cur += ch
    if cur.strip():
        out.append(cur.strip())
    return out


def signature(line):
    m = re.match(r'def (\w+)\((.*)\) -> (.*):$', line)
    name, params, ret = m.group(1), m.group(2), m.group(3)
    # the parameter list ends at the first ') -> ' at depth 0
    depth = 0
    for i, ch in enumerate(line):
        if ch in '<({[':
            depth += 1
        elif ch in '>)}]' and not (ch == '>' and line[i - 1] == '-'):
            depth -= 1
            if depth == 0 and line[i:i + 5] == ') -> ':
                params = line[line.index('(') + 1:i]
                ret = line[i + 5:-1]
                break
    return name, params, ret


def rel(path):
    # an import path of proofs/tree_map/X.bend, seen from proofs/
    if path.startswith('../../'):
        return '../' + path[6:]
    if path.startswith('../'):
        return './' + path[3:]
    return './tree_map/' + path[2:]


imports, defs = {}, []
for alias, mod in MODULES:
    text = (TM / (mod + '.bend')).read_text()
    for p, a in re.findall(r'^import (\S+) as (\w+)$', text, re.M):
        imports.setdefault(a, rel(p))
        assert imports[a] == rel(p), (a, p, imports[a])
    local = set(re.findall(r'^def (\w+)\(', text, re.M))
    for line in text.splitlines():
        if not line.startswith('def ') or not re.match(r'def \w+_ok\(', line):
            continue
        name, params, ret = signature(line)
        if alias == 'LF' and name not in ('new_ok', 'with_limit_ok'):
            continue
        q = lambda s: re.sub(r'(?<![\w.~])(' + '|'.join(sorted(local, key=len, reverse=True)) + r')\(', alias + r'.\1(', s)
        params_q, ret_q = q(params), q(ret)
        args = []
        for prm in split_top(params):
            nm = re.match(r'([~+-]?)(\w+)', prm)
            args.append(('~' if nm.group(1) == '~' else '') + nm.group(2))
        defs.append((name, params_q, ret_q, '%s.%s(%s)' % (alias, name, ', '.join(args))))
    imports[alias] = './tree_map/%s.bend' % mod

# key_set, values and entry_set: the iterator
it = [d for d in defs if d[0] == 'iterator_ok'][0]
for op in ['key_set', 'values', 'entry_set']:
    ret = it[2].replace('M.iterator(', 'M.%s(' % op, 1)
    defs.append(('%s_ok' % op, it[1], ret, it[3].replace('CA.iterator_ok', 'CA.iterator_ok')))

out = ['import Base']
for a, p in sorted(imports.items(), key=lambda x: x[1]):
    out.append('import %s as %s' % (p, a))
out.append('')
out.append(HEADER)
for name, params, ret, body in defs:
    out.append('def %s(%s) -> %s:' % (name, params, ret))
    out.append('  ' + body)
    out.append('')
(ROOT / 'proofs' / 'tree_map.bend').write_text('\n'.join(out))
print('%d theorems' % len(defs))
