#!/usr/bin/env python3
"""Generate the indexed TreeMap's shadow, abstraction and invariant
(proofs/containers/balanced_search_tree/state.bend).

The shadow keeps the map's header, the two dynamic arrays' mirror trees
(nodes and payloads share limit, depth and length), a ghost tree of node ids
and the free stack (ghost). Keys and colours are read from the node list, so
every invariant component is a Bool over the shadow's fields: the generator
writes each component, their conjunction goodF, one accessor g_<c> per
component, and good_intro.
"""
import pathlib

ROOT = pathlib.Path(__file__).resolve().parents[2]
STATE = ROOT / "proofs/containers/balanced_search_tree/state.bend"

P = ("~K: Data, ~V: Data, ~cmp: K -> K -> Cmp, +n: Nat, +root: Nat, +lo: Nat, +hi: Nat, +free: Nat, "
     "+l: Nat, +d: Nat, +nl: List<&2, M.Node<K>>, +pl: List<&2, Maybe<&2, V>>, "
     "+t: Tr, +fl: List<&2, Nat>")
A = "n, root, lo, hi, free, l, d, nl, pl, t, fl"
TA = "~K, ~V, ~cmp"
NL = "nl"
PL = "pl"
LEN = "SC.length(M.Node<K>, nl)"
IDS = "ids(t)"

COMPS = [
    ("cl", "Nat.is_le(l, 31n)"),
    ("cd", "Nat.is_le(d, l)"),
    ("ccap", f"Nat.is_le({LEN}, SC.pow2(d))"),
    ("cpl", f"Nat.is_eq(SC.length(Maybe<&2, V>, pl), {LEN})"),
    ("crep", f"rep(~K, t, 0n, {NL})"),
    ("cpay", f"pay(~V, t, {PL})"),
    ("cfll", f"fll(~K, {NL}, fl)"),
    ("cnd", f"NL.nodupn(SC.append(Nat, {IDS}, fl))"),
    ("cin", f"allin(SC.append(Nat, {IDS}, fl), {LEN})"),
    ("clen", f"Nat.is_eq(SC.length(Nat, SC.append(Nat, {IDS}, fl)), {LEN})"),
    ("cord", f"ordered(~K, ~V, ~cmp, ents(~K, ~V, {IDS}, {NL}, {PL}))"),
    ("cblk", f"root_black(~K, t, {NL})"),
    ("csz", f"Nat.is_eq(n, SC.length(Nat, {IDS}))"),
    ("croot", "Nat.is_eq(root, rid(t))"),
    ("clo", f"Nat.is_eq(lo, fst0({IDS}))"),
    ("chi", f"Nat.is_eq(hi, last0({IDS}))"),
    ("cfree", "Nat.is_eq(free, fst0(fl))"),
]
NAMES = [c for c, _ in COMPS]

BASE = '''import Base
import ../../lib/logic.bend as L
import ../../lib/nat.bend as N
import ../../lib/array.bend as AR
import ../../../spec/lib/common.bend as SC
import ../../../spec/containers/balanced_search_tree/main.bend as S
import ../dynamic_array/layout.bend as LY
import ../dynamic_array/state.bend as DAS
import ../../../src/containers/balanced_search_tree.bend as M
import ../../../src/containers/dynamic_array.bend as D
import ./nsr.bend as NR
import ./mk.bend as MK
import ../../lib/nat_list.bend as NL

# The indexed TreeMap's shadow: the header, the node and payload lists (the
# arrays are their canonical blocks, one limit and depth for both; the node
# store is one block per node field, nsr.bend), a ghost
# tree of node ids and the free stack (ghost). Colours, links and keys are
# read from the node list. (generated by tools/generators/tm_state.py)

type Tr is Data:
  TE{}
  TN{id: Nat, left: Tr, right: Tr}

type Sh<-K: Data, -V: Data> is Data:
  SH{n: Nat, root: Nat, lo: Nat, hi: Nat, free: Nat, l: Nat, d: Nat, nl: List<&2, M.Node<K>>, pl: List<&2, Maybe<&2, V>>, t: Tr, fl: List<&2, Nat>}

def nodes(~K: Data, +l: Nat, +d: Nat, +nl: List<&2, M.Node<K>>) -> M.NodeStore<K>:
  NR.real(~K, l, d, nl)

def pays(~V: Data, +l: Nat, +d: Nat, +pl: List<&2, Maybe<&2, V>>) -> D.DynArray<&2, Maybe<&2, V>>:
  DAS.real(Maybe<&2, V>, DAS.Sh{l, d, SC.length(Maybe<&2, V>, pl), MK.mk(Maybe<&2, V>, d, pl)})

def real(~K: Data, ~V: Data, ~cmp: K -> K -> Cmp, sh: Sh<K, V>) -> M.TreeMap<K, V, cmp>:
  match sh:
    case SH{+n, +root, +lo, +hi, +free, +l, +d, +nl, +pl, +t, +fl}:
      M.TM{n, root, lo, hi, free, nodes(~K, l, d, nl), pays(~V, l, d, pl)}

# ---- the ghost tree ----

def rid(t: Tr) -> Nat:
  match t:
    case TE{}:
      0n
    case TN{+i, l, r}:
      i

# the ids in key (in-)order
def ids(t: Tr) -> List<&2, Nat>:
  match t:
    case TE{}:
      Nil{}
    case TN{+i, l, r}:
      SC.append(Nat, ids(l), Con{i, ids(r)})

def fst0(xs: List<&2, Nat>) -> Nat:
  match xs:
    case Nil{}:
      0n
    case Con{+x, t}:
      x

def last0(xs: List<&2, Nat>) -> Nat:
  match xs:
    case Nil{}:
      0n
    case Con{+x, t}:
      match t:
        case Nil{}:
          x
        case Con{+y, +u}:
          last0(Con{y, u})

# ---- nodes read by id ----

def pk(-T: Type, +b: Bool, x: T, y: T) -> T:
  match b:
    case True{}:
      x
    case False{}:
      y

def nth_or(-X: Data, xs: List<&2, X>, +i: Nat, +dflt: X) -> X:
  match xs i:
    case Nil{} _:
      dflt
    case Con{x, t} 0n:
      x
    case Con{x, t} 1n+p:
      nth_or(X, t, p, dflt)

# the node of id (a free sentinel for 0 or an id out of range)
def nd(-K: Data, xs: List<&2, M.Node<K>>, +id: Nat) -> M.Node<K>:
  match id:
    case 0n:
      M.Free{0n}
    case 1n+i:
      nth_or(M.Node<K>, xs, i, M.Free{0n})

def pv(-V: Data, xs: List<&2, Maybe<&2, V>>, +id: Nat) -> Maybe<&2, V>:
  match id:
    case 0n:
      None{}
    case 1n+i:
      nth_or(Maybe<&2, V>, xs, i, None{})

def is_node(-K: Data, x: M.Node<K>, +a: Nat, +b: Nat, +p: Nat) -> Bool:
  match x:
    case M.Free{f}:
      False{}
    case M.N{c, +x1, +x2, +x3, k}:
      Bool.and(Nat.is_eq(x1, a), Bool.and(Nat.is_eq(x2, b), Nat.is_eq(x3, p)))

def is_free(-K: Data, x: M.Node<K>, +q: Nat) -> Bool:
  match x:
    case M.Free{+f}:
      Nat.is_eq(f, q)
    case M.N{c, x1, x2, x3, k}:
      False{}

def is_red(-K: Data, x: M.Node<K>) -> Bool:
  match x:
    case M.Free{f}:
      False{}
    case M.N{+c, x1, x2, x3, k}:
      c

# every node of t links to its children's ids and to its parent p
def rep(~K: Data, t: Tr, +p: Nat, +xs: List<&2, M.Node<K>>) -> Bool:
  match t:
    case TE{}:
      True{}
    case TN{+i, +l, +r}:
      Bool.and(Nat.is_lt(0n, i), Bool.and(is_node(K, nd(K, xs, i), rid(l), rid(r), p), Bool.and(rep(~K, l, i, xs), rep(~K, r, i, xs))))

def some2(-V: Data, m: Maybe<&2, V>) -> Bool:
  match m:
    case None{}:
      False{}
    case Some{v}:
      True{}

# every node of t has a value
def pay(~V: Data, t: Tr, +ys: List<&2, Maybe<&2, V>>) -> Bool:
  match t:
    case TE{}:
      True{}
    case TN{+i, l, r}:
      Bool.and(some2(V, pv(V, ys, i)), Bool.and(pay(~V, l, ys), pay(~V, r, ys)))

# the free stack: each id is a free node pointing to the next (0 last)
def fll(~K: Data, +xs: List<&2, M.Node<K>>, fl: List<&2, Nat>) -> Bool:
  match fl:
    case Nil{}:
      True{}
    case Con{+f, +t}:
      Bool.and(is_free(K, nd(K, xs, f), fst0(t)), fll(~K, xs, t))

# every id in 1..len
def allin(xs: List<&2, Nat>, +len: Nat) -> Bool:
  match xs:
    case Nil{}:
      True{}
    case Con{+x, t}:
      Bool.and(Bool.and(Nat.is_lt(0n, x), Nat.is_le(x, len)), allin(t, len))

# ---- entries ----

def ent(-K: Data, -V: Data, x: M.Node<K>, m: Maybe<&2, V>) -> Maybe<&2, M.Entry<K, V>>:
  match x m:
    case M.N{c, a, b, p, k} Some{v}:
      Some{M.Entry{k, v}}
    case _ _:
      None{}

def cons_m(-X: Data, m: Maybe<&2, X>, xs: List<&2, X>) -> List<&2, X>:
  match m:
    case None{}:
      xs
    case Some{x}:
      Con{x, xs}

# the entries of the ids, in order
def ents(~K: Data, ~V: Data, ix: List<&2, Nat>, +xs: List<&2, M.Node<K>>, +ys: List<&2, Maybe<&2, V>>) -> List<&2, M.Entry<K, V>>:
  match ix:
    case Nil{}:
      Nil{}
    case Con{+i, t}:
      cons_m(M.Entry<K, V>, ent(K, V, nd(K, xs, i), pv(V, ys, i)), ents(~K, ~V, t, xs, ys))

# consecutive keys strictly increasing (the model invariant, stated in the spec)
def ordered(~K: Data, ~V: Data, ~cmp: K -> K -> Cmp, es: List<&2, M.Entry<K, V>>) -> Bool:
  S.ordered(~K, ~V, ~cmp, es)

def root_black(~K: Data, t: Tr, +xs: List<&2, M.Node<K>>) -> Bool:
  match t:
    case TE{}:
      True{}
    case TN{+i, l, r}:
      Bool.not(is_red(K, nd(K, xs, i)))

def model(~K: Data, ~V: Data, ~cmp: K -> K -> Cmp, sh: Sh<K, V>) -> S.Model<K, V>:
  match sh:
    case SH{+n, +root, +lo, +hi, +free, +l, +d, +nl, +pl, +t, +fl}:
      S.TM{l, ents(~K, ~V, ids(t), nl, pl)}

# ---- the invariant ----
'''


def call(c, pre="", args=A):
    return f"{pre}{c}({TA}, {args})"


def rest(i):
    if i == len(NAMES) - 1:
        return call(NAMES[i])
    return f"Bool.and({call(NAMES[i])}, {rest(i + 1)})"


def T_(x):
    return "{" + x + " == True{} : Bool}"


def intro(i, hs):
    if i == len(NAMES) - 1:
        return hs[i]
    return f"L.and_intro({call(NAMES[i])}, {rest(i + 1)}, {hs[i]}, {intro(i + 1, hs)})"


def block():
    out = [BASE]
    for c, body in COMPS:
        out.append(f"def {c}({P}) -> Bool:\n  {body}\n")
    out.append(f"def goodF({P}) -> Bool:\n  {rest(0)}\n")
    out.append(f'''def good(~K: Data, ~V: Data, ~cmp: K -> K -> Cmp, sh: Sh<K, V>) -> Bool:
  match sh:
    case SH{{+n, +root, +lo, +hi, +free, +l, +d, +nl, +pl, +t, +fl}}:
      goodF({TA}, {A})
''')
    prs = ["g"]
    for i in range(len(NAMES) - 1):
        prs.append(f"L.and_right({call(NAMES[i])}, {rest(i + 1)}, {prs[i]})")
    for i, c in enumerate(NAMES):
        body = f"L.and_left({call(c)}, {rest(i + 1)}, {prs[i]})" if i < len(NAMES) - 1 else prs[i]
        out.append(f"def g_{c}({P}, +g: {T_(call('goodF'))}) -> {T_(call(c))}:\n  {body}\n")
    hs = ", ".join(f"+h_{c}: {T_(call(c))}" for c in NAMES)
    out.append("# the invariant from its components\n"
               f"def good_intro({P}, {hs}) -> {T_(call('goodF'))}:\n  {intro(0, ['h_' + c for c in NAMES])}\n")
    return "\n".join(out)


def main():
    STATE.write_text(block())


if __name__ == "__main__":
    main()
