#!/usr/bin/env python3
"""Lower straight-line state threading into Bend helpers (no runtime framework).

The algorithms below use explicit red-black links and DynArray values.
Generated helpers only unpack returned pairs: they do not introduce a runtime
interpreter, FFI, or hidden storage. Regenerate src/balanced_search_tree.bend with this file.
"""
from pathlib import Path
import re
ROOT=Path(__file__).resolve().parents[2]
T='TreeMap<K, V, cmp>'
P='~K: Data, ~V: Data, ~cmp: K -> K -> Cmp'
A='~K, ~V, ~cmp'
parts=[]

def raw(s):parts.append(s.strip()+'\n\n')

def fun(name,params,result,body):
    params=re.sub(r'(?<![+\w])(\w+): (Nat|Bool|K|V|Node<K>|Fix|Search)(?=,|$)', r'+\1: \2', params)
    raw(f'def {name}({P}'+(', '+params if params else '')+f') -> {result}:\n'+body)

# A small source-generation aid for ownership-threaded calls. Each step is
# ([(name,type),...], call). Fresh variable names make every move explicit.
def seq(name,params,result,steps,expr):
    env=dict(params)
    def build(j,known):
        if j==len(steps):return expr
        binds,call=steps[j]
        rest=' '.join(x[1] for x in steps[j+1:])+' '+expr
        newnames={k for k,t in binds}
        captures=[(k,t) for k,t in known.items() if k not in newnames and re.search(r'\b'+re.escape(k)+r'\b',rest)]
        inner=build(j+1,dict(captures+binds))
        n=f'{name}_{j+1}'
        rtype=' & '.join(t for k,t in binds)
        pattern=', '.join('+'+k if t in ['Nat','Bool','Cmp','K','V','Node<K>','Search'] else k for k,t in binds)
        sig=', '.join(('+' if t in ['Nat','Bool','Cmp','K','V','Node<K>','Search'] else '')+k+': '+t for k,t in captures)
        fun(n,(sig+', ' if sig else '')+'pair_result: '+rtype,result,f'  ({pattern}) = pair_result\n  '+inner)
        return f'{n}({A}'+('' if not captures else ', '+', '.join(k for k,t in captures))+', '+call+')'
    body=build(0,env)
    sig=', '.join(('+' if t in ['Nat','Bool','Cmp','K','V','Node<K>','Search'] else '')+k+': '+t for k,t in params)
    fun(name,sig,result,'  '+body)

raw('''# Generated by tools/generators/tree_map.py; edit algorithm definitions there.
import Base
import ./dynamic_array.bend as D
import ./types/dynamic_array.bend as DE

# Indexed CLRS red-black map. Keys and values are Data for this version.
# Comparator is a type index: changing comparator requires rebuilding a map.
# Node links are slot indices plus one; zero is the black NIL sentinel.
type Node<-K: Data> is Data:
  Free{next: Nat}
  N{red: Bool, left: Nat, right: Nat, parent: Nat, key: K}

# Node storage: one array per node field instead of one array of Node
# records. Reading a record out of an array hands back a shared copy that the
# runtime reference-counts and takes apart field by field; a field read out of
# its own array is a plain word. The store has the shape of a dynamic array
# of nodes: slots [0, used) are live, the capacity is 2^depth <= 2^limit, and
# it grows by doubling. A slot holds the encoding of its node by ntag (0 free,
# 1 black, 2 red), nleft (the free-list link of a free slot), nright, nparent
# and nkey (None when free); every other slot holds the encoding of Free{0},
# so each array is exactly its field of the node list, padded.
type NodeStore<-K: Data> is Type:
  NS{limit: Nat, depth: Nat, cap: Nat, used: Nat, tags: Array<Nat>, lefts: Array<Nat>, rights: Array<Nat>, parents: Array<Nat>, keys: Array<Maybe<&2, K>>}

def ntag(~K: Data, n: Node<K>) -> Nat:
  match n:
    case Free{x}:
      0n
    case N{c, l, r, p, k}:
      match c:
        case True{}:
          2n
        case False{}:
          1n

def nleft(~K: Data, n: Node<K>) -> Nat:
  match n:
    case Free{x}:
      x
    case N{c, l, r, p, k}:
      l

def nright(~K: Data, n: Node<K>) -> Nat:
  match n:
    case Free{x}:
      0n
    case N{c, l, r, p, k}:
      r

def nparent(~K: Data, n: Node<K>) -> Nat:
  match n:
    case Free{x}:
      0n
    case N{c, l, r, p, k}:
      p

def nkey(~K: Data, n: Node<K>) -> Maybe<&2, K>:
  match n:
    case Free{x}:
      None{}
    case N{c, l, r, p, k}:
      Some{k}

def mk_node(~K: Data, +t: Nat, +l: Nat, +r: Nat, +p: Nat, k: Maybe<&2, K>) -> Node<K>:
  match t k:
    case 0n _:
      Free{l}
    case 1n+ +c Some{key}:
      N{Nat.is_eq(c, 1n), l, r, p, key}
    case 1n+ +c None{}:
      Free{l}

def ns_nats(+d: Nat) -> Array<Nat>:
  Array.new(Nat, d, 0n)

def ns_nokeys(~K: Data, +d: Nat) -> Array<Maybe<&2, K>>:
  Array.new(Maybe<&2, K>, d, None{})

def ns_empty(~K: Data, +limit: Nat) -> NodeStore<K>:
  NS{limit, 0n, 1n, 0n, ns_nats(0n), ns_nats(0n), ns_nats(0n), ns_nats(0n), ns_nokeys(~K, 0n)}

def ns_new(~K: Data) -> NodeStore<K>:
  ns_empty(~K, D.max_depth())

def ns_with_limit(~K: Data, +k: Nat) -> NodeStore<K>:
  ns_empty(~K, D.clamp_limit(k, Nat.is_lt(k, D.max_depth())))

def ns_length(~K: Data, s: NodeStore<K>) -> NodeStore<K> & Nat:
  NS{limit, depth, cap, +used, tags, lefts, rights, parents, keys} = s
  (NS{limit, depth, cap, used, tags, lefts, rights, parents, keys}, used)

# ---- reading a slot ----

def ns_rk(~K: Data, +limit: Nat, +depth: Nat, +cap: Nat, +used: Nat, tags: Array<Nat>, lefts: Array<Nat>, rights: Array<Nat>, parents: Array<Nat>, +t: Nat, +l: Nat, +r: Nat, +p: Nat, q: Array<Maybe<&2, K>> & Maybe<&2, K>) -> NodeStore<K> & Result<&2, &2, DE.Error, Node<K>>:
  (keys, k) = q
  (NS{limit, depth, cap, used, tags, lefts, rights, parents, keys}, Done{mk_node(~K, t, l, r, p, k)})

def ns_rp(~K: Data, +limit: Nat, +depth: Nat, +cap: Nat, +used: Nat, tags: Array<Nat>, lefts: Array<Nat>, rights: Array<Nat>, keys: Array<Maybe<&2, K>>, +i: U32, +t: Nat, +l: Nat, +r: Nat, q: Array<Nat> & Nat) -> NodeStore<K> & Result<&2, &2, DE.Error, Node<K>>:
  (parents, +p) = q
  ns_rk(~K, limit, depth, cap, used, tags, lefts, rights, parents, t, l, r, p, Array.get(Maybe<&2, K>, keys, i))

def ns_rr(~K: Data, +limit: Nat, +depth: Nat, +cap: Nat, +used: Nat, tags: Array<Nat>, lefts: Array<Nat>, parents: Array<Nat>, keys: Array<Maybe<&2, K>>, +i: U32, +t: Nat, +l: Nat, q: Array<Nat> & Nat) -> NodeStore<K> & Result<&2, &2, DE.Error, Node<K>>:
  (rights, +r) = q
  ns_rp(~K, limit, depth, cap, used, tags, lefts, rights, keys, i, t, l, r, Array.get(Nat, parents, i))

def ns_rl(~K: Data, +limit: Nat, +depth: Nat, +cap: Nat, +used: Nat, tags: Array<Nat>, rights: Array<Nat>, parents: Array<Nat>, keys: Array<Maybe<&2, K>>, +i: U32, +t: Nat, q: Array<Nat> & Nat) -> NodeStore<K> & Result<&2, &2, DE.Error, Node<K>>:
  (lefts, +l) = q
  ns_rr(~K, limit, depth, cap, used, tags, lefts, parents, keys, i, t, l, Array.get(Nat, rights, i))

def ns_rt(~K: Data, +limit: Nat, +depth: Nat, +cap: Nat, +used: Nat, lefts: Array<Nat>, rights: Array<Nat>, parents: Array<Nat>, keys: Array<Maybe<&2, K>>, +i: U32, q: Array<Nat> & Nat) -> NodeStore<K> & Result<&2, &2, DE.Error, Node<K>>:
  (tags, +t) = q
  ns_rl(~K, limit, depth, cap, used, tags, rights, parents, keys, i, t, Array.get(Nat, lefts, i))

def ns_get_ok(~K: Data, +limit: Nat, +depth: Nat, +cap: Nat, +used: Nat, tags: Array<Nat>, lefts: Array<Nat>, rights: Array<Nat>, parents: Array<Nat>, keys: Array<Maybe<&2, K>>, +i: Nat, ok: Bool) -> NodeStore<K> & Result<&2, &2, DE.Error, Node<K>>:
  match ok:
    case True{}:
      ns_rt(~K, limit, depth, cap, used, lefts, rights, parents, keys, U32.from_nat(i), Array.get(Nat, tags, U32.from_nat(i)))
    case False{}:
      (NS{limit, depth, cap, used, tags, lefts, rights, parents, keys}, Fail{DE.IndexOutOfRange{}})

def ns_get(~K: Data, s: NodeStore<K>, +i: Nat) -> NodeStore<K> & Result<&2, &2, DE.Error, Node<K>>:
  NS{limit, depth, cap, +used, tags, lefts, rights, parents, keys} = s
  ns_get_ok(~K, limit, depth, cap, used, tags, lefts, rights, parents, keys, i, Nat.is_lt(i, used))

# ---- writing a slot: the encoding of the node in all five arrays ----

def ns_put(~K: Data, +limit: Nat, +depth: Nat, +cap: Nat, +used: Nat, tags: Array<Nat>, lefts: Array<Nat>, rights: Array<Nat>, parents: Array<Nat>, keys: Array<Maybe<&2, K>>, +i: U32, +node: Node<K>) -> NodeStore<K>:
  NS{limit, depth, cap, used, Array.set(Nat, tags, i, ntag(~K, node)), Array.set(Nat, lefts, i, nleft(~K, node)), Array.set(Nat, rights, i, nright(~K, node)), Array.set(Nat, parents, i, nparent(~K, node)), Array.set(Maybe<&2, K>, keys, i, nkey(~K, node))}

def ns_set_ok(~K: Data, +limit: Nat, +depth: Nat, +cap: Nat, +used: Nat, tags: Array<Nat>, lefts: Array<Nat>, rights: Array<Nat>, parents: Array<Nat>, keys: Array<Maybe<&2, K>>, +i: Nat, +node: Node<K>, ok: Bool) -> NodeStore<K> & Result<&2, &2, DE.Error, Unit>:
  match ok:
    case True{}:
      (ns_put(~K, limit, depth, cap, used, tags, lefts, rights, parents, keys, U32.from_nat(i), node), Done{Unit{}})
    case False{}:
      (NS{limit, depth, cap, used, tags, lefts, rights, parents, keys}, Fail{DE.IndexOutOfRange{}})

def ns_set(~K: Data, s: NodeStore<K>, +i: Nat, +node: Node<K>) -> NodeStore<K> & Result<&2, &2, DE.Error, Unit>:
  NS{limit, depth, cap, +used, tags, lefts, rights, parents, keys} = s
  ns_set_ok(~K, limit, depth, cap, used, tags, lefts, rights, parents, keys, i, node, Nat.is_lt(i, used))

# ---- appending a slot ----

def ns_grow_nats(+depth: Nat, a: Array<Nat>) -> Array<Nat>:
  ANode{a, ns_nats(depth)}

def ns_grow_keys(~K: Data, +depth: Nat, a: Array<Maybe<&2, K>>) -> Array<Maybe<&2, K>>:
  ANode{a, ns_nokeys(~K, depth)}

def ns_push_room(~K: Data, +limit: Nat, +depth: Nat, +cap: Nat, +used: Nat, tags: Array<Nat>, lefts: Array<Nat>, rights: Array<Nat>, parents: Array<Nat>, keys: Array<Maybe<&2, K>>, +node: Node<K>, room: Bool, grow: Bool) -> NodeStore<K> & Result<&2, &2, DE.Error, Unit>:
  match room grow:
    case True{} _:
      (ns_put(~K, limit, depth, cap, 1n+used, tags, lefts, rights, parents, keys, U32.from_nat(used), node), Done{Unit{}})
    case False{} True{}:
      (ns_put(~K, limit, 1n+depth, Nat.double(cap), 1n+used, ns_grow_nats(depth, tags), ns_grow_nats(depth, lefts), ns_grow_nats(depth, rights), ns_grow_nats(depth, parents), ns_grow_keys(~K, depth, keys), U32.from_nat(used), node), Done{Unit{}})
    case False{} False{}:
      (NS{limit, depth, cap, used, tags, lefts, rights, parents, keys}, Fail{DE.CapacityExceeded{}})

def ns_push(~K: Data, s: NodeStore<K>, +node: Node<K>) -> NodeStore<K> & Result<&2, &2, DE.Error, Unit>:
  NS{+limit, +depth, +cap, +used, tags, lefts, rights, parents, keys} = s
  ns_push_room(~K, limit, depth, cap, used, tags, lefts, rights, parents, keys, node, Nat.is_lt(used, cap), Nat.is_lt(depth, limit))

# ---- dropping slots: the dropped slots get the encoding of Free{0} back ----

def ns_drop(~K: Data, s: NodeStore<K>, +m: Nat) -> NodeStore<K>:
  NS{limit, depth, cap, used, tags, lefts, rights, parents, keys} = s
  ns_put(~K, limit, depth, cap, m, tags, lefts, rights, parents, keys, U32.from_nat(m), Free{0n})

def ns_pop_fin(~K: Data, +m: Nat, r: NodeStore<K> & Result<&2, &2, DE.Error, Node<K>>) -> NodeStore<K> & Result<&2, &2, DE.Error, Node<K>>:
  (s, x) = r
  (ns_drop(~K, s, m), x)

def ns_pop_n(~K: Data, +limit: Nat, +depth: Nat, +cap: Nat, used: Nat, tags: Array<Nat>, lefts: Array<Nat>, rights: Array<Nat>, parents: Array<Nat>, keys: Array<Maybe<&2, K>>) -> NodeStore<K> & Result<&2, &2, DE.Error, Node<K>>:
  match used:
    case 0n:
      (NS{limit, depth, cap, 0n, tags, lefts, rights, parents, keys}, Fail{DE.EmptyArray{}})
    case 1n+ +m:
      ns_pop_fin(~K, m, ns_get(~K, NS{limit, depth, cap, 1n+m, tags, lefts, rights, parents, keys}, m))

def ns_pop(~K: Data, s: NodeStore<K>) -> NodeStore<K> & Result<&2, &2, DE.Error, Node<K>>:
  NS{+limit, +depth, +cap, used, tags, lefts, rights, parents, keys} = s
  ns_pop_n(~K, limit, depth, cap, used, tags, lefts, rights, parents, keys)

def ns_clear_go(~K: Data, k: Nat, s: NodeStore<K>) -> NodeStore<K>:
  match k:
    case 0n:
      s
    case 1n+ +m:
      ns_clear_go(~K, m, ns_drop(~K, s, m))

# O(used): resets the live slots top down and keeps the capacity.
def ns_clear(~K: Data, s: NodeStore<K>) -> NodeStore<K>:
  NS{limit, depth, cap, +used, tags, lefts, rights, parents, keys} = s
  ns_clear_go(~K, used, NS{limit, depth, cap, used, tags, lefts, rights, parents, keys})

type TreeMap<-K: Data, -V: Data, -cmp: K -> K -> Cmp> is Type:
  TM{size: Nat, root: Nat, first: Nat, last: Nat, free: Nat,
     nodes: NodeStore<K>, values: D.DynArray<&2, Maybe<&2, V>>}

type Entry<-K: Data, -V: Data> is Data:
  Entry{key: K, value: V}

type Error is Data:
  CapacityExceeded{}
  OutOfRange{}
  NoCurrent{}
  InvalidBounds{}

type Rejected<-K: Data, -V: Data> is Data:
  Rejected{error: Error, key: K, value: V}

type Search is Data:
  Search{found: Nat, parent: Nat, left: Bool}

def pick(-T: Type, b: Bool, yes: T, no: T) -> T:
  match b:
    case True{}:
      yes
    case False{}:
      no

def red(-K: Data, n: Node<K>) -> Bool:
  match n:
    case Free{x}:
      False{}
    case N{c, l, r, p, k}:
      c

def left(-K: Data, n: Node<K>) -> Nat:
  match n:
    case Free{x}:
      0n
    case N{c, l, r, p, k}:
      l

def right(-K: Data, n: Node<K>) -> Nat:
  match n:
    case Free{x}:
      0n
    case N{c, l, r, p, k}:
      r

def parent(-K: Data, n: Node<K>) -> Nat:
  match n:
    case Free{x}:
      0n
    case N{c, l, r, p, k}:
      p

def node_key(-K: Data, n: Node<K>) -> Maybe<&2, K>:
  match n:
    case Free{x}:
      None{}
    case N{c, l, r, p, k}:
      Some{k}

def child(-K: Data, +n: Node<K>, forward: Bool) -> Nat:
  pick(Nat, forward, right(K, n), left(K, n))

# All links reference live slots. Free slots contain no key and no value.
''')
fun('new','',T,'  TM{0n, 0n, 0n, 0n, 0n, ns_new(~K), D.new_at(~Maybe<&2, V>)}')
fun('size',f'm: {T}',T+' & Nat','  TM{+n, root, lo, hi, free, nodes, values} = m\n  (TM{n, root, lo, hi, free, nodes, values}, n)')
fun('root_id',f'm: {T}',T+' & Nat','  TM{n, +root, lo, hi, free, nodes, values} = m\n  (TM{n, root, lo, hi, free, nodes, values}, root)')
fun('first_id',f'm: {T}',T+' & Nat','  TM{n, root, +lo, hi, free, nodes, values} = m\n  (TM{n, root, lo, hi, free, nodes, values}, lo)')
fun('last_id',f'm: {T}',T+' & Nat','  TM{n, root, lo, +hi, free, nodes, values} = m\n  (TM{n, root, lo, hi, free, nodes, values}, hi)')
fun('read_finish','n: Nat, root: Nat, lo: Nat, hi: Nat, free: Nat, values: D.DynArray<&2, Maybe<&2, V>>, r: NodeStore<K> & Result<&2, &2, DE.Error, Node<K>>',T+' & Node<K>', '''  match r:
    case Tuple{nodes, Done{x}}:
      (TM{n, root, lo, hi, free, nodes, values}, x)
    case Tuple{nodes, Fail{e}}:
      (TM{n, root, lo, hi, free, nodes, values}, Free{0n})''')
fun('read',f'm: {T}, id: Nat',T+' & Node<K>',f'''  match m id:
    case mm 0n:
      (mm, Free{{0n}})
    case TM{{n, root, lo, hi, free, nodes, values}} 1n+i:
      read_finish({A}, n, root, lo, hi, free, values, ns_get(~K, nodes, i))''')
fun('write_finish','n: Nat, root: Nat, lo: Nat, hi: Nat, free: Nat, values: D.DynArray<&2, Maybe<&2, V>>, r: NodeStore<K> & Result<&2, &2, DE.Error, Unit>',T,'''  (nodes, status) = r
  TM{n, root, lo, hi, free, nodes, values}''')
fun('write',f'm: {T}, id: Nat, node: Node<K>',T,f'''  match m id:
    case mm 0n:
      mm
    case TM{{n, root, lo, hi, free, nodes, values}} 1n+i:
      write_finish({A}, n, root, lo, hi, free, values, ns_set(~K, nodes, i, node))''')
for field,typ in [('left','Nat'),('right','Nat'),('parent','Nat'),('red','Bool')]:
    names=['c','l','r','p','k'];replacement={'left':1,'right':2,'parent':3,'red':0}[field];names[replacement]='v'
    fun('set_'+field+'_node',f'm: {T}, id: Nat, v: {typ}, node: Node<K>',T,f'''  match node:
    case Free{{next}}:
      m
    case N{{c, l, r, p, k}}:
      write({A}, m, id, N{{{', '.join(names)}}})''')
    seq('set_'+field,[('m',T),('id','Nat'),('v',typ)],T,[([('m1',T),('node','Node<K>')],f'read({A}, m, id)')],f'set_{field}_node({A}, m1, id, v, node)')
fun('set_root',f'm: {T}, root: Nat',T,'  TM{n, old, lo, hi, free, nodes, values} = m\n  TM{n, root, lo, hi, free, nodes, values}')
fun('attach_side',f'm: {T}, p: Nat, x: Nat, on_left: Bool',T,f'''  match p on_left:
    case 0n _:
      set_root({A}, m, x)
    case 1n+q True{{}}:
      set_left({A}, m, 1n+q, x)
    case 1n+q False{{}}:
      set_right({A}, m, 1n+q, x)''')
# Replace a parent edge, then install the child's parent. NIL has no slot.
seq('attach',[('m',T),('p','Nat'),('x','Nat'),('on_left','Bool')],T,[],f'set_parent({A}, attach_side({A}, m, p, x, on_left), x, p)')
# Ordinary rotations. The moving subtree's parent and the external parent
# edge are updated as well; no node/value allocation occurs.
for direction in ['left','right']:
    side='right' if direction=='left' else 'left'
    other=direction
    seq('rotate_'+direction,[('m',T),('x','Nat')],T,[
      ([('m1',T),('xn','Node<K>')],f'read({A}, m, x)'),
      ([('m2',T),('yn','Node<K>')],f'read({A}, m1, {side}(K, xn))'),
      ([('m3',T),('pn','Node<K>')],f'read({A}, m2, parent(K, xn))')],
      f'set_parent({A}, set_{other}({A}, attach({A}, set_parent({A}, set_{side}({A}, m3, x, {other}(K, yn)), {other}(K, yn), x), parent(K, xn), {side}(K, xn), Nat.is_eq(left(K, pn), x)), {side}(K, xn), x), x, {side}(K, xn))')
# Search returns both a hit or the insertion edge in one traversal.
fun('probe_node',f'id: Nat, k: K, r: {T} & Node<K>',T+' & (Node<K> & Cmp)',f'''  match r:
    case Tuple{{m, Free{{next}}}}:
      (m, (Free{{next}}, EQ{{}}))
    case Tuple{{m, N{{c, l, r, p, +key}}}}:
      (m, (N{{c, l, r, p, key}}, cmp(k, key)))''')
fun('probe',f'm: {T}, +id: Nat, k: K',T+' & (Node<K> & Cmp)',f'  probe_node({A}, id, k, read({A}, m, id))')
fun('search_loop',f'fuel: Nat, +k: K, +id: Nat, p: Nat, on_left: Bool, st: {T} & (Node<K> & Cmp)',T+' & Search',f'''  match fuel st:
    case 0n Tuple{{m, node}}:
      (m, Search{{0n, p, on_left}})
    case 1n+f Tuple{{m, Tuple{{Free{{next}}, order}}}}:
      (m, Search{{0n, p, on_left}})
    case 1n+f Tuple{{m, Tuple{{N{{c, +l, r, p0, key}}, LT{{}}}}}}:
      search_loop({A}, f, k, l, id, True{{}}, probe({A}, m, l, k))
    case 1n+f Tuple{{m, Tuple{{N{{c, l, +r, p0, key}}, GT{{}}}}}}:
      search_loop({A}, f, k, r, id, False{{}}, probe({A}, m, r, k))
    case 1n+f Tuple{{m, Tuple{{N{{c, l, r, p0, key}}, EQ{{}}}}}}:
      (m, Search{{id, p, on_left}})''')
fun('search',f'm: {T}, +k: K',T+' & Search',f'''  TM{{+n, +root, lo, hi, free, nodes, values}} = m
  search_loop({A}, 1n+n, k, root, 0n, False{{}}, probe({A}, TM{{n, root, lo, hi, free, nodes, values}}, root, k))''')
# Exchange moves an value. None represents a free payload slot.
fun('exchange_finish','n: Nat, root: Nat, lo: Nat, hi: Nat, free: Nat, nodes: NodeStore<K>, r: D.DynArray<&2, Maybe<&2, V>> & Result<&2, &2, DE.Error, Maybe<&2, V>>',T+' & Maybe<&2, V>', """  match r:
    case Tuple{values, Done{old}}:
      (TM{n, root, lo, hi, free, nodes, values}, old)
    case Tuple{values, Fail{e}}:
      (TM{n, root, lo, hi, free, nodes, values}, None{})""")
fun('exchange',f'm: {T}, id: Nat, value: Maybe<&2, V>',T+' & Maybe<&2, V>',f'''  match m id:
    case mm 0n:
      (mm, None{{}})
    case TM{{n, root, lo, hi, free, nodes, values}} 1n+i:
      exchange_finish({A}, n, root, lo, hi, free, nodes, D.swap_at(~Maybe<&2, V>, values, i, value))''')
# Root is black on every public operation boundary.
seq('black_root',[('m',T)],T,[([('m1',T),('r','Nat')],f'root_id({A}, m)')],f'set_red({A}, m1, r, False{{}})')

# More algorithms are appended below before emitting.
raw('''type Fix is Data:
  Fix{node: Nat, more: Bool}
''')
for side,opposite in [('left','right'),('right','left')]:
    # p is on side of g; triangle is the opposite child of p.
    fun('insert_black_'+side,f'm: {T}, z: Nat, p: Nat, g: Nat, triangle: Bool',T+' & Fix',f'''  match triangle:
    case True{{}}:
      (rotate_{opposite}({A}, set_red({A}, set_red({A}, rotate_{side}({A}, m, p), z, False{{}}), g, True{{}}), g), Fix{{0n, False{{}}}})
    case False{{}}:
      (rotate_{opposite}({A}, set_red({A}, set_red({A}, m, p, False{{}}), g, True{{}}), g), Fix{{0n, False{{}}}})''')
    fun('insert_uncle_'+side,f'm: {T}, z: Nat, p: Nat, g: Nat, u: Nat, triangle: Bool, uncle: Node<K>',T+' & Fix',f'''  match uncle:
    case N{{True{{}}, l, r, gp, k}}:
      (set_red({A}, set_red({A}, set_red({A}, m, p, False{{}}), u, False{{}}), g, True{{}}), Fix{{g, True{{}}}})
    case _:
      insert_black_{side}({A}, m, z, p, g, triangle)''')
    seq('insert_side_'+side,[('m',T),('z','Nat'),('p','Nat'),('g','Nat'),('pn','Node<K>'),('gn','Node<K>')],T+' & Fix',
        [([('m1',T),('un','Node<K>')],f'read({A}, m, {opposite}(K, gn))')],f'insert_uncle_{side}({A}, m1, z, p, g, {opposite}(K, gn), Nat.is_eq(z, {opposite}(K, pn)), un)')
fun('insert_side',f'm: {T}, z: Nat, p: Nat, g: Nat, pn: Node<K>, gn: Node<K>, on_left: Bool',T+' & Fix',f'''  match on_left:
    case True{{}}:
      insert_side_left({A}, m, z, p, g, pn, gn)
    case False{{}}:
      insert_side_right({A}, m, z, p, g, pn, gn)''')
seq('insert_grand',[('m',T),('z','Nat'),('p','Nat'),('pn','Node<K>')],T+' & Fix',[([('m1',T),('gn','Node<K>')],f'read({A}, m, parent(K, pn))')],f'insert_side({A}, m1, z, p, parent(K, pn), pn, gn, Nat.is_eq(p, left(K, gn)))')
fun('insert_parent',f'm: {T}, z: Nat, p: Nat, pn: Node<K>, is_red: Bool',T+' & Fix',f'''  match is_red:
    case False{{}}:
      (m, Fix{{0n, False{{}}}})
    case True{{}}:
      insert_grand({A}, m, z, p, pn)''')
seq('insert_fix_step',[('m',T),('z','Nat')],T+' & Fix',[
 ([('m1',T),('zn','Node<K>')],f'read({A}, m, z)'),
 ([('m2',T),('pn','Node<K>')],f'read({A}, m1, parent(K, zn))')],f'insert_parent({A}, m2, z, parent(K, zn), pn, red(K, pn))')
fun('insert_fix_loop',f'fuel: Nat, st: {T} & Fix',T,f'''  match fuel st:
    case 0n Tuple{{m, f}}:
      black_root({A}, m)
    case 1n+p Tuple{{m, Fix{{z, False{{}}}}}}:
      black_root({A}, m)
    case 1n+p Tuple{{m, Fix{{z, True{{}}}}}}:
      insert_fix_loop({A}, p, insert_fix_step({A}, m, z))''')
# Append failure rolls back the metadata append, retaining rejected values.
fun('append_rollback','n: Nat, root: Nat, lo: Nat, hi: Nat, free: Nat, values: D.DynArray<&2, Maybe<&2, V>>, k: K, v: V, r: NodeStore<K> & Result<&2, &2, DE.Error, Node<K>>',T+' & Result<&2, &2, Rejected<K, V>, Nat>', '''  (nodes, dropped) = r
  (TM{n, root, lo, hi, free, nodes, values}, Fail{Rejected{CapacityExceeded{}, k, v}})''')
fun('append_values','n: Nat, root: Nat, lo: Nat, hi: Nat, free: Nat, nodes: NodeStore<K>, k: K, v: V, id: Nat, r: D.DynArray<&2, Maybe<&2, V>> & Result<&2, &2, DE.Error, Unit>',T+' & Result<&2, &2, Rejected<K, V>, Nat>',f"""  match r:
    case Tuple{{values, Done{{u}}}}:
      (TM{{n, root, lo, hi, free, nodes, values}}, Done{{id}})
    case Tuple{{values, Fail{{e}}}}:
      append_rollback({A}, n, root, lo, hi, free, values, k, v, ns_pop(~K, nodes))""")
fun('append_nodes','n: Nat, root: Nat, lo: Nat, hi: Nat, free: Nat, values: D.DynArray<&2, Maybe<&2, V>>, k: K, v: V, id: Nat, r: NodeStore<K> & Result<&2, &2, DE.Error, Unit>',T+' & Result<&2, &2, Rejected<K, V>, Nat>',f'''  match r:
    case Tuple{{nodes, Done{{u}}}}:
      append_values({A}, n, root, lo, hi, free, nodes, k, v, id, D.push_at(~Maybe<&2, V>, values, Some{{v}}))
    case Tuple{{nodes, Fail{{e}}}}:
      (TM{{n, root, lo, hi, free, nodes, values}}, Fail{{Rejected{{CapacityExceeded{{}}, k, v}}}})''')
fun('append_count','n: Nat, root: Nat, lo: Nat, hi: Nat, free: Nat, values: D.DynArray<&2, Maybe<&2, V>>, +k: K, v: V, p: Nat, r: NodeStore<K> & Nat',T+' & Result<&2, &2, Rejected<K, V>, Nat>',f'''  (nodes, +used) = r
  append_nodes({A}, n, root, lo, hi, free, values, k, v, 1n+used, ns_push(~K, nodes, N{{True{{}}, 0n, 0n, p, k}}))''')
fun('append',f'm: {T}, k: K, v: V, p: Nat',T+' & Result<&2, &2, Rejected<K, V>, Nat>',f'''  TM{{n, root, lo, hi, free, nodes, values}} = m
  append_count({A}, n, root, lo, hi, free, values, k, v, p, ns_length(~K, nodes))''')
fun('free_header',f'm: {T}, free: Nat',T,'  TM{n, root, lo, hi, old, nodes, values} = m\n  TM{n, root, lo, hi, free, nodes, values}')
seq('reuse_slot',[('m',T),('id','Nat'),('next','Nat'),('p','Nat'),('k','K'),('v','V')],T+' & Result<&2, &2, Rejected<K, V>, Nat>',[
 ([('m1',T),('old','Maybe<&2, V>')],f'exchange({A}, write({A}, free_header({A}, m, next), id, N{{True{{}}, 0n, 0n, p, k}}), id, Some{{v}})')], '(m1, Done{id})')
fun('alloc_read',f'id: Nat, p: Nat, k: K, v: V, r: {T} & Node<K>',T+' & Result<&2, &2, Rejected<K, V>, Nat>',f'''  match r:
    case Tuple{{m, Free{{next}}}}:
      reuse_slot({A}, m, id, next, p, k, v)
    case Tuple{{m, N{{c, l, r, q, oldk}}}}:
      (m, Fail{{Rejected{{CapacityExceeded{{}}, k, v}}}})''')
fun('allocate',f'm: {T}, p: Nat, k: K, v: V',T+' & Result<&2, &2, Rejected<K, V>, Nat>',f'''  TM{{n, root, lo, hi, free, nodes, values}} = m
  match free:
    case 0n:
      append({A}, TM{{n, root, lo, hi, 0n, nodes, values}}, k, v, p)
    case 1n+ +f:
      alloc_read({A}, 1n+f, p, k, v, read({A}, TM{{n, root, lo, hi, 1n+f, nodes, values}}, 1n+f))''')
fun('insert_header',f'm: {T}, +id: Nat, +p: Nat, +on_left: Bool',T,f'''  TM{{+n, root, +lo, +hi, free, nodes, values}} = m
  TM{{1n+n, root, pick(Nat, Bool.or(Nat.is_eq(n, 0n), Bool.and(on_left, Nat.is_eq(p, lo))), id, lo), pick(Nat, Bool.or(Nat.is_eq(n, 0n), Bool.and(Bool.not(on_left), Nat.is_eq(p, hi))), id, hi), free, nodes, values}}''')
fun('insert_fixed',f'+id: Nat, r: {T} & Nat',T,f'''  (m, n) = r
  insert_fix_loop({A}, 1n+n, (m, Fix{{id, True{{}}}}))''')
fun('put_allocated',f'+p: Nat, +on_left: Bool, r: {T} & Result<&2, &2, Rejected<K, V>, Nat>',T+' & Result<&2, &2, Rejected<K, V>, Maybe<&2, V>>',f'''  match r:
    case Tuple{{m, Done{{+id}}}}:
      (insert_fixed({A}, id, size({A}, insert_header({A}, attach({A}, m, p, id, on_left), id, p, on_left))), Done{{None{{}}}})
    case Tuple{{m, Fail{{e}}}}:
      (m, Fail{{e}})''')
fun('put_replaced',f'r: {T} & Maybe<&2, V>',T+' & Result<&2, &2, Rejected<K, V>, Maybe<&2, V>>','  (m, old) = r\n  (m, Done{old})')
fun('put_found',f'k: K, v: V, r: {T} & Search',T+' & Result<&2, &2, Rejected<K, V>, Maybe<&2, V>>',f'''  match r:
    case Tuple{{m, Search{{0n, +p, +on_left}}}}:
      put_allocated({A}, p, on_left, allocate({A}, m, p, k, v))
    case Tuple{{m, Search{{1n+i, p, on_left}}}}:
      put_replaced({A}, exchange({A}, m, 1n+i, Some{{v}}))''')
fun('put',f'm: {T}, +k: K, v: V',T+' & Result<&2, &2, Rejected<K, V>, Maybe<&2, V>>',f'  put_found({A}, k, v, search({A}, m, k))')

# A Data read returns a value copy while preserving ownership of the map.
fun('get_id_finish','n: Nat, root: Nat, lo: Nat, hi: Nat, free: Nat, nodes: NodeStore<K>, r: D.DynArray<&2, Maybe<&2, V>> & Result<&2, &2, DE.Error, Maybe<&2, V>>',T+' & Maybe<&2, V>', """  match r:
    case Tuple{values, Done{x}}:
      (TM{n, root, lo, hi, free, nodes, values}, x)
    case Tuple{values, Fail{e}}:
      (TM{n, root, lo, hi, free, nodes, values}, None{})""")
fun('get_id',f'm: {T}, id: Nat',T+' & Maybe<&2, V>',f"""  match m id:
    case mm 0n:
      (mm, None{{}})
    case TM{{n, root, lo, hi, free, nodes, values}} 1n+i:
      get_id_finish({A}, n, root, lo, hi, free, nodes, D.get_at(~Maybe<&2, V>, values, i))""")
fun('get_found',f'r: {T} & Search',T+' & Maybe<&2, V>',f'  (m, Search{{id, p, on_left}}) = r\n  get_id({A}, m, id)')
fun('get',f'm: {T}, k: K',T+' & Maybe<&2, V>',f'  get_found({A}, search({A}, m, k))')
fun('contains_found',f'r: {T} & Search',T+' & Bool','  (m, Search{id, p, left}) = r\n  (m, Nat.is_lt(0n, id))')
fun('contains_key',f'm: {T}, k: K',T+' & Bool',f'  contains_found({A}, search({A}, m, k))')

# Extremal descent and parent-linked successor/predecessor.
fun('extreme_probe',f'forward: Bool, r: {T} & Node<K>',T+' & Nat', '''  (m, node) = r
  (m, child(K, node, forward))''')
fun('extreme_loop',f'fuel: Nat, +forward: Bool, id: Nat, st: {T} & Nat',T+' & Nat',f'''  match fuel st:
    case 0n Tuple{{m, next}}:
      (m, id)
    case 1n+p Tuple{{m, 0n}}:
      (m, id)
    case 1n+p Tuple{{m, 1n+ +j}}:
      extreme_loop({A}, p, forward, 1n+j, extreme_probe({A}, forward, read({A}, m, 1n+j)))''')
fun('extreme',f'm: {T}, +id: Nat, +forward: Bool',T+' & Nat',f'''  TM{{+n, root, lo, hi, free, nodes, values}} = m
  extreme_loop({A}, 1n+n, forward, id, extreme_probe({A}, forward, read({A}, TM{{n, root, lo, hi, free, nodes, values}}, id)))''')
raw('''type Ascend is Data:
  Ascend{child: Nat, parent: Nat, done: Bool}
''')
raw('''# A direct branch preserves scalar traversal state in native code. Passing
# these records through pick(-T: Type) erases their layout and boxes both arms.
def ascend_choice(x: Nat, p: Nat, q: Nat, found: Bool) -> Ascend:
  match found:
    case True{}:
      Ascend{0n, p, True{}}
    case False{}:
      Ascend{x, q, False{}}
''')
fun('ascend_step_node',f'x: Nat, p: Nat, forward: Bool, r: {T} & Node<K>',T+' & Ascend',f'''  match r:
    case Tuple{{m, Free{{next}}}}:
      (m, Ascend{{0n, 0n, True{{}}}})
    case Tuple{{m, N{{c, l, r, q, key}}}}:
      (m, ascend_choice(p, p, q, Nat.is_eq(x, pick(Nat, forward, l, r))))''')
fun('ascend_loop',f'fuel: Nat, +forward: Bool, st: {T} & Ascend',T+' & Nat',f'''  match fuel st:
    case 0n Tuple{{m, state}}:
      (m, 0n)
    case 1n+f Tuple{{m, Ascend{{x, p, True{{}}}}}}:
      (m, p)
    case 1n+f Tuple{{m, Ascend{{+x, +p, False{{}}}}}}:
      ascend_loop({A}, f, forward, ascend_step_node({A}, x, p, forward, read({A}, m, p)))''')
# Read-only successor traversal carries only the metadata buffer. The owning
# map header and payload buffer stay outside the inner loops and are restored.
NA='NodeStore<K>'
fun('node_slot_done',f'r: {NA} & Result<&2, &2, DE.Error, Node<K>>',NA+' & Node<K>', '''  match r:
    case Tuple{nodes, Fail{e}}:
      (nodes, Free{0n})
    case Tuple{nodes, Done{node}}:
      (nodes, node)''')
fun('node_slot_checked',f'nodes: {NA}, i: Nat, valid: Bool',NA+' & Node<K>',f'''  match valid:
    case False{{}}:
      (nodes, Free{{0n}})
    case True{{}}:
      node_slot_done({A}, ns_get(~K, nodes, i))''')
fun('node_slot',f'nodes: {NA}, used: Nat, id: Nat',NA+' & Node<K>',f'''  match id:
    case 0n:
      (nodes, Free{{0n}})
    case 1n+ +i:
      node_slot_checked({A}, nodes, i, Nat.is_lt(i, used))''')
fun('ascend_slots_step',f'x: Nat, p: Nat, forward: Bool, r: {NA} & Node<K>',NA+' & Ascend',f'''  match r:
    case Tuple{{nodes, Free{{next}}}}:
      (nodes, Ascend{{0n, 0n, True{{}}}})
    case Tuple{{nodes, N{{c, l, r, q, key}}}}:
      (nodes, ascend_choice(p, p, q, Nat.is_eq(x, pick(Nat, forward, l, r))))''')
fun('ascend_slots_loop',f'fuel: Nat, used: Nat, forward: Bool, st: {NA} & Ascend',NA+' & Nat',f'''  match fuel st:
    case 0n Tuple{{nodes, state}}:
      (nodes, 0n)
    case 1n+f Tuple{{nodes, Ascend{{x, p, True{{}}}}}}:
      (nodes, p)
    case 1n+f Tuple{{nodes, Ascend{{+x, +p, False{{}}}}}}:
      ascend_slots_loop({A}, f, used, forward, ascend_slots_step({A}, x, p, forward, node_slot({A}, nodes, used, p)))''')
fun('extreme_slots_probe',f'forward: Bool, r: {NA} & Node<K>',NA+' & Nat','  (nodes, node) = r\n  (nodes, child(K, node, forward))')
fun('extreme_slots_loop',f'fuel: Nat, used: Nat, forward: Bool, id: Nat, st: {NA} & Nat',NA+' & Nat',f'''  match fuel st:
    case 0n Tuple{{nodes, next}}:
      (nodes, id)
    case 1n+f Tuple{{nodes, 0n}}:
      (nodes, id)
    case 1n+f Tuple{{nodes, 1n+ +j}}:
      extreme_slots_loop({A}, f, used, forward, 1n+j, extreme_slots_probe({A}, forward, node_slot({A}, nodes, used, 1n+j)))''')
fun('neighbor_slots',f'nodes: {NA}, n: Nat, used: Nat, id: Nat, p: Nat, forward: Bool, c: Nat',NA+' & Nat',f'''  match c:
    case 0n:
      ascend_slots_loop({A}, 1n+n, used, forward, (nodes, Ascend{{id, p, False{{}}}}))
    case 1n+ +j:
      extreme_slots_loop({A}, 1n+n, used, Bool.not(forward), 1n+j, extreme_slots_probe({A}, Bool.not(forward), node_slot({A}, nodes, used, 1n+j)))''')
fun('neighbor_slots_finish',f'n: Nat, root: Nat, lo: Nat, hi: Nat, free: Nat, values: D.DynArray<&2, Maybe<&2, V>>, r: {NA} & Nat',T+' & Nat','  (nodes, id) = r\n  (TM{n, root, lo, hi, free, nodes, values}, id)')
fun('neighbor_used',f'n: Nat, root: Nat, lo: Nat, hi: Nat, free: Nat, values: D.DynArray<&2, Maybe<&2, V>>, id: Nat, forward: Bool, node: Node<K>, r: {NA} & Nat',T+' & Nat',f'''  (nodes, +used) = r
  neighbor_slots_finish({A}, n, root, lo, hi, free, values, neighbor_slots({A}, nodes, n, used, id, parent(K, node), forward, child(K, node, forward)))''')
fun('neighbor_node',f'id: Nat, forward: Bool, r: {T} & Node<K>',T+' & Nat',f'''  (TM{{+n, root, lo, hi, free, nodes, values}}, +node) = r
  neighbor_used({A}, n, root, lo, hi, free, values, id, forward, node, ns_length(~K, nodes))''')
fun('neighbor',f'm: {T}, id: Nat, forward: Bool',T+' & Nat',f'  neighbor_node({A}, id, forward, read({A}, m, id))')
# Removing an internal node moves its successor's payload into its slot.
# The ordering depends only on keys.
fun('set_key_node',f'm: {T}, id: Nat, k: K, node: Node<K>',T,f'''  match node:
    case Free{{next}}:
      m
    case N{{c, l, r, p, old}}:
      write({A}, m, id, N{{c, l, r, p, k}})''')
seq('set_key',[('m',T),('id','Nat'),('k','K')],T,[([('m1',T),('node','Node<K>')],f'read({A}, m, id)')],f'set_key_node({A}, m1, id, k, node)')
fun('copy_key',f'm: {T}, target: Nat, node: Node<K>',T,f'''  match node:
    case Free{{next}}:
      m
    case N{{c, l, r, p, k}}:
      set_key({A}, m, target, k)''')
seq('move_successor',[('m',T),('target','Nat'),('source','Nat')],T+' & Nat',[
 ([('m1',T),('source_node','Node<K>')],f'read({A}, m, source)'),
 ([('m2',T),('value','Maybe<&2, V>')],f'exchange({A}, m1, source, None{{}})'),
 ([('m3',T),('old','Maybe<&2, V>')],f'exchange({A}, copy_key({A}, m2, target, source_node), target, value)')], '(m3, source)')
fun('successor_ready',f'target: Nat, r: {T} & Nat',T+' & Nat',f'  (m, source) = r\n  move_successor({A}, m, target, source)')
fun('delete_target',f'id: Nat, r: {T} & Node<K>',T+' & Nat',f'''  match r:
    case Tuple{{m, N{{c, 1n+l, 1n+r, p, k}}}}:
      successor_ready({A}, id, extreme({A}, m, 1n+r, False{{}}))
    case Tuple{{m, node}}:
      (m, id)''')
raw('''type DeleteFix is Data:
  DF{node: Nat, parent: Nat, more: Bool}
''')
for side,opposite in [('left','right'),('right','left')]:
    # x is the side child; rotate toward x's side after borrowing from sibling.
    fun('delete_borrow_'+side,f'm: {T}, p: Nat, w: Nat, pn: Node<K>, wn: Node<K>',T+' & DeleteFix',f'''  (rotate_{side}({A}, set_red({A}, set_red({A}, set_red({A}, m, w, red(K, pn)), p, False{{}}), {opposite}(K, wn), False{{}}), p), DF{{0n, 0n, False{{}}}})''')
    seq('delete_borrow_read_'+side,[('m',T),('p','Nat')],T+' & DeleteFix',[
      ([('m1',T),('pn','Node<K>')],f'read({A}, m, p)'),
      ([('m2',T),('wn','Node<K>')],f'read({A}, m1, {opposite}(K, pn))')],f'delete_borrow_{side}({A}, m2, p, {opposite}(K, pn), pn, wn)')
    fun('delete_far_'+side,f'm: {T}, p: Nat, w: Nat, pn: Node<K>, wn: Node<K>, far_red: Bool',T+' & DeleteFix',f'''  match far_red:
    case True{{}}:
      delete_borrow_{side}({A}, m, p, w, pn, wn)
    case False{{}}:
      delete_borrow_read_{side}({A}, rotate_{opposite}({A}, set_red({A}, set_red({A}, m, {side}(K, wn), False{{}}), w, True{{}}), w), p)''')
    fun('delete_children_'+side,f'm: {T}, p: Nat, w: Nat, pn: Node<K>, wn: Node<K>, near_red: Bool, far_red: Bool',T+' & DeleteFix',f'''  match near_red far_red:
    case False{{}} False{{}}:
      (set_red({A}, m, w, True{{}}), DF{{p, parent(K, pn), True{{}}}})
    case _ _:
      delete_far_{side}({A}, m, p, w, pn, wn, far_red)''')
    seq('delete_sibling_'+side,[('m',T),('p','Nat')],T+' & DeleteFix',[
      ([('m1',T),('pn','Node<K>')],f'read({A}, m, p)'),
      ([('m2',T),('wn','Node<K>')],f'read({A}, m1, {opposite}(K, pn))'),
      ([('m3',T),('near_node','Node<K>')],f'read({A}, m2, {side}(K, wn))'),
      ([('m4',T),('far_node','Node<K>')],f'read({A}, m3, {opposite}(K, wn))')],f'delete_children_{side}({A}, m4, p, {opposite}(K, pn), pn, wn, red(K, near_node), red(K, far_node))')
    fun('delete_red_sibling_'+side,f'm: {T}, p: Nat, w: Nat, red_sibling: Bool',T+' & DeleteFix',f'''  match red_sibling:
    case True{{}}:
      delete_sibling_{side}({A}, rotate_{side}({A}, set_red({A}, set_red({A}, m, w, False{{}}), p, True{{}}), p), p)
    case False{{}}:
      delete_sibling_{side}({A}, m, p)''')
    seq('delete_side_'+side,[('m',T),('p','Nat'),('pn','Node<K>')],T+' & DeleteFix',[
      ([('m1',T),('wn','Node<K>')],f'read({A}, m, {opposite}(K, pn))')],f'delete_red_sibling_{side}({A}, m1, p, {opposite}(K, pn), red(K, wn))')
fun('delete_side',f'm: {T}, x: Nat, p: Nat, pn: Node<K>, on_left: Bool',T+' & DeleteFix',f'''  match on_left:
    case True{{}}:
      delete_side_left({A}, m, p, pn)
    case False{{}}:
      delete_side_right({A}, m, p, pn)''')
fun('delete_stop',f'm: {T}, x: Nat, p: Nat, pn: Node<K>, stop: Bool',T+' & DeleteFix',f'''  match stop:
    case True{{}}:
      (set_red({A}, m, x, False{{}}), DF{{0n, 0n, False{{}}}})
    case False{{}}:
      delete_side({A}, m, x, p, pn, Nat.is_eq(x, left(K, pn)))''')
seq('delete_fix_step',[('m',T),('x','Nat'),('p','Nat')],T+' & DeleteFix',[
 ([('m1',T),('root_node','Nat')],f'root_id({A}, m)'),
 ([('m2',T),('xn','Node<K>')],f'read({A}, m1, x)'),
 ([('m3',T),('pn','Node<K>')],f'read({A}, m2, p)')],f'delete_stop({A}, m3, x, p, pn, Bool.or(Nat.is_eq(x, root_node), red(K, xn)))')
fun('delete_fix_loop',f'fuel: Nat, st: {T} & DeleteFix',T,f'''  match fuel st:
    case 0n Tuple{{m, fix}}:
      black_root({A}, m)
    case 1n+f Tuple{{m, DF{{x, p, False{{}}}}}}:
      black_root({A}, m)
    case 1n+f Tuple{{m, DF{{x, p, True{{}}}}}}:
      delete_fix_loop({A}, f, delete_fix_step({A}, m, x, p))''')
fun('release_header',f'm: {T}, id: Nat',T,'''  TM{n, root, lo, hi, free, nodes, values} = m
  TM{Nat.sub(n, 1n), root, lo, hi, id, nodes, values}''')
fun('recycle',f'm: {T}, id: Nat',T,f'''  TM{{n, root, lo, hi, +free, nodes, values}} = m
  release_header({A}, write({A}, TM{{n, root, lo, hi, free, nodes, values}}, id, Free{{free}}), id)''')
fun('delete_repair',f'm: {T}, x: Nat, p: Nat, was_red: Bool',T,f'''  TM{{+n, root, lo, hi, free, nodes, values}} = m
  delete_fix_loop({A}, 1n+n, (TM{{n, root, lo, hi, free, nodes, values}}, DF{{x, p, Bool.not(was_red)}}))''')
seq('unlink',[('m',T),('id','Nat')],T,[
 ([('m1',T),('node','Node<K>')],f'read({A}, m, id)'),
 ([('m2',T),('pn','Node<K>')],f'read({A}, m1, parent(K, node))')],
 f'delete_repair({A}, recycle({A}, attach({A}, m2, parent(K, node), pick(Nat, Nat.is_lt(0n, left(K, node)), left(K, node), right(K, node)), Nat.is_eq(id, left(K, pn))), id), pick(Nat, Nat.is_lt(0n, left(K, node)), left(K, node), right(K, node)), parent(K, node), red(K, node))')
fun('set_ends',f'm: {T}, lo: Nat, hi: Nat',T,'  TM{n, root, oldlo, oldhi, free, nodes, values} = m\n  TM{n, root, lo, hi, free, nodes, values}')
seq('refresh_ends',[('m',T)],T,[
 ([('m1',T),('r','Nat')],f'root_id({A}, m)'),
 ([('m2',T),('lo','Nat')],f'extreme({A}, m1, r, False{{}})'),
 ([('m3',T),('hi','Nat')],f'extreme({A}, m2, r, True{{}})')],f'set_ends({A}, m3, lo, hi)')
fun('unlink_target',f'r: {T} & Nat',T,f'  (m, id) = r\n  refresh_ends({A}, unlink({A}, m, id))')
seq('remove_present',[('m',T),('id','Nat')],T+' & Maybe<&2, V>',[
 ([('m1',T),('value','Maybe<&2, V>')],f'exchange({A}, m, id, None{{}})')],f'(unlink_target({A}, delete_target({A}, id, read({A}, m1, id))), value)')
fun('remove_id',f'm: {T}, id: Nat',T+' & Maybe<&2, V>',f'''  match id:
    case 0n:
      (m, None{{}})
    case 1n+i:
      remove_present({A}, m, 1n+i)''')
fun('remove_found',f'r: {T} & Search',T+' & Maybe<&2, V>',f'  (m, Search{{id, p, on_left}}) = r\n  remove_id({A}, m, id)')
fun('remove',f'm: {T}, k: K',T+' & Maybe<&2, V>',f'  remove_found({A}, search({A}, m, k))')
fun('clear',f'm: {T}',T,'''  TM{n, root, lo, hi, free, nodes, values} = m
  TM{0n, 0n, 0n, 0n, 0n, ns_clear(~K, nodes), D.clear_at(~Maybe<&2, V>, values)}''')
seq('is_empty',[('m',T)],T+' & Bool',[([('m1',T),('n','Nat')],f'size({A}, m)')], '(m1, Nat.is_eq(n, 0n))')

# Navigation mode: higher=True chooses successor side, inclusive admits EQ.
fun('nav_loop',f'fuel: Nat, +k: K, +higher: Bool, +inclusive: Bool, +id: Nat, best: Nat, st: {T} & (Node<K> & Cmp)',T+' & Nat',f'''  match fuel st:
    case 0n Tuple{{m, node}}:
      (m, best)
    case 1n+f Tuple{{m, Tuple{{Free{{next}}, order}}}}:
      (m, best)
    case 1n+f Tuple{{m, Tuple{{N{{c, +l, r, p, key}}, LT{{}}}}}}:
      nav_loop({A}, f, k, higher, inclusive, l, pick(Nat, higher, id, best), probe({A}, m, l, k))
    case 1n+f Tuple{{m, Tuple{{N{{c, l, +r, p, key}}, GT{{}}}}}}:
      nav_loop({A}, f, k, higher, inclusive, r, pick(Nat, higher, best, id), probe({A}, m, r, k))
    case 1n+f Tuple{{m, Tuple{{node, EQ{{}}}}}}:
      nav_equal({A}, m, id, higher, inclusive)''')
fun('nav_equal',f'm: {T}, id: Nat, higher: Bool, inclusive: Bool',T+' & Nat',f'''  match inclusive:
    case True{{}}:
      (m, id)
    case False{{}}:
      neighbor({A}, m, id, higher)''')
fun('navigate',f'm: {T}, +k: K, higher: Bool, inclusive: Bool',T+' & Nat',f'''  TM{{+n, +root, lo, hi, free, nodes, values}} = m
  nav_loop({A}, 1n+n, k, higher, inclusive, root, 0n, probe({A}, TM{{n, root, lo, hi, free, nodes, values}}, root, k))''')
fun('key_finish',f'r: {T} & Node<K>',T+' & Maybe<&2, K>','  (m, node) = r\n  (m, node_key(K, node))')
fun('key_id',f'r: {T} & Nat',T+' & Maybe<&2, K>',f'  (m, id) = r\n  key_finish({A}, read({A}, m, id))')
for name,higher,inclusive in [('lower',False,False),('floor',False,True),('ceiling',True,True),('higher',True,False)]:
    fun(name+'_key',f'm: {T}, k: K',T+' & Maybe<&2, K>',f'  key_id({A}, navigate({A}, m, k, {str(higher)}{{}}, {str(inclusive)}{{}}))')
for name in ['first','last']:
    fun(name+'_key',f'm: {T}',T+' & Maybe<&2, K>',f'  key_id({A}, {name}_id({A}, m))')
fun('entry_value',f'k: Maybe<&2, K>, r: {T} & Maybe<&2, V>',T+' & Maybe<&2, Entry<K, V>>', '''  match k r:
    case Some{key} Tuple{m, Some{v}}:
      (m, Some{Entry{key, v}})
    case _ Tuple{m, value}:
      (m, None{})''')
seq('remove_entry_id',[('m',T),('id','Nat')],T+' & Maybe<&2, Entry<K, V>>',[
 ([('m1',T),('node','Node<K>')],f'read({A}, m, id)')],f'entry_value({A}, node_key(K, node), remove_id({A}, m1, id))')
fun('poll_ready',f'r: {T} & Nat',T+' & Maybe<&2, Entry<K, V>>',f'  (m, id) = r\n  remove_entry_id({A}, m, id)')
for name in ['first','last']:
    fun('poll_'+name+'_entry',f'm: {T}',T+' & Maybe<&2, Entry<K, V>>',f'  poll_ready({A}, {name}_id({A}, m))')
# Data entry snapshots preserve ownership of the map.
raw(f'''def entry_snapshot_value(~K: Data, ~V: Data, ~cmp: K -> K -> Cmp, id: Nat, r: {T} & Node<K>) -> {T} & Maybe<&2, Entry<K, V>>:
  (m, node) = r
  entry_value({A}, node_key(K, node), get_id({A}, m, id))

def entry_snapshot(~K: Data, ~V: Data, ~cmp: K -> K -> Cmp, r: {T} & Nat) -> {T} & Maybe<&2, Entry<K, V>>:
  (m, +id) = r
  entry_snapshot_value({A}, id, read({A}, m, id))
''')
for name,higher,inclusive in [('lower',False,False),('floor',False,True),('ceiling',True,True),('higher',True,False)]:
    raw(f'''def {name}_entry(~K: Data, ~V: Data, ~cmp: K -> K -> Cmp, m: {T}, k: K) -> {T} & Maybe<&2, Entry<K, V>>:
  entry_snapshot({A}, navigate({A}, m, k, {str(higher)}{{}}, {str(inclusive)}{{}}))''')
for name in ['first','last']:
    raw(f'''def {name}_entry(~K: Data, ~V: Data, ~cmp: K -> K -> Cmp, m: {T}) -> {T} & Maybe<&2, Entry<K, V>>:
  entry_snapshot({A}, {name}_id({A}, m))''')

fun('with_limit',f'limit: Nat',T,'  TM{0n, 0n, 0n, 0n, 0n, ns_with_limit(~K, limit), D.with_limit_at(~Maybe<&2, V>, limit)}')

# Additional map updates do one search and retain the comparator-equivalent key.
fun('put_absent_found',f'k: K, v: V, r: {T} & Search',T+' & Result<&2, &2, Rejected<K, V>, Maybe<&2, V>>',f'''  match r:
    case Tuple{{m, Search{{0n, +p, +on_left}}}}:
      put_allocated({A}, p, on_left, allocate({A}, m, p, k, v))
    case Tuple{{m, Search{{1n+i, p, on_left}}}}:
      put_replaced({A}, get_id({A}, m, 1n+i))''')
fun('put_if_absent',f'm: {T}, k: K, v: V',T+' & Result<&2, &2, Rejected<K, V>, Maybe<&2, V>>',f'  put_absent_found({A}, k, v, search({A}, m, k))')
fun('replace_found',f'v: V, r: {T} & Search',T+' & Maybe<&2, V>',f'''  match r:
    case Tuple{{m, Search{{0n, p, on_left}}}}:
      (m, None{{}})
    case Tuple{{m, Search{{1n+i, p, on_left}}}}:
      exchange({A}, m, 1n+i, Some{{v}})''')
fun('replace',f'm: {T}, k: K, v: V',T+' & Maybe<&2, V>',f'  replace_found({A}, v, search({A}, m, k))')
fun('default_value',f'fallback: V, r: {T} & Maybe<&2, V>',T+' & V','''  match r:
    case Tuple{m, None{}}:
      (m, fallback)
    case Tuple{m, Some{v}}:
      (m, v)''')
fun('get_or_default',f'm: {T}, k: K, fallback: V',T+' & V',f'  default_value({A}, fallback, get({A}, m, k))')

# Owned, backed range views. They return the original map at finish; no copy.
raw('''type Bound<-K: Data> is Data:
  Unbounded{}
  Inclusive{key: K}
  Exclusive{key: K}

type View<-K: Data, -V: Data, -cmp: K -> K -> Cmp> is Type:
  View{map: TreeMap<K, V, cmp>, lower: Bound<K>, upper: Bound<K>, descending: Bool}

type InvalidView<-K: Data, -V: Data, -cmp: K -> K -> Cmp> is Type:
  InvalidView{map: TreeMap<K, V, cmp>, error: Error}

type Cursor<-K: Data, -V: Data, -cmp: K -> K -> Cmp> is Type:
  Cursor{map: TreeMap<K, V, cmp>, next: Nat, current: Nat,
         lower: Bound<K>, upper: Bound<K>, forward: Bool}

def ordering_ok(order: Cmp, inclusive: Bool) -> Bool:
  match order:
    case LT{}:
      True{}
    case EQ{}:
      inclusive
    case GT{}:
      False{}
''')
W='View<K, V, cmp>';C='Cursor<K, V, cmp>';B='Bound<K>'
fun('above_lower',f'k: K, bound: {B}','Bool',f'''  match bound:
    case Unbounded{{}}:
      True{{}}
    case Inclusive{{lo}}:
      ordering_ok(cmp(lo, k), True{{}})
    case Exclusive{{lo}}:
      ordering_ok(cmp(lo, k), False{{}})''')
fun('below_upper',f'k: K, bound: {B}','Bool',f'''  match bound:
    case Unbounded{{}}:
      True{{}}
    case Inclusive{{hi}}:
      ordering_ok(cmp(k, hi), True{{}})
    case Exclusive{{hi}}:
      ordering_ok(cmp(k, hi), False{{}})''')
fun('in_range',f'k: K, lower: {B}, upper: {B}','Bool',f'  Bool.and(above_lower({A}, k, lower), below_upper({A}, k, upper))')
fun('bounds_valid',f'lower: {B}, upper: {B}','Bool',f'''  match lower upper:
    case Unbounded{{}} _:
      True{{}}
    case _ Unbounded{{}}:
      True{{}}
    case Inclusive{{lo}} Inclusive{{hi}}:
      ordering_ok(cmp(lo, hi), True{{}})
    case Inclusive{{lo}} Exclusive{{hi}}:
      ordering_ok(cmp(lo, hi), True{{}})
    case Exclusive{{lo}} Inclusive{{hi}}:
      ordering_ok(cmp(lo, hi), True{{}})
    case Exclusive{{lo}} Exclusive{{hi}}:
      ordering_ok(cmp(lo, hi), True{{}})''')
fun('view_checked',f'm: {T}, lower: {B}, upper: {B}, descending: Bool, valid: Bool',f'Result<&1, &1, InvalidView<K, V, cmp>, {W}>',f'''  match valid:
    case True{{}}:
      Done{{View{{m, lower, upper, descending}}}}
    case False{{}}:
      Fail{{InvalidView{{m, InvalidBounds{{}}}}}}''')
fun('sub_map',f'm: {T}, +lower: {B}, +upper: {B}',f'Result<&1, &1, InvalidView<K, V, cmp>, {W}>',f'  view_checked({A}, m, lower, upper, False{{}}, bounds_valid({A}, lower, upper))')
fun('head_map',f'm: {T}, upper: {B}',W,'  View{m, Unbounded{}, upper, False{}}')
fun('tail_map',f'm: {T}, lower: {B}',W,'  View{m, lower, Unbounded{}, False{}}')
fun('descending_map',f'm: {T}',W,'  View{m, Unbounded{}, Unbounded{}, True{}}')
fun('view_reverse',f'view: {W}',W,'  View{m, lower, upper, descending} = view\n  View{m, lower, upper, Bool.not(descending)}')
fun('view_finish',f'view: {W}',T,'  View{m, lower, upper, descending} = view\n  m')
fun('view_value',f'lower: {B}, upper: {B}, descending: Bool, r: {T} & Maybe<&2, V>',W+' & Maybe<&2, V>','  (m, v) = r\n  (View{m, lower, upper, descending}, v)')
for op in ['get','remove']:
    fun('view_'+op+'_checked',f'm: {T}, k: K, lower: {B}, upper: {B}, descending: Bool, valid: Bool',W+' & Maybe<&2, V>',f'''  match valid:
    case True{{}}:
      view_value({A}, lower, upper, descending, {op}({A}, m, k))
    case False{{}}:
      (View{{m, lower, upper, descending}}, None{{}})''')
    fun('view_'+op,f'view: {W}, k: K',W+' & Maybe<&2, V>',f'''  View{{m, +lower, +upper, descending}} = view
  view_{op}_checked({A}, m, k, lower, upper, descending, in_range({A}, k, lower, upper))''')
fun('view_put_finish',f'lower: {B}, upper: {B}, descending: Bool, r: {T} & Result<&2, &2, Rejected<K, V>, Maybe<&2, V>>',W+' & Result<&2, &2, Rejected<K, V>, Maybe<&2, V>>','  (m, status) = r\n  (View{m, lower, upper, descending}, status)')
fun('view_put_checked',f'm: {T}, k: K, v: V, lower: {B}, upper: {B}, descending: Bool, valid: Bool',W+' & Result<&2, &2, Rejected<K, V>, Maybe<&2, V>>',f'''  match valid:
    case True{{}}:
      view_put_finish({A}, lower, upper, descending, put({A}, m, k, v))
    case False{{}}:
      (View{{m, lower, upper, descending}}, Fail{{Rejected{{OutOfRange{{}}, k, v}}}})''')
fun('view_put',f'view: {W}, k: K, v: V',W+' & Result<&2, &2, Rejected<K, V>, Maybe<&2, V>>',f'''  View{{m, +lower, +upper, descending}} = view
  view_put_checked({A}, m, k, v, lower, upper, descending, in_range({A}, k, lower, upper))''')
# Cursor walks parent links, never expands a collection into linked entries.
fun('range_start',f'm: {T}, bound: {B}, forward: Bool',T+' & Nat',f'''  match bound:
    case Unbounded{{}}:
      range_unbounded({A}, m, forward)
    case Inclusive{{k}}:
      navigate({A}, m, k, forward, True{{}})
    case Exclusive{{k}}:
      navigate({A}, m, k, forward, False{{}})''')
fun('range_unbounded',f'm: {T}, forward: Bool',T+' & Nat',f'''  match forward:
    case True{{}}:
      first_id({A}, m)
    case False{{}}:
      last_id({A}, m)''')
fun('cursor_started',f'lower: {B}, upper: {B}, forward: Bool, r: {T} & Nat',C,'  (m, id) = r\n  Cursor{m, id, 0n, lower, upper, forward}')
fun('view_iterator',f'view: {W}',C,f'''  View{{m, +lower, +upper, +descending}} = view
  cursor_started({A}, lower, upper, Bool.not(descending), range_start({A}, m, pick(Bound<K>, descending, upper, lower), Bool.not(descending)))''')
fun('iterator',f'm: {T}',C,f'  cursor_started({A}, Unbounded{{}}, Unbounded{{}}, True{{}}, first_id({A}, m))')
fun('descending_iterator',f'm: {T}',C,f'  cursor_started({A}, Unbounded{{}}, Unbounded{{}}, False{{}}, last_id({A}, m))')
fun('iterator_finish',f'cursor: {C}',T,'  Cursor{m, next, current, lower, upper, forward} = cursor\n  m')
fun('iterator_view',f'cursor: {C}',W,'  Cursor{m, next, current, lower, upper, forward} = cursor\n  View{m, lower, upper, Bool.not(forward)}')
fun('iterator_yield',f'id: Nat, lower: {B}, upper: {B}, forward: Bool, entry: Entry<K, V>, r: {T} & Nat',C+' & Maybe<&2, Entry<K, V>>','  (m, next) = r\n  (Cursor{m, next, id, lower, upper, forward}, Some{entry})')
fun('iterator_checked',f'm: {T}, id: Nat, current: Nat, lower: {B}, upper: {B}, forward: Bool, entry: Entry<K, V>, valid: Bool',C+' & Maybe<&2, Entry<K, V>>',f'''  match valid:
    case True{{}}:
      iterator_yield({A}, id, lower, upper, forward, entry, neighbor({A}, m, id, forward))
    case False{{}}:
      (Cursor{{m, 0n, current, lower, upper, forward}}, None{{}})''')
fun('iterator_read',f'id: Nat, current: Nat, +lower: {B}, +upper: {B}, forward: Bool, r: {T} & Maybe<&2, Entry<K, V>>',C+' & Maybe<&2, Entry<K, V>>',f'''  match r:
    case Tuple{{m, None{{}}}}:
      (Cursor{{m, 0n, current, lower, upper, forward}}, None{{}})
    case Tuple{{m, Some{{Entry{{+k, v}}}}}}:
      iterator_checked({A}, m, id, current, lower, upper, forward, Entry{{k, v}}, in_range({A}, k, lower, upper))''')
fun('iterator_next',f'cursor: {C}',C+' & Maybe<&2, Entry<K, V>>',f'''  Cursor{{m, +next, current, lower, upper, forward}} = cursor
  iterator_read({A}, next, current, lower, upper, forward, entry_snapshot({A}, (m, next)))''')
fun('iterator_set_done',f'next: Nat, current: Nat, lower: {B}, upper: {B}, forward: Bool, r: {T} & Maybe<&2, V>',C+' & Result<&2, &2, Error, V>', '''  match r:
    case Tuple{m, Some{old}}:
      (Cursor{m, next, current, lower, upper, forward}, Done{old})
    case Tuple{m, None{}}:
      (Cursor{m, next, current, lower, upper, forward}, Fail{NoCurrent{}})''')
fun('iterator_set_value',f'cursor: {C}, v: V',C+' & Result<&2, &2, Error, V>',f'''  match cursor:
    case Cursor{{m, next, 0n, lower, upper, forward}}:
      (Cursor{{m, next, 0n, lower, upper, forward}}, Fail{{NoCurrent{{}}}})
    case Cursor{{m, next, 1n+ +id, lower, upper, forward}}:
      iterator_set_done({A}, next, 1n+id, lower, upper, forward, exchange({A}, m, 1n+id, Some{{v}}))''')
# Re-seek the successor key after deleting: two-child deletion may relocate it.
fun('iterator_reseek',f'k: Maybe<&2, K>, lower: {B}, upper: {B}, forward: Bool, r: {T} & Maybe<&2, V>',C+' & Maybe<&2, V>',f'''  match k r:
    case None{{}} Tuple{{m, removed}}:
      (Cursor{{m, 0n, 0n, lower, upper, forward}}, removed)
    case Some{{key}} Tuple{{m, removed}}:
      iterator_relocated({A}, lower, upper, forward, removed, search({A}, m, key))''')
fun('iterator_relocated',f'lower: {B}, upper: {B}, forward: Bool, removed: Maybe<&2, V>, r: {T} & Search',C+' & Maybe<&2, V>','  (m, Search{id, p, on_left}) = r\n  (Cursor{m, id, 0n, lower, upper, forward}, removed)')
seq('iterator_delete',[('m',T),('next','Nat'),('current','Nat'),('lower',B),('upper',B),('forward','Bool')],C+' & Maybe<&2, V>',[
 ([('m1',T),('node','Node<K>')],f'read({A}, m, next)')],f'iterator_reseek({A}, node_key(K, node), lower, upper, forward, remove_id({A}, m1, current))')
fun('iterator_remove',f'cursor: {C}',C+' & Maybe<&2, V>',f'''  Cursor{{m, next, current, lower, upper, forward}} = cursor
  iterator_delete({A}, m, next, current, lower, upper, forward)''')
# Keys/values are projections of the same owning cursor, without materialization.
fun('iterator_key_result',f'r: {C} & Maybe<&2, Entry<K, V>>',C+' & Maybe<&2, K>', '''  match r:
    case Tuple{cursor, None{}}:
      (cursor, None{})
    case Tuple{cursor, Some{Entry{k, v}}}:
      (cursor, Some{k})''')
fun('iterator_value_result',f'r: {C} & Maybe<&2, Entry<K, V>>',C+' & Maybe<&2, V>', '''  match r:
    case Tuple{cursor, None{}}:
      (cursor, None{})
    case Tuple{cursor, Some{Entry{k, v}}}:
      (cursor, Some{v})''')
for name in ['key','value']:
    fun('iterator_next_'+name,f'cursor: {C}',C+f' & Maybe<&2, {"K" if name=="key" else "V"}>',f'  iterator_{name}_result({A}, iterator_next({A}, cursor))')
for name in ['entry_set','key_set','values']:
    fun(name,f'm: {T}',C,f'  iterator({A}, m)')

# Value equality is explicit; comparator equality applies only to keys.
for op in ['remove','replace']:
    change=f'remove_id({A}, m, id)' if op=='remove' else f'exchange({A}, m, id, Some{{replacement}})'
    fun(op+'_if_apply',f'm: {T}, id: Nat, replacement: V, equal: Bool',T+' & Bool',f'''  match equal:
    case False{{}}:
      (m, False{{}})
    case True{{}}:
      changed_value({A}, {change})''')
    fun(op+'_if_value',f'~eq: V -> V -> Bool, id: Nat, expected: V, replacement: V, r: {T} & Maybe<&2, V>',T+' & Bool',f'''  match r:
    case Tuple{{m, None{{}}}}:
      (m, False{{}})
    case Tuple{{m, Some{{old}}}}:
      {op}_if_apply({A}, m, id, replacement, eq(old, expected))''')
    fun(op+'_if_found',f'~eq: V -> V -> Bool, expected: V, replacement: V, r: {T} & Search',T+' & Bool',f'''  (m, Search{{+id, p, on_left}}) = r
  {op}_if_value({A}, ~eq, id, expected, replacement, get_id({A}, m, id))''')
fun('changed_value',f'r: {T} & Maybe<&2, V>',T+' & Bool','''  match r:
    case Tuple{m, None{}}:
      (m, False{})
    case Tuple{m, Some{old}}:
      (m, True{})''')
fun('remove_if_equal',f'~eq: V -> V -> Bool, m: {T}, k: K, expected: V',T+' & Bool',f'  remove_if_found({A}, ~eq, expected, expected, search({A}, m, k))')
fun('replace_if_equal',f'~eq: V -> V -> Bool, m: {T}, k: K, expected: V, replacement: V',T+' & Bool',f'  replace_if_found({A}, ~eq, expected, replacement, search({A}, m, k))')
fun('contains_value_loop',f'~eq: V -> V -> Bool, fuel: Nat, wanted: V, found: Bool, st: {C} & Maybe<&2, Entry<K, V>>',T+' & Bool',f'''  match fuel found st:
    case _ True{{}} Tuple{{cursor, item}}:
      (iterator_finish({A}, cursor), True{{}})
    case 0n False{{}} Tuple{{cursor, item}}:
      (iterator_finish({A}, cursor), False{{}})
    case 1n+f False{{}} Tuple{{cursor, None{{}}}}:
      (iterator_finish({A}, cursor), False{{}})
    case 1n+f False{{}} Tuple{{cursor, Some{{Entry{{k, v}}}}}}:
      contains_value_loop({A}, ~eq, f, wanted, eq(v, wanted), iterator_next({A}, cursor))''')
fun('contains_value_start',f'~eq: V -> V -> Bool, wanted: V, r: {T} & Nat',T+' & Bool',f'''  (m, n) = r
  contains_value_loop({A}, ~eq, 1n+n, wanted, False{{}}, iterator_next({A}, iterator({A}, m)))''')
fun('contains_value',f'~eq: V -> V -> Bool, m: {T}, wanted: V',T+' & Bool',f'  contains_value_start({A}, ~eq, wanted, size({A}, m))')

fun('iterator_has_checked',f'next: Nat, current: Nat, lower: {B}, upper: {B}, forward: Bool, r: {T} & Node<K>',C+' & Bool',f'''  match r:
    case Tuple{{m, Free{{free}}}}:
      (Cursor{{m, next, current, lower, upper, forward}}, False{{}})
    case Tuple{{m, N{{c, l, rr, p, key}}}}:
      (Cursor{{m, next, current, lower, upper, forward}}, in_range({A}, key, lower, upper))'''.replace('lower:','lower:'))
# Bound values are read both to rebuild the cursor and to check the candidate.
parts[-1]=parts[-1].replace('lower: Bound<K>', '+lower: Bound<K>').replace('upper: Bound<K>', '+upper: Bound<K>')
fun('iterator_has_next',f'cursor: {C}',C+' & Bool',f'''  Cursor{{m, +next, current, lower, upper, forward}} = cursor
  iterator_has_checked({A}, next, current, lower, upper, forward, read({A}, m, next))''')
fun('view_contains_value',f'r: {W} & Maybe<&2, V>',W+' & Bool','''  match r:
    case Tuple{view, None{}}:
      (view, False{})
    case Tuple{view, Some{x}}:
      (view, True{})''')
fun('view_contains_key',f'view: {W}, k: K',W+' & Bool',f'  view_contains_value({A}, view_get({A}, view, k))')
fun('view_entry_checked',f'm: {T}, lower: {B}, upper: {B}, descending: Bool, entry: Entry<K, V>, valid: Bool',W+' & Maybe<&2, Entry<K, V>>', '''  match valid:
    case True{}:
      (View{m, lower, upper, descending}, Some{entry})
    case False{}:
      (View{m, lower, upper, descending}, None{})''')
fun('view_entry_result',f'+lower: {B}, +upper: {B}, descending: Bool, r: {T} & Maybe<&2, Entry<K, V>>',W+' & Maybe<&2, Entry<K, V>>',f'''  match r:
    case Tuple{{m, None{{}}}}:
      (View{{m, lower, upper, descending}}, None{{}})
    case Tuple{{m, Some{{Entry{{+k, v}}}}}}:
      view_entry_checked({A}, m, lower, upper, descending, Entry{{k, v}}, in_range({A}, k, lower, upper))''')
fun('view_nav_start',f'm: {T}, k: K, lower: {B}, upper: {B}, higher: Bool, inclusive: Bool, within: Bool',T+' & Nat',f'''  match within:
    case True{{}}:
      navigate({A}, m, k, higher, inclusive)
    case False{{}}:
      range_start({A}, m, pick(Bound<K>, higher, lower, upper), higher)''')
fun('view_nav',f'view: {W}, k: K, higher: Bool, inclusive: Bool',W+' & Maybe<&2, Entry<K, V>>',f'''  View{{m, +lower, +upper, +descending}} = view
  +up = pick(Bool, descending, Bool.not(higher), higher)
  view_entry_result({A}, lower, upper, descending, entry_snapshot({A}, view_nav_start({A}, m, k, lower, upper, up, inclusive, pick(Bool, up, above_lower({A}, k, lower), below_upper({A}, k, upper)))))''')
for name,higher,inclusive in [('lower',False,False),('floor',False,True),('ceiling',True,True),('higher',True,False)]:
    fun('view_'+name+'_entry',f'view: {W}, k: K',W+' & Maybe<&2, Entry<K, V>>',f'  view_nav({A}, view, k, {higher}{{}}, {inclusive}{{}})')
fun('view_extreme',f'view: {W}, first: Bool',W+' & Maybe<&2, Entry<K, V>>',f'''  View{{m, +lower, +upper, +descending}} = view
  +up = pick(Bool, descending, Bool.not(first), first)
  view_entry_result({A}, lower, upper, descending, entry_snapshot({A}, range_start({A}, m, pick(Bound<K>, up, lower, upper), up)))''')
for name,first in [('first',True),('last',False)]:
    fun('view_'+name+'_entry',f'view: {W}',W+' & Maybe<&2, Entry<K, V>>',f'  view_extreme({A}, view, {first}{{}})')
fun('view_count_loop',f'fuel: Nat, count: Nat, st: {C} & Maybe<&2, Entry<K, V>>',W+' & Nat',f'''  match fuel st:
    case 0n Tuple{{cursor, item}}:
      (iterator_view({A}, cursor), count)
    case 1n+f Tuple{{cursor, None{{}}}}:
      (iterator_view({A}, cursor), count)
    case 1n+f Tuple{{cursor, Some{{item}}}}:
      view_count_loop({A}, f, 1n+count, iterator_next({A}, cursor))''')
fun('view_size',f'view: {W}',W+' & Nat',f'''  View{{TM{{+n, root, lo, hi, free, nodes, values}}, lower, upper, descending}} = view
  view_count_loop({A}, 1n+n, 0n, iterator_next({A}, view_iterator({A}, View{{TM{{n, root, lo, hi, free, nodes, values}}, lower, upper, descending}})))''')
fun('view_clear_next',f'r: {C} & Maybe<&2, V>',C+' & Maybe<&2, Entry<K, V>>',f'  (cursor, removed) = r\n  iterator_next({A}, cursor)')
fun('view_clear_loop',f'fuel: Nat, st: {C} & Maybe<&2, Entry<K, V>>',W,f'''  match fuel st:
    case 0n Tuple{{cursor, item}}:
      iterator_view({A}, cursor)
    case 1n+f Tuple{{cursor, None{{}}}}:
      iterator_view({A}, cursor)
    case 1n+f Tuple{{cursor, Some{{item}}}}:
      view_clear_loop({A}, f, view_clear_next({A}, iterator_remove({A}, cursor)))''')
fun('view_clear',f'view: {W}',W,f'''  View{{TM{{+n, root, lo, hi, free, nodes, values}}, lower, upper, descending}} = view
  view_clear_loop({A}, 1n+n, iterator_next({A}, view_iterator({A}, View{{TM{{n, root, lo, hi, free, nodes, values}}, lower, upper, descending}})))''')

# Sort definitions by dependency; self-recursion stays in one def.
def emit():
    text=''.join(parts)
    for name in ['red', 'left', 'right', 'parent', 'node_key', 'child']:
        text=text.replace('def '+name+'(-K: Data', 'def '+name+'(~K: Data')
        text=re.sub(r'\b'+name+r'\(K,', name+'(~K,', text)
    chunks=re.split(r'(?=^def )',text,flags=re.M)
    header=chunks.pop(0)
    # Type declarations are emitted ahead of definitions.
    for i,c in enumerate(chunks):
        pos=c.find('\ntype ')
        if pos>=0:
            header+=c[pos+1:];chunks[i]=c[:pos]+'\n\n'
    defs={re.match(r'def (\w+)',c).group(1):c for c in chunks}
    out=[header]
    while defs:
        ready=[k for k,v in defs.items() if not (set(re.findall(r'(?<![.\w])(\w+)\(',v.split('\n',1)[1])) & (defs.keys()-{k}))]
        if not ready:raise RuntimeError('cyclic helper dependency: '+str(list(defs)))
        for k in ready:out.append(defs.pop(k))
    (ROOT/'src/containers/balanced_search_tree.bend').write_text(re.sub(r'\b(left|right|parent|red)\(', lambda m:'node_'+m[1]+'(', re.sub(r'\bvalues\b(?!\()', 'payloads', ''.join(out))).rstrip()+'\n')
if __name__=='__main__':emit()
