#!/usr/bin/env python3
"""Emit the repetitive parts of the BLAKE3 package.

  python3 tools/generators/blake3/gen.py

Writes src/crypto/blake/blake3/compress.bend (the unrolled round and the
seven-round compression with the fixed message schedule) and the block-read
chain of src/crypto/blake/blake3/blake3.bend (between the GENERATED markers).
"""
from pathlib import Path

ROOT = Path(__file__).resolve().parents[3]
SRC = ROOT / 'src/crypto/blake/blake3'

PERM = [2, 6, 3, 10, 7, 0, 4, 13, 1, 11, 12, 5, 9, 14, 15, 8]
IV = [0x6A09E667, 0xBB67AE85, 0x3C6EF372, 0xA54FF53A, 0x510E527F, 0x9B05688C, 0x1F83D9AB, 0x5BE0CD19]
# (a, b, c, d, message index x, message index y) of the eight G calls of a round
GS = [(0, 4, 8, 12, 0, 1), (1, 5, 9, 13, 2, 3), (2, 6, 10, 14, 4, 5), (3, 7, 11, 15, 6, 7),
      (0, 5, 10, 15, 8, 9), (1, 6, 11, 12, 10, 11), (2, 7, 8, 13, 12, 13), (3, 4, 9, 14, 14, 15)]


def schedules():
    s = list(range(16))
    out = []
    for _ in range(7):
        out.append(s)
        s = [s[PERM[i]] for i in range(16)]
    return out


def ws(prefix, n, plus=False):
    return ','.join(('+' if plus else '') + '%s%d' % (prefix, i) for i in range(n))


def half_def(name, gs, first_m, comment):
    lines = [comment,
             'def %s(s: T.St, %s) -> T.St:' % (name, ', '.join('+m%d: U32' % i for i in range(first_m, first_m + 8))),
             '  match s:',
             '    case T.St{%s}:' % ws('v', 16, True)]
    cur = ['v%d' % i for i in range(16)]
    k = 0
    for (a, b, c, d, x, y) in gs:
        va, vb, vc, vd = cur[a], cur[b], cur[c], cur[d]
        t = ['t%d' % (k + i) for i in range(8)]
        k += 8
        lines += ['      +%s = U32.add(U32.add(%s,%s),m%d)' % (t[0], va, vb, x),
                  '      +%s = rot16(U32.xor(%s,%s))' % (t[1], vd, t[0]),
                  '      +%s = U32.add(%s,%s)' % (t[2], vc, t[1]),
                  '      +%s = rot12(U32.xor(%s,%s))' % (t[3], vb, t[2]),
                  '      +%s = U32.add(U32.add(%s,%s),m%d)' % (t[4], t[0], t[3], y),
                  '      +%s = rot8(U32.xor(%s,%s))' % (t[5], t[1], t[4]),
                  '      +%s = U32.add(%s,%s)' % (t[6], t[2], t[5]),
                  '      +%s = rot7(U32.xor(%s,%s))' % (t[7], t[3], t[6])]
        cur[a], cur[b], cur[c], cur[d] = t[4], t[7], t[6], t[5]
    lines.append('      T.St{%s}' % ','.join(cur))
    return '\n'.join(lines)


def round_def():
    return '\n\n'.join([
        half_def('column', GS[:4], 0, '# G on the four columns, message words m0..m7.'),
        half_def('diagonal', GS[4:], 8, '# G on the four diagonals, message words m8..m15.'),
        '# One round: the column step then the diagonal step.\n'
        'def round(s: T.St, %s) -> T.St:\n  diagonal(column(s,%s),%s)'
        % (', '.join('+m%d: U32' % i for i in range(16)), ws('m', 8), ','.join('m%d' % i for i in range(8, 16)))])


def compress_def():
    sch = schedules()
    body = 's'
    for r in range(7):
        body = 'round(%s,%s)' % (body, ','.join('m%d' % i for i in sch[r]))
    return '\n'.join([
        '# The initial state: the chaining value, IV[0..3], the counter (low word,',
        '# then the high word, 0: an input has fewer than 2^32 chunks), the block',
        '# length and the flags.',
        'def init(cv: T.CV, +t: U32, +len: U32, +flags: U32) -> T.St:',
        '  match cv:',
        '    case T.CV{%s}:' % ws('h', 8),
        '      T.St{%s,%s,t,0,len,flags}' % (ws('h', 8), ','.join(str(v) for v in IV[:4])),
        '',
        '# Seven rounds; round r takes the message words in the order of the',
        '# permutation applied r times (the fixed BLAKE3 schedule).',
        'def rounds7(s: T.St, b: T.Block) -> T.St:',
        '  match b:',
        '    case T.B{%s}:' % ws('m', 16, True),
        '      %s' % body,
        '',
        '# The compression function (hash mode, 32-byte output): the new chaining',
        '# value is the low half of the final state xor its high half.',
        'def compress(cv: T.CV, b: T.Block, +t: U32, +len: U32, +flags: U32) -> T.CV:',
        '  fold(rounds7(init(cv,t,len,flags),b))',
    ])


COMPRESS_HEAD = '''import Base
import ./types.bend as T

# Generated by tools/generators/blake3/gen.py; do not edit by hand.

def rot16(+x: U32) -> U32:
  U32.or(U32.shrn(x,16n),U32.shln(x,16n))

def rot12(+x: U32) -> U32:
  U32.or(U32.shrn(x,12n),U32.shln(x,20n))

def rot8(+x: U32) -> U32:
  U32.or(U32.shrn(x,8n),U32.shln(x,24n))

def rot7(+x: U32) -> U32:
  U32.or(U32.shrn(x,7n),U32.shln(x,25n))

'''

FOLD = '''def fold(s: T.St) -> T.CV:
  match s:
    case T.St{%s}:
      T.CV{%s}
''' % (ws('v', 16), ','.join('U32.xor(v%d,v%d)' % (i, i + 8) for i in range(8)))


def read_chain():
    out = ['# Reads the 16 words of a block at word `index`, threading the array.']
    out.append('def read15(+index: U32, %s, pair: Array<U32> & U32) -> Array<U32> & T.Block:' % ', '.join('w%d: U32' % i for i in range(15)))
    out.append('  (a,w15) = pair')
    out.append('  (a,T.B{%s})' % ws('w', 16))
    out.append('')
    for k in range(14, -1, -1):
        params = ''.join('w%d: U32, ' % i for i in range(k))
        out.append('def read%d(+index: U32, %spair: Array<U32> & U32) -> Array<U32> & T.Block:' % (k, params))
        out.append('  (a,w%d) = pair' % k)
        args = ''.join('w%d,' % i for i in range(k + 1))
        out.append('  read%d(index,%sArray.get(U32,a,U32.add(index,%d)))' % (k + 1, args, k + 1))
        out.append('')
    out.append('def read_block(a: Array<U32>, +index: U32) -> Array<U32> & T.Block:')
    out.append('  read0(index,Array.get(U32,a,index))')
    return '\n'.join(out)


def main():
    (SRC / 'compress.bend').write_text(COMPRESS_HEAD + round_def() + '\n\n' + FOLD + '\n' + compress_def() + '\n')
    p = SRC / 'blake3.bend'
    text = p.read_text()
    a = text.index('# GENERATED BEGIN')
    b = text.index('# GENERATED END')
    p.write_text(text[:a] + '# GENERATED BEGIN (tools/generators/blake3/gen.py)\n' + read_chain() + '\n' + text[b:])


if __name__ == '__main__':
    main()
