#!/usr/bin/env python3
"""Emit the repetitive BLAKE3 proof modules.

  python3 tools/generators/blake3/proofs.py

Writes proofs/crypto/blake/blake3/compress.bend (the compression function
equals the list specification) and proofs/crypto/blake/blake3/read.bend (the
block-read chain and the zero padding equal the specification's).
"""
from pathlib import Path

ROOT = Path(__file__).resolve().parents[3]
OUT = ROOT / 'proofs/crypto/blake/blake3'
PERM = [2, 6, 3, 10, 7, 0, 4, 13, 1, 11, 12, 5, 9, 14, 15, 8]
L = 'List<&2,U32>'


def names(prefix, idx):
    return ','.join('%s%d' % (prefix, i) for i in idx)


def fors(prefix, idx, plus=True):
    return '\n'.join('  for %s%s%d: U32' % ('+' if plus else '', prefix, i) for i in idx)


M = names('m', range(16))
ML = '[%s]' % M
MP = '[%s]' % ','.join('m%d' % PERM[i] for i in range(16))
M07 = names('m', range(8))
M815 = names('m', range(8, 16))
V = names('v', range(16))


def compress_file():
    out = ['''import Base
import ../../../../src/crypto/blake/blake3/types.bend as T
import ../../../../src/crypto/blake/blake3/compress.bend as C
import ../../../../spec/crypto/blake/blake3.bend as S

# Generated by tools/generators/blake3/proofs.py.
#
# The unrolled compression function equals the list specification, for every
# chaining value, block, counter, length and flags. One round is checked by
# evaluation on a symbolic state; the seven rounds are then composed one step
# of the specification's loop at a time over abstract states, so no check
# evaluates more than one round.

def st_list(s: T.St) -> %s:
  match s:
    case T.St{%s}: [%s]
''' % (L, V, V)]
    out.append('''# One round, by evaluation on a symbolic state.
law round_correct:
  for +s: T.St
%s
  {st_list(C.round(s,%s)) == S.round(st_list(s),%s) : %s}

def round_correct(s,%s):
  match s:
    case T.St{%s}: {==}
''' % (fors('m', range(16)), M, ML, L, M, V))
    out.append('''# One round of the specification's loop, with the permutation applied to the
# message words.
law step:
  for +k: Nat
  for +x: T.St
%s
  {S.rounds(1n+k,st_list(x),%s) == S.rounds(k,st_list(C.round(x,%s)),%s) : %s}

def step(k,x,%s):
  Equal.cong(%s,%s,v => S.rounds(k,v,%s),S.round(st_list(x),%s),st_list(C.round(x,%s)),
    Equal.sym(%s,st_list(C.round(x,%s)),S.round(st_list(x),%s),round_correct(x,%s)))
''' % (fors('m', range(16)), ML, M, MP, L, M, L, L, MP, ML, M, L, M, ML, M))
    # rounds7: the chain of seven steps.
    sch = [list(range(16))]
    for _ in range(7):
        sch.append([sch[-1][PERM[i]] for i in range(16)])
    st = ['s']
    for r in range(7):
        st.append('C.round(%s,%s)' % (st[-1], names('m', sch[r])))
    E = ['S.rounds(%dn,st_list(%s),[%s])' % (7 - r, st[r], names('m', sch[r])) for r in range(8)]
    # prove E0 == E7 by folding: chain(r) : E_r == E_7
    proof = '{==}'
    for r in range(6, -1, -1):
        proof = 'Equal.trans(%s,%s,%s,%s,step(%dn,%s,%s),\n        %s)' % (L, E[r], E[r + 1], E[7], 6 - r, st[r], names('m', sch[r]), proof)
    out.append('''law rounds7_correct:
  for +s: T.St
%s
  {st_list(C.rounds7(s,T.B{%s})) == S.rounds(7n,st_list(s),%s) : %s}

def rounds7_correct(s,%s):
  Equal.sym(%s,%s,st_list(%s),
    %s)
''' % (fors('m', range(16)), M, ML, L, M, L, E[0], st[7], proof))
    out.append('''law fold_correct:
  for +s: T.St
  {C.fold(s) == S.output(st_list(s)) : T.CV}

def fold_correct(s):
  match s:
    case T.St{%s}: {==}

law init_correct:
  for +c: T.CV
  for +t: U32
  for +len: U32
  for +flags: U32
  {st_list(C.init(c,t,len,flags)) == S.init(c,t,len,flags) : %s}

def init_correct(c,t,len,flags):
  match c:
    case T.CV{h0,h1,h2,h3,h4,h5,h6,h7}: {==}

law compress_correct:
  for +c: T.CV
  for +b: T.Block
  for +t: U32
  for +len: U32
  for +flags: U32
  {C.compress(c,b,t,len,flags) == S.compress(c,b,t,len,flags) : T.CV}

def compress_correct(c,b,t,len,flags):
  match b:
    case T.B{%s}:
      Equal.trans(T.CV,
        C.fold(C.rounds7(C.init(c,t,len,flags),T.B{%s})),
        S.output(st_list(C.rounds7(C.init(c,t,len,flags),T.B{%s}))),
        S.output(S.rounds(7n,S.init(c,t,len,flags),%s)),
        fold_correct(C.rounds7(C.init(c,t,len,flags),T.B{%s})),
        Equal.trans(T.CV,
          S.output(st_list(C.rounds7(C.init(c,t,len,flags),T.B{%s}))),
          S.output(S.rounds(7n,st_list(C.init(c,t,len,flags)),%s)),
          S.output(S.rounds(7n,S.init(c,t,len,flags),%s)),
          Equal.cong(%s,T.CV,v => S.output(v),st_list(C.rounds7(C.init(c,t,len,flags),T.B{%s})),S.rounds(7n,st_list(C.init(c,t,len,flags)),%s),rounds7_correct(C.init(c,t,len,flags),%s)),
          Equal.cong(%s,T.CV,v => S.output(S.rounds(7n,v,%s)),st_list(C.init(c,t,len,flags)),S.init(c,t,len,flags),init_correct(c,t,len,flags))))
''' % (V, L, M, M, M, ML, M, M, ML, ML, L, M, ML, M, L, ML))
    (OUT / 'compress.bend').write_text('\n'.join(out))


READ_HEAD = '''import Base
import ../../../../src/crypto/blake/blake3/types.bend as T
import ../../../../src/crypto/blake/blake3/blake3.bend as K
import ../../../../spec/crypto/blake/blake3.bend as S

# Generated by tools/generators/blake3/proofs.py.
#
# The implementation's unrolled block read (read0..read15) equals the
# specification's word-gathering loop, step by step, for every array and index;
# the implementation's final-block mask equals the specification's zero
# padding, for every block and length.
'''

READ_TAIL = '''law read_block_correct:
  for a: Array<U32>
  for +index: U32
  {K.read_block(a,index) == S.read_block(a,index) : Array<U32> & T.Block}

def read_block_correct(a,index):
  read0_correct(index,Array.get(U32,a,index))

law partial_low:
  for +w: U32
  for +d: Nat
  {K.partial(w,d) == S.low_bytes(w,Nat.min(4n,d)) : U32}

def partial_low(w,d):
  match d:
    case 0n: {==}
    case 1n: {==}
    case 2n: {==}
    case 3n: {==}
    case 4n+q: {==}

law mask_keep:
  for +w: U32
  for +pos: Nat
  for +len: Nat
  {K.mask(w,pos,len) == S.keep(w,pos,len) : U32}

def mask_keep(w,pos,len):
  partial_low(w,Nat.sub(len,pos))
'''


def read_file():
    out = [READ_HEAD]
    for k in range(15, -1, -1):
        acc = '[%s]' % ','.join('w%d' % i for i in range(k - 1, -1, -1)) if k else 'Nil{}'
        params = ''.join('w%d,' % i for i in range(k))
        stmt = '{K.read%d(index,%spair) == S.as_block(S.gather(%dn,index,%d,%s,pair)) : Array<U32> & T.Block}' % (
            k, params, 15 - k, k + 1, acc)
        if k == 15:
            body = '  (a,w15) = pair\n  {==}'
        else:
            body = '  (a,w%d) = pair\n  read%d_correct(index,%sw%d,Array.get(U32,a,U32.add(index,%d)))' % (
                k, k + 1, params, k, k + 1)
        out.append('law read%d_correct:\n  for +index: U32\n%s%s  for pair: Array<U32> & U32\n  %s\n\ndef read%d_correct(index,%spair):\n%s\n' % (
            k, fors('w', range(k)), '\n' if k else '', stmt, k, params, body))
    out.append(READ_TAIL)
    lhs = 'T.B{%s}' % ','.join('K.mask(m%d,%dn,len)' % (i, 4 * i) for i in range(16))
    lines = []
    for i in range(16):
        rhs = ','.join(('K.mask(m%d,%dn,len)' % (j, 4 * j)) if j < i else
                       ('_' if j == i else 'S.keep(m%d,%dn,len)' % (j, 4 * j)) for j in range(16))
        lines.append('      %%mask_keep(m%d,%dn,len) : {%s == T.B{%s} : T.Block}' % (i, 4 * i, lhs, rhs))
    out.append('''law mask_block_correct:
  for +b: T.Block
  for +len: Nat
  {K.mask_block(b,len) == S.zero_tail(b,len) : T.Block}

def mask_block_correct(b,len):
  match b:
    case T.B{%s}:
%s
      {==}

# A full block keeps all 64 bytes.
law zero_tail_full:
  for +b: T.Block
  {S.zero_tail(b,64n) == b : T.Block}

def zero_tail_full(b):
  match b:
    case T.B{%s}: {==}
''' % (M, '\n'.join(lines), M))
    (OUT / 'read.bend').write_text('\n'.join(out))


if __name__ == '__main__':
    compress_file()
    read_file()
