#!/usr/bin/env python3
"""Emit tests/crypto/blake/blake3/main.bend with expected digests computed by
the official BLAKE3 C reference (benchmarks/native/blake/, portable build).

  python3 tools/generators/blake3/tests.py
"""
import subprocess, tempfile
from pathlib import Path

ROOT = Path(__file__).resolve().parents[3]
NATIVE = ROOT / 'benchmarks/native/blake'
FLAGS = ['-DBLAKE3_NO_SSE2', '-DBLAKE3_NO_SSE41', '-DBLAKE3_NO_AVX2', '-DBLAKE3_NO_AVX512', '-DBLAKE3_USE_NEON=0']

# Official test_vectors.json input lengths (input byte i = i % 251).
OFFICIAL = [0, 1, 1023, 1024, 1025, 2048, 2049, 3072, 3073, 4096, 4097, 5120, 5121, 6144, 6145,
            7168, 7169, 8192, 8193, 16384, 31744, 102400]
# Boundary lengths over packed pseudo-random words (w_i = i*2654435761 + seed).
LENGTHS = [0, 1, 2, 3, 4, 5, 63, 64, 65, 127, 128, 129, 1023, 1024, 1025, 2047, 2048, 2049, 3072,
           3073, 4095, 4096, 4097, 5121, 8192, 8193, 16385, 32769]


def depth(n):
    return max(0, (((n + 3) // 4) - 1).bit_length())


def main():
    with tempfile.TemporaryDirectory() as d:
        exe = Path(d) / 'vec'
        subprocess.run(['cc', '-O2'] + FLAGS + ['-I', str(NATIVE), '-o', str(exe),
                        str(ROOT / 'tools/generators/blake3/vectors.c'),
                        str(NATIVE / 'blake3.c'), str(NATIVE / 'blake3_dispatch.c'),
                        str(NATIVE / 'blake3_portable.c')], check=True)
        dig = lambda *a: subprocess.run([str(exe)] + [str(x) for x in a], capture_output=True,
                                        text=True, check=True).stdout.strip()
        rows = []
        for n in OFFICIAL:
            rows.append(('    official(%dn,%dn,"%s")' % (n, depth(n), dig(0, n)), n))
        for n in LENGTHS:
            seed = (n * 7 + 13) % 1000
            rows.append(('    packed(%dn,%d,%dn,"%s")' % (n, seed, depth(n), dig(1, n, seed)), n))
            # One extra power of two of capacity: the words past the message differ.
            rows.append(('    packed(%dn,%d,%dn,"%s")' % (n, seed, depth(n) + 1, dig(1, n, seed)), n))
        head = HEAD.replace('"%s"', '"%s"' % dig(1, 32, 5))
    (ROOT / 'tests/crypto/blake/blake3/main.bend').write_text(head + '\n'.join(r for r, n in rows) + '\n' + TAIL)
    # The executable specification on the same vectors (at most 40 chunks: its
    # tree uses 2^(chunk count) as a height bound, a native Nat below 2^48).
    spec = head.replace('import ../../../../src/crypto/blake/blake3/blake3.bend as K',
                        'import ../../../../spec/crypto/blake/blake3.bend as K')
    spec = spec.replace('# Generated by tools/generators/blake3/tests.py.',
                        '# The executable specification (spec/crypto/blake/blake3.bend) on the\n# vectors of main.bend. Generated by tools/generators/blake3/tests.py.')
    spec = spec.replace('"blake3: all cases passed"', '"blake3 spec: all cases passed"')
    (ROOT / 'tests/crypto/blake/blake3/spec.bend').write_text(
        spec + '\n'.join(r for r, n in rows if n <= 40 * 1024) + '\n' + TAIL.replace('blake3:', 'blake3 spec:'))


HEAD = '''import Base
import ../../../../src/crypto/blake/blake3/blake3.bend as K
import ../../../../src/crypto/blake/blake3/hex.bend as H

# Generated by tools/generators/blake3/tests.py. Expected digests come from the
# official BLAKE3 C reference (benchmarks/native/blake/, portable build).
# Prints one line per case and "blake3: all cases passed" at the end; exits
# with status 1 on the first mismatch.

# Word i = i * 2654435761 + seed for every slot of the array.
def fill(n: Nat, +i: U32, +seed: U32, a: Array<U32>) -> Array<U32>:
  match n:
    case 0n: a
    case 1n+p: fill(p,U32.inc(i),seed,Array.set(U32,a,i,U32.add(U32.mul(i,2654435761),seed)))

# The official input: byte k = k mod 251, packed little-endian.
def byte(+k: Nat) -> U32:
  U32.from_nat(Nat.mod(k,251n))

def official_word(+j: Nat) -> U32:
  +k = Nat.mul(4n,j)
  U32.or(U32.or(byte(k),U32.shln(byte(Nat.add(k,1n)),8n)),U32.or(U32.shln(byte(Nat.add(k,2n)),16n),U32.shln(byte(Nat.add(k,3n)),24n)))

def fill_official(n: Nat, +j: Nat, a: Array<U32>) -> Array<U32>:
  match n:
    case 0n: a
    case 1n+p: fill_official(p,1n+j,Array.set(U32,a,U32.from_nat(j),official_word(j)))

def show(r: Maybe<&1,Array<U32>>) -> String:
  match r:
    case None{}: "invalid"
    case Some{a}: H.hex(a)

def verdict(name: String, got: String, want: String, ok: Bool) -> IO(Unit):
  match ok:
    case True{}: IO.print("ok   " ++ name)
    case False{}:
      IO.die(Unit,1,"FAIL " ++ name ++ " got " ++ got ++ " want " ++ want)

def check(name: String, +got: String, +want: String) -> IO(Unit):
  verdict(name,got,want,String.eq(got,want))

def official(+n: Nat, +depth: Nat, want: String) -> IO(Unit):
  a = fill_official(Nat.pow(2n,depth),0n,Array.new(U32,depth,0))
  check("official len=" ++ Nat.show(n),show(K.blake3(a,n)),want)

def packed(+n: Nat, +seed: U32, +depth: Nat, want: String) -> IO(Unit):
  a = fill(Nat.pow(2n,depth),0,seed,Array.new(U32,depth,0))
  check("packed len=" ++ Nat.show(n) ++ " depth=" ++ Nat.show(depth),show(K.blake3(a,n)),want)

# byte_length past 4 * capacity is rejected; exactly 4 * capacity is accepted.
def bounds() -> IO(Unit):
  do IO<Unit>:
    check("reject len=33 cap=8",show(K.blake3(fill(8n,0,5,Array.new(U32,3n,0)),33n)),"invalid")
    check("reject len=5 cap=1",show(K.blake3(fill(1n,0,5,Array.new(U32,0n,0)),5n)),"invalid")
    check("accept len=32 cap=8",show(K.blake3(fill(8n,0,5,Array.new(U32,3n,0)),32n)),"%s")

def main() -> IO(Unit):
  do IO<Unit>:
    bounds()
'''

TAIL = '''    IO.print("blake3: all cases passed")
'''

if __name__ == '__main__':
    main()
