"""Semantic mutants for tools/validate.py.

Each entry is (label, file, search, replace). The search text must occur
exactly once in the named source file; the replacement must keep the program
type-correct so that the mutant compiles and runs. A mutant only counts as
rejected when the mutated binary builds, runs to completion and then prints an
answer that differs from the independent oracle: a compile error or a crash is
recorded as a failure of the mutation test, never as a detection.
"""

MUTANTS = {
    'dynamic_array': [
        ('get reads the next slot', 'src/dynamic_array.bend',
         'get_checked_at(~T, limit, depth, cap, len, arr, i, Nat.is_lt(i, len))',
         'get_checked_at(~T, limit, depth, cap, len, arr, 1n+i, Nat.is_lt(i, len))'),
        ('push ignores the capacity limit', 'src/dynamic_array.bend',
         'push_room_at(~T, limit, depth, cap, len, arr, v, Nat.is_lt(len, cap), Nat.is_lt(depth, limit))',
         'push_room_at(~T, limit, depth, cap, len, arr, v, Nat.is_lt(len, cap), Nat.is_lt(depth, 1n+limit))'),
        ('clear drops the capacity', 'src/dynamic_array.bend',
         '  DA{limit, depth, cap, 0n, empty_slots_at(~T, depth)}',
         '  DA{limit, 0n, 1n, 0n, empty_slots_at(~T, 0n)}'),
        ('set writes at the next index', 'src/dynamic_array.bend',
         'set_checked_at(~T, limit, depth, cap, len, arr, i, v, Nat.is_lt(i, len))',
         'set_checked_at(~T, limit, depth, cap, len, arr, 1n+i, v, Nat.is_lt(i, len))'),
        ('push does not grow the cached capacity', 'src/dynamic_array.bend',
         '      (DA{limit, 1n+depth, Nat.double(cap), 1n+len, Array.set(Maybe<&2, T>, grown_at(~T, depth, arr), U32.from_nat(len), Some{v})}, Done{Unit{}})',
         '      (DA{limit, 1n+depth, cap, 1n+len, Array.set(Maybe<&2, T>, grown_at(~T, depth, arr), U32.from_nat(len), Some{v})}, Done{Unit{}})'),
    ],
    'deque': [
        ('push_back writes the ring offset slot', 'src/deque.bend',
         '      DQ{dep, cap, lo, 1n+len, Array.set(T, a, U32.from_nat(wrap(Nat.add(lo, len), cap)), v)}',
         '      DQ{dep, cap, lo, 1n+len, Array.set(T, a, U32.from_nat(lo), v)}'),
        ('push_front keeps the ring offset', 'src/deque.bend',
         '      DQ{dep, cap, k, 1n+len, Array.set(T, a, U32.from_nat(k), v)}',
         '      DQ{dep, cap, 1n+k, 1n+len, Array.set(T, a, U32.from_nat(k), v)}'),
        ('growing keeps the old offset', 'src/deque.bend',
         '      DQ{1n+dep, Nat.double(cap), 0n, 1n+len, Array.set(T, grow(~T, dep, cap, lo, len, a, v), U32.from_nat(len), v)}',
         '      DQ{1n+dep, Nat.double(cap), lo, 1n+len, Array.set(T, grow(~T, dep, cap, lo, len, a, v), U32.from_nat(len), v)}'),
        ('pop_back takes the front slot', 'src/deque.bend',
         '      popb_fin(~T, dep, cap, lo, m, Array.get(T, a, U32.from_nat(wrap(Nat.add(lo, m), cap))))',
         '      popb_fin(~T, dep, cap, lo, m, Array.get(T, a, U32.from_nat(lo)))'),
        ('peek_back reads the front slot', 'src/deque.bend',
         '      peek_fin(~T, dep, cap, lo, 1n+m, Array.get(T, a, U32.from_nat(wrap(Nat.add(lo, m), cap))))',
         '      peek_fin(~T, dep, cap, lo, 1n+m, Array.get(T, a, U32.from_nat(lo)))'),
        ('to_list reads one ring position too far', 'src/deque.bend',
         '      tl_go(~T, p, lo, cap, Con{x, acc}, Array.get(T, a, U32.from_nat(wrap(Nat.add(lo, p), cap))))',
         '      tl_go(~T, p, lo, cap, Con{x, acc}, Array.get(T, a, U32.from_nat(wrap(Nat.add(lo, 1n+p), cap))))'),
        ('pop_front does not move the offset', 'src/deque.bend',
         '  (DQ{dep, cap, wrap(1n+lo, cap), m, a}, Done{x})',
         '  (DQ{dep, cap, lo, m, a}, Done{x})'),
        ('growth copies the ring from slot 0', 'src/deque.bend',
         '  copy_go(~T, len, 0n, lo, cap, Array.new(T, 1n+dep, v), Array.get(T, a, U32.from_nat(wrap(Nat.add(lo, 0n), cap))))',
         '  copy_go(~T, len, 0n, 0n, cap, Array.new(T, 1n+dep, v), Array.get(T, a, U32.from_nat(wrap(Nat.add(0n, 0n), cap))))'),
    ],
    'queue': [
        ('enqueue pushes at the front', 'src/queue.bend',
         '  QU{DQ.push_back(~T, d, x)}',
         '  QU{DQ.push_front(~T, d, x)}'),
        ('dequeue takes from the back', 'src/queue.bend',
         '  lift(~T, DQ.pop_front(~T, d))',
         '  lift(~T, DQ.pop_back(~T, d))'),
        ('peek looks at the back', 'src/queue.bend',
         '  lift(~T, DQ.peek_front(~T, d))',
         '  lift(~T, DQ.peek_back(~T, d))'),
        ('dequeue does not remove', 'src/queue.bend',
         '      obs_item(~T, dequeue(~T, q))',
         '      obs_item(~T, peek(~T, q))'),
    ],
    'doubly_linked_list': [
        ('push_front appends instead', 'src/doubly_linked_list.bend',
         'insert_between(~T, tag, fresh, count, head, tail, depth, cap, vals, prevs, nexts, nil(), head, x)',
         'insert_between(~T, tag, fresh, count, head, tail, depth, cap, vals, prevs, nexts, tail, nil(), x)'),
        ('insert_before inserts after', 'src/doubly_linked_list.bend',
         '      done_handle(~T, insert_between(~T, tag, fresh, count, head, tail, depth, cap, vals, prevs, nexts, p, link(i), x))',
         '      done_handle(~T, insert_between(~T, tag, fresh, count, head, tail, depth, cap, vals, prevs, nexts, link(i), n, x))'),
        ('prev and next links are swapped on insertion', 'src/doubly_linked_list.bend',
         '      set_next(Array.set(U32, prevs, n, a), b, link(n)),\n      set_next(Array.set(U32, nexts, n, b), a, link(n))}, E.H{tag, n})',
         '      set_next(Array.set(U32, prevs, n, b), a, link(n)),\n      set_next(Array.set(U32, nexts, n, a), b, link(n))}, E.H{tag, n})'),
        ('handle ids are reused', 'src/doubly_linked_list.bend',
         '  (DL{tag, U32.inc(n), 1n+count,',
         '  (DL{tag, n, 1n+count,'),
        ('foreign handles are accepted', 'src/doubly_linked_list.bend',
         '  get_checked(~T, U32.is_lt(i, fresh), tag, fresh, count, head, tail, depth, cap, vals, prevs, nexts, i, U32.is_eq(l, tag))',
         '  get_checked(~T, U32.is_lt(i, fresh), tag, fresh, count, head, tail, depth, cap, vals, prevs, nexts, i, True{})'),
        ('removal does not relink the neighbours', 'src/doubly_linked_list.bend',
         '      vals, set_next(prevs, n, p), set_next(nexts, p, n)}, Done{v})',
         '      vals, prevs, nexts}, Done{v})'),
    ],
    'binary_heap': [
        ('comparator reversed', 'src/binary_heap.bend',
         '  Cmp.is_le(cmp(x, y))',
         '  Bool.not(Cmp.is_le(cmp(x, y)))'),
        ('peek does not report the minimum', 'src/binary_heap.bend',
         '    case E.Peek{}:\n      obs_item(~A, peek(~A, h))',
         '    case E.Peek{}:\n      obs_item(~A, pop(~A, ~cmp, h))'),
        ('sift-down takes the larger child', 'src/binary_heap.bend',
         '  match left:\n    case True{}:\n      down_dec(~A, arr, i, lv, l, le(~A, ~cmp, x, lv))\n    case False{}:\n      down_dec(~A, arr, i, rv, r, le(~A, ~cmp, x, rv))',
         '  match left:\n    case True{}:\n      down_dec(~A, arr, i, rv, r, le(~A, ~cmp, x, rv))\n    case False{}:\n      down_dec(~A, arr, i, lv, l, le(~A, ~cmp, x, lv))'),
        ('pop does not sift the moved element down', 'src/binary_heap.bend',
         '    case False{}:\n      (BH{size, m, depth, cap, sift_down(~A, ~cmp, depth, m, 0, last, arr)}, Done{root})',
         '    case False{}:\n      (BH{size, m, depth, cap, Array.set(Maybe<&2, A>, arr, 0, Some{last})}, Done{root})'),
        ('a full block is not doubled', 'src/binary_heap.bend',
         '    case False{}:\n      BH{1n+size, U32.inc(n), 1n+depth, U32.shl(cap), sift_up(~A, ~cmp, 1n+depth, n, x, grown(~A, depth, arr))}',
         '    case False{}:\n      BH{1n+size, U32.inc(n), depth, cap, sift_up(~A, ~cmp, depth, n, x, arr)}'),
        ('push drops the element', 'src/binary_heap.bend',
         '    case E.Push{x}:\n      (push(~A, ~cmp, h, x), E.OUnit{})',
         '    case E.Push{x}:\n      (h, E.OUnit{})'),
    ],
    'balanced_search_tree': [
        ('range becomes inclusive at the top', 'src/balanced_search_tree.bend',
         '  Bool.and(Bool.not(Cmp.is_gt(cmp(lo, k))), Cmp.is_lt(cmp(k, hi)))',
         '  Bool.and(Bool.not(Cmp.is_gt(cmp(lo, k))), Bool.not(Cmp.is_gt(cmp(k, hi))))'),
        ('min returns the maximum', 'src/balanced_search_tree.bend',
         '      (s, E.OEntry{min(K, V, s)})',
         '      (s, E.OEntry{max(K, V, s)})'),
        ('contains is negated', 'src/balanced_search_tree.bend',
         '      (s, E.OBool{contains(~K, ~cmp, V, s, k)})',
         '      (s, E.OBool{Bool.not(contains(~K, ~cmp, V, s, k))})'),
        ('lower_bound skips an equal key', 'src/balanced_search_tree.bend',
         '      (s, E.OEntry{lower_bound(~K, ~cmp, V, s, k)})',
         '      (s, E.OEntry{min(K, V, s)})'),
    ],
    'bitset': [
        ('difference becomes intersection', 'src/bitset.bend',
         '    case KDiff{}:\n      U32.and(a, U32.not(b))',
         '    case KDiff{}:\n      U32.and(a, b)'),
        ('xor becomes or', 'src/bitset.bend',
         '    case KXor{}:\n      U32.xor(a, b)',
         '    case KXor{}:\n      U32.or(a, b)'),
        ('length mismatch is accepted instead of rejected', 'src/bitset.bend',
         '      (BS{n, d, a}, Fail{E.LengthMismatch{}})',
         '      (BS{n, d, a}, Done{Unit{}})'),
        ('an out-of-range index is not rejected', 'src/bitset.bend',
         '      get_if(Nat.is_lt(i, n), n, d, a, i)',
         '      get_if(True{}, n, d, a, i)'),
        ('set and clear are swapped', 'src/bitset.bend',
         '      assign_read(read(a, d, wordix(i)), n, d, wordix(i), bitix(i), v)',
         '      assign_read(read(a, d, wordix(i)), n, d, wordix(i), bitix(i), Bool.not(v))'),
        ('the bit index inside the word is dropped', 'src/bitset.bend',
         'def bitix(i: Nat) -> Nat:\n  Nat.mod(i, 32n)',
         'def bitix(i: Nat) -> Nat:\n  0n'),
        ('a whole-array combine stops one word short', 'src/bitset.bend',
         '      zip_fin(zip_go(pow2(d), (a, b), k, d, 0n), n, d, m, e)',
         '      zip_fin(zip_go(Nat.sub(pow2(d), 1n), (a, b), k, d, 0n), n, d, m, e)'),
    ],
    'union_find': [
        ('union-by-size tie-break flipped', 'src/union_find.bend',
         'union_pick(Nat.is_le(zb, za), n, d, r, z, m, c, ra, rb, Nat.add(za, zb))',
         'union_pick(Nat.is_lt(zb, za), n, d, r, z, m, c, ra, rb, Nat.add(za, zb))'),
        ('component count is not decremented', 'src/union_find.bend',
         'write_ms(m, d, big, List.append(&2, Nat, mss, msb)), Nat.sub(c, 1n)}',
         'write_ms(m, d, big, List.append(&2, Nat, mss, msb)), c}'),
        ('merging an existing class reports a change', 'src/union_find.bend',
         '      (UF{n, d, r, z, m, c}, Done{False{}})',
         '      (UF{n, d, r, z, m, c}, Done{True{}})'),
        ('the merged size arena keeps the big class size', 'src/union_find.bend',
         'write_nat(z, d, big, tot)',
         'write_nat(z, d, big, Nat.sub(tot, 1n))'),
        ('relink skips the first member of the small class', 'src/union_find.bend',
         '    case Con{+q, rest}:\n      relink(rest, write_nat(r, d, q, big), d, big)',
         '    case Con{+q, rest}:\n      relink(rest, r, d, big)'),
        ('the merged member list drops the small class', 'src/union_find.bend',
         'write_ms(m, d, big, List.append(&2, Nat, mss, msb))',
         'write_ms(m, d, big, msb)'),
        ('component_size reads slot 0 of the size arena', 'src/union_find.bend',
         '  size_root(read_nat(z, d, v), n, d, r, m, c)',
         '  size_root(read_nat(z, d, 0n), n, d, r, m, c)'),
    ],
    'fenwick_tree': [
        ('point update subtracts', 'src/fenwick_tree.bend',
         '  bump_fin(read(a, k), k, v)',
         '  bump_fin(read(a, k), k, U32.sub(0, v))'),
        ('prefix bound off by one', 'src/fenwick_tree.bend',
         '      prefix_if(Nat.is_le(e, n), n, d, b, a, e)',
         '      prefix_if(Nat.is_lt(e, n), n, d, b, a, e)'),
        ('range endpoints swapped', 'src/fenwick_tree.bend',
         '  (FT{n, d, b, a}, Done{U32.sub(hi, lo)})',
         '  (FT{n, d, b, a}, Done{U32.sub(lo, hi)})'),
        ('a left turn does not update the split cell', 'src/fenwick_tree.bend',
         '      add_go(q, bump(a, Nat.add(o, h), v), base, hh, Nat.div(hh, 2n), o, i, v, Nat.is_lt(i, hh))',
         '      add_go(q, a, base, hh, Nat.div(hh, 2n), o, i, v, Nat.is_lt(i, hh))'),
        ('a right turn adds the split cell it should skip', 'src/fenwick_tree.bend',
         '      add_go(q, a, base, hh, Nat.div(hh, 2n), Nat.add(o, h), Nat.sub(i, h), v, Nat.is_lt(Nat.sub(i, h), hh))',
         '      add_go(q, bump(a, Nat.add(o, h), v), base, hh, Nat.div(hh, 2n), Nat.add(o, h), Nat.sub(i, h), v, Nat.is_lt(Nat.sub(i, h), hh))'),
        ('the prefix walk skips the stored left sums', 'src/fenwick_tree.bend',
         'Nat.div(hh, 2n), U32.add(acc, cval(x)), Nat.add(o, h)',
         'Nat.div(hh, 2n), acc, Nat.add(o, h)'),
        ('the leaf of a prefix walk is always counted', 'src/fenwick_tree.bend',
         '''    case 0n:
      0
    case 1n+j:
      x''',
         '''    case 0n:
      x
    case 1n+j:
      x'''),
    ],
    'segment_tree': [
        ('lazy range add is not closed off', 'src/segment_tree.bend',
         '  set_done(padd(d, c, g, b, l, U32.sub(0, v)), n, d, b)',
         '  set_done(padd(d, c, g, b, l, v), n, d, b)'),
        ('range query accepts one past the end', 'src/segment_tree.bend',
         '      query_if(Bool.and(Nat.is_le(l, r), Nat.is_le(r, n)), n, d, b, c, g, l, r)',
         '      query_if(Bool.and(Nat.is_le(l, r), Nat.is_le(r, 1n+n)), n, d, b, c, g, l, r)'),
        ('point assignment ignores the pending lazy tags', 'src/segment_tree.bend',
         '      (write(c, Nat.add(base, o), U32.sub(v, acc)), g)',
         '      (write(c, Nat.add(base, o), v), g)'),
        ('get ignores accumulated lazy tags', 'src/segment_tree.bend',
         '      (c, (g, U32.add(cval(x), acc)))',
         '      (c, (g, cval(x)))'),
        ('a left turn of set does not recompute the block sum', 'src/segment_tree.bend',
         '      fix(set_go(q, pre_t(q, c, g, base, hh, o), base, hh, Nat.div(hh, 2n), U32.add(acc, cval(x)), o, i, v, Nat.is_lt(i, hh)), base, h, hh, o, q)',
         '      set_go(q, pre_t(q, c, g, base, hh, o), base, hh, Nat.div(hh, 2n), U32.add(acc, cval(x)), o, i, v, Nat.is_lt(i, hh))'),
        ('a tagged block raises its stored sum by one unit only', 'src/segment_tree.bend',
         '      bump(c, Nat.add(o, hq), U32.shln(v, 1n+r))',
         '      bump(c, Nat.add(o, hq), v)'),
        ('the prefix walk ignores the tags above a skipped block', 'src/segment_tree.bend',
         'U32.add(sum, U32.add(cval(tot), U32.shln(U32.add(acc, cval(z)), q)))',
         'U32.add(sum, U32.add(cval(tot), U32.shln(U32.add(acc, cval(z)), 1n+q)))'),
        ('a leaf prefix always counts its value', 'src/segment_tree.bend',
         '''def leaf_prefix(x: U32, i: Nat) -> U32:
  match i:
    case 0n:
      0
    case 1n+j:
      x''',
         '''def leaf_prefix(x: U32, i: Nat) -> U32:
  match i:
    case 0n:
      x
    case 1n+j:
      x'''),
    ],
    'prefix_trie': [
        ('longest_prefix returns the shortest', 'src/prefix_trie.bend',
         '      shift(V, c, orM(V, lp(V, down, y, hc(V, y, down), r), here(V, val)))',
         '      shift(V, c, orM(V, here(V, val), lp(V, down, y, hc(V, y, down), r)))'),
        ('prefix_entries drops the exact match', 'src/prefix_trie.bend',
         '      mapc(V, c, SC.append(BE.Entry<String, V>, opt(V, SNil{}, val), ent(V, down)))',
         '      mapc(V, c, ent(V, down))'),
        ('contains is negated', 'src/prefix_trie.bend',
         '      (s, E.OBool{contains(V, s, k)})',
         '      (s, E.OBool{Bool.not(contains(V, s, k))})'),
        ('remove keeps the value', 'src/prefix_trie.bend',
         '    case E.Remove{k}:\n      obs_val(V, remove(V, s, k))',
         '    case E.Remove{k}:\n      (s, E.OVal{lookup(V, s, k)})'),
    ],
    'graph': [
        ('self-loops are accepted', 'src/graph.bend',
         '      ae_loop(dir, lo, hi, cap, depth, ids, adj, iu, iv, u, v, U32.is_eq(u, v))',
         '      ae_loop(dir, lo, hi, cap, depth, ids, adj, iu, iv, u, v, False{})'),
        ('undirected edges are stored at one endpoint only', 'src/graph.bend',
         '      add_nbr(add_nbr(adj, iu, v), iv, u)',
         '      add_nbr(adj, iu, v)'),
        ('undirected removal is one way', 'src/graph.bend',
         '      del_nbr_fin(del_nbr(adj, iv, u))',
         '      adj'),
        ('has_vertex is negated', 'src/graph.bend',
         '  (G{dir, lo, hi, cap, depth, ids, adj}, found)',
         '  (G{dir, lo, hi, cap, depth, ids, adj}, Bool.not(found))'),
        ('a new vertex keeps the neighbours of the slot it takes', 'src/graph.bend',
         '     Array.set(Array<U32>, shra_go(U32.to_nat(U32.sub(hi, i)), hi, adj), i, empty_blk())},',
         '     shra_go(U32.to_nat(U32.sub(hi, i)), hi, adj)},'),
        ('the adjacency block is not kept sorted', 'src/graph.bend',
         '      blk_put(b, deg, q, w)',
         '      blk_put(b, deg, ent_end(deg), w)'),
    ],
}
